<?php
  /******************************************************************
   delete.phtml					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by: edit.phtml
   Arguments: none
   Grant needed: delete
   Interface/Widget: all
   Global variables: none

   This template deletes the current object.

  ******************************************************************/

/* page is not saved on disk yet, if ever
  if ($this->CheckLogin("delete")) {
    if (file_exists($this->store->files."/files".$data->path.$data->name)) {
      unlink($this->store->files."/files".$data->path.$data->name);
    }
  }
*/
  include($this->store->code."includes/delete.object.phtml");
?>