<?php
    if ($this->CheckSilent('edit')) {
?>
<html>
<head>
	<style>
		.editable {
			border: 1px dotted #999999;
		}
	</style>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->make_url(); ?>style.css">
</head>
<body>
<?php
        include($this->store->get_config('code').'modules/mod_edit.php');
		edit::setEditMode(true);
        edit::showDiv($this->GetPage(), "[$nls][page]");
?>
</body>
</html>
<?php
    }
?>