<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="data">
		<legend><?php echo $ARnls["data"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<span class="required"><?php echo $ARnls["name"]; ?></span>
				</td><td align="right">
					<?php echo $flag; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<input type="text" name="<?php echo $selectednls."[name]"; ?>"
						value="<?php $this->showdata("name", $selectednls); ?>">
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["summary"]; ?>
				</td><td align="right">
					<?php echo $flag; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<textarea name="<?php echo $selectednls."[summary]"; ?>" cols="30" rows="4" wrap="soft"><?php 
							echo ereg_replace("&","&amp;",$this->getdata("summary", $selectednls)); 
					?></textarea>
				</td>
			<?php
				//if (!$this->arIsNewObject) {
					echo "</tr><tr><td>";
					$wgHTMLEditName="page";
					$wgHTMLEditLanguage=$arLanguage;
					$wgHTMLEditContent=$this->ParsePage($this->getdata("page",$arLanguage), true, true);
					include($this->store->code."widgets/htmledit/js.html"); 
					include($this->store->code."widgets/htmledit/form.html"); 
					echo "</td><td align=\"right\">$flag</td>";
				//}
			?>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["<?php echo $selectednls; ?>[name]"].focus();
	}
</script>
<?php
		if ($selectednls==$ARConfig->nls->default) {
			$arResult["save"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["save"][$selectednls."[name]"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
			$arResult["next"]=$arResult["save"];
		} else {
			$arResult["next"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["next"][$selectednls."[name]"]["confirm"]=sprintf($ARnls["confirm:nonameentered"],$selectedlanguage);
			if ($this->getdata("name",$ARConfig->nls->default)) {
				$arResult["save"]=$arResult["next"];
			} else {
				$arResult["save"]=false;
			}
		}
	}
?>