<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) &&
			$this->CheckConfig()) {

				$nls=$ARConfig->nls->default;

		$tempfile = $this->getdata("file_temp", "none");
		$tempfile = $this->store->get_config("files")."temp/$tempfile";
		debug("opening page ($tempfile)");
		$fp = @fopen($tempfile, "r");
		if (!$fp) {
			debug("could not open tempfile containing page");
			$this->error = sprintf($ARnls["err:couldnotopen"],$tempfile);
		} else {
			$page = "";
			while (!feof($fp)) {
				$page .= fgets($fp, 4096);
			}
			fclose($fp);



			/* rewrite relative img src's to abs. Ariadne paths */
			$scanpage = $page;
			$reg = '/(<[^<]*img.*src.*=.*["]([^"]*)["][^>]*>)(.*)$/isU';
			while (preg_match($reg, $scanpage, $matches)) {
				if ($matches[2]) {
					$imgtag = $matches[1];
					$imgpath = $matches[2];
					if ($imgpath && !preg_match('%^[[:space:]]*(http://|/)%i', $imgpath)) {
						$newimgpath = $this->store->make_path($this->parent, $imgpath);
						$newimgpath = substr($newimgpath, 0, -1);	
						$newimgtag = str_replace($imgpath, "{arRoot}$newimgpath", $imgtag);
						$page = str_replace($imgtag, $newimgtag, $page);
					}
				}
				$scanpage = $matches[3];
			}

			$page=utf8_encode($page);

			$arCheckCharSet=$nls;
			if (!$AR->nls->charsets[$arCheckCharSet]) {
				$arCheckCharSet="default";
			}
			require_once($this->store->get_config("code")."modules/mod_unicode.php");
			if ($AR->nls->charsets[$arCheckCharSet] == "ISO-8859-1") {
				$page=unicode::utf8toiso8859($page);
				// now change special characters to their html entity
				// $page=htmlentities($page);
				// now change '<', '>', '"', '~' and '&' back.
				$page=str_replace("&lt;","<",$page);
				$page=str_replace("&gt;",">",$page);
				$page=str_replace("&quot;","\"",$page);
				$page=str_replace("&tilde;","~",$page);
				// do this last, think about it :)
				$page=str_replace("&amp;","&",$page);
			} else {
				$page=unicode::utf8convert($page);//$page=utf8_encode($page);
			}

			debug("pagedata(".$this->path.")($nls)");
			$arCallArgs[$nls]["page"] = $page;

			if (preg_match('|<title>(.*)</title>|i', $page, $regs)) {
				$arCallArgs[$nls]["name"]=$regs[1];
			} else {
				$arCallArgs[$nls]["name"]=$this->getdata("file");
			}
			$this->call("system.save.data.phtml", $arCallArgs);
		}
	}
?>
