<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		if (!($result=$this->call("pobject::system.copyto.phtml", $arCallArgs))) {

			if (!$ARCurrent->newpath) {
				$arResult="no path to save to";
			} else {
			    $targetData = current($this->get($ARCurrent->newpath, "system.get.data.phtml"));

				// change links in $nlsdata->page
				if ( ( $search ?? null ) && ( $replace ?? null ) ) {
					reset($AR->nls->list);
					while (list($nls, $language)=each($AR->nls->list)) {
						if (isset($targetData->$nls) && isset($targetData->$nls->page)) {
							$targetData->$nls->page=str_replace("{arRoot}".$search, "{arRoot}".$replace, $targetData->$nls->page);
						}
					}
				}

				$this->store->save($ARCurrent->newpath, $this->type, $targetData);
			}

		} else {
			$arResult=$result;
		}
	}
?>
