<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new object;
		}
		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			$count=0;
			while (list($key, $value)=each($AR->nls->list)) {
				
				if ($name=$this->getdata("name",$key)) { // $name is the variable that must be set for a language to be available.
					if (!$this->data->$key) {
						debug("$key not yet set","all");
						$newnlsdata=new object;
					} else {
						debug("$key was set","all");
						$newnlsdata=$this->data->$key;
					}
					debug("name found: $name","all");
					$newnlsdata->name=$name;
					$properties["name"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["name"][$count]["nls"]="'$key'";
					$properties["text"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["text"][$count]["nls"]="'$key'";
					$count++;
					$newnlsdata->summary=$this->getdata("summary",$key);
					$properties["text"][$count]["value"]="'".AddSlashes($newnlsdata->summary)."'";
					$properties["text"][$count]["nls"]="'$key'";
					$count++;
					if ($this->store->is_supported("fulltext")) {
						$properties["fulltext"][$count]["value"]="'".AddSlashes($this->store->format_for_fti(
								$newnlsdata->name." ".
								$this->html_to_text($newnlsdata->summary)." ".
								$newnlsdata->title." ".
								$this->html_to_text($this->getdata("page",$key))
								))."'";
						$properties["fulltext"][$count]["nls"]="'$key'";
					}
					$this->data->{$key}=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else { // clear language values for $key->name if set, keep the rest, just in case.
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->nls->list[$key]);
					}
				}
			}
			$this->save($properties);

			if (!$this->error) {
				unset($this->arIsNewObject);
				reset($AR->nls->list);
				$count=0;
				while (list($key, $value)=each($AR->nls->list)) {
					$page=$this->getdata("page",$key);
					if ($page!==false) {
						$this->call("system.save.page.phtml",Array("ContentLanguage" => $key, "page" => $page));
					}
				}
				$this->ClearCache();
			}
		}
	}
?>