<?php
	require_once($this->store->get_config('code')."modules/mod_page.php");
	
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		if (!$ContentLanguage) {
			$this->error="Somehow there was no language set. This is a bug.";
		} else if (!$AR->nls->list[$ContentLanguage]) {
			$this->error="Unknown language selected... weird";
		} else {
			if (!$page) {
				$page=$htmltext;
			}
			if ($ContentEditOptionsPath) {
				$arEditorSettings=$ARCurrent->editorSettings[$ContentEditOptionsPath];
				if (!$arEditorSettings) {
					$arEditorSettings=current($this->get($ContentEditOptionsPath, "editor.ini"));
					$ARCurrent->editorSettings[$ContentEditOptionsPath]=$arEditorSettings;
				}
			} else {
				$arEditorSettings=$ARCurrent->editorSettings[$this->path];
				if (!$arEditorSettings) {
					$arEditorSettings=$this->call("editor.ini");
					$ARCurrent->editorSettings[$this->path]=$arEditorSettings;
				}
			}
			if ($arEditorSettings) {
				if ($arEditorSettings["htmlcleaner"]["enabled"]) {
					include_once($this->store->get_config("code")."modules/mod_htmlcleaner.php");
					$config = $arEditorSettings["htmlcleaner"];
					$page = htmlcleaner::cleanup($page, $config);
				}
				if ($arEditorSettings["htmltidy"]["enabled"]) {
					include_once($this->store->get_config("code")."modules/mod_tidy.php");
					$config=$arEditorSettings["htmltidy"];
					$config["temp"]=$this->store->get_config("files")."temp/";
					$config["path"]=$AR->Tidy->path;
					$tidy=new tidy($config);
					$result=$tidy->clean($page);
					$page=$result["html"];
				}


				if ($arEditorSettings["allow_tags"]) {
					$page=strip_tags($page, $arEditorSettings["allow_tags"]);
				}
			}

			$page = page::compile($page, $ContentLanguage);

			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));
			$this->data->$ContentLanguage->page=$page;

			// Find out all references to other objects
			// (images, links) in this object, so we can
			// warn the user if he tries to delete/rename
			// an object which is still referenced somewhere
			// Use Perl compatible regex for non-greedy matching
			$refs=(array)$this->GetReferences($page);
			$count=0;
			foreach ($refs as $ref) {
				if (substr($ref, -1) != '/' && !$this->exists($ref)) {
					// Drop the template name
					$ref=substr($ref, 0, strrpos($ref, "/")+1);
				}
				$properties["references"][$count]["path"]=$ref;
				$count++;
			}
			$this->save($properties);
			$this->ClearCache();
			$arResult=$page;
		}
	}
?>
