<?php
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		if (!$ContentLanguage) {
			$this->error="Somehow there was no language set. This is a bug.";
		} else if (!$AR->nls->list[$ContentLanguage]) {
			$this->error="Unknown language selected... weird";
		} else {
			if (!$page) {
				$page=$htmltext;
			}
			if ($ContentEditOptionsPath) {
				$arEditorSettings=current($this->get($ContentEditOptionsPath, "editor.ini"));
			} else {
				$arEditorSettings=$this->call("editor.ini");
			}
			if ($arEditorSettings) {
				if ($arEditorSettings["htmltidy"]["enabled"]) {
					include_once($this->store->code."modules/mod_tidy.php");
					$config=$arEditorSettings["htmltidy"];
					$config["temp"]=$this->store->files."temp/";
					$config["path"]=$AR->Tidy->path;
					$tidy=new tidy($config);
					$result=$tidy->clean($page);
	//				if ($result["errors"]) {
	//					$this->error=$result["errors"];
	//				} else {
						$page=$result["html"];
	//				}
				}
				if ($arEditorSettings["allow_tags"]) {
					$page=strip_tags($page, $arEditorSettings["allow_tags"]);
				}
			}

			$page = $this->RAWtoAR($page);

			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));
			$this->data->$ContentLanguage->page=$page;
			$this->save();
			$this->ClearCache();
			$arResult=$page;
		}
	}
?>