<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig($arCallFunction, $arCallArgs)) {
?>
<head>
<title><?php echo $nlsdata->name; ?></title>
</head>
<body scroll="no" bgcolor="white" onLoad="top.LoadingDone();">
<?php
  include($this->store->code."widgets/menu/menu.phtml");
?>
<?php echo $nlsdata->page; ?>
</body>
<?php
  }
?>