<?php   
	if ($this->CheckSilent("delete")) {
		if (!$this->lock("T")) {
			$this->error=$ARnls["err:cannotlockobject"];
		} else {
			if (!$this->real_ls(".","system.get.phtml")) {
				// remove grants for this object in all user objects.
				$userConfig = $this->loadUserConfig();
				$authconfig = $userConfig['authentication'];

				if ($data->config->grants && is_array($data->config->grants)) {
					while (list($login, $grants)=each($data->config->grants)) {
						$criteria["login"]["value"]["="]=$login;
						foreach ($authconfig['userdirs'] as $userdirpath) {
							$this->find($userdirpath, $criteria, "system.update.grants.phtml", array(
								"action" => "delete",
								"path" => $this->path) );
						}
					}
				}
				// clear cache
				$this->ClearCache();
				// finally remove object itself
				$this->delete();
			} else {
				$this->error=$ARnls["err:containsobj"];
			}
			$this->unlock();
		}
	} else {
		$this->error=$ARnls["nopermission"];
	}
?>
