#!/usr/bin/env php
<?php
	$tests = [
		"dialog.add.php" => [
			[],
			["arNewType" => "paddressbook"],
			["arNewType" => "particle"],
			["arNewType" => "pbookmark"],
			["arNewType" => "pcalendar"],
			["arNewType" => "pcalitem"],
			["arNewType" => "pdir"],
			["arNewType" => "pfile"],
			["arNewType" => "pgroup"],
			["arNewType" => "pdir.groups"],
			["arNewType" => "pldapconnection"],
			["arNewType" => "pdir.libs"],
			["arNewType" => "psection.lib"],
			["arNewType" => "pnewspaper"],
			["arNewType" => "pobject"],
			["arNewType" => "porganization"],
			["arNewType" => "ppage"],
			["arNewType" => "pperson"],
			["arNewType" => "pphoto"],
			["arNewType" => "pphotobook"],
			["arNewType" => "pprofile"],
			["arNewType" => "pdir.profiles"],
			["arNewType" => "pproject"],
			["arNewType" => "pscenario"],
			["arNewType" => "psearch"],
			["arNewType" => "psection"],
			["arNewType" => "pshortcut"],
			["arNewType" => "psite"],
			["arNewType" => "pdir.system"],
			// FIXME: Skipped, requires PHPUnit_Framework_Test
			// ["arNewType" => "punittest"],
			["arNewType" => "puser"],
			["arNewType" => "pdir.users"]
		],
		"dialog.add.form.php" => [
			[],
			["arNewType" => "paddressbook", "showall" => 1],
			["arNewType" => "particle", "showall" => 1],
			["arNewType" => "pbookmark", "showall" => 1],
			["arNewType" => "pcalendar", "showall" => 1],
			["arNewType" => "pcalitem", "showall" => 1],
			["arNewType" => "pdir", "showall" => 1],
			["arNewType" => "pfile", "showall" => 1],
			["arNewType" => "pgroup", "showall" => 1],
			["arNewType" => "pdir.groups", "showall" => 1],
			["arNewType" => "pldapconnection", "showall" => 1],
			["arNewType" => "pdir.libs", "showall" => 1],
			["arNewType" => "psection.lib", "showall" => 1],
			["arNewType" => "pnewspaper", "showall" => 1],
			["arNewType" => "pobject", "showall" => 1],
			["arNewType" => "porganization", "showall" => 1],
			["arNewType" => "ppage", "showall" => 1],
			["arNewType" => "pperson", "showall" => 1],
			["arNewType" => "pphoto", "showall" => 1],
			["arNewType" => "pphotobook", "showall" => 1],
			["arNewType" => "pprofile", "showall" => 1],
			["arNewType" => "pdir.profiles", "showall" => 1],
			["arNewType" => "pproject", "showall" => 1],
			["arNewType" => "pscenario", "showall" => 1],
			["arNewType" => "psearch", "showall" => 1],
			["arNewType" => "psection", "showall" => 1],
			["arNewType" => "pshortcut", "showall" => 1],
			["arNewType" => "psite", "showall" => 1],
			["arNewType" => "pdir.system", "showall" => 1],
			// FIXME: Skipped, requires PHPUnit_Framework_Test
			// ["arNewType" => "punittest", "showall" => 1],
			["arNewType" => "puser", "showall" => 1],
			["arNewType" => "pdir.users", "showall" => 1]
		],
	];
	include_once("testRunner.php");
