<?php 
	/******************************************************************
	 browse.nav.icons.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the icons list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
	?>
<html>
<head>
<link type="text/css" rel="stylesheet" href="<?php echo $AR->dir->www; ?>styles/browse.icons.css">
<body bgcolor="white">
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	if ($letter && ($letter=substr(eregi_replace("[^a-z]","",$letter),0,1))) {
		$crit["name"]["value"]["LIKE"]="'$letter%'";
	}
	if (!$limit) {
		$limit=100;
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$total=$this->store->count($this->store->find("", $crit));
	$this->find(".",$crit, "browse.nav.icons.show.phtml", "", $limit, $offset);
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
?>
</body>
<?php
	}
?>