<table border="0" width="100%">
<tr>
  <td align="left">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["first"]; ?> :</b></font>
  </td><td align="right">
    <input type="text" name="firstname" maxlength="50" 
      value="<?php $this->showdata("firstname"); ?>">
  </td>  <td align="left">
    <font face="helvetica, sans-serif"><?php echo $ARnls["middle"]; ?> :</font>
  </td><td align="right">
    <input type="text" name="middlename" maxlength="50" 
      size="5" value="<?php $this->showdata("middlename"); ?>">
  </td>  <td align="left">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["last"]; ?> :</b></font>
  </td><td align="Right">
    <input type="text" name="lastname" maxlength="50" 
       value="<?php $this->showdata("lastname"); ?>">
  </td>
</tr>
</table>
<br>
<table border="0" >
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		E-Mail</font>
	</td><td align="right">
		<input type="text" name="emailaddress" value="">
	</td><td align="right">
		<input type="button"  width="100%" onClick="add_new_item(document.forms[0].emailaddress,document.forms[0].emailaddresses);" name="e_add" value="Add">
	</td>
</tr>
<tr>
	<td align="left" colspan="2">
	<select name="emailaddresses" size="5" width="300">
	</select>
	</td>
	<td align="left">
		<input type="button"  width="100%" name="e_edit" value="Edit" onClick="edit_item(document.forms[0].emailaddresses, document.forms[0].emailaddress);"><br>
		<input type="button" width="100%" name="e_remove" value="Remove" onClick="remove_item(document.forms[0].emailaddresses);"><br>
	</td>
</tr>
</table>
