<?php
  /******************************************************************
   form.phtml                                      Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read")) {
?>
<head>
	<script language="javascript">
	<!--
		function collect_items(src,dest) {
			dest.value="";
				for (i=0; i<src.options.length; i++) {
					if (dest.value)
						dest.value+=","+src.options[i].value;
					else
						dest.value=src.options[i].value;
				}
		}


		function add_new_item(src,dest) {
			if (src.value) {
				dest.options[dest.options.length]=new Option(src.value,src.value);
				src.value="";
			}
		}

		function remove_item(item) {
			item.options[item.selectedIndex]=null;
		}


		function edit_item(src,dest) {
			dest.value=src.options[src.selectedIndex].value;
			src.options[src.selectedIndex]=null;
		}
	// -->
	</script>
</head>

<body bgcolor="white">
<?php
  $this->parents($this->path, "ShowLink.phtml","target=edit.phtml");
?>
<form method="post" onSubmit="collect_items(document.forms[0].emailaddresses,document.forms[0].emails);">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="newtype" value="<?php echo $newtype; ?>">
<input type="hidden" name="newparent" value="<?php echo $this->path; ?>">
<input type="hidden" name="newfilename" value="<?php echo $newfilename; ?>">
<input type="hidden" name="returnpage" value="<?php echo $returnpage; ?>">
<?php
include($this->store->code."widgets/formlock/js.html");
?>

<table border="0" cellspacing="0" width="100%" bgcolor="#404074"> 
<tr>
  <td >
      <font face="helvetica, sans-serif" size="+1" color="white"><b><?php
	echo $ARnls["editorganization"]; ?>:</b></font><br>
  </td>
</tr>
</table>
<center>
<table border="0">
<tr>
	<td align="left">
		<font face="helvetica, sans-serif"><b>
		<?php echo $ARnls["name"]; ?></b> :</font>
	</td><td align="right">
		<input type="text" size="30"  name="name" value="<?php $this->showdata("name"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["address"]; ?> :</font>
	</td><td align="right">
		<input type="text" size="30"  name="address" value="<?php $this->showdata("address"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["zipcode"]; ?> :</font>
	</td><td>
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
		<tr>
			<td align="left">
				<input type="text" size="6" maxlength="6" name="zipcode" value="<?php $this->showdata("zipcode"); ?>">
			</td>
			<td align="right">
				<font face="helvetica, sans-serif">
				<?php echo $ARnls["city"]; ?> :</font>
			</td>
			<td align="right">
				<input type="text" size="15" name="city" value="<?php $this->showdata("city"); ?>">
			</td>
		</tr>
		</table>
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["pobox"]; ?> :</font>
	</td><td align="right">
		<input type="text" size="10"  name="pobox" value="<?php $this->showdata("pobox"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["country"]; ?> :</font>
	</td><td align="right">
		<input type="text"  name="country" value="<?php $this->showdata("country"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["telephone"]; ?> :</font>
	</td><td align="right">
		<input type="text" name="telephone" value="<?php $this->showdata("telephone"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["fax"]; ?> :</font>
	</td><td align="right">
		<input type="text" name="fax" value="<?php $this->showdata("fax"); ?>">
	</td>
</tr>
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["url"]; ?> :</font>
	</td><td align="right">
		<input type="text" name="url" value="<?php $this->showdata("url"); ?>">
	</td>
</tr>

<tr><td colspan="2">
<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr>
	<td align="left">
		<font face="helvetica, sans-serif">
		E-Mail</font> :
	</td><td align="right">
		<input type="text" name="emailaddress" value="">
	</td>
</tr>
<tr>
	<td align="right" colspan="2">
	<select name="emailaddresses" size="5" width="300">
	<?php
		while (is_array($data->emails) && (list($key,$email)=each($data->emails))) {
			echo "<option value=\"$email\">$email</option>\n	";
		}
	?>
	</select>
	</td>
</tr>
</table>
</td><td align="left" valign="top">
		<input type="hidden" name="emails" value="">
		<input type="button"  width="100%" onClick="add_new_item(document.forms[0].emailaddress,document.forms[0].emailaddresses);" name="e_add" value="Add"><br>
		<input type="button"  width="100%" name="e_edit" value="Edit" onClick="edit_item(document.forms[0].emailaddresses, document.forms[0].emailaddress);"><br>
		<input type="button" width="100%" name="e_remove" value="Remove" onClick="remove_item(document.forms[0].emailaddresses);"><br>
	</td>
</tr>
</table>
</center>
<p>

<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
  <td>
    <?php if ($newtype) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">

<?php
	$wgFFmessage="<b>Deleting from ".$this->path."</b>";
	$wgFFfunction="delete";
	include($this->store->code."widgets/fsfunctions/form.html");
?>

    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>
</form>
<font face="helvetica, sans-serif" size="2">
<?php
  $this->ls("","Show.phtml","target=edit.phtml");
?>
</font>
</body>
<?php
  }
?>