<?php
  include_once($this->store->code."nls/menu.".$nls);
?>
<script>
  imagedir='<?php echo $AR->dir->images; ?>';
  path='<?php echo $this->path; ?>';
</script>
<script language="JavaScript1.2" type="text/javascript" src="<?php echo $AR->dir->www; ?>widgets/menu/ns/menu.js"></script>
<LINK REL=stylesheet HREF="<?php echo $AR->dir->www; ?>widgets/menu/ns/menu.css" type="text/css">
<script language="JavaScript1.2" type="text/javascript">
<!--
  Faded=true;
  <?php
    if ($AR->user->data->login != "admin") {
      if (!$AR->user->grants["add"]) { $add=", Faded"; }
      if (!$AR->user->grants["edit"]) { $edit=", Faded"; }
      if (!$AR->user->grants["config"]) { $config=", Faded"; }
      if (!$AR->user->grants["delete"]) { $delete=", Faded"; }
      if (!$AR->user->grants["layout"]) { $layout=", Faded"; }
    }
    if (!$this->implements("pshortcut")) { 
      $shortcut=", Faded";  
      $shortcutlink="javascript:void(0)";
    } else {
      $shortcutlink="javascript:arshow(\\'edit_object_shortcut\\',\\'edit.object.shortcut.phtml\\')";
    }
  ?>
  ARMenu = new appMenu();

  ARMenu.addMenuItem('<?php echo $ARnls["m_object"]; ?>', 'javascript:void(0)', 'SubObject');
  ARMenu.addMenuItem('<?php echo $ARnls["m_edit"]; ?>', 'javascript:void(0)', 'SubEdit');
  ARMenu.addMenuItem('<?php echo $ARnls["m_view"]; ?>', 'javascript:void(0)', 'SubView');
  ARMenu.addMenuItem('<?php echo $ARnls["m_help"]; ?>', 'javascript:void(0)', 'SubHelp');

  SubObject.addMenuItem('<?php echo $ARnls["m_new"]; ?>', 'javascript:arshow(\'edit_object_data\',\'object.new.select.phtml\')', 0 <?php echo $add; ?>);
  SubObject.addMenuItem('<?php echo $ARnls["m_rename"]; ?>', 'javascript:arshow(\'object_fs\',\'object.rename.phtml\')', 0 <?php $delete; ?>);
  SubObject.addMenuItem('<?php echo $ARnls["m_copy"]; ?>', 'javascript:arshow(\'object_fs\',\'object.copy.phtml\')');
  SubObject.addMenuItem('<?php echo $ARnls["m_link"]; ?>', 'javascript:arshow(\'object_fs\',\'object.link.phtml\')');
  SubObject.addSeparator();
  SubObject.addMenuItem('<?php echo $ARnls["m_import"]; ?>', 'javascript:arshow(\'object_import\',\'object.import.phtml\')', 0 <?php echo $add; ?>);
  SubObject.addMenuItem('<?php echo $ARnls["m_export"]; ?>', 'javascript:arshow(\'object_export\',\'object.export.phtml\')');
  SubObject.addSeparator();
  SubObject.addMenuItem('<?php echo $ARnls["m_delete"]; ?>', 'javascript:arshow(\'object_fs\',\'object.delete.phtml\')', 0 <?php echo $delete; ?>);
  SubObject.addSeparator();
  SubObject.addMenuItem('<?php echo $ARnls["m_logoff"]; ?>', 'javascript:arshow(\'object_fs\',\'object.logoff.phtml\')', 0 <?php echo $delete; ?>);

  SubEdit.addMenuItem('<?php echo $ARnls["m_object"]; ?>', 'javascript:void(0)', 'SubEditObject');
  SubEdit.addMenuItem('<?php echo $ARnls["m_priority"]; ?>', 'javascript:arshow(\'edit_priority\', \'edit.priority.phtml\')');
  SubEdit.addSeparator();
  SubEdit.addMenuItem('<?php echo $ARnls["m_find"]; ?>', 'javascript:arshow(\'edit_find\', \'edit.find.phtml\')');
  SubEdit.addSeparator();
  SubEdit.addMenuItem('<?php echo $ARnls["m_preferences"]; ?>', 'javascript:arshow(\'<?php echo $this->store->root.$AR->user->path; ?>edit_preferences\',\'edit.preferences.phtml\')');

  SubEditObject.addMenuItem('<?php echo $ARnls["m_data"]; ?>','javascript:arshow(\'edit_object_data\', \'edit.object.data.phtml\')', 0 <?php echo $edit; ?>);
  SubEditObject.addMenuItem('<?php echo $ARnls["m_shortcut"]; ?>','<?php echo $shortcutlink; ?>', 0 <?php echo $shortcut; ?>);
  SubEditObject.addSeparator();
  SubEditObject.addMenuItem('<?php echo $ARnls["m_cache"]; ?>','javascript:arshow(\'edit_object_cache\', \'edit.object.cache.phtml\')', 0 <?php echo $edit; ?>);
  SubEditObject.addMenuItem('<?php echo $ARnls["m_layout"]; ?>','javascript:arshow(\'edit_object_layout\', \'edit.object.layout.phtml\')', 0 <?php echo $layout; ?>);
  SubEditObject.addSeparator();
  SubEditObject.addMenuItem('<?php echo $ARnls["m_grants"]; ?>','javascript:arshow(\'edit_object_grants\',\'edit.object.grants.phtml\')', 0 <?php echo $config; ?>);
  SubEditObject.addMenuItem('<?php echo $ARnls["m_types"]; ?>','javascript:arshow(\'edit_object_types\',\'edit.object.types.phtml\')', 0 <?php echo $config; ?>);
  SubEditObject.addMenuItem('<?php echo $ARnls["m_language"]; ?>','javascript:arshow(\'edit_object_nls\',\'edit.object.nls.phtml\')', 0 <?php echo $config; ?>);

  SubView.addMenuItem('<?php echo $ARnls["m_explorerbar"]; ?>', 'javascript:arexplorerbar()');
  SubView.addSeparator();
  SubView.addMenuItem('<?php echo $ARnls["m_small"]; ?>', 'javascript:setview(\'small\')');
  SubView.addMenuItem('<?php echo $ARnls["m_large"]; ?>', 'javascript:setview(\'large\')');
  SubView.addMenuItem('<?php echo $ARnls["m_details"]; ?>', 'javascript:setview(\'details\')');
  SubView.addSeparator();
  SubView.addMenuItem('<?php echo $ARnls["m_web"]; ?>', 'javascript:arshow(\'_new\',\'<?php echo $this->make_url(); ?>view.html\')');

  SubHelp.addMenuItem('<?php echo $ARnls["m_index"]; ?>', 'javascript:arshow(\'help\',\'help.topics.phtml\')');
  SubHelp.addMenuItem('<?php echo $ARnls["m_tutorials"]; ?>', 'javascript:arshow(\'help\',\'help.tutorials.phtml\')');
  SubHelp.addMenuItem('<?php echo $ARnls["m_search"]; ?>', 'javascript:arshow(\'help\',\'help.search.phtml\')');
  SubHelp.addSeparator();
  SubHelp.addMenuItem('<?php echo $ARnls["m_about"]; ?>', 'javascript:arshow(\'help_about\',\'help.about.phtml\')');

  ARMenu.build();
  ARMenu.init();

//-->
</script>
&nbsp;<br>
<div>
