<?php
  function array_merge_clobber($a1,$a2) {
  /*
    This function merges two arrays, recursively.
  */
    if(!is_array($a1)) {
      if (!is_array($a2)) {
        return false;
      } else {
        return $a2;
      }
    } else if (!is_array($a2)) {
      return $a1;
    }
    $newarray = $a1;
    while (list($key, $val) = each($a2)) {
      if (is_array($val) && is_array($newarray[$key])) {
        $newarray[$key] = array_merge_clobber($newarray[$key], $val);
      } else {
        $newarray[$key] = $val;
      }
    }
    return $newarray;
  }
?>