<?php   
if ($this->CheckLogin("delete")) {
  if (($result=$this->lock(0,"T")) && ($result["locks"][$this->path]["identity"]!=$AR->user->data->login)) {
    $error=$ARnls["err:cannotlockobject"];
  } else {
    if ($this->ls(".","system.get.phtml")) {
      $error="Object contains other objects, remove these first.";
    } else {
      // remove grants for this object in all user objects.
      if ($data->grants && is_array($data->grants)) {
        while (list($login, $grants)=each($data->grants)) {    
          $criteria["login"]["value"]["="]="'".$login."'";
          $this->find("/system/users/", $criteria, "updategrant.phtml", 
                      "action=delete&path=".RawUrlEncode($this->path)
                 );
        }
      }
      $this->delete($this->path);
    }
    $this->unlock();
  } 
}
?>