<?php
  include($this->store->code."includes/delete.phtml");
  if (!$error) {
	if (substr($this->path, 0, strlen("/system/users/"))=="/system/users/") { 
		// user object can also be linked under /system/groups/, 
		// but there can only be one in /system/users/ and if this
		// is that one, than remove it from the groups as well.
		if ($data->groups) {
			while (list($path, $value)=each($data->groups)) {
				$this->get($path, "SetUser.phtml", 
					"action=delete&path=".RawUrlEncode($path.$data->login."/").
					"&silent=true");
			}
  		}
		if (!$silent) {
			if (!$returnpage) {
				$returnpage=$this->store->root.$this->parent;
			} 
			Header("Location: ".$AR->dir->www."setlink.php?do=delete&path=".RawUrlEncode($this->path).
				"&returnpage=".RawUrlEncode($returnpage)."&parent=".RawUrlEncode($this->parent));
		}
	}
  } else {
	include($this->store->code."includes/error.phtml");
  }
?>