<?php
  include($this->store->code."includes/delete.phtml");
  if (!$error) {    
    // remove nodes from tree. 
    if (!$silent) {
      if (!$returnpage) {
        $returnpage=$this->store->root.$this->parent;
      } 
      Header("Location: ".$AR->dir->www.
          "setlink.php?do=delete&path=".RawUrlEncode($this->path).
          "&returnpage=".RawUrlEncode($returnpage).
          "&parent=".RawUrlEncode($this->parent));
    }
  } else {
    include($this->store->code."includes/error.phtml");
  }
?>