<?php
  function DelGrant(&$grants, $key, $grant="") {
    if ($grant) {
      while (list($currkey, $list)=@@each($grants)) {
        while (list($currgrant, $value)=@@each($list)) {
          if ($currgrant!=$grant || $currkey!=$key) {
            $newgrants[$currkey][$currgrant]=$value;
          }
        }
      }
    } else {
      while (list($currkey, $list)=@@each($grants)) {
        while (list($currgrant, $value)=@@each($list)) {
          if ($currkey!=$key) {
            $newgrants[$currkey][$currgrant]=$value;
          }
        }
      }
    }
    return $newgrants;
  }
?>