<?php
	global $AR;
	if ($this) $store=&$this->store;

	include_once($store->code."includes/system.functions.merge.phtml");

	if (!$data) $data=new object;

	include_once($store->code."modules/mod_ax.phtml");

	$mod=new mod_ax;

    if (!$store->exists($import_path)) {
		$error="Error: Import path $import_path doesn't exist";
    } else
      if (!($error=$mod->open($ax_file,$AR->ax,"unpack",$store->files."temp/"))) {
		if (!$fp=$mod->openObjectsData("r")) {
			$error="Error: No object data found in $ax_file";
		} else {
			unset($savedObject);
			while ($object=$mod->getObject()) {
				$path=$object->path;
				$id=$object->id;

				$newfilename=$import_path.substr($path,1);

				if (!$savedObject[$id]) {
					$savedObject[$id]=$newfilename;
					$obj=$mod->data->objects[$object];
					if ($ARImportNoGrants) {
						unset($obj["data"]->grants);
						unset($obj["data"]->usergrants);
					}
					
					if ($store->exists($newfilename)) {
						$old=$store->call("Get.phtml","",$store->get($newfilename));
						$old=$old[0];
						if ($old->lastchanged<$object->lastchanged) {
						 	//ok, merge it
							merge($old->data,$object->data);
							$object->data=$old->data;
						} else {
							// echo "not merging ($newfilename)\n";
						}
					}
					$result=$store->save($newfilename, $object->type, $object->data, $object->properties, $object->vtype);
					if (!$result) {
						$error=$store->error;
					}
				} else {
					$result=$store->link($savedObject[$id],$newfilename);
					if (!$result) {
						$error=$store->error;
					}
				}
			}
		}

		if (!($error=$mod->importfiles("files",$store->files."files".$import_path))) {
			$error=$mod->importfiles("templates",$store->files."templates".$import_path);
		}
		$mod->close();
}
?>