<?php
  global $nocache;
  $nocache=true;
  if (!$error) {
    if ($newtype) { // save a new object
      if ($this->CheckLogin("add")) {
        if (!eregi("\.\.",$newfilename)) {
          if (eregi("^[a-z0-9_\{\}\.\:-]+$",$newfilename)) { // no "/" allowed, these will void the 'add' grant check.
            if (!$this->exists($newfilename)) {
              $newfilename=$this->save($newfilename, $newtype, $newdata, $properties, $vtype);
              $parent=$this->path;
              $this->ClearCache();
            } else {
              $error="$newfilename already exists.";
            }
          } else {
            $error="$newfilename is no valid filename, use only a-z, A-Z, 0-9 and _ or -.";          
          }
        } else {
          $error="$newfilename is no valid filename, do not use '..' in filenames.";
        }
      }
    } else { // edit an existing object
      if ($this->CheckLogin("edit") && $this->CheckConfig("save.phtml","")) {
        if (!($result=$this->lock(0,"O")) || ($result["locks"][$this->path]["identity"]==$AR->user->data->login)) {
          $newfilename=$this->save($this->path, $this->type, $newdata, $properties, $vtype);
          $parent=$this->parent;
          $this->ClearCache();
	  $this->unlock();
	} else {
	  $error="Object already locked.";
        }
      }
    }
  }

?>