<?php
	/******************************************************************
	 classic.form.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arNewType, $arNewFilename
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object. 

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["edituser"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
</head>
<body bgcolor="white">
<form>
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<table border="0" width="100%" cellspacing="0">
<tr>
	<td bgcolor="#404074" colspan="2">
		<font face="helvetica, sans-serif" color="white"><b><?php $ARnls["userdata"]; ?>
		<?php if (!$arNewType) { echo $data->login; } else { echo $arNewFilename; } ?></b></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="text" name="name" maxlength="50" value="<?php $this->showdata("name"); ?>">
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["password"]; ?>&nbsp:</b></font>
	</td>
	<td>
		<input type="password" name="newpass1" value="">
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["again"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="password" name="newpass2" value="">
	</td>
</tr><tr>
	<td bgcolor="#404074" colspan="2">
		<font face="helvetica, sans-serif" color="white"><b><?php echo $ARnls["preferences"]; ?></b></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["language"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<select name="language">
		<?php
			if (!$arNewType) {
				$language=$data->language;
			} else {
				$language=$ARCurrent->default;
			}
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				if ($key==$language) {
					echo "<option value=\"$key\" selected>$value</option>\n";
				} else {
					echo "<option value=\"$key\">$value</option>\n";
				}
			}
		?>
		</select>
	<font face="helvetica, sans-serif"><b><?php echo $ARnls["interface"]; ?>&nbsp;:</b></font>
		<select name="interface">
		<option value="classic"><?php echo $ARnls["classic"]; ?></option>
		<option value="new" <?php if ($data->interface=="new") { echo "selected"; } ?>><?php echo $ARnls["new"]; ?></option>
	</select>
	</td>
</tr><tr>
	<td></td>
	<td><font face="helvetica, sans-serif"><i><?php echo $ARnls["changeeffectivenextlogin"]; ?></i></font></td>
</tr><tr>
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removeuser"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->code."widgets/recurse/form.js");
				include($this->store->code."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
	}
?>