<?php
	if ($this->arIsNewObject) {
		$url=$AR->dir->www."setlink.php?do=add";
	} else {
		$url=$AR->dir->www."setlink.php?do=update";
	}
	$this->call("system.save.data.phtml",$arCallArgs);
	if (!$this->error) {
		if (!$arReturnPage) {
			$arReturnPage=$this->store->get_config("root").$this->path;
		}
		$folder=$this->call("system.get.folder.phtml");
		if ($arShortCut) {
			$url.="&shortcut=".RawUrlEncode($arShortCut);
		}
		$url.="&link=".RawUrlEncode($this->parent);
		$url.="&icon=".RawUrlEncode($folder["icon"]);
		$url.="&name=".RawUrlEncode($folder["name"]);
		$url.="&path=".RawUrlEncode($folder["path"]);
		$url.="&pre=".RawUrlEncode($folder["pre"]);
		$url.="&returnpage=".RawUrlEncode($arReturnPage);
		ldRedirect($url);
	} else {
		$this->call("show.error.phtml");
	}
?>