<?php
	/******************************************************************
	 classic.config.phtml                                  Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: "config"
	 Global variables: none

	 This displays the user interface for the configuration of the 
	 current object (cache, templates, grants, usergrants).

	 No return value.
	
	******************************************************************/
	if ($this->CheckLogin("config")) {
		$ARCurrent->arReturnPage=$this->store->root.$this->path."classic.config.phtml";
?>
<html>
<head>
<title><?php printf($ARnls["configure"],$nlsdata->name); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
</head>
<body bgcolor="white" onLoad="custom_init()">
<table border="0" width="100%" cellspacing="4" vspace="10" hspace="10">
<tr>
	<td bgcolor="#404074" colspan="2">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php 
			echo $ARnls["grantsforobject"]; ?></b> ( <?php 
			echo $this->path; ?> )</font>
	</td>
</tr>
<tr>
	<td colspan="2">
		<?php $this->call("classic.config.grants.form.phtml"); ?>
	</td>
</tr>
<tr>
	<td bgcolor="#404074" colspan="2">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php printf($ARnls["allgrants"],$data->name); ?></b></font>
	</td>
</tr>
<tr>
	<td colspan="2">
		<table border="1" width="100%">
		<?php
			if ($data->usergrants && is_array($data->usergrants)) {
				ksort($data->usergrants);
				while (list($path, $usergrants)=each($data->usergrants)) {	
					echo "<tr>";
					echo "<td><a href=\"".$this->store->root.$path.
						"classic.config.grants.save.phtml?delete=true&type=puser&id=".RawUrlEncode($data->login).
						"&arReturnPage=".RawUrlEncode($ARCurrent->arReturnPage).
						"\"onClick=\"return confirm('".sprintf($ARnls["q:removeallgrants"],$path).
						"')\">$path</a></td><td>"; 
					if ($usergrants && is_array($usergrants)) {
						ksort($usergrants);
						while (list($usergrant, $modifiers)=each($usergrants)) {
							if (!is_array($modifiers)) {
								echo arGetGrantType($modifiers);
							}
							echo "<a href=\"".$this->store->root.$path.
								"classic.config.grants.save.phtml?delete=true&type=".RawUrlEncode($this->type)."&id=".RawUrlEncode($data->login).
								"&grant=".RawUrlEncode($usergrant).
								"&arReturnPage=".RawUrlEncode($ARCurrent->arReturnPage).
								"\"	onClick=\"return confirm('".sprintf($ARnls["q:removegrant"],$usergrant,$path).
								"')\">$usergrant</a> "; 
							if (is_array($modifiers)) {
								echo "( ";
								while (list($modifier, $value)=each($modifiers)) {
									echo arGetGrantType($value);
									echo "<a href=\"edit.object.grants.save.phtml?delete=true&type=".RawUrlEncode($this->type)."&id=".
										RawUrlEncode($data->login)."&grant=".
										RawUrlEncode($usergrant)."&modifier=".
										RawUrlEncode($modifier)."&arReturnPage=".
										RawUrlEncode($ARCurrent->arReturnPage).
										"\" onClick=\"return confirm('".sprintf($ARnls["q:removegrant"],$usergrant."(".$modifier.")",$path)."')\">$modifier</a>\n"; 
								}
								echo ") ";
							}
						}
					}
					echo "</td></tr>";
				}
			}
		?>
		</table>
	</td>
</tr>
<tr>
	<td bgcolor="#404074" colspan="2">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php printf($ARnls["groupmembership"],$data->name); ?></b></font>
	</td>
</tr>
<tr>
	<td colspan="2">
		<table><tr>
		<?php
			while (list($path, $group)=@each($data->groups)) {
				echo "<td><a href=\"".$this->store->root.$path."classic.edit.phtml\"><img src=\"".
					$AR->dir->images."icons/pgroup.gif\" border=\"0\"> $group</a></td>";
			}
		?></tr></table>		
	</td>
</tr>
<tr>
	<td bgcolor="#404074">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["types"]; ?></b></font>
	</td>
	<td bgcolor="#404074">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["priority"]; ?></b></font>
	</td>
</tr>
<tr>
	<td valign="top">
		<?php $this->call("classic.config.types.form.phtml"); ?>
	</td>
	<td valign="top">
		<?php $this->call("classic.config.priority.form.phtml"); ?>
	</td>
</tr><tr>
	<td bgcolor="#404074">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php 
			echo $ARnls["language"]; ?></b></font>
	</td>
	<td bgcolor="#404074" width="50%">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["caching"]; ?></b></font>
	</td>
</tr><tr>
	<td valign="top">
		<?php $this->call("classic.config.nls.form.phtml"); ?>
	</td>
	<td valign="top">
		<?php $this->call("classic.config.cache.form.phtml"); ?>
	</td>
</tr><tr>
	<td bgcolor="#404074">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["customdata"]; ?></b></font>
	</td>
</tr><tr>
	<td valign="top" bgcolor="#EEEEEE">
		<?php 
			$this->call("edit.object.custom.form.phtml", 
							Array(
							"arReturnPage" => $this->path."classic.config.phtml"
							)); 
		?>
	</td>
</tr>
</table>
</body>
<?php
	}
?>