<?php
  /******************************************************************
  ******************************************************************/
  if ($this->CheckSilent("read")) {
    if ($this->arIsNewObject) {
      $login=$this->getdata("arNewFilename","none");
    } else {
      $login=$this->data->login;
    }

    require($this->store->get_config("code")."/configs/authentication.phtml");
?>
<table border="0" width="90%">
<tr>
  <td>
    <fieldset id="data">
    <legend><?php echo $ARnls["login"]." : ".$login; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center" width="90%">
      <tr>
        <td>
          <span class="required"><?php echo $ARnls["name"]; ?></span>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="text" name="name" maxlength="32" 
            value="<?php $this->showdata("name", "none"); ?>">
        </td>
      </tr><tr>
        <td colspan="2">
          <?php echo $ARnls["password"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="password" name="newpass1" maxlength="50" 
            value="">
        </td>
      </tr><tr>
        <td colspan="2">
          <?php echo $ARnls["again"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="password" name="newpass2" maxlength="50" 
            value="">
        </td>
      </tr>
      <?php
        if($auth_config["expiry"] ) {
          if ($this->data->password_expiry) {
             $checked = "";
          } else {
             $checked = "checked";
          }
      ?>
      <tr>
        <td colspan="2">
          <input type="checkbox" name="neverexpires" value="1" <?php echo $checked; ?>><?php echo $ARnls["neverexpires"]; ?>
        </td>
      </tr>
      <?php
        }
      ?>
      <?php
        // profile support
        if($this->CheckSilent("config")) {
      ?>
      <tr>
        <td colspan="2">
          <?php echo $ARnls["profile"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          <select name="profile">
            <option value=""><?php echo $ARnls["noprofile"]; ?></option>
            <?php
              $selected=$this->getdata("profile");
              $crit['object']['type']['=']="'pprofile'";
              $this->find("/system/profiles/",$crit,"show.option.phtml",'selected='.$selected);
            ?>
          </select>
        </td>
      </tr>
      <?php
        if ($this->arIsNewObject) {
          // show set owner option
      ?>
      <tr>
        <td colspan="2">
          <?php echo $ARnls["change_owner_recursive"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
			<input type="radio" name="setowner" value="1" <?php if ($this->getdata('setowner')) { echo 'checked'; } ?>> <?php echo $ARnls["yes"]; ?>	
			<input type="radio" name="setowner" value="0" <?php if (!$this->getdata('setowner')) { echo 'checked'; } ?>> <?php echo $ARnls["no"]; ?>
        </td>
      </tr>
      <?php
          }
        }
      ?>
      </table>
    </fieldset>
  </td>
</tr>
</table>
<script>
  window.onload=init;
  function init() {
    document.wgWizForm["name"].focus();
  }
</script>
<?php
    $arResult["save"]["name"]["ereg"]=".+";
    $arResult["save"]["name"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
    $arResult["next"]=$arResult["save"];
  }
?>