<?php
  /******************************************************************
  ******************************************************************/
  if ($this->CheckSilent("read")) {
    if ($this->arIsNewObject) {
      $login=$this->getdata("arNewFilename","none");
    } else {
      $login=$this->data->login;
    }
?>
<table border="0" width="90%">
<tr>
  <td>
    <fieldset id="data">
    <legend><?php echo $ARnls["login"]." : ".$login; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center" width="90%">
      <tr>
        <td>
          <span class="required"><?php echo $ARnls["name"]; ?></span>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="text" name="name" maxlength="32" 
            value="<?php $this->showdata("name", "none"); ?>">
        </td>
      </tr><tr>
        <td colspan="2">
          <?php echo $ARnls["password"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="password" name="newpass1" maxlength="50" 
            value="">
        </td>
      </tr><tr>
        <td colspan="2">
          <?php echo $ARnls["again"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="password" name="newpass2" maxlength="50" 
            value="">
        </td>
        </tr>

                <?
              // profile support
                if($this->CheckSilent("config")) {
                ?>
         <tr>
          <td colspan="2">
            <?php echo $ARnls["profile"]; ?>
          </td>
        </tr><tr>
          <td colspan="2">
            <select name="profile">
              <option value=""><?php echo $ARnls["noprofile"]; ?></option>
              <?php
                      $selected=$this->getdata("profile");
                $crit['object']['type']['=']="'pprofile'";
                $this->find("/system/profiles/",$crit,"show.option.phtml",'selected='.$selected);
              ?>
            </select>
          </td>
      </tr>
                <?
                }
                ?>
      </table>
    </fieldset>
  </td>
</tr>
</table>
<script>
  window.onload=init;
  function init() {
    document.wgWizForm["name"].focus();
  }
</script>
<?php
    $arResult["save"]["name"]["ereg"]=".+";
    $arResult["save"]["name"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
    $arResult["next"]=$arResult["save"];
  }
?>