<?php
	/******************************************************************
	******************************************************************/
	if ($this->CheckSilent("config")) {
		if (!$login=$this->data->login) {
			$login=$this->getdata("arNewFilename");
		}
?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset id="data">
		<legend><?php printf($ARnls["groupmembership"],$login); ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" height="100%">
			<tr>
				<td>
					<select multiple name="groups[]" size="10" style="width: 250px;">
					<?php
						$selected = Array();
						$groups = $this->getdata("groups", "none");
						/* now for backwards compatibility use the key if $val is not a path, in that case the key will be a path. */
						if (is_array($groups)) {
							reset($groups);
							while (list($key, $val)=each($groups)) {
								if (substr($val, 0, 1) == "/") {
									$selected[$val] = $val;
								} else {
									$selected[$key] = $val;
								}
							}
						}
						$criteria["object"]["implements"]["="]="'pgroup'";
						$this->find(
								"/system/groups/", 
								$criteria, 
								"show.option.multiple.phtml", 
								Array("selected" => $selected, "grant" => "edit")
								);
					?>
					</select>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["groups[]"].focus();
	}
</script>
<?php
	}
?>