<?php
  /******************************************************************

   no result.

  ******************************************************************/
  if ($this->CheckSilent("read")) {
?>
    <fieldset id="editor">
    <legend><?php echo $ARnls["editor"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          HTML
        </td><td>
          <select name="editor" style="width: 100px;">
              <option value="wysiwyg"><?php echo $ARnls["wysiwyg"]; ?></option>
              <option value="text" <?php if ($data->editor=="text") { echo "selected"; } ?>><?php echo $ARnls["text"]; ?></option>
	      <option value="tinymce" <?php if ($editor=="tinymce") { echo "selected"; } ?>><?php echo $ARnls["tinymce"]; ?></option>
          </select>
        <td>
      </tr>
      <tr>
        <td>
          <?php echo $ARnls["templates"]; ?>
        </td><td>
          <select name="template_editor" style="width: 100px;">
              <option value="text"><?php echo $ARnls["text"]; ?></option>
              <option value="helene" <?php if ($data->template_editor=="helene") { echo "selected"; } ?>>Helene</option>
          </select>
        <td>
      </tr>
      </table>
    </fieldset>
<?php
  }
?>
