<?php
  /******************************************************************
   edit.object.cache.phtml			   Muze Ariadne v2.1
   ------------------------------------------------------------------

   No result.

  ******************************************************************/

  if ($this->CheckLogin("edit") && $this->CheckConfig()) {
    include($this->store->code."widgets/wizard/code.php");

    $start="edit.preferences.language.phtml";
    $interface="edit.preferences.interface.phtml";
    $editor="edit.preferences.editor.phtml";
    $finish="edit.preferences.save.phtml";
	$cancel="js.window.close.phtml";
	   
    $wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
    $wgWizFlow[0]["save"]=$finish;
    $wgWizFlow[0]["cancel"]=$cancel;
    $i++;
    $wgWizFlow[$i]["title"]=$ARnls["language"];
    $wgWizFlow[$i]["image"]=$AR->dir->images."wizard/languages.png";
    $wgWizFlow[$i]["template"]=$start;
    $i++;
    $wgWizFlow[$i]["title"]=$ARnls["interface"];
    $wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
    $wgWizFlow[$i]["template"]=$interface;
    $i++;
    $wgWizFlow[$i]["title"]=$ARnls["editor"];
    $wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
    $wgWizFlow[$i]["template"]=$editor;
    $i++;
    $wgWizFlow[$i]["title"]=$ARnls["save"];
    $wgWizFlow[$i]["template"]=$finish;
    $wgWizFlow[$i]["back"]=$i-1;

    $wgWizNoSidebar=true;    
    $wgWizControl=$this->getdata("wgWizControl","none");
    $wgWizCurrent=$this->getdata("wgWizCurrent","none");
    if ($wgWizControl && $wgWizCurrent) {
      $wgWizNextStep=$wgWizFlow[$wgWizCurrent][wgWizGetAction($wgWizControl)];
      $wgWizButtons=$wgWizFlow[$wgWizNextStep];
    }
    $wgWizTitle=$ARnls["preferences"];    
    $wgWizHeader=$ARnls["preferences"];    
    include($this->store->code."widgets/wizard/new.html");
  }
?>