<?php
	/******************************************************************
	 edit.object.language.tabs.phtml                       Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays a tablist of available languages
	 to be used in the flow of an object edit wizard.

	 no result

	******************************************************************/

	if ($this->CheckSilent("read") && $this->CheckConfig()) {
	}
?>