<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$start="edit.object.data.form.phtml";
		$preferences="edit.object.data.preferences.phtml";
		$groups="edit.object.data.groups.phtml";
		$finish="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["template"] = $cancel;
	 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["template"]=$start;
		$wgWizFlow[$i]["next"]=$i+1;
		if ($this->CheckSilent("config")) {
			/* include the 'groups' template */
			$wgWizFlow[$i]["save"]=$i+3+$customoffset;
		} else {
			/* skip the 'groups' template */
			$wgWizFlow[$i]["save"]=$i+2+$customoffset;
		}
		$wgWizFlow[$i]["cancel"]=0;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["preferences"];
		$wgWizFlow[$i]["template"]=$preferences;
		$wgWizFlow[$i]["prev"]=$i-1;		
		$wgWizFlow[$i]["cancel"]=0;
		if ($this->CheckSilent("config")) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$customoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["groups"];
			$wgWizFlow[$i]["template"]=$groups;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["cancel"]=0;
		}
		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["cancel"]=0;
		}
		$wgWizFlow[$i]["save"]=$i+1;
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
		$wgWizFlow[$i]["cancel"]=0;
		
		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>