<?php
	/******************************************************************
	 edit.object.data.save.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: see system.save.data.phtml
	 Grant needed: read
	 Global variables: none

	 This template is a wrapper around system.save.data.phtml. It is
	 meant to be used as the last step in a wizard.

	 If system.save.data.phtml doesn't return an error, it will call
	 the javascript function 'objectadded(type, name, path)' in its
	 opener document and then close the current window.
	 
	 no result

	******************************************************************/
	$arIsNewObject=$this->arIsNewObject;
	$arCallArgs["disabled"]	= $this->getdata("disabled", "none");
	$this->call("system.save.data.phtml",$arCallArgs);
	if ($this->error) {
		?>
			<font color="red" face="arial,helvetica,sans-serif" size=+1><?php echo $this->error; ?></font><p>
		<?php
	} else {
		?>
			<script> 
				function done() {
					if (top.window.opener) {
						if (top.window.opener.objectadded) {
							top.window.opener.objectadded('<?php echo $this->type; ?>','<?php echo AddCSlashes($this->nlsdata->name, ARESCAPE); ?>','<?php echo $this->path; ?>'); 
						}
						<?php
							if (!$arIsNewObject || $this->getdata("arCloseWindow", "none")) {
						?>
								top.window.close();
						<?php
							} else {
						?>
								top.window.location.href='object.new.select.phtml';
						<?php
							}
						?>
					} else if (top.window.dialogArguments) {
						arr=new Array();
						arr['type']='<?php echo $this->type; ?>';
						arr['name']='<?php echo AddCSlashes($this->nlsdata->name, ARESCAPE); ?>';
						arr['path']='<?php echo $this->path; ?>';
						top.window.returnValue=arr;
						top.window.close();
					}
				}
				done();
			</script>
		<?php
	}
?>