<?php
	/******************************************************************
	 edit.object.data.save.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------

	 no result.
 
	******************************************************************/

	$arIsNewObject=$this->arIsNewObject;
	$this->call("system.save.data.phtml",$arCallArgs);
	if ($this->error) {
		?>
			<font color="red" face="arial,helvetica,sans-serif" size=+1><?php echo $this->error; ?></font><p>
		<?php
	} else {
		$folder=$this->call("system.get.folder.phtml");
		$arReturnPath=$this->path;
		$arReturnTemplate="js.window.objectadded.phtml?arIsNewObject=".RawUrlEncode($arIsNewObject);
		if (($password=$this->getdata("newpass1","none")) && 
				($this->data->login==$AR->user->data->login)) {
			$arReturnPage=$this->store->root.$this->path."login.phtml?ARLogin=".RawUrlEncode($data->login).
				"&ARPassword=".RawUrlEncode($password)."&arReturnPath=".RawUrlEncode($arReturnPath).
				"&arReturnTemplate=".RawUrlEncode($arReturnTemplate);
		} else {
			$arReturnPage=$this->store->root.$arReturnPath.$arReturnTemplate;
		}
		?>
			<script> 
				if (window.opener.top.tree) {
					<?php
						if ($arIsNewObject) {
							echo "  window.opener.top.tree.AddLinks('{$this->parent}','{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
						} else {
							echo "  window.opener.top.tree.UpdateLinks('{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
						}
					?>
					document.location='<?php echo $arReturnPage; ?>';
				}
			</script>
		<?php
	}
?>