<?php
	/******************************************************************

	 no result.

	******************************************************************/
	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset id="preferences">
		<legend><?php echo $ARnls["preferences"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<?php echo $ARnls["language"]; ?>
				</td><td>
					<select name="language" style="width: 100px;">
					<?php
						$language=$this->getdata("language","none");
						if (!$language) {
							$language=$nls;
						}
						reset($AR->nls->list);
						while (list($key, $value)=each($AR->nls->list)) {
							if ($key==$language) {
								echo "<option value=\"$key\" selected>$value</option>\n";
							} else {
								echo "<option value=\"$key\">$value</option>\n";
							}
						}
					?>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $ARnls["interface"]; ?>
				</td><td>
					<select name="interface" style="width: 100px;">
							<?php $interface=$this->getdata("interface","none"); ?>
							<option value="new" <?php if ($interface=="new") { echo "selected"; } ?>><?php echo $ARnls["new"]; ?></option>
							<option value="classic" <?php if ($interface=="classic") { echo "selected"; } ?>><?php echo $ARnls["classic"]; ?></option>
							<option value="winxp" <?php if ($interface=="winxp") { echo "selected"; } ?>><?php echo $ARnls["winxp"]; ?></option>
					</select>
				<td>
			</tr>
			<tr>
				<td>
					<?php echo $ARnls["editor"]; ?>
				</td><td>
					<select name="editor" style="width: 100px;">
							<?php $editor=$this->getdata("editor","none"); ?>
							<option value="wysiwyg"><?php echo $ARnls["wysiwyg"]; ?></option>
							<option value="text" <?php if ($editor=="text") { echo "selected"; } ?>><?php echo $ARnls["text"]; ?></option>
					</select>
				<td>
			</tr>
			</table>
		</fieldset>
		<fieldset>
		<legend><?php echo $ARnls["contactinformation"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td><?php echo $ARnls["email"]; ?></td>
				<td>
					<input type="text" name="email" value="<?php echo $this->getdata("email", "none"); ?>">	
				</td>
			</tr><tr>
				<td><?php echo $ARnls["telephone"]; ?></td>
				<td>
					<input type="text" name="telephone" value="<?php echo $this->getdata("telephone", "none"); ?>">	
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<?php
	}
?>