<?php
  /******************************************************************
   form.phtml                                      Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read")) {
?>
<body bgcolor="white">
<?php
  $this->parents($this->path, "ShowLink.phtml","target=edit.phtml");
?>
<form>
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="newtype" value="<?php echo $newtype; ?>">
<input type="hidden" name="newparent" value="<?php echo $this->path; ?>">
<input type="hidden" name="newfilename" value="<?php echo $newfilename; ?>">
<?php
include($this->store->code."widgets/formlock/js.html");
?>

<table border="0" width="100%" cellspacing="0">
<tr>
  <td bgcolor="#404074" colspan="2">
    <font face="helvetica, sans-serif" color="white"><b><?php $ARnls["userdata"]; ?>
    <?php if (!$newtype) { echo $data->login; } else { echo $newfilename; } ?></b></font>
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <input type="text" name="name" maxlength="50" value="<?php $this->showdata("name"); ?>">
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["password"]; ?>&nbsp:</b></font>
  </td>
  <td>
    <input type="password" name="newpass1" value="">
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["again"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <input type="password" name="newpass2" value="">
  </td>
</tr><tr>
  <td bgcolor="#404074" colspan="2">
    <font face="helvetica, sans-serif" color="white"><b><?php echo $ARnls["configuration"]; ?></b></font>
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["language"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <select name="language">
    <?php
      if (!$newtype) {
        $language=$data->language;
      } else {
        $language=$ARCurrent->default;
      }
      reset($AR->nls->list);
      while (list($key, $value)=each($AR->nls->list)) {
        if ($key==$language) {
          echo "<option value=\"$key\" selected>$value</option>\n";
        } else {
          echo "<option value=\"$key\">$value</option>\n";
        }
      }
    ?>
    </select>
	<font face="helvetica, sans-serif"><b>Interface&nbsp;:</b></font>
    <select name="interface">
		<option value="classic">Classic</option>
		<option value="new" <?php if ($data->interface=="new") { echo "selected"; } ?>>New</option>
	</select>
  </td>
</tr><tr>
  <td></td>
  <td><font face="helvetica, sans-serif"><i><?php echo $ARnls["changenls"]; ?></i></font></td>
</tr><tr>
  <td>
    <?php if ($newtype) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">
<?php
    $wgRecurseConfirm=$ARnls["q:removeuser"];
	$wgRecurseAction="delete";
	$wgRecurseTitle=$ARnls["delete"];
    include($this->store->code."widgets/recurse/form.js");
	include($this->store->code."widgets/recurse/form.html");
?>
    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>
</form>
<font face="helvetica, sans-serif" size="2">
<?php
  $this->ls("","Show.phtml","target=edit.phtml");
?>
</font>
</body>
<?php
  }
?>