<?php
	$continue=true;
	if ($locks) {
		reset($_POST);
		while (list($key,$val)=each($_POST)) {
			if (substr($key,0,6)=="unlock") {
				$this->store->mod_lock->unlock($this->data->login,$path=substr($key,7));
			}
		}
		if ($arReturnPage) {
			ldRedirect($arReturnPage);
			$continue=false;
		}
	}
	if ($continue) {
		$locks=$this->store->mod_lock->get_locks($this->data->login);

		if ( ( (!is_array($locks)) || (count($locks) == 0) ) && $arReturnPage ) {
			ldRedirect($arReturnPage);
			$continue=false;
		}
	}
	if ($continue) {
	?>
<html>
<head>
<title><?php printf($ARnls["openlocks"],$nlsdata->name); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<style>
	.required {
		background-color: buttonface;
		border: 2px outset;
		padding: 2px;
		font-weight: bold;
	}	
	.required div {
		width: 100%;
	}
	td.type {
		width: 22px;
		padding-left: 2px;
	}
	a.button {
		border: 1px outset;
	}
	input {
		width: 75px;
	}
	.row0 td {
		background-color: white;
	}
	.row1 td {
		background-color: #EEEEEE;
	}
</style>
</head>
<body bgcolor="white">
<script>
	if (document.all) {
		window.innerHeight=document.body.clientHeight;
		window.innerWidth=document.body.clientWidth;
	}	
	function toggleAll() {
		var boxes = document.getElementsByClassName('checkbox');
		if (boxes.length) {
			var check = !boxes[0].checked;
			for (var i = 0; i < boxes.length; i++) {
				boxes[i].checked = check;
			}
		}
	}
</script>

<form method="post" style="height: 95%">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<table border="0" width="100%" height="100%" align="center" cellspacing="2" vspace="10" hspace="10">
<th><?php printf($ARnls["openlocks"],$nlsdata->name); ?></th>
<tr>
	<td colspan="2" bgcolor="white" style="border: 2px inset; padding: 0px;" height="90%" valign="top">

	<div style="height: 100%; width: 100%; overflow: auto; margin: 0px; border: 0px;">
		<table border="0" bgcolor="white" width="100%" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="top" class="required" colspan="2">
				<div><?php echo $ARnls["path"]; ?></div>
			</td><td valign="top" colspan="2" class="required">
				<div><?php echo $ARnls["expires"]; ?></div>
			</td><td valign="top" class="required" style="width: 150px;">
				<div>
					<?php echo $ARnls["unlock"]; ?>
					<span style="float: right; padding-right: 40px; text-decoration: underline;"><a href="#" onclick="toggleAll(); return false;"><?php echo $ARnls["all"]; ?></span>
				</div>
			</td>
		</tr>
<?php
	$currcol=0;
	if(is_array($locks)){
		while (list($path,$lock)=each($locks)) {
			echo "<tr class=\"row".$currcol."\"><td align=\"left\"><font face=\"helvetica,sans-serif\">";
			echo $path;
			echo "</td><td></td><td align=\"left\">";
			echo date("d-m-Y H:i:s",$lock["release"]);
			echo "</td><td></td><td align=\"center\">";
			echo "<input class=\"checkbox\" type=\"checkbox\" name=\"unlock_$path\">";
			echo "</td></tr>";
			$currcol++;
			$currcol=$currcol%2;
		}
	}
?>
		</table>
	</div>
	</td>
</tr><tr>
	<td valign="bottom" align="right"><input type="submit" name="locks" value="<?php echo $ARnls["ok"]; ?>"></td>
</tr>
</table>
</form>
</body>
</html>
<?php
	}
?>