<?php
	if ($this->CheckLogin("read")) {
		if ($AR->user->data->login==$data->login || $AR->user->data->login=="admin") {
			if (!$checkedlocks) {
				ldRedirect("lock.user.report.phtml?arReturnPage=logoff.phtml?checkedlocks=true");
			} else {
				$ARCurrent->session->kill();
				unset($ARCurrent->session);
				?>
					<h1>Goodbye <?php echo $data->name; ?>.</h1>
					<form action="<?php echo $AR->dir->www; ?>">
						<input type="submit" value="<?php echo $ARnls["login"]; ?>">
					</form>
				<?php
			}
		} else {
			?>
				<h2>Sorry, you can only logoff yourself.</h2>
			<?php
		}
	}
?>