    <table border="0">
      <td>
        <span class="required"><?php echo $ARnls["login"]; ?></span>
      </td>
    </tr><tr>
      <td valign="top">
        <input type="text" name="arNewFilename" size="16" maxlength="32" value="<?php echo $this->getdata("arNewFilename","none"); ?>">
      </td>
    </tr>
    </table>
    <script>
      function forminit() { 
        document.wgWizForm.arNewFilename.select();
        document.wgWizForm.arNewFilename.focus();
      }
      window.onload=forminit;
    </script>
    <?php
      $arResult["next"]["arNewFilename"]["ereg"]="^[a-zA-Z0-9_\.-]+\$";
      $arResult["next"]["arNewFilename"]["error"]=AddCSlashes(sprintf($ARnls["err:fileillegalchars"], ""), ARESCAPE);
    ?>