<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	$customoffset=0;
	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				$customoffset=1;
				break;
			}
		}
	}
	if (count($ARConfig->nls->list)>1) { // more than one language available
		$languages=true;
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.filename.phtml";
	$user="edit.object.data.form.phtml";
	$preferences="edit.object.data.preferences.phtml";
	$groups="edit.object.data.groups.phtml";
	$finish="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$finish;

	$i++;
	$arFlow[$i]["title"]=$ARnls["login"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$start;

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$user;

	$i++;
	$arFlow[$i]["title"]=$ARnls["preferences"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$preferences;

	if ($this->CheckSilent("config")) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["groups"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$arFlow[$i]["template"]=$groups;
	}

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}
	
	$wgWizCurrent=$this->getdata("wgWizCurrent","none");
	$wgWizControl=$this->getdata("wgWizControl","none");
	if ($wgWizCurrent==1) {
		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arFlow[0]["error"]=$ARnls["err:mustenterlogin"];
			$ARCurrent->wgWizNextStep=1;
		} else {
			$criteria["login"]["value"]["="]="'".AddSlashes($arNewFilename)."'";
			$result=$this->find("/system/users/", $criteria, "system.get.phtml");
			if ($result) {
				$arFlow[0]["error"]=sprintf($ARnls["err:loginexists"],$newfilename);
				$ARCurrent->wgWizNextStep=1;
			}
		}	
	} else if ( $wgWizCurrent == 2 ) {
		global $HTTP_POST_VARS;

		$profile = $this->getdata("profile", "none");
		if ($profile && $this->getdata("arProfileLoaded", "none") != $profile) {
			$pdata = current($this->get($profile,'system.get.data.phtml'));
			if (is_object($pdata)) {
				$HTTP_POST_VARS["language"] = $pdata->language;
				$HTTP_POST_VARS["interface"] = $pdata->interface;
				$HTTP_POST_VARS["editor"] = $pdata->editor;
				$HTTP_POST_VARS["email"] = $pdata->email;
				$HTTP_POST_VARS["telephone"] = $pdata->telephone;
				if (is_array($pdata->groups)) {
					reset($pdata->groups);
					while (list($key, $val)=each($pdata->groups)) {
						$HTTP_POST_VARS["groups"][$key] = $val;
					}
				}
				$HTTP_POST_VARS["arProfileLoaded"] = $profile;
			}
		}
	}
	$arResult=$arFlow;
?>