<?php

  function GetPassword($pass1, $pass2) {
    if ($pass1 && ($pass1==$pass2)) {
      $password=ARCrypt($pass1);
    }
    return $password;
  }  

  if ($newtype) { // save a new object
    // check for {id} type filename/login
    $newdata=new object;
    if (ereg("{.*}",$newfilename)) {
      $error=$ARnls["err:donotuseid"];
    } else { // now check for existing login
      $criteria["login"]["value"]["="]="'".ereg_replace("'","''",$newfilename)."'";
      $result=$this->find("/system/users/", $criteria, "Get.phtml");
      if ($result) {
        $error=sprintf($ARnls["err:loginexists"],$newfilename);
      } else {
        $newdata->login=$newfilename;
      }
    }
  } else {
    $newdata=$data;
  }
  $properties["name"][0]["value"]="'".AddSlashes($newname)."'";
  $properties["login"][0]["value"]="'".AddSlashes($newdata->login)."'";
  $newdata->name=$name;
  $newdata->language=$language;
  $newdata->interface=$interface;
  if ($newpass1 || $newpass2) {
    if (!($newdata->password=GetPassword($newpass1,$newpass2))) {
      $error=$ARnls["err:validpassword"];
    } else if (!$error && ($newdata->login==$AR->user->data->login)) {
      $returnpage=$this->store->root.$this->path."login.phtml?ARLogin=".RawUrlEncode($newdata->login)."&ARPassword=".RawUrlEncode($newpass1)."&arReturnPage=".RawUrlEncode($this->path);
    }
  } else {
    if ($newtype) {
      $error=$ARnls["err:validpassword"];
    }
  }
  include($this->store->code."includes/save.dir.phtml");
?>