<?php
  // show all 'readable' data 
  if ($target) { 
    echo "<a href=\"".$this->store->root.$this->path.$target."\"".
         " onClick=\"if (top.tree) { top.View('$this->path','$target'); return false; }\">";  
  } else {
    echo "<a href=\"".$this->store->root.$this->path."\"".
         " onClick=\"if (top.tree) { top.View('$this->path'); return false; }\">";
  }
?><img src="<?php 
  echo $AR->dir->images; ?>icons/<?php echo $this->type; ?>.gif" alt="[view]" border="0"> 
<?php
  if (!$this->CheckSilent("read")) {
    echo "<font color=\"#CCCCCC\"><b>$data->name</b></font>";
  } else {
    echo "<b>$data->name</b>";
  }
?></a> <?php echo $data->login; ?><br>
