<?php
	if ($this->CheckLogin('passwordchange') && $this->CheckConfig()) {
		if (!$this->CheckPassword($chpwdPassword)) {
			$this->error = $ARnls["passwordincorrect"];
		} else {
			$newPassword = ($chpwdNewPassword1 && ($chpwdNewPassword1 == $chpwdNewPassword2)) ? puser::hashPassword($chpwdNewPassword1) : false;
			if (!$newPassword) {
				$this->error = $ARnls["err:validpassword"];
			} else {
				$data = current($this->get($this->path, 'system.get.data.phtml'));
				$data->password = $newPassword;
				$this->store->save($this->path, $this->type, $data);
				if ($this->store->error) {
					$this->error = $this->store->error;
					unset($this->store->error);
				}
			}
		}
	}
?>
