<?php
	include($this->store->get_config("code")."configs/authentication.phtml");
	require_once($this->store->get_config("code")."modules/mod_error.php");

	$this->data = current($this->get($this->path, "system.get.data.phtml"));

	$passentry = $this->data->config->password_array[$code];
	if (!$passentry) {
		$this->error = $ARnls["err:activationincorrect"];
		$arResult = error::raiseError($this->error, 1);
	} else {

		unset($this->data->config->password_array[$code]);

		if ($passentry['ctime'] + $auth_config['genpassexpiry'] < time()) {
			$this->error = $ARnls["err:activationexpired"];
			$this->store->save($this->path, $this->type, $this->data);
			$arResult = error::raiseError($this->error, 2);
		} else {
			$this->data->password = $passentry['password'];
			$arResult = $this->store->save($this->path, $this->type, $this->data);
		}

	}
?>
