<?php
	include($this->store->get_config("code")."configs/authentication.phtml");

	$this->data = current($this->get($this->path, "system.get.data.phtml"));
	$passentry = $this->data->config->password_array[$code];
	if (!$passentry) {
		// FIXME: create a new nls entry for this error
		$this->error = $ARnls["err:wronggrants"];
		return false;
	}
	if ($passentry['ctime'] + $auth_config['genpassexpiry'] < time()) {
		// FIXME: create a new nls entry for this error
		$this->error = $ARnls["err:wronggrants"];
		unset($this->data->config->password_array[$code]);
		$this->save();
		return false;

	}
	$this->data->password = $passentry['password'];

	// save the object
	$arResult = $this->save();
?>