<?php
	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		$criteria["login"]["value"]["="]="'".AddSlashes($this->data->login)."'";
		$result = $this->find("/system/users/", $criteria, "system.get.phtml");
		if (is_array($result) && current($result)) {
			$this->error = $ARnls["user"]." ".sprintf($ARnls["err:alreadyexists"],$this->data->login);
			// FROP $this->error = "user '".$this->data->login."' already exists";
		} else {
			$this->store->save(
				$this->path,
				$this->type,
				$this->data,
				$this->properties,
				$this->vtype,
				$this->priority);
				$this->error = $this->store->error;
		}
	}
?>