<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		$grouppath = "/system/groups/";

		$criteria["login"]["value"]["="]=$this->data->login;
		$result = $this->find("/system/users/", $criteria, "system.get.phtml");
		if (is_array($result) && current($result)) {
			if (substr($this->path, 0, strlen($grouppath)) == $grouppath ){
				$user = current($result);
				$user->link($this->path);
				$this->error = $user->error;
			} else{
				$this->error = $ARnls["user"]." ".sprintf($ARnls["err:alreadyexists"],$this->data->login);
			}
		} else {
			$this->store->save(
				$this->path,
				$this->type,
				$this->data,
				$this->properties,
				$this->vtype,
				$this->priority);
				$this->error = $this->store->error;

				if ($ARCurrent->AXAction == "import") {
					if (is_array($this->data->groups)) {
						reset($this->data->groups);
						while (list($key, $val)=each($this->data->groups)) {
							if ($this->exists($key)) {
								$target = $key.substr($this->path, strlen($this->parent));
								display("		adding (".$this->path." to $target)\n");
								$this->get($key, "system.set.user.phtml", Array("path" => $this->path, "action" => "add"));
							}
						}
					}
				}
		}
	}
?>