<?php
	if (!$setDummyObject) {
		$this->properties=$this->load_properties('%'); // get properties for all scopes
		if (!$ARCurrent->options["without_grants"]) {
			$this->call("system.export.get.grants.phtml");
		}
	} else {
		$this->dummy_save=1;
	}

	/* 
		unset grants defined on this object, they will be resetted after
		the complete database has been imported
	*/
	unset($this->data->config->grants);
	unset($this->data->config->usergrants);
	$arResult=clone $this;
?>
