<?php   
	if ($this->CheckSilent("delete")) {
		if (!$this->lock("T")) {
			$this->error = ar::error( $ARnls["err:cannotlockobject"], 1105);
		} else {
			if ($this->AR_implements("pgroup")) {
				$systempath = "/system/groups/";
			} else {
				$systempath = "/system/users/";
			}
			if (substr($this->path, 0, strlen($systempath))==$systempath) {
				// this is a live user object, not a link in a group
				if ($this->data->login=="public" || $this->data->login=="admin") {
					$this->error = ar::error($ARnls["err:cannotdelsystemusers"], 1116);
				} else {
					if (is_array($this->data->config->usergrants)) {
						// remove usergrants
						while (list($key, $value)=each($this->data->config->usergrants)) {
							$this->get($key, "system.save.grants.phtml", array("delete" => true, "id" => $this->data->login, "type" => $this->type));
						}
					}
					if (is_array($this->data->groups)) {
						// remove user object from groups
						while (list($key, $value)=each($this->data->groups)) {
							$this->get($key, "system.set.user.phtml", array("path" => $this->path, "action" => "delete"));
						}
					}
				}
			} else {
				// this is probably a link in a group
				$parentobject=current($this->get($this->parent, "system.get.phtml"));
				if ($parentobject && $parentobject->AR_implements("pgroup")) {
					// so it is, so remove the user from the group
					// which will by the way also delete the current object
					// first get the original users path
					$crit["login"]["value"]["="]=$this->data->login;
					$realuser=current($this->find("/system/users/",$crit,"system.get.phtml"));
					if ($realuser && $realuser->path) {
						$realpath=$realuser->path;
						$parentobject->call("system.set.user.phtml", array("path" => $realpath, "action" => "delete"));
					}
				}
			}
			if (!$this->error) {
				$arResult = $this->call("pobject::system.delete.phtml",$arCallArgs);
			}
		}
	} else {
		$this->error = ar::error( $ARnls["nopermission"], 1117);
	}
?>