<?php
	if ($this->CheckLogin("config")) { 
		include_once($this->store->code."includes/DelGrant.phtml");
		$searchpath["pgroup"]="/system/groups/";
		$searchpath["puser"]="/system/users/";
		$criteria["login"]["value"]["="]="'".AddSlashes($id)."'";
		if ($delete) {
			$data->grants[$type]=DelGrant($data->grants[$type], $id, $grant);
			if ($id==$data->login && $type==$this->type) {
				$data->usergrants=DelGrant($data->usergrants, $this->path, $grant);
			} else {
				$this->find($searchpath[$type], $criteria, "updategrant.phtml", 
							"action=delete&path=".RawUrlEncode($this->path)."&grant=".RawUrlEncode($grant));
			}
		} else if ($newgrants) {
			if ($type=@current($this->get($path, "system.get.type.phtml"))) {
				if ($this->store->implements($type, "puser")) {
					if ($id=@current($this->get($path, "system.get.id.phtml"))) {
						$criteria["login"]["value"]["="]="'".AddSlashes($id)."'";
						$newgrants=ereg_replace("[[:space:]]"," ",$newgrants);
						$newgrant=strtok($newgrants, " ");
						if ($newgrant==".") {
							// first retrieve the current inherited grants, and replace "." with them
							if ($result=@current($this->find($searchpath[$type],$criteria,"system.get.grants.phtml","path=".RawUrlEncode($this->path) ) ) ) {
								$current=implode(" ", array_keys($result));
								$newgrants=ereg_replace(" ?\. ?",AddSlashes($current),$newgrants);		
							}
							// now get the next grant ("." is already processed)
							$newgrant=strtok($newgrants, " ");
						} else if (ereg("({(.*)})",$newgrant,$regs)) {
							// first retrieve the grants from the specified user or group 
							if ($data->grants[$type][$regs[2]]) {
								while (list($grant,$value)=each($data->grants[$type][$regs[2]])) {
									if ($value) {
										$cloned.=$grant." ";
									}
								}
							}
							// replace the match with the cloned grants
							$newgrants=ereg_replace(" ?".$regs[1]." ?",AddSlashes($cloned),$newgrants);
							// now get the next grant
							$newgrant=strtok($newgrants, " ");
						}
						while ($newgrant) {
							if ($newgrant!=".") {
								if (substr($newgrant,0,1)=="-") {
									$delgrant=substr($newgrant,1);
									$data->grants[$type]=DelGrant($data->grants[$type],$id,$delgrant);
									if ($id==$data->login && $type==$this->type) {
										$data->usergrants=DelGrant($data->usergrants, $this->path, $delgrant);
									} else {
										$this->find($searchpath[$type], $criteria, "updategrant.phtml", 
													"action=delete&path=".RawUrlEncode($this->path)."&grant=".RawUrlEncode($delgrant));
									}
								} else {
									if (substr($newgrant,0,1)=="+") {
										$newgrant=substr($newgrant,1);
									}
									$data->grants[$type][$id][$newgrant]=1;
									if ($id==$data->login && $type==$this->type) {
										$data->usergrants[$this->path][$newgrant]=1;
									} else {
										$this->find($searchpath[$type], $criteria, "updategrant.phtml", 
												"action=add&path=".RawUrlEncode($this->path)."&grant=".RawUrlEncode($newgrant));
									}
								}
							}
							$newgrant=strtok(" ");
						}
					}
				}
			}
		}
		$this->save($this->path, $this->type, $data, $properties);
		Header("Location: $returnpage");
		?>
			<a href="<?php echo $returnpage; ?>">Continue</a>
		<?php
	}
?>