<?php
	if ($this->CheckConfig()) {
		$this->data = current($this->get($this->path, "system.get.data.phtml"));

		srand((double)microtime()*1000000);
		$code		= md5(uniqid(rand(), true));

		if (!$password) {
			$passlen	= 6;
			$password	= "";
			$valid_chars	= array();
			for ($c = ord('2'); $c <= ord('9'); $c++) {
				$valid_chars[] = chr($c);
			}
			for ($c = ord('a'); $c <= ord('z'); $c++) {
				if (!in_array(chr($c), array('o', 'i', 'l'))) {
					$valid_chars[] = chr($c);
					$valid_chars[] = strtoupper(chr($c));
				}
			}

			while ($passlen--) $password .= $valid_chars[rand(0, count($valid_chars)-1)];
		}

		if (is_array($this->data->config->password_array)) {
			if (count($this->data->config->password_array) >= 10) {
					array_shift($this->data->config->password_array);
			}
		} else {
			$this->data->config->password_array = array();
		}
		$this->data->config->password_array[$code] = array("password" => $this->hashPassword($password), "ctime" => time());

		$this->store->save($this->path, $this->type, $this->data);

		$arResult = array(
			"password"	=> $password,
			"code"		=> $code,
			"name"		=> $data->name,
			"email"		=> $data->email
		);
	}
?>
