<?php
	if ($AR->user && ($AR->user->data->login=="admin" || $AR->user->grants["config"])) { // can not be called directly from loader
		switch($action) {
			case "delete" :
				if (!$grant) {
					unset($data->usergrants[$path]);
				} else {
					unset($data->usergrants[$path][$grant]);
					if (!@count($data->usergrants[$path])) {
						unset($data->usergrants[$path]);
					}
				}
			break;
			case "add" :
				$data->usergrants[$path][$grant]=1;
			break;
		}
		$this->save($this->path, $this->type, $data, "");
	}
?>