<?php
	/******************************************************************
	 system.save.grants.user.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $action, $path, $grant
	 Grant needed: none
	 Global variables: none 

	 This template adds a grant to the user grants table of this user.
	 First it checks whether the user who is applying the grant has 
	 sufficient grants in the given path (path) to add/delete the
	 grant.

	 The template checks whether a user is logged on, it can only be 
	 called from another template which calls CheckLogin() first.

	 $action: "add" or "delete"
	 $path: path to the object on which the grant is added.
	 $grant: name of the grant to apply.

	 result: "ok" or an error message.

	******************************************************************/

	// first check whether the user has the config grant on the given path
	debug("puser/system.save.grants.user.phtml: $this->path","class");
	$grants=@current($this->get($path, "system.get.grants.phtml"));
	if ($AR->user && ($AR->user->data->login=="admin" || $grants["config"])) { // can not be called directly from loader
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=@current($this->get(".","system.get.data.phtml"));
		switch($action) {
			case "delete" :
				unset($this->data->usergrants[$path][$grant]);
				if (!@count($this->data->usergrants[$path])) {
					unset($this->data->usergrants[$path]);
				}
				break;
			case "add" :
				$this->data->usergrants[$path][$grant]=1;
				break;
		}
		if ($this->save()) {
			$arResult="ok";
		} else {
			$arResult=$this->error;
		}
	} else {
		$arResult="Access denied";
	}
	debug("res:".$arResult);
?>