<?php
	debug("puser::system.set.group.phtml: $action $path","class");
	// first check wether the user has edit grant on the given group.
	if ($this->get($path,"system.check.grant.phtml",array('grant' => "edit") ) ) {
		$granted=true;
	} else {
		$granted=false;
	}
	if ($granted) {
		// FIXME: check whether $path is a group?
		// now make sure this->data is clean.
		$this->data=current($this->get($this->path, "system.get.data.phtml"));
		if ($action=="add") {
			$this->data->config->groups[$path]=$id;
			$this->data->groups[$path]=$id;
			$this->save();
		} else {
			unset($this->data->config->groups[$path]);
			unset($this->data->groups[$path]);
			$this->save();
		}
	}
?>
