<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/
	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new object;
		}


		function GetPassword($pass1, $pass2) {
			if ($pass1 && ($pass1==$pass2)) {
				$password=ARCrypt($pass1);
			}
			return $password;
		}	

		$pass1=$this->getdata("newpass1","none");
		$pass2=$this->getdata("newpass2","none");
		if ($pass1 || $pass2 ) {
			if (!($this->data->password=GetPassword($pass1,$pass2))) {
				$this->error=$ARnls["err:validpassword"];
			}
		}
		$properties["value"][]["value"]="'".AddSlashes($value)."'";
		$this->data->name=$this->getdata("name","none");
		$properties["name"][]["value"]="'".AddSlashes($this->data->name)."'";
		$properties["text"][]["value"]="'".AddSlashes($this->data->name)."'";
		if ($this->arIsNewObject) {
			$login=$this->getdata("arNewFilename","none");
			if ($login) {
				$criteria["login"]["value"]["="]="'".AddSlashes($login)."'";
				$result=$this->find("/system/users/",$criteria,"system.get.phtml");
				if ($result) {
					$this->error=sprintf($ARnls["err:loginexists"],$login);
				} else {
					if (ereg('\{.*\}',$login)) {
						$this->error=$ARnls["err:donotuseid"];
					} else {
						$this->data->login=$login;
						$properties["login"][0]["value"]="'".AddSlashes($login)."'";
						if (!$this->data->password) {
							$this->error=$ARnls["err:validpassword"];
						}
					}
				}
			} else {
				$this->error=$ARnls["err:mustenterlogin"];
			}
		}
		if ($this->arIsNewObject && ($profile=$this->getdata("profile","none"))) {
			// fill in values from the given profile
		}
		if ($language=$this->getdata("language","none")) {
			$this->data->language=$language;
		}
		if ($interface=$this->getdata("interface","none")) {
			$this->data->interface=$interface;
		}
		if (!$this->error) {
			$this->save($properties);
			if (!$this->error) {
				if (($groups=$this->getdata("groups","none")) && ($groups!=$this->data->groups)) {
					// overrides data from profile
					reset($groups);
					while (list($key, $group)=each($groups)) {
						if (!$this->data->groups[$group]) {
							$this->get($group, "system.set.user.phtml", Array(
								"action" => "add",
								"path" => $this->path));
						}
					}
					@reset($this->data->groups);
					while (list($group, $value)=@each($this->data->groups)) {
						if (!in_array($group, $groups)) {
							$this->get($group, "system.set.user.phtml", Array(
								"action" => "delete",
								"path" => $this->path));
						}
					}
				} 
			}
		}
	}
?>