<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
		$target=$this->getdata("target");
		$target=$this->store->make_path($this->parent, $this->getdata("target","none"));
		if (substr($this->path, 0, strlen('/system/users/'))=='/system/users/') {
			// this is a live user object, not a link in a group
			if (substr($target, 0, strlen('/system/users/'))!='/system/users/') {
				$this->error=$ARnls["err:invaliduserlocation"];
			} else if ($this->data->login=="public" || $this->data->login=="admin") {
				$this->error=$ARnls["err:cannotdelsystemusers"];
			} else {
				if (!$this->exists($target)) {
					// new filename -> new login, so check if it is unique
					$newparent=$this->store->make_path($target, "..");
					$newlogin=substr($target, strlen($newparent), -1);
					$crit["login"]["value"]["="]="'".AddSlashes($newlogin)."'";
					$result=$this->find("/system/users/",$crit,"system.get.id.phtml");
					if ($result) {
						$this->error=sprintf($ARnls["err:loginexists"],$newlogin);
					}
				}
				if (!$this->error) {
					$this->call("pobject::system.rename.phtml", $arCallArgs);
					$this->data->login=substr($this->path, strlen($this->parent), -1);
					$properties["login"][0]["value"]="'".AddSlashes($this->data->login)."'";
					$this->save($properties);
				}
			}
		} else {
			// this is probably a link in a group
			$parentobject=current($this->get($this->parent, "system.get.phtml"));
			if ($parentobject && $parentobject->implements("pgroup")) {
				// so it is, so remove the user from the group
				// which will by the way also delete the current object
				// first get the original users path
				$crit["login"]["value"]["="]="'".AddSlashes($this->data->login)."'";
				$realuser=current($this->find("/system/users/",$crit,"system.get.phtml"));
				if ($realuser && $realuser->path) {
					$realpath=$realuser->path;
					$parentobject->call("system.set.user.phtml", Array("path" => $realpath, "action" => "delete"));
				}
			}
		}			
	}
	$arResult=$target;
?>