<?php
	if (!($setDummyObject??null)) {
		$this->properties=$this->load_properties('%'); // get properties for all scopes
		if (!($ARCurrent->options["without_grants"]??null)) {
			if ($this->data->config->grants ?? null) {
				while (list($type, $type_val)=@each($this->data->config->grants)) {
					while (list($user,$grants)=@each($type_val)) {
						while (list($grant, $value)=@each($grants)) {
							//display("exporting grants [$type][$user][$this->path][$grant]\n");
							$ARCurrent->grants_list[$type][$user][$this->path][$grant]=$value;
						}
					}
				}
			}
		}
	} else {
		$this->dummy_save=1;
	}

	/* 
		unset grants defined on this object, they will be resetted after
		the complete database has been imported
	*/
	unset($this->data->config->grants);
	unset($this->data->config->usergrants);
	$arResult=clone $this;
?>
