<?php
	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		
		$grouppath = "/system/groups/";

		$criteria["login"]["value"]["="]="'".AddSlashes($this->data->login)."'";
		$result = $this->find("/system/users/", $criteria, "system.get.phtml");
		if (is_array($result) && current($result)) {
			if (substr($this->path, 0, strlen($grouppath)) == $grouppath ){
				$user = current($result);
				$user->link($this->path);
				$this->error = $user->error;
			} else{
				$this->error = $ARnls["user"]." ".sprintf($ARnls["err:alreadyexists"],$this->data->login);
			}
		} else {
			$this->store->save(
				$this->path,
				$this->type,
				$this->data,
				$this->properties,
				$this->vtype,
				$this->priority);
				$this->error = $this->store->error;
		}
	}
?>