<?php
	if (!$setDummyObject) {
		$this->properties=$this->load_properties('%'); // get properties for all scopes
		if (!$ARCurrent->options["without_grants"]) {

			foreach ($this->data->config->grants as $type => $type_val) {
				foreach ($type_val as $user => $grants) {
					foreach ($grants as $grant => $value) {
						//display("exporting grants [$type][$user][$this->path][$grant]\n");
						$ARCurrent->grants_list[$type][$user][$this->path][$grant]=$value;
					}
				}
			}
		}
	} else {
		$this->dummy_save=1;
	}

	/* 
		unset grants defined on this object, they will be resetted after
		the complete database has been imported
	*/
	unset($this->data->config->grants);
	unset($this->data->config->usergrants);
	$arResult=clone $this;
?>
