<?php
	if ($this->CheckConfig()) {
		$this->data = current($this->get($this->path, "system.get.data.phtml"));

		$code	= bin2hex(random_bytes(16));

		if (!$password) {
			$passlen	= 8;
			$password	= "";
			$valid_chars	= array();
			for ($c = ord('2'); $c <= ord('9'); $c++) {
				$valid_chars[] = chr($c);
			}
			for ($c = ord('a'); $c <= ord('z'); $c++) {
				if (!in_array(chr($c), array('o', 'i', 'l'))) {
					$valid_chars[] = chr($c);
					$valid_chars[] = strtoupper(chr($c));
				}
			}
			$max = count($valid_chars)-1;
			while ($passlen--) $password .= $valid_chars[random_int(0, $max)];
		}

		if (is_array($this->data->config->password_array)) {
			if (count($this->data->config->password_array) >= 10) {
					array_shift($this->data->config->password_array);
			}
		} else {
			$this->data->config->password_array = array();
		}
		$this->data->config->password_array[$code] = array("password" => $this->hashPassword($password), "ctime" => time());

		$this->store->save($this->path, $this->type, $this->data);

		$arResult = array(
			"password"	=> $password,
			"code"		=> $code,
			"name"		=> $data->name,
			"email"		=> $data->email
		);
	}
?>
