<?php
	if ($this->CheckConfig()) {
		$this->data = current($this->get($this->path, "system.get.data.phtml"));

		srand((double)microtime()*1000000);
		$code		= md5(uniqid(rand(), true));

		$passlen	= 6;
		$password	= "";
		$valid_chars	= Array();
		for ($c = ord('2'); $c <= ord('9'); $c++) {
			$valid_chars[] = chr($c);
		}
		for ($c = ord('a'); $c <= ord('z'); $c++) {
			if (!in_array(chr($c), Array('o', 'i', 'l'))) {
				$valid_chars[] = chr($c);
				$valid_chars[] = strtoupper(chr($c));
			}
		}

		while ($passlen--) $password .= $valid_chars[rand(0, count($valid_chars)-1)];

		if (is_array($this->data->config->password_array)) {
			if (count($this->data->config->password_array) >= 10) {
					array_shift($this->data->config->password_array);
			}
		} else {
			$this->data->config->password_array = Array();
		}
		$this->data->config->password_array[$code] = Array("password" => md5($password), "ctime" => time());

		$this->save();

		$arResult = Array(
			"password"	=> $password,
			"code"		=> $code,
			"name"		=> $data->name
		);
	}
?>