<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
		display("importing grants for user ".$this->data->login."\n");
		$paths=$ARCurrent->grants_list["puser"][$this->data->login];
		while (list($path, $grants)=each($paths)) {
			$newpath=$importDestPath.substr($path, strlen($importRootPath));
			display("	$newpath\n");

			$result=current($this->get($newpath, "system.import.grants.phtml", 
													Array(
														"importDestPath" => $importDestPath,
														"importRootPath" => $importRootPath,
														"grants" => &$grants,
														"type" 	=> "puser" ,
														"id"	=> $this->data->login
													)));
			if ($result) {
				@reset($grants);
				while (list($grant, $value)=each($grants)) {
					$this->data->usergrants[$newpath][$grant]=$value;
				}
			}
		}
		$this->save();
	}
?>