<?php
	if ($AR->user && ($AR->user->data->login=="admin" || $AR->user->grants["config"])) { // can not be called directly from loader
		switch($action) {
			case "delete" :
				if (!($grant??null)) {
					unset($data->config->usergrants[$path]);
				} else {
					unset($data->config->usergrants[$path][$grant]);
					if (!@count($data->config->usergrants[$path])) {
						unset($data->config->usergrants[$path]);
					}
				}
			break;
			case "add" :
				$data->config->usergrants[$path][$grant]=1;
			break;
		}
		$this->save();
	}
?>
