<?php
	/******************************************************************
	 system.save.grants.user.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $action, $path, $grant
	 Grant needed: none
	 Global variables: none 

	 This template adds a grant to the user grants table of this user.
	 First it checks whether the user who is applying the grant has 
	 sufficient grants in the given path (path) to add/delete the
	 grant.

	 The template checks whether a user is logged on, it can only be 
	 called from another template which calls CheckLogin() first.

	 $action: "add" or "delete"
	 $path: path to the object on which the grant is added.
	 $grant: name of the grant to apply.

	 result: "ok" or an error message.

	******************************************************************/

	// first check whether the user has the config grant on the given path
	debug("puser/system.save.grants.user.phtml: $this->path","class");
	if ($AR->user && current($this->get($path, "system.check.grant.phtml", array( "grant" => "config" )))) { // can not be called directly from loader
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=current($this->get(".","system.get.data.phtml"));

		$action=$this->getdata("action","none");
		$path=$this->getdata("path","none");
		$grant=$this->getdata("grant","none");
		$granttype=$this->getdata("granttype","none");
		$modifier=$this->getdata("modifier", "none");
		if (!$granttype) {
			$granttype=ARGRANTGLOBAL;
		}
		switch($action) {
			case "delete" :
				if ($grant===false) {
					unset($this->data->config->usergrants[$path]);
				} else {
					if (!$modifier) {
						unset($this->data->config->usergrants[$path][$grant]);
					} else {
						unset($this->data->config->usergrants[$path][$grant][$modifier]);
						if (!@count($this->data->config->usergrants[$path][$grant])) {
							unset($this->data->config->usergrants[$path][$grant]);
						}
					}
					if (!@count($this->data->config->usergrants[$path])) {
						unset($this->data->config->usergrants[$path]);
					}
				}
				break;
			case "add" :
				if ($modifier) {
					if (!is_array($this->data->config->usergrants[$path][$grant])) {
						unset($this->data->config->usergrants[$path][$grant]);
					}
					$this->data->config->usergrants[$path][$grant][$modifier]=$granttype;
				} else {
					$this->data->config->usergrants[$path][$grant]=$granttype;
				}
				break;
			case "set" :
				$this->data->config->usergrants[$path] = $grants;
				break;
		}
		if ($this->save()) {
			$arResult=$ARnls["ok"];
		} else {
			$arResult=$this->error;
		}
	} else {
		$arResult=$ARnls["accessdenied"];
	}
	debug("res:".$arResult);
?>
