<?php
  if ($AR->user && ($AR->user->data->login=="admin" || $AR->user->grants["config"])) { // can not be called directly from loader
    switch($action) {
      case "delete" :
          include_once($this->store->code."includes/DelGrant.phtml");
          $data->usergrants=DelGrant($data->usergrants, $path, $grant);
  	break;
      case "add" :
          $data->usergrants[$path][$grant]=1;
  	break;
    }
    $this->save($this->path, $this->type, $data, "");
  }
?>