<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
		$target=$this->getdata("target");
		$target=$this->store->make_path($this->parent, $this->getdata("target","none"));
		if (substr($this->path, 0, strlen('/system/users/'))=='/system/users/') {
			// this is a live user object, not a link in a group
			if (substr($target, 0, strlen('/system/users/'))!='/system/users/') {
				$this->error=$ARnls["err:invaliduserlocation"];
			} else if ($this->data->login=="public" || $this->data->login=="admin") {
				$this->error=$ARnls["err:cannotdelsystemusers"];
			} else {
				$this->call("pobject::system.rename.phtml", $arCallArgs);
				$this->data->login=substr($this->path, strlen($this->parent), -1);
				$this->save();
			}
		} else {
			// this is probably a link in a group
			$parentobject=@current($this->get($this->parent, "system.get.phtml"));
			if ($parentobject && $parentobject->implements("pgroup")) {
				// so it is, so remove the user from the group
				// which will by the way also delete the current object
				// first get the original users path
				$crit["login"]["value"]["="]="'".AddSlashes($this->data->login)."'";
				$realuser=@current($this->find("/system/users/",$crit,"system.get.phtml"));
				if ($realuser && $realuser->path) {
					$realpath=$realuser->path;
					$parentobject->call("system.set.user.phtml", Array("path" => $realpath, "action" => "delete"));
				}
			}
		}			
	}
	$arResult=$target;
?>