<html>
<head>
<style>
TD {
	FONT: 13px sans-serif;
}
BODY 	{
	FONT: 13px sans-serif;
	BORDER: 0;
    CURSOR: wait;
  <?php
    global $HTTP_USER_AGENT;
    if (eregi(".*msie ([0-9]+).*",$HTTP_USER_AGENT, $regs) &&
       $regs[1] && (intval($regs[1])>=4)) { //ie4+
  ?>
	BACKGROUND-COLOR: buttonface;
  <?php
    } else {
  ?>
	BACKGROUND-COLOR: #BBBBBB;
  <?php
    }
  ?>
}
</style>
</head>
<body onLoad="load()">
<fieldset>
<?php
  $this->store->accessdenied='<table width="100%"><tr><td valign="middle">Access Denied</td><td align="right"><img align="right" src="'.$AR->dir->images.'tree/x.png" vspace="1"></td></tr></table>';
  if ($this->CheckLogin("read")) {
?>
<table width="100%">
<tr>
  <td valign="middle"><img src="<?php echo $AR->dir->images; ?>tree/wait.gif" align="left" hspace="2">Loading...</td>
  <td align="right"><img align="right" src="<?php echo $AR->dir->images; ?>tree/x.png" vspace="1"></td>
</tr>
</table>
<script>
  function load() {
    node=parent.Nodes[<?php echo $node; ?>];
    <?php
      flush();
      $criteria["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
      $criteria["object"]["implements"]["="]="'pdir'";
      $folders=$this->find("",$criteria,"GetFolder.phtml",$args);
      // en nu node.add doen voor elke folder.
      if ($folders) {
        while (list($key, $folder)=each($folders)) {
          ?>
            node.add("<?php echo AddSlashes($folder["icon"]); ?>",
                     "<?php echo AddSlashes($folder["name"]); ?>",
                     "<?php echo AddSlashes($folder["path"]); ?>",
                     "<?php echo AddSlashes($folder["pre"]); ?>");
          <?php
        }
      }
    ?>
    parent.Draw();
  } 
</script>
<?php } ?>
</fieldset>
</body>
</html>
