<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.

  ******************************************************************/
  if ($this->CheckConfig($arCallFunction, $arCallArgs) && $this->CheckLogin("read")) {
    if ($this->exists("index.html/")) {
      $this->get("index.html/","view.html");
    } else {
?>
<html>
<body scroll="no" bgcolor="white" onLoad="top.LoadingDone();">
<?php
  include($this->store->code."widgets/menu/menu.phtml");
?>
<font face="helvetica, sans-serif" size="2">
<h3><?php echo $data->name; ?>.</h3>
<?php
  $this->ls("","Show.phtml");
?>
</font>
</body>
</html>
<?php
    }
  }
?>