<?php
/**************************************************************************
	mod_lock v1.0b						MySQL

	table layout:

	Table locks
	+----------+---------------+------+-----+---------+-------+
	| Field    | Type          | Null | Key | Default | Extra |
	+----------+---------------+------+-----+---------+-------+
	| release  | int(11)       |      | MUL | 0       |       |
	| type     | enum('O','T') |      | MUL | O       |       |
	| identity | varchar(23)   |      | MUL |         |       |
	| path     | varchar(127)  |      | MUL |         |       |
	+----------+---------------+------+-----+---------+-------+

	error numbers:

	1	lock()	mysql error when running lock query
	2	lock()	path already locked by someone else

**************************************************************************/


class mysqllock {

	function mysqllock($tbl_prefix="") {
		debug("mysqllock::mysqllock($tbl_prefix)");
		  $this->tbl_prefix=$tbl_prefix;
		  debug("mysqllock::mysqllock end","all");
	}

	function connect($host="localhost",$user="root",$password="") {
		debug("mysqllock::connect($host, $user, [password])","store");
		$this->mayClose=true;
//		$this->host=$host;
//		$this->user=$user;
//		$this->password=$password;
		$this->connectid=mysql_pconnect($host,$user,$password);
		debug("mysqllock::connect end","all");
	}

	function select_db($database="modules", $connectid=false) {
		debug("mysqllock::select_db($database, $connectid)");
		$this->database=$database;
		if ($connectid!==false) {
			$this->connectid=$connectid;
		}
		debug("mysqllock::select_db end");
	}

	function get_locks($identity) {
		debug("mysqllock:get_locks($identity)","store");
		$query_string="select `path`,`release`, `type`, `identity` from ".$this->tbl_prefix."locks where 
		`release` >=".time()." and `identity`='".AddSlashes($identity)."'";
		mysql_select_db($this->database,$this->connectid);
		$query=@mysql_query($query_string,$this->connectid);
		while ($temp=@mysql_fetch_array($query)) {
			$result[$temp["path"]]=$temp;
		}
		debug("mysqllock:get_locks end","all");
		return $result;
	}

	function lock($identity, $path, $type="O", $time=0) {
	/**********************************************************************
		This function locks an object/path
	 **********************************************************************/
		debug("mysqllock:lock($identity,$path,$time,$type)","store");
		$tablelock = "write";
		$checkonly = false;

		if (!$time) {
			$time=time()+$this->lock_duration;
 		}

		if($time < time()) {
			$checkonly = true;
			$tablelock = "read";
		}

		// lock table first
		$query_string="lock tables ".$this->tbl_prefix."locks ".$tablelock;
		mysql_select_db($this->database,$this->connectid);
		@mysql_query($query_string,$this->connectid);

		// check if the path is not already locked by a parent
		$query_string="
			select `path`, `release`, `type`, `identity` 
			  from ".$this->tbl_prefix."locks 
			 where ( ( path=substring('".AddSlashes($path)."',1,length(path)) 
				       AND `type`='T' ) 
				     OR ( `path`='".AddSlashes($path)."' )";

		// if we are locking a whole tree we must also check if no
		// child has been locked already
		if ($type=="T") {
			$query_string.=" OR ( `path` like '".AddSlashes($path)."%' ) ";
		}

		$alreadylocked=false;
		// see if this lock is still alive
		$query_string.=") AND `release`>=".time();
		mysql_select_db($this->database,$this->connectid);
		$query=@mysql_query($query_string, $this->connectid);
		while ($lock=@mysql_fetch_array($query)) {
			if ($lock["identity"]!=$identity) {
				// this is a lock with another identity, so fail the current lock attempt
				$alreadylocked=true;
				$this->locklist[]=$lock;
			}
		}

		$result=false;
		if (!$alreadylocked) {
			if(!$checkonly) {
				// clear old lock entries
				$query_string="
					delete from ".$this->tbl_prefix."locks where `path`='".AddSlashes($path)."'";

				mysql_select_db($this->database,$this->connectid);
				mysql_query($query_string, $this->connectid);

				$query_string="
					insert into ".$this->tbl_prefix."locks (`path`, `release`, `type`, `identity`) values (
					'".AddSlashes($path)."', $time, '".AddSlashes($type)."',
					'".AddSlashes($identity)."')";

				mysql_select_db($this->database,$this->connectid);
				mysql_query($query_string, $this->connectid);
				if (!mysql_errno()) {
					$result=true;
				} else {
					$this->error=2;
					$this->error_message="MOD_LOCK: ERROR 2: ".mysql_error();
				}
			} else {
				$result = true;
			}
		} else {
			$this->error=1;
			$this->error_message="MOD_LOCK: ERROR 1: $path already locked.";
		}
		$query_string="unlock tables";
		mysql_select_db($this->database,$this->connectid);
		mysql_query($query_string,$this->connectid);

		return ($result);
	}

	function unlock($identity,$path="") {

		$query_string="delete from ".$this->tbl_prefix."locks where `identity`='".AddSlashes($identity)."'";
		if ($path) {
			$query_string.=" and `path`='".AddSlashes($path)."'";
		}
		mysql_select_db($this->database,$this->connectid);
		mysql_query($query_string, $this->connectid);

	}

	function close() {
		if ($this->mayClose) {
			mysql_close($this->connectid);
		}
	}

	function init() {
		$query_string="
CREATE TABLE ".$this->tbl_prefix."locks (
        `release` int NOT NULL,
        `type` enum('O','T') NOT NULL,
        `identity` varchar(32) NOT NULL,
        `path` varchar(127) NOT NULL,
  key (`release`),
  key (`type`),
  key (`identity`),
  key (`path`)
)";
		mysql_select_db($this->database,$this->connectid);
		mysql_query($query_string, $this->connectid);
	}
}
?>