# .travis.yml
env:
    - DB=mysql WORKSPACE=yes
    - DB=mysql WORKSPACE=no
    - DB=postgresql

language: php
cache: apt

php:
    - 5.4
    - 5.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apache2 libapache2-mod-fastcgi imagemagick wget lynx subversion tidy poppler-utils
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo ln -s ${TRAVIS_BUILD_DIR}/www /var/www/ariadne
    - sudo cp -f tests/travis-ci-apache /etc/apache2/sites-available/default
    - phpenv rehash
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sudo service apache2 restart
    - ls -lad ${TRAVIS_BUILD_DIR}/files ${TRAVIS_BUILD_DIR}/lib/configs/ariadne.phtml
    - svnadmin create ${TRAVIS_BUILD_DIR}/files/temp/testsvn
    - svnadmin load ${TRAVIS_BUILD_DIR}/files/temp/testsvn < ${TRAVIS_BUILD_DIR}/tests/svnrepo.log

before_script:
    - sh -c "echo \"<?php \\\$ariadne='${TRAVIS_BUILD_DIR}/lib'; ?>\" | tee ${TRAVIS_BUILD_DIR}/www/ariadne.inc"
    - sh -c "if [ ${DB} = 'mysql' ]; then mysqladmin -u root create ariadne; fi"
    - sh -c "if [ ${DB} = 'postgresql' ]; then psql -c 'create database ariadne;' -U postgres; fi"

script:
    - bash ./tests/run.sh
    - svnrepo="file://${TRAVIS_BUILD_DIR}/files/temp/testsvn/" phpunit --coverage-clover=coverage.clover

notifications:
    email: false
    irc:
      secure: "mOc/UjQgoRI1+Ez12A/DWXShtfKjKwDTSuMn8PoSyul8WelNYl6z6zKBflePB8BcYN2TNIaGQQGAXqAJKB1njYG5/RCmF8HVvBUOLWBdcJ7AW2h7bOb30YxYZr+vTXebKhz9TDZHD0lTVI5F6d7JYv0jjfPr4nj6rVhSvkbZUrw="
      on_success: change
      on_failure: always
      use_notice: true
      skip_join: true

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

