<?php
	/******************************************************************
	 classic.save.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $newtype, $newfilename
	 Grant needed: add or edit
	 Global variables: none

	 This template is a wrapper around system.save.data.phtml for the
	 classic interface.

	 no result.
 
	******************************************************************/
	// first make sure the uploaded file is in the place where 
	// system.save.data.phtml expects it.
	$this->call("system.save.tempfile.phtml");
	// only then call system.save.data.phtml
	$this->call("system.save.data.phtml",$arCallArgs);
	if (!$this->error) {
		if (!$arReturnPage=$this->getdata("arReturnPage","none")) {
			$arReturnPage=$this->store->root.$parent; 
		}
		ldRedirect($arReturnPage);
	} else {
		$this->call("show.error.phtml");
	}
?>