<?php
  /******************************************************************
   delete.phtml					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by: edit.phtml
   Arguments: none
   Grant needed: delete
   Interface/Widget: all
   Global variables: none

   This template deletes the current object.

  ******************************************************************/

  include($this->store->code."includes/delete.object.phtml");
  if (!$error && $this->CheckLogin("delete")) {
    $root=$this->store->files."/files".$this->path;
    if (file_exists($root)) {
      $dir=opendir($root);
      while ($file=readdir($dir)) {
        if (!is_dir($root."/".$file)) {
          unlink($root."/".$file);
        }
      }
      closedir($dir);
    }
  }
?>