<?php
	/******************************************************************
	 edit.page.save.phtml                                  Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $nls[page]
	 Grant needed: edit
	 Global variables: none

	 No result.

	******************************************************************/
	// FIXME: use nls text
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
	if ($data->mimetype=="text/html") {
		$this->call("system.save.html.phtml", $arCallArgs);
	} else {
		$this->error=$ARnls["err:nothtmlfile"];
	}
?>
<hmtl>
<head><title>Saving HTML File</title></head>
<body bgcolor="#CCCCCC"><font face="arial,helvetica,sasn-serif">
<?php
		if (!$this->error) {
			echo $ARnls["filesaved"];
			?>
<script>
  window.setTimeout('window.close()',500);
</script>
			<?php
		} else {
			echo "Error: $this->error";
		}
?>		
</font>
<form>
<input type="button" name="ok" value=" OK " onClick="window.close();">
</form>
</body>
<?php
	}
?>
