<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="data">
		<legend><?php echo $ARnls["data"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<span class="required"><?php echo $ARnls["name"]; ?></span>
				</td><td>
					<span class="required"><?php echo $ARnls["mimetype"]; ?></span>
				</td>
			</tr><tr>
				<td>
					<input type="text" size="16" name="<?php echo $selectednls."[name]"; ?>" maxlength="50" 
						value="<?php $this->showdata("name", $selectednls); ?>">
				</td><td>
					<input type="text" size="16" name="mimetype" maxlength="50" 
						value="<?php $this->showdata("mimetype", "none"); ?>">
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["summary"]; ?>
				</td><td align="right">
					<?php echo $flag; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<?php
						if ($data->mimetype=="text/html") {
							$rows=2;
						} else {
							$rows=4;
						}
					?>
					<textarea name="<?php echo $selectednls."[summary]"; ?>" cols="30" rows="<?php echo $rows; ?>" wrap="soft"><?php 
							echo ereg_replace("&","&amp;",$this->getdata("summary", $selectednls)); 
					?></textarea>
				</td>
			</tr><tr>
				<td colspan="2">
					<?php echo $ARnls["file"]; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<input type="file" name="file">
					<?php
						if ($data->mimetype=="text/html") {
							$wgHTMLEditName="html";
							$wgHTMLEditPath=$this->parent;
							$wgHTMLEditFile=substr($this->path, strlen($this->parent), -1);
							$wgHTMLEditLanguage="none";
							$wgHTMLEditType="full";
							$wgHTMLEditContent=$this->ParseFile($this->GetFile());
							include($this->store->code."widgets/htmledit/js.html");
							include($this->store->code."widgets/htmledit/form.html"); 
						}
					?>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["<?php echo $selectednls; ?>[name]"].focus();
	}
</script>
<?php
		$arResult["save"]["mimetype"]["ereg"]=".+";
		$arResult["save"]["mimetype"]["error"]=$ARnls["err:nomimetypeentered"];
		$arResult["next"]["mimetype"]=$arResult["save"]["mimetype"];
		if ($selectednls==$ARConfig->nls->default) {
			$arResult["save"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["save"][$selectednls."[name]"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
			$arResult["next"][$selectednls."[name]"]=$arResult["save"][$selectednls."[name]"];
		} else {
			$arResult["next"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["next"][$selectednls."[name]"]["confirm"]=sprintf($ARnls["confirm:nonameentered"],$selectedlanguage);
			if ($this->getdata("name",$ARConfig->nls->default)) {
				$arResult["save"][$selectednls."[name]"]=$arResult["next"][$selectednls."[name]"];
			} else {
				$arResult["save"]=false;
			}
		}
	}
?>