<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
//		if (count($ARConfig->nls->list)>1) { // more than one language available
//			$languages=true;
//		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$summary="edit.object.data.form.phtml";
		$language="edit.object.language.phtml";
		$save="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $save;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$summary;

		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}
		if ($languages) { // more than one language available
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/languages.png";
			$wgWizFlow[$i]["template"]=$language;
		}

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$save;

		global $HTTP_POST_VARS;		
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($wgWizFlow[0]["current"]==1) {
			$this->call("system.save.tempfile.phtml");
			if ($this->error) {
				$this->call("show.error.phtml");
				exit;
			}
		}
		$arLanguage=$this->getdata("arLanguage","none");
		if ($languages && $wgWizFlow[0]["current"]==2) { // =edit.object.language.phtml
			$arLanguage=$this->getdata("arPrevLanguage","none");
			$ARCurrent->arLanguage=$arLanguage;
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		$name=current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml"));
		$wgWizTitle=$ARnls["edit"]." ".$name;		
		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$this->type.'_open.gif" alt="" hspace="4" align="absmiddle">';
		include($this->store->code."widgets/wizard/new.html");
	}
?>