<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$summary="edit.object.data.form.phtml";
		$language="edit.object.language.phtml";
		$save="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["template"] = $cancel;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["template"]=$summary;
		$wgWizFlow[$i]["cancel"]=0;
		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["cancel"]=0;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			if ($hascustomdata) {
				$wgWizFlow[$i]["next"]=$i-2;
			} else {
				$wgWizFlow[$i]["next"]=$i-1;
			}
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
			$wgWizFlow[$i]["cancel"]=0;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$save;
		$wgWizFlow[$i]["back"]=$i-1;
		$wgWizFlow[$i]["cancel"]=0;

		global $HTTP_POST_VARS;		
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($wgWizFlow[0]["current"]==1) {
			if ($arControl=="next" || $arControl=="save") {
				$this->call("system.save.tempfile.phtml");
				if ($this->error) {
					$this->call("show.error.phtml");
					exit;
				}
			}
		}
		$arLanguage=$this->getdata("arLanguage","none");
		if ($languages && $wgWizFlow[0]["current"]==2) { // =edit.object.language.phtml
			if ($arControl=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		$name=current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml"));
		$wgWizTitle=$ARnls["edit"]." ".$name;		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>