<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->AR_implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->get_config("code")."widgets/wizard/code.php");

		$summary="edit.object.data.form.phtml";
		$language="edit.object.language.phtml";
		$save="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $save;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$summary;

		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$save;

		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		$this->call("system.save.tempfile.phtml");
		if ($this->error) {
			$this->call("show.error.phtml");
			exit;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if ($languages && $wgWizFlow[0]["current"]==2) { // =edit.object.language.phtml
			$arLanguage=$this->getdata("arPrevLanguage","none");
			$ARCurrent->arLanguage=$arLanguage;
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$_POST["arLanguage"]=$arLanguage;

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		foreach ($AR->nls->list as $language => $language_name) {
			if (!$this->getdata("name", $language)) {
				if (($file=$this->getdata("file", $language)) && ereg("[^\/\\]*\$", $file, $matches)) {
					$arFilename = eregi_replace("[^a-z0-9\./_-]", "_", $matches[0]);
					$_POST[$language]["name"] = $arFilename;
				}
			}
		}


		$wgWizFlow = $this->call("user.wizard.edit.html", Array("wgWizFlow" => $wgWizFlow));

		if (!$ARCurrent->arTypeIconsSmall[$this->type]) {
			// FIXME: for performance the check above is necessary, but
			// it does make it possible to get the wrong icon...
			// get typetree to get the correct icon
			$this->call('typetree.ini');
		}
		$icon=$ARCurrent->arTypeIcons[$this->type]['default'];
		if (!$icon) {
			$dotPos=strpos($this->type, '.');
			if (false!==$dotPos) {
				$realtype=substr($this->type, 0, $dotPos);
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
			} else { 
				$realtype=$this->type;
			}
			if (!$icon) {
				$icon=$AR->dir->images."icons/".$realtype.".gif";
			}
			$name=$ARCurrent->arTypeNames[$this->type];
		} else {
			$name=$ARCurrent->arTypeNames[$this->type];
		}
		$arResult=$icon;

		$wgWizTitle=$ARnls["edit"]." ".$name;
		$wgWizHeader=$wgWizTitle.'<img src="'.$icon.'" alt="" hspace="4" align="absmiddle">';
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>