<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")))
      && $this->CheckConfig()) {

		$tmpname=$this->getdata("file");
		$dotPos=strrpos($tmpname, '.');
		if (false!==$dotPos) {
			$tmpname=substr($tmpname,0,$dotPos);
		}
		$tmpname=str_replace('_',' ',$tmpname);
		$arCallArgs[$ARConfig->nls->default]["name"]=$tmpname;

		$this->call("system.save.data.phtml", $arCallArgs);
	}
?>