<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")))
      && $this->CheckConfig()) {

		$defaultNLS = $ARConfig->nls->default;
		$tmpname=${$defaultNLS}['file'];
		$tmpname=str_replace('_',' ',$tmpname);
		$arCallArgs[$defaultNLS]["name"]=$tmpname;

		$this->call("system.save.data.phtml", $arCallArgs);
	}
?>
