<?php
	$nls = $this->data->nls->default;
	$result["date"]=$this->lastchanged;
	$result["size"]=$this->data->$nls->filesize;
	$result["path"]=$this->path;
	$result["type"]="dir";

	if ($this->CheckLogin("read")) {
		$grants["read"]=true;
	} else {
		$grants["read"]=false;
	}

	if ($this->CheckLogin("add")) {
		$grants["write"]=true;
	} else {
		$grants["write"]=false;
	}

	$result["grants"]=$grants;

	$arResult=$result;
?>
