<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	global $HTTP_POST_VARS;

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=1;
				break;
			}
		}
	}

	$custom="edit.object.data.custom.phtml";
	$start="object.new.uploadfile.phtml";
	$filename="object.new.filename.phtml";
	$summary="edit.object.data.form.phtml";
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$finish;

	$i++;
	$arFlow[$i]["title"]=$ARnls["uploadfile"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/upload.png";
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$filename;
	$arFlow[$i]["nolang"]=true;

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$summary;

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}

	$arControl=$this->getdata("wgWizControl","none");

	/* save uploaded file if available */
	$this->call("system.save.tempfile.phtml");
	if ($this->error) {
		$this->call("show.error.phtml");
		exit;
	}

	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		if (($file=$this->getdata("file","none")) && ereg("[^\/\\]*\$",$file, $matches)) {
			$arNewFilename=eregi_replace("[^a-z0-9\./_-]","_",$matches[0]);
			$HTTP_POST_VARS['arNewFilename'] = $arNewFilename;
			$this->path = $this->store->make_path($this->parent, $arNewFilename);
		}
		while (list($key, $value)=each($configcache->nls->list)) {
			$HTTP_POST_VARS[$key]["name"]=$arNewFilename;
		}
	}
	$arResult = $this->call("user.wizard.new.html", Array("wgWizFlow" => $arFlow));
?>