<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	global $HTTP_POST_VARS, $HTTP_POST_FILES;

	$start="object.new.uploadfile.phtml";
	$filename="object.new.filename.phtml";
	$finish="edit.object.data.save.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$i++;
	$arFlow[$i]["title"]=$ARnls["uploadfile"];
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["next"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["template"]=$filename;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["save"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["save"];
	$arFlow[$i]["template"]=$finish;
	$arFlow[$i]["back"]=$i-1;
	$arFlow[$i]["save"]=$i;

	$arControl=$this->getdata("wgWizControl","none");
	if ($arFlow[0]["current"]==1) {
		if ($arControl==$ARnls["next"]) {
			$this->call("system.save.tempfile.phtml");
		}
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$file=$this->getdata("file","none");
		if (($file=$this->getdata("file","none")) && ereg("[^\/\\]*\$",$file, $matches)) {
			$arNewFilename=$matches[0];
		} else {
			$arNewFilename="{5:id}";
		}
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	if ($arFlow[0]["current"]==3) {
		$wgOverwrite=$this->getdata("wgOverwrite","none");
		if (!$wgOverwrite || $wgOverwrite=="no") {
			$arFlow[0]["current"]=2;
			$HTTP_POST_VARS["wgWizControl"]="";
			$HTTP_POST_VARS["wgOverwrite"]="";
		}
	}
	$arResult=$arFlow;
?>