<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	global $HTTP_POST_VARS, $HTTP_POST_FILES;

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}
	if (count($configcache->nls->list)>1) { // more than one language available
		$languages=true;
		$saveoffset=1;
	} else {
		$saveoffset=0;
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.uploadfile.phtml";
	$filename="object.new.filename.phtml";
	$summary="edit.object.data.form.phtml";
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$i++;
	$arFlow[$i]["title"]=$ARnls["uploadfile"];
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["next"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["template"]=$filename;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 
	$arFlow[$i]["save"]=$i+2+$saveoffset;

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["template"]=$summary;
	$arFlow[$i]["prev"]=$i-1;

	if ($hascustomdata) {
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2+$saveoffset;
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["template"]=$custom;
		$arFlow[$i]["prev"]=$i-1;
	}
	if ($languages) { // more than one language available
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2;
		$i++;
		$arFlow[$i]["title"]=$ARnls["language"];
		$arFlow[$i]["template"]=$language;
		if ($hascustomdata) {
			$arFlow[$i]["next"]=$i-2;
		} else {
			$arFlow[$i]["next"]=$i-1;
		}
		$arFlow[$i]["prev"]=$i-1;
		$arFlow[$i]["save"]=$i+1;
	} else {
		$arFlow[$i]["save"]=$i+1;
	}

	$i++;
	$savestep=$i;
	$arFlow[$i]["title"]=$ARnls["save"];
	$arFlow[$i]["template"]=$finish;
	$arFlow[$i]["back"]=$i-1;
	$arFlow[$i]["save"]=$i;

	$arControl=$this->getdata("wgWizControl","none");
	if ($arFlow[0]["current"]==1) {
		if (wgWizGetAction($arControl)=="next") {
			$this->call("system.save.tempfile.phtml");
			$HTTP_POST_VARS["mimetype"]=$HTTP_POST_VARS["file_type"];
			while (list($key, $value)=each($configcache->nls->list)) {
				$HTTP_POST_VARS[$key]["name"]=$HTTP_POST_VARS["file"];
			}
		}
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$file=$this->getdata("file","none");
		if (($file=$this->getdata("file","none")) && ereg("[^\/\\]*\$",$file, $matches)) {
			$arNewFilename==eregi_replace("[^a-z0-9\./_-]","_",$matches[0]);
		} else {
			$arNewFilename="{5:id}";
		}
		$ARCurrent->arNewFilename=$arNewFilename;
	}
	if ($arFlow[0]["current"]==2) { // filename entered
		while (list($key, $value)=each($configcache->nls->list)) {
			$HTTP_POST_VARS[$key]["name"]=$arNewFilename;
		}
	}		
	$arResult=$arFlow;
?>