	<?php
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;

	?>
	<table border="0">
	<tr>
		<td>
			<span class="required"><?php echo $ARnls["file"]; ?></span>
		</td>
	</tr><tr>
		<td valign="top">
			<input type="file" id="file" name="<?php echo $selectednls; ?>[file]" <?php
				if ($this->AR_implements("pphoto")) {
					echo "onMouseDown=\"preview(true);\"";
				}
			?>>
		</td>
	</tr><tr>
		<td align="center">
			<div ID="busy"  STYLE="position: absolute; top: 100px; left: 100px; width: 200px; height: 50px; background: buttonface; border:2px outset; padding: 10px; margin-top: 20px; text-align: left; visibility:hidden;">
				<img src="<?PHP echo $AR->dir->images; ?>tree/wait.gif" align="left">Uploading...
			</div>
		</td>
	</tr>
	</table>
	<script>
		var oldValue=document.getElementById("file").value;
		function preview(first) {
			return false;
			if (first) {
				oldValue=document.getElementById("file").value;
			}
			var newValue=document.getElementById("file").value;
			if (newValue==oldValue) {
				setTimeout(preview, 500, false);
			} else {
				document.images["thumb"].src = 'file://'+newValue;
				oldValue=newValue;
			}
		}

		function forminit() { 
			document.wgWizForm.file.focus();
		}
		function busy() {
			if (document.all) {
				var busy=document.all['busy'];
			} else if (document.getElementById) {
				var busy=document.getElementById('busy');
			}
			if (busy) {
				busy.style.visibility='visible';
			}
		}
		window.onload=forminit;
		document.wgWizForm.onsubmit=busy;
	</script>
