<?php
  global $HTTP_POST_FILES;
  if ($newtype) {
    $newdata=new object;
    $newdata->author=$AR->user->name;
    $newdata->authorpath=$AR->user->path;
    $newdata->created=time();
  } else { 
    $newdata=$data;
  }
  $newdata->mimetype=$mimetype;
  if (!isset(${$ARConfig->nls->default}) && !isset($newdata->{$ARConfig->nls->default})) { // default language for this path
    $error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
  } else {
    if (!$newdata->nls) {
      $newdata->nls=new object;
    }
    $newdata->nls->default=$ARConfig->nls->default;
    reset($AR->nls->list);
    while (list($key, $value)=each($AR->nls->list)) {
      if (isset(${$key})) {
        $nlsformdata=$$key;
        if (!isset($newdata->$key)) {
          $newnlsdata=new object;
        } else {
          $newnlsdata=$newdata->$key;
        }
        if (!$nlsformdata["name"]) {
          $error=sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]);
        }
        $newnlsdata->name=$nlsformdata["name"];
        $newnlsdata->summary=$nlsformdata["summary"];
        $properties["name"][]["value"]="'".AddSlashes($nlsformdata["name"])."'";
        $properties["text"][]["value"]="'".AddSlashes($nlsformdata["summary"])."'";
        $newdata->$key=$newnlsdata;
        $newdata->nls->list[$key]=$value;
      }
    }
    if (!$error) {
      if ($HTTP_POST_FILES['file'] && is_uploaded_file($HTTP_POST_FILES['file']['tmp_name'])) {
        // a new file is uploaded via pfile/form.phtml 
        $path=$this->store->files."files".$this->path."/view=";
        if ($newtype) {
          $this->MkDir("files".$this->path);
        }
        $newdata->size=$HTTP_POST_FILES['file']['size'];
        if (!$newdata->mimetype) {
          $newdata->mimetype=$HTTP_POST_FILES['file']['type'];
        }
        if (!$error) {
          if (!move_uploaded_file($HTTP_POST_FILES['file']['tmp_name'],$path)) {
            $error="Couldn't move file to $path";
          }
        }
      }
    }
  }
  include($this->store->code."includes/save.object.phtml");
?>