<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $arNewType)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) &&
			$this->CheckConfig()) {

	$arCallArgs = array_merge($arCallArgs, ldRegisterFile("file", $this->error));
	if (!$this->error) {
		$this->call("system.save.data.phtml", $arCallArgs);
	}

  }
?>
