<?php
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
    // first do normal delete
    $this->call(get_parent_class($this)."::system.delete.phtml");
    if (!$arResult) {
      // no errors: delete files
      if ($d=@dir($this->store->files."files".$this->path)) {
        while ($entry=$d->read()) {
          if (!is_dir($this->store->files."files".$this->path.$entry)) {
            unlink($this->store->files."files".$this->path.$entry);
          }
        }
      }
    }
  }
?>