<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
 
	******************************************************************/

	require_once($this->store->get_config('code')."modules/mod_page.php");

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) &&
			$this->CheckConfig()) {
		if ($this->arIsNewObject) {
			$this->data=new object;
		} else {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));
		}

		// unset the properties array, so no properties can be passed to this template.
		$properties = Array();

		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			$count=0;
			$nlslist = Array("none");
			while (list($key, $value)=each($AR->nls->list)) {
				if ($this->getdata("name",$key)) {
					array_push($nlslist, $key);
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					$newnlsdata->name=$this->getdata("name",$key);
					$properties["name"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["name"][$count]["nls"]="'$key'";
					$properties["text"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["text"][$count]["nls"]="'$key'";
 					$count++;
					$newnlsdata->summary=page::compile($this->getdata("summary",$key), $key);
					$properties["text"][$count]["value"]="'".AddSlashes(substr($newnlsdata->summary,0,255))."'";
					$properties["text"][$count]["nls"]="'$key'";
					$count++;
					if ($this->store->is_supported("fulltext")) {
						$properties["fulltext"][$count]["value"]="'".AddSlashes($this->store->format_for_fti(
								$newnlsdata->name." ".
								$this->html_to_text($newnlsdata->summary)." "
								))."'";
						$properties["fulltext"][$count]["nls"]="'$key'";
					}
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else { // clear language values for $key->name if set, keep the rest, just in case.
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->nls->list[$key]);
					}
				}
			}
		}
		if (!$this->error) {
			$file_type = $this->getdata("file_type", "none");
			if (!$file_type) {
				$file_type = $this->getdata("mimetype","none");
			}
			$this->data->mimetype = $file_type;

			$this->save($properties);

			if (!$this->error) {
				$this->ClearCache();
				// keep only the fulltext properties.
				$properties = Array('fulltext' => $properties['fulltext']);

				$this->arIsNewObject = false;
				$isDefaultSet = false;
				foreach ($nlslist as $nlskey) {
					$fulltext = $properties['fulltext'];
					$tempfile = $this->getdata("file_temp", $nlskey);
					$mimetype = $this->getdata("mimetype", $nlskey);
					$file_type = $this->getdata("file_type", $nlskey);
					if (!$file_type) {
						$file_type = $mimetype;
					}
					$mimetype = $file_type;
					
					$this->data->$nlskey->mimetype = $mimetype;
					
					$deletefile = $this->getdata("delete", $nlskey);

					// now check whether $file_temp is defined, if so, move it
					if (!$this->error) {
						if ($tempfile && !$deletefile) {
							$tempfile=preg_replace("|[\\\/]|","",$tempfile); // make sure nobody gets /etc/passwd
							$tempfile=$this->store->get_config("files")."temp/".$tempfile;

							if (file_exists($tempfile)) {	
								$files = $this->store->get_filestore("files");
								if (!$isDefaultSet) {
									// keep the 'none' key for backwards compatibility
									if ($nlskey == "none" || $nlskey == $ARConfig->nls->default) {
										$files->copy_to_store($tempfile, $this->id, "file");
										$files->remove($this->id, "file_plaintext");
										$isDefaultSet = true;
									}
								}
								$armime = explode("/", $mimetype);
								if ($nlskey != "none") {
									$files->copy_to_store($tempfile, $this->id, $nlskey."_file");
									$files->remove($this->id, $nlskey."_file_plaintext");
									$this->data->$nlskey->filesize = $this->getdata("file_size", $nlskey); 
									$this->data->$nlskey->mimetype = $mimetype;
									$this->data->mime["type"] = $armime[0];
									$this->data->mime["subtype"] = $armime[1];
								} else {
									$this->data->filesize = $this->getdata("file_size", "none"); 
									$this->data->mimetype = $mimetype;
									$this->data->mime["type"] = $armime[0];
									$this->data->mime["subtype"] = $armime[1];
								}
								$properties["mimetype"][] = Array(
									"type"		=> "'".AddSlashes($this->data->mime["type"])."'",
									"subtype"	=> "'".AddSlashes($this->data->mime["subtype"])."'"
								);
								unlink($tempfile);

							} else {
								$tempfile=false;
							}
						} 
						if ($this->store->is_supported("fulltext")) {
							$filetext = $this->GetPlainText("file", $nlskey);
							if ($filetext) {
								$count++;
								$properties["fulltext"] = $fulltext;
								$properties["fulltext"][$count]["nls"]="'".AddSlashes($nlskey)."'";
								$properties["fulltext"][$count]["value"]="'".AddSlashes($this->store->format_for_fti(
										$filetext
										))."'";
							}
						}
						if ($deletefile) {
							$files = $this->store->get_filestore("files");
							if ($nlskey != "none") {
								$files->remove($this->id, $nlskey."_file");
								unset($this->data->$nlskey->filesize);
								unset($this->data->$nlskey->mimetype);
							} else {
								$files->remove($this->id, "file");
							}

							if ($nlskey == $this->data->nls->default) {
								$files->remove($this->id, "file");
							}
							foreach ($properties["fulltext"] as $count => $property) {
								if ($property['nls'] == AddSlashes($nlskey)) {
									unset($properties["fulltext"][$count]);
								}
							}
							if ($tempfile) {
								unlink($tempfile);
							}
						}
					} else {
						debug("err: $this->error");
						break;
					}
				}
				if (!$this->error) {
						$this->save($properties);
				}
			}
		}
	}
?>
