<?php
	if ($this->CheckLogin("edit") && $this->CheckConfig()) { 
		$newdata=$data;
		if (!$html) {
			$html=$htmltext;
		}
		// only keep the body.innerHTML
		//$html=eregi_replace("^.*<body[^>]*>","",$html);
		//$html=eregi_replace("</body[^>]*>.*$","",$html);
		// change hardcoded links and images to use a placeholder for the root
		$html=ereg_replace("(http://[^/]*)?".$this->store->root,"{arRoot}",$html);
		if ($this->data->mimetype=="text/html") {
			$file="file";
		} else {
			$file="file.html";
		}
		$files=$this->store->get_filestore("files");
		$files->write($html, $this->id, $file);
	}
?>