<?php
	if (($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) {

		global $HTTP_POST_VARS;

		$info = ldRegisterFile("file", $this->error);
		if (!$this->error) {
			$HTTP_POST_VARS = array_merge($HTTP_POST_VARS, $info);
			if ($info['file_type']) {
				$HTTP_POST_VARS['mimetype'] = $info['file_type'];
			}
		}
		$arResult = $info;
	}
?>