<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		// first do normal copyto
		if (!($result=$this->call("pobject::system.copyto.phtml", $arCallArgs))) {
			if ($newpath=$ARCurrent->newpath && $newid=$ARCurrent->newid) {
				// no errors: copy files
				$files=$this->store->get_filestore("files");
				if ($list=$files->ls($this->id)) {
					foreach ($list as $key => $file) {
						$files->copy($this->id, $file, $ARCurrent->newid, $file);
					}
				}
			}
		} else {
			$arResult=$result;
		}
	}
?>
