<?php
	if ( ( $this->arIsNewObject && $this->CheckLogin("add", $this->type) ) ||
			 ( !$this->arIsNewObject && $this->CheckLogin("edit") ) ) {
		global $HTTP_POST_FILES, $HTTP_POST_VARS;

		if (!$form_field) {
			$form_field="file";
		}

		$file_temp=$HTTP_POST_FILES[$form_field]['tmp_name'];
		$file=$HTTP_POST_FILES[$form_field]['name'];
		if ($file && is_uploaded_file($file_temp)) {
			// new file uploaded -> save it before PHP deletes it
			$file_artemp=tempnam($this->store->files."temp","upload");
			if (move_uploaded_file($file_temp, $file_artemp)) {
				// now make the new values available to wgWizKeepVars()
				$HTTP_POST_VARS[$form_field]=$file;
				$HTTP_POST_VARS[$form_field."_temp"]=substr($file_artemp,strlen($this->store->files."temp"));
				$HTTP_POST_VARS[$form_field."_size"]=$HTTP_POST_FILES[$form_field]['size'];
				$HTTP_POST_VARS[$form_field."_type"]=$HTTP_POST_FILES[$form_field]['type'];
			}
		}
	}
?>