<?php
	if (($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit", $this->type))) {

		if ($ARConfig->nls->default != $nls) {
			$arCallArgs[$ARConfig->nls->default]["name"] = $arCallArgs["file"];
		}
		$arCallArgs[$nls]["name"] = $arCallArgs["file"];
		$arResult=$this->call("system.save.data.phtml", $arCallArgs);
	}
?>
