<?php
	require_once($this->store->get_config("code")."modules/mod_webdav.php");
	
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")))
      && $this->CheckConfig()) {

		$tmpname=$this->getdata("file");
		$tmpname = Ariadne_WebDAV_Server::path_unescape($tmpname);

		$arCallArgs[$ARConfig->nls->default]["name"]=$tmpname;

		$this->call("system.save.data.phtml", $arCallArgs);
	}
?>
