	<LINK REL=stylesheet HREF="<?php echo $AR->dir->www; ?>widgets/menu/ie/menu.css" TYPE="text/css">
	<script src="<?php echo $AR->dir->www; ?>widgets/menu/ie/menu.js" type="text/javascript"></script>
	<style>
	BODY		{font-family: verdana;}
	P			{margin: 10; font-family: verdana;}
	PRE			{color: gray;}
	PRE B		{color: black; font-weight: bold;}
	CODE		{color: gray;}
	CODE B		{color: black; font-weight: bold;}
	</style>

 <?php
  if ($AR->user->data->login != "admin") {
    if (!$AR->user->grants["add"]) { $add="class=\"disabled\""; }
    if (!$AR->user->grants["edit"]) { $edit="class=\"disabled\""; }
    if (!$AR->user->grants["config"]) { $config="class=\"disabled\""; }
    if (!$AR->user->grants["delete"]) { $delete="class=\"disabled\""; }
    if (!$AR->user->grants["layout"]) { $layout="class=\"disabled\""; }
  }
  if (!$this->implements("pshortcut")) {
    $shortcut="class=\"disabled\"";
    $shortcutlink="javascript:void(0)";
  } else {
    $shortcut="";
    $shortcutlink="javascript:arshow('edit_object_shortcut','edit.object.shortcut.phtml')";
  }
?>
	
<!-- Start Defining the menu -->
<table id="menu" onselectstart="return false" onmouseover="menuOver()" onmouseout="menuOut()" onclick="menuClick()"
 cellspacing="1">
	<tr id="menubar">
		<td class="root">Object
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr class="sub">
					<td><span style="width: 20">&nbsp;</span></td>
					<td nowrap>New</td>
					<td><span class="more">4</span>
						<table class="menu" style="visibility: hidden" cellspacing=0>
<?php
  if ($AR->user->data->login=="admin") { // || $AR->user->grants["config"] ?
    $list=$this->ls("/system/ariadne/types/","Get.phtml");
  } else {
    if ($ARConfig->typetree) { // FIXME: change to typetree per user/group
      $list=$this->ls($ARConfig->typetree."/".$this->type."/",
        "Get.phtml");
    } else {
      $list=$this->ls("/system/ariadne/typetree/normal/".$this->type."/",
        "Get.phtml");
    }
  }
  while (list($key, $type)=each($list)) {
        if (!$type->data->$nls) {
          $typenls=$type->data->nls->default;
        } else {
          $typenls=$nls;
        }
	echo "<tr $add href=\"javascript:arshow('object_new','object.new.phtml?arNewType=".RawUrlEncode($type->data->value)."')\">\n";
	echo "  <td><span style=\"width: 20\">&nbsp;</span></td>\n";
	echo "	<td nowrap style=\"height: 20;\">".ereg_replace(" ","&nbsp;",$type->data->$typenls->name)."</td>\n";
	echo "  <td><span style=\"width: 20\">&nbsp;</span></td>\n";
	echo "</tr>\n";
  }
?>
						</table>
					</td>
				</tr>
				<tr <?php echo $delete; ?> href="javascript:arshow('objet_fs','object.rename.phtml')">
					<td></td>
					<td>Rename</td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_fs','object.copy.phtml')">
					<td></td>
					<td>Copy</td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_fs','object.link.phtml')">
					<td></td>
					<td>Link</td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr <?php echo $add; ?> href="javascript:arshow('object_import','object.import.phtml')">
					<td></td>
					<td>Import</td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_export','object.export.phtml')">
					<td></td>
					<td>Export</td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr <?php echo $delete; ?> href="javascript:arshow('obect_fs','object.delete.phtml')">
					<td></td>
					<td>Delete</td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root">Edit
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr class="sub">
					<td><span style="width: 20">&nbsp;</span></td>
					<td nowrap>Object</td>
					<td><span class="more">4</span>
						<table class="menu" style="visibility: hidden" cellspacing=0>
							<tr <?php echo $edit; ?> href="javascript:arshow('edit_object_data','edit.object.data.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td>Data</td>
								<td><span style="width: 20">&nbsp;</span></td>
							</tr>
							<tr <?php echo $shortcut; ?> href="<?php echo $shortcutlink; ?>">
								<td></td>
								<td>Shortcut</td>
								<td></td>
							</tr>
							<tr class="disabled">
								<td colspan="3"><hr></td>
							</tr>
							<tr <?php echo $edit; ?> href="javascript:arshow('edit_object_cache','edit.object.cache.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td>Cache</td>
								<td></td>
							</tr>
							<tr <?php echo $layout; ?> href="javascript:arshow('edit_object_layout','edit.object.layout.phtml')">
								<td></td>
								<td>Layout</td>
								<td></td>
							</tr>
							<tr class="disabled">
								<td colspan="3"><hr></td>
							</tr>
							<tr <?php echo $config; ?> href="javascript:arshow('edit_object_grants','edit.object.grants.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td>Grants</td>
								<td></td>
							</tr>
							<tr <?php echo $config; ?> href="javascript:arshow('edit_object_types','edit.object.types.phtml')">
								<td></td>
								<td>Types</td>
								<td></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('edit_find','edit.find.phtml')">
					<td></td>
					<td>Find</td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('edit_preferences','edit.preferences.phtml')">
					<td></td>
					<td>Preferences</td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root">View
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr href="javascript:arshow('view_fonts','view.fonts.phtml')">
					<td><span style="width: 20">&nbsp;</span></td>
					<td nowrap>Fonts</td>
					<td><span style="width: 20">&nbsp;</span></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:setview('list')">
					<td></td>
					<td>List</td>
					<td></td>
				</tr>
				<tr href="javascript:setview('details')">
					<td></td>
					<td>Details</td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('view','view.html')">
					<td></td>
					<td>Webpage</td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root">Help
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr href="javascript:arshow('help','help.topics.phtml')">
					<td><span style="width: 20">&nbsp;</span></td>
					<td>Index</td>
					<td><span style="width: 20">&nbsp;</span></td>
				</tr>
				<tr href="javascript:arshow('help','help.tutorials.phtml')">
					<td></td>
					<td>Tutorials</td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('help','help.search.phtml')">
					<td></td>
					<td>Search</td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('help_about','help.about.phtml')">
					<td></td>
					<td>About&nbsp;Ariadne</td>
					<td></td>
				</tr>
			</table>
		</td> 
                <form onSubmit="return viewpath(this.path.value)">
		<td width=100% class="disabled" align="right"><input type="text" name="path" size="40" value="<?php echo $this->path; ?>">&nbsp;</td> <!-- Needed to fill out the menubar -->
                </form>
	</tr>
</table>


<div id="outerDiv">
<!-- You could remove the above line and the closing div at the very end of this document -->
<script language="Javascript">
  fixSize();
</script>
