<?php
  include_once($this->store->code."nls/menu.".$nls);
?>
	<LINK REL=stylesheet HREF="<?php echo $AR->dir->www; ?>widgets/menu/ie/menu.css" TYPE="text/css">
	<script src="<?php echo $AR->dir->www; ?>widgets/menu/ie/menu.js" type="text/javascript"></script>
	<style>
	BODY		{font-family: verdana;}
	P			{margin: 10; font-family: verdana;}
	PRE			{color: gray;}
	PRE B		{color: black; font-weight: bold;}
	CODE		{color: gray;}
	CODE B		{color: black; font-weight: bold;}
	</style>

 <?php
  if ($AR->user->data->login != "admin") {
    if (!$AR->user->grants["add"]) { $add="class=\"disabled\""; }
    if (!$AR->user->grants["edit"]) { $edit="class=\"disabled\""; }
    if (!$AR->user->grants["config"]) { $config="class=\"disabled\""; }
    if (!$AR->user->grants["delete"]) { $delete="class=\"disabled\""; }
    if (!$AR->user->grants["layout"]) { $layout="class=\"disabled\""; }
  }
  if (!$this->implements("pshortcut")) {
    $shortcut="class=\"disabled\"";
    $shortcutlink="javascript:void(0)";
  } else {
    $shortcut="";
    $shortcutlink="javascript:arshow('edit_object_shortcut','edit.object.shortcut.phtml')";
  }
?>
	
<!-- Start Defining the menu -->
<table id="menu" onselectstart="return false" onmouseover="menuOver()" onmouseout="menuOut()" onclick="menuClick()"
 cellspacing="1">
	<tr id="menubar">
		<td class="root"><?php echo $ARnls["m_object"]; ?>
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr <?php echo $add; ?> href="javascript:arshow('edit_object_data','object.new.select.phtml')">
					<td><span style="width: 20">&nbsp;</span></td>
					<td><?php echo $ARnls["m_new"]; ?></td>
					<td><span style="width: 20">&nbsp;</span></td>
				</tr>
				<tr <?php echo $delete; ?> href="javascript:arshow('object_fs','object.rename.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_rename"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_fs','object.copy.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_copy"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_fs','object.link.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_link"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr <?php echo $add; ?> href="javascript:arshow('object_import','object.import.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_import"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('object_export','object.export.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_export"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr <?php echo $delete; ?> href="javascript:arshow('object_fs','object.delete.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_delete"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('object_fs','object.logoff.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_logoff"]; ?></td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root"><?php echo $ARnls["m_edit"]; ?>
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr class="sub">
					<td><span style="width: 20">&nbsp;</span></td>
					<td nowrap><?php echo $ARnls["m_object"]; ?></td>
					<td><span class="more">4</span>
						<table class="menu" style="visibility: hidden" cellspacing=0>
							<tr <?php echo $edit; ?> href="javascript:arshow('edit_object_data','edit.object.data.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td><?php echo $ARnls["m_data"]; ?></td>
								<td><span style="width: 20">&nbsp;</span></td>
							</tr>
							<tr <?php echo $shortcut; ?> href="<?php echo $shortcutlink; ?>">
								<td></td>
								<td><?php echo $ARnls["m_shortcut"]; ?></td>
								<td></td>
							</tr>
							<tr class="disabled">
								<td colspan="3"><hr></td>
							</tr>
							<tr <?php echo $edit; ?> href="javascript:arshow('edit_object_cache','edit.object.cache.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td><?php echo $ARnls["m_cache"]; ?></td>
								<td></td>
							</tr>
							<tr <?php echo $layout; ?> href="javascript:arshow('edit_object_layout','edit.object.layout.phtml')">
								<td></td>
								<td><?php echo $ARnls["m_layout"]; ?></td>
								<td></td>
							</tr>
							<tr class="disabled">
								<td colspan="3"><hr></td>
							</tr>
							<tr <?php echo $config; ?> href="javascript:arshow('edit_object_grants','edit.object.grants.phtml')">
								<td><span style="width: 20">&nbsp;</span></td>
								<td><?php echo $ARnls["m_grants"]; ?></td>
								<td></td>
							</tr>
							<tr <?php echo $config; ?> href="javascript:arshow('edit_object_types','edit.object.types.phtml')">
								<td></td>
								<td><?php echo $ARnls["m_types"]; ?></td>
								<td></td>
							</tr>
							<tr <?php echo $config; ?> href="javascript:arshow('edit_object_nls','edit.object.nls.phtml')">
								<td></td>
								<td><?php echo $ARnls["m_language"]; ?></td>
								<td></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr href="javascript:arshow('edit_priority','edit.priority.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_priority"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('edit_find','edit.find.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_find"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('edit_preferences','<?php echo $this->store->root.$AR->user->path; ?>edit.preferences.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_preferences"]; ?></td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root"><?php echo $ARnls["m_view"]; ?>
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr href="javascript:artoggleexplorerbar()">
					<td><span style="width: 20">&nbsp;</span></td>
					<td nowrap><?php echo $ARnls["m_explorerbar"]; ?></td>
					<td><span style="width: 20">&nbsp;</span></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:setview('small')">
					<td></td>
					<td><?php echo $ARnls["m_small"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:setview('large')">
					<td></td>
					<td><?php echo $ARnls["m_large"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:setview('details')">
					<td></td>
					<td><?php echo $ARnls["m_details"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('_new','view.html')">
					<td></td>
					<td><?php echo $ARnls["m_web"]; ?></td>
					<td></td>
				</tr>
			</table>
		</td>
		<td class="root"><?php echo $ARnls["m_help"]; ?>
			<table cellspacing="0" class="menu" style="visibility: hidden;">
				<tr href="javascript:arshow('help','help.topics.phtml')">
					<td><span style="width: 20">&nbsp;</span></td>
					<td><?php echo $ARnls["m_index"]; ?></td>
					<td><span style="width: 20">&nbsp;</span></td>
				</tr>
				<tr href="javascript:arshow('help','help.tutorials.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_tutorials"]; ?></td>
					<td></td>
				</tr>
				<tr href="javascript:arshow('help','help.search.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_search"]; ?></td>
					<td></td>
				</tr>
				<tr class="disabled">
					<td colspan="3"><hr></td>
				</tr>
				<tr href="javascript:arshow('help_about','help.about.phtml')">
					<td></td>
					<td><?php echo $ARnls["m_about"]; ?></td>
					<td></td>
				</tr>
			</table>
		</td> 
		<form onSubmit="return viewpath(this.path.value)">
		<td width=100% align="right" class="disabled"><input class="path" type="text" name="path" size="40" value="<?php echo $this->path; ?>">&nbsp;</td> <!-- Needed to fill out the menubar -->
		</form>
	</tr>
</table>


<div id="outerDiv">
<!-- You could remove the above line and the closing div at the very end of this document -->
<script language="Javascript">
  fixSize();
</script>
