<?php
debug("paddressbook: Load","object");
include_once($this->code."objects/pdir.phtml");

function sort_addresses($a,$b) {
		global $addresses_sortby;
		if ($a->data->$addresses_sortby == $b->data->$addresses_sortby) return 0;
		return ($a->data->$addresses_sortby < $b->data->$addresses_sortby) ? -1 : 1;
}


class paddressbook extends pdir { // definitie class

	function get_addresses($crit="",$sortby="name") {
		global $ARCurrent;

		debug("paddressbook: get_addresses([crit], $sortby)","object");
		if (is_array($crit)) {
			$criteria=$crit;
		}
		$criteria["object"]["implements"]["="]="'address'";
		$this->find(".",$criteria,"populate.phtml","");

		unset($criteria);
		$criteria["object"]["implements"]["="]="'paddressbook'";
		$criteria["object"]["type"]["="]="'pshortcut'";
		$this->find(".",$criteria,"populate.phtml","crit=".urlencode(serialize($crit)));

		if (($sortby!=-1) && is_array($ARCurrent->addresses)) {
			global $addresses_sortby;
			$addresses_sortby=$sortby;

			uasort($ARCurrent->addresses,sort_addresses);
		}
		debug("paddressbook: get_addresses: end","all");
		return $ARCurrent->addresses;
	}

	function _get_addresses($crit="",$sortby="") {
		return $this->get_addresses($crit,$sortby);
	}

	function _call_address($address,$template="",$args="") {
		return $address->call($template,$args);
	}
} // end class paddressbook
?>