<?php
    /******************************************************************
     paddressbook.phtml                                    Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: 31 october 2002

     Copyright 2002 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > ppage > pdir > paddressbook
     Description:

       This is the class definition file of the paddressbook class.

    ******************************************************************/
debug("paddressbook: Load","object");
global $AR;
require_once($AR->dir->install."/lib/objects/pdir.phtml");

function sort_addresses($a,$b) {
	global $addresses_sortby;

	if ($a->data->$addresses_sortby == $b->data->$addresses_sortby) {
		$result=0;
	} else {
		$result=($a->data->$addresses_sortby < $b->data->$addresses_sortby) ? -1 : 1;
	}
	return $result;
}

define("DONT_SORT", false);

class paddressbook extends pdir { // paddressbook class definition

	function get_addresses($search_criteria="",$sortby="name") {
		global $ARCurrent;

		debug("paddressbook: get_addresses([crit], $sortby)","object");
		if (is_array($search_criteria)) {
			$criteria=$search_criteria;
		}
		$criteria["object"]["implements"]["="]="address";
		$this->find(".",$criteria,"populate.phtml");

		unset($criteria);
		$criteria["object"]["implements"]["="]="paddressbook";
		$criteria["object"]["type"]["="]="pshortcut";
		$this->find(".", $criteria, "populate.phtml", compact("search_criteria"));

		if (($sortby!=DONT_SORT) && is_array($ARCurrent->addresses)) {
			global $addresses_sortby;
			$addresses_sortby=$sortby;

			uasort($ARCurrent->addresses, sort_addresses);
		}
		debug("paddressbook: get_addresses: end","all");
		return $ARCurrent->addresses;
	}

	function _get_addresses($search_criteria="", $sortby="name") {
		return $this->get_addresses($search_criteria, $sortby);
	}

	function _call_address($address, $template="", $args="") {
		return $address->call($template,$args);
	}
} // end of paddressbook class definition
?>