<?php
debug("particle.phtml: Load","object");
include_once($this->code."objects/ppage.phtml");

class particle extends ppage { // definitie class

	function ParseSummary($template="view.html", $extra="", $text="") {
		debug("particle: ParseSummary()","object");
        if (eregi("<a>",$this->nlsdata->summary)) {
            return eregi_replace("<a>","<a href=\"".$this->make_url()."$template\"$extra>",$this->nlsdata->summary);
        } else {
			if (!$text) {
				$text=$ARnls["more"]."...";
			}
			return $this->nlsdata->summary." <a href=\"".$this->make_url()."$template\"$extra>$text</a>";
		}
	}

	function _ParseSummary($template="view.html", $extra="", $text="") {
		return $this->ParseSummary($template, $extra, $text);
	}

} // end class article
?>