<?php
debug("particle.phtml: Load","object");
include_once($this->code."objects/pobject.phtml");

class particle extends pobject { // definitie class

	function parse_summary() {
		debug("particle: parse_summary()","object");
        if (eregi("<a>",$this->nlsdata->summary)) {
            return eregi_replace("<a>","<a href=\"".$this->store->root.$this->path."\">",$this->nlsdata->summary);
        }
        return $this->nlsdata->summary;
	}

	function _parse_summary() {
		return $this->parse_summary();
	}

} // end class article
?>