<?php
    /******************************************************************
     pcalitem.phtml                                        Muze Ariadne
     ------------------------------------------------------------------
     Author: Auke van Slooten (auke@muze.nl)
     Date: 31 october 2002

     Copyright 2002 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > pcalitem
     Description:

       This is the class definition file of the pcalitem class.

    ******************************************************************/

require_once(AriadneBasePath."/objects/pobject.phtml");

class pcalitem extends pobject { // pcalitem class definition

	function DelTimeframe($date) {
		debug("pcalitem->DelTimeframe($date)","object");
		$result = array();
		if(is_array($this->data->timeframes)){
			foreach($this->data->timeframes as $timeframe){
				if ($timeframe["start"]!=$date) {
					$result[]=$timeframe;
				} else {
					$this->store->del_property($this->id, "timeframe", $timeframe);
				} 
			}
		}
		$this->data->timeframes=$result;
		debug("pcalitem->DelTimeframe: end","all");
		return $result;
	}

	function NewEndtime($endtime) {
		debug("pcalitem->NewEndtime($endtime)","object");
		@reset($this->data->timeframes);
		$timeframe=current($this->data->timeframes);
		while ($timeframe && ($timeframe["start"]<$endtime)) {
			$result[]=$timeframe;
			$timeframe=next($this->data->timeframes);
		}
		while ($timeframe) {
			$this->store->del_property($this->id, "timeframe", $timeframe);
			$timeframe=next($this->data->timeframes);
		}
		$this->data->timeframes=$result;
		debug("pcalitem->NewEndtime: end","all");
		return $result;
	}

} // end of pcalitem class definition
