<?php

debug("pcalendar: Load","object");
include_once($this->code."objects/pdir.phtml");

class pcalendar extends pdir { // definitie class

	function populate($pop_from, $pop_to, $pop_priority, $pop_template="AddTime.phtml", $pop_args="") {
		debug("pcalendar: populate($prop_from, $prop_to, $prop_priority, $prop_template, $prop_args)","object");
		$criteria["timeframe"]["start"]["<"]=$pop_to;
		$criteria["timeframe"]["end"][">"]=$pop_from;
		$criteria["priority"]["value"][">="]=$pop_priority;
		$this->find(".",$criteria, $pop_template, $pop_args);
		unset($criteria);
		$criteria["object"]["implements"]["="]="'pcalendar'";
		$criteria["object"]["type"]["="]="'pshortcut'";
		$this->find("",$criteria,"populate.phtml", Array(
			"pop_from"		=> $pop_from,
			"pop_to" 		=> $pop_to,
			"pop_priority"	=> $pop_priority,
			"pop_template"	=> $pop_template,
			"pop_args"		=> $pop_args ) );
		debug("pcalendar: populate: end","all");
	}

	function get_items($priority, $max=0, $start="", $end="") {
		global $ARCurrent;
		unset($ARCurrent->arCalItems);
		unset($ARCurrent->arDateList);
		$now=getdate(time());
		if (!$start) {
			$start=mktime(0,0,0,$now["month"],$now["mday"], $now["year"]);
		}
		if (!$end) {
			$start=mktime(0,0,0,$now["month"],$now["mday"]+1, $now["year"]);
		}
		$this->populate($start, $end, $priority, "system.get.item-by-time.phtml");
		if (is_array($ARCurrent->arCalItems)) {
			asort($ARCurrent->arDateList);
			reset($ARCurrent->arDateList);
			$i=0;
			while ((!$max || ($i<$max)) && (list($key, $item)=each($ARCurrent->arDateList))) {
				$items[]=$ARCurrent->arCalItems[$key];
				$i++;
			}
		} else {
			debug("no items found?","all");
		}
		return $items;
	}

	function _get_items($priority, $max=0, $start="", $end="") {
		return $this->get_items($priority, $max, $start, $end);
	}

} // end class pcalendar
?>