<?php

include_once($this->code."objects/pobject.phtml");

debug("pcalitem: Load","object");

class pcalitem extends pobject { // definitie class

	function DelTimeframe($date) {
		debug("pcalitem->DelTimeframe($date)","object");
		reset($this->data->timeframes);
		while (list($index, $timeframe)=each($this->data->timeframes)) {
			if ($timeframe["start"]!=$date) {
				$result[]=$timeframe;
			} else {
				$this->store->del_property($this->id, "timeframe", $timeframe);
			} 
		}
		$this->data->timeframes=$result;
		debug("pcalitem->DelTimeframe: end","all");
		return $result;
	}

	function NewEndtime($endtime) {
		debug("pcalitem->NewEndtime($endtime)","object");
		@reset($this->data->timeframes);
		$timeframe=@current($this->data->timeframes);
		while ($timeframe && ($timeframe["start"]<$endtime)) {
			$result[]=$timeframe;
			$timeframe=next($this->data->timeframes);
		}
		while ($timeframe) {
			$this->store->del_property($this->id, "timeframe", $timeframe);
			$timeframe=next($this->data->timeframes);
		}
		$this->data->timeframes=$result;
		debug("pcalitem->NewEndtime: end","all");
		return $result;
	}

} // end class ptimeframe
?>