<?php
    /******************************************************************
     pfile.phtml                                           Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: 31 october 2002

     Copyright 2002 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > pfile
     Description:

       This is the class definition file of the pfile class.

    ******************************************************************/

debug("pfile: Load","object");
global $AR;
require_once($AR->dir->install."/lib/objects/pobject.phtml");
require_once($AR->dir->install."/lib/modules/mod_url.php");
require_once($AR->dir->install."/lib/modules/mod_mimemagic.php");

class pfile extends pobject { // pfile class definition

	function GetFile($file='file', $nls='') {
		if (!$nls) {
			$nls = $this->reqnls;
		}
		$files = $this->store->get_filestore("files");
		if ($files->exists($this->id, $nls."_$file")) {
			$file = $nls."_$file";
		}
		return $files->read($this->id, $file);
	}

	function ExistsFile($file='file', $nls='') {
		if (!$nls) {
			$nls = $this->reqnls;
		}
		$files = $this->store->get_filestore("files");

		$result = $files->exists($this->id, $nls."_$file");
		if( $result ){
			return $result;
		} else {
			return $files->exists($this->id, $file);
		}
	}

	function ParseFile($filecontent) {
		return URL::ARtoRAW($filecontent, true);
	}

	function ShowFile($file='file', $nls='', $mimetype='') {
		global $AR, $ARCurrent, $ARnls;
		if (!$nls) {
			$nls = $this->reqnls;
		}
		$files = $this->store->get_filestore("files");

		if ($files->exists($this->id, $nls."_$file")) {
			$file = $nls."_$file";
			if (!$mimetype) {
				$mimetype = $this->data->$nls->mimetype;
			}
		}
		if (!$mimetype) {
			$mimetype = $this->data->mimetype;
		}

		if (!$mimetype) {
			if (function_exists("get_content_type")) {
				$mimetype = get_content_type($mimetype, basename($this->path));
			}
		}

		if (!$ARCurrent->arDontCache && $ARCurrent->cachetime!=-1 && $this->CheckPublic('read')) {
			$ARCurrent->cachetime=-2; // set cache to onchange
		}
		$template = $this->getvar("arCallFunction");
		if (!$template || $template == "view.html") {
			$filename = basename($this->path);
		}
		if (!preg_match("|^text/|", $mimetype)) {
			$size = $files->size($this->id, $file);
		}
		

		if (ldSetContent($mimetype, $size)) {
			$cacheseconds=1800; // 1/2 hour
			$expires=time()+$cacheseconds;
			if ($AR->user->data->login=="public" || $this->CheckPublic("read")) {
				// always set the client side cache headers, independant of
				// server side cache configuration. Except for private content
				// (needed to prevent proxies from caching it too). If server 
				// side caching is on, the loader will override this header.
				ldSetClientCache(true, $expires);
			}
		} else if(!preg_match("|^text/|", $mimetype)) {
			error( sprintf( $ARnls["err:headerssentnottext"], $this->path ) );
			$stop=true;
		}
		if( !$stop ) {
			if ($filename) {
				ldHeader("Content-Disposition: inline; filename=$filename");
			}
			if ($mimetype=="text/html") { // parse {arRoot}
				// assume html files to use charset UTF-8; this will always work correctly
				// with the MSIE html editor, and won't corrupt 'normal' html.
				// ldHeader("Content-Type: text/html; charset=UTF-8");
				echo $this->ParseFile($this->GetFile($file));
			} else {
				// ldHeader("Content-Type: $mimetype");
				// set pragma: cache; bug workaround for internet explorer and https
				if (ldGetServerVar('HTTPS')) {
					ldHeader('Pragma: cache');
				}
				$files->show($this->id, $file);
			}
		}
		$files->close();
	}

	function DownloadFile($file='file', $nls='', $filename=false) {
		global $ARCurrent, $ARnls;
		if (!$nls) {
			$nls = $this->reqnls;
		}
		$files = $this->store->get_filestore("files");

		if ($files->exists($this->id, $nls."_$file")) {
			$file = $nls."_$file";
		}

		if (!$ARCurrent->arDontCache && $ARCurrent->cachetime!=-1 && $this->CheckPublic('read')) {
			$ARCurrent->cachetime=-2; // set cache to onchange
		}
		$files=$this->store->get_filestore("files");
		if (!$filename) {
			$filename = substr($this->path, strlen($this->parent), -1);
		}
		ldHeader('Cache-Control: private');
		// set pragma: cache; bug workaround for internet explorer and https
		if (ldGetServerVar('HTTPS')) {
			ldHeader('Pragma: cache');
		} else {
			ldHeader('Pragma: no-cache');
		}
		if (!ldHeader("Content-type: application/x-ariadne-download")) {
			error( sprintf( $ARnls["err:headerssentnottext"], $this->path ) );
		} else {
			ldHeader("Content-Disposition: attachment; filename=\"".$filename."\"");
			ldHeader("Content-length:".(string)$size);
			$files->show($this->id, $file);
		}
		$files->close();
	}

	function _ParseFile($filecontent) {
		return $this->ParseFile($filecontent);
	}
  
	function _ExistsFile($file='file', $nls='') {
		return $this->ExistsFile($file, $nls);
	}

	function _GetFile($file='file', $nls='') {
		return $this->GetFile($file, $nls);
	}
  
	function _ShowFile($file='file', $nls='', $mimetype='') {
		return $this->ShowFile($file, $nls, $mimetype);
	}

	function _DownloadFile($file='file', $nls='', $filename=false) {
		return $this->DownloadFile($file, $nls, $filename);
	}

	function GetPlainText($file='file', $nls='') {  
		global $AR;
		$result="";
		$files=$this->store->get_filestore("files");

		if (!$nls) {
			$nls = $this->reqnls;
		}
		$files = $this->store->get_filestore("files");

		$mimetype = $this->data->mimetype;
		if ($files->exists($this->id, $nls."_$file")) {
			$file = $nls."_$file";
			if ( $this->data->$nls->mimetype ) {
				$mimetype = $this->data->$nls->mimetype;
			}
		}
		if ( !$mimetype ) {
			$defaultnls = $this->data->nls->default;
			$mimetype = $this->data->{$defaultnls}->mimetype;
		}
		$file_plaintext = $file."_plaintext";

		if ($files->exists($this->id, $file_plaintext) ) {
			$result = $files->read($this->id, $file_plaintext);
		} else {
			if (preg_match("|^text/|i", $mimetype)) {
				$result=$this->GetFile($file);
				if ($mimetype=="text/html") {
					$result=$this->html_to_text($result);
				}
			} elseif (preg_match("|^application/(.*)$|i", $mimetype, $regs)) {
				$textualizer=$AR->Textualizers[$regs[1]];
				if ($textualizer) {
					$temp_file = tempnam($this->store->get_config('files').'temp/', 'totext');
					@unlink($temp_file);
					$files->copy_from_store($temp_file, $this->id, $file);
					exec(preg_replace('/FILE/', $temp_file, $textualizer), $result, $ret);
				
					@unlink($temp_file);
					if (!$ret) {
						$result = implode("\n", $result);
					} else {
						$result = "";
					}
				}
			}
			if( $result != "" ) {
				$files->write($result, $this->id, $file_plaintext);
			}
		}
		return $result;
	}
	
	function _GetPlainText($file='file', $nls='') {
		return $this->GetPlainText($file, $nls);
	}
  
	function SaveFile($contents, $mimetype=false, $name='file', $nls='') {  
		$result="";
		$name=preg_replace("|[\\\/]|","",$name); // make sure nobody gets /etc/passwd
		if ($name) {
			if ( $nls !== false ) {
				if (!$nls) {
					$nls = $this->reqnls;
				}
				$name = $nls.'_'.$name;
			}
			if (!$this->arIsNewObject && $this->CheckSilent('edit')) {
				$files=$this->store->get_filestore("files");
				return $files->write($contents, $this->id, $name);
			} else if ($this->arIsNewObject && $this->CheckSilent('add','pfile')) {
				// new pfile, so it has no id yet, use the tempfile
				require_once($this->store->get_config('code')."modules/mod_mimemagic.php");
				$result = Array();

				// fake an uploaded file, put it in the normal temp dir
				$file_artemp=tempnam($this->store->get_config("files")."temp","upload");
				if ($fp=fopen($file_artemp, "wb")) {
					$result=fwrite($fp, $contents);
					fclose($fp);
				}

				// now make the new values available to system.save.data.phtml
				$info[$name]=$this->data->name;
				$info[$name."_temp"]=substr($file_artemp,strlen($this->store->get_config("files")."temp"));
				$info[$name."_size"]=strlen($contents);
				if (!$mimetype) {
					$type = get_mime_type($file_artemp);
				} else {
					$type = $mimetype;
				}
				$info[$name."_type"]=$type;
				$info['mimetype']=$type;
				$_POST = array_merge($_POST, $info);

				return true;
			}
		} else {
			return false;
		}
	}
	
	function _SaveFile($contents, $mimetype=false, $name='file', $nls='') {
		return $this->SaveFile($contents, $mimetype, $name, $nls);
	}
  
} // end of pfile class definition
?>