<?php

debug("pfile: Load","object");
include_once($this->code."objects/pobject.phtml");

class pfile extends pobject { // definitie class

	function ShowFile() {
		$files=$this->store->get_filestore("files");
		if (!ereg("^text/",$this->data->mimetype)) {
			$size=$files->size($this->id, "file");
		}
		if (ldSetContent($this->data->mimetype, $size)) {
			$cacheseconds=1800; // 1/2 hour
			$expires=time()+$cacheseconds;
			ldSetClientCache(true, $expires);
		} else if(!ereg("^text/",$this->data->mimetype)) {
			error("headers already sent and this is not a text file (".$this->path.")");
			$stop=true;
		}
		if( !$stop ) {
			if ($this->data->mimetype=="text/html") { // parse {arRoot}
				// assume html files to use charset UTF-8; this will always work correctly
				// with the MSIE html editor, and won't corrupt 'normal' html.
				ldHeader("Content-Type: text/html; charset=UTF-8");
				echo str_replace("{arRoot}",$this->store->root,$files->read($this->id, "file"));
			} else {
				$files->show($this->id, "file");
			}
		}
	}

	function _ShowFile() {
		return $this->ShowFile();
	}
  
} // end class pfile
?>