<?php

debug("pfile: Load","object");
include_once($this->code."objects/pobject.phtml");

class pfile extends pobject { // definitie class

  function ShowFile() {
    if (!headers_sent()) {
      Header("Content-type: ".$this->data->mimetype);
    } else if(!ereg("^text/",$this->data->mimetype)) {
      error("headers already sent and this is not a text file (".$this->path.")");
      $stop=true;
    }
    if( !$stop ) {
      if ($this->data->mimetype=="text/html") { // parse {arRoot}
        echo str_replace("{arRoot}",$this->store->root,@implode("",@file($this->store->files."files".$this->path."/view=")));
      } else {
        @readfile($this->store->files."files".$this->path."/view=");
      }
    }
  }

  function _ShowFile() {
    return $this->ShowFile();
  }
  
} // end class pfile
?>