<?php

debug("pnewspaper: Load","object");
include_once($this->code."objects/pdir.phtml");


class pnewspaper extends pdir { // definitie class

	function get_articles($display, $max="", $start="", $end="") {
		global $ARCurrent;
		debug("pnewspaper: get_articles($display, $max, $start, $end)","object");
		if (!$start) { $start=time(); }
		if (!$end) { $end=$start; }
		$criteria["article"]["start"]["<="]=$end;
		$criteria["article"]["end"][">="]=$start;
		$criteria["article"]["display"]["="]="'".AddSlashes($display)."'";
		$this->find(".",$criteria,"system.get.article-by-priority.phtml","display=$display");
		if (is_array($ARCurrent->priority)) {
			$ARCurrent->priority=array_reverse($ARCurrent->priority);
			arsort($ARCurrent->priority);
			reset($ARCurrent->priority);
			while ((!$max || ($i<$max)) && (list($key,$val)=each($ARCurrent->priority))) {
				$articles[]=$ARCurrent->article[$key];
				$i++;
			}
		}
		debug("pnewspaper: get_articles: end","all");
		return $articles;
	}

	function _get_articles($display,$max="",$start="",$end="") {
		return $this->get_articles($display,$max,$start,$end);
	}

	function _call_article($article,$template="",$args="") {
		return $article->call($template,$args);
	}

	function clear_articles() {
		global $ARCurrent;
		unset($ARCurrent->articles);
		unset($ARCurrent->priority);
	}

	function _clear_articles() {
		return $this->clear_articles();
	}

} // end class pnewspaper
?>