<?php
    /******************************************************************
     pnewspaper.phtml                                      Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: 31 october 2002

     Copyright 2002 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > ppage > pdir > pnewspaper
     Description:

       This is the class definition file of the pnewspaper class.

    ******************************************************************/

debug("pnewspaper: Load","object");
global $AR;
require_once($AR->dir->install."/lib/objects/pdir.phtml");


class pnewspaper extends pdir { // pnewspaper class definition

	function get_articles($display, $max="", $start="", $end="", $nls="", $priority_date="") {
		global $ARCurrent;
		debug("pnewspaper: get_articles($display, $max, $start, $end)","object");
		if (!$start) { 
			$start=time(); 
		}
		if (!$end) { 
			$end=$start; 
		}
		if (!$priority_date) {
			$priority_date=time();
		}
		$query="object.implements='particle' and article.start<=$end ".
			"and article.end>=$start and article.display='".AddSlashes($display)."'";
		if ($nls) {
			$query.=" and name.nls='".AddSlashes($nls)."'";
		}
		$query.=" limit 0"; //.(((int)$max)*2);
		// FIXME: it appears that 'limit 0' is actually translated to 'limit 0, 100, 0', which works like 'limit 100'...
		$this->find(".",$query,"system.get.article-by-priority.phtml",Array("display" => $display, "date" => $priority_date), 0, 0);
		if (is_array($ARCurrent->priority)) {
			$ARCurrent->priority=array_reverse($ARCurrent->priority, true);
			arsort($ARCurrent->priority);
			reset($ARCurrent->priority);
			while ((!$max || ($i<$max)) && (list($key,$val)=each($ARCurrent->priority))) {
				$articles[]=$ARCurrent->article[$key];
				$i++;
			}
		}
		debug("pnewspaper: get_articles: end","all");
		return $articles;
	}

	function _get_articles($display,$max="",$start="",$end="",$nls="",$priority_date="") {
		return $this->get_articles($display,$max,$start,$end,$nls,$priority_date);
	}

	function _call_article($article,$template="",$args="") {
		return $article->call($template,$args);
	}

	function clear_articles() {
		// FIXME: in current news system this should be done 
		// automatically by get_articles? check with CMS.
		global $ARCurrent;
		unset($ARCurrent->articles);
		unset($ARCurrent->priority);
		unset($ARCurrent->idlist);
	}

	function _clear_articles() {
		return $this->clear_articles();
	}

} // end of pnewspaper class definition
