<?php

debug("ppage: Load","object");
include_once($this->code."objects/pobject.phtml");

class ppage extends pobject { // definitie class

  function ParsePage($page) {
    return str_replace("{arRoot}",$this->store->root,$page);
  }

  function GetPage($nls="", $source=false) {
    if (!$nls) {
      $target=$this->nlsdata->page;
    } else if ($this->data->$nls) {
      $target=$this->data->$nls->page;
    }
    if ($source) {
      return htmlspecialchars($this->ParsePage($target));
    } else {
      return $this->ParsePage($target);
    }
  }

  function ShowPage($nls="", $source=false) {
    echo $this->GetPage($nls, $source);
  }

  function _ParsePage($page) {
    return $this->ParsePage($page);
  }

  function _GetPage($nls="", $source=false) {
    return $this->GetPage($nls, $source);
  }

  function _ShowPage($nls="") {
    return $this->ShowPage($nls);
  }

} // end class ppage
?>