<?php

debug("pphotobook: Load","object");
include_once($this->code."objects/pdir.phtml");

class pphotobook extends pdir { // definitie class

	function get_photos($max=0,$start=0) {
		$crit["object"]["implements"]["="]="'pphoto'";
		$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
		return $this->find($this->path,$crit,"system.get.phtml","",$max,$start);
	}

	function get_thumb_settings() {
		global $ARConfig;
		return $ARConfig->cache[$this->path]->thumb;
	}

	function _get_thumb_settings() {
		return $this->get_thumb_settings();
	}

} // end class pphotobook
?>