<?php
    /******************************************************************
     pproject.phtml                                           Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: 28 december 2010

     Copyright 2010 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > ppage > pdir > psection > pproject
     Description:

       This is the class definition file of the psite class.

    ******************************************************************/

debug("psection: Load","object");
global $AR;
require_once($AR->dir->install."/lib/objects/psection.phtml");

class pproject extends psection {  // pproject class definition


	function getConfigData() {
	global $ARConfig;
		psection::getConfigData();
		$configcache=$ARConfig->cache[$this->path];
		$configcache->project=$this->path;
		$ARConfig->cache[$this->path]=$configcache;
	}

} // end of pproject class definition
