<?php
    /******************************************************************
     psearch.phtml                                     Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: August 8 2003

     Copyright 2003 Muze

    -------------------------------------------------------------------

     Class inheritance: 	pobject > ppage > pdir > psearch
     Description:

       This is the class definition file of the psearch class.

    ******************************************************************/

require_once(AriadneBasePath."/objects/pdir.phtml");

class psearch extends pdir { // psearch class definition

	function ls($path = '', $function = 'list.html', $args = '') {
		$path=$this->store->make_path($this->path, $path);
		if( (substr($path, 0, strlen($this->path))==$this->path)) {
			return pdir::find($this->data->path, $this->data->query, $function, $args);
		} else {
			return pdir::ls($path, $function, $args);
		}
	}

	function real_ls($path, $function="list.html", $args="") {
		return pdir::ls($path, $function, $args);
	}

	function find($path, $criteria, $function="list.html", $args="", $limit=100, $offset=0) {
		$path=$this->store->make_path($this->path, $path);
		if( (substr($path, 0, strlen($this->path))==$this->path)) {
			if ($criteria) {
				$criteria = "(" . $this->data->query . ") and " . $criteria;
			} else {
				$criteria = $this->data->query;
			}
			return pdir::find($this->data->path, $criteria, $function, $args, $limit, $offset);
		} else {
			return pdir::find($path, $criteria, $function, $args, $limit, $offset);
		}
	}

	function count_find($path='', $criteria='') {
		$path=$this->store->make_path($this->path, $path);
		if( (substr($path, 0, strlen($this->path))==$this->path)) {
			if ($criteria) {
				$criteria = "(" . $this->data->query . ") and " . $criteria;
			} else {
				$criteria = $this->data->query;
			}
			return pdir::count_find($this->data->path, $criteria);
		} else {
			return pdir::count_find($path, $criteria);
		}
	}


	function real_find($path, $criteria, $function="list.html", $args="", $limit=100, $offset=0) {
		return pdir::find($path, $criteria, $function, $args, $limit, $offset);
	}

	function real_count_find($path='', $query='') {
		return pdir::count_find($path, $query);
	}

	function _count_find($query='') {
		return $this->count_find($this->path, $query);
	}

	function _ls($function='list.html', $args="") {
		return $this->ls($this->path, $function, $args);
	}

	function _find($criteria, $function="list.html", $args="", $limit=100, $offset=0) {
		return $this->find($this->path, $criteria, $function, $args, $limit, $offset);
	}

} // end of psearch class definition
