<?php
    /******************************************************************
     pshadowuser.phtml                                     Muze Ariadne
     ------------------------------------------------------------------
     Author: Johann Hanne <jhml@gmx.net>
     Date: 14 April 2004

     Copyright Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance:   pobject > ppage > pdir > puser > pshadowuser
     Description:

       This is the class definition file of the pshadowuser class.

    ******************************************************************/

require_once(AriadneBasePath."/objects/puser.phtml");

class pshadowuser extends puser {  // pshadowuser class definition

} // end of pshadowuser class definition
