<?php
    /******************************************************************
     psite.phtml                                           Muze Ariadne
     ------------------------------------------------------------------
     Author: Muze (info@muze.nl)
     Date: 31 october 2002

     Copyright 2002 Muze

     This file is part of Ariadne.

     Ariadne is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published 
     by the Free Software Foundation; either version 2 of the License, 
     or (at your option) any later version.
 
     Ariadne is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Ariadne; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

    -------------------------------------------------------------------

     Class inheritance: 	pobject > ppage > pdir > psection > psite
     Description:

       This is the class definition file of the psite class.

    ******************************************************************/

debug("psite: Load","object");
global $AR;
include_once($ariadne."/objects/psection.phtml");

class psite extends psection {  // psite class definition

	function getConfigData() {
	global $ARConfig;
		pdir::getConfigData();

      $configcache=$ARConfig->cache[$this->path];
      $hostsubwww = $host = $_SERVER["HTTP_HOST"];
      if (substr($host, 0, 4) == 'www.') {
          $hostsubwww = substr($host, 4);
      }
      if (($sitenls=$this->data->url_list["host"][$hostsubwww]) 
          || (($sitenls=$this->data->url_list["host"]["www.".$hostsubwww]))) {

          $url = $this->data->url_list["nls"][$sitenls];
      }
      if (!$url) {
          $url=$this->data->url;
      }
      if ($url) {
          $configcache->root["path"]=$this->path;
          $configcache->root["value"]=$url;
          $configcache->root["list"]=$this->data->url_list;
          if ($sitenls) {
              $configcache->root["nls"] = $sitenls;
          }
      }

      $configcache->site=$this->path;
      $configcache->section=$this->path;
      $ARConfig->cache[$this->path]=$configcache;
	}

} // end of psite class definition
?>