<?php

include_once($ariadne."/stores/mssqlstore.phtml");

class mssqlstore_install extends mssqlstore {

	function initialize() {
		echo "initializing MSSQL store.\n";

		$queries[0]["msg"]="creating objects table.";
		$queries[0]["query_string"]="
CREATE TABLE ".$this->tbl_prefix."objects (
	[id] integer IDENTITY (1,1) PRIMARY KEY,
	[type] varchar(16) DEFAULT '' NOT NULL,
	[object] text,
	[vtype] varchar(16) DEFAULT '' NOT NULL,
	[lastchanged] DATETIME DEFAULT CURRENT_TIMESTAMP
);";
		$queries[1]["msg"]="creating objects index.";
		$queries[1]["query_string"]="CREATE INDEX ".$this->tbl_prefix."objects_lastchanged ON ".$this->tbl_prefix."objects (lastchanged);";

		$queries[2]["msg"]="creating nodes table.";
		$queries[2]["query_string"]="
CREATE TABLE ".$this->tbl_prefix."nodes (
	path varchar(127) DEFAULT '' NOT NULL PRIMARY KEY,
	parent varchar(127) DEFAULT '' NOT NULL,
	object numeric(11) DEFAULT '0' NOT NULL,
	priority numeric(11) DEFAULT '0' NOT NULL
);";
		$queries[3]["msg"]="creating node_object index.";
		$queries[3]["query_string"]="CREATE INDEX ".$this->tbl_prefix."nodes_object ON ".$this->tbl_prefix."nodes (object);";
		$queries[4]["msg"]="creating node_parent index.";
		$queries[4]["query_string"]="CREATE INDEX ".$this->tbl_prefix."nodes_parent ON ".$this->tbl_prefix."nodes (parent);";
		$queries[5]["msg"]="creating node_priorities index.";
		$queries[5]["query_string"]="CREATE INDEX ".$this->tbl_prefix."nodes_priority ON ".$this->tbl_prefix."nodes (priority);";
		$queries[6]["msg"]="creating properties table.";
		$queries[6]["query_string"]="
CREATE TABLE ".$this->tbl_prefix."properties (
	name varchar(21) DEFAULT '' NOT NULL PRIMARY KEY
)";

		$queries[7]["msg"]="creating seq_id table.";
		$queries[7]["query_string"]="
CREATE TABLE ".$this->tbl_prefix."seq_id (
	[path] varchar(127) DEFAULT '' NOT NULL PRIMARY KEY,
	[next_id] numeric(11) DEFAULT '0' NOT NULL
)";
		$queries[8]["msg"]="creating types table.";
		$queries[8]["query_string"]="
CREATE TABLE ".$this->tbl_prefix."types (
	[type] varchar(16) DEFAULT '' NOT NULL,
	[implements] varchar(16) DEFAULT '' NOT NULL
);";
		$queries[9]["msg"]="creating objects index.";
		$queries[9]["query_string"]="CREATE INDEX ".$this->tbl_prefix."types_type ON ".$this->tbl_prefix."types (type);";
		$queries[10]["msg"]="creating objects index.";
		$queries[10]["query_string"]="CREATE INDEX ".$this->tbl_prefix."types_implements ON ".$this->tbl_prefix."TYPES (implements);";

		while ((list($key, $query)=each($queries)) && (!$error)) {
			if ($query["msg"]) {
				echo $query["msg"]."\n";
			}
			$exec=mssql_query($query["query_string"]);
			$err=mssql_query("select @@ERROR as ErrorNum");
			$e = mssql_fetch_array($err);
			if ($e[0]) {
				$error=$e[0];
				error("MSSQL: $e[0]");
			}
		}

		if (!$error) {
			$return=true;
			// initialize locking tables
			$this->mod_lock->init($this->tbl_prefix);

			echo "MSSQL store initialized.\n\n";
		} else {
			$return=false;
		}
		return $return;
	}

	function create_property($property, $definition, $indexes="") {
	/**********************************************************************

		This function creates a new property type. This property can then be
	used by objects to set special information on which to quickly search
	using find.

	$name must be a string of at most 16 characters from the set [a-zA-Z0-9_] 
	or '-', starting with a letter (a-zA-Z).

	$definition describes which name value pairs this property contains and
	which type (and size) each value is.
	$definition is defined as: $definition[{name}][{type}]={size}
		{name} is defined like $name above
		(type} can be 'number', 'string', 'text' or 'boolean'
		{size} is only used for the string type and can not be more than 255. 
	$indexes describes which indexes the storage layer should consider
		for the property. Default behaviour is to create one index for the
		complete set of name-value pairs. If you want you can create a smaller
		index, or more than one index.
	$indexes is defined as: $indexes[][]={name} || $indexes="none"
		e.g. $indexes[0][0]="name1";
	 $indexes[1][0]="name2"
				 $indexes[1][1]="name3";
		this would create two indexes, one on "name1" and one on "name2" and
		"name3".
		{name} is defined like $name above. 
	if $indexes is set to "none", no user indexes will be created on this 
	property. This is usually not a good thing to do. 
	 
	**********************************************************************/
		$result=1;
		$this->error="";
		if (eregi("^[a-z][a-z0-9_-]*$",$property) && strlen($property)<=16) {
			$tablename=$this->tbl_prefix."prop_".AddSlashes($property);
			$create_string="create table ".AddSlashes($tablename)." (\n";
			while (list($name, $typedef)=each($definition)) {
				if (!eregi("^[a-z][a-z0-9_-]*$",$name) || strlen($name)>16) {
					$result=0;
					$this->error="Wrong format for type: $name";
					break;
				}	 
				$create_string.= " [AR_".$name."] ";
				$indexstring.="AR_$name,";
				while (list($type,$size)=each($typedef)) {
					switch($type) {
						case "string": 
							if ($size>0 && $size<256) {
								$create_string.="varchar(".$size.") DEFAULT '' not null,\n";
							} else {
								$result=0;
								$this->error="Wrong format for typedefinition $name: incorrect size."; 
							}
							break;
						case "number":
							$create_string.="numeric(11) DEFAULT 0 not null,\n";
							break;
						case "boolean":
							$create_string.="bool DEFAULT false not null,\n";
							break;
					}
				}
			}
			if ($result) {
				// now add the 'object' field.
				$create_string.="[object] numeric(11) not null);\n";
				$exec=mssql_query($create_string);

				// now add the correct indexes.
				if ($indexes=="none") {
					$indexstring="";
				} else {
					if ($indexes && is_array($indexes)) {
						$indexstring="";
						while ((list($key, $values)=each($indexes)) && $result) {
							$indexstring="CREATE INDEX ".$tablename."_id".$key." ON ".$tablename." (";
							$comma="";
							while (list($key2, $name)=each($values)) {
								if (eregi("^[a-z][a-z0-9_-]*$",$name) && strlen($name)<=16) {
									$indexstring.=$comma."AR_".$name;
								} else {
									$result=0;
									$this->error="Wrong format for index ".$key." in: ".$name;
									break;
								}
								$comma=",";
							}
							$indexstring.=");\n";
							$exec = mssql_query($indexstring);
						}
					} else {
						$indexstring="CREATE INDEX ".$tablename."_id0 ON $tablename(".substr($indexstring,0,-1).");\n";
						$exec=mssql_query($indexstring);
					}
				}
				if ($result) {
					// add the object index
					$create_string="CREATE INDEX ".$tablename."_object ON $tablename (object);\n";
					$exec=mssql_query($create_string);

					$err=mssql_query("select @@ERROR");
					$e = mssql_fetch_array($err);
					if (!$e[0]) {
						$query_string="insert into ".$this->tbl_prefix."properties values ( '".AddSlashes($property)."' )";
						$exec=mssql_query($query_string);
						$err=mssql_query("select @@ERROR");
						$e = mssql_fetch_array($err);
						if ($e[0]) {
							$this->error=$e[0];
							error("ERROR: MSSQL: ".$this->error);
						}
					} else {
						$this->error=$e[0];
						error("ERROR: MSSQL: ".$this->error);
					}
					//FIXME: check for succes first, how?
				}
			}
		} else {
			$result=0;
			$this->error="Wrong format for property name: $property";
		}
		debug("create_property: $create_string","store");
		return $result;
	}

	function remove_property($property) {
	/**********************************************************************

		This function removes the property with the given name. It does not
	check whether there are types left which use this property. It returns
	true when the named property is succesfully removed. This means it also
	returns true if the property didn't exist in the first place.
	Otherwise it will return false.

	**********************************************************************/

		$this->error="";
		$eproperty=AddSlashes($property);
		$remove_string="drop ".$this->tbl_prefix."table prop_$eproperty";
		debug($remove_string,"store");
		mssql_query($remove_string);
		$query_string="delete from ".$this->tbl_prefix."properties where name='$eproperty'";
		$exec=mssql_query($query_string);
		$err=mssql_query("select @@ERROR");
		$e = mssql_fetch_array($err);
		if ($e[0]) {
			$this->error=$e[0];
			error("ERROR: MSSQL: ".$this->error);
		}
		//FIXME: check for succes first, check whether table no longer exists.
		return 1;
	}
	
	function add_type($type, $implements) {
	/**********************************************************************
	
		This function does not actually create a type, it only serves to
	notify to the system that $type exists and that it implements the
	type or interface given in $implements.
	$type and $implements must be strings of at most 16 characters.

	**********************************************************************/

		$this->error="";
		if ($type && $implements && (strlen($type)<17) && (strlen($implements)<17)) {
			$etype=AddSlashes($type);
			$eimplements=AddSlashes($implements);
			$query_string="insert into ".$this->tbl_prefix."types values ('$etype','$eimplements')";
			debug($query_string,"store");
			mssql_query($query_string);
			$err=mssql_query("select @@ERROR");
			$e = mssql_fetch_array($err);
			if ($e[0]) {
				$this->error=$e[0];
				$result=0;
				error("ERROR: MSSQL: ".$this->error);
			} else {
				$result=1;
			}	
		} else {
			$this->error="Wrong format for type or implements";
		}
		return $result;
	}

	function del_type($type, $implements="") {
	/**********************************************************************

		This function notifies the system that either:
	1) A type no longer implements a certain type or interface, or
	2) a type no longer exists.

	**********************************************************************/

		$this->error="";
		$etype=AddSlashes($type);
		if (!$implements) {
			$query_string="delete from ".$this->tbl_prefix."types where type='$etype' or implements='$etype'";
		} else {
			$eimplements=AddSlashes($implements);
			$query_string="delete from ".$this->tbl_prefix."types where type='$etype' and implements='$etype'";
		}
		debug($query_string,"store");
		mssql_query($query_string);
		$err=mssql_query("select @@ERROR");
		$e = mssql_fetch_array($err);
		if ($e[0]) {
			$this->$error=$e[0];
			error("ERROR: MSSQL: ".$this->error);
			$result=0;
		} else {
			$result=1;
		}
		return $result;
	}

}

?>
