<?php
/******************************************************************************
  Mysql Store 1.0						Ariadne 2.0

  Copyright (C) 1998-2000  Muze 

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

  --------------------------------------------------------------------------

  This is an implementation of the store class for MySQL. The store class is
  an interface between Ariadne objects and a storage layer. It is used by all 
  Ariadne objects to call templates in other objects or to manipulate
  the location and contents of objects in the Ariadne system.

*******************************************************************************/


// general objectstore functions

class mysqlstore {

	var $connect_id;
	var $error;
	var $root;
	var $code;

	function mysqlstore($path, $config) {
	/**********************************************************************************
		
	 This is the constructor routine for the store object. It takes some configuration 
	 information as arguments and sets up the database connection.

	 $path is the root path of the running script under the document root of				
		the webserver.
	 $config contains some database configuration values: "host", "user",
		"password", "database" and the location of the class files for all the used
		types.

	 **********************************************************************************/
		debug("mysqlstore($path, [array])","store");
		if (!function_exists("mysql_pconnect")) {
			dl("mysql.so");
		}
		$this->error="";
		$this->connect_id=mysql_pconnect($config["host"], $config["user"], $config["password"]) or die ("Could not connect to MySQL");
		mysql_select_db($config["database"]) or die ("Could not access database '".$config["database"]."'. Please create this database manually.");
		$this->root=$path;
		$this->code=$config["code"];
		$this->files=$config["files"];
		$this->tbl_prefix=$config["prefix"];

		// necessary to avoid the 'mysql_select_db' bug, it will select
		// a database for all open connect_id's
		// so we have to supply the database name wheenever a query is run
		$this->database=$config["database"];

		/* Include module mysql_compiler */
		include_once($this->code."stores/modules/mysql_compiler.php");

		/* Instantiate module locking */
		include_once($this->code."modules/mod_lock/mysql.phtml");
		$this->mod_lock=new mysqllock($config["prefix"]);
		$this->mod_lock->select_db($config["database"], $this->connect_id);
		$this->mod_lock->lock_duration=$config["lock_duration"];
		$config["password"]="";
		debug("mysqlstore: end","all");
	}

	function call($template, $args, $objects) {
	/**********************************************************************************
	
	 This function takes a list of objects, the function to be called in each of those
	 objects and the arguments of that function as arguments. The list of objects is of
	 unspecified type and may be different in other implementations of the store 
	 interface.

	 The function will retrieve and instantiate each object in the object list and call
	 the objects call with $function and $args.

	 store->call is aware of the possibility of objects being called as a substore, 
	 meaning: If a requested object is not found in this store, it might be in a
	 different store which is linked into this one via a substore. Each object can in
	 principle double as a substore, as long as it declares the object->is_store 
	 variable as TRUE. So if the requested object is not found, the search functions 
	 (get, ls and find) will return the object with the longest matching path. It is up
	 to store->call to check wether this object is the one referenced and if not, 
	 wether it is a substore.
	 **********************************************************************************/ 

		debug("call($template, ".serialize($args).", [list])","store");
		$result = Array();
		$this->error="";
		$this->count=@mysql_num_rows($objects["list"]);
		while ($row=@mysql_fetch_array($objects["list"])) {
			$object=$this->newobject($row["path"], $row["parent"], $row["type"], unserialize($row["object"]), $row["id"], $row["lastchanged"], $row["vtype"], strlen($row["object"]), $row["priority"]);
			$result[]=$object->call($template, $args);
		}

		if (!$this->count) {
			debug("call: end: no objects found whatsoever.","all");
		} else {
			debug("call: end: $this->count objects found","all");
		}
		$this->total+=$this->count;
		return $result;
	}

	function count($objects) {
		return @mysql_num_rows($objects["list"]);
	}

	function info($objects) {
		debug("call($template, $args, [list])","store");
		while ($row=@mysql_fetch_array($objects["list"])) {
			unset($row["object"]);
			$result[]=$row;
		}
		return $result;
	}

	function newobject($path, $parent, $type, $data, $id=0, $lastchanged=0, $vtype="", $size=0, $priority=0) {
		debug("newobject($path, $parent, $type, [data], $id, $lastchanged, $vtype, $size, $priority)","all");
		include_once($this->code."objects/".$type.".phtml");
		$object=new $type;
		$object->init($this, $path, $data);
		$object->type=$type;
		$object->parent=$parent;
		$object->id=(int)$id;
		$object->lastchanged=(int)$lastchanged;
		$object->vtype=$vtype;
		$object->size=(int)$size;
		$object->priority=(int)$priority;
		return $object;
	}

	function get($path) {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store and will retrieve
	 all the necessary data and return this in the objectlist type needed for 
	 store->call(). If the requested path does not exist, it will retrieve the object
	 with the longest matching path.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("get($path)","store");
		$this->error="";
		$result["method"]="get";
		$result["path"]=$path;
		$epath=AddSlashes($path);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$query_string="select $nodes_tbl.path, $nodes_tbl.parent, $nodes_tbl.priority, $objects_tbl.id, $objects_tbl.type, $objects_tbl.object, UNIX_TIMESTAMP($objects_tbl.lastchanged) as lastchanged, $objects_tbl.vtype from $objects_tbl, $nodes_tbl where $objects_tbl.id=$nodes_tbl.object and $nodes_tbl.path='$epath'";
		$result["list"]=mysql_db_query($this->database,$query_string, $this->connect_id);
		debug("get: end","all");
		return $result;
	}

	function ls($path) {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store and will retrieve
	 all the objects and their data which have this object as their parent. It will 
	 then return this in the objectlist type needed for store->call(). If the requested
	 path does not exist, it will retrieve the object with the longest matching path.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("ls($path)","store");
		$this->error="";
		$epath=AddSlashes($path);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$query_string="select distinct($nodes_tbl.path), $nodes_tbl.parent, $nodes_tbl.priority, $objects_tbl.id, $objects_tbl.type, $objects_tbl.object, UNIX_TIMESTAMP($objects_tbl.lastchanged) as lastchanged, $objects_tbl.vtype from $objects_tbl, $nodes_tbl where $objects_tbl.id=$nodes_tbl.object and $nodes_tbl.parent='$epath' order by $nodes_tbl.priority DESC, $nodes_tbl.path";
		$result["method"]="ls";
		$result["path"]=$path;
		$result["list"]=mysql_db_query($this->database,$query_string, $this->connect_id);
		debug("ls: query=$query_string","all");
		debug("ls: end","all");
		return $result;
	}

	function parents($path, $top="/") {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store. It will return 
	 all objects with a path which is a substring of the given path. The resulsts are 
	 ordered by path (length), shortest paths first.
	 In effect all parents of an object in the tree are called, in order, starting at 
	 the root.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("parents($path)","store");
		$this->error="";
		$epath=AddSlashes($path);
		$etop=AddSlashes($top);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$query_string="select distinct($nodes_tbl.path), $nodes_tbl.parent, $nodes_tbl.priority, $objects_tbl.id, $objects_tbl.type, $objects_tbl.object, UNIX_TIMESTAMP($objects_tbl.lastchanged) as lastchanged, $objects_tbl.vtype from $objects_tbl, $nodes_tbl where $objects_tbl.id=$nodes_tbl.object and $nodes_tbl.path=substring('$epath',1,length(path)) and $nodes_tbl.path LIKE '$etop%' order by path";
		debug($query_string, "all");
		$result["method"]="parents";
		$result["path"]=$path;
		$result["list"]=mysql_db_query($this->database,$query_string, $this->connect_id);
		debug("parents: end","all");
		return $result;
	}

	function find($path, $criteria, $limit=100, $offset=0) {
	/**********************************************************************************

	 This function takes as arguments a path to an object in the store and some search
	 criteria. It will search for all matching objects under the given path. If the
	 given path is not in this store but in a substore it will not automatically search
	 that substore. 

	 $criteria is of the form 

	 $criteria ::= ({ $property_name => ({ $valuename => ({ $compare_function, $value }) }) }) 

	 e.g.: $criteria["status"]["value"][">"]="'published'";

	 $path should always start and end with a '/'.

	 **********************************************************************************/
		debug("find($path, [criteria], $limit, $offset)","store");
		if (!is_array($criteria) && ($criteria=trim($criteria))) {
			$criteria=" and $criteria ";

			$sqlcompiler=new mysql_compiler($this->tbl_prefix);
			$query_string=$sqlcompiler->compile("path ~= '$path%'$criteria", $limit, $offset);
			if ($sqlcompiler->error) {
				$this->error=$sqlcompiler->error;
			}
			unset($sql_compiler);

		} else {
			$this->error="";
			$count=0;
			$result["method"]="find";
			$result["path"]=$path;
			$result["criteria"]=$criteria;
			$epath=AddSlashes($path);

			$nodes_tbl=$this->tbl_prefix."nodes";
			$objects_tbl=$this->tbl_prefix."objects";
			$types_tbl=$this->tbl_prefix."types";

			while (list($property, $values)=@each($criteria)) {
				$eproperty=AddSlashes($property);
				if ($property!="object") {
					$from.=", ".$this->tbl_prefix."prop_$eproperty";
					$where.=" and (";
				}
				while (list($valuename, $compare)=each($values)) {
					while (list($function, $value)=each($compare)) {
						$ecompare=AddSlashes($function);
						$evaluename=AddSlashes($valuename);
						if ($value=="") { 
							// empty strings as value generate strange results in SQL land
							$value=0;
						}
						switch($property) {
							case "object" :
								switch($valuename) {
									case ("type") : 
										$where.=" and $objects_tbl.type $ecompare $value ";
									 	break;
									case ("implements") : 
										$types=", $types_tbl";
										$where.=" and ( $types_tbl.implements $ecompare $value and $objects_tbl.vtype=$types_tbl.type ) ";
										break;
									case ("parent") :
										$where.=" and $nodes_tbl.parent $ecompare $value ";
										break;
									case ("lastchanged") :
										$value = date("YmdHis", $value);
										$where.=" and $objects_tbl.lastchanged $ecompare $value ";
										break;
								}
								break;
							default :
								$where.=$this->tbl_prefix."prop_$eproperty.AR_$evaluename $ecompare $value and "; 
						}
					}
				}
				if ($property!="object") {
					$where.=" ".$this->tbl_prefix."prop_$eproperty.object=$objects_tbl.id)	";
				}
			}
			$query_string="select distinct($nodes_tbl.path), $nodes_tbl.parent, $nodes_tbl.priority, $objects_tbl.id, $objects_tbl.type, $objects_tbl.object, UNIX_TIMESTAMP($objects_tbl.lastchanged) as lastchanged, $objects_tbl.vtype from $nodes_tbl, $objects_tbl $from $types where $objects_tbl.id=$nodes_tbl.object and $nodes_tbl.path like '$epath%'";
			$where=substr($where,4);
			if ($where) { 
				$query_string.=" and ( ( $where ) )";
			} 
			$query_string.=" order by $nodes_tbl.parent, $nodes_tbl.priority DESC, $nodes_tbl.path";
			if ($limit) {
				$query_string.=" limit ";
				if ($offset) {
					$query_string.="$offset,";
				}
				$query_string.="$limit";
			}
		}
		debug("find: query=$query_string","all");
		$result["list"]=mysql_db_query($this->database,$query_string, $this->connect_id);
		if ($result["list"]) {
			debug("find: end (".mysql_num_rows($result["list"]).")","all");
		}
		return $result;
	}

	function close() {
		// This is the destructor function, nothing much to see :)
		debug("close()","store");
		if (is_array($this->filestores)) {
			while (list($key, $filestore)=each($this->filestores)) {
				$filestore->close();
			}
		}
		return @mysql_close($this->connect_id);
	}


	function save($path, $type, $data, $properties="", $vtype="", $priority=0) {
	/***************************************************************

		This function takes as argument a path, type, objectdata and 
		possibly a properties list and vtype (virtual type).
		If there exists no object with the given path, a new object is 
		saved with the given type, data, properties and vtype, and a
		new path is saved pointing to it.
		If there does exist an object with the given path, it's object
		data is overwritten with the given data and if vtype is set the
		current vtype is overwritten with the new one.
		
		$path must be an absolute path (containing no '..' and starting
			with '/')
		$type must be a valid type
		$data can be any string (usually a serialized object.)
		$properties is a multidimensional hash of the following form:
			$properties[{property_name}][][{value_name}]={value}
			{property_name} must be a valid property name
			{value_name} must be a valid value name for this property
			{value} can be a number, boolean or string. If it is a string
				it must be enclosed in single qoutes. All other single 
				quotes in the string must be escaped. e.g:
				"'\'t is a String'"
		example:
			$properties["name"][0]["value"]="'A name'";
			$properties["name"][1]["value"]="'A second name!'";
		if $properties["name"]=1 then all properties for property name
			will be removed.

		$vtype must be a valid type.
	 
		if $properties or $vtype are not set or empty ("",0 or false)
		they will be ignored. $vtype defaults to $type.
		Only those properties listed in $properties will be updated.
		Any other property set will remain as it was.

	***************************************************************/

		debug("save($path, $type, [data], [properties], $vtype, $priority)","store");

		$this->error="";
		if ($path!="/") {
			$parent=$this->make_path($path, "..");
		} else {
			$parent="..";
		}
		$eparent=AddSlashes($parent);
		if (ereg("^(.*)\{([0-9]):id\}(.*)",$path,$matches)) { 
			// if the last part of a path matches something like {2:id} this
			// part will automatically create a new number, unique in this directory, and fill it in.
			// before we proceed, we need to lock the 'nodes' and 'objects' table

			$query_string="lock tables ".$this->tbl_prefix."nodes write, ".$this->tbl_prefix."objects write";
			if (mysql_db_query($this->database, $query_string, $this->connect_id)) {
				$needunlocking = true;

				$subid = 0;
				$mask_pre = $matches[1];
				$substr_s = strlen($mask_pre)+1;
				$substr_l = $matches[2];
				$mask_post= $matches[3];
				$query_string = 
					"select max(substring(path, $substr_s, $substr_l)) as id
					from ".$this->tbl_prefix."nodes where 
					path regexp '^".$mask_pre."[0-9]\{".$substr_l."\}".$mask_post."'";

				$result = mysql_db_query($this->database, $query_string, $this->connect_id);
				if ($result) {
					$row = mysql_fetch_array($result);
					$subid  = intval($row["id"]);
				}
				$subid=$subid+1;
				$subid = str_pad((string)$subid, $substr_l-strlen($subid)+1, "0", STR_PAD_LEFT);

				$path=ereg_replace("\{[0-9]:id\}",strval($subid),$path);
				debug("save: new path: $path ($subid)","all");
			} else {
				error("PANIC: could not obtain write lock on nodes table!");
				$this->close();
				exit;
			}
		}

		$edata=AddSlashes(serialize($data));
		$epath=AddSlashes($path);
		$etype=AddSlashes($type);
		$epriority=(int)$priority;

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if ($id=$this->exists($path)) { //update
			debug("save: updating","all");
			if ($vtype) { // only change/save vtype if it is explicitly set
				$evtype=AddSlashes($vtype);
				$query_string="update $objects_tbl set object='$edata', vtype='$evtype' where id=$id"; 
			} else {
				$query_string="update $objects_tbl set object='$edata' where id=$id"; 
			}
			debug("save: query=$query_string","all");
			mysql_db_query($this->database,$query_string, $this->connect_id);
			$errno=mysql_errno($this->connect_id);
			if (!$errno) { // mysql_affected_rows doesn't always work
				debug("save: query=$query_string","all");
				$this->save_properties($properties, $id, $this); 
				$query_string="update $nodes_tbl set priority=$epriority where path='$epath'";
				mysql_db_query($this->database,$query_string, $this->connect_id);
				$errno=mysql_errno($this->connect_id);
				if (!$errno) {
					debug("save: query=$query_string","all");
					$result=$path;
				} else {
					$this->error="ERROR: Mysql: $errno: ".mysql_error($this->connect_id);
					debug("save: query=$query_string","store");
					debug("save: update object failed!","store");
					debug("save: ".$this->error,"store");
					$result=0;
				}
			} else {
				$this->error="ERROR: Mysql: $errno: ".mysql_error($this->connect_id);
				debug("save: query=$query_string","store");
				debug("save: update object failed!","store");
				debug("save: ".$this->error,"store");
				$result=0;
			}
		} else { // insert new
			debug("save: new","all");
			if ($vtype=="") { // if vtype is not set, it defaults to type for new objects
				$vtype=$type; 
			}
			$evtype=AddSlashes($vtype);
			$query_string="insert into $objects_tbl (id,type,object,vtype) values (0,'$etype','$edata','$evtype')";
			debug("save: query=$query_string","all");
			$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
			$errno=mysql_errno($this->connect_id);
			$error=mysql_error($this->connect_id);
			if (!$errno && $id=mysql_insert_id($this->connect_id)) {
				$query_string="insert into $nodes_tbl (path,parent,object,priority) values ('$epath','$eparent',$id,$epriority)";
				debug("save: query=$query_string","all");
				$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
				$errno=mysql_errno($this->connect_id);
				$error=mysql_error($this->connect_id);
				if (!$errno) {				
					$this->save_properties($properties, $id, $this);
					$result=$path;
				} else {
					$this->error="ERROR: Mysql: $errno: $error";
					debug("save: insert node failed!","store");
					debug("save: ".$this->error,"store");
					$result=0;
				}
			} else {
				$this->error="ERROR: Mysql: $errno: $error";
				debug("save: insert object failed!","store");
				debug("save: ".$this->error,"store");
				$result=0;
			}			
		}
		if ($needunlocking) {
			$query_string = "unlock tables";
			mysql_db_query($this->database,$query_string, $this->connect_id);
		}
		debug("save: end","all");
		return $result;
	}


	function purge($path) {
	/**********************************************************************
	 
		This function will delete the object pointed to by $path and all
	other paths pointing to that object. It will then remove any property
	for this object from all property tables.
		The function returns the number of paths found and removed or 1 if
	there was no path found (meaning that the object doesn't exist and 
	therefor purge succeeded while doing nothing.)

	 $path should always start and end with a '/'.

	**********************************************************************/

		debug("purge($path)","store");
		$this->error="";

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";
		$nextid_tbl=$this->tbl_prefix."seq_id";

		$object=$this->exists($path);
		if ($object) {
			$query_string="delete from $nodes_tbl where object=$object";
			$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
			if ($temp) {
				$result=mysql_affected_rows($this->connect_id);
			}
			$this->del_property($object);
			$query_string="delete from $objects_tbl where id=$object";
			mysql_db_query($this->database,$query_string, $this->connect_id);
			$paths=$this->list_paths($path);
			if (is_array($paths)) {
				while (list($key, $path)=each($paths)) {
					$epath=AddSlashes($path);
					$query_string="delete from $nextid_tbl where path='$epath'";
					$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
				}
			}
		} else { // no such path, so purge already succeeded :)
			$result=1;
		}
		debug("purge: end","all");
		return $result;
	}

	function delete($path) {
	/**********************************************************************

		This function deletes the path given. If this is the last path pointing
	to an object, the object will be purged instead.

	$path should always start and end with a '/'.

	**********************************************************************/

		debug("delete($path)","store");
		$this->error="";
		$epath=AddSlashes($path);
		$paths=$this->list_paths($path);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";
		$nextid_tbl=$this->tbl_prefix."seq_id";


		if (is_array($paths)) {
			if (sizeof($paths)==1) { // only one path for this object
				$result=$this->purge($path); // therefore purge the object.
			} else { // only delete the given path
				$query_string="delete from $nodes_tbl where path='$epath'";
				$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
				if (mysql_affected_rows($this->connect_id)) {
					$result=1;
				} else {
					$result=0;
				}
				$query_string="delete from $nextid_tbl where path='$epath'";
				$temp=mysql_db_query($this->database,$query_string, $this->connect_id);

			}
		}
		debug("delete: end","all");
		return $result;
	}

	function exists($path) {
	/**********************************************************************

		This function checks the given path to see if it exists. If it does
	it returns the id of the object to which it points. Otherwise it returns
	0.

	$path should always start and end with a '/'.

	**********************************************************************/

		debug("exists($path)","store");
		$this->error="";
		$epath=AddSlashes($path);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$query_string="select object from $nodes_tbl where path='$epath'";
		$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
		if ($temp && ($row=mysql_fetch_array($temp))) {
			$object=intval($row["object"]);
			debug("exists: end (yes)","all");
		} else {
			debug("exists: end (no)","all");
		}
		return $object;
	}


	function link($source, $destination) {
	/**********************************************************************

		Link adds an extra path to an already existing object. It has two
	arguments: $source and $destination. $source is an existing path of
	an object, $destination is the new path. $destination must not already
	exist.

	$destination should always start and end with a '/'.

	**********************************************************************/

		debug("link($source,$destination)","store");
		$this->error="";
		$edestination=AddSlashes($destination);
		$esource=AddSlashes($source); 
		$parent=$this->make_path($destination, "..");
		$eparent=AddSlashes($parent);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if ($this->exists($destination)) {
			$this->error="$destination already exists, cannot overwrite.";
			debug("link: ERROR: ".$this->error,"store");
			$result=false;
		} else if (!$this->exists($parent)) {
			$this->error="$parent does not exist, cannot link.";
			debug("link: ERROR: ".$this->error,"store");
			$result=false;
		} else { 
			if (ereg("(.*)\{([0-9]):id\}(.*)",$destination,$matches)) {
				$query_string="lock tables ".$this->tbl_prefix."nodes write";
				if (mysql_db_query($this->database, $query_string, $this->connect_id)) {
					$needunlocking = true;
					$subid = 0;

					$mask_pre = $matches[1];
					$substr_s = strlen($mask_pre)+1;
					$substr_l = $matches[2];
					$mask_post= $matches[3];
					$query_string = 
						"select max(substring(path, $substr_s, $substr_l)) as id
						from ".$this->tbl_prefix."nodes where 
						path regexp '^".$mask_pre."[0-9]\{".$substr_l."\}".$mask_post."'";

					$result = mysql_db_query($this->database, $query_string, $this->connect_id);
					if ($result) {
						$row = mysql_fetch_array($result);
						$subid  = intval($row["id"]);
					}
					$subid=$subid+1;
					$subid = str_pad((string)$subid, $substr_l-strlen($subid)+1, "0", STR_PAD_LEFT);

					$destination=ereg_replace("\{[0-9]:id\}",strval($subid),$destination);
					$edestination=AddSlashes($destination);
					debug("link: new destination: $destination ($subid)","all");
				} else {
					error("PANIC: could not obtain write lock on nodes table!");
					$this->close();
					exit;
				}
			}
			$id=$this->exists($source);
			if ($id) {
				$query_string="insert into $nodes_tbl (path, parent, object ) values ('$edestination', '$eparent', $id)";
				$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
				$errno=mysql_errno($this->connect_id);
				$error=mysql_error($this->connect_id);
				if ($errno) {				
					$this->error="ERROR: Mysql: $errno: $error";
					debug("link: insert node failed!","store");
					debug("link: ".$this->error,"store");
					debug("link: query=$query_string","store");
					$result=false;
				}
				debug("link: end","all");
				$result=$destination;
			} else {
				$result=false;
				debug("link: end (no $source)","store");
			}
		}
		if ($needunlocking) {
			$query_string = "unlock tables";
			mysql_db_query($this->database,$query_string, $this->connect_id);
		}
		return $result;
	}

	function store_run_query($query) {
		/* private function, do not use this outside this class */
		$result=mysql_db_query($this->database, $query, $this->connect_id);
		$errno=mysql_errno($this->connect_id);
		$error=mysql_error($this->connect_id);
		if ($errno) {				
			$this->error="ERROR: Mysql: $errno: $error";
			debug("run_query: ".$this->error,"store");
			debug("run_query: query=$query_string","store");
			$result=false;
		}
		return $result;
	}

	function move($source, $destination) {
	/**********************************************************************

	$destination should always start and end with a '/'.

	**********************************************************************/

		debug("move($source,$destination)","store");
		$this->error="";
		$edestination=AddSlashes($destination);
		$esource=AddSlashes($source); 
		$parent=$this->make_path($destination, "..");
		$eparent=AddSlashes($parent);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if ($this->exists($destination)) {
			$this->error="$destination already exists, cannot overwrite.";
			debug("move: ERROR: ".$this->error,"store");
			$result=false;
		} else if (!$this->exists($parent)) {
			$this->error="$parent does not exist, cannot move.";
			debug("move: ERROR: ".$this->error,"store");
			$result=false;
		} else { 
			if (ereg("(.*)\{([0-9]):id\}(.*)",$destination,$matches)) {
				$query_string="lock tables ".$this->tbl_prefix."nodes write";
				if (mysql_db_query($this->database, $query_string, $this->connect_id)) {
					$subid = 0;

					$mask_pre = $matches[1];
					$substr_s = strlen($mask_pre)+1;
					$substr_l = $matches[2];
					$mask_post= $matches[3];
					$query_string = 
						"select max(substring(path, $substr_s, $substr_l)) as id
						from ".$this->tbl_prefix."nodes where 
						path regexp '^".$mask_pre."[0-9]\{".$substr_l."\}".$mask_post."'";

					$result = mysql_db_query($this->database, $query_string, $this->connect_id);
					if ($result) {
						$row = mysql_fetch_array($result);
						$subid  = intval($row["id"]);
					}
					$subid=$subid+1;
					$subid = str_pad((string)$subid, $substr_l-strlen($subid)+1, "0", STR_PAD_LEFT);

					$destination=ereg_replace("\{[0-9]:id\}",strval($subid),$destination);
					$edestination=AddSlashes($destination);
					debug("move: new destination: $destination ($subid)","all");
				} else {
					error("PANIC: could not obtain write lock on nodes table!");
					$this->close();
					exit;
				}
			}
			$id=$this->exists($source);
			if ($id) {
				$destinationlength=strlen($destination);
				$sourcelength=strlen($source);
				$parentlength=strlen($parent);
				// move the top path
				$query_string="update $nodes_tbl set path='$edestination', parent='$eparent' where path='$esource'";
				if ($result=$this->store_run_query($query_string)) {
					// move the nextid path too
					$query_string="update ".$this->tbl_prefix."seq_id set path='$edestination' where path='$esource'";
					if ($result=$this->store_run_query($query_string)) {
						// now move all the children
						$query_string="update $nodes_tbl set path=CONCAT('$edestination', SUBSTRING(path, $sourcelength+1)), parent=CONCAT('$edestination', SUBSTRING(parent, $sourcelength+1)) where path like '$esource%'";
						if ($result=$this->store_run_query($query_string)) {
							// finally move the nextid's for the children
							$query_string="update ".$this->tbl_prefix."seq_id set path=CONCAT('$edestination', SUBSTRING(path, $sourcelength+1)) where path like '$esource%'";
							$result=$this->store_run_query($query_string);	
						}
					}
				}
				debug("move: end","all");
			} else {
				$result=false;
				debug("move: end (no $source)","store");
			}
		}

		if ($needunlocking) {
			$query_string = "unlock tables";
			mysql_db_query($this->database,$query_string, $this->connect_id);
		}

		if ($result) {
			return $destination;
		} else {
			return false;
		}
	}


	function list_paths($path) {
	/**********************************************************************

		This function returns an array of all paths pointing to the same object 
	as $path does.

	**********************************************************************/

		debug("list_paths($path)","store");
		$this->error="";

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$object=$this->exists($path);
		$query_string="select path from $nodes_tbl where object=$object";
		$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
		while ($row=@mysql_fetch_array($temp)) {
			$result[]=$row["path"];
		}
		debug("list_paths: end","all");
		return $result;
	}

	function implements($type, $implements) {
	/**********************************************************************

		This function returns 1 if the $type implements the type or
	interface in $implements. Otherwise it returns 0.

	**********************************************************************/

		debug("implements($implements)","store");

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$query_string="select distinct type from $types_tbl where implements='".AddSlashes($implements)."' and type='".AddSlashes($type)."'";
		$this->error="";
		$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
		if ($temp) {
			$row=mysql_fetch_array($temp);
		}
		if ($row) {
			$result=1;
		}
		debug("implements: end ($result)","all");
		return $result;
	}
	
	function make_path($curr_dir, $path) {
	/**********************************************************************
 
		This function creates an absolute path from the given starting path
	($curr_dir) and a relative (or absolute) path ($path). If $path starts
	with a '/' $curr_dir is ignored. 
	$path must be a string of substrings seperated by '/'. each of these 
	substrings may consist of charachters and/or numbers. If a substring
	is "..", it and the previuos substring will be removed. If a substring
	is "." or "", it is removed. All other substrings are then concatenated
	with a '/' between them and at the start and the end. This string is 
	then returned.

	**********************************************************************/

		debug("make_path($curr_dir, $path)","all");		
		$this->error="";
		if (substr($path,0,1)=="/") {
			$result="/";
			$path=substr($path, 1);
		} else {
			$result=$curr_dir;
		}
		if (substr($path,-1)=="/") {
			$path=substr($path, 0, -1);
		}
		if ($path) {
			$splitpath=explode("/", $path);

			while (list($key, $pathticle)=each($splitpath)) {
				switch($pathticle) {
					case ".." : $result=substr($result, 0, strrpos(substr($result,0,-1), "/")+1);
								break;
					case "." : break;
					case ""	 : break;
					default	 : $result=$result.$pathticle."/";
				}
			}
		}
		debug("make_path: end ($result)","all");		
		return $result;
	}

	function save_properties($properties, $id) {
	/********************************************************************

		'private' function of mysql.phtml. It updates all property tables
		defined in $properties and sets the values to the values in
		$properties.

	********************************************************************/

		debug("save_properties([properties], $id)","all");
		if ($properties && (is_array($properties)) && (is_int($id))) {
			while (list($property, $property_set)=each($properties)) {
				$this->del_property($id, $property);
				if (is_array($property_set)) {
					while (list($key, $values)=each($property_set)) {
						$this->add_property($id, $property, $values);
					}
				}
			}
		}
		debug("save_properties: end","all");
	}


	function load_properties($object) {
		debug("load_properties($object)","all");
		if ($object) {
			$query_string="select name from ".$this->tbl_prefix."properties";
			$query=@mysql_db_query($this->database,$query_string,$this->connect_id);
			while ($prop=@mysql_fetch_array($query)) {
				if ($value=$this->load_property($object,$prop["name"])) {
					$result[$prop["name"]]=$value;
				}
			}
		}
		debug("load_properties: end","all");
		return $result;
	}

	function load_property($object, $property) {
		debug("load_property($object, $property)","all");

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if ($object) {
			$query_string="select * from ".$this->tbl_prefix."prop_".AddSlashes($property)." where object=$object";
			$query=@mysql_db_query($this->database,$query_string,$this->connect_id);
			$currProp=0;
			while ($prop=@mysql_fetch_array($query)) {
				reset($prop);
				while (is_array($prop) && (list($name,$val)=each($prop)) ) {
					if (($name!="object")&&(!is_int($name))) {
						if (is_string($val)) {
							$result[$currProp][substr($name,3)]="'".AddSlashes($val)."'";
						} else {
							$result[$currProp][substr($name,3)]=$val;
						}
					}
				}
				$currProp++;
			}
		}
		debug("load_property: end","all");
		return $result;
	}

	function add_property($object, $property, $values) {
		debug("add_property($object, $property, ".serialize($values)." )","all");

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if ($object) {
			while (list($name, $value)=each($values)) {
				if ($value!="") {
					$query_names.="AR_".AddSlashes($name).", ";
					$query_values.="$value, ";
				}
			}
			$query_string="insert into ".$this->tbl_prefix."prop_".AddSlashes($property)." ( ".
										$query_names."object ) values ( ".$query_values."$object )";
			debug($query_string, "all");
			mysql_db_query($this->database,$query_string, $this->connect_id);
			$result=mysql_affected_rows($this->connect_id);
		}
		debug("add_property: end","all");
		return $result;
	}

	function del_property($object, $property="", $values="") {
		debug("del_property($object, $property, [values])","all");

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		if (intval($object)) {
			if (!$property) { // remove all properties for $object
				$query_string="select name from properties";
				$temp=mysql_db_query($this->database,$query_string, $this->connect_id);
				while ($row=@mysql_fetch_array($temp)) {
					$query_string="delete from ".$this->tbl_prefix."prop_".$row["name"]." where object=$object";
					mysql_db_query($this->database,$query_string, $this->connect_id);
					$result+=mysql_affected_rows($this->connect_id);
				}
			} else {
				$query_string="delete from ".$this->tbl_prefix."prop_".AddSlashes($property)." where ";
				if (is_array($values)) {
					while (list($name, $value)=each($values)) {
						$query_string.="AR_".AddSlashes($name)."=$value and ";
					}
				}
				$query_string.="object=$object";
				mysql_db_query($this->database,$query_string, $this->connect_id);
				$result=mysql_affected_rows($this->connect_id);
			}
		}
		debug("del_property: end","all");
		return $result;
	}

	function set_nextid($path, $newid) {
	/**********************************************************************

		'private' function of mysql store. 
		(deprecated, but still available for backward compatibility).

	**********************************************************************/
		return $newid;
	}


	function get_nextid($path, $mask="{5:id}") {
	/**********************************************************************

		'private' function of mysql store. Used for import/exporting nextid
		information.

	**********************************************************************/

		$epath=AddSlashes($path);
		$path=AddSlashes($path);

		$nodes_tbl=$this->tbl_prefix."nodes";
		$objects_tbl=$this->tbl_prefix."objects";
		$types_tbl=$this->tbl_prefix."types";

		$substr_s = strlen($path)+1;
		if (ereg('^(.*)\{([0-9]):id\}(.*)$', $mask, $matches)) {

			$id = 0;

			$mask_pre = $matches[1];
			$substr_s+= strlen($mask_pre);
			$substr_l = $matches[2];
			$mask_post= $matches[3];
			$query_string = 
				"select max(substring(path, $substr_s, $substr_l)) as id
				from ".$this->tbl_prefix."nodes where 
				path regexp '^".$path.$mask_pre."[0-9]\{".$substr_l."\}".$mask_post."'";

			$result = mysql_db_query($this->database, $query_string, $this->connect_id);
			if ($result) {
				$row = mysql_fetch_array($result);
				$id  = intval($row["id"]);
			}
			$id++;
			$id = str_pad((string)$id, $substr_l-strlen($id)+1, "0", STR_PAD_LEFT);
		}
		return $id;
	}


	function get_filestore($name) {
		require_once($this->code."modules/mod_filestore.phtml");
		if (!$this->filestores[$name]) {
			$this->filestores[$name]=new filestore($name, $this->files);
		}
		return $this->filestores[$name];
	}


} // end class store

?>