<?php
/******************************************************************************
  Abstract Store 1.0						Ariadne 2.0

  Copyright (C) 1998,1999  Muze 

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*******************************************************************************/

// debugging functions.

$DB["all"]=5;
$DB["store"]=4;
$DB["class"]=3;
$DB["object"]=2;
$DB["pinp"]=1;
$DB["off"]=0;
$DB["level"]=$DB["off"];

function debug($text, $level="pinp") {
	global $DB;
	if ($DB["level"]>=$DB[$level]) {
		echo "<b>$level::$text</b><BR>\n";
		flush();
	}
}

function debugon($level="pinp") {
	global $DB;
	$DB["level"]=$DB[$level];
	debug("Debuglevel: $level");
}

function debugoff() {
	global $DB;
	debug("Debugging off.");
	$DB["level"]=$DB["off"];
}

function error($text) {
	echo "// <b>Error: $text</b><BR>\n<!--\nalert('Error: $text');\n// -->\n";
}

// general objectstore functions

class store {

	var $error;
	var $root;
	var $code;


	function store($path, $config) {
	/**********************************************************************************
		
	 This is the constructor routine for the store object. It takes some configuration 
	 information as arguments and sets up the database connection.

	 $path is the root path of the running script under the document root of				
		the webserver.
	 $config contains some database configuration values: "host", "user",
		"password", "database" and the location of the class files for all the used
		types.

	 **********************************************************************************/
		debug("store($path, [array])","store");
		$this->error="";
		$this->root=$path;
		$this->code=$config["code"];
		// include database initialization here
		debug("store: end","all");
	}

	function call($template, $args, $objects) {
	/**********************************************************************************
	
	 This function takes a list of objects, the function to be called in each of those
	 objects and the arguments of that function as arguments. The list of objects is of
	 unspecified type and may be different in other implementations of the store 
	 interface.

	 The function will retrieve and instantiate each object in the object list and call
	 the objects call with $function and $args.

	 store->call is aware of the possibility of objects being called as a substore, 
	 meaning: If a requested object is not found in this store, it might be in a
	 different store which is linked into this one via a substore. Each object can in
	 principle double as a substore, as long as it declares the object->is_store 
	 variable as TRUE. So if the requested object is not found, the search functions 
	 (get, ls and find) will return the object with the longest matching path. It is up
	 to store->call to check wether this object is the one referenced and if not, 
	 wether it is a substore.
	 **********************************************************************************/ 

		debug("call($template, $args, [list])","store");
		// get the object data 
		return $result;
	}

	function newobject($path, $parent, $type, $data, $id=0, $lastchanged=0, $vtype="") {
		debug("newobject($path, $parent, $type, [data], $id, $lastchanged, $vtype)","all");
		include_once($this->code."objects/".$type.".phtml");
		$object=new $type;
		$object->init($this, $path, $data);
		$object->type=$type;
		$object->parent=$parent;
		$object->id=$id; 
		$object->lastchanged=$lastchanged;
		return $object;
	}

	function get($path) {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store and will retrieve
	 all the necessary data and return this in the objectlist type needed for 
	 store->call(). If the requested path does not exist, it will retrieve the object
	 with the longest matching path.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("get($path)","store");
		$this->error="";
		$result["method"]="get";
		$result["path"]=$path;
		// get an object and put a pointer to it in $result["list"]
		$result["list"]=0;
		debug("get: end","all");
		return $result;
	}

	function ls($path) {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store and will retrieve
	 all the objects and their data which have this object as their parent. It will 
	 then return this in the objectlist type needed for store->call(). If the requested
	 path does not exist, it will retrieve the object with the longest matching path.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("ls($path)","store");
		$this->error="";
		$epath=AddSlashes(strtoupper($path));
		$result["method"]="ls";
		$result["path"]=$path;
		// get a list of objects and put a pointer to it in $result["list"]
		$result["list"]=0;
		debug("ls: end","all");
		return $result;
	}

	function parents($path) {
	/**********************************************************************************

	 This function takes as argument a path to an object in the store. It will return 
	 all objects with a path which is a substring of the given path. The resulsts are 
	 ordered by path (length), shortest paths first.
	 In effect all parents of an object in the tree are called, in order, starting at 
	 the root.

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("parents($path)","store");
		$this->error="";
		$epath=AddSlashes(strtoupper($path));
		$result["method"]="parents";
		$result["path"]=$path;
		// get a list of objects and put a pointer to it in $result["list"]
		$result["list"]=0;
		debug("parents: end","all");
		return $result;
	}

	function find($path, $criteria, $limit=100, $offset=0) {
	/**********************************************************************************

	 This function takes as arguments a path to an object in the store and some search
	 criteria. It will search for all matching objects under the given path. If the
	 given path is not in this store but in a substore it will not automatically search
	 that substore. 

	 $criteria is of the form 

	 $criteria ::= ({ $property_name => ({ $valuename => ({ $compare_function, $value }) }) }) 

	 e.g.: $criteria["status"]["value"][">"]="'published'";

	 $path should always start and end with a '/'.

	 **********************************************************************************/

		debug("find($path, [array], $limit, $offset)","store");
		$this->error="";
		$count=0;
		$result["method"]="find";
		$result["path"]=$path;
		$result["criteria"]=$criteria;
		$epath=AddSlashes(strtoupper($path));
		while (list($property, $values)=@each($criteria)) {
			$eproperty=AddSlashes($property);
			while (list($valuename, $compare)=each($values)) {
				while (list($function, $value)=each($compare)) {
					$ecompare=AddSlashes($function);
					$evaluename=AddSlashes($valuename);
					if ($value=="") { 
						// empty strings as value generate strange results in SQL land
						$value=0;
					}
					switch($property) {
						case "object" :
							switch($valuename) {
								case ("type") : 
								 	break;
								case ("implements") : 
									break;
								case ("parent") :
									break;
								case ("lastchanged") :
									break;
							}
							break;
						default :
					}
				}
			}
		}
		// get the list of objects fullfilling the criteria and put a pointer to it in $result["list"]
		$result["list"]=0;

		debug("find: end","all");
		return $result;
	}

	function close() {
		// This is the destructor function, nothing much to see :)
		debug("close()","store");
		return true;
	}


	function save($path, $type, $data, $properties="", $vtype="") {
	/***************************************************************

		This function takes as argument a path, type, objectdata and 
		possibly a properties list and vtype (virtual type).
		If there exists no object with the given path, a new object is 
		saved with the given type, data, properties and vtype, and a
		new path is saved pointing to it.
		If there does exist an object with the given path, it's object
		data is overwritten with the given data and if vtype is set the
		current vtype is overwritten with the new one.
		
		$path must be an absolute path (containing no '..' and starting
			with '/')
		$type must be a valid type
		$data can be any string (usually a serialized object.)
		$properties is a multidimensional hash of the following form:
			$properties[{property_name}][][{value_name}]={value}
			{property_name} must be a valid property name
			{value_name} must be a valid value name for this property
			{value} can be a number, boolean or string. If it is a string
				it must be enclosed in single qoutes. All other single 
				quotes in the string must be escaped. e.g:
				"'\'t is a String'"
		example:
			$properties["name"][0]["value"]="'A name'";
			$properties["name"][1]["value"]="'A second name!'";
		if $properties["name"]=1 then all properties for property name
			will be removed.

		$vtype must be a valid type.
	 
		if $properties or $vtype are not set or empty ("",0 or false)
		they will be ignored. $vtype defaults to $type.
		Only those properties listed in $properties will be updated.
		Any other property set will remain as it was.

	***************************************************************/

		debug("save($path, $type, [data], [properties], $vtype)","store");
		$this->error="";
		if ($path!="/") {
			$parent=$this->make_path($path, "..");
		} else {
			$parent="..";
		}
		$epath=AddSlashes($path);
		$eparent=AddSlashes($parent);
		if (ereg("{([0-9]):id}",$path,$match)) { 
			// if the last part of a path matches something like {2:id} this
			// part will automatically create a new number, unique in this directory, and fill it in.
			$subid=$this->nextid($parent);
			if ($match[1]) { 
				$subid=substr("000000000".$subid,-(intval($match[1])));
			}
			$path=ereg_replace("{[0-9]:id}",strval($subid),$path);
			debug("save: new path: $path ($subid)","all");
		}
		$edata=AddSlashes(serialize($data));
		$epath=AddSlashes($path);
		$etype=AddSlashes($type);
		if ($id=$this->exists($path)) { //update
			debug("save: updating","all");
			if ($vtype) { // only change/save vtype if it is explicitly set
				$evtype=AddSlashes($vtype);
			}
		} else { // insert new
			debug("save: new","all");
			if ($vtype=="") { // if vtype is not set, it defaults to type for new objects
				$vtype=$type; 
			}
			$evtype=AddSlashes($vtype);
		}
		debug("save: end","all");
		return $result;
	}


	function purge($path) {
	/**********************************************************************
	 
		This function will delete the object pointed to by $path and all
	other paths pointing to that object. It will then remove any property
	for this object from all property tables.
		The function returns the number of paths found and removed or 1 if
	there was no path found (meaning that the object doesn't exist and 
	therefor purge succeeded while doing nothing.)

	 $path should always start and end with a '/'.

	**********************************************************************/

		debug("purge($path)","store");
		$this->error="";
		$epath=AddSlashes($path);
		$object=$this->exists($path);
		if ($object) {
			// remove object
		} else { // no such path, so purge already succeeded :)
			$result=1;
		}
		debug("purge: end","all");
		return $result;
	}

	function delete($path) {
	/**********************************************************************

		This function deletes the path given. If this is the last path pointing
	to an object, the object will be purged instead.

	$path should always start and end with a '/'.

	**********************************************************************/

		debug("delete($path)","store");
		$this->error="";
		$epath=AddSlashes($path);
		$paths=$this->list_paths($path);
		if ($paths) {
			if (sizeof($paths)==1) { // only one path for this object
				$result=$this->purge($path); // therefore purge the object.
			} else { // only delete the given path
			}
		}
		debug("delete: end","all");
		return $result;
	}

	function exists($path) {
	/**********************************************************************

		This function checks the given path to see if it exists. If it does
	it returns the id of the object to which it points. Otherwise it returns
	0.

	$path should always start and end with a '/'.

	**********************************************************************/

		debug("exists($path)","store");
		$this->error="";
		$epath=AddSlashes(strtoupper($path));
		// check for $path
		return $object;
	}


	function link($source, $destination) {
	/**********************************************************************

		Link adds an extra path to an already existing object. It has two
	arguments: $source and $destination. $source is an existing path of
	an object, $destination is the new path. $destination must not already
	exist.

	$destination should always start and end with a '/'.

	**********************************************************************/

		debug("link($source,$destination)","store");
		$this->error="";
		$edestination=AddSlashes($destination);
		$esource=AddSlashes($source); 
		$parent=$this->make_path($destination, "..");
		$eparent=AddSlashes($parent);
		if ($this->exists($destination)) {
			$this->error="$destination already exists, cannot overwrite.";
			debug("link: ERROR: ".$this->error,"store");
			$result=0;
		} else { 
			if (ereg("{([0-9]):id}",$destination,$match)) {
				$subid=$this->nextid($parent);
				if ($match[1]) {
					$subid=substr("000000000".$subid,-(intval($match[1])));
				}
				$destination=ereg_replace("{[0-9]:id}",strval($subid),$destination);
				$edestination=AddSlashes($destination);
				debug("link: new destination: $destination ($subid)","all");
			}
			$id=$this->exists($source);
			if ($id) {
				debug("link: end","all");
				$result=$destination;
			}
		}
		debug("link: end (no $source)","store");
		return $result;
	}

	function list_paths($path) {
	/**********************************************************************

		This function returns an array of all paths pointing to the same object 
	as $path does.

	**********************************************************************/

		debug("list_paths($path)","store");
		$this->error="";
		$object=$this->exists($path);
		debug("list_paths: end","all");
		return $result;
	}

	function implements($type, $implements) {
	/**********************************************************************

		This function returns 1 if the $type implements the type or
	interface in $implements. Otherwise it returns 0.

	**********************************************************************/

		debug("implements($implements)","store");
		debug("implements: end ($result)","all");
		return $result;
	}
	
	function make_path($curr_dir, $path) {
	/**********************************************************************
 
		This function creates an absolute path from the given starting path
	($curr_dir) and a relative (or absolute) path ($path). If $path starts
	with a '/' $curr_dir is ignored. 
	$path must be a string of substrings seperated by '/'. each of these 
	substrings may consist of charachters and/or numbers. If a substring
	is "..", it and the previuos substring will be removed. If a substring
	is "." or "", it is removed. All other substrings are then concatenated
	with a '/' between them and at the start and the end. This string is 
	then returned.

	**********************************************************************/

		debug("make_path($curr_dir, $path)","all");		
		$this->error="";
		if (substr($path,0,1)=="/") {
			$result="/";
			$path=substr($path, 1);
		} else {
			$result=$curr_dir;
		}
		if (substr($path,-1)=="/") {
			$path=substr($path, 0, -1);
		}
		if ($path) {
			$splitpath=split("/", $path);

			while (list($key, $pathticle)=each($splitpath)) {
				switch($pathticle) {
					case ".." : $result=substr($result, 0, strrpos(substr($result,0,-1), "/")+1);
								break;
					case "." : break;
					case ""	 : break;
					default	 : $result=$result.$pathticle."/";
				}
			}
		}
		debug("make_path: end ($result)","all");		
		return $result;
	}

	function save_properties($properties, $id) {
	/********************************************************************

		'private' function of mysql.phtml. It updates all property tables
		defined in $properties and sets the values to the values in
		$properties.

	********************************************************************/

		debug("save_properties([properties], $id)","all");
		if ($properties && (is_array($properties)) && (is_int($id))) {
			while (list($property, $property_set)=each($properties)) {
				$this->del_property($id, $property);
				if (is_array($property_set)) {
					while (list($key, $values)=each($property_set)) {
						$this->add_property($id, $property, $values);
					}
				}
			}
		}
		debug("save_properties: end","all");
	}


	function load_properties($object) {
		debug("load_properties($object)","all");
		if ($object) {
		}
		debug("load_properties: end","all");
		return $result;
	}

	function load_property($object, $property) {
		debug("load_property($object, $property)","all");
		if ($object) {
		}
		debug("load_property: end","all");
		return $result;
	}

	function add_property($object, $property, $values) {
		debug("add_property($object, $property, [values])","all");
		if ($object) {
			while (list($name, $value)=each($values)) {
				if ($value!="") {

				}
			}

		}
		debug("add_property: end","all");
		return $result;
	}

	function del_property($object, $property="", $values="") {
		debug("del_property($object, $property, [values])","all");
		if (intval($object)) {
			if (!$property) { // remove all properties for $object
			} else {
			}
		}
		debug("del_property: end","all");
		return $result;
	}

	function nextid($path) {
	/**********************************************************************

		'private' function of mysql store. Used by link and save.
		This function calculates and returns the next unused id (number) for 
	the given path. 

	**********************************************************************/

		$path=AddSlashes($path);
		return $id;
	}

} // end class store

?>