<?php
	/******************************************************************
	 system.get.config.phtml							 Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Arguments: see super::system.get.config.phtml
	 Grant needed: none
	 Global variables: none

	 This template calls its superclass template first, and then adds
	 the url defined in psite to the configcache->root.

	 This allows make_url() to generate correct user specified url's.

	 No result.	

	******************************************************************/

	debug($this->type."/system.get.config.phtml ".$this->path,"class");
	$this->call("super::system.get.config.phtml");
	$configcache=$ARConfig->cache[$this->path];
	// this is the only
	if ($data->url) {
		$configcache->root["path"]=$this->path;
		$configcache->root["value"]=$data->url;
	}
	$ARConfig->cache[$this->path]=$configcache;
?>