<?php
	/******************************************************************
	 system.get.config.phtml							 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: see pdir::system.get.config.phtml
	 Grant needed: none
	 Global variables: none

	 This template calls its superclass template first, and then adds
	 the url defined in psite to the configcache->root.

	 This allows make_url() to generate correct user specified url's.

	 No result.	

	******************************************************************/

	debug($this->type."/system.get.config.phtml ".$this->path,"class");
	$this->call("pdir::system.get.config.phtml",$arCallArgs);
	global $HTTP_SERVER_VARS;

	$configcache=$ARConfig->cache[$this->path];
	$host = $HTTP_SERVER_VARS["HTTP_HOST"];

	if ($sitenls=$this->data->url_list["host"][$host]) {
		$configcache->nls->default = $sitenls;
		$url = $this->data->url_list["nls"][$sitenls];
	}
	if (!$url) {
		$url=$data->url;
	}
	if ($url) {
		$configcache->root["path"]=$this->path;
		$configcache->root["value"]=$url;
		$configcache->root["list"]=$this->data->url_list;
	}


	$configcache->site=$this->path;
	$configcache->section=$this->path;
	$ARConfig->cache[$this->path]=$configcache;
?>