<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) &&
			$this->CheckConfig()) {
		$this->call("pdir::system.save.data.phtml",$arCallArgs);

		// unset the properties array, so no properties can be passed to this template.
		$properties = Array();
		$this->data->config->url_list = Array();
		$this->data->config->workspaceurl_list = Array();

		if (!$this->error) {
			$this->arIsNewObject=false;
            reset($AR->nls->list);
            $count=0;

            while (!$this->error && (list($key, $value)=each($AR->nls->list))) {
                if ($name=$this->getdata("name",$key)) { // $name is the variable that must be set for a language to be available.
					$mainURL = $this->getdata('url', $key);
					$urlList = $this->getdata('urlList', $key);

					if ( !is_array($urlList) ) {
						$urlList = array();
						if ( $mainURL ) {
							array_unshift( $urlList, $mainURL );
						}
					}

					$this->data->$key->url = "";
					$this->data->$key->urlList = $urlList;
					$this->data->config->url_list['nls'][$key] = array();

					$firstURL = true;
					foreach ( $urlList as $i => $url) {
						$url = trim($url);
						if (!$url) {
							unset( $this->data->$key->urlList[ $i ] );
							continue;
						}

						if (substr($url, -1, 1)=='/') {
							$url = substr($url, 0, -1);
						}

						preg_match('|^([a-z0-9]+:)?//([^/:]+)(:[0-9]+)?|i', $url, $regs);
						if ($url) {
							if ($firstURL) {
								$this->data->$key->url = $url;
							}
							$this->data->config->url_list['nls'][$key][] = $url;
							if (!$this->data->config->url_list['host'][$regs[2].$regs[3]]) {
								$this->data->config->url_list['host'][$regs[2].$regs[3]] = $key;
							} else {
								$this->error = "Please fill in distinctive hostnames; they should not be the same for different languages.";
							}
						}
						$protocol = $regs[1];
						if ($protocol) {
							$protocol = substr( $protocol, -1 ); // remove trailing ':'
						}
						$properties["url"][$count]["protocol"]=	$regs[1];
						$properties["url"][$count]["host"]=		$regs[2];
						if ($regs[3]) {
							$properties["url"][$count]["port"]= (int)substr($regs[3], 1);
						}
						$count++;
						$firstURL = false;
					}
					$workspaceurl=$this->getdata("workspaceurl",$key);
					if (substr($workspaceurl, -1, 1)=='/') {
						$workspaceurl=substr($workspaceurl, 0, -1);
					}
					if ($workspaceurl!=$this->data->$key->workspaceurl) {
						$clearcache=true;
						$this->data->$key->workspaceurl=$workspaceurl;
					}
					preg_match('|^([a-z0-9]+)://([^/:]+)(:[0-9]+)?|i', $workspaceurl, $regs);
					if ($workspaceurl) {
						$this->data->config->workspaceurl_list['nls'][$key] = $workspaceurl;
						if (!$this->data->config->workspaceurl_list['host'][$regs[2].$regs[3]]) {
							$this->data->config->workspaceurl_list['host'][$regs[2].$regs[3]] = $key;
						} else {
							$this->error = "Please fill in distinctive hostnames; they should not be the same for different languages.";
						}
					}
					$properties["url"][$count]["protocol"]=	$regs[1];
					$properties["url"][$count]["host"]=		$regs[2];
					if ($regs[3]) {
						$properties["url"][$count]["port"]=	(int)substr($regs[3], 1);
					}
					$count++;


                }
			}
			if ($clearcache) {
				// Changing the root url invalidates all cache images below this.
				$this->ClearCache();
			}
			$this->data->url = $this->data->{$this->data->nls->default}->url;
			$this->data->workspaceurl=$this->data->{$this->data->nls->default}->workspaceurl;
			if (!$this->error) {
				$this->save($properties);
				$this->ClearCache();
			}
		}
	}
?>