<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.0b
	 ------------------------------------------------------------------
 
	******************************************************************/

	if (($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")) &&
			$this->CheckConfig()) {
		$this->call("pdir::system.save.data.phtml",$arCallArgs);
		if (!$this->error) {
			$this->arIsNewObject=false;
			$url=$this->getdata("url","none");
			if ($this->data->url!=$url) {
				$this->data->url=$url;
				// Changing the root url invalidates all cache images below this.
				$this->ClearCache();
			}

			unset($properties);
			eregi('^([a-z0-9]+)://([^/:]+)(:[0-9]+)?', $url, $regs);
			$properties["url"][0]["protocol"]=	"'".AddSlashes($regs[1])."'";
			$properties["url"][0]["host"]=		"'".AddSlashes($regs[2])."'";
			if ($regs[3]) {
				$properties["url"][0]["port"]=	$regs[3];
			}

			if (substr($this->data->url,-1)=="/") {
				$this->data->url=substr($this->data->url,0,-1);
			}
			$this->save($properties);
			$this->ClearCache();
		}
	}
?>