<?php
	/******************************************************************
	 system.get.config.phtml							 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: see pdir::system.get.config.phtml
	 Grant needed: none
	 Global variables: none

	 This template calls its superclass template first, and then adds
	 the url defined in psite to the configcache->root.

	 This allows make_url() to generate correct user specified url's.

	 No result.	

	******************************************************************/

	debug($this->type."/system.get.config.data.phtml ".$this->path,"class");
	$this->call("pdir::system.get.config.data.phtml",$arCallArgs);

	$configcache=$ARConfig->cache[$this->path];
	$hostsubwww = $host = $_SERVER["HTTP_HOST"];
	if (substr($host, 0, 4) == 'www.') {
		$hostsubwww = substr($host, 4);
	}
	if (($sitenls=$this->data->url_list["host"][$hostsubwww]) 
		|| (($sitenls=$this->data->url_list["host"]["www.".$hostsubwww]))) {

		$url = $this->data->url_list["nls"][$sitenls];
	}
	if (!$url) {
		$url=$data->url;
	}
	if ($url) {
		$configcache->root["path"]=$this->path;
		$configcache->root["value"]=$url;
		$configcache->root["list"]=$this->data->url_list;
		if ($sitenls) {
			$configcache->root["nls"] = $sitenls;
		}
	}

	$configcache->site=$this->path;
	$configcache->section=$this->path;
	$ARConfig->cache[$this->path]=$configcache;
?>
