<?php 
	/******************************************************************
	 browse.nav.details.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none

	 This templates displays the detailed list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<style>
	BODY, TD {
		font: 10pt Arial,Helvetica,sans-serif;
		line-height: 15pt;
	}
	BODY {
		margin: 0px;
		padding: 0px;
	}
	TD {
		margin: 1px;
	}
	A {
		text-decoration: none;
		color: black;
	}
	.heading {
		font: 10pt Arial,Helvetica,sans-serif;
		background: buttonface;
		border: 1px solid buttonhighlight;
		border-bottom-color: buttonshadow;
		border-right-color: buttonshadow;
		text-align: center;
	}

</style>
<body bgcolor="white">
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
  <td><div class="heading"><?php echo $ARnls["name"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["size"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["user"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["time"]; ?></div></td>
  <td><div class="heading">&nbsp;</div></td>
</tr>
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}	
	if ($date) {
		$date=ereg_replace("[^0-9]*","",$date);
		$crit["timeframe"]["start"]["<="]=$date+86400;
		$crit["timeframe"]["end"][">="]=$date;
	}
	if (!$limit) {
		$limit=100;
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$total=$this->store->count($this->store->find("", $crit, 0));
	$this->find(".",$crit, "browse.nav.details.show.phtml", "", $limit, $offset);
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
?>
</table>
</body>
<?php
	}
?>