<?php
	/******************************************************************
	 classic.form.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arNewType, $arNewFilename, $arReturnPage
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object. 

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<body bgcolor="white">
<?php
	$this->parents($this->path, "show.link.phtml","target=classic.edit.phtml");
?>
<form>
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">
<?php
	include($this->store->code."widgets/formlock/js.html");
?>

<table border="0" cellspacing="0">
<tr bgcolor="#404074">
	<td colspan="2">
		<?php
			$wgNLSpretext="<font face=\"helvetica, sans-serif\" color=\"white\" size=\"+1\"><b>".
				$ARnls["editcalendar"].":</b></font><br>";
			include($this->store->code."widgets/nls/form.phtml");
		?>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="text" name="<?php echo $nls; ?>[name]" maxlength="50" value="<?php $this->showdata("name",$nls); ?>">
	</td>
</tr>
<tr>
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removecalendar"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->code."widgets/recurse/form.js");
				include($this->store->code."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
<?php
	}
?>