<?php
	/******************************************************************
	 classic.form.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: arNewType, arNewFilename
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object.

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php 
	$title=$ARnls["edit"]." ".current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<?php 
		if ($this->call("lock.init.phtml")) {

		include($this->store->get_config("code")."widgets/multiple/js.html"); 
?>
</head>
<body bgcolor="white" onUnLoad="releaseLock()">
<?php $this->call("lock.form.phtml"); ?>
<form method="post" onSubmit="if (document.wgWizForm.wgWizSubmitHandler) { document.wgWizForm.wgWizSubmitHandler(); }">
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<table border="0" cellspacing="0" width="100%"> 
<tr>
	<td bgcolor="#404074">
		<?php
			$wgNLSpretext="<font face=\"helvetica, sans-serif\" size=\"+1\" color=\"white\"><b>".
				$ARnls["editorganization"].":</b></font><br>";
			include($this->store->get_config("code")."widgets/nls/form.phtml");
		?>
	</td>
</tr>
</table>


<table border="0">
<tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b>
		<?php echo $ARnls["name"]; ?></b>&nbsp;:</font>
	</td><td align="left">
		<input type="text" size="30"	name="<?php echo $nls; ?>[name]" value="<?php $this->showdata("name",$nls); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["address"]; ?>&nbsp;:</font>
	</td><td align="left">
		<input type="text" size="30"	name="address" value="<?php $this->showdata("address","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["zipcode"]; ?>&nbsp;:</font>
	</td><td align="left">
				<input type="text" size="6" maxlength="6" name="zipcode" value="<?php $this->showdata("zipcode","none"); ?>">
				<font face="helvetica, sans-serif">
				&nbsp;&nbsp;<?php echo $ARnls["city"]; ?>&nbsp;:</font>
				<input type="text" size="15" name="city" value="<?php $this->showdata("city","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["pobox"]; ?>&nbsp;:</font>
	</td><td align="left">
		<input type="text" size="10"	name="pobox" value="<?php $this->showdata("pobox","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["country"]; ?>&nbsp;:</font>
	</td><td align="left">
	<select name="country">
	<?php
		$this->ls("/system/addressbook/countries/","show.option.value.phtml","selected=".$this->getdata("country","none"));
	?>
	</select>
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["telephone"]; ?>&nbsp;:</font>
	</td><td align="left">
		<input type="text" name="telephone" value="<?php $this->showdata("telephone","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["fax"]; ?>&nbsp;:</font>
	</td><td align="left">
		<input type="text" name="fax" value="<?php $this->showdata("fax","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["url"]; ?>&nbsp;:</font>
	</td><td align="left">
		<input type="text" name="url" value="<?php $this->showdata("url","none"); ?>">
	</td>
</tr>

<tr valign="top">
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["email"]; ?>&nbsp;:</font>
	</td><td align="left">
	<?php
		$wgMultipleName="emails";
		$wgMultipleArray=$this->getdata("emails","none");
		if (!is_array($wgMultipleArray) && ($wgMultipleArray)) {
			$wgMultipleArray=explode(",",$emails);
		}
		include($this->store->get_config("code")."widgets/multiple/form.html");
	?>
	</td>
</tr><tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif"><?php echo $ARnls["comments"]; ?>&nbsp;:</font>
	</td>
	<td colspan="2">
		<textarea name="<?php echo $nls."[summary]"; ?>" cols="50" rows="4" wrap="soft"><?php
				echo ereg_replace("&","&amp;",$this->getdata("summary",$nls));
		?></textarea>
	</td>
</tr>
</table>
 

<p>

<script>
	<!-- set wgWizForm to the current form -->
	document.wgWizForm = document.forms[0];
</script>
<table width="100%" cellspacing="0" border="0">
<?php
	$configcache=$ARConfig->cache[$this->path];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->AR_implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}

	if ($hascustomdata) {
?><tr>
	<td colspan="2" bgcolor="#404074">
		<font face="helvetica, sans-serif" color="white">
		<?php 
			echo $ARnls["customdata"];
		?></font>
	</td>
</tr><tr>
	<td colspan="2">
		<?php
				$this->call("edit.object.data.custom.phtml", Array("arLanguage" => $selectednls));
		?>
	</td>
</tr>
<?php
	}
?><tr bgcolor="#404074">
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removeorganization"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->get_config("code")."widgets/recurse/form.js");
				include($this->store->get_config("code")."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
		}
	}
?>
