<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		global $HTTP_POST_VARS;

		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$name="edit.object.data.name.phtml";
		$address="edit.object.data.address.phtml";
		$contact="edit.object.data.contact.phtml"; 
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $save;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["name"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$name;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["address"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/address.png";
		$wgWizFlow[$i]["template"]=$address;
		$wgWizFlow[$i]["nolang"]=true;
		
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["contactinformation"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/address.png";
		$wgWizFlow[$i]["template"]=$contact;
		$wgWizFlow[$i]["nolang"]=true;
		
		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arNewFilename="{5:id}";
			$ARCurrent->arNewFilename=$arNewFilename;
		}		

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$this->type.'_open.gif" alt="" hspace="4" align="absmiddle">';
		include($this->store->code."widgets/wizard/new.html");
	}
?>