<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		global $HTTP_POST_FILES, $HTTP_POST_VARS;

		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$name="edit.object.data.name.phtml";
		$address="edit.object.data.address.phtml";
		$contact="edit.object.data.contact.phtml"; 
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["name"];
		$wgWizFlow[$i]["template"]=$name;
		$wgWizFlow[$i]["next"]=$i+1; 
		$wgWizFlow[$i]["save"]=$i+3+$saveoffset+$customoffset;
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["address"];
		$wgWizFlow[$i]["template"]=$address;
		$wgWizFlow[$i]["prev"]=$i-1;
		$wgWizFlow[$i]["next"]=$i+1; 
		$wgWizFlow[$i]["save"]=$i+2+$saveoffset+$customoffset;
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["contactinformation"];
		$wgWizFlow[$i]["template"]=$contact;
		$wgWizFlow[$i]["prev"]=$i-1;
		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			if ($hascustomdata) {
				$wgWizFlow[$i]["next"]=$i-4;
			} else {
				$wgWizFlow[$i]["next"]=$i-3;
			}
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
	 
		$arLanguage=$this->getdata("arLanguage","none");
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($wgWizFlow[0]["current"]==4) { // =edit.object.language.phtml
			if ($arControl=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arNewFilename="{5:id}";
			$ARCurrent->arNewFilename=$arNewFilename;
		}		
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>