<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]="object.new.cancel.phtml";
	$arFlow[0]["save"]="edit.object.data.save.phtml";
 
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]="object.new.filename.phtml";
	$arFlow[$i]["nolang"]=true;

	$i++;
	$arFlow[$i]["title"]=$ARnls["name"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]="edit.object.data.name.phtml";

	$i++;
	$arFlow[$i]["title"]=$ARnls["address"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/address.png";
	$arFlow[$i]["template"]="edit.object.data.address.phtml";
	$arFlow[$i]["nolang"]=true;

	$i++;
	$arFlow[$i]["title"]=$ARnls["contactinformation"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/contact.png";
	$arFlow[$i]["template"]="edit.object.data.contact.phtml"; 
	$arFlow[$i]["nolang"]=true;

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]="edit.object.data.custom.phtml";
	}

	$arLanguage=$this->getdata("arLanguage","none");
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}

	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		

	$arResult = $this->call("user.wizard.new.html", Array("wgWizFlow" => $arFlow));
?>