<?php
  /******************************************************************
   save.phtml					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: $newtype, $newfilename
   Grant needed: add or edit
   Interface/Widget: all
   Global variables: none

   This template checks the input from form.phtml, sets the 
   corresponding values in a data object ($newdata), adds the proper
   values to its properties and includes the common save code to save
   this data as a new object or as an update of this object 
   (depending on $newtype, if $newtype is set a new object will be 
   saved.)

   no result.
 
  ******************************************************************/
  if ($newtype) {
    $newdata=new object;
  } else {
    $newdata=$data; 
  }


  if (!isset(${$ARConfig->nls->default}) && !isset($newdata->{$ARConfig->nls->default})) { // default language for this path
    $error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
  } else {
    if (!$newdata->nls) {
      $newdata->nls=new object;
    }
    $newdata->nls->default=$this->nls;
    reset($AR->nls->list);
    while (list($key, $value)=each($AR->nls->list)) {
      if (isset(${$key})) {
        $nlsformdata=$$key;
        if (!$newdata->$key) {
          $newnlsdata=new object;
        } else {
          $newnlsdata=$newdata->$key;
        }
        $newnlsdata->summary=$nlsformdata["summary"];
        $newdata->$key=$newnlsdata;
        $newdata->nls->list[$key]=$value;
      }
    }
  }



  if (!$name) {
	$error=$ARnls["err:nonameentered"];
  } else {
	$newdata->name=$name;
	$newdata->address=$address;
	$newdata->zipcode=$zipcode;
	$newdata->pobox=$pobox;
	$newdata->city=$city;
	$newdata->country=$country;
	$newdata->telephone=$telephone;
	$newdata->fax=$fax;
	$newdata->url=$url;
	$emails=explode(",",$emails);
	if ($emails) $newdata->emails=$emails;
  }

  if (!$error) {
	$properties["name"][0]["value"]="'".AddSlashes($newdata->name)."'";
	$properties["address"][0]["street"]="'".AddSlashes($newdata->street)."'";
	$properties["address"][0]["zipcode"]="'".AddSlashes($newdata->zipcode)."'";
	$properties["address"][0]["city"]="'".AddSlashes($newdata->city)."'";
	$properties["address"][0]["country"]="'".AddSlashes($newdata->country)."'";

	include($this->store->code."includes/save.dir.phtml");
  } else {
	include($this->store->code."includes/error.phtml");
  }
?>