<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.0b
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject && $this->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		}

		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			$count=0;
			while (list($key, $value)=each($AR->nls->list)) {
				
				if ($this->getdata("name", $key)) {
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					if (!$this->getdata("name",$key)) {
						$this->error=sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]);
					}
					$newnlsdata->name=$this->getdata("name",$key);
					$properties["name"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["name"][$count]["nls"]="'$key'";
					$properties["text"][$count]["value"]="'".AddSlashes($newnlsdata->name)."'";
					$properties["text"][$count]["nls"]="'$key'";
					$count++;
					$newnlsdata->summary=$this->getdata("summary",$key);
					$properties["text"][$count]["value"]="'".AddSlashes($newnlsdata->summary)."'";
					$properties["text"][$count]["nls"]="'$key'";
					$count++;
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else { // clear language values for $key->name if set, keep the rest, just in case.
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->nls->list[$key]);
					}
				}
			}
			$this->data->address=$this->getdata("address","none");
			$this->data->zipcode=$this->getdata("zipcode","none");
			$this->data->city=$this->getdata("city","none");
			$this->data->country=$this->getdata("country","none");
			$this->data->telephone=$this->getdata("telephone","none");
			$this->data->fax=$this->getdata("fax","none");
			$this->data->pobox=$this->getdata("pobox","none");
			$this->data->url=$this->getdata("url","none");
			$emails=explode(",",$this->getdata("emails","none"));
			if ($emails[0]) {
					$this->data->emails=$emails;
			} else {
					unset($this->data->emails);
			}
			$properties["address"][0]["street"]="'".AddSlashes($this->data->address)."'";
			$properties["address"][0]["zipcode"]="'".AddSlashes($this->data->zipcode)."'";
			$properties["address"][0]["city"]="'".AddSlashes($this->data->city)."'";
			$properties["address"][0]["country"]="'".AddSlashes($this->data->country)."'";
			if (!$this->error) {
				$this->save($properties);
			}
		}
	}
?>