<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="contact">
		<legend><?php echo $ARnls["contactinformation"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<?php echo $ARnls["telephone"]; ?>
				</td><td>
					<?php echo $ARnls["mobile"]; ?>
				</td>
			</tr><tr>
				<td>
					<input type="text" name="telephone" size="12" value="<?php $this->showdata("telephone","none"); ?>">
				</td><td>
					<input type="text" name="mobile" size="12" value="<?php $this->showdata("mobile","none"); ?>">
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["email"]; ?>
				</td>
			</tr><tr>
				<td colspan="2">
				<?php
					$wgMultipleArray=$this->getdata("emails","none");
					if (!is_array($wgMultipleArray) && ($wgMultipleArray)) {
							$wgMultipleArray=explode(",",$wgMultipleArray);
					} 
					$wgMultipleName="emails";
					include($this->store->get_config("code")."widgets/multiple/js.html");
					include($this->store->get_config("code")."widgets/multiple/form.html");
				?>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["telephone"].focus();
	}
</script>
<?php
	}
?>