<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->get_config("code")."widgets/wizard/code.php");

		$name="edit.object.data.name.phtml";
		$address="edit.object.data.address.phtml";
		$contact="edit.object.data.contact.phtml"; 
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $finish;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["name"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$name;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["address"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/address.png";
		$wgWizFlow[$i]["template"]=$address;
		$wgWizFlow[$i]["nolang"]=true;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["contactinformation"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/contact.png";
		$wgWizFlow[$i]["template"]=$contact;
		$wgWizFlow[$i]["nolang"]=true;

		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arNewFilename="{5:id}";
			$ARCurrent->arNewFilename=$arNewFilename;
		}

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
			unset($wgWizFlow[$i]["next"]);
			unset($wgWizFlow[$i]["save"]);
		}

		$wgWizFlow = $this->call("user.wizard.edit.html", Array("wgWizFlow" => $wgWizFlow));

		if (!$ARCurrent->arTypeIconsSmall[$this->type]) {
			// FIXME: for performance the check above is necessary, but
			// it does make it possible to get the wrong icon...
			// get typetree to get the correct icon
			$this->call('typetree.ini');
		}
		$icon=$ARCurrent->arTypeIcons[$this->type]['default'];
		if (!$icon) {
			$dotPos=strpos($this->type, '.');
			if (false!==$dotPos) {
				$realtype=substr($this->type, 0, $dotPos);
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
			} else { 
				$realtype=$this->type;
			}
			if (!$icon) {
				$icon=$AR->dir->images."icons/".$realtype.".gif";
			}
			$name=$ARCurrent->arTypeNames[$this->type];
		} else {
			$name=$ARCurrent->arTypeNames[$this->type];
		}
		$arResult=$icon;

		$wgWizTitle=$ARnls["edit"]." ".$name;
		$wgWizHeader=$wgWizTitle.'<img src="'.$icon.'" alt="" hspace="4" align="absmiddle">';
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>