<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->code."widgets/wizard/code.php");

		$name="edit.object.data.name.phtml";
		$address="edit.object.data.address.phtml";
		$contact="edit.object.data.contact.phtml"; 
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["name"];
		$wgWizFlow[$i]["template"]=$name;
		$wgWizFlow[$i]["next"]=$i+1; 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["address"];
		$wgWizFlow[$i]["template"]=$address;
		$wgWizFlow[$i]["prev"]=$i-1;
		$wgWizFlow[$i]["next"]=$i+1; 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["contactinformation"];
		$wgWizFlow[$i]["template"]=$contact;
		$wgWizFlow[$i]["prev"]=$i-1;
		if (count($ARConfig->nls->list)>1) { // just one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			$wgWizFlow[$i]["next"]=$i-3;
			$wgWizFlow[$i]["prev"]=$i-3;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
	 
		$arLanguage=$this->getdata("arLanguage","none");
		if ($wgWizFlow[0]["current"]==4) { // =edit.object.language.phtml
			$arControl=$this->getdata("wgWizControl","none");
			if ($arControl==$ARnls["prev"]) { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arNewFilename="{5:id}";
			$ARCurrent->arNewFilename=$arNewFilename;
		}		
		global $HTTP_POST_VARS;
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>