<?php
  /******************************************************************
   form.phtml                                      Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<head>
	<?php include($this->store->code."widgets/multiple/js.html"); ?>
</head>

<body bgcolor="white">
<?php
  $this->parents($this->path, "ShowLink.phtml","target=edit.phtml");
?>
<form method="post">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="newtype" value="<?php echo $newtype; ?>">
<input type="hidden" name="newparent" value="<?php echo $this->path; ?>">
<input type="hidden" name="newfilename" value="<?php echo $newfilename; ?>">
<input type="hidden" name="returnpage" value="<?php echo $returnpage; ?>">
<?php
include($this->store->code."widgets/formlock/js.html");
?>

<table border="0" cellspacing="0" width="100%"> 
<tr>
  <td bgcolor="#404074">
    <?php
      $wgNLSpretext="<font face=\"helvetica, sans-serif\" size=\"+1\" color=\"white\"><b>".
        $ARnls["editcontact"].":</b></font><br>";
      include($this->store->code."widgets/nls/form.phtml");
    ?>
  </td>
</tr>
</table>

<table border="0">
<tr>
  <td align="right" valign="top">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
  </td><td colspan="2" valign="top">
    <table border="0" cellpadding="0" cellspacing="1">
    <tr>
      <td align="left" valign="top">
        <font face="helvetica, sans-serif"><?php echo $ARnls["first"]; ?></font>
      </td><td align="left">
        <font face="helvetica, sans-serif"><?php echo $ARnls["last"]; ?></font>
      </td>
    </tr>
    <tr>
      <td>
        <input type="text" name="firstname" size="12" maxlength="50" 
          value="<?php $this->showdata("firstname","none"); ?>">
        <input type="text" name="middlename" maxlength="50" 
          size="5" value="<?php $this->showdata("middlename","none"); ?>">
      </td><td>
		<input type="text" name="lastname" size="20" maxlength="50" 
           value="<?php echo $this->showdata("lastname","none"); ?>">
      </td>
    </tr>
    </table>
  </td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["address"]; ?> :</font>
	</td><td colspan="2">
		<input type="text" size="30"  name="address" value="<?php $this->showdata("address","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["zipcode"]; ?> :</font>
	</td><td colspan="2">
		<input type="text" size="6" maxlength="6" name="zipcode" value="<?php echo $this->showdata("zipcode","none"); ?>">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["city"]; ?> :</font>
		<input type="text" size="15" name="city" value="<?php echo $this->showdata("city","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["country"]; ?> :</font>
	</td><td colspan="2">
	<select name="country">
	<?php
		$this->ls("/system/addressbook/countries/","ShowOption.phtml","selected=".$this->getdata("country","none"));
	?>
	</select>
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["telephone"]; ?> :</font>
	</td><td colspan="2">
		<input type="text" name="telephone" value="<?php $this->showdata("telephone","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["mobile"]; ?> :</font>
	</td><td colspan="2">
		<input type="text" name="mobile" value="<?php $this->showdata("mobile","none"); ?>">
	</td>
</tr>
<tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif">
		<?php echo $ARnls["email"]; ?>&nbsp;:</font>
	</td><td>
		<?php
			$wgMultipleArray=$this->getdata("emails","none");
			if (!is_array($wgMultipleArray) && ($wgMultipleArray)) {
				$wgMultipleArray=explode(",",$wgMultipleArray);
			}
			$wgMultipleName="emails";
			include($this->store->code."widgets/multiple/form.html");
		?>
	</td>
</tr>
<tr>
  <td align="right" valign="top">
    <font face="helvetica, sans-serif"><?php echo $ARnls["summary"]; ?>&nbsp;:</font>
  </td>
  <td colspan="2">
    <textarea name="<?php echo $nls."[summary]"; ?>" cols="50" rows="4" wrap="soft"><?php
        echo ereg_replace("&","&amp;",$this->getdata("summary",$nls));
    ?></textarea>
  </td>
</tr>
</table>



<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
  <td>
    <?php if ($newtype) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">

<?php
    $wgRecurseConfirm=$ARnls["q:removeperson"];
	$wgRecurseAction="delete";
	$wgRecurseTitle=$ARnls["delete"];
    include($this->store->code."widgets/recurse/form.js");
	include($this->store->code."widgets/recurse/form.html");
?>

    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>
</form>
<font face="helvetica, sans-serif" size="2">
<?php
  $this->ls("","Show.phtml","target=edit.phtml");
?>
</font>
</body>
<?php
  }
?>