<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	global $HTTP_POST_VARS;

	$saveoffset=0;
	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				$saveoffset+=1;
				break;
			}
		}
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.filename.phtml";
	$name="edit.object.data.name.phtml";
	$address="edit.object.data.address.phtml";
	$contact="edit.object.data.contact.phtml"; 
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$finish;
 
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]=$ARnls["name"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$name;

	$i++;
	$arFlow[$i]["title"]=$ARnls["address"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/address.png";
	$arFlow[$i]["template"]=$address;
	$arFlow[$i]["nolang"]=true;

	$i++;
	$arFlow[$i]["title"]=$ARnls["contactinformation"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/contact.png";
	$arFlow[$i]["template"]=$contact;
	$arFlow[$i]["nolang"]=true;

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}

	$arLanguage=$this->getdata("arLanguage","none");
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}
	if (($arFlow[0]["current"]==2) && ($arControl=="next")) {
		$HTTP_POST_VARS[$arLanguage]["name"]=$this->getdata("lastname");
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	$arResult = $this->call("user.wizard.new.html", Array("wgWizFlow" => $arFlow));
?>