<?php 
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$width="1";
		$height="1";
?>
<table border="0" cellspacing="0" celllpadding="0" width="100%">
<tr><td colspan="3" bgcolor="#DDDDDD"><img height="<?php echo $height; ?>" width="<?php echo $width; ?>" src="<?php echo $AR->dir->images."dot.gif"; ?>"></td></tr>
<tr><td bgcolor="#DDDDDD" width="1"><img border="0" width="<?php echo $width; ?>" height="<?php echo $height; ?>" src="<?php echo $AR->dir->images."dot.gif"; ?>"></td>
<td width="100%">
<table border="0" cellspacing="0">
<tr>
	<td align="left" valign="top" width="20">
		<a href="<?php echo $this->make_url(); ?>" onClick="if (top.View) { top.View('<?php echo $this->path; ?>'); return false; }">
		<img border="0" src="<?php echo $AR->dir->images."icons/".$this->type.".gif"; ?>"></a>
	</td>
	<td align="left">
	<font face="helvetica,sans-serif"><b><?php $this->showdata("name"); ?></b><br>
	<?php $this->showdata("address"); ?><br>
	<?php $this->showdata("zipcode"); ?>&nbsp;&nbsp;
	<?php $this->showdata("city"); ?><br>
	<?php
		$this->get("/system/addressbook/countries/".$this->data->country,"show.name.phtml");
	?><br><br>
	<?php $this->showdata("telephone"); ?><br>
	<?php $this->showdata("mobile"); ?><br>
	</td><td width="100">&nbsp;</td>
	<td align="left" valign="top">
		<?php
			echo $nlsdata->summary; 
		?>
		<br><br>
		<?php
			if ($data->url)
				echo "<a href=\"".$data->url."\">".$data->url."</a><br>\n";
			while (is_array($data->emails) && (list($key,$email)=each($data->emails))) {
				echo "<a href=\"mailto:$email\">$email</a><br>";
			}
		?>
	</td>
</tr>
</table>
</td>
<td bgcolor="#DDDDDD"><img width="<?php echo $width; ?>" height="<?php echo $height; ?>" src="<?php echo $AR->dir->images."dot.gif"; ?>"></td>
</tr>
<tr><td colspan="3" bgcolor="#DDDDDD"><img height="<?php echo $height; ?>" width="<?php echo $width; ?>" src="<?php echo $AR->dir->images."dot.gif"; ?>"></td></tr>
</table>
<p>
<?php
	}
?>