<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject && $this->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		}

		if (!$this->getdata("lastname","none")) { // default language for this path
			$this->error=$ARnls["err:nolastnameentered"];
		} else {
			$this->data->firstname=$this->getdata("firstname","none");
			$this->data->middlename=$this->getdata("middlename","none");
			$this->data->lastname=$this->getdata("lastname","none");
			$this->data->name=$this->data->lastname;
			$comma=", ";
			if ($this->data->middlename) { 
				$this->data->name.=$comma.$this->data->middlename." ";
				$comma="";
			}
			$this->data->name.=$comma.$this->data->firstname;
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$properties["name"][]["value"]="'".AddSlashes($this->data->name)."'";
			$properties["text"][]["value"]="'".AddSlashes($this->data->name)."'";

			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				
				if ($this->getdata("summary",$key)) {  // name is language independant
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					$newnlsdata->name=$this->data->name;
					$newnlsdata->summary=$this->getdata("summary",$key);
					$properties["text"][]["value"]="'".AddSlashes($newnlsdata->summary)."'";
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else { // clear language values for $key->name if set, keep the rest, just in case.
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->$key->summary);
						unset($this->data->nls->list[$key]);
					}
				}
			}

			$this->data->address=$this->getdata("address","none");
			$this->data->zipcode=$this->getdata("zipcode","none");
			$this->data->city=$this->getdata("city","none");
			$this->data->country=$this->getdata("country","none");
			$this->data->telephone=$this->getdata("telephone","none");
			$this->data->mobile=$this->getdata("mobile","none");
			$emails=explode(",",$this->getdata("emails","none"));
			if ($emails[0]) {
					$this->data->emails=$emails;
			} else {
					unset($this->data->emails);
			}
			$properties["address"][0]["street"]="'".AddSlashes($this->data->address)."'";
			$properties["address"][0]["zipcode"]="'".AddSlashes($this->data->zipcode)."'";
			$properties["address"][0]["city"]="'".AddSlashes($this->data->city)."'";
			$properties["address"][0]["country"]="'".AddSlashes($this->data->country)."'";
			if (!$this->error) {
				$this->save($properties);
			}
		}
	}
?>