<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$scaffold = ar::getvar('scaffold');
			if ($scaffold && ar::exists($scaffold)) {
				$this->data = current(ar::get($scaffold)->call('system.get.data.phtml'));
			}
			if (!isset($this->data) || ar_error::isError($this->data)) {
				$this->data = new baseObject;
			}
		}

		$this->error = null;

		// unset the properties array, so no properties can be passed to this template.
		$properties = array();

		if (!$this->getdata("lastname","none")) {
			$this->error = ar::error( $ARnls["err:nolastnameentered"], 1210);
			return false;
		} else {
			$this->data->initials=$this->getdata("initials", "none");
			$this->data->firstname=$this->getdata("firstname","none");
			$this->data->middlename=$this->getdata("middlename","none");
			$this->data->lastname=$this->getdata("lastname","none");
			$this->data->name=$this->data->lastname;
			$comma=", ";
			$this->data->name=$this->data->lastname.$comma.$this->data->firstname;
			if ($this->data->middlename) {
				$this->data->name.=" ".$this->data->middlename;
			}
			if (!$this->data->nls) {
				$this->data->nls=new baseObject;
			}
			$properties["name"][]["value"]=$this->data->name;
			$properties["text"][]["value"]=$this->data->name;

			if (!$this->data->nls) {
				$this->data->nls=new baseObject;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				if ($summary=$this->getdata("summary", $key)) {
					if (!$this->data->$key) {
						$newnlsdata=new baseObject;
					} else {
						$newnlsdata=$this->data->$key;
					}
					$newnlsdata->name=$this->data->name;
					$newnlsdata->summary=$summary;
					$properties["text"][]["value"]=$newnlsdata->summary;
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				}
			}

			$this->data->address=$this->getdata("address","none");
			$this->data->zipcode=$this->getdata("zipcode","none");
			$this->data->city=$this->getdata("city","none");
			$this->data->country=$this->getdata("country","none");
			$this->data->state=$this->getdata("state","none");
			$this->data->telephone=$this->getdata("telephone","none");
			$this->data->mobile=$this->getdata("mobile","none");

			$emails = $this->getdata("emails", "none");
			if (!is_array($emails)) {
				$rawemails=$emails;
				$emails=explode(",",$emails);
				if ($emails[0]) {
					for ($i=0; $i<count($emails); $i++) {
						$email=trim($emails[$i]);
						if ($email) {
							$newemails[]=$email;
						}
					}
					$this->data->emails=$newemails;
				} else {
					unset($this->data->emails);
				}
			} else {
				$rawemails=implode(',',$emails);
				$this->data->emails=$emails;
			}

			$this->data->scaffold = $this->getdata('scaffold','none');

			$properties["address"][0]["street"]=$this->data->address;
			$properties["address"][0]["zipcode"]=$this->data->zipcode;
			$properties["address"][0]["city"]=$this->data->city;
			$properties["address"][0]["country"]=$this->data->country;
			if ($this->store->is_supported("fulltext")) {
				$properties["fulltext"][0]["value"]=$this->store->format_for_fti(
						$this->data->name." ".
						$this->data->address." ".
						$this->data->zipcode." ".
						$this->data->city." ".
						$this->data->country." ".
						$this->data->state." ".
						$this->data->telephone." ".
						$this->data->mobile." ".
						$rawemails
						);
			}
			if (!$this->error) {
				$arIsNewObject = $this->arIsNewObject;
				$arResult = $this->save($properties);
				if ( !$this->error && $arIsNewObject && $this->data->scaffold ) {
					$this->call('system.copy.scaffold.php', array('scaffold' => $this->data->scaffold) );
				}
			}
			global $cache_config;
			$cachestore=new cache($cache_config);
			$cachestore->onObjectSaved($this->id);
		}
	}
?>