<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new object;
		}

		if (!$this->getdata("lastname","none")) {
			$this->error=$ARnls["err:nolastnameentered"];
		} else {
			$this->data->initials=$this->getdata("initials", "none");
			$this->data->firstname=$this->getdata("firstname","none");
			$this->data->middlename=$this->getdata("middlename","none");
			$this->data->lastname=$this->getdata("lastname","none");
			$this->data->name=$this->data->lastname;
			$comma=", ";
			$this->data->name=$this->data->lastname.$comma.$this->data->firstname;
			if ($this->data->middlename) {
				$this->data->name.=" ".$this->data->middlename;
			}
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$properties["name"][]["value"]="'".AddSlashes($this->data->name)."'";
			$properties["text"][]["value"]="'".AddSlashes($this->data->name)."'";

			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				if ($summary=$this->getdata("summary", $key)) {
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					$newnlsdata->name=$this->data->name;
					$newnlsdata->summary=$summary;
					$properties["text"][]["value"]="'".AddSlashes($newnlsdata->summary)."'";
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				}
			}

			$this->data->address=$this->getdata("address","none");
			$this->data->zipcode=$this->getdata("zipcode","none");
			$this->data->city=$this->getdata("city","none");
			$this->data->country=$this->getdata("country","none");
			$this->data->state=$this->getdata("state","none");
			$this->data->telephone=$this->getdata("telephone","none");
			$this->data->mobile=$this->getdata("mobile","none");

			$emails = $this->getdata("emails", "none");
			if (!is_array($emails)) {
				$emails=explode(",",$emails);
				if ($emails[0]) {
					$this->data->emails=$emails;
				} else {
					unset($this->data->emails);
				}
			}
			$properties["address"][0]["street"]="'".AddSlashes($this->data->address)."'";
			$properties["address"][0]["zipcode"]="'".AddSlashes($this->data->zipcode)."'";
			$properties["address"][0]["city"]="'".AddSlashes($this->data->city)."'";
			$properties["address"][0]["country"]="'".AddSlashes($this->data->country)."'";
			if (!$this->error) {
				$this->save($properties);
				$this->ClearCache();
			}
		}
	}
?>