<?php
	/******************************************************************
	 classic.form.phtml               Muze Ariadne: pBookmark extension
	 ------------------------------------------------------------------
	 Author: Auke van Slooten (auke@muze.nl)
	 Date: 30 october 2002

	 Copyright 2002 Muze

	 This file is part of the Ariadne: pBookmark extension, pBookmark.

	 pBookmark is free software; you can redistribute it and/or modify
	 it under the terms of the GNU General Public License as published 
	 by the Free Software Foundation; either version 2 of the License, 
	 or (at your option) any later version.
 
	 pBookmark is distributed in the hope that it will be useful,
	 but WITHOUT ANY WARRANTY; without even the implied warranty of
	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 GNU General Public License for more details.

	 You should have received a copy of the GNU General Public License
	 along with pBookmark; if not, write to the Free Software 
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
     02111-1307  USA

	-------------------------------------------------------------------

	 Arguments: arNewType, arNewFilename, arReturnPage
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object. 

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php 
	$title=$ARnls["edit"]." ".current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<?php
		if ($this->call("lock.init.phtml")) {
?>
</head>
<body bgcolor="white" onUnLoad="releaseLock();">
<?php $this->call("lock.form.phtml"); ?>
<form  onSubmit="if (document.wgWizForm.wgWizSubmitHandler) { document.wgWizForm.wgWizSubmitHandler(); }">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<script>
	<!-- set wgWizForm to the current form -->
	document.wgWizForm = document.forms[0];
</script>

<table border="0" cellspacing="0" width="100%">
<tr>
	<td colspan="2" bgcolor="#404074">
		<font face="helvetica, sans-serif" color="white" size="+1"><b><?php echo $title; ?> :</b></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><?php echo $ARnls["value"]; ?> :</font>
	</td>
	<td>
		<input type="text" name="value"
			value="<?php $this->showdata("value","none"); ?>">
	</td>
</tr><tr>
	<td colspan="2" bgcolor="#404074">
		<?php 
			include($this->store->code."widgets/nls/form.phtml");
		?>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?> :</b></font>
	</td>
	<td>
		<input type="text" name="<?php echo $nls."[name]"; ?>" maxlength="50" 
			value="<?php $this->showdata("name",$nls); ?>">
	</td>
</tr><tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif"><?php echo $ARnls["summary"]; ?>&nbsp;:</font>
	</td>
	<td>
		<textarea name="<?php echo $nls."[summary]"; ?>" cols="50" rows="4" wrap="soft"><?php 
				echo ereg_replace("&","&amp;",$this->getdata("summary",$nls)); 
		?></textarea>
	</td>
</tr><tr>
	<td><br></td>
</tr>
<?php 
	$configcache=$ARConfig->cache[$this->path];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}

	if ($hascustomdata) {
?>
<tr>
	<td colspan="2" bgcolor="#404074">
		<font face="helvetica, sans-serif" color="white">
		<?php 
			echo $ARnls["customdata"];
		?></font>
	</td>
</tr><tr>
	<td colspan="2">
		<?php
				$this->call("edit.object.data.custom.phtml", Array("arLanguage" => $nls));
		?>
	</td>
</tr>
<?php
	}
?>
<tr bgcolor="#404074">
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removeobject"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->code."widgets/recurse/form.js");
				include($this->store->code."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
		}
	}
?>