<?php
	/******************************************************************
	 edit.object.data.form.phtml           Muze Ariadne: pBookmark extension
	 ------------------------------------------------------------------
	 Author: Auke van Slooten (auke@muze.nl)
	 Date: 30 october 2002

	 Copyright 2002 Muze

	 This file is part of the Ariadne: pBookmark extension, pBookmark.

	 pBookmark is free software; you can redistribute it and/or modify
	 it under the terms of the GNU General Public License as published 
	 by the Free Software Foundation; either version 2 of the License, 
	 or (at your option) any later version.
 
	 pBookmark is distributed in the hope that it will be useful,
	 but WITHOUT ANY WARRANTY; without even the implied warranty of
	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 GNU General Public License for more details.

	 You should have received a copy of the GNU General Public License
	 along with pBookmark; if not, write to the Free Software 
	 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
	 02111-1307  USA

	-------------------------------------------------------------------
	 Arguments: newtype, newparent, newfilename
	 Grant needed: read
	 Global variables: none

	 This template displays the data entry step for creating or editing
	 an object. The template is meant to be used as part of a wizard.

	 no result.

	******************************************************************/
	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="data">
		<legend><?php echo $ARnls["data"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<span class="required"><?php echo $ARnls["name"]; ?></span>
				</td><td align="right">
					<?php echo $flag; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<input type="text" name="<?php echo $selectednls."[name]"; ?>" 
						value="<?php $this->showdata("name", $selectednls); ?>">
				</td>
			</tr><tr>
				<td colspan="2">
					URL
				</td>
			</tr><tr>
				<td colspan="2">
					<input type="text" name="value"  
						value="<?php $this->showdata("value","none"); ?>">
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["summary"]; ?>
				</td><td align="right">
					<?php echo $flag; ?>
				</td>
			</tr><tr>
				<td colspan="2">
					<textarea name="<?php echo $selectednls."[summary]"; ?>" cols="30" rows="4" wrap="soft"><?php 
							echo ereg_replace("&","&amp;",$this->getdata("summary", $selectednls)); 
					?></textarea>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["<?php echo $selectednls; ?>[name]"].focus();
	}
</script>
<?php
		if ($selectednls==$ARConfig->nls->default) {
			$arResult["save"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["save"][$selectednls."[name]"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
			$arResult["next"]=$arResult["save"];
		} else {
			$arResult["next"][$selectednls."[name]"]["ereg"]=".+";
			$arResult["next"][$selectednls."[name]"]["confirm"]=sprintf($ARnls["confirm:nonameentered"],$selectedlanguage);
			if ($this->getdata("name",$ARConfig->nls->default)) {
				$arResult["save"]=$arResult["next"];
			} else {
				$arResult["save"]=false;
			}
		}
	}
?>