<?php
	/******************************************************************
	 system.get.config.phtml							 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: see pdir::system.get.config.phtml
	 Grant needed: none
	 Global variables: none

	 This template calls its superclass template first, and then adds
	 the url defined in psite to the configcache->root.

	 This allows make_url() to generate correct user specified url's.

	 No result.	

	******************************************************************/

	debug($this->type."/system.get.config.data.phtml ".$this->path,"class");
	$this->call("psection::system.get.config.data.phtml",$arCallArgs);
	$configcache=$ARConfig->cache[$this->path];
	$configcache->project=$this->path;
	$ARConfig->cache[$this->path]=$configcache;
?>
