<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

	$folder=$this->call("system.get.folder.phtml");

?>
<SPAN class=item>
	<A HREF="javascript:top.View('<?php echo $this->path; ?>','<?php echo $nlsdata->name; ?>');"><IMG 
		SRC="<?php echo $AR->dir->images."icons/".$folder['icon']."_open.gif"; ?>" border="0" HEIGHT="40" WIDTH="40" HSPACE=0 VSPACE=0 ALT="<?php echo $nlsdata->name; ?>"><br>
	<?php 
		if (!$this->CheckSilent("read")) {
			echo "<font color=\"#CCCCCC\">$nlsdata->name</font>";
		} else {
			echo "$nlsdata->name";
		}
	?></A>
</SPAN>
