<?php
	/******************************************************************
	 classic.form.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: newtype, newparent, newfilename
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object.

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php 
	$title=$ARnls["edit"]." ".@current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<?php
		if ($this->call("lock.init.phtml")) {
?>
</head>
<body bgcolor="white" onUnLoad="releaseLock();">
<?php 
	$this->call("lock.form.phtml"); 
?>
<form>
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">
<table border="0" cellspacing="0" width="100%">
<tr>
	<td bgcolor="#404074" colspan="2">
		<?php
			$wgNLSpretext="<font face=\"helvetica, sans-serif\" color=\"white\" size=\"+1\"><b>".
				$ARnls["editshortcut"].":</b></font><br>";
			include($this->store->code."widgets/nls/form.phtml");
		?>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="text" name="<?php echo $nls; ?>[name]" maxlength="50" value="<?php
			$this->showdata("name",$nls); ?>">
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["path"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<?php 
			if (!$data->path) {
				$data->path=$this->parent;
			}
			if (!$wgBrowsePath=$this->getdata("path","none")) {
				$wgBrowsePath=$data->path;
			}
			$wgBrowseName="path"; 
			include($this->store->code."widgets/browse/js.html");
			include($this->store->code."widgets/browse/form.html");
		?>
	</td>
</tr><tr bgcolor="#404074">
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removeshortcut"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->code."widgets/recurse/form.js");
				include($this->store->code."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<?php if (!$newtype) { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["editoriginal"]; ?>">
		<?php } ?>
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
<?php
		}
	}
?>