<?php
	/******************************************************************
	 classic.edit.phtml								 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: $arSubmit
	 Grant needed: edit
	 Global variables: none

	 This template controls the flow between the form and save or delete
	 templates. 
	 First the classic.form.phtml template will be shown. This will set 
	 $arSubmit to either 'Save' or 'Delete'. Then the corresponding 
	 template will be called.

	 No result.

	******************************************************************/
	$ARCurrent->allnls=1;
	if (!$arReturnPage=$this->getdata("arReturnPage","none")) {
		$ARCurrent->arReturnPage=$this->store->root.$this->path."classic.edit.phtml";
	}
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		if ($arSubmit==$ARnls["save"]) { // save data
			$this->call("classic.save.phtml",$arCallArgs);
		} else if ($arSubmit==$ARnls["cancel"]) {
			ldRedirect($arReturnPage);
		} else if ($arSubmit==$ARnls["editoriginal"]) {
			ldRedirect($this->store->root.$data->path."classic.edit.phtml?arReturnPage=".RawUrlEncode($arReturnPage));
		} else {// edit it
			$this->call("classic.form.phtml",$arCallArgs);	
		}
	}
?>