<?php
	/******************************************************************
	 classic.save.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.data.phtml, $arReturnPage
	 Grant needed: add or edit
	 Global variables: none

	 This is a wrapper around system.save.data.phtml for the classic
	 interface.	 

	 no result.
 
	******************************************************************/
	$this->call("system.save.shortcut.phtml",$arCallArgs);
	if (!$this->error) {
		if ($this->store->implements($this->vtype, "pdir")) {
			if ($this->arIsNewObject) {
				$url=$AR->dir->www."setlink.php?do=add";
			} else {
				$url=$AR->dir->www."setlink.php?do=update";
			}
			if (!$arReturnPage) {
				$arReturnPage=$this->store->get_config("root").$parent;
			}
			$folder=$this->call("system.get.folder.phtml");
			if ($arShortCut) {
				$url.="&shortcut=".RawUrlEncode($arShortCut);
			}
			$url.="&link=".RawUrlEncode($this->parent);
			$url.="&icon=".RawUrlEncode($folder["icon"]);
			$url.="&name=".RawUrlEncode($folder["name"]);
			$url.="&path=".RawUrlEncode($folder["path"]);
			$url.="&pre=".RawUrlEncode($folder["pre"]);
			$url.="&returnpage=".RawUrlEncode($arReturnPage);
		} else {
			$url=$arReturnPage;
		}
		ldRedirect($url);
	} else {
		$this->call("show.error.phtml");
	}
?>