<?php
	$path=$this->store->make_path($this->parent, $data->path);
	$MAXLOOPCOUNT=10;
	if ($ARBeenhere[$arCallFunction][$path]<$MAXLOOPCOUNT) {
		$ARBeenHere[$arCallFunction][$path]+=1;
		if ($this->CheckConfig($arCallFunction, $arCallArgs)) {
			if ($path && $this->store->exists($path)) {
				$arResult=@current($this->get($path, $arCallFunction, $arCallArgs."&arShortCut=".RawUrlEncode($this->path)));
			} else {
				?>
					<html>
					<body bgcolor="white">
					<h1>Shortcut <?php echo $this->path; ?> points to nonexisting path: <?php echo $path; ?>.</h1>
					</body>
					</html>
				<?php
			}
		}
	} else {
		error("$data->path$arCallFunction called more than $MAXLOOPCOUNT times, recursive ShortCut $this->path?");
	}
?>