<?php
	$path=$this->store->make_path($this->parent, $data->path);
	$MAXLOOPCOUNT=10;
	if ($ARBeenhere[$arCallFunction][$path]<$MAXLOOPCOUNT) {
		$ARBeenHere[$arCallFunction][$path]+=1;

		if ($this->CheckConfig($arCallFunction, $arCallArgs)) {
			if ($path && $this->store->exists($path)) {
				$arCallArgs["arShortCut"] = $this->path;
				if (!is_array($ARCurrent->shortcut_redirect)) {
					$ARCurrent->shortcut_redirect = Array();
				}
				array_push($ARCurrent->shortcut_redirect, Array("src" => $this->path, "dest" => $path, "keepurl" => $this->data->keepurl));
					$arResult=current($this->get($path, $arCallFunction, $arCallArgs));
				array_pop($ARCurrent->shortcut_redirect);
			} else {
				$arResult=false;
				debug("pshortuct::default.phtml: ".sprintf($ARnls["err:shortcutnopath"],$this->path,$path));
			}
		}
		unset($ARConfig->cache[$this->data->path]->templates_path);
	} else {
		error( sprintf($ARnls["err:shortcutloopexceed"],$data->path, $arCallFunction,$MAXLOOPCOUNT,$this->path) );
	}
?>
