<?php
  /******************************************************************
   edit.object.data.save.phtml			   Muze Ariadne v2.0b
   ------------------------------------------------------------------

   no result.
 
  ******************************************************************/
  $vtype=$this->call("system.save.shortcut.phtml",$arCallArgs);
  if ($this->error) {
?>
  <font color="red"><?php
    echo $this->error;
  ?></font><p>
<?php
  } else {
?>
<script>
  if (window.opener) {
<?php
    if ($this->store->implements($vtype, 'pdir')) {
      $returnpage=$AR->dir->www."blue.html";
      $folder=$this->call("system.get.folder.phtml");
      if ($this->newobject) {
        $url=$AR->dir->www."setlink.php?do=add";
      } else {
        $url=$AR->dir->www."setlink.php?do=update";
      }
      $url.="&link=".RawUrlEncode($this->parent);
      $url.="&icon=".RawUrlEncode($folder["icon"]);
      $url.="&name=".RawUrlEncode($folder["name"]);
      $url.="&path=".RawUrlEncode($folder["path"]);
      $url.="&pre=".RawUrlEncode($folder["pre"]);
      $url.="&returnpage=".RawUrlEncode($returnpage);
?>
    if (window.opener.top.tree) {
      window.opener.top.tree.treeload.location='<?php echo $url; ?>';
    }
<?php
    }
?>
    window.opener.objectadded('<?php echo $this->type; ?>','<?php echo $nlsdata->name; ?>','<?php echo $this->path; ?>'); 
    window.close()
  } 
</script>
<?php
  }
?>