<?php
	/******************************************************************
	 edit.object.shortcut.save.phtml                       Muze Ariadne
	 ------------------------------------------------------------------

	 no result.
 
	******************************************************************/
	$vtype=$this->call("system.save.shortcut.phtml",$arCallArgs);
	if ($this->error) {
		?>
			<font color="red"><?php echo $this->error; ?></font><p>
		<?php
	} else {
		?>
			<script>
				if (window.opener) {
					<?php
						if ($this->store->implements($vtype, 'pdir')) {
							$folder=$this->call("system.get.folder.phtml");
							if ($this->arIsNewObject) {
								echo "	window.opener.top.tree.AddLinks('{$this->parent}','{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
							} else {
								echo "	window.opener.top.tree.UpdateLinks('{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
							}
						}
					?>
					if (window.opener.objectadded) {
						window.opener.objectadded('<?php echo $this->type; ?>','<?php echo $nlsdata->name; ?>','<?php echo $this->path; ?>'); 
					}
					window.close()
				} 
			</script>
		<?php
	}
?>