<?php
  if ($this->CheckConfig($arCallFunction, $arCallArgs) && $this->CheckLogin("edit")) {
    if ($next==$ARnls["save"]) { // save it. 
      include($this->store->code."templates/".$this->type."/save.phtml");
    } else if ($next==$ARnls["editoriginal"]) {
      Header("Location: ".$this->store->root.$data->path."edit.phtml?returnpage=".RawUrlEncode($returnpage));
    } else if ($next==$ARnls["cancel"]) {
      include($this->store->code."includes/cancel.phtml");
		$this->unlock();
    } else { // edit it.
      if ($this->lock()) {
        // object locked, show us by who
		$this->call("show.locks.phtml");
      } else {
        include($this->store->code."templates/".$this->type."/form.phtml");
      }
    }
  } 
?>