<?php
	/******************************************************************
	 edit.object.shortcut.phtml                            Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->code."widgets/wizard/code.php");

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		

		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}

		$custom="edit.object.shortcut.custom.phtml";

		$step1="edit.object.shortcut.form.phtml";
		$step2="edit.object.shortcut.language.phtml";
		$finish="edit.object.shortcut.save.phtml";
		$cancel="object.new.cancel.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["template"]=$cancel;
	 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["template"]=$step1;
		$wgWizFlow[$i]["prev"]=$i-1;
		$wgWizFlow[$i]["cancel"]=0;
		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["cancel"]=0;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$step2;
			if ($hascustomdata) {
				$wgWizFlow[$i]["next"]=$i-2;
			} else {
				$wgWizFlow[$i]["next"]=$i-1;
			}
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
			$wgWizFlow[$i]["cancel"]=0;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
		$wgWizFlow[$i]["cancel"]=0;


		$arLanguage=$this->getdata("arLanguage","none");
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($wgWizFlow[0]["current"]==2) { // =edit.object.language.phtml
			if ($arControl=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		include($this->store->code."widgets/wizard/classic.html");
	}
?>