<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.1
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.

  ******************************************************************/
  $ARCurrent->nolangcheck=true;
  $arResult = false;
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
		preg_match('/^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)/i', $arRequestedTemplate, $regs);
		$type=$regs[2];
		$function=$regs[3];
		$language=$regs[4];
		if ($data->config->pinp[$type][$function][$language]) {
			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				$arResult = true;
			}
		}
  }
?>
