<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$arResult=$this->call("ftp.objects.list.phtml");

		if ($this->CheckSilent("layout")) {
			$entry["grants"]["write"]=true;
		}

		if (($data->config->pinp) && is_array($data->config->pinp)) {
			while (list($type, $values)=each($data->config->pinp)) {
				while (list($function, $templatelist)=each($values)) {
							ksort($templatelist);
							reset($templatelist);
							while (list($language, $template)=each($templatelist)) {
									$entry["filename"]="$type.$function.$language";
									$entry["date"]=$this->lastchanged;
									$entry["type"]="template";
									$entry["size"]=0;
									$entry["grants"]["read"]=true;
									$arResult[]=$entry;
							}
				}
			}
		}
	}
?>
