<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$arResult=$this->call("ftp.objects.list.phtml");

		if ($this->CheckSilent("layout")) {
			$entry["grants"]["write"]=true;
		}

		if (($data->config->pinp) && is_array($data->config->pinp)) {
			foreach ($data->config->pinp as $type => $values) {
				foreach ($values as $function => $templatelist) {
							ksort($templatelist);
							reset($templatelist);
							foreach ($templatelist as $language => $template) {
									$entry["filename"]="$type.$function.$language";
									$entry["date"]=$this->lastchanged;
									$entry["type"]="template";
									$entry["size"]=0;
									$entry["grants"]["read"]=true;
									$arResult[]=$entry;
							}
				}
			}
		}
	}
?>
