<?php
	$result["date"]=$this->lastchanged;
	$result["size"]=0;
	$result["path"]=$this->path;
	$result["type"]="shortcut";
	$result["target"]=$this->data->path;

	if ($this->CheckLogin("read")) {
		$grants["read"]=true;
	} else {
		$grants["read"]=false;
	}

	if ($this->CheckLogin("add")) {
		$grants["write"]=true;
	} else {
		$grants["write"]=false;
	}

	$result["grants"]=$grants;

	$arResult=$result;
?>
