<?php
  $ARCurrent->nolangcheck=true;
  if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		preg_match('/^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)/i', $source_template, $regs);
		$default=$regs[1];
		$type=$regs[2];
		$function=$regs[3];
		$language=$regs[4];
		unset($regs);
		if ($data->config->pinp[$type][$function][$language]) {

			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				$file=$templates->read($this->id, $template);
				/* now we have to save our template */

				preg_match('/^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)/i', $target_template, $regs);
				$tdefault	= (isset($regs[1])) ? $regs[1] : $default;
				$ttype		= (isset($regs[2])) ? $regs[2] : $type;
				$tfunction	= (isset($regs[3])) ? $regs[3] : $target_template;
				$tlanguage	= (isset($regs[4])) ? $regs[4] : $language;

				$this->get($target, "system.save.layout.phtml", array(
														"template"	=> $file,
														"default"	=> $tdefault,
														"type"		=> $ttype,
														"function"	=> $tfunction,
														"language"	=> $tlanguage ));
				if (!$this->error) {
					$this->get($source, "system.delete.layout.phtml", 
										array(
											"type"		=> $type,
											"function"	=> $function,
											"language"	=> $language 
										));

				}
			}
		}

	$ARCurrent->ftp_error = $this->error;
  }
?>
