<?php
  if ($newtype) {
    $newdata=new object;
  } else {
    $newdata=$data; 
  }
  $newdata->path=$path;
  $path=$this->make_path($path);
  if (!isset(${$ARConfig->nls->default}) && !isset($newdata->{$ARConfig->nls->default})) { // default language for this path
	$error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
  } else {
    if (!$newdata->nls) {
      $newdata->nls=new object;
    }
    $newdata->nls->default=$this->nls;
    reset($AR->nls->list);
    while (list($key, $value)=each($AR->nls->list)) {
      if (isset(${$key})) {
        $nlsformdata=$$key;
        if (!$newdata->$key) {
          $newnlsdata=new object;
        } else {
          $newnlsdata=$newdata->$key;
        }
        if (!$nlsformdata["name"]) {
          $error=sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]);
        }
        $newnlsdata->name=$nlsformdata["name"];
        $properties["name"][]["value"]="'".AddSlashes($nlsformdata["name"])."'";
        $newdata->$key=$newnlsdata;
        $newdata->nls->list[$key]=$value;
      }
    }
  }
  if ($this->store->exists($path)) {
    $result=$this->get($path, "GetType.phtml");
    if ($result && $result[0]) {
      $vtype=$result[0];
      if ($this->store->implements($vtype, 'pdir')) {
        $saveinclude=$this->store->code."includes/save.dir.phtml";
      } else {
        $saveinclude=$this->store->code."includes/save.object.phtml";
      }
    } else {
      $error=sprintf($ARnls["err:nosupportforshortcuts"],$path);
    }
  } else {
    $error=sprintf($ARnls["err:wrongpath"],$path);
  }
  include($saveinclude);
?>