<?php
	// show all 'readable' data 
	if (!isset($nlsdata)) {
		$nls=$data->nls->default;
		$flag="<image src=\"".$AR->dir->images."nls/small/$nls.gif\" border=\"0\" alt=\"\">";
	}
	if ($folder=current($this->get($data->path, "system.get.folder.phtml"))) {
		$icon=$folder["icon"];
	} else {
		$icon="pdir";
	}
	if (!strstr($icon,"pshortcut/")) {
		$icon="pshortcut/".$icon;
	}
	if ($target) {
		echo "<a href=\"".$this->store->get_config("root").$this->path.$target."\"".
				 " onClick=\"if (top.tree) { top.View('$this->path','$target'); return false; }\">";
	} else {
		echo "<a href=\"".$this->store->get_config("root").$this->path."\"".
				 " onClick=\"if (top.tree) { top.View('$this->path'); return false; }\">";
	}
	echo '<img src="'.$AR->dir->images.'icons/'.$icon.'.gif" border="0" alt="">';
	if ($flag) { 
		echo $flag; 
	}
	if (!$this->CheckSilent("read")) {
		echo " <font color=\"#CCCCCC\"><b>$nlsdata->name</b></font>";
	} else {
		echo " <b>$nlsdata->name</b>";
	}
	echo "</a> -&gt; $data->path<br>\n";
?>
