<?php
  /*******************************************************************
	system.export.get.grants.phtml					Muze Ariadne v2.0b
	------------------------------------------------------------------
	Arguments: none
	Grant needed: add
	Global variables: none

	This template will add grants per object to the user/group 
	grants-list which will update the user objects
	when all objects are being imported.

  *******************************************************************/
	while (list($type, $type_val)=@each($this->data->grants)) {
		while (list($user,$grants)=@each($type_val)) {
			while (list($grant,)=@each($grants)) {
				//display("exporting grants [$type][$user][$this->path][$grant]\n");
				$ARCurrent->grants_list[$type][$user][$this->path][$grant]=1;
			}
		}
	}
?>