<?php
	require_once($this->store->get_config("code")."modules/mod_unicode.php");
	$name=unicode::utf8convert(trim($nlsdata->name));
	$path=$this->store->make_path($this->parent, $data->path);
	if ($AR->user && !$this->CheckSilent("read")) {
		$arResult["pre"]="<font color='#CCCCCC'>$flag";
	} else {
		$arResult["pre"]=$flag;
	}
	if ($path!=$this->path) {
		$folder=$this->get($path,"system.get.folder.phtml");
		$arResult["icon"]=$this->call('system.get.icon.small.phtml');
/*
		if ($folder && $folder[0]["icon"]) {
			$arResult["icon"]=$folder[0]["icon"];
		} else {
			$arResult["icon"]='pdir';
		}
		if (!strstr($arResult["icon"],"pshortcut/")) {
			$arResult["icon"]="pshortcut/".$arResult["icon"];
		}
*/
	}
	$arResult["name"]=$name;
	$arResult["path"]=$this->path;
	$arResult["shortcut"]=$path;
?>
