<?php
	/* FIXME: what to do if the shortcut points to another shortcut? */
	/******************************************************************
	 system.save.shortcut.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	if (
			(
				(
					$this->arIsNewObject &&
					( $parentobj = current($this->get($this->parent, "system.get.phtml")) ) &&
					$parentobj->CheckLogin("add", $this->type)
				) ||
				( !$this->arIsNewObject && $this->CheckLogin("edit") )
			) &&
			$this->CheckConfig()
		) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new object;
		}


		$this->data->path=$this->getdata("path","none");
		$path=$this->store->make_path($this->parent, $this->data->path);

		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			$count=0;
			while (list($key, $value)=each($AR->nls->list)) {

				if ($name=$this->getdata("name",$key)) {
					// (if user selects a language but enters nothing and then submits, $$key will be set, but all values empty)
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					$newnlsdata->name=$this->getdata("name",$key);
					$properties["name"][$count]["value"]=$newnlsdata->name;
					$properties["name"][$count]["nls"]=$key;
					$properties["text"][$count]["value"]=$newnlsdata->name;
					$properties["text"][$count]["nls"]=$key;
					$count++;
					$newnlsdata->summary=$this->getdata("summary",$key);
					$properties["text"][$count]["value"]=$newnlsdata->summary;
					$properties["text"][$count]["nls"]=$key;

					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else {
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->nls->list[$key]);
					}
				}
			}
		}

		$this->data->keepurl = $this->getdata("keepurl");

		if ($path == $this->path) {
			$this->error=sprintf($ARnls["err:nosupportforshortcuts"],$path);
		} else
		if ($this->store->exists($path)) {
			$result=$this->get($path, "system.get.type.phtml");
			if ($result && $result[0]) {
				$vtype=$result[0];
				$arResult=$vtype;
				$properties["references"][0]["path"] = $this->data->path;
			} else {
				$this->error=sprintf($ARnls["err:nosupportforshortcuts"],$path);
			}
		} else {
			$this->error=sprintf($ARnls["err:wrongpath"],$path);
		}
		if (!$this->error) {
			$this->vtype=$vtype;
			$this->save($properties, $vtype);

			global $cache_config;
			$cachestore=new cache($cache_config);
			$cachestore->onObjectSaved($this->id);
		}
	}
?>
