<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
        $path=$this->store->make_path($this->parent, $data->path);
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<div class="border">
  <span class="hoverbutton" style="float: right"><a href="#" onClick="top.hidetree(); return false;"><img src="<?php echo $AR->dir->images; ?>tree/x.gif" border="0" height="18" width="18" vspace="2"></a></span>
  <img src="<?php echo $AR->dir->images; ?>tree/wait.gif" hspace="2" width="15" height="15" style="float: left"> Loading...  
  <?php
		flush();
		if ($folder=$this->call("system.get.folder.phtml")) {
			?>
				<script>
					window.parent.init("<?php echo AddCSlashes($folder["icon"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["name"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["path"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["pre"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["shortcut"], ARESCAPE); ?>");
					node=window.parent.root;
					node.status="Open";
					<?php
						$criteria["object"]["parent"]["="]="'".AddSlashes($path)."'";
						$criteria["object"]["implements"]["="]="'pdir'";
						if ($folders=$this->find($path,$criteria,"system.get.folder.phtml",$args)) {
							while (list($key, $folder)=each($folders)) {
								?>
									node.add("<?php echo AddCSlashes($folder["icon"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["name"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["path"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["pre"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["shortcut"], ARESCAPE); ?>");
								<?php
							}
						}
					?>
					window.parent.Draw();
				</script>
			<?php
		} else {
			echo "Error initializing tree, contact system administrator.";
		}
  ?>
</div>
</body>
</html>
<?php	 
	} 
?>