<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
        $path=$this->store->make_path($this->parent, $data->path);
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<table width="100%">
<tr>
	<td valign="middle"><img src="<?php echo $AR->dir->images; ?>tree/wait.gif" align="left" hspace="2" height="15" width="15">Loading...</td>
	<td align="right"><img align="right" src="<?php echo $AR->dir->images; ?>tree/x.gif" vspace="1" height="18" width="18"></td>
</tr>
</table>
<?php
		flush();
		if ($folder=$this->call("system.get.folder.phtml")) {
			?>
				<script>
					window.parent.init("<?php echo AddSlashes($folder["icon"]); ?>",
							"<?php echo AddSlashes($folder["name"]); ?>",
							"<?php echo AddSlashes($folder["path"]); ?>",
							"<?php echo AddSlashes($folder["pre"]); ?>");
					node=window.parent.root;
					node.status="Open";
					<?php
						$criteria["object"]["parent"]["="]="'".AddSlashes($path)."'";
						$criteria["object"]["implements"]["="]="'pdir'";
						if ($folders=$this->find($path,$criteria,"system.get.folder.phtml",$args)) {
							while (list($key, $folder)=each($folders)) {
								?>
									node.add("<?php echo AddSlashes($folder["icon"]); ?>",
											 "<?php echo AddSlashes($folder["name"]); ?>",
											 "<?php echo AddSlashes($folder["path"]); ?>",
											 "<?php echo AddSlashes($folder["pre"]); ?>");
								<?php
							}
						}
					?>
					window.parent.Draw();
				</script>
			<?php
		} else {
			echo "Error initializing tree, contact system administrator.";
		}
?>
</body>
</html>
<?php	 
	} 
?>