<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body onLoad="doload()" class="border">
  <span class="hoverbutton" style="float: right"><a href="#" onClick="top.hidetree(); return false;"><img src="<?php echo $AR->dir->images; ?>tree/x.gif" border="0" height="18" width="18" vspace="2"></a></span>
  <?php
	$this->store->accessdenied='Access Denied';
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$path=$this->store->make_path($this->parent, $data->path);
      ?>
		<script>
			function doload() {
				node=parent.Nodes[<?php echo $node; ?>];
				<?php
					flush();
					$criteria["object"]["parent"]["="]="'".AddSlashes($path)."'";
					$criteria["object"]["implements"]["="]="'pdir'";
					if ($folders=$this->find($path,$criteria,"system.get.folder.phtml",$args)) {
						while (list($key, $folder)=each($folders)) {
							?>
								node.add("<?php echo AddSlashes($folder["icon"]); ?>",
										 "<?php echo AddSlashes($folder["name"]); ?>",
										 "<?php echo AddSlashes($folder["path"]); ?>",
										 "<?php echo AddSlashes($folder["pre"]); ?>");
							<?php
						}
					}
				?>
				parent.Draw();
			} 
		</script>
        <img src="<?php echo $AR->dir->images; ?>tree/wait.gif" hspace="2" width="15" height="15" style="float: left"> Loading...  
      <?php 
	}
  ?>
</body>
</html>
