<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body onLoad="load()">
<?php
	$this->store->accessdenied='<table width="100%"><tr><td valign="middle">Access Denied</td><td align="right"><img align="right" src="'.$AR->dir->images.'tree/x.gif" vspace="1"></td></tr></table>';
	if ($this->CheckLogin("read")) {
		$path=$this->store->make_path($this->parent, $data->path);
		?>
			<table width="100%">
			<tr>
				<td valign="middle"><img src="<?php echo $AR->dir->images; ?>tree/wait.gif" align="left" hspace="2">Loading...</td>
				<td align="right"><img align="right" src="<?php echo $AR->dir->images; ?>tree/x.gif" vspace="1"></td>
			</tr>
			</table>
			<script>
				function load() {
					node=parent.Nodes[<?php echo $node; ?>];
					<?php
						flush();
						$criteria["object"]["parent"]["="]="'".AddSlashes($path)."'";
						$criteria["object"]["implements"]["="]="'pdir'";
						if ($folders=$this->find($path,$criteria,"system.get.folder.phtml",$args)) {
							while (list($key, $folder)=each($folders)) {
								?>
									node.add("<?php echo AddSlashes($folder["icon"]); ?>",
											 "<?php echo AddSlashes($folder["name"]); ?>",
											 "<?php echo AddSlashes($folder["path"]); ?>",
											 "<?php echo AddSlashes($folder["pre"]); ?>");
								<?php
							}
						}
					?>
					parent.Draw();
				} 
			</script>
		<?php
	}
?>
</body>
</html>