<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.
 
  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig($arCallFunction, $arCallArgs) ) {
?>
<html>
<head>
	<TITLE><?php echo $nlsdata->name; ?></TITLE>
<script>
  function objectadded() {
    document.location=document.location;
  }
</script>
</head>
<body scroll="no" bgcolor="white" onLoad="top.LoadingDone();">
<?php
  include($this->store->code."widgets/menu/menu.phtml");
?>
<font face="helvetica, sans-serif" size="2">
<h3><?php echo $nlsdata->name; ?>.</h3>
<?php
  $path=$this->store->make_path($this->parent, $data->path);
  $this->ls($path,"show.phtml");
?>
</font>
</div>
</body>
</html>
<?php
  }
?>