<?php
	/******************************************************************
	 view.phtml                                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays the management view of the object, with
	 pulldown menu's etc.

	 no result.

 ******************************************************************/

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title><?php echo $data->$nls->name; ?></title>

<link href="<?php echo $AR->dir->styles; ?>default.css" rel="StyleSheet" type="text/css">

<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/menu/functions.js"
        type='text/javascript'>
</script>	

<script>
	tree=1;
	function View(path) {
		document.location.href='<?php echo $this->store->root; ?>'+path+'view.phtml';
	}
	function LoadingDone() {
	}
</script>
</head>
<body bgcolor="white" onLoad="top.LoadingDone();">
<?php

	include($this->store->code."widgets/menu/menu.phtml");

	$this->call("manage.html",'view=true');  //toggles the links in the listing- true means 'view.phtml' will get added.
?>

</body>
</html>
<?
	}
?>