<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

	if (!$arLanguage) {
		$arLanguage=$nls;
	}
	if ($data->$arLanguage) {
		$nlsdata=$data->$arLanguage;
	}

	$permcheck = array();
	$permcheck[] = "edit";
	$permcheck[] = "config";
	$permcheck[] = "delete";
	$permcheck[] = "layout";
	
	$disabledItems="";
	if(!$this->implements("pshortcut") || !$this->CheckSilent("edit"))
		$disabledItems.= "normalCMshortcut;";
	if(!$this->CheckSilent("edit"))
		$disabledItems.= "normalCMedit;";
	if(!$this->CheckSilent("delete"))
		$disabledItems.= "normalCMdelete;normalCMrename;";
	if(!$this->CheckSilent("read"))
		$disabledItems.= "normalCMexplore;normalCMviewweb;normalCMcopy;normalCMlink;";
	$folder=$this->call("system.get.folder.phtml");

	$server_name=eregi_replace("^[htps:/]*/","",$AR->host);
        if ($HTTP_SERVER_VARS["HTTP_HOST"]!=$server_name) {
                $fullObjectpath = $this->store->root.$this->path;
        } else {
                $fullObjectpath = $this->make_url();
        }
?>

<div class='object'><nobr><a contextmenu="normalContextMenu" disableditems="<?php echo $disabledItems; ?>"
	href="#" class="unselectedItem" onClick="selectItem(this);" onDblClick="top.View(this.getAttribute('path'))" path="<?php echo $this->path; ?>" fullPath="<?php echo $fullObjectpath ?>"><img 
	width="20" height="20" src="<?php echo $AR->dir->images; ?>icons/<?php echo $folder['icon']; ?>.gif" 
	alt="<?php echo $this->path; ?>" border="0"> <?php
		if (strlen($nlsdata->name)>32) {
			$name=substr($nlsdata->name,0, 32)."...";
		} else {
			$name=$nlsdata->name;
		}
		if (!$this->CheckSilent("read")) {
			echo "<font color=\"#CCCCCC\">$name</font>";
		} else {
			echo "$name";
		}
	?></a></nobr></div>
