<?php
  /******************************************************************
   browselist.phtml				   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by browse widget  (from file 'ariadne/widgets/browse/index.phtml')
   Arguments: none
   Grant needed: "read"
   Interface/Widget: browse
   Global variables: $AR->dir->www

   Displays browse information of the current object and a list of 
   objects (calling 'browseitem.phtml') under the current object 
   (it's children). 

   This script should only be used by the browse widget, as it
   assumes the existance of the browse frameset. It will set the path
   form input field of the path frame to the path of the current object.  

   No return value.

  ******************************************************************/
  if ($this->CheckLogin("read")) {
?>
<head>
<script>
function inittop() {
  top.path.SetPath('<?php echo ereg_replace("'","\\'",$this->path); ?>');
}

function GoUp() {
    document.location.href='<?php
    echo $this->store->root.$this->store->make_path($this->path, "..").'browselist.phtml';
  ?>';
}

</script>
</head>
<body bgcolor="white" onLoad="inittop();">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
  <td><img src="<?php echo $AR->dir->images; ?>icons/<?php echo $this->type; ?>.gif"></td>
  <td colspan="2" valign="middle" width="100%"><font face="verdana,helvetica,sans-serif" size="-1"><?php 
    echo $nlsdata->name; ?></font></td>
</tr>
<?php $this->ls(".", "browseitem.phtml"); ?>
</table>
</font>
</body>
<?php
  }
?>