<?php
  /******************************************************************

  ******************************************************************/
  if ($this->CheckSilent("read")) {
?>
<script>
  function settime(name, form) {
    time=form[name+"_hour"].options[form[name+"_hour"].selectedIndex].value*3600+
         form[name+"_minute"].options[form[name+"_minute"].selectedIndex].value*60;
    form[name].value=time;
  }
</script>
<table border="0" width="90%">
<tr>
  <td>
    <?php 
      $arLanguage=$this->getdata("arLanguage","none");
      if (!$arLanguage) {
       $arLanguage=$ARConfig->nls->default;
      }
      $selectednls=$arLanguage;
      $selectedlanguage=$ARConfig->nls->list[$arLanguage];
      $flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";

    function input_time($name,$time) {
        if (!$time) {
            $date=getdate(time());
            $hours=$date["hours"]; $mins=$date["minutes"];
			$time=$hours*3600+$minutes*60;
        } else {
            $hours=floor($time/3600);
            $mins=floor(($time-($hours*3600))/60);
        }
        $mins=floor($mins/5)*5;

        echo "<input type=\"hidden\" name=\"$name\" value=\"$time\">";
        echo "<nobr><select name=\"".$name."_hour\" onChange=\"settime('$name',this.form);\">\n";
        for ($i=0; $i<=23; $i++) {
            if (strlen($i)<2) $i="0".$i;
            if ($i!=$hours)
                echo "<option value=\"$i\">$i</option>\n";
            else
                echo "<option value=\"$i\" selected>$i</option>\n";
        }

        echo "</select><b>:</b>\n";
        echo "<select name=\"".$name."_minute\" onChange=\"settime('$name',this.form);\">\n";
        for ($i=0; $i<=59; $i=$i+5) {
            if (strlen($i)<2) $i="0".$i;
            if ($i!=$mins)
                echo "<option value=\"$i\">$i</option>\n";
            else
                echo "<option value=\"$i\" selected>$i</option>\n";
        }
        echo "</select></nobr>\n";
    }
    ?>
    <fieldset id="selectstart">
    <legend><?php echo $ARnls["start"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          <span class="required"><?php echo $ARnls["date"]; ?></span>
        </td><td>
          <span class="required"><?php echo $ARnls["time"]; ?></span>
        </td>
      </tr><tr>
        <td>
          <?php
    $startdateformatted=$this->getdata("startdateformatted","none");
    $enddateformatted=$this->getdata("enddateformatted","none");
    if ($startdateformatted) {
      $temp=explode("-",$startdateformatted);
      $startdate=mktime(0,0,0,$temp[1],$temp[0],$temp[2]);
    } else {
      $startdate=$this->getdata("startdate","none");
    }
    if ($enddateformatted) {
      $temp=explode("-",$enddateformatted);
      $enddate=mktime(0,0,0,$temp[1],$temp[0],$temp[2]);
    } else {
      $enddate=$this->getdata("enddate","none");
    }
    if (!$startdate) {
      $startdate=time();
    }
    if ($enddate<=$startdate) {
        $enddate = $startdate;
    }

	$wgDateName="startdate";
	$wgDate=$startdate;
	if (!$wgDate) {
		$temp=getdate(time());
		$wgDate=mktime(0,0,0,$temp["mon"],$temp["mday"],$temp["year"]);
	}
	$startdate=$wgDate;
	include($this->store->code."widgets/date/js.html");
	include($this->store->code."widgets/date/form.button.html");

?>
        </td><td>
<?php input_time("starttime",$this->getdata("starttime","none")); ?>
        </td>
      </tr>
      </table>
    </fieldset>

    <fieldset id="selectend">
    <legend><?php echo $ARnls["end"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          <?php echo $ARnls["date"]; ?>
        </td><td>
          <?php echo $ARnls["time"]; ?>
        </td>
      </tr><tr>
        <td>
          <?php
$wgDateName="enddate";
$wgDate=$enddate;
include($this->store->code."widgets/date/js.html");
include($this->store->code."widgets/date/form.button.html");
?>
        </td><td>
<?php input_time("endtime",$this->getdata("endtime","none")); ?>
        </td>
      </tr>
      </table>
    </fieldset>

    <fieldset id="scenarioeffect">
    <legend><?php echo $ARnls["effect"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
<?php
        $scenario = $this->getdata("scenario","none"); 
        if( $this->exists($scenario) ) $this->get($scenario,"show.effect.phtml");
?>
        </td>
      </tr>
      </table>
    </fieldset>


  </td>
</tr>
</table>
<?php
  }
?>