<?php
	/******************************************************************
	 edit.object.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->AR_implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}

		$custom="edit.object.data.custom.phtml";

		include($this->store->get_config("code")."widgets/wizard/code.php");

		$scenario="edit.object.data.scenario.phtml";
		$datetime="edit.object.data.datetime.phtml";
		$summary="edit.object.data.form.phtml";
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $finish;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["scenario"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/scenario.png";
		$wgWizFlow[$i]["template"]=$scenario;
		$wgWizFlow[$i]["nolang"]=true;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["date"]."&nbsp;/&nbsp;".$ARnls["time"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/schedule.png";
		$wgWizFlow[$i]["template"]=$datetime;
		$wgWizFlow[$i]["nolang"]=true;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["summary"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$summary;

		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$wgWizFlow = $this->call("user.wizard.edit.html", Array("wgWizFlow" => $wgWizFlow));

		$wgWizControl=$this->getdata("wgWizControl","none");
		$wgWizCurrent=$this->getdata("wgWizCurrent","none");

		if (!$ARCurrent->arTypeIconsSmall[$this->type]) {
			// FIXME: for performance the check above is necessary, but
			// it does make it possible to get the wrong icon...
			// get typetree to get the correct icon
			$this->call('typetree.ini');
		}
		$icon=$ARCurrent->arTypeIcons[$this->type]['default'];
		if (!$icon) {
			$dotPos=strpos($this->type, '.');
			if (false!==$dotPos) {
				$realtype=substr($this->type, 0, $dotPos);
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
			} else { 
				$realtype=$this->type;
			}
			if (!$icon) {
				$icon=$AR->dir->images."icons/".$realtype.".gif";
			}
			$name=$ARCurrent->arTypeNames[$this->type];
		} else {
			$name=$ARCurrent->arTypeNames[$this->type];
		}
		$arResult=$icon;

		$wgWizTitle=$ARnls["edit"]." ".$name;
		$wgWizHeader=$wgWizTitle.'<img src="'.$icon.'" alt="" hspace="4" align="absmiddle">';
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>
