<?php
	/******************************************************************
	 edit.object.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$scenario="edit.object.data.scenario.phtml";
		$datetime="edit.object.data.datetime.phtml";
		$summary="edit.object.data.form.phtml";
		$language="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";


		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["scenario"];
		$wgWizFlow[$i]["template"]=$scenario;
		$wgWizFlow[$i]["next"]=$i+1;
		$wgWizFlow[$i]["save"]=$i+3+$customoffset+$saveoffset;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["date"]."&nbsp;/&nbsp;".$ARnls["time"];
		$wgWizFlow[$i]["template"]=$datetime;
		$wgWizFlow[$i]["next"]=$i+1; 
		$wgWizFlow[$i]["prev"]=$i-1; 
		$wgWizFlow[$i]["save"]=$i+2+$customoffset+$saveoffset;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["summary"];
		$wgWizFlow[$i]["template"]=$summary;
		$wgWizFlow[$i]["prev"]=$i-1;

		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			$wgWizFlow[$i]["next"]=$i-1-$customoffset;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
		
		$arLanguage=$this->getdata("arLanguage","none");
		if ($wgWizFlow[0]["current"]=="language") { // =edit.object.language.phtml
			$arControl=$this->getdata("wgWizControl","none");
			if (wgWizGetAction($arControl)=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		global $HTTP_POST_VARS;
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		// now fool the wizard keepvars function to use the new language
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;

		$wgWizControl=$this->getdata("wgWizControl","none");
		$wgWizCurrent=$this->getdata("wgWizCurrent","none");
		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>