<?php
  // show image select box with browse button
  
?>
<html>
<head>
<title>Picture</title>
<style>
TD {
	FONT: 8pt sans-serif;
}
INPUT {
	FONT: 8pt sans-serif;
    MARGIN: 2px 4px 2px 4px;
    WIDTH: 50px;
}
SELECT {
	FONT: 8pt sans-serif;
    MARGIN: 2px 4px 2px 4px;
    WIDTH: 75px;
}
BODY 	{
	FONT: 8pt sans-serif;
	BORDER: 0;
	BACKGROUND-COLOR: buttonface;
}
.button {
    width:75px;
}
.alternate {
    width: 235px;
}
.wgBrowseInput {
    width: 150px;
}
.wgBrowseButton {
    width: 75px;
}
.fieldset {
    height: 60px;
}
.layout {
    width: 75px;
}
</style>
</head>
<body scroll="no">
<script>
  if (document.all) {
    window.innerHeight=document.body.clientHeight;
    window.innerWidth=document.body.clientWidth;
  }  
</script>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<form method="post" name="PictureForm" 
  action="edit.object.data.page.image.save.phtml"
  onSubmit="return checksubmit();">
<tr>
  <td>Picture&nbsp;Source:</td>
  <td><?php
    include($this->store->code."widgets/browse/js.html");
    include($this->store->code."widgets/browse/form.html");
  ?></td>
  <td><input type="submit" name="ok" value="OK" class="button"></td>
</tr><tr>
  <td>Alternate&nbsp;Text:</td>
  <td><input type="text" name="alt" value="" size="20" class="alternate"></td>
  <td><input type="button" name="cancel" value="Cancel" onClick="window.close();" class="button"></td>
</tr><tr>
  <td colspan="2">
    <table><tr><td>
    <fieldset id="layout">
    <legend>Layout</legend>
    <table class="fieldset" align="left">
      <tr>
        <td>Alignment:</td>
        <td><select name="alignment" class="layout">
          <option value="">Not Set</option>
          <option>Left</option>
          <option>Right</option>
          <option>Texttop</option>
          <option>Absmiddle</option>
          <option>Baseline</option>
          <option>Absbottom</option>
          <option>Bottom</option>
          <option>Middle</option>
          <option>Top</option>
        </select></td>
      </tr><tr>
        <td>Border&nbsp;Thickness:</td>
        <td><input type="text" name="border" value="" size="6" class="layout"></td>
      </tr>
    </table>
    </fieldset>
    </td><td>
    <fieldset id="spacing">
    <legend>Spacing</legend>
    <table class="fieldset" align="left">
      <tr>
        <td>Horizontal:</td>
        <td><input type="text" name="hspace" value="" size="6"></td>
      </tr><tr>
        <td>Vertical:</td>
        <td><input type="text" name="vspace" value="" size="6">
      </tr>
    </table>
    </fieldset>
    </td></tr></table>
  </td>
</tr>
</form>
</table>
</body>
</html>
