<?php
  /******************************************************************
   edit.page.save.phtml				   Muze Ariadne v2.1
   ------------------------------------------------------------------
   Arguments: $nls[page]
   Grant needed: edit
   Widget: htmledit
   Global variables: none

   No result.

  ******************************************************************/
  // FIXME: use nls text
  if ($this->CheckLogin("edit") && $this->CheckConfig()) {
    $this->call("system.save.page.phtml", $arCallArgs);
?>
<hmtl>
<head><title>Saving HTML Page</title></head>
<body bgcolor="#CCCCCC"><font face="arial,helvetica,sasn-serif">
<?php
    if (!$this->error) {
      echo "Page saved";
?>
<script>
  window.setTimeout('window.close()',500);
</script>
<?php
    } else {
      echo "Error: $this->error";
    }
?>    
</font>
<form>
<input type="button" name="ok" value=" OK " onClick="window.close();">
</form>
</body>
<?php
  }
?>