<?php
  /******************************************************************

  ******************************************************************/
  if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
  <td>
    <?php 
      $arLanguage=$this->getdata("arLanguage","none");
      if (!$arLanguage) {
       $arLanguage=$ARConfig->nls->default;
      }
      $selectednls=$arLanguage;
      $selectedlanguage=$ARConfig->nls->list[$arLanguage];
      $flag="<img align=\"right\" src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
    ?>
    <fieldset id="setarticle">
    <legend><?php echo $ARnls["article"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          <?php echo $flag.$ARnls["title"]; ?>
        </td>
      </tr><tr>
        <td>
          <input type="text" name="<?php echo $selectednls."[title]"; ?>" 
            size="35" value="<?php $this->showdata("title", $selectednls); ?>">
        </td>
      </tr><tr>
        <td>
          <?php echo $ARnls["text"]; ?>
        </td>
      </tr><tr>
        <td>
          <?php
            $wgHTMLEditName="page";
            $wgHTMLEditLanguage=$arLanguage;
            $wgHTMLEditContent=$this->getdata("page",$arLanguage);
            $wgHTMLEditTitle=$this->getdata("title",$selectednls);
            include($this->store->code."widgets/htmledit/js.html");
            include($this->store->code."widgets/htmledit/form.html");
          ?>
        </td>
      </tr>
      </table>
    </fieldset>
  </td>
</tr>
</table>
<script>
  window.onload=init;
  function init() {
    document.wgWizForm["<?php echo $selectednls; ?>[title]"].focus();
  }
</script>
<?php
  }
?>