<?php
  /******************************************************************
   GetForDisplay.phtml				Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by: multiple
   Arguments: none
   Grant needed: none
   Interface/Widget: all
   Global variables: none
   
  ******************************************************************/

  if (isset($nlsdata)) {
    $ARCurrent->priority[$this->path]=$this->data->priority-(abs( ($this->data->startdate + $this->data->starttime)-time() )/60);
    $ARCurrent->article[$this->path]=$this;
  }
?>