<?php
  $MAX_TITLE_LENGTH=40;


  if ($newtype) {
    $newdata=new object;
    $publishpath=$this->path;
  } else { 
    $newdata=$data;
    $publishpath=$this->parent;
  }
  $displays=$this->get($newscenario, "Get.phtml");
  $newdata->priority=$displays[0]->data->priority;
  $displays=$displays[0]->data->display; // we only need the display array

  if (!isset(${$ARConfig->nls->default}) && !isset($newdata->{$ARConfig->nls->default})) { // default language for this path
    $error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
  } else {
    if (!$newdata->nls) {
      $newdata->nls=new object;
    }
    $newdata->nls->default=$ARConfig->nls->default;
    reset($AR->nls->list);
    while (list($key, $value)=each($AR->nls->list)) {
      if (isset(${$key})) {
        $nlsformdata=$$key;
        if (!$newdata->$key) {
          $newnlsdata=new object;
        } else {
          $newnlsdata=$newdata->$key;
        }
        if (strlen($nlsformdata["name"])>$MAX_TITLE_LENGTH) {
          $error=sprintf($ARnls["err:titlelength"], $MAX_TITLE_LENGTH);
          break;
        } else  {
          $newnlsdata->name=$nlsformdata["name"];
          $properties["name"][]["value"]="'".AddSlashes($nlsformdata["name"])."'";
        }
   
        $newnlsdata->summary=$nlsformdata["summary"];
        $properties["text"][]["value"]="'".AddSlashes(substr($nlsformdata["summary"],0,255))."'";
        $newnlsdata->page=urldecode($nlsformdata["page"]);
        $newdata->$key=$newnlsdata;
        $newdata->nls->list[$key]=$value;
      }
    }
  }

  $newdata->scenario=$newscenario;

  $newdata->startdate=$startdate;
  $newdata->enddate=$enddate;
  $newdata->starttime=($starttime_hour*3600)+($starttime_minute*60);
  $newdata->endtime=($endtime_hour*3600)+($endtime_minute*60);

  if (!$newdata->published) {
    $newdata->published=time();
  }
  if (!$newdata->author) {
	$newdata->author=$AR->user->data->name;
	$newdata->author_path=$AR->user->path;
  }

  $i=0;
  reset($displays);
  while ((list($display,$val)=each($displays))) {
	$scenario_start=$newdata->startdate+$newdata->starttime +($val["start"]*3600*24);
  	$scenario_end=$newdata->enddate+$newdata->endtime+($val["end"]*3600*24);
  	$newdata->sstart[$display]=$scenario_start;
        $newdata->send[$display]=$scenario_end;
  	$properties["article"][$i]["start"]=$scenario_start;
  	$properties["article"][$i]["end"]=$scenario_end;
  	$properties["article"][$i]["display"]="'".$display."'";
  	$i++;
  }
  $properties["published"][0]["value"]=$newdata->published;
  include($this->store->code."includes/save.object.phtml");
?>