<?php
  if (!isset($nlsdata)) {
    $nls=$data->nls->default;
    $flag="<img src=\"".$AR->dir->images."nls/small/$nls.gif\" border=\"0\" alt=\"\">";
  }
  // show all 'readable' data 
  if ($target) {
    echo "<a href=\"".$this->store->root.$this->path.$target."\"".
         " onClick=\"if (top.tree) { top.View('$this->path','$target'); return false; }\">";
  } else {
    echo "<a href=\"".$this->store->root.$this->path."\"".
         " onClick=\"if (top.tree) { top.View('$this->path'); return false; }\">";
  }
?>
<img src="<?php 
  echo $AR->dir->images; ?>icons/<?php echo $this->type; ?>.gif" alt="[view]"
  border="0">
<?php
    if ($flag) { echo $flag; }
    if (!$this->CheckSilent("read")) {
      echo " <font color=\"#CCCCCC\"><b>$nlsdata->name</b></font>";
    } else {
      echo " <b>$nlsdata->name</b>"; 
    }
?></a> <?php 
    echo "<i>".sprintf($ARnls["publisheddata"],$data->author,
      date("d-m-Y",$data->published))."</i>"; 
?><br>
