<?php
	/******************************************************************
	 system.get.article-by-priority                        Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none
	 
	******************************************************************/
	if (isset($nlsdata)) {
		if (!$ARCurrent->idlist[$this->id]) {
			$ARCurrent->priority[$this->path]=$this->data->priority-(abs( ($this->data->startdate + $this->data->starttime)-time() )/60);
			$ARCurrent->article[$this->path]=$this;
			$ARCurrent->idlist[$this->id]=$this->path;
		}
	}
?>