FROM php:8.4-apache
LABEL maintainer="yvo@muze.nl"
RUN docker-php-ext-install mysqli
#RUN docker-php-ext-install mbstring
RUN docker-php-ext-install exif
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y subversion
RUN apt-get install -y tidy
RUN apt-get install -y imagemagick
RUN apt-get install -y poppler-utils