<?php

class session {

	function session($session_config, $id=0) {
        debug("session([array],$id)","store");
		// init session store
		$this->sessionstore=new mysqlstore($session_config["root"], $session_config);

		$this->timeout=$session_config["timeout"];

		if ((!$id) || (!$this->sessionstore->exists("/$id/")))  { 
			// generate new id
			srand((double)microtime()*1000000);
			do { 
				// 3 bytes id
				$genid=chr(rand(1,255)).chr(rand(1,255)).chr(rand(1,255));
				// replace all slashes with "0" 
				$id=strtr(base64_encode($genid),"/+","01");
			} while ($this->sessionstore->exists("/".$id."/"));
			// save new session object
			$this->data=new object;
			$this->id=$id;
			$this->save();
		} else { // retrieve session
			$result=$this->sessionstore->call("get.data.phtml","",$this->sessionstore->get("/$id/"));
			debug("session found ($result) in database");
			$this->id=$id;
			$this->data=$result[0];
		}
		$this->put("ARSessionId",$this->id);
        debug("session: end","all");
	}

	function put($varname, $value) {
		debug("session->put($varname,$value)","store");
		$this->data->$varname=$value;
        debug("session->put: end","all");
	}

	function get($varname) {
        debug("session->get($varname)","store");
		return $this->data->$varname;
        debug("session->get: end","all");
   
	}

	function save($id=0) {
        debug("session->save($id)","store");
		if (!$id) { $id=$this->id; } else { $this->id=$id; }
		// store session data
		$this->sessionstore->save("/$id/","psession",$this->data);
        debug("session->save: end","all");
	}


	function suspend() {
		debug("session->suspend()","store");
		$this->save();
		$this->sessionstore->close();
		$this->id=0;
        debug("session->suspend: end","all");
		return ldSetSession();      
	}
 
	function kill() {
		debug("session->kill()","store");
		// remove session data from store
		$this->sessionstore->purge("/".$this->id."/");
		$this->sessionstore->close();
		$this->id=0;
		debug("session->kill: end","all");
		return ldSetSession();
	}
}
?>