<?PHP
	/**************************************************************************
	File Store Module - SVN extension
	---------------------------------------------------------------------------

	This module is used to add SVN support to the filestore. Since the
	filestore handles all the nodes and the directory structure, directory
	support is disabled. If needed, recursion into directories should be
	done from within Ariadne, not using default SVN functionality.

	All SVN commands are prepended with "svn_" to prevent collisions with
	mod_filestore and php.

	svn commands:
	connect($id, $repository, $username, $password); -> returns $svn.

	svn_add($svn, $name)
	svn_blame($svn, $name)
	svn_cat($svn, $name)
	svn_checkout($svn, $repository, $revision)
	svn_cleanup($svn)
	svn_commit($svn, $comment, $fileinfo)
	svn_delete($svn, $name, $comment)
	svn_diff($svn, $name)
	svn_export($svn, $repository, $revision)
	svn_import($svn, $repository, $comment)
	svn_info($svn, $name)
	svn_list($svn)
	svn_log($svn, $name)
	svn_propdel($svn, $propkey, $name)
	svn_propget($svn, $propkey, $name)
	svn_proplist($svn, $name)
	svn_propset($svn, $propkey, $propvalue, $name)
	svn_resolved($svn, $name)
	svn_revert($svn, $name)
	svn_status($svn, $name)
	svn_update($svn, $name, $revision)

	Custom commands:
	svn_accept_cert($svn, $repository)
	svn_checkunder($svn, $repository, $revision)
	svn_mkdirs($svn, $repository)
	svn_rinfo($svn, $repository, $name)
	svn_rpropget($svn, $repository, $propkey, $name)
	
	The following functions have not yet been implemented:
	svn_copy
	svn_merge
	svn_mkdir
	svn_move
	svn_switch

	Copyright Muze 2007;
	Written by Yvo Brevoort

	**************************************************************************/

	require_once 'VersionControl/SVN.php';
	require_once 'mod_filestore.phtml';

	class filestore_svn extends filestore {

		/* public */

		function filestore_svn($name, $root) {
			global $AR;
			filestore::filestore($name, $root);

			// Setup error handling -- always a good idea!
			$this->svnstack = &PEAR_ErrorStack::singleton('VersionControl_SVN');

			if (!isset($AR->SVN->path)) {
				$AR->SVN->path = '/usr/bin/svn';
			}

			// Set up runtime options. 
			$this->svn_options = array(
				'fetchmode'		=> VERSIONCONTROL_SVN_FETCHMODE_ARRAY, 
				'svn_path'		=> $AR->SVN->path
			);

		}

		function connect($id, $username='', $password='') {
			global $AR;

			/* Makes the connection between a filestore ID and a
			   SVN repository. Other SVN commands will run using
			   the result of this function.
			*/

			$svn_instance = VersionControl_SVN::factory(array(
				"add",
				"blame",
				"checkout", 
				"cleanup",
				"commit", 
				"delete", 
				"diff",
				"export",
				"import",
				"info", 
				"list", 
				"log",
				"propdel",
				"propget",
				"proplist",
				"propset",
				"resolved",
				"revert",
				"status", 
				"update"
			), $this->svn_options);


			$svn_switches = array();
			if ($username) {
				$svn_switches['username'] = $username;
			}
			if ($password) {
				$svn_switches['password'] = $password;
			}
			if (file_exists($AR->dir->install . "/lib/configs/svn/")) {
				$svn_switches['config-dir'] = $AR->dir->install . "/lib/configs/svn";
			}

			$svn_switches['non-recursive'] = true;

			$svn_info = $svn_instance->info->run(
				array($this->make_path($id, '')), 
				$svn_switches
			);

			$svn = array(
				'instance' 		=> $svn_instance,
				'switches' 		=> $svn_switches,
				'object_id'		=> $id,
				'info'			=> $svn_info 
			);

			return $svn;
		}

		function get_path($svn, $name) {
			$path = $this->make_path($svn['object_id'], $name);
			return $path;
		}

		function rmdir_rf($path) {
			$dirhandle = opendir($path);
			while ($file = readdir($dirhandle)) {
				if ($file == "." || $file == "..") {
					continue;
				}

 				if (is_dir($path . $file)) {
					echo "Dir: $file<br>";
					$this->rmdir_rf($path .  $file . "/");	
				} else {
					echo "Unlink $file<br>";
					unlink($path . $file);
				} 		
			}
			echo "rmdir $path<br>";
			rmdir($path);
			closedir($dirhandle);			
		}

		/* Start of the SVN functions. */
		function svn_add($svn, $name) {
			/*	SVN add wrapper
				This function also creates the meta file by touching it. The
				contents of the file will be added when commited, but this
				allows the meta file to be added to the SVN at the same time
				as the file.
			*/

			$args = array(
				$this->get_path($svn, $name),
			);
			$result = $svn['instance']->add->run($args, $svn['switches']);
			return $result;
		}

		function svn_blame($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->blame->run($args, $svn['switches']);
			return $result;
		}

		function svn_cat($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->cat->run($args, $svn['switches']);
		}

		function svn_checkout($svn, $repository, $revision='HEAD') {
			/* Checkout given SVN. 
			   Since we only handle flat SVN, the checkout is
			   done only for files, and does not recurse into
			   directories.
			*/

			$args = array(
				$repository,
				$this->get_path($svn, '')
			);
			
			$switches = $svn['switches'];

			if ($revision != '') {
				$switches['revision'] = $revision;
			}

			$result = $svn['instance']->checkout->run($args, $switches);
			return $result;
		}

		function svn_cleanup($svn) {
			$args = array(
				$this->get_path($svn, '')
			);
			$result = $svn['instance']->cleanup->run($args, $svn['switches']);
			return $result;
		}

		function svn_commit($svn, $comment='', $fileinfo='') {
			/* 
				File information is used to record the meta
				information needed in Ariadne. The
				properties are saved in SVN properties. This
				part is needed because Ariadne does not
				store the meta information in the filenames
				(correctly).

				SVN properties that are used for Ariadne
				should be prepended with "ar:" to prevent
				collision with properties that someone else
				is using.


				Information structure is as follows
				[name]
						[ar:function]	 (usually the same as name)
						[ar:type]
						[ar:language]
						[ar:default]
			*/

			$args = array();
			
			if ($fileinfo) {
				foreach ($fileinfo as $filename => $file) {
					foreach ($file as $key => $value) {
						$this->svn_propset($svn, $key, $value, $filename);
					}
					$args[] = $this->get_path($svn, $filename);
				}
			} else {
				$args[] = $this->get_path($svn, '');
			}

			$switches = $svn['switches'];
			$switches['message'] = $comment;
			$result = $svn['instance']->commit->run($args, $switches);
			return $result;
		}

		function svn_delete($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$switches = $svn['switches'];
			$result = $svn['instance']->delete->run($args, $switches);
			return $result;
		}

		function svn_diff($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->diff->run($args, $svn['switches']);
			return $result;
		}

		function svn_export($svn, $repository, $revision='HEAD') {
			$args = array(
				$repository,
				$this->get_path($svn, '')
			);
			
			$switches = $svn['switches'];
			if ($revision != '') {
				$switches['revision'] = $revision;
			}
	
			$result = $svn['instance']->export->run($args, $switches);
			return $result;
		}

		function svn_import($svn, $repository, $comment='') {
			$args = array(
				$this->get_path($svn, ''),
				$repository
			);
			$switches = $svn['switches'];
			$switches['message'] = $comment;
			$result = $svn['instance']->import->run($args, $switches);
			return $result;
		}

		function svn_info($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->info->run($args, $svn['switches']);
			return $result;
		}

		function svn_list($svn) {
			$args = array(
				$this->get_path($svn, '')
			);
			$result = $svn['instance']->list->run($args, $svn['switches']);
			return $result;
		}

		function svn_log($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->log->run($args, $svn['switches']);
			return $result;
		}

		function svn_propdel($svn, $propkey, $name='') {
			$args = array(
				$propkey,
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->propdel->run($args, $svn['switches']);
			return $result;
		}

		function svn_propget($svn, $propkey, $name='') {
			$args = array(
				$propkey,
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->propget->run($args, $svn['switches']);
			return $result;
		}

		function svn_proplist($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->proplist->run($args, $svn['switches']);
			return $result;
		}

		function svn_propset($svn, $propkey, $propvalue, $name='') {
			$args = array(
				$propkey,
				$propvalue,
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->propset->run($args, $svn['switches']);
			return $result;
		}

		function svn_resolved($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->resolved->run($args, $svn['switches']);
			return $result;
		}

		function svn_revert($svn, $name='') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$result = $svn['instance']->revert->run($args, $svn['switches']);
			return $result;
		}

		function svn_status($svn, $name='') {
			$path = $this->get_path($svn, $name);

			// Performance improvement to make svn_status
			// faster. If there is not .svn dir, there is no SVN
			// status.
			if (file_exists($path . ".svn")) {
				$args = array(
					$path
				);

				$tempresult = $svn['instance']->status->run($args, $svn['switches']);

				// Since we have a flat structure, remove the path and use only the names.
				if ($tempresult) {
					//if (isset($tempresult[$args[0]])) {
					//	echo "1";
					//}

					if ((sizeof($tempresult) == 1) && (isset($tempresult[$args[0]]))) {
						return false;
					} else {
						$result = array();
						foreach ($tempresult as $key=>$value) {
							$filename = basename($key);
							$filename = substr($filename, 1);
				
							$result[$filename] = $value;
						}
						return $result;
					}
				} else {
					return false;
				}
			} else {
				return false;
			}
		}

		function svn_update($svn, $name='', $revision='HEAD') {
			$args = array(
				$this->get_path($svn, $name)
			);
			$switches = $svn['switches'];

			if ($revision != '') {
				$switches['revision'] = $revision;
			}

			$result = $svn['instance']->update->run($args, $switches);
			return $result;
		}

		// Start of customized SVN functions, these are not actually SVN commands but are very handy.
		function svn_accept_cert($svn, $repository) {
			$listargs = array(
				$repository
			);

			$switches = $svn['switches'];
			$switches['non-interactive'] = false;

			$result = $svn['instance']->list->run_interactive($listargs, $switches);
			return $result;
		}

		function svn_get_ariadne_props($svn, $name='') {
			if( substr($name, 0, 1) != "/" ) {
				$name = $this->get_path($svn, $name);
			}
			// accepts a filename within the svn store and returns an array containing the ar: properties of the file
			$proplist = explode("\n", $svn['instance']->proplist->run(array($name), $svn['switches']));
			$result = array();
			foreach( $proplist as $value ) {
				$value = ltrim($value);
				if( substr($value, 0, 3) == "ar:" ) {
					$result[$value] = $svn['instance']->propget->run(array($value, $name), $svn['switches']);
				}
			}
			return $result;			
		}

		function svn_checkunder($svn, $repository, $revision='HEAD') {
			// This function is designed mainly to be able to
			// sync up SVN versions and non-SVN versions,
			// without messing up existing files. It does this
			// by moving the templates to a safe location,
			// checkout the SVN, then move the original
			// templates back over the SVN version.

			$dir = $this->get_path($svn, '');
			$tempdir = tempnam($AR->dir->install . "/files/temp/", "svntemp");
			unlink($tempdir);

			if (file_exists($dir)) {
				// $dir only exists if templates are defined on this object.
				// Move the templates to a safe location.
				mkdir($tempdir);

				$tempdir .= "/";

				// echo "Tempdir: $tempdir\n";
				// echo "Dir: $dir\n";

				$dirhandle = opendir($dir);
				while (false !== ($file = readdir($dirhandle))) {
					if(is_file($dir . $file)) {
						rename($dir . $file, $tempdir . $file);
						// echo "Moved $file\n";
					}
				}
				closedir($dirhandle);
			}
			
			// echo "Checkout revision $revision<br>";
			$checkout_result = $this->svn_checkout($svn, $repository, $revision);

			if (file_exists($tempdir)) {
				// Tempdir only exists if we moved any templtes.
				// Move the templates back to the original location
		
				$dirhandle = opendir($tempdir);
				while (false !== ($file = readdir($dirhandle))) {
					if (is_file($tempdir . $file)) {
						rename($tempdir . $file, $dir . $file);
						touch($dir.$file);
						// echo "Replaced $file\n";
					}
				}
				closedir($dirhandle);

				// echo "Removed $tempdir\n";
				rmdir($tempdir);
			}
			return $checkout_result;			
		}
			
		function svn_mkdirs($svn, $repository) {
			/* Create all subdirectories needed where needed, including all
			   the need parent directories. This works by creating an empty
			   directory and importing it into the SVN.

			   The reason import is used instead of mkdir is because import
			   creates the parent directories as well.
			*/
			global $AR;
			$listargs = array(
				$repository
			);
			echo "Testing repository directory - error is normal\n";
			$svnlist = @$svn['instance']->list->run($listargs, $svn['switches']);
			if ($svnlist) {
				return false;
			} else {
				echo "\nRepository dir does not exist - creating...\n";
				$tempdir = tempnam($AR->dir->install . "/files/temp/", "svntemp");
				unlink($tempdir);
				mkdir($tempdir);
				$args = array(
					$tempdir,
					$repository
				);
				$switches = $svn['switches'];
				$switches['message'] = "Repository creation";
				$result = $svn['instance']->import->run($args, $switches);
				rmdir($tempdir);
			}
			return true;
		}

		function svn_rinfo($svn, $repository, $name='') {
			$args = array(
				$repository . $name
			);
			$result = $svn['instance']->info->run($args, $svn['switches']);
			return $result;
		}

		function svn_rpropget($svn, $repository, $propkey, $name='') {
			$args = array(
				$propkey,
				$repository . $name
			);
			$result = $svn['instance']->propget->run($args, $svn['switches']);
			return $result;
		}

		function svn_unsvn($svn) {
			$path = $this->get_path($svn, '') . ".svn/";
			$this->rmdir_rf($path);
		}
	}
?>