<?php
	class mod_tar {
		protected $config;
		protected $tar_error_handler;
		protected $tar_tar;
		protected $tar_untar;
		protected $tar_nofail;
		protected $mode;
		function __construct($config) {
			$this->config = $config;
			$this->tar_error_handler = $config["error_handler"];
			$this->tar_tar = $config["tar"];
			$this->tar_untar = $config["untar"];
			$this->tar_nofail = $config["nofail"];
			PEAR::setErrorHandling(PEAR_ERROR_DIE);
		}


		function extract($archive, $file, $dstdir) {
			$archive = new Archive_Tar($archive);
			$result = $archive->extract($dstdir);
			$archive->_Archive_Tar();

			return $result;
		}

		function create($archive, $filelist, $srcdir) {
			$archive = new Archive_Tar($archive, true);
			$filelist = trim($filelist);
			$filelist = explode(" ", $filelist);
			if ($srcdir && $srcdir[strlen($srcdir)-1] != '/') {
				$srcdir.='/';
			}
			if (is_array($filelist)) {
				while (list($key, $file) = each($filelist)) {
					$filelist[$key] = $srcdir.$file;
				}
			}
			$result = $archive->addModify($filelist, "", $srcdir);
			$archive->_Archive_Tar();
			return $result;
		}
	}
