<tr>
<td>
<?php
  $BrowseGrant=$this->CheckSilent("read");
  $BrowseGrant=true;
  if ($BrowseGrant) {
    echo "<a href=\"#\" onClick=\"top.View('".$this->path."');\">";
  }
?>
<img src="<?php 
  echo $AR->dir->images; ?>icons/<?php echo $this->type; ?>.gif" alt="[view]" border="0"></a>
</td>
<td align="left">
<?php
  if (!$BrowseGrant) {
    echo "<font color=\"#CCCCCC\"><b>$nlsdata->name</b></font>";
  } else {
    echo "<a href=\"#\" onClick=\"top.View('".$this->path."'); return false;\">";
    echo "<b>$nlsdata->name</b></a>";
  }
?></a>
</td>
</tr>
