<?php
	/******************************************************************
	 browse.nav.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays the list of directories in the left frame
	 of the browse dialog.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<script language="javascript">
<!--
	// announce ourselfs
	top.ViewLoaded('<?php echo $this->path; ?>','<?php echo AddSlashes($nlsdata->name); ?>');
//-->
</script>
<style>
	.object {
		width: 100%;
		overflow: hidden;
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
		height: 100%;
	}
	A {
		text-decoration: none;
		color: black;
	}
</style>
<body bgcolor="white">
<?php
	$crit["object"]["implements"]["="]="'pdir'";
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$this->find(".",$crit,"browse.nav.list.show.phtml");
?>
</body>
<?php
	}
?>