<?php 
	/******************************************************************
	 browse.nav.list.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<style>
	.object {
		width: 150px;
		overflow: hidden;
		<?php
			if (($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
	}
	A {
		text-decoration: none;
		color: black;
	}
</style>
<body bgcolor="white">
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	if (!$limit) {
		$limit=100;
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$total=$this->store->count($this->store->find("", $crit));
//	debugon('all');
	$this->find(".",$crit, "browse.nav.list.show.phtml", "", $limit, $offset);
//	debugoff();
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
?>
</body>
<?php
	}
?>