<?php
	/******************************************************************
	 browse.show.option.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $selected
	 Grant needed: none
	 Global variables: none

	 This template displays the name and path of the current object 
	 in an option list, indented according to the 'level' of the object.
	 Each child is indented relative to its parent.
	 
	 no result

	******************************************************************/

?><option value="<?php echo $this->path; ?>" 
<?php
	if ($selected==$this->path) {
		echo " selected ";
	}
?>><?php
	for ($i=0; $i<$ARCurrent->BrowseEntry; $i++) {
		echo "&nbsp;&nbsp;&nbsp;";
	}
	$ARCurrent->BrowseEntry+=1;
	echo $nlsdata->name;
?></option>
