<?php 
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<style>
	.object {
		width: 150px;
		overflow: hidden;
		<?php
			if (($browser["id"]!="msie") || ($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
		line-height: 15pt;
		border: 2px inset;
		height: 100%;
	}
	A {
		text-decoration: none;
		color: black;
	}
</style>
<body bgcolor="white">
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$this->find(".",$crit, "browse.nav.list.show.phtml");
?>
</body>
<?php
	}
?>