<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

?>
<div class='object'><nobr><a 
	href="javascript:top.View('<?php echo $this->parent; ?>');"><img 
	width="20" height="20" src="<?php echo $AR->dir->images; ?>icons/pdir.gif" 
	alt="[view]" border="0"> ..</a></nobr></div>
