<html>
<head>
<title><?php echo $title; ?></title>
<script language="javascript">
<!--
	CurrentPath='<?php echo $this->path; ?>';
	CurrentViewMode="list";

	function View(path) {
		CurrentPath=path;
		top.browsemiddle.rightnav.location="<?php
		echo $this->store->root; ?>"+path+"browse.nav."+CurrentViewMode+".phtml";

		top.browsemiddle.leftnav.location="<?php
		echo $this->store->root; ?>"+path+"browse.nav.phtml";
	}

	function ViewLoaded(path,name) {
		top.browsetop.View(path,name);
	}

	function ViewMode(mode) {
		CurrentViewMode=mode;
		View(CurrentPath);
	}

	function New() {
		top.browsemiddle.rightnav.location="<?php
		echo $this->store->root; ?>"+CurrentPath+"new.phtml?returnpage="+
		"<?php echo $this->store->root; ?>"+
		CurrentPath+"browse.nav."+CurrentViewMode+".phtml";
	}
//-->
</script>
</head>
<frameset rows="40,*,40" border="0">
	<frame name="browsetop" border="0" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="<?php echo $this->store->root.$this->path; ?>browse.top.phtml">
	<frame name="browsemiddle" border="0" frameborder="0" src="<?php echo $this->store->root.$this->path; ?>browse.middle.phtml">
	<frame name="browsebottom" border="0" frameborder="0" marginwidth="0" marginheight="0" border="0" scrolling="no" src="<?php echo $this->store->root.$this->path; ?>browse.bottom.phtml">
</frameset>
