<?php 
	/******************************************************************
	 browse.nav.icons.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the icons list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
	?>
<html>
<head>
<link type="text/css" rel="stylesheet" href="<?php echo $AR->dir->www; ?>styles/browse.icons.css">
<body bgcolor="white">
<?php
	$this->call('browse.list.phtml', Array('template' => 'browse.nav.icons.show.phtml'));
?>
</body>
<?php
	}
?>