<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>menu.css">
<script>

  function showFilename() {
    document.selectform.filename.scrollLeft=1000000;
  }

</script>
</head>
<body onLoad="showFilename()"> 
<form name="selectform">
<table border="0" cellpadding="2" cellspacing="2">
<tr valign="middle">
	<td>
		<?php echo $ARnls["filename"]; ?> :
	</td><td>
		<input type="text" name="filename" style="width: 200;" value="<?php echo $this->path; ?>">
	</td><td>
		&nbsp;&nbsp;<input type="button" name="open" style="width: 75px" value="<?php echo $ARnls["open"]; ?>" onClick="top.opener.wgBrowseResult.value=top.CurrentPath; top.close();">
	</td>
</tr><tr>
	<td>
		<?php echo $ARnls["objectsoftype"]; ?> :
	</td><td>
		<select name="filter" style="width: 200;" onChange="top.filter(this.options[this.selectedIndex].value)">
			<option value=""><?php echo $ARnls["allobjects"]; ?></option>
			<?php
				if ($AR->user->data->login=="admin") {
					$this->ls('/system/ariadne/types/','show.option.value.phtml','selected='.RawUrlEncode($wgBrowseFilter));
				} else {
					$this->ls($ARConfig->typetree,'show.option.value.phtml','selected='.RawUrlEncode($wgBrowseFilter));
				}
			?>
		</select>
	</td><td>
		&nbsp;&nbsp;<input type="button" name="cancel" style="width: 75px" value="<?php echo $ARnls["cancel"]; ?>" onClick="top.opener.wgBrowseResult.value=top.CurrentPath; top.close();">
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
  }
?>