<?php
	if ($this->CheckLogin('read') && $this->CheckConfig()) {
		$query="object.parent='".AddSlashes($this->path)."'";
		$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
		if ($filter=$this->getvar('filter')) {
			$query.=" and object.implements='".AddSlashes($filter)."'";
			$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
		}
		if ($name=$this->getvar('name')) {
			$query.=" and name.value ~= '%".AddSlashes($name)."%'";
			$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
		} else if ($letter=$this->getvar('letter')) {
			$query.=" and name.value ~= '".AddSlashes($letter)."%'";
			$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
		}
		if ($AR->user->data->orderedbrowsing) {
			$query.=" order by name.$nls.value";
		}
		if (!($limit=$this->getvar('limit'))) {
			$limit=100;
		}
		if (!$template) {
			$template='browse.nav.list.show.phtml';
		}
		$offset=$this->getvar('offset');
		$total=$this->store->count($this->store->find("", $query, 0));
		$this->find(".",$query, $template, "", $limit, $offset);
		$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
	}
?>