<html>
<head>
</head>
<body bgcolor="#CCCCCC">
<form>
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" bgcolor="#CCCCCC">
<tr valign="middle">
	<td align="left">
		<img src="<?php echo $AR->dir->images; ?>dot.gif" width="5" height="1">
	</td>
	<td align="left">
	<input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="top.close();">
	</td>
	<td align="right">
	<input type="button" name="ok" value="<?php echo $ARnls["ok"]; ?>" onClick="top.opener.wgBrowseResult.value=top.CurrentPath; top.close();">
	</td>
	<td align="left">
		<img src="<?php echo $AR->dir->images; ?>dot.gif" width="5" height="1">
	</td>
</tr>
</table>
</form>
</body>
</html>
