<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

?>
<SPAN class=item>
	<A HREF="javascript:top.View('<?php echo $this->parent; ?>');"><IMG 
		SRC="<?php echo $AR->dir->images."icons/pdir_open.gif"; ?>" border="0" HEIGHT="40" WIDTH="40" HSPACE=0 VSPACE=0 ALT=".."><br>..</A>
</SPAN>
