<?php
	/******************************************************************
	 browse.top.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays the top pat of the browse dialog.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?><html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
<script language="javascript">
<!--
	LastPath='<?php echo $this->path; ?>';
	function View(path,name) {
		var inlist=-1;
		var newname="";
		
		if (document.browseform.BrowseNav) {
			blist=document.browseform.BrowseNav.options;
			for (i=0; i<blist.length; i++) {
				if (blist[i].value==path) {
					blist.selected=true;
					inlist=i;
				}
			}
			if (inlist==-1) {
				for (i=0; i<blist.length; i++) {
					newname+="   ";
				}
				newname+=name;
				blist[blist.length]=new Option(newname,path);
				blist[blist.length-1].selected=true;
			} else {
				for (i=blist.length-1; i>inlist; i--) {
					blist[i]=null;
				}
				blist[blist.length-1].selected=true;
			}
		}
	}

	function browseUp() {
		if (blist=document.browseform.BrowseNav) {
			sIndex=blist.options.selectedIndex;
			if (sIndex>0) {
				parent.View(blist.options[blist.options.selectedIndex-1].value);
			}
		}
	}

	function browseHome() {
		parent.View('<?php echo $AR->user->path; ?>');
	}

	function ViewMode(mode) {
		if (mode=='details') {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details-pressed.gif';			
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons.gif';			
		} else if (mode=='icons') {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details.gif';			
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons-pressed.gif';			
		} else {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details.gif';
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list-pressed.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons.gif';			
		}
		parent.ViewMode(mode);
	}

	function New() {
		if (blist=document.browseform.BrowseNav) {
			startpath='<?php echo $this->store->root; ?>'+blist.options[blist.options.selectedIndex].value;
		} else {
			startpath='<?php echo $this->store->root.$this->path; ?>';
		}
		if (document.all) {
			args=new Array();
			showModalDialog( startpath+"object.new.select.phtml",args,"font-family:Verdana; font-size:12; dialogWidth:38em; dialogHeight:26em; status:no; resizable: yes;");
			ObjectAdded();
		} else {
			newwindow=window.open( startpath+'object.new.select.phtml', 'newwindow',
				'directories=no,height=300,width=500,location=no,menubar=no,status=no,toolbar=no,resizable=yes');
			newwindow.focus();
		}
	}

	function ObjectAdded() {
		if (blist=document.browseform.BrowseNav) {
			parent.View(blist.options[blist.options.selectedIndex].value);
		} else {
			parent.View('<?php echo $this->store->root.$this->path; ?>');
		}
	}

	function init() {
		if (blist=document.browseform.BrowseNav) {
			if (blist.options[blist.options.selectedIndex].value=='/') {
				document.images["up"].src='<?php echo $AR->dir->images; ?>browse/up-shaded.gif';
			}
		}
		if (parent.CurrentViewMode=="list" && document.images["list"]) {
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list-pressed.gif';
		}
		if (parent.CurrentViewMode=="icons" && document.images["icons"]) {
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons-pressed.gif';
		}
		if (parent.CurrentViewMode=="details" && document.images["details"]) {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details-pressed.gif';
		}
		loaded=true;
		parent.isLoaded['browsetop']=true;
	}

	function showPage(page) { 
        parent.b_page=page;
        parent.b_offset=parent.b_limit*page;
		parent.browsemiddle.location.search='?filter=<?php echo RawUrlEncode($filter); ?>&offset='+escape(parent.b_offset)+'&limit='+escape(parent.b_limit);
        return false;
	}

	loaded=false;
//-->
</script>
</head>
<body bgcolor="#CCCCCC" border="no" onLoad="init()">
<form name="browseform">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
	<?php
		if (!$buttons['lookin']) {
	?>
	<td align="left" valign="middle">
		<nobr>&nbsp;&nbsp;<?php echo $ARnls["lookin"]; ?>&nbsp;:</nobr>
	</td><td align="left" valign="top">
		<select name="BrowseNav" style="width: 150px; padding: 2px; margin: 2px;" onChange="parent.View(this.options[this.options.selectedIndex].value);" class="minimal">
		<?php
			$this->parents(".","browse.show.option.phtml",Array("selected" => $this->path));
		?>
		</select>
				</nobr>
	</td>
	<?php
		}
	?>
	<td align="left" valign="top">
		<nobr>
			<?php
				if (!$buttons['up']) { 
			?>
			<a href="#" onClick="browseUp(); return false;"><img name="up" src="<?php echo $AR->dir->images; ?>browse/up.gif" width="23" height="22" alt="<?php echo $ARnls["up"]; ?>" border="0" hspace="2" vspace="2"></a>
			<?php
				}
				if (!$buttons['home']) {
			?>
			<a href="#" onClick="browseHome(); return false;"><img name="home" src="<?php echo $AR->dir->images; ?>browse/home.gif" width="23" height="22" alt="<?php echo $ARnls["home"]; ?>" border="0" hspace="2" vspace="2"></a>
			<?php
				}
				if (!$buttons['new']) {
					if (!$this->CheckSilent("add")) {
			?>
				<img name="new" src="<?php echo $AR->dir->images; ?>browse/new-shaded.gif" alt="" width="23" height="22" border="0" hspace="4" vspace="2">
			<?php 
					} else {
			?>
				<a href="#" onClick="New(); return false;"><img name="new" src="<?php echo $AR->dir->images; ?>browse/new.gif" alt="<?php echo $ARnls["new"]; ?>" width="23" height="22" border="0" hspace="4" vspace="2"></a> 
			<?php
					}
				}
				if (!$buttons['viewmode']) {
			?>
			<a href="#" onClick="ViewMode('list'); return false;"><img name="list" src="<?php echo $AR->dir->images; ?>browse/list.gif" alt="<?php echo $ARnls["list"]; ?>" width="23" height="22" border="0" hspace="0" vspace="2"></a><a 
			href="#" onClick="ViewMode('icons'); return false;"><img name="icons" src="<?php echo $AR->dir->images; ?>browse/icons.gif" alt="<?php echo $ARnls["icons"]; ?>" width="23" height="22" border="0" hspace="0" vspace="2"></a><a 		
			href="#" onClick="ViewMode('details'); return false;"><img name="details" src="<?php echo $AR->dir->images; ?>browse/details.gif" alt="<?php echo $ARnls["details"]; ?>" width="23" height="22" border="0" hspace="0" vspace="2"></a>
			<?php
				}
			?>
		</td><td align="right" valign="top" width="100%">
			<?php
				if (!$buttons['page']) {
			?>
				<select name="page" onChange="return showPage(this.options.selectedIndex);" style="margin: 2px; display: none;">
				</select>
			<?php
				}
			?>
		</nobr>
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
	}
?>