<body bgcolor="white">
<table border="0" cellpadding="0" cellspacing="0" height="100%">
<tr><td><img src="dot.gif" width="100" height="1"></td></tr>
<tr valign="top">
<td>
	<?php
		$this->call("browse.nav.view.phtml");
	?>
</td>

<td align="left" width="1" units="pixels" bgcolor="#000000"><img width="1" height="1" src="<?php echo $AR->dir->images; ?>dot.gif" border="0" vspace="0" hspace="0"><p></td>

<td align="left" width="100%">
	<table border="0" width="100%">
	<tr valign="top">
		<td align="left">&nbsp;</td>
		<td width="100%" align="left">&nbsp;</td>
	</tr>
	<?php
		$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
		$this->ls(".","browse.nav.details.show.phtml");
	?>
	</table>
</td>

</tr>
</table>
</body>
