<html>
<head>
	<?php
        $browser=$this->call("browsercheck.phtml");
        if ($browser=="ns4") {
			?>
<SCRIPT language="JavaScript" type="text/javascript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {
    if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
      document.MM_pgW=innerWidth; 
      document.MM_pgH=innerHeight; 
      onresize=MM_reloadPage; 
    }
  } else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) {
    location.reload();
  }
}

function myclip(id) {
  mylayer=document.layers[id];
  mylayer.bgColor="white";
  mylayer.clip.height=16;
  mylayer.clip.width=80;
}

function myunclip(id) {
  mylayer=document.layers[id];
  mylayer.bgColor="yellow";
  mylayer.clip.height=mylayer.clipheight;  
  mylayer.clip.width=mylayer.clipwidth;
  while(otherlayer=mylayer.siblingAbove) {
    mylayer.zIndex=otherlayer.zIndex+1;
  }
}

MM_reloadPage(true);

function init() {
  num=document.layers.length;
  for (i=0; i<num; i++) {
    document.layers[i].clipheight=document.layers[i].clip.height-55;
    document.layers[i].clipwidth=document.layers[i].clip.width;
    document.layers[i].clip.top=55;
    document.layers[i].clip.height=16;
    document.layers[i].clip.width=80;
  }
}

window.onload=init;
// -->
</script>
<style>
.text {
  position: absolute;
  top: 55px;
  left: -85px;
  width: 100px;
  height: 25px;
  padding: 1px 20px 1px 2px;
}
BODY { font: 9pt sans-serif,Arial,Helvetica }
A { text-decoration: none; color: #000000}
IMG { padding-top: 0px }
-->
</STYLE>
			<?php
			$template="browse.item.show.ns4.phtml";
		} else {
			?>
<STYLE TYPE="text/css">
<!--
SPAN.item { left: 10 px; 
            width: 90px; 
            height: 100px;
            position: relative; 
            margin-top: 5px; 
            margin-right: 5px; 
            vertical-align: top; 
            text-align: center;
            float: left;
            overflow: hidden;
          }
BODY { font: 9pt sans-serif,Arial,Helvetica }
A { text-decoration: none; color: #000000}
IMG { padding-top: 0px }
-->
</STYLE>

			<?php
			$template="browse.item.show.phtml";
		}
	?>
</head>
<body bgcolor="white">
<table border="0" cellpadding="0" cellspacing="0" height="100%">
<tr><td><img src="dot.gif" width="100" height="1"></td></tr>
<tr valign="top">
<td>
	<?php
		$this->call("browse.item.view.phtml");
	?>
</td>

<td align="left" width="1" units="pixels" bgcolor="#000000"><img width="1" height="1" src="<?php echo $AR->dir->images; ?>dot.gif" border="0" vspace="0" hspace="0"><p></td>

<td align="left" width="100%">
	<?php 
		$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
        $this->find(".",$crit,$template,,50);
	?>
</td>

</tr>
</table>
</body>
</html>