<?php
	/******************************************************************
	 browse.middle.phtml                                   Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none

	 This template displays the files frame set for the browse dialog.
	 The left frame displays a list of objects implementing pdir via
	 the browse.nav.phtml template.
	 The right frame displays a list of objects, fullfilling the
	 requirements passed via the $filter argument, vie the
	 browse.nav.list.phtml template.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
  <script>
    function b_setTotal(total) {
		if( parent && parent.browsetop && parent.browsetop.b_setTotal ) {
			parent.browsetop.b_setTotal(total);
		}
    }
    function b_hide() { }
    function b_show() { }
  </script>
</head>
<frameset cols="150,*">
	<frame name="leftnav" src="<?php echo $this->store->get_config("root").$this->path; ?>browse.nav.phtml?root=<?php echo RawUrlEncode($root); ?>">
	<frame name="rightnav" src="<?php echo $this->store->get_config("root").$this->path; ?>browse.nav.list.phtml?root=<?php echo RawUrlEncode($root); ?>&filter=<?php echo $filter; ?>">
</frameset>
</html>
<?php
	}
?>