<?php 
	/******************************************************************
	 browse.nav.icons.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the icons list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
	?>
<html>
<head>
<style>
	SPAN.item { 
		left: 5 px;
		width: 60px;
		height: 68px;
		position: relative;
		margin-top: 5px;
		margin-right: 5px;
		vertical-align: top;
		text-align: center;
		<?php
			if ($browser["id"]!="msie" || $browser["version"]!=4) { 
		?>
				float: left;
		<?php
			}
		?>
		overflow: hidden;
	}
	BODY {
		font: 9pt sans-serif,Arial,Helvetica
	}
	A { 
		text-decoration: none;
		color: #000000
	}
	IMG {
		padding-top: 0px
	}
</style>
<body bgcolor="white">
<?php
	if ($this->parent!="..") {
		$this->call("browse.nav.icons.show.up.phtml");
	}
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$this->find(".", $crit, "browse.nav.icons.show.phtml");
?>
</body>
<?php
	}
?>