<tr>
<td><?php $this->call("browse.nav.list.show.phtml"); ?></td>
<td align="right"><?php
		 	if ($this->size>1024) {
				echo round(intval($this->size)/1024)."&nbsp;KB&nbsp;"; 
			} else {
				echo intval($this->size)."&nbsp;B&nbsp;";
			}
?></td>
<td align="right"><?php echo $this->type; ?>&nbsp;</td>
<td><?php
  $now=time();
  if ($this->lastchanged>($now+86400)) {
    echo strftime("&nbsp;%d/%m/%Y", $this->lastchanged); 
  } else {
    echo strftime("&nbsp;%H:%M", $this->lastchanged);
  }
?></td><td><?php
  if (is_array($this->data->nls->list)) {
    reset($this->data->nls->list);
    while (list($key, $value)=each($this->data->nls->list)) {
      echo "<img src=\"".$AR->dir->images."nls/small/".$key.".gif\" alt=\"$value\"> ";
    }
  }
?></td>
</tr>
