<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?><html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>menu.css">
<script language="javascript">
<!--
	LastPath='<?php echo $this->path; ?>';
	function View(path,name) {
		var inlist=-1;
		var newname="";
		
		blist=document.browseform.BrowseNav.options;
		for (i=0; i<blist.length; i++) {
			if (blist[i].value==path) {
				blist.selected=true;
				inlist=i;
			}
		}
		if (inlist==-1) {
			for (i=0; i<blist.length; i++) {
				newname+="   ";
			}
			newname+=name;
			blist[blist.length]=new Option(newname,path);
			blist[blist.length-1].selected=true;
		} else {
			for (i=blist.length-1; i>inlist; i--) {
				blist[i]=null;
			}
			blist[blist.length-1].selected=true;
		}
	}

	function browseUp() {
		blist=document.browseform.BrowseNav;
		sIndex=blist.options.selectedIndex;
		if (sIndex>0) {
			top.View(blist.options[blist.options.selectedIndex-1].value);
		}
	}

	function browseHome() {
		top.View('<?php echo $AR->user->path; ?>');
	}

	function ViewMode(mode) {
		if (mode=='details') {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details-pressed.gif';			
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list.gif';			
		} else {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details.gif';
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list-pressed.gif';			
		}
		top.ViewMode(mode);
	}

	function New() {
		blist=document.browseform.BrowseNav;
		newwindow=window.open('<?php echo $this->store->root; ?>'+blist.options[blist.options.selectedIndex].value+'object.new.select.phtml',
			'newwindow',
			'directories=no,height=300,width=500,location=no,menubar=no,status=no,toolbar=no,resizable=yes');
		newwindow.focus();
	}

	function ObjectAdded() {
		blist=document.browseform.BrowseNav;
		top.View(blist.options[blist.options.selectedIndex].value);
	}

	function init() {
		blist=document.browseform.BrowseNav;
		if (blist.options[blist.options.selectedIndex].value=='/') {
			document.images["up"].src='<?php echo $AR->dir->images; ?>browse/up-shaded.gif';
		}
		if (top.CurrentViewMode=="list") {
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list-pressed.gif';
		}
		if (top.CurrentViewMode=="details") {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details-pressed.gif';
		}
		loaded=true;
	}

	loaded=false;
//-->
</script>
</head>
<body bgcolor="#CCCCCC" border="no" onLoad="init()">
<form name="browseform">
<table border="0" cellpadding="0" cellspacing="0">
<tr>
	<td align="left" valign="middle">
		<nobr>&nbsp;&nbsp;<?php echo $ARnls["lookin"]; ?>&nbsp;:</nobr>
	</td><td align="left" valign="top">
		<select name="BrowseNav" style="width: 150px; padding: 2px; margin: 2px;" onChange="top.View(this.options[this.options.selectedIndex].value);" class="minimal">
		<?php
			$this->parents(".","browse.select.option.phtml","selected=".urlencode($this->path));
		?>
		</select>
        </nobr>
	</td><td align="left" valign="top">
		<nobr>
			<a href="javascript:browseUp()"><img name="up" src="<?php echo $AR->dir->images; ?>browse/up.gif" width="23" height="22" alt="<?php echo $ARnls["up"]; ?>" border="0" hspace="2" vspace="2"></a>
			<a href="javascript:browseHome()"><img name="home" src="<?php echo $AR->dir->images; ?>browse/home.gif" width="23" height="22" alt="<?php echo $ARnls["home"]; ?>" border="0" hspace="2" vspace="2"></a>
			<?php
				if (!$this->CheckSilent("add")) {
			?>
				<img name="new" src="<?php echo $AR->dir->images; ?>browse/new-shaded.gif" alt="" width="23" height="22" border="0" hspace="4" vspace="2">
			<?php 
				} else {
			?>
				<a href="javascript:New()"><img name="new" src="<?php echo $AR->dir->images; ?>browse/new.gif" alt="<?php echo $ARnls["new"]; ?>" width="23" height="22" border="0" hspace="4" vspace="2"></a> 
			<?php
				}
			?>
			<a href="javascript:ViewMode('list')"><img name="list" src="<?php echo $AR->dir->images; ?>browse/list.gif" alt="<?php echo $ARnls["new"]; ?>" width="23" height="22" border="0" hspace="0" vspace="2"></a><a 
			href="javascript:ViewMode('details')"><img name="details" src="<?php echo $AR->dir->images; ?>browse/details.gif" alt="<?php echo $ARnls["new"]; ?>" width="23" height="22" border="0" hspace="0" vspace="2"></a>
		<nobr>
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
  }
?>