<?php 
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<style>
	BODY, TD {
		font: 10pt Arial,Helvetica,sans-serif;
		line-height: 15pt;
	}
	BODY {
		margin: 0px;
		padding: 0px;
	}
	TD {
		margin: 1px;
	}
	A {
		text-decoration: none;
		color: black;
	}
	.heading {
		font: 10pt Arial,Helvetica,sans-serif;
		<?php
			$browser=$this->call("browsercheck.phtml");
			if ($browser["id"]=="ns" && $browser["version"]==4) {
		?>
			background: #BBBBBB;
			width: 100px;
		<?php
			} else {
		?>
			background: buttonface;
			width: 100%;
		<?php
			}
		?>
		border: 2px outset;
		text-align: center;
	}
</style>
<body bgcolor="white">
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
  <td><span class="heading"><?php echo $ARnls["name"]; ?></span></td>
  <td><span class="heading"><?php echo $ARnls["size"]; ?></span></td>
  <td><span class="heading"><?php echo $ARnls["type"]; ?></span></td>
  <td><span class="heading"><?php echo $ARnls["modified"]; ?></span></td>
</tr>
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$this->find(".",$crit, "browse.nav.details.show.phtml");
?>
</table>
</body>
<?php
	}
?>