<?php
  $BrowseGrant=$this->CheckSilent("read");
  echo "<div class='object'><nobr>";
  if ($BrowseGrant) {
    echo "<a href=\"javascript:top.View('".$this->path."');\">";
  }
?>
<img width="18" height="18" src="<?php 
  echo $AR->dir->images; ?>icons/<?php echo $this->type; ?>.gif" alt="[view]" border="0" align="left">
<?php
  if (!$BrowseGrant) {
    echo "<font color=\"#CCCCCC\">$nlsdata->name</font>";
  } else {
    echo "$nlsdata->name</a>";
  }
?></nobr></div>
