<?php
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<SPAN class=item>
   <A HREF="<?php echo $this->store->root.$this->path; ?>" onClick="return top.View('<?php echo $this->path; ?>');"><IMG SRC=<?php 
     echo $AR->dir->images."icons/".$this->type; ?>.gif border=0 width=40 height=40 HSPACE=0 VSPACE=0
     ALT="<?php echo $nlsdata->name; ?>"><br>
   <?php echo $nlsdata->name; ?></A>
</SPAN>
<?php
  }
?>