<?php
	/******************************************************************
	 browse.phtml                                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter, $path, $mode, $title
	 Grant needed: read
	 Global variables: none

	 This templates sets up the frame set for the entire browse dialog.
	 It is called by the browse widget.

	 $filter can either be empty or a valid argument for the 
	   object.implements search criteria.
	 $path is the starting path of the browse dialog. If it doesn't 
	   exist the path of this object is used instead.
	 $mode can either be 'list','details' or 'web' (FIXME: not yet implemented)
	 $title is the title of the window.

	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		if ($root) {
			$path = $root.$path;
		}
		$path=$this->make_path($path);
		if (!$path || !$this->exists($path)) {
			$path=$this->path;
		}
?><html>
<head>
<title><?php echo $title; ?></title>
<script language="javascript">
<!--
	CurrentRoot='<?php echo $root; ?>';
	CurrentPath='<?php echo $path; ?>';
	CurrentViewMode='<?php echo $mode; ?>';
	CurrentFilter='<?php echo $filter; ?>';

	function View(path) {
		CurrentPath=path;
		top.browsemiddle.rightnav.location="<?php
		echo $this->store->get_config("root"); ?>"+path+"browse.nav."+
			CurrentViewMode+".phtml?filter="+escape(CurrentFilter)+"&root="+CurrentRoot;
		top.browsemiddle.leftnav.location="<?php
		echo $this->store->get_config("root"); ?>"+path+"browse.nav.phtml?root="+CurrentRoot;
		if (CurrentRoot && path) {
			var rootFilter = new RegExp(CurrentRoot+"(.*)", "");
			var rootFilterMatches = rootFilter.exec(path);			
			if (rootFilterMatches) {
				path = rootFilterMatches[1];
			} else {
				path = "";
			}
		}
		top.browsebottom.document.selectform.filename.value=path;
		top.browsebottom.showFilename();
	}

	function ViewLoaded(path,name) {
		if (top.browsetop && top.browsetop.loaded) {
			top.browsetop.View(path,name);
		}
	}

	function ViewMode(mode) {
		CurrentViewMode=mode;
		View(CurrentPath);
	}

	function New() {
		top.browsemiddle.rightnav.location="<?php
		echo $this->store->get_config("root"); ?>"+CurrentPath+"classic.new.phtml?arReturnPage="+
		"<?php echo $this->store->get_config("root"); ?>"+
		CurrentPath+"browse.nav."+CurrentViewMode+".phtml";
	}

	function filter(type) {
		CurrentFilter=type;
		View(CurrentPath);
	}

//-->
</script>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
<style>
	FRAMESET, FRAME {
		BORDER: 0;
	}
</style>
</head>
<frameset rows="30,*,70" border="0">
	<frame name="browsetop" border="0" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" 
		src="<?php echo $this->store->get_config("root").$path; ?>browse.top.phtml?root=<?php echo RawUrlEncode($root); ?>&filter=<?php echo RawUrlEncode($filter); ?>">
	<frame name="browsemiddle" border="0" frameborder="0" 
		src="<?php echo $this->store->get_config("root").$path; ?>browse.middle.phtml?root=<?php echo RawUrlEncode($root); ?>&filter=<?php echo RawUrlEncode($filter); ?>">
	<frame name="browsebottom" border="0" frameborder="0" marginwidth="0" marginheight="0" border="0" scrolling="no" 
		src="<?php echo $this->store->get_config("root").$path; ?>browse.bottom.phtml?root=<?php echo RawUrlEncode($root); ?>&filename=<?php echo RawUrlEncode($filename); ?>&filter=<?php echo RawUrlEncode($filter); ?>">
</frameset>
<?php
	}
?>