<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

	$icon=$this->call('system.get.icon.phtml');
?>
<SPAN class=item>
	<A TITLE="<?php echo $nlsdata->name; ?>" 
		HREF="javascript:top.View('<?php echo $this->path; ?>','<?php echo AddCSlashes($nlsdata->name,ARESCAPE); ?>');"><IMG 
		SRC="<?php echo $icon; ?>" 
		border="0" HEIGHT="40" WIDTH="40" HSPACE=0 VSPACE=0 
		ALT="<?php echo $this->path; ?>"><br>
	<?php 
		if (!$this->CheckSilent("read")) {
			echo "<font color=\"#CCCCCC\">$nlsdata->name</font>";
		} else {
			echo "$nlsdata->name";
		}
	?></A>
</SPAN>
