<?php 
	/******************************************************************
	 browse.nav.icons.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the icons list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
	?>
<html>
<head>
<style>
	SPAN.item { 
		left: 5 px;
		width: 60px;
		height: 68px;
		position: relative;
		margin-top: 5px;
		margin-right: 5px;
		vertical-align: top;
		text-align: center;
		<?php
			if ($browser["id"]!="msie" || $browser["version"]!=4) { 
		?>
				float: left;
		<?php
			}
		?>
		overflow: hidden;
	}
	BODY {
		font: 9pt sans-serif,Arial,Helvetica
		margin: 0px;
		padding: 0px;
	}
	A { 
		text-decoration: none;
		color: #000000
	}
	IMG {
		padding-top: 0px
	}
</style>
<body bgcolor="white">
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	if (!$limit) {
		$limit=100;
	}
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	$total=$this->store->count($this->store->find("", $crit));
	$this->find(".",$crit, "browse.nav.icons.show.phtml", "", $limit, $offset);
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
?>
</body>
<?php
	}
?>