<?php
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
?>
<form action="classic.config.priority.save.phtml">
	<input type="hidden" name="arReturnPage" value="<?php echo htmlspecialchars($ARCurrent->arReturnPage); ?>">
	<table border="0" cellspacing="0" bgcolor="#EEEEEE" width="100%">
	<tr>
		<td>
			<font face="helvetica,sans-serif"><?php echo $ARnls["value"]; ?></font>			 
		</td><td>
			<input type="text" name="priority" value="<?php echo $this->priority; ?>" size="10" maxlength="10">
		</td><td>
			<input type="submit" name="Update" value="<?php echo $ARnls["update"]; ?>">
		</td>
	</tr>
	</table>
</form> 
<?php
	}
?>