<?php
  /******************************************************************
   save.phtml					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: $newtype, $newfilename
   Grant needed: add or edit
   Interface/Widget: all
   Global variables: none

   This template checks the input from form.phtml, sets the 
   corresponding values in a data object ($newdata), adds the proper
   values to its properties and includes the common save code to save
   this data as a new object or as an update of this object 
   (depending on $newtype, if $newtype is set a new object will be 
   saved.)

   no result.
 
  ******************************************************************/
  $this->call("system.save.data.phtml",$arCallArgs);
  if (!$this->error) {
    if (!$arReturnPage) {
      $arReturnPage=$this->store->root.$parent; 
    }
    Header("Location: $arReturnPage");
  } else {
    $this->call("show.error.phtml");
  }
?>