<?php
	/******************************************************************
	 classic.config.nls.save.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arReturnPage
	 Grant needed: "config"
	 Global variables: none

	 This template is a wrapper around system.save.nls.phtml the language (nls)
	 configuration.
 
	 No return value.
	
	******************************************************************/

	if ($this->Checklogin("config") && $this->CheckConfig()) {
		$this->call("system.save.nls.phtml",$arCallArgs);
		if (!$this->error) {
			ldRedirect($arReturnPage);
			?>
				<a href="<?php echo $arReturnPage; ?>">Continue</a>
			<?php
		} else {
			$this->call("show.error.phtml");
		}
	}
?>