<?php
	/******************************************************************
	 classic.config.phtml                                  Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: "config"
	 Global variables: none

	 This displays the user interface for the configuration of the 
	 current object (cache, templates, grants).

	 No return value.
	
	******************************************************************/
	if ($this->CheckLogin("config")) {
		$ARCurrent->returnpage=$this->store->root.$this->path."config.phtml";
?>
<html>
<head>
<title><?php printf($ARnls["configure"],$nlsdata->name); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
</head>
<body bgcolor="white">
<table border="0" width="100%" cellspacing="4" vspace="10" hspace="10">
<tr>
	<td bgcolor="#404074" colspan="2">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["grantsforobject"]; ?></b> ( <?php echo $this->path; ?> )</font>
	</td>
</tr>
<tr>
	<form name="grantsform" action="classic.config.grants.save.phtml">
	<td colspan="2">
		<input type="hidden" name="returnpage" value="<?php echo $ARCurrent->returnpage; ?>">
		<table border="0" width="100%" bgcolor="white" style="border: 2px inset;" cellspacing="0" cellpadding="2">
		<?php
			function DisplayGrants(&$grantslist, $type) {
				global $AR, $ARCurrent, $ARnls;
				if ($grantslist[$type] && is_array($grantslist[$type])) {
					ksort($grantslist[$type]);
					while (list($id, $grants)=each($grantslist[$type])) { // path was login en is weer login
						echo "<tr><td>";
						echo "<img src=\"".$AR->dir->images."icons/".$type.".gif\">";
						echo "<a href=\"savegrants.phtml?delete=true&type=$type&id=".RawUrlEncode($id).
								 "&returnpage=".RawUrlEncode($ARCurrent->returnpage).
								 "\" onClick=\"return confirm('".sprintf($ARnls["q:removeallgrants"],$id)."')\">$id</a></td>";
						echo "</td><td>";
						if ($grants && is_array($grants)) {
							ksort($grants);
							while (list($grant, $value)=each($grants)) {
								if ($value) { 
									echo "<a href=\"savegrants.phtml?delete=true&type=$type&id=".
										RawUrlEncode($id)."&grant=".
										RawUrlEncode($grant)."&returnpage=".
										RawUrlEncode($ARCurrent->returnpage).
										"\" onClick=\"return confirm('".sprintf($ARnls["q:removegrant"],$grant,$id).
										"')\">$grant</a> "; 
								} 
							}
						}
						echo "</td></tr>";
					}
				}
			}


			if ($data->grants && is_array($data->grants)) {
				DisplayGrants($data->grants,"pgroup");
				DisplayGrants($data->grants,"puser");
			}
		?>
		</table>
		<table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top: 5px;">
		<tr bgcolor="#EEEEEE">
			<td valign="middle">
				<?php echo $ARnls["user"]."/".$ARnls["group"]; ?>&nbsp;:
			</td><td valign="middle" >
				<?php
					$wgBrowsePath="/system/groups/";
					$wgBrowseName="path";
					$wgBrowseSize=18;
					include($this->store->code."widgets/browse/js.html");
					include($this->store->code."widgets/browse/form.html");
				?>
			</td><td valign="middle" >
				<?php echo $ARnls["grants"]; ?>&nbsp;:
			</td><td valign="middle" >
				<input type="text" name="newgrants" size="18" maxlength="50">
				<input type="submit" name="Add" value="<?php echo $ARnls["add"]; ?>">
			</td>
		</tr>
		</table>
	</td>
	</form>
</tr>
<tr>
	<td bgcolor="#404074">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["types"]; ?></b></font>
	</td>
	<td bgcolor="#404074" width="50%">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["caching"]; ?></b></font>
	</td>
</tr>
<tr>
	<form action="classic.config.types.save.phtml">
	<td valign="top">
		<table border="0" cellspacing="0" bgcolor="#EEEEEE" width="100%">
		<tr>
			<td>
				<font face="helvetica,sans-serif"><?php echo $ARnls["typetree"]; ?></font>			 
			</td><td>
				<font face="helvetica,sans-serif"><?php echo $ARnls["delete"]; ?></font>			 
			</td>
		</tr><tr>
			<td>
				<select name="typetree">
				<?php
					echo "<option value=\"inherit\">".$ARnls["inherit"]."</option>\n";
					$this->ls("/system/ariadne/typetree/","show.option.phtml","selected=".RawUrlEncode($data->typetree));
				?>
				</select>
			</td><td>
				<input type="submit" name="Update" value="<?php echo $ARnls["update"]; ?>">
			</td>
		</tr>
		</table>
	</td>
	</form> 
	<form action="classic.config.cache.save.phtml">
	<td valign="top" rowspan="3">
		<table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
		<tr>
			<td valign="top"><input type="radio" name="cache" value="0" <?php if (!$data->cacheconfig) { echo "checked"; } ?>></td>
			<td colspan="2">
				<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["inheritcache"]; ?></font></nobr>
			</td>
		</tr><tr>
			<td valign="top"><input type="radio" name="cache" value="1" <?php if ($data->cacheconfig>0 && $data->cacheconfig<999) { echo "checked"; } ?>></td>
			<td colspan="2">
				<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonrq."]; ?><br>
				<?php echo $ARnls["keepimage"]; ?> <input type="text" name="keepfor" size="2" maxlength="3" value="<?php if ($data->cacheconfig>0 && $data->cacheconfig<999) { echo $data->cacheconfig; } else { echo "2"; } ?>"> <?php echo $ARnls["hours"]; ?>.</nobr>
				</font>
			</td>
		</tr><tr>
			<td valign="top"><input type="radio" name="cache" value="999" <?php if ($data->cacheconfig>=999) { echo "checked"; } ?>></td>
			<td colspan="2">
				<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonch."]; ?></font></nobr>
			</td>
		</tr><tr>
			<td valign="top"><input type="radio" name="cache" value="-1" <?php if ($data->cacheconfig<0) { echo "checked"; } ?>></td>
			<td>
				<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["donotcache"]; ?></font></nobr>
			</td><td rowspan="2" valign="bottom" align="right">
				<input type="submit" name="Save" value="<?php echo $ARnls["save"]; ?>">
			</td>
		</tr><tr>
			<td><input type="checkbox" name="refresh" value="now"></td>
			<td>
				<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshnow"]; ?></font></nobr>
			</td>
		</tr>
		</table>
	</td>
	</form>	 
</tr><tr>
	<td bgcolor="#404074">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["language"]; ?></b></font>
	</td>
</tr><tr>
	<form action="classic.config.nls.save.phtml">
	<td>
		<table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
		<tr>
			<td colspan="2"><font face="helvetica,sans-serif">
			<input type="radio" name="inherit" value="1" <?php
				if (!$this->data->nlsconfig->list) { // set for this object
					echo "checked";		
				} 
			?>><?php echo $ARnls["inherit"]; ?>
			<input type="radio" name="inherit" value="0" <?php
				if ($this->data->nlsconfig->list) { // set for this object
					echo "checked";
				} 
			?>><?php echo $ARnls["use"]; ?> :</font>

			</td></tr><tr><td rowspan="2" valign="top" align="center"><font face="helvetica,sans-serif">
			<?php echo $ARnls["available"]; ?><br>
			<select multiple name="available[]">
			<?php
				if ($data->nlsconfig->list) { // acquired from parents
					$selected=$data->nlsconfig->list;
				}
				reset($AR->nls->list);
				while (list($key, $value)=each($AR->nls->list)) {
					$value=htmlentities($value);
					if ($selected[$key]) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?> 
			</select>
			
			</font></td><td align="center"><font face="helvetica,sans-serif">

			<?php echo $ARnls["default"]; ?><br>
			<select name="default">
			<?php
				unset($selected);
				reset($AR->nls->list);
				if ($data->nlsconfig->default) {
					$selected=$data->nlsconfig->default;
				}
				while (list($key, $value)=each($AR->nls->list)) {
					if ($selected==$key) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?>
			</select>

			</font></td></tr><tr><td valign="bottom" align="right"><font face="helvetica,sans-serif">

			<input type="submit" name="Update" value="<?php echo $ARnls["update"]; ?>">

			</font></td></tr></table>

	</td>
	</form>
</tr>
</table>
</body>
</html>
<?php 
	}
?>