<?php
	/******************************************************************
	 classic.config.phtml                                  Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: "config"
	 Global variables: none

	 This displays the user interface for the configuration of the 
	 current object (cache, templates, grants).

	 No return value.
	
	******************************************************************/
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$ARCurrent->arReturnPage=$this->store->get_config("root").$this->path."classic.config.phtml";
?>
<html>
<head>
<title><?php printf($ARnls["configure"],$nlsdata->name); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
</head>
<body bgcolor="white" onLoad="custom_init()">
<table border="0" width="100%" cellspacing="4" vspace="10" hspace="10">
<tr>
	<td bgcolor="#404074" colspan="2">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["grantsforobject"]; ?></b> ( <?php echo $this->path; ?> )</font>
	</td>
</tr>
<tr>
	<td colspan="2">
		<?php $this->call("classic.config.grants.form.phtml"); ?>
	</td>
</tr>
<tr>
	<td bgcolor="#404074">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["types"]; ?></b></font>
	</td>
	<td bgcolor="#404074">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["priority"]; ?></b></font>
	</td>
</tr>
<tr>
	<td valign="top">
		<?php $this->call("classic.config.types.form.phtml"); ?>
	</td>
	<td valign="top">
		<?php $this->call("classic.config.priority.form.phtml"); ?>
	</td>
</tr><tr>
	<td bgcolor="#404074">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["language"]; ?></b></font>
	</td>
	<td bgcolor="#404074" width="50%">&nbsp;
		<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["caching"]; ?></b></font>
	</td>
</tr><tr>
	<td valign="top">
		<?php $this->call("classic.config.nls.form.phtml"); ?>
	</td>
	<td valign="top">
		<?php $this->call("classic.config.cache.form.phtml"); ?>
	</td>
</tr><tr>
	<td bgcolor="#404074">
		&nbsp;<font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["customdata"]; ?></b></font>
	</td>
</tr><tr>
	<td valign="top" bgcolor="#EEEEEE">
		<?php 
			$this->call("edit.object.custom.form.phtml", 
							Array(
							"arReturnPage" => $this->path."classic.config.phtml"
							)); 
		?>
	</td>
</tr>
</table>
</body>
</html>
<?php 
	}
?>