<?php
	/******************************************************************
	 classic.config.cache.save.phtml                       Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arReturnPage 
	 Grant needed: none
	 Global variables: none

	 This template is a wrapper for the classic interface around 
	 system.save.cache.phtml

	 The template saves the cache and then redirects the browser to 
	 the classic.config.phtml template.

	 No return value.
	
	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$this->call("system.save.cache.phtml",$arCallArgs);
		if (!$this->error) {
			Header("Location: $arReturnPage");
			?>
				<a href="<?php echo $arReturnPage; ?>">Continue</a>
			<?php
		} else {
			$this->call("show.error.phtml");
		}
	}
?>