<?php
	/******************************************************************
	 classic.config.priority.save.phtml                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.priority.phtml
	 Grant needed: read
	 Global variables: none

	 This template is a wrapper around system.save.priority.phtml for 
	 the classic config interface.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$this->call("system.save.priority.phtml",$arCallArgs);
		if (!$this->error) {
			ldRedirect($arReturnPage);
			?>
				<a href="<?php echo $arReturnPage; ?>">Continue</a>
			<?php
		} else {
			$this->call("show.error.phtml");
		}
	}
?>