<?php
	/******************************************************************
	 classic.config.types.save.phtml                       Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.types.phtml
	 Grant needed: read
	 Global variables: none

	 This template is a wrapper around system.save.types.phtml for the
	 classic config interface.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
		$this->call("system.save.types.phtml",$arCallArgs);
		if (!$this->error) {
			ldRedirect($arReturnPage);
			?>
				<a href="<?php echo $arReturnPage; ?>">Continue</a>
			<?php
		} else {
			$this->call("show.error.phtml");
		}
	}
?>