<?php
	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
?>
<form action="classic.config.cache.save.phtml">
	<input type="hidden" name="arReturnPage" value="<?php echo htmlspecialchars($ARCurrent->arReturnPage); ?>">
	<table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
	<tr>
		<td valign="top"><input type="radio" name="cacheconfig" value="0" <?php if (!$data->config->cacheconfig) { echo "checked"; } ?>></td>
		<td colspan="2">
			<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["inheritcache"]; ?></font></nobr>
		</td>
	</tr><tr>
		<td valign="top"><input type="radio" name="cacheconfig" value="1" <?php if ($data->config->cacheconfig>0 && $data->config->cacheconfig<999) { echo "checked"; } ?>></td>
		<td colspan="2">
			<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonrq."]; ?><br>
			<?php echo $ARnls["keepimage"]; ?> <input type="text" name="keepfor" size="2" maxlength="3" value="<?php if ($data->config->cacheconfig>0 && $data->config->cacheconfig<999) { echo $data->config->cacheconfig; } else { echo "2"; } ?>"> <?php echo $ARnls["hours"]; ?>.</nobr>
			</font>
		</td>
	</tr><tr>
		<td valign="top"><input type="radio" name="cacheconfig" value="999" <?php if ($data->config->cacheconfig>=999) { echo "checked"; } ?>></td>
		<td colspan="2">
			<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonch."]; ?></font></nobr>
		</td>
	</tr><tr>
		<td valign="top"><input type="radio" name="cacheconfig" value="-1" <?php if ($data->config->cacheconfig<0) { echo "checked"; } ?>></td>
		<td>
			<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["donotcache"]; ?></font></nobr>
		</td><td rowspan="2" valign="bottom" align="right">
			<input type="submit" name="Save" value="<?php echo $ARnls["save"]; ?>">
		</td>
	</tr><tr>
		<td><input type="checkbox" name="refresh" value="now"></td>
		<td>
			<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshnow"]; ?></font></nobr>
		</td>
	</tr>
	</table>
</form>	 
<?php
	}
?>