<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<form name="grantsform" action="classic.config.grants.save.phtml">
	<input type="hidden" name="arReturnPage" value="<?php echo $ARCurrent->arReturnPage; ?>">
	<table border="0" width="100%" bgcolor="white" style="border: 2px inset;" cellspacing="0" cellpadding="2">
	<?php
		function DisplayGrants(&$grantslist, $type) {
			global $AR, $ARCurrent, $ARnls;
			if ($grantslist[$type] && is_array($grantslist[$type])) {
				ksort($grantslist[$type]);
				while (list($id, $grants)=each($grantslist[$type])) { // path was login en is weer login
					echo "<tr><td>";
					echo "<img src=\"".$AR->dir->images."icons/".$type.".gif\">";
					echo "<a href=\"classic.config.grants.save.phtml?delete=true&type=$type&id=".RawUrlEncode($id).
							 "&arReturnPage=".RawUrlEncode($ARCurrent->arReturnPage).
							 "\" onClick=\"return confirm('".sprintf($ARnls["q:removeallgrants"],$id)."')\">$id</a></td>";
					echo "</td><td>";
					if ($grants && is_array($grants)) {
						ksort($grants);
						while (list($grant, $value)=each($grants)) {
							if ($value) { 
								echo "<a href=\"classic.config.grants.save.phtml?delete=true&type=$type&id=".
									RawUrlEncode($id)."&grant=".
									RawUrlEncode($grant)."&arReturnPage=".
									RawUrlEncode($ARCurrent->arReturnPage).
									"\" onClick=\"return confirm('".sprintf($ARnls["q:removegrant"],$grant,$id).
									"')\">$grant</a> "; 
							} 
						}
					}
					echo "</td></tr>";
				}
			}
		}


		if ($data->grants && is_array($data->grants)) {
			DisplayGrants($data->grants,"pgroup");
			DisplayGrants($data->grants,"puser");
		}
	?>
	</table>
	<table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top: 5px;">
	<tr bgcolor="#EEEEEE">
		<td valign="middle">
			<?php echo $ARnls["user"]."/".$ARnls["group"]; ?>&nbsp;:
		</td><td valign="middle" >
			<?php
				$wgBrowsePath="/system/groups/";
				$wgBrowseName="path";
				$wgBrowseSize=18;
				include($this->store->code."widgets/browse/js.html");
				include($this->store->code."widgets/browse/form.html");
			?>
		</td><td valign="middle" >
			<?php echo $ARnls["grants"]; ?>&nbsp;:
		</td><td valign="middle" >
			<input type="text" name="newgrants" size="18" maxlength="50">
			<input type="submit" name="Add" value="<?php echo $ARnls["add"]; ?>">
		</td>
	</tr>
	</table>
</form>
<?php
	}
?>