<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<form action="classic.config.nls.save.phtml">
	<input type="hidden" name="arReturnPage" value="<?php echo htmlspecialchars($ARCurrent->arReturnPage); ?>">
	<table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
	<tr>
		<td colspan="2">
			<font face="helvetica,sans-serif">
			<input type="radio" name="inherit" value="1" <?php
				if (!$this->data->nlsconfig->list) { // set for this object
					echo "checked";		
				} 
			?>><?php echo $ARnls["inherit"]; ?>
			<input type="radio" name="inherit" value="0" <?php
				if ($this->data->nlsconfig->list) { // set for this object
					echo "checked";
				} 
			?>><?php echo $ARnls["use"]; ?> :</font>

		</td>
	</tr><tr>
		<td rowspan="2" valign="top" align="center">
			<font face="helvetica,sans-serif">
			<?php echo $ARnls["available"]; ?><br>
			<select multiple name="available[]">
			<?php
				if ($data->nlsconfig->list) { // acquired from parents
					$selected=$data->nlsconfig->list;
				}
				reset($AR->nls->list);
				while (list($key, $value)=each($AR->nls->list)) {
					if ($selected[$key]) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?> 
			</select>
			</font>
		</td><td align="center">
			<font face="helvetica,sans-serif">
			<?php echo $ARnls["default"]; ?><br>
			<select name="default">
			<?php
				unset($selected);
				reset($AR->nls->list);
				if ($data->nlsconfig->default) {
					$selected=$data->nlsconfig->default;
				}
				while (list($key, $value)=each($AR->nls->list)) {
					if ($selected==$key) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?>
			</select>
			</font>
		</td>
	</tr><tr>
		<td valign="bottom" align="right">
			<font face="helvetica,sans-serif">
			<input type="submit" name="Update" value="<?php echo $ARnls["update"]; ?>">
			</font>
		</td>
	</tr>
	</table>
</form>
<?php
	}
?>