<?php
	/******************************************************************
	 classic.config.grants.save.phtml                      Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arReturnPage 
	 Grant needed: none
	 Global variables: none

	 This is a wrapper around the system.save.grants.phtml template.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
		$this->call("system.save.grants.phtml",$arCallArgs);
		if (!$this->error) {
			ldRedirect($arReturnPage);
			?>
				<a href="<?php echo $arReturnPage; ?>">Continue</a>
			<?php
		} else {
			$this->call("show.error.phtml");
		}
	}
?>