<?php
	/******************************************************************
	 classic.toolbar.phtml							 Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays a set of tabs with links to the relevant
	 templates for the management environment. Links to templates for 
	 which the user hasn't got the needed grants will be grayed out,
	 but still available. 
	 When this template is fully loaded it will remove the 'Loading' 
	 message in the management interface.	 

	 No result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<HTML>
<HEAD>
<link rel="stylesheet" href="<?php echo $AR->dir->styles; ?>menu.css" type="text/css">
<style>
BODY {
	margin: 0px;
	padding: 0px;
}
</style>
<script>
<!--
	function ClearLoader() {
		top.LoadingDone();
		tofront(<?php
			switch($template) {

				case 'view.html':
					echo(2);
				break;

				case 'classic.search.phtml':
					echo(3);
				break;

				case 'classic.config.phtml':
					echo(4);
				break;

				case 'classic.edit.phtml':
					echo(5);
				break;

				case 'edit.object.layout.phtml':
					echo(6);
				break;

				case 'classic.new.phtml':
					echo(7);
				break;

				case 'classic.manage.html':
				default:
					echo(1);
				break;

			}
		?>);
	}

	infront=1;
	lefty=0;
	righty=2;

	function tofront(num) {

		if( document.images) {
			
			document.images ["lt"+infront].src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif";
			document.images ["t"+infront].src="<?php echo $AR->dir->images; ?>tabs/top5.gif";
			document.images ["rt"+infront].src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif";
			document.images ["l"+infront].src="<?php echo $AR->dir->images; ?>tabs/left5.gif";
			document.images ["r"+infront].src="<?php echo $AR->dir->images; ?>tabs/right5.gif";
			document.images ["lb"+infront].src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif";
			document.images ["b"+infront].src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif";
			document.images ["rb"+infront].src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif";
			
			if(lefty>0) {	
				document.images ["rt"+lefty].src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif";
				document.images ["r"+lefty].src="<?php echo $AR->dir->images; ?>tabs/right5.gif";
				document.images ["rb"+lefty].src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif";
			}

			if( righty < 8 ) {
				document.images ["l"+righty].src="<?php echo $AR->dir->images; ?>tabs/left5.gif";
				document.images ["lt"+righty].src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif";
				document.images ["lb"+righty].src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif";
			}

			lefty = num-1;
			righty = num+1;

			if(lefty>0) {
				document.images ["rt"+lefty].src="<?php echo $AR->dir->images; ?>tabs/top5.gif";
				document.images ["r"+lefty].src="<?php echo $AR->dir->images; ?>tabs/neighbour5.gif";
				document.images ["rb"+lefty].src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif";
			}

			if(righty<8) {
				document.images ["lt"+righty].src="<?php echo $AR->dir->images; ?>tabs/top5.gif";
				document.images ["l"+righty].src="<?php echo $AR->dir->images; ?>tabs/neighbour5.gif";
				document.images ["lb"+righty].src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif";
			}


			document.images ["lt"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_left_top5.gif";
			document.images ["t"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_top5.gif";
			document.images ["rt"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_right_top5.gif";
			document.images ["lb"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_left_bottom5.gif";
			document.images ["b"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_bottom5.gif";
			document.images ["rb"+num].src="<?php echo $AR->dir->images; ?>tabs/ontop_right_bottom5.gif";

		}

		infront=num;

	}

// -->
</script>
</HEAD>
<BODY bgcolor="#BFBFBF" TEXT="#000000" LINK="#000000" ALINK="#000000" VLINK="#000000" onLoad="ClearLoader()">
<base target="object">
<form>
<table width="100%" border="0" cellpadding="0" cellspacing="0" vspace="0" hspace="0">
<!-- Top row images -->
<tr>
	<!-- TAB 1 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_left_top5.gif" alt="" name="lt1" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_top5.gif" alt="" name="t1" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_right_top5.gif" alt="" name="rt1" width="5"height="5" border="0"></td>
	<!-- TAB 2 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="lt2" height="5" width="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t2" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt2" width="5" height="5" border="0"></td>
	<!-- TAB 3 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif" alt="" name="lt3" border="0" width="5" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t3" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt3" border="0" width="5" height="5"></td>
	<!-- TAB 4 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif" alt="" name="lt4" border="0" width="5" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t4" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt4" border="0" width="5" height="5"></td>
	<!-- TAB 5 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif" alt="" name="lt5" border="0" width="5" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t5" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt5" border="0" width="5" height="5"></td>
	<!-- TAB 6 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif" alt="" name="lt6" border="0" width="5" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t6" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt6" border="0" width="5" height="5"></td>
	<!-- TAB 7 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_top5.gif" alt="" name="lt7" border="0" width="5" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/top5.gif" alt="" name="t7" width="50" height="5"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_top5.gif" alt="" name="rt7" border="0" width="5" height="5"></td>
	<!-- REST -->
	<td rowspan="2" align="right" width="100%"><input type="text" name="path" size="40" style="width: 90%;" value="<?php echo $this->path; ?>"></td>
</tr>

<!-- Left & Right images and text of tabs -->
<tr>
	<!-- TAB 1 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l1" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(1); top.cacheTemplate='classic.manage.html';" class="category"
		href="classic.manage.html"><?php echo $ARnls["manage"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r1" width="5" height="20" border="0"></td>
	<!-- TAB 2 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/neighbour5.gif" alt="" name="l2" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(2); top.cacheTemplate='view.html'" class="category"
		href="view.html"><?php echo $ARnls["view"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r2" width="5" height="20" border="0"></td>
	<!-- TAB 3 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l3" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(3); top.cacheTemplate='classic.search.phtml';" 
		href="classic.search.phtml"><?php echo $ARnls["search"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r3" width="5" height="20" border="0"></td>
	<!-- TAB 4 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l4" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(4); top.cacheTemplate='classic.config.phtml';" href="classic.config.phtml"<?php
		if (!$AR->user->grants["config"]) {
			echo "><font color=\"#666666\""; 
		}
	?>><?php echo $ARnls["config"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r4" width="5" height="20" border="0"></td>
	<!-- TAB 5 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l5" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(5); top.cacheTemplate='classic.edit.phtml';" href="classic.edit.phtml?returnpage=<?php
		echo RawUrlEncode($this->store->root.$this->path)."\"";
		if (!$AR->user->grants["edit"] 
				|| (is_array($AR->user->grants["edit"]) && !$AR->user->grants["edit"][$this->type])) {
			echo "><font color=\"#666666\""; 
		}	
	?>><?php echo $ARnls["edit"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r5" width="5" height="20" border="0"></td>
	<!-- TAB 6 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l6" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(6); top.cacheTemplate='edit.object.layout.phtml';" href="edit.object.layout.phtml"<?php
		if (!$AR->user->grants["layout"]) {
			echo "><font color=\"#666666\""; 
		}	
	?>><?php echo $ARnls["layout"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r6" width="5" height="20" border="0"></td>
	<!-- TAB 7 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left5.gif" alt="" name="l7" width="5" height="20" border="0"></td>
	<td align="center"><a onClick="tofront(7); top.cacheTemplate='classic.new.phtml';" href="classic.new.phtml"<?php
		if (!$AR->user->grants["add"]) {
			echo "><font color=\"#666666\"";
		}
	?>><?php echo $ARnls["new"]; ?></a></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right5.gif" alt="" name="r7" width="5" height="20" border="0"></td>
	<!-- REST -->
</tr>

<!-- Bottom of Tabs --> 
<tr> 
	<!-- TAB 1 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_left_bottom5.gif" alt="" name="lb1" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_bottom5.gif" alt="" name="b1" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/ontop_right_bottom5.gif" alt="" name="rb1" width="5" height="5"border="0"></td>
	<!-- TAB 2 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="lb2" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b2" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb2" width="5" height="5" border="0"></td>
	<!-- TAB 3 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif" alt="" name="lb3" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b3" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb3" width="5" height="5" border="0"></td>
	<!-- TAB 4 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif" alt="" name="lb4" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b4" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb4" width="5" height="5" border="0"></td>
	<!-- TAB 5 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif" alt="" name="lb5" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b5" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb5" width="5" height="5" border="0"></td>
	<!-- TAB 6 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif" alt="" name="lb6" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b6" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb6" width="5" height="5" border="0"></td>
	<!-- TAB 7 -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/left_bottom5.gif" alt="" name="lb7" width="5" height="5" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" name="b7" height="5" width="50" border="0"></td>
	<td><img src="<?php echo $AR->dir->images; ?>tabs/right_bottom5.gif" alt="" name="rb7" width="5" height="5" border="0"></td>
	<!-- REST -->
	<td><img src="<?php echo $AR->dir->images; ?>tabs/bottom5.gif" alt="" border="0" width="100%" height="5"></td>
</tr>
</table>
</form>
</BODY>
</HTML>
<?php
	}
?>