<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<form action="classic.config.types.save.phtml">
	<input type="hidden" name="arReturnPage" value="<?php echo htmlspecialchars($ARCurrent->arReturnPage); ?>">
	<table border="0" cellspacing="0" bgcolor="#EEEEEE" width="100%">
	<tr>
		<td>
			<font face="helvetica,sans-serif"><?php echo $ARnls["typetree"]; ?></font>			 
		</td><td>
			<select name="typetree">
			<?php
				echo "<option value=\"inherit\">".$ARnls["inherit"]."</option>\n";
				$this->ls("/system/ariadne/typetree/","show.option.phtml",Array("selected" => $data->config->typetree));
			?>
			</select>
		</td><td>
			<input type="submit" name="Update" value="<?php echo $ARnls["update"]; ?>">
		</td>
	</tr>
	</table>
</form> 
<?php
	}
?>