<?php
	/******************************************************************
	 edit.object.cache.save.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.cache.phtml
	 Grant needed: none
	 Global variables: none

	 This template is a wrapper around the system.save.cache.phtml 
	 template.

	 No result
	
	******************************************************************/

	$this->call("system.save.cache.phtml");
	if (!$this->error) {
		?>
		<script>
			window.close();
		</script>
		<?php
	} else {
		$this->call("show.error.phtml");
	}
?>