<?php
	/******************************************************************
	 edit.object.cache.form.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $cacheconfig, $refresh, $keepfor
	 Grant needed: edit
	 Global variables: none

	 This template displays the cache configuration form.

	 If one of the arguments isn't set it will display the values from
	 the current object.
	 
	 no result

	******************************************************************/
	if ($this->CheckSilent("edit")) {
		$cacheconfig=$this->getdata("cacheconfig","none");
		$refresh=$this->getdata("refresh","none");
		$keepfor=$this->getdata("keepfor","none");
		if ($keepfor && $cacheconfig==1) {
			$cacheconfig=$keepfor;
		}
?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset id="cache">
		<legend><?php echo $ARnls["caching"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td valign="top"><input type="radio" name="cacheconfig" value="0" <?php if (!$cacheconfig) { echo "checked"; } ?>></td>
				<td>
					<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["inheritcache"]; ?></font></nobr>
				</td>
			</tr><tr>
				<td valign="top"><input type="radio" name="cacheconfig" value="1" <?php if ($cacheconfig>0 && $cacheconfig<999) { echo "checked"; } ?>></td>
				<td>
					<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonrq."]; ?><br>
					<?php echo $ARnls["keepimage"]; ?> <input type="text" name="keepfor" size="2" maxlength="3" value="<?php if ($cacheconfig>0 && $cacheconfig<999) { echo $cacheconfig; } else { echo "2"; } ?>"> <?php echo $ARnls["hours"]; ?>.</nobr>
					</font>
				</td>
			</tr><tr>
				<td valign="top"><input type="radio" name="cacheconfig" value="999" <?php if ($cacheconfig>=999) { echo "checked"; } ?>></td>
				<td>
					<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshonch."]; ?></font></nobr>
				</td>
			</tr><tr>
				<td valign="top"><input type="radio" name="cacheconfig" value="-1" <?php if ($cacheconfig<0) { echo "checked"; } ?>></td>
				<td>
					<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["donotcache"]; ?></font></nobr>
				</td>
			</tr><tr>
				<td><input type="checkbox" name="refresh" value="now" <?php if ($refresh) echo " checked"; ?>></td>
				<td>
					<nobr><font face="helvetica,sans-serif"><?php echo $ARnls["refreshnow"]; ?></font></nobr>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<?php
	}
?>