<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		global $HTTP_USER_AGENT;
		if	(	eregi(".*msie ([0-9]+).*",$HTTP_USER_AGENT, $regs) &&
				$regs[1] && 
				(intval($regs[1])>=4) && 
				($AR->user->data->editor!="text")
			) { //ie4+ && wysiwyg set as default editor
			include($this->store->code."widgets/htmledit/ie/edit.php");
		} else {
			if ($file) {
				$file.="/";
			}
?>
<html>
<head>
<script>
<!--

	function loadpage(root, path, file, name, language, type, value) {
		if (value) {
			document.editform.htmltext.value=value;
		} else if (window.opener && !window.opener.closed && window.opener.wgHTMLEditContent) {
			document.editform.htmltext.value=window.opener.wgHTMLEditContent.value;
		}
		document.editform.ContentLanguage=language;
		document.editform.htmltext.focus();
	}

	function checksubmit() {
		if (window.opener && window.opener.wgHTMLEditContent) {
			window.opener.wgHTMLEditContent.value=document.editform.htmltext.value;
			window.close();
			return false;
		} else {			
			return true;
		}
	}

// -->
</script>
</head>
<body bgcolor="white" onLoad="loadpage('<?php echo $root; ?>','<?php echo $path; ?>','<?php echo $file; ?>','<?php echo $name; ?>','<?php echo $language; ?>','<?php echo $language; ?>','<?php echo $content; ?>')">
<form name="editform" method="post" action="<?php echo $root.$path.$file."edit.".$name.".save.phtml"; ?>" onSubmit="return checksubmit();">
<input name="ContentLanguage" type="hidden" value="<?php echo $language; ?>">
<table width="100%" border="0" cellspacing="0"><tr>
	<td colspan="2">
		<textarea name="htmltext" cols="75" rows="24" wrap="soft"></textarea>
	</td>
</tr><tr bgcolor="#404074">
	<td>&nbsp;</td>
	<td align="right">
		<input type="button" name="cancel" value="Cancel" onClick="window.close()">
		<input type="submit" name="save" value="Save">
	</td>
</tr></table>
</form>
</body>
</html>
<?php
		}
	}
?>