<?php
  if ($this->CheckLogin("read")) {
?>
<HTML>
<HEAD>
<TITLE><?php echo $ARnls["search"]; ?></TITLE>
<script>
<!--

function View(object) {
  window.opener.top.View(object);
}

lastquery='';

//-->
</script>
<style>
  FRAME, FRAMESET {
    BORDER: 0;
  }
</style>
</HEAD>
<FRAMESET ROWS="30,150,*" BORDER="0" FRAMEBORDER="no" FRAMESPACING="0">
  <FRAME NAME="tabs" SRC="edit.find.tabs.phtml"  scrolling="no" marginwidth="0" marginheight="0" BORDER="0" FRAMEBORDER="no" FRAMESPACING="0">
  <FRAME NAME="searchframe" SRC="edit.find.context.phtml"  scrolling="no" marginwidth="0" marginheight="0" BORDER="0" FRAMEBORDER="no" FRAMESPACING="0">
  <FRAME NAME="results" SRC="edit.find.results.phtml" marginwidth="0" marginheight="0" BORDER="0" FRAMEBORDER="no" FRAMESPACING="0">
</FRAMESET>
</HTML>
<?php
  }
?>