<?php
	if ( ( 	($this->arIsNewObject && $this->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")) )
        && $this->CheckConfig()) {
		global $HTTP_USER_AGENT;
		if	(	eregi(".*msie ([0-9]+).*",$HTTP_USER_AGENT, $regs) &&
				$regs[1] && 
				(intval($regs[1])>=4) && 
				($AR->user->data->editor!="text")
			) { //ie4+ && wysiwyg set as default editor
			include($this->store->code."widgets/htmledit/ie/edit.php");
		} else {
			if ($file) {
				$file.="/";
			}
?>
<html>
<head>
<script>
<!--

	function loadpage(root, path, file, name, language, type, value) {
		if (value) {
			document.editform.htmltext.value=value;
		} else if (window.opener && !window.opener.closed && window.opener.wgHTMLEditContent) {
			document.editform.htmltext.value=window.opener.wgHTMLEditContent.value;
		}
		document.editform.ContentLanguage.value=language;
		document.editform.htmltext.focus();
	}

	function checksubmit() {
		if (window.opener && window.opener.wgHTMLEditContent) {
			window.opener.wgHTMLEditContent.value=document.editform.htmltext.value;
			window.close();
			return false;
		} else {			
			return true;
		}
	}

// -->
</script>
<?php
    include($this->store->code."widgets/wizard/classic.css");
?>
<style>
  TEXTAREA {
    width: 100%;
    height: 94%;
  }
</style>
</head>
<body bgcolor="#BFBFBF" onLoad="loadpage('<?php echo $root; ?>','<?php echo $path; ?>','<?php echo $file; ?>','<?php echo $name; ?>','<?php echo $language; ?>','<?php echo $language; ?>','<?php echo $content; ?>')">
<form name="editform" method="post" action="<?php echo $root.$path.$file."edit.".$name.".save.phtml"; ?>" onSubmit="return checksubmit();">
<input name="ContentLanguage" type="hidden" value="<?php echo $language; ?>">
<textarea name="htmltext" cols="75" rows="24" wrap="soft"></textarea>
<table width="100%" border="0" cellspacing="0">
  <tr>
	<td align="right">
		<input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close()">
		<input type="submit" name="save" value="<?php echo $ARnls["save"]; ?>">
	</td>
  </tr>
</table>
</form>
</body>
</html>
<?php
		}
	}
?>