<?php
	/******************************************************************
	 edit.object.types.form.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the form to select the typetree to be used
	 starting at this object.
	 
	 no result

	******************************************************************/

?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset id="types">
		<legend><?php echo $ARnls["types"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<span class="required"><?php echo $ARnls["typetree"]; ?> :</span>
				</td>
			</tr><tr>
				<td>
					<select name="typetree">
					<option value="inherit"><?php echo $ARnls["inherit"]; ?></option>
					<?php					
						$trees=$this->ls("/system/ariadne/typetree/","show.option.phtml",Array( "selected" => $data->typetree));
					?>
					</select>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
