<?php
	/******************************************************************
	 edit.priority.phtml                                   Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $wgWizNextStep, $wgWizCurrent, $wgWizControl
	 Grant needed: edit
	 Global variables: none

	 This template controls the priority dialog.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["save"]='edit.priority.save.phtml';
		$wgWizFlow[0]["cancel"]='js.window.close.phtml';
		$wgWizFlow[0]["template"]='edit.priority.form.phtml';
                
		$wgWizTitle=$ARnls["priority"];
        $wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'wizard/sections/config.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTabsTemplate=false;
		include($this->store->get_config("code")."widgets/wizard/new.html");

	}
?>