<?php
	/******************************************************************
	 edit.object.layout.higlight.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $type, $function, $template, $mode
	 Grant needed: layout
	 Global variables: none

	 This template displays an object template defined at the current 
	 object in a highlighted editor.

	 If the template is called without arguments, it will default to
	 an empty template with the class of the current object.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php printf($ARnls["edittemplate"],$function); ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");

	if (!($file=$template)) {
		if ($data->pinp[$type][$function][$language]) {
			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				$file=$templates->read($this->id, $template);
			}
		}
	}

	$file = str_replace("\r", "", $file);
	$file = str_replace("\n", "\\n", $file);
	$file = str_replace("'", "\'", $file);
	$file = str_replace("\t", "        ", $file);

	if( $newtype ) { 
		$type = $newtype; 
	}
	if( $newfunction ) {
		$function = $newfunction;
	}
	if( $newlanguage ) {
		$language = $newlanguage;
	}


?>
<script>
  function init() {
    <?php
	 if ($error) {
		 echo "alert('".AddCSlashes($error, ARESCAPE)."');\n";
	 }
    ?>
     editor.setContents('<?php echo $file; ?>');
    
    
  }

function template_submit() {
	document.forms[0].template.value = editor.getContents();
}

function mode_change() {
	document.forms[0].action = "edit.object.layout.form.phtml";
	if( document.forms[0].mode[document.forms[0].mode.selectedIndex].value == 'highlight' ) {
		document.forms[0].action = "edit.object.layout.highlight.phtml";
	}
	template_submit();
	document.forms[0].submit();
}

</script>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
</head>
<body onload="init();">
<?php
?>
<form onsubmit="template_submit();" action="edit.object.layout.save.phtml" method="post" style="height: 100%;">
<input type="hidden" name="type" value="<?php echo $type; ?>">
<input type="hidden" name="function" value="<?php echo $function; ?>">
<input type="hidden" name="language" value="<?php echo $language; ?>">
<table border="0" width="100%" cellspacing="0" height="5%">
	<tr>
		<td>
			<span class="required"><?php echo $ARnls["type"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["template"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["language"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["mode"]; ?></span>
		</td><td>
		</td>
	</tr><tr>
		<td>
			<select name="newtype">
			<?php
				$this->ls("/system/ariadne/types/", "show.option.value.phtml","selected=$type");
			?>
			</select>
		</td><td>
			<input type="text" name="newfunction" value="<?php echo $function; ?>">
		</td><td>
			<select name="newlanguage">
			<option value="any"><?php echo $ARnls["any"]; ?></option>
			<?php
				while (list($key, $value)=each($AR->nls->list)) {
					if ($language==$key) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?>
			</select>
		</td><td>
			<select name="mode" onchange="mode_change();">
				<option value="highlight" <?php if( $mode == "highlight" ) echo "selected"; ?>><?php echo $ARnls["highlight"]; ?></option>
				<option value="edit" <?php if( !$mode || $mode == "edit" ) echo "selected"; ?>><?php echo $ARnls["edit"]; ?></option>
			</select>
		</td><td>
			<?php 
				if ($data->templates[$type][$function][$language] || !$function) {
					$default=1;
				}
			?>
			<input type="checkbox" name="default" value="1" <?php 
				if ($default) { echo " checked"; } ?>>
			<span class="required"><nobr><?php echo $ARnls["default"]; ?></nobr></span>
		</td>
	</tr>
</table>
	
	
<table border="0" width="100%" height="82%" cellspacing="0">
<input type="hidden" name="template" value="">
<tr height="100%"><td>
<iframe name="editor" width="100%" height="100%" src="<?php echo $AR->dir->www; ?>widgets/helene/editor.html"></iframe>
</td></tr>
</table>

<table border="0" width="100%" height="10%" cellspacing="0">
<tr>
	<td colspan="2" valign="top">
		<input type="submit" name="next_cancel" value="<?php echo $ARnls["cancel"]; ?>">
		<input type="submit" name="next_delete" value="<?php echo $ARnls["delete"]; ?>" 
		 onClick="return confirm('<?php echo $ARnls["q:removethistemplate"]; ?>');">
	</td><td colspan="2" align="right" valign="top">
		<input type="submit" name="next_apply" value="<?php echo $ARnls["apply"]; ?>">	
		<input type="submit" name="next_save" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
<?php 
	} 
?>