<?php
	/******************************************************************
	 edit.object.custom.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: layout
	 Global variables: none

	 This template displays a list of Custom data fieldnames, and their
	 definition. Fields added here, can be used to add custom defined
	 data entry fields per class.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["customdata"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>dialog.css">
<style>
    #header {
        height: 48px;
        background-image: url('<?php echo $AR->dir->images; ?>wizard/header_banner.jpeg');
        background-repeat: no-repeat;
        background-color: #496799;
        background-position: bottom left;
        border: 0px;
        color: white;
        font-size: 14px;
        font-weight: bold;
        padding-right: 5px;
    }

</style>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
</head>
<body bgcolor="white" onload="custom_init();">
<table cellspacing="0" cellpadding="0" border="0" width="100%">
<tr>
  <td valign="middle" align="right" id="header" height="48">
    <?php echo $ARnls["customdata"]; ?><img src="<?php echo $AR->dir->images; ?>wizard/sections/config.gif" alt="" height="40" width="40" hspace="4" align="absmiddle">
  </td>
</tr>
</table>
<?php $this->call("edit.object.custom.form.phtml"); ?>
</body>
<?php
	}
?>