<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $wgWizNextStep, $wgWizCurrent, $wgWizControl
	 Grant needed: edit
	 Global variables: none

	 This template defines the wizard for editing an existing object.

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->code."widgets/wizard/code.php");

		$start="edit.object.data.form.phtml";
		$step1="edit.object.language.phtml";
		$finish="edit.object.data.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["template"]=$start;
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$step1;
			$wgWizFlow[$i]["next"]=$i-1;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
		
		$arLanguage=$this->getdata("arLanguage","none");
		if ($wgWizFlow[0]["current"]==2) { // =edit.object.language.phtml
			$arControl=$this->getdata("wgWizControl","none");
			if ($arControl==$ARnls["prev"]) { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>