<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		switch($next) {
			case $ARnls["apply"] :
				$returnpage="edit.object.layout.form.phtml?type=".RawUrlEncode($newtype).
					"&function=".RawUrlEncode($newfunction)."&language=".RawUrlEncode($newlanguage);
			case $ARnls["save"] :
				$this->call("system.save.layout.phtml",$arCallArgs);
				break;
			case $ARnls["delete"] :
				$this->call("system.delete.layout.phtml",$arCallArgs);
				break;
		}
		if (!$this->error) {
			if (!$returnpage) {
				$returnpage=$this->store->root.$this->path."edit.object.layout.phtml";
			}
			Header("Location: ".$returnpage);
		} else { 
?>
<body>
<script>
	alert('<?php echo AddSlashes($this->error); ?>');
	history.back();
</script>
</body>
<?php
		}
	}
?>