<?php
	/******************************************************************
	 edit.object.layout.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: layout
	 Global variables: none

	 This template displays a list of object templates defined at the
	 current object. It displays a list of clickable flags denoting the
	 different languages for which the template is defined, linked to
	 the template edit form for that template in that language.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["templates"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<style>
	.required {
		background-color: buttonface;
		border: 2px outset;
		padding: 2px;
		font-weight: bold;
	}	
	.required div {
		width: 100%;
	}
	td.type {
		padding-left: 2px;
	}
	a.button {
		border: 1px outset;
	}
	input {
		width: 75px;
	}
	.row0 td {
		background-color: white;
	}
	.row1 td {
		background-color: #EEEEEE;
	}
</style>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
</head>
<body bgcolor="white">
<script>
	if (document.all) {
		window.innerHeight=document.body.clientHeight;
		window.innerWidth=document.body.clientWidth;
	}	
</script>
<form action="edit.object.layout.form.phtml">
<table border="0" width="100%" align="center" cellspacing="2" vspace="10" hspace="10">
<tr>
	<td colspan="2" bgcolor="white" style="border: 2px inset; padding: 0px;"><script> 
			document.write('<div style="height:'+(window.innerHeight-50)+'px; overflow: auto; margin: 0px; border: 0px;">'); 
		</script><table border="0" bgcolor="white" width="100%" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="top" class="required">
				<div><?php echo $ARnls["type"]; ?></div>
			</td><td valign="top" colspan="2" class="required">
				<div><?php echo $ARnls["template"]; ?></div>
			</td><td valign="top" class="required">
				<div><?php echo $ARnls["language"]; ?></div>
			</td>
		</tr><?php
			if (($data->pinp) && is_array($data->pinp)) {
				$currcol=0;
				while (list($type, $values)=each($data->pinp)) {
					while (list($function, $templatelist)=each($values)) {	
						?><tr class="row<?php echo $currcol; ?>">
							<td class="type"><?php echo $type; ?>&nbsp;</td>
							<td align="center"><?php 
								if (!$data->templates[$type][$function]) {
									echo "<img src='{$AR->dir->images}local.gif' alt='local' height='12' width='11'>";	
								}
							?></td>
							<td><?php echo $function; ?></td>
							<td><?php
								ksort($templatelist);
								reset($templatelist);
								while (list($language, $template)=each($templatelist)) {
									$flag="<img src=\"".$AR->dir->images."nls/small/$language.gif\" alt=\"".$AR->nls->list[$language]."\" border=\"0\">";
									echo "<a class=\"button\" href=\"edit.object.layout.form.phtml?type=".$type."&function=".RawUrlEncode($function).
										"&language=".$language."\">$flag</a> ";
								}
							?></td>
						</tr><?php
						$currcol++;
						$currcol=$currcol%2;
					}
				}
			}
		?><tr>
			<td></td>
		</tr>
		</table></div></td>
</tr><tr>
	<td valign="bottom"><input type="button" name="action" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();"></td>
	<td align="right" valign="bottom"><input type="hidden" name="type" value="<?php echo $this->type; ?>">
		<input type="submit" name="action" value="<?php echo $ARnls["new"]; ?>"></td>
</tr>
</table>
</form>
</body>
<?php
	}
?>