<?php
	/******************************************************************
	 edit.object.types.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $wgWizNextStep, $wgWizCurrent, $wgWizControl
	 Grant needed: config
	 Global variables: none

	 This template controls the flow of the types (typetree) selection
	 dialog.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("config") && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["save"]='edit.object.types.save.phtml';
		$wgWizFlow[0]["cancel"]='js.window.close.phtml';
		$wgWizFlow[0]["template"]='edit.object.types.form.phtml';
                
		$wgWizTitle=$ARnls["types"];		
        $wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'wizard/sections/config.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTabsTemplate=false;
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>