<?php
	/******************************************************************
	 edit.object.grants.save.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arReturnPage
	 Grant needed: config
	 Global variables: none

	 This template is a wrapper around system.save.grants.phtml.
	 
	 $arReturnPage is a fully qualified URL.

	 no result

	******************************************************************/
	$this->call("system.save.grants.phtml",$arCallArgs);
	if (!$this->error) {
		ldRedirect($arReturnPage);
		?>
			<a href="<?php echo $arReturnPage; ?>">Continue</a>
		<?php
	} else {
		$this->call("show.error.phtml");
	}
?>