<?php
	/******************************************************************
	 edit.object.cache.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template manages the flow of the cache configuration wizard.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");

		$start="edit.object.cache.form.phtml";
		$finish="edit.object.cache.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["save"]='edit.object.cache.save.phtml';
		$wgWizFlow[0]["cancel"]='js.window.close.phtml';
		$wgWizFlow[0]["template"]='edit.object.cache.form.phtml';
                
		$wgWizTitle=$ARnls["caching"];
        $wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'wizard/sections/cache.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTabsTemplate=false;
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>