<?php
  if ($this->CheckLogin("layout")) {
    if (ereg("\.phtml$",$function)) {
      $error=$ARnls["err:cannotedit.phtml"];
      include($this->store->code."includes/error.phtml");
    } else {
?>
<body bgcolor="white">
<br>
<h3><?php printf($ARnls["layoutfor"],$data->name); ?></h3>
<table border="0" width="100%" cellpadding="4" bgcolor="#EEEEEE" vspace="10" hspace="10">
<tr>
  <td bgcolor="#404074" colspan="2">&nbsp;
    <font face="helvetica,sans-serif" color="white"><b><?php printf($ARnls["edittemplate"],$function); ?></b></font>
  </td>  
</tr><tr>
  <td colspan="2">
    <form action="CompileTemplate.phtml" method="post">
    <input type="hidden" name="type" value="<?php echo $type; ?>">
    <input type="hidden" name="function" value="<?php echo $function; ?>">
    <input type="hidden" name="language" value="<?php echo $language; ?>">
    <table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
    <tr><td colspan="2">
      <?php echo $ARnls["type"]; ?> :
      <select name="newtype">
      <?php
        $this->ls("/system/ariadne/types/", "ShowOption.phtml","selected=$type");
      ?>
      </select>
      <?php echo $ARnls["language"]; ?> :
      <select name="newlanguage">
      <?php
        while (list($key, $value)=each($AR->nls->list)) {
          if ($language==$key) {
            echo "<option value=\"$key\" selected>$value</option>\n";
          } else {
            echo "<option value=\"$key\">$value</option>\n";
          }
        }        
      ?>
      </select>
      <?php echo $ARnls["template"]; ?> :
      <input type="text" name="newfunction" value="<?php echo $function; ?>">
      <?php echo $ARnls["setasdefault"]; ?>
      <?php 
        if ($data->templates[$type][$function][$language]) {
          $default=1;
        }
      ?>
      <input type="radio" name="default" value="1" <?php 
        if ($default) { echo " checked"; } ?>> <?php echo $ARnls["yes"]; ?>
      <input type="radio" name="default" value="0" <?php 
        if (!$default) { echo " checked"; } ?>> <?php echo $ARnls["no"]; ?>
      </td>
    </tr><tr>
      <td colspan="2">
      <textarea cols="78" rows="20" name="template" wrap="off"><?php
        if ($data->pinp[$type][$function][$language]) {
          $template=$this->store->files."templates".$data->pinp[$type][$function][$language].".pinp";
          if (file_exists($template)) {
            $file=file($template);
	    $file=implode("",$file);
	    $file=ereg_replace("&","&amp;",$file);
            $file=ereg_replace("<","&lt;", ereg_replace(">","&gt;",$file));
	    echo $file;
          }
        }
      ?></textarea>
      </td>
    </tr><tr>
      <td>
        <input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">
        <input type="submit" name="next" value="<?php echo $ARnls["delete"]; ?>" 
         onClick="return confirm('<?php echo $ARnls["q:removethistemplate"]; ?>');">
      </td><td align="right">
        <input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">  
      </td>
    </tr>
    </table>    
    </form>
  </td>
</tr>
</table>
</body>
<?php 
    }
  } 
?>