<?php
	/******************************************************************
	 edit.priority.form.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the form to enter the priority of this node.
	 
	 no result

	******************************************************************/

?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset>
		<legend><?php echo $ARnls["priority"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<span class="required"><?php echo $ARnls["value"]; ?> :</span>
				</td>
			</tr><tr>
				<td>
					<input type="text" name="priority" value="<?php echo $this->priority; ?>" size="10" maxlength="10">
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["priority"].focus();
	}
</script>
