<?php
	/******************************************************************
	 edit.object.nls.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["save"]='edit.object.nls.save.phtml';
		$wgWizFlow[0]["cancel"]='js.window.close.phtml';
		$wgWizFlow[0]["template"]='edit.object.nls.form.phtml';
                
		$wgWizTitle=$ARnls["language"];		
        $wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'wizard/sections/nls.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTabsTemplate=false;
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>