<?php
	/******************************************************************
	 edit.object.layout.form.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $type, $function, $template
	 Grant needed: layout
	 Global variables: none

	 This template displays an object template defined at the current 
	 object in an editable textarea.

	 If the template is called without arguments, it will default to
	 an empty template with the class of the current object.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php printf($ARnls["edittemplate"],$function); ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
</head>
<body>
<script>
	if (document.all) {
		window.innerHeight=document.body.clientHeight;
		window.innerWidth=document.body.clientWidth;
	}	
	document.write('<style> .full { width: '+(window.innerWidth-25)+'px; height: '+(window.innerHeight-100)+'px; } </style>');
</script>
<table border="0" width="100%" cellspacing="0">
<form action="edit.object.layout.save.phtml" method="post">
<tr>
	<td colspan="2">
		<input type="hidden" name="type" value="<?php echo $type; ?>">
		<input type="hidden" name="function" value="<?php echo $function; ?>">
		<input type="hidden" name="language" value="<?php echo $language; ?>">
		<table border="0" width="100%" height="75%" cellspacing="0">
		<tr><td>
			<span class="required"><?php echo $ARnls["type"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["template"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["language"]; ?></span>
		</td><td>
		</td></tr>
		<tr><td>
			<select name="newtype">
			<?php
				$this->ls("/system/ariadne/types/", "show.option.value.phtml","selected=$type");
			?>
			</select>
		</td><td>
			<input type="text" name="newfunction" value="<?php echo $function; ?>">
		</td><td>
			<select name="newlanguage">
			<option value="any"><?php echo $ARnls["any"]; ?></option>
			<?php
				while (list($key, $value)=each($AR->nls->list)) {
					if ($language==$key) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?>
			</select>
		</td><td>
			<?php 
				if ($data->templates[$type][$function][$language] || !$function) {
					$default=1;
				}
			?>
			<input type="checkbox" name="default" value="1" <?php 
				if ($default) { echo " checked"; } ?>>
			<span class="required"><nobr><?php echo $ARnls["default"]; ?></nobr></span>
		</td>
		</tr><tr>
			<td colspan="4">
			<textarea class="full" cols="78" rows="20" name="template" wrap="off"><?php
				if ($data->pinp[$type][$function][$language]) {
					$template=$this->store->files."templates".$data->pinp[$type][$function][$language].".pinp";
					if (file_exists($template)) {
						$file=file($template);
			$file=implode("",$file);
			$file=ereg_replace("&","&amp;",$file);
						$file=ereg_replace("<","&lt;", ereg_replace(">","&gt;",$file));
			echo $file;
					}
				}
			?></textarea>
			</td>
		</tr><tr>
			<td colspan="2">
				<input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">
				<input type="submit" name="next" value="<?php echo $ARnls["delete"]; ?>" 
				 onClick="return confirm('<?php echo $ARnls["q:removethistemplate"]; ?>');">
			</td><td colspan="2" align="right">
				<input type="submit" name="next" value="<?php echo $ARnls["apply"]; ?>">	
				<input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">	
			</td>
		</tr>
		</table>		
	</td>
</tr>
</form>
</table>
</body>
<?php 
	} 
?>