<?php
	/******************************************************************
	 edit.object.language.tabs.phtml                       Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays a tablist of available languages
	 to be used in the flow of an object edit wizard.

	 no result

	******************************************************************/

	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<ul id="tabnav">
<?php
	$arLanguage=$this->getdata('arLanguage');
    if (!$AR->user->data->languagelist) {
      // make sure at least one language is available for editing
      $languagelist=Array($AR->user->data->language => $AR->nls->list[$AR->user->data->language]);
    } else {
      $languagelist=$AR->user->data->languagelist;
    }
    if (!$languagelist[$arLanguage]) {
      // make sure the currently selected language is also available at all times
      $languagelist[$arLanguage]=$AR->nls->list[$arLanguage];
    }
	$languages=array_intersect(array_keys($languagelist), array_keys(array_merge($ARConfig->nls->list, $this->data->config->nls->list)));
	$count=count($languages);
	while (list($key, $nlskey)=each($languages)) {
		$language=$AR->nls->list[$nlskey];
		if (($this->data->config->nls->list[$nlskey]) || ($this->getdata('name',$nlskey))) {
			$image=$AR->dir->images."nls/small/".$nlskey.".gif";
		} else {
			$image=$AR->dir->images."nls/small/faded/".$nlskey.".gif";
		}
		if ($nlskey==$arLanguage) {
			$class="tab-selected";
			$image=$AR->dir->images."nls/small/".$nlskey.".gif";
		} else {
			$class="tab";
		}
		echo "<li class=\"$class\"><a href=\"javascript:switchLanguage('$nlskey');\">";
		echo "<img src=\"$image\" alt=\"$language\" border=\"0\">";
		if (($count<10) && ($count>4)) {
			echo "&nbsp;".$nlskey;
		} else if ($count<=4) {
			echo "&nbsp;".$language;
		}
		echo "</a>";
	}
?>
</ul>
<?php
	}
?>