<?php
	/******************************************************************
	 edit.object.html.link.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $src
	 Grant needed: read
	 Global variables: none

	 This template displays a hyperlink dialog window for the MSIE WYSIWYG
	 HTML editor.

	 It is meant to be called via a (MSIE specific) showModalDialog()
	 On submit it calls the javascript function LINK_set() in the 
	 opener window, with an array with the new values.
	 
	 no result

	******************************************************************/

	$ARCurrent->nolangcheck=true;
	if ($this->CheckLogin("read") && $this->CheckConfig()) {

		$settings=$this->call("editor.ini");

		include($this->store->get_config("code")."nls/".$this->reqnls);
		include($this->store->get_config("code")."nls/ieedit.".$this->reqnls);

?>
<HTML>
<HEAD>
<title><?php echo $ARnls["e_hyperlink"]; ?></title>
<style>
TD {
	FONT: 11px arial, helvetica, sans-serif;
}
INPUT {
	FONT: 11px arial, helvetica, sans-serif;
	MARGIN: 2px 4px 2px 4px;
	WIDTH: 50px;
}
SELECT {
	FONT: 11px arial, helvetica, sans-serif;
	MARGIN: 2px 4px 2px 4px;
	WIDTH: 75px;
}
BODY 	{
	FONT: 11px arial, helvetica, sans-serif;
	BORDER: 0;
	BACKGROUND-COLOR: buttonface;
	PADDING: 0px;
	MARGIN: 7px;
}
.button {
	width:75px;
	margin-left: 10px;
}
.alternate {
	width: 235px;
}
.fieldset {
	width: 245px;
}
.layout {
	width: 75px;
}
.url {
	width: 225px;
}
</style>

<script language="javascript" type="text/javascript">
// Some global instances, this will be filled later
var tinyMCE = null, tinyMCELang = null;

function TinyMCE_Popup() {
};

TinyMCE_Popup.prototype = {
	findWin : function(w) {
		var c;

		// Check parents
		c = w;
		while (c && (c = c.parent) != null) {
			if (typeof(c.tinyMCE) != "undefined")
				return c;
		}

		// Check openers
		c = w;
		while (c && (c = c.opener) != null) {
			if (typeof(c.tinyMCE) != "undefined")
				return c;
		}

		// Try top
		if (typeof(top.tinyMCE) != "undefined")
			return top;

		return null;
	},

	init : function() {
		var win = window.opener ? window.opener : window.dialogArguments, c;
		var inst;

		if (!win)
			win = this.findWin(window);

		if (!win) {
			alert("tinyMCE object reference not found from popup.");
			return;
		}

		window.opener = win;
		this.windowOpener = win;
		this.onLoadEval = "";

		// Setup parent references
		tinyMCE = win.tinyMCE;
		tinyMCELang = win.tinyMCELang;

		inst = tinyMCE.selectedInstance;
		this.isWindow = tinyMCE.getWindowArg('mce_inside_iframe', false) == false;

		if (this.isWindow)
			window.focus();
	}
};

// Setup global instance
var tinyMCEPopup = new TinyMCE_Popup();

tinyMCEPopup.init();
</script>

<SCRIPT LANGUAGE=JavaScript>
<!--
function IsDigit()
{
	return ((event.keyCode >= 48) && (event.keyCode <= 57))
}
// -->
</SCRIPT>

<SCRIPT LANGUAGE=JavaScript>
<!--
	var attributes = Array();

	function doSubmit(form) {
                document.getElementById("realform").contentWindow.doSubmit();
	}

	function arGetAttributes() {
		return attributes;
	}

	function init() {
		var defaultType='<?php echo current($settings["hyperlink"]); ?>';
		var allTypes=new Array();
		<?php
			reset($settings["hyperlink"]);
			while (list($key, $value)=each($settings["hyperlink"])) {
				echo "		allTypes['$key']='$value';\n";
			}
		?>

                attributes['href'] = tinyMCE.getWindowArg('href');
                attributes['target'] = tinyMCE.getWindowArg('target');
                attributes['title'] = tinyMCE.getWindowArg('title');
                attributes['onclick'] = tinyMCE.getWindowArg('onclick');
                attributes['style_class'] = tinyMCE.getWindowArg('style_class');
                attributes['ar:path'] = tinyMCE.getWindowArg('arpath');
                attributes['ar:type'] = tinyMCE.getWindowArg('artype');
		attributes['ar:nls'] = tinyMCE.getWindowArg('arnls');
		attributes['name'] = tinyMCE.getWindowArg('arname');

		var ar_type = attributes['ar:type'];

		if (ar_type && allTypes[ar_type]) {
			arType=allTypes[ar_type];
		} else {
			arType=defaultType;
		}
		document.getElementById("realform").src= arType;
	}

	function arSetReturnVal(arr) {
                var target, artype, arpath, arnls;

                if (arr['attributes'][0]) {
                        artype = arr["attributes"][0].value;
                }
                if (arr['attributes'][1]) {
                        arpath = arr["attributes"][1].value;
                }
                if (arr['attributes'][2]) {
                        arnls = arr["attributes"][2].value;
                }
                if (arr['attributes'][3]) {
                        target = arr["attributes"][3].value;
                }

                tinyMCE.themes['advanced']._insertLink(arr["URL"], target, arr["title"], null, arr["style_class"], artype, arpath, arnls, arr["name"]);
                //top.window.returnValue = arr;
	}

	function arCloseWindow() {
		//alert(top.window.returnValue['URL']);
		window.close();
	}

// -->
</SCRIPT>
</HEAD>
<BODY SCROLL=NO onLoad="init()">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<form onSubmit="doSubmit(this)">
<tr>
	<td>
		<fieldset id="hyperlink">
		<legend><?php echo $ARnls["e_hyperlink_information"]; ?></legend>
		<iframe id="realform" name="realform" style="margin: 0px; padding: 0px; height: 100px; width: 370px;" frameborder="no" src="javascript:">
		</iframe>
		</fieldset>
	</td>
	<td valign="top"><input type="button" name="ok" value="<?php echo $ARnls["ok"]; ?>" class="button" onClick="doSubmit(this.form);"><BR>
        <input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();" class="button"></td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>