<?php
	/******************************************************************
	 edit.object.nls.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->code."widgets/wizard/code.php");

		$start="edit.object.nls.form.phtml";
		$finish="edit.object.nls.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["caching"];
		$wgWizFlow[$i]["template"]=$start;
		$wgWizFlow[$i]["save"]=$i+1;
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;

		$wgWizTitle=$ARnls["language"];		
		include($this->store->code."widgets/wizard/small.html");
	}
?>