<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["owner"]; ?></title>
<?php
	include($this->store->get_config("code")."widgets/wizard/classic.css");
?>
<script>
	function init() {
	}
</script>
<style>
	form {
		height: 100%;
		margin: 0px;
		padding: 0px;
		border: 0px;
	}
	input.wgBrowseInput {
		width: 150px;
	}
</style>
</head>
<body onLoad="init()">
<form action="<?php echo $currentpath; ?>edit.config.owner.save.phtml" name="ownerform">
<input type="hidden" name="action" value="setowner">
<table border="0" width="100%" height="100%" cellspacing="0" cellpadding="2">
<?php
	$server_name=preg_replace("|^[htps:/]*/|i","",$AR->host);
	if ($_SERVER["HTTP_HOST"]==$server_name) {
		$currentpath=$this->store->get_config("root").$this->path;
	} else {
		$currentpath=$this->make_url();
	}
?>
<tr>
	<td align="center" colspan="2">
		<?php 
			echo $ARnls["change_owner"].":&nbsp;";
			$wgBrowseName="owner";
			$query = "object.implements='puser' and login.value='".AddSlashes($this->data->config->owner)."'";
			$wgBrowsePath = current($this->find('/system/users/', $query, 'system.get.path.phtml'));
			if (!$wgBrowsePath) {
				$wgBrowsePath = '/system/users/';
			}
			$wgBrowseFilter = 'puser';
			// $wgBrowseSize=30;
			include($this->store->get_config("code")."widgets/browse/js.html");
			include($this->store->get_config("code")."widgets/browse/form.html");
		?>
	</td>
</tr><tr>
	<td align="center">
		<input type="checkbox" name="recursive" value="true"><?php echo $ARnls["change_owner_recursive"];  ?>
	</td>
</tr><tr>
	<td align="left" valign="bottom">
		<input type="button" name="cancel" style="width: 100px" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();">
	</td><td align="right" valign="bottom">
		<input type="submit" name="submit" style="width: 100px" value="<?php echo $ARnls["save"]; ?>">
	</td>
</tr>
</table>
</form>
</body>
</html>
<?php
	}
?>