<?php
	/******************************************************************
	 edit.object.layout.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: layout
	 Global variables: none

	 This template displays a list of object templates defined at the
	 current object. It displays a list of clickable flags denoting the
	 different languages for which the template is defined, linked to
	 the template edit form for that template in that language.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["templates"] . ' ' . $this->path; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<style>
	.required {
		background-color: buttonface;
		border: 2px outset;
		padding: 2px;
		font-weight: bold;
	}	
	.required div {
		width: 100%;
	}
	td.type {
		width: 22px;
		padding-left: 2px;
	}
	a.button {
		border: 1px outset;
	}
	input {
		width: 75px;
	}
</style>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
<script src="<?php echo $AR->dir->www; ?>widgets/webfx/tablesort/tablesort.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->www; ?>widgets/webfx/tablesort/tablesort.css">
</head>
<body bgcolor="white">
<script>
	if (document.all) {
		window.innerHeight=document.body.clientHeight;
		window.innerWidth=document.body.clientWidth;
	}	
</script>
<form action="edit.object.layout.form.phtml" style="height: 95%">
<table border="0" width="100%" height="100%" align="center" cellspacing="2" vspace="10" hspace="10">
<tr>
	<td colspan="2" bgcolor="white" style="border: 2px inset; padding: 0px;" height="90%" valign="top">

	<div style="height: 100%; width: 100%; overflow: auto; margin: 0px; border: 0px;">
		<table border="0" background="<?php echo $AR->dir->www; ?>widgets/webfx/tablesort/tablebackground.jpg" bgcolor="white" width="100%" cellspacing="0" cellpadding="0" onclick="sortColumn(event)">
		<thead style="cursor:hand;">
		<tr>    
			<td valign="top" class="required">
				<?php echo $ARnls["type"]; ?>
			</td><td valign="top" class="required">
				<?php echo $ARnls["template"]; ?>
			</td><td valign="top" class="required">
				<?php echo $ARnls["language"]; ?>
			</td><td valign="top" class="required">
				<?php echo $ARnls["size"]; ?>
			</td><td valign="top" class="required">
				<?php echo $ARnls["modified"]; ?>
			</td>
		</tr></thead><tbody><?php
			$filestore = $this->store->get_filestore("templates");
			if (!function_exists("layout_sortfunc")) {
				function layout_sortfunc($a, $b) {
				   if ($a == $b) {
				       return 0;
				   }
				   return ($a < $b) ? -1 : 1;
				}
			}
			$pinp = $data->config->pinp;
			if (($pinp) && is_array($pinp)) {
				while (list($type, $values)=each($pinp)) {
					uksort($values, 'layout_sortfunc');	
					while (list($function, $templatelist)=each($values)) {
						ksort($templatelist);
						reset($templatelist);
						$language = key($templatelist);
						$onclick = "document.location='edit.object.layout.form.phtml?type=".$type."&function=".RawUrlEncode($function)."&language=".$language."'";
						
						
						?><tr valign="middle" onmouseover="style.backgroundColor='steelblue',style.color='white'" onmouseout="style.color='',style.backgroundColor='';" onclick="<?php echo $onclick; ?>">
						       <td align="left" valign="middle" style="height:23px">
								<img src="<?php echo $AR->dir->images. "icons/$type.gif"; ?>" width="20" height="20" align="absmiddle">
								<?php echo $type; ?>&nbsp;</td>
							<td align="left"><div style="display:none;"><?php echo $function; ?></div><?php  
								if (!$data->config->templates[$type][$function]) {
									echo "<img src='{$AR->dir->images}local.gif' alt='local' height='12' width='11'>";	
								}
							?>
							<?php echo $function; ?></td>
							<td><?php
								ksort($templatelist);
								reset($templatelist);
								while (list($language, $template)=each($templatelist)) {
									$flag="<img src=\"".$AR->dir->images."nls/small/$language.gif\" alt=\"".$AR->nls->list[$language]."\" border=\"0\">";
									echo "<a class=\"button\" href=\"edit.object.layout.form.phtml?type=".$type."&function=".RawUrlEncode($function).
										"&language=".$language."\">$flag</a> ";
								}
							?></td>
								<?php
									$tbasename = "$type.$function";
									reset($templatelist);
									$mtime = 0;
									$msize = 0;
									while (list($language, $template)=each($templatelist)) {
										$time = $filestore->mtime($this->id, "$tbasename.$language.pinp");
										if ($time > $mtime) {
											$mtime = $time;
										}
										$size = $filestore->size($this->id, "$tbasename.$language.pinp");
										if( $size > $msize) {
											$msize = $size;
										}

									}

								?>
							<td>
								<div style="display:none;"><?php printf("%010d", $msize); ?></div><?php echo $this->make_filesize($msize); ?>&nbsp;
							</td>
							<td>
								<div style="display:none;"><?php print $mtime; ?></div>
								<?php echo strftime("%H:%M", $mtime); ?>&nbsp;&nbsp;
								<?php echo strftime("%d %b %Y", $mtime); ?>&nbsp;
							</td>

						</tr><?php
					}
				}
			}
		?></tbody>
		</table>
	</div>
	</td>
</tr><tr>
	<td valign="bottom"><input type="button" name="action" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();"></td>
	<td align="right" valign="bottom"><input type="hidden" name="type" value="<?php echo $this->type; ?>">
		<input type="submit" name="action" value="<?php echo $ARnls["new"]; ?>"></td>
</tr>
</table>
</form>
</body>
<?php
	}
?>
