<?php
	/******************************************************************
	 edit.object.html.image.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $src, $alt, $align, $border, $hspace, $vspace
	 Grant needed: read
	 Global variables: none

	 This template displays an image dialog window for the MSIE WYSIWYG
	 HTML editor.

	 It is meant to be called via a (MSIE specific) showModalDialog()
	 On submit it calls the javascript function IMAGE_set() in the 
	 opener window, with an array with the new values.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		// show image select box with browse button 

		include($this->store->code."nls/ieedit.".$this->reqnls);

?>
<HTML>
<HEAD>
<title><?php echo $ARnls["e_picture"]; ?></title>
<style>
TD {
	FONT: 8pt sans-serif;
}
INPUT {
	FONT: 8pt sans-serif;
		MARGIN: 2px 4px 2px 4px;
		WIDTH: 50px;
}
SELECT {
	FONT: 8pt sans-serif;
		MARGIN: 2px 4px 2px 4px;
		WIDTH: 75px;
}
BODY 	{
	FONT: 8pt sans-serif;
	BORDER: 0;
	PADDING: 4px;
	BACKGROUND-COLOR: buttonface;
}
.button {
		width:75px;
}
.alternate {
		width: 235px;
}
.wgBrowseInput {
		width: 150px;
}
.wgBrowseButton {
		width: 75px;
}
.fieldset {
		height: 60px;
}
.layout {
		width: 75px;
}
</style>
<SCRIPT LANGUAGE=JavaScript>
<!--
function IsDigit()
{
	return ((event.keyCode >= 48) && (event.keyCode <= 57))
}
// -->
</SCRIPT>

<SCRIPT LANGUAGE=JavaScript>
<!--
	function doSubmit(form) {
		var arr = new Array();
		arr["src"] = form.imgsrc.value;
		arr["alt"] = form.alt.value;
		arr["border"] = form.border.value;
		arr["align"] = form.align.options[form.align.selectedIndex].value;
		arr["hspace"] = form.hspace.value;
		arr["vspace"] = form.vspace.value;
		window.returnValue=arr;
		window.close();
	}

	function init() {
		arr=window.dialogArguments;
		PictureForm.imgsrc.value=arr['src'];
		PictureForm.alt.value=arr['alt'];
		PictureForm.border.value=arr['border'];
		PictureForm.hspace.value=arr['hspace'];
		PictureForm.vspace.value=arr['vspace'];
		for (i=0; i<PictureForm.align.options.length; i++) {
			alignment=PictureForm.align.options[i];
			if (alignment.value==arr['align']) {
				alignment.selected=true;
				break;
			}
		}
	}
// -->
</SCRIPT>
</HEAD>
<BODY SCROLL=NO onLoad="init();">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<form method="post" name="PictureForm">
<tr>
	<td><?php echo $ARnls["e_picture_source"]; ?>:</td>
	<td><?php
		$wgBrowseName="imgsrc";
		$wgBrowsePath=$src;
		include($this->store->code."widgets/browse/js.html");
		include($this->store->code."widgets/browse/form.html");
	?></td>
	<td><input type="button" name="ok" value="<?php echo $ARnls["ok"]; ?>" class="button" onClick="doSubmit(this.form);"></td>
</tr><tr>
	<td><?php echo $ARnls["e_alternate_text"]; ?>:</td>
	<td><input id="alt" type="text" name="alt" value="<?php echo $alt; ?>" size="20" class="alternate"></td>
	<td><input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();" class="button"></td>
</tr><tr>
	<td colspan="2">
		<table><tr><td>
		<fieldset id="layout">
		<legend><?php echo $ARnls["e_layout"]; ?></legend>
		<table class="fieldset" align="left">
			<tr>
				<td><?php echo $ARnls["e_alignment"]; ?>:</td>
				<td><select name="align" class="layout">
					<?php
						$list["none"]="Not Set";
						$list["left"]="Left";
						$list["right"]="Right";
						$list["textTop"]="Texttop";
						$list["absMiddle"]="Absmiddle";
						$list["baseline"]="Baseline";
						$list["absBottom"]="Absbottom";
						$list["bottom"]="Bottom";
						$list["middle"]="Middle";
						$list["top"]="Top";				 
						while (list($key, $value)=each($list)) {
							echo "<option value=\"$key\"";
							if ($key==$align) { echo " selected"; }
							echo ">$value</option>";
						}
					?>
				</select></td>
			</tr><tr>
				<td><?php echo $ARnls["e_border_thickness"]; ?>:</td>
				<td><INPUT ID=border TYPE=TEXT SIZE=3 NAME=border ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $border; ?>" class="layout"></td>
			</tr>
		</table>
		</fieldset>
		</td><td>
		<fieldset id="spacing">
		<legend><?php echo $ARnls["e_spacing"]; ?></legend>
		<table class="fieldset" align="left">
			<tr>
				<td><?php echo $ARnls["e_horizontal"]; ?>:</td>
				<td><INPUT ID=hspace TYPE=TEXT SIZE=3 NAME=hspace ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $hspace; ?>"></td>
			</tr><tr>
				<td><?php echo $ARnls["e_vertical"]; ?>:</td>
				<td><INPUT ID=vspace TYPE=TEXT SIZE=3 NAME=vspace ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $vspace; ?>"></td>
			</tr>
		</table>
		</fieldset>
		</td></tr></table>
	</td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>