<?php
	if ($this->CheckLogin('read') && $this->CheckConfig()) {
		$filename=substr($this->path, strlen($this->parent), -1);
		if (!$filename) {
			$filename="root";
		}
		if (is_array($data->grants) && (count($data->grants['puser']) || count($data->grants['pgroup']))) {
			echo "<a class='hasgrants' href=\"javascript:showpath('".$this->path."','".$this->make_url()."');\">$filename</a> / ";
		} else {
			echo "<a class='hasnogrants' href=\"javascript:showpath('".$this->path."','".$this->make_url()."');\">$filename</a> / ";
		}
	}
?>