<?php
	/******************************************************************
	 edit.priority.save.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.priority.phtml
	 Grant needed: none
	 Global variables: none

	 This template is a wrapper around the system.save.priority.phtml
	 template.
	 
	 no result

	******************************************************************/

	$this->call("system.save.priority.phtml", $arCallArgs);
?>
<script>
  window.close();
</script>
