<?php
	/******************************************************************

	 no result.

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<fieldset id="cache">
		<legend><?php echo $ARnls["language"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<input type="radio" name="inherit" value="1" <?php
						if (!$this->data->config->nlsconfig->list) { // set for this object
							echo "checked";		
						} 
					?>><?php echo $ARnls["inherit"]; ?>
				</td><td>
					<input type="radio" name="inherit" value="0" <?php
						if ($this->data->config->nlsconfig->list) { // set for this object
							echo "checked";
						} 
					?>><?php echo $ARnls["use"]; ?> :</font>
				</td>
			</tr><tr>
				<td align="center" valign="top">
					<?php echo $ARnls["available"]; ?><br>
					<div align="left" style="width: 150px; border: inset 2px; height: 68px; overflow: auto; margin: 1px; padding: 1px;">
					<div style="margin: 1px; margin-left: 3px;">
					<?php
						$config=$ARConfig->cache[$this->parent];
						reset($config->nls->list);
						while (list($key, $value)=each($config->nls->list)) {
							echo $value."<br>";
						}
					?>
					</div>
					</div>
				</td>
				<td align="center" valign="top">
					<?php echo $ARnls["available"]; ?><br>
					<select multiple name="available[]" style="width: 150px; height: 70px;">
					<?php
					if ($data->config->nlsconfig->list) { // acquired from parents
						$selected=$data->config->nlsconfig->list;
					}
					reset($AR->nls->list);
					while (list($key, $value)=each($AR->nls->list)) {
						if ($selected[$key]) {
							echo "<option value=\"$key\" selected>$value</option>\n";
						} else {
							echo "<option value=\"$key\">$value</option>\n";
						}
					}				
				?> 
				</select>
			</td>
		</tr><tr>
				<td align="center" valign="top">
					<?php echo $ARnls["default"]; ?><br>
					<div align="left" style="width: 150px; border: inset 2px; padding: 0px; margin: 0px;">
						<div style="margin: 1px; margin-left: 3px; padding: 0px; border: 0px;">
						<?php echo $config->nls->list[$config->nls->default]; ?>
						</div>
					</div>
				</td>
				<td align="center" valign="top">
				<?php echo $ARnls["default"]; ?><br>
				<select name="default" style="width:150px;">
				<?php
					unset($selected);
					reset($AR->nls->list);
					if ($data->config->nlsconfig->default) {
						$selected=$data->config->nlsconfig->default;
					}
					if (!$selected) {
						$selected=$config->nls->default;
					}
					while (list($key, $value)=each($AR->nls->list)) {
						if ($selected==$key) {
							echo "<option value=\"$key\" selected>$value</option>\n";
						} else {
							echo "<option value=\"$key\">$value</option>\n";
						}
					}				
				?>
				</select>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<?php
	}
?>