<?php
	/******************************************************************
	 edit.priority.phtml                                   Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $wgWizNextStep, $wgWizCurrent, $wgWizControl
	 Grant needed: edit
	 Global variables: none

	 This template controls the priority dialog.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->code."widgets/wizard/code.php");

		$start="edit.priority.form.phtml";
		$finish="edit.priority.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["priority"];
		$wgWizFlow[$i]["template"]=$start;
		$wgWizFlow[$i]["save"]=$i+1;
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;

		$wgWizTitle=$ARnls["priority"];		
		include($this->store->code."widgets/wizard/small.html");
	}
?>