<?php
	/******************************************************************
	 edit.object.grants.save.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $returnpage
	 Grant needed: config
	 Global variables: none

	 This template is a wrapper around system.save.grants.phtml.
	 
	 $returnpage is a fully qualified URL.

	 no result

	******************************************************************/
	$this->call("system.save.grants.phtml");
	if (!$this->error) {
		Header("Location: $returnpage");
		?>
			<a href="<?php echo $returnpage; ?>">Continue</a>
		<?php
	} else {
		$this->call("show.error.phtml");
	}
?>