<?php
	/******************************************************************
	 edit.object.custom.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: layout
	 Global variables: none

	 This template displays a list of Custom data fieldnames, and their
	 definition. Fields added here, can be used to add custom defined
	 data entry fields per class.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["customdata"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>dialog.css">
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
</head>
<body bgcolor="white" onload="custom_init();">
<?php $this->call("edit.object.custom.form.phtml"); ?>
</body>
<?php
	}
?>