<?php
	/******************************************************************
	
	******************************************************************/

	$this->call("system.save.custom.phtml", $arCallArgs);
	if (!$this->error) {
		if ($arReturnPage) {
			ldHeader("Location: ".$this->store->get_config("root").$arReturnPage);
		} else {
		?>
			<script>
				if (window.opener) {
					window.close();
				}
			</script>
		<?php
		}
	} else {
		echo "<font color='red'>$this->error</font>";
	}
?>