<?php
	/******************************************************************
	 edit.object.html.link.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $src
	 Grant needed: read
	 Global variables: none

	 This template displays a hyperlink dialog window for the MSIE WYSIWYG
	 HTML editor.

	 It is meant to be called via a (MSIE specific) showModalDialog()
	 On submit it calls the javascript function LINK_set() in the 
	 opener window, with an array with the new values.
	 
	 no result

	******************************************************************/

	$ARCurrent->nolangcheck=true;
	if ($this->CheckLogin("read") && $this->CheckConfig()) {

		$settings=$this->call("editor.ini");

		include($this->store->get_config("code")."nls/".$this->reqnls);
		include($this->store->get_config("code")."nls/ieedit.".$this->reqnls);

?>
<HTML>
<HEAD>
<title><?php echo $ARnls["e_hyperlink"]; ?></title>
<style>
TD {
	FONT: 11px arial, helvetica, sans-serif;
}
INPUT {
	FONT: 11px arial, helvetica, sans-serif;
	MARGIN: 2px 4px 2px 4px;
	WIDTH: 50px;
}
SELECT {
	FONT: 11px arial, helvetica, sans-serif;
	MARGIN: 2px 4px 2px 4px;
	WIDTH: 75px;
}
BODY 	{
	FONT: 11px arial, helvetica, sans-serif;
	BORDER: 0;
	BACKGROUND-COLOR: buttonface;
	PADDING: 0px;
	MARGIN: 7px;
}
.button {
	width:75px;
	margin-left: 10px;
}
.alternate {
	width: 235px;
}
.fieldset {
	width: 245px;
}
.layout {
	width: 75px;
}
.url {
	width: 225px;
}
</style>
<SCRIPT LANGUAGE=JavaScript>
<!--
function IsDigit()
{
	return ((event.keyCode >= 48) && (event.keyCode <= 57))
}
// -->
</SCRIPT>

<SCRIPT LANGUAGE=JavaScript>
<!--
	function doSubmit(form) {
		realform.doSubmit();
	}

	function init() {
		var defaultType='<?php echo current($settings["hyperlink"]); ?>';
		var allTypes=new Array();
		<?php
			reset($settings["hyperlink"]);
			while (list($key, $value)=each($settings["hyperlink"])) {
				echo "		allTypes['$key']='$value';\n";
			}
		?>
		var ar_type=window.dialogArguments['ar:type'];
		if (window.dialogArguments['ar:type']) {
			var ar_type=window.dialogArguments['ar:type'];
		} else if (window.dialogArguments['ar_type']) {
			var ar_type=window.dialogArguments['ar_type'];
		} 
		if (ar_type && allTypes[ar_type]) {
			arType=allTypes[ar_type];
		} else {
			arType=defaultType;
		}
		document.all['realform'].src=arType;
	}

	function arCloseWindow() {
		window.close();
	}

	function arGetAttributes() {
		return window.dialogArguments;
	}

	function arSetReturnVal(returnval) {
		window.returnValue = returnval;
	}

// -->
</SCRIPT>
</HEAD>
<BODY SCROLL=NO onLoad="init()">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<form onSubmit="doSubmit(this)">
<tr>
	<td>
		<fieldset id="hyperlink">
		<legend><?php echo $ARnls["e_hyperlink_information"]; ?></legend>
		<iframe name="realform" style="margin: 0px; padding: 0px; height: 100px; width: 270px;" src="javascript:">
		</iframe>
		</fieldset>
	</td>
	<td valign="top"><input type="button" name="ok" value="<?php echo $ARnls["ok"]; ?>" class="button" onClick="doSubmit(this.form);"><BR>
        <input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();" class="button"></td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>