<?php
	if ($this->CheckLogin('config')) {
		if ($recursive) {
			$this->call('recurse.phtml', $arCallArgs);
		} else {
			$this->call('system.save.owner.phtml', Array('owner' => $owner));
			if ($this->error) {
				?>
				<script>
					alert('<?php echo AddCSlashes($this->error, ARESCAPE); ?>');
					history.back();
				</script>
				<?php
			} else {
				?>
				<script>
					if (top.window) {
						if (top.window.opener && top.window.opener.wgRecurseDone) {
							top.window.opener.wgRecurseDone();
						}
						top.window.close();
					} else {
						if (window.opener && window.opener.wgRecurseDone) {
							window.opener.wgRecurseDone();
						}
						window.close();
					}
				</script>
				<?php
			}
		}
	}
?>