<?php
  /******************************************************************
   edit.object.data.save.phtml			   Muze Ariadne v2.0b
   ------------------------------------------------------------------

   no result.
 
  ******************************************************************/
  $this->call("system.save.data.phtml",$arCallArgs);
  if ($this->error) {
?>
  <font color="red"><?php
    echo $this->error;
  ?></font><p>
<?php
  } else {
?>
  <script> 
    if (window.opener) {
      window.opener.objectadded('<?php echo $this->type; ?>','<?php echo $nlsdata->name; ?>','<?php echo $this->path; ?>'); 
      window.close();
    } 
  </script>
<?php
  }
?>