<?php
  /******************************************************************
   SetCache.phtml				   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'config.phtml'
   Arguments: $cache, $keepfor, $refresh
   Grant needed: "config"
   Interface/Widget: management
   Global variables: none

   This template is called by config.phtml and saves the cache 
   configuration. If the checkbox 'clear cache now' is checked in 
   config.phtml it will also call $this->ClearCache().
 
   $cache is an integer between -1 and 999. If $cache==1 then $cache
     will become $keepfor. The value of $cache is saved in 
     $data->cacheconfig.
   $keepfor is an integer between 1 and 999.
   $refresh is the string "now" or is not set. If $refresh is set, 
     the cache will be cleared for all objects and templates from 
     the current object in the tree and onwards.

   No return value.
  
  ******************************************************************/
  $donotcache=-1;
  $inherited=0;
  $onrequest=1;
  $onchange=999;  

  $cache=$this->getdata("cacheconfig","none");
  $refresh=$this->getdata("refresh","none");
  $keepfor=$this->getdata("keepfor","none");
  if ($this->CheckLogin("edit")) {
    if ($cache==$onrequest) {
      $cache=$keepfor;
    }
    $data->cacheconfig=$cache;
    $this->save($this->path, $this->type, $data, "");
    if ($refresh) {
      $this->ClearCache();
    }
  }
?>
<script>
  window.close();
</script>