<?php
	/******************************************************************
	 edit.object.html.image.phtml                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $src, $alt, $align, $border, $hspace, $vspace
	 Grant needed: read
	 Global variables: none

	 This template displays an image dialog window for the MSIE WYSIWYG
	 HTML editor.

	 It is meant to be called via a (MSIE specific) showModalDialog()
	 On submit it calls the javascript function IMAGE_set() in the 
	 opener window, with an array with the new values.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		// show image select box with browse button 

		include($this->store->code."nls/ieedit.".$this->reqnls);

?>
<HTML>
<HEAD>
<title><?php echo $ARnls["e_picture"]; ?></title>
<!-- this link element includes the css definitions that describes the tab pane -->
<link type="text/css" rel="stylesheet" href="<?php echo $AR->dir->www; ?>widgets/webfx/tabpane/css/tab.winclassic.css">
<link type="text/css" rel="stylesheet" href="<?php echo $AR->dir->www; ?>styles/wizard.menu.css">
<style type="text/css">

.dynamic-tab-pane-control {
	height: 85%;
}

.dynamic-tab-pane-control .tab-page {
	height:		100%;
	width:		100%;
}

html, body {
	background:	ThreeDFace;
}

form {
	margin:		0;
	padding:	0;
}

/* over ride styles from webfxlayout */

body {
	margin:		10px;
	width:		auto;
	height:		auto;
}

.dynamic-tab-pane-control h2 {
	text-align:	center;
	width:		auto;
}

.dynamic-tab-pane-control h2 a {
	display:	inline;
	width:		auto;
}

.dynamic-tab-pane-control a:hover {
	background: transparent;
}

TD {
	FONT: 8pt sans-serif;
}
INPUT {
	FONT: 8pt sans-serif;
		MARGIN: 2px 4px 2px 4px;
		WIDTH: 50px;
}
SELECT {
	FONT: 8pt sans-serif;
		MARGIN: 2px 4px 2px 4px;
		WIDTH: 75px;
}
BODY 	{
	FONT: 8pt sans-serif;
	BORDER: 0;
	PADDING: 4px;
	BACKGROUND-COLOR: buttonface;
}
.button {
		width:75px;
}
.alternate {
		width: 235px;
}
.wgBrowseInput {
		width: 150px;
}
.wgBrowseButton {
		width: 75px;
}
.fieldset {
		height: 60px;
}
.layout {
		width: 75px;
}
</style>
<script type="text/javascript" src="<?php echo $AR->dir->www; ?>widgets/webfx/tabpane/js/tabpane.js"></script>
<SCRIPT LANGUAGE=JavaScript>
<!--

	var tbContentEditOptions=new Array;
	var KeepPath=new Array;
        KeepPath[0]='';
        KeepPath[1]='';
        KeepPath[2]='';
        KeepPath[3]='http://';

	var KeepIndex=0;
	var ViewMode='icons';
	var browseTop='<?php echo $this->path; ?>';
	var CurrentPath=new String('<?php echo $path; ?>');
	var CurrentViewMode='<?php echo $mode; ?>';
	var CurrentFilter='<?php echo $filter; ?>';
	var CurrentLimit=50;
	var LastPath='<?php echo $this->path; ?>';

    var b_offset=0;
    var b_limit=CurrentLimit;
    var b_total=0;
    var b_page=0;

	var PreviewURL=false;
	var CurrentButton=0;

	function IsDigit() {
		return ((event.keyCode >= 48) && (event.keyCode <= 57))
	}

	function doSubmit(form) {
		var arr = new Array();
		if (PreviewURL) {
			arr["src"] = CurrentPath;
		} else {
			arr["src"] = CurrentPath+form.imgstyle.options[form.imgstyle.selectedIndex].value;
		}
		arr["alt"] = form.alt.value;
		arr["border"] = form.border.value;
		arr["align"] = form.align.options[form.align.selectedIndex].value;
		arr["hspace"] = form.hspace.value;
		arr["vspace"] = form.vspace.value;
		window.returnValue=arr;
		window.close();
	}

	function init() {
		arr=window.dialogArguments;
		CurrentPath=new String(arr['src']);
		if (CurrentPath.substr(0, <?php echo strlen($this->store->root); ?>)=='<?php echo $this->store->root; ?>') {
			PreviewURL=false;
		} else {
			if( CurrentPath.substr(0,4) == 'http' ) {
				PreviewURL=true;
			} else {
				PreviewURL=false;
			}
		}
		PictureForm.alt.value=arr['alt'];
		PictureForm.border.value=arr['border'];
		PictureForm.hspace.value=arr['hspace'];
		PictureForm.vspace.value=arr['vspace'];
		for (i=0; i<PictureForm.align.options.length; i++) {
			alignment=PictureForm.align.options[i];
			if (alignment.value==arr['align']) {
				alignment.selected=true;
				break;
			}
		}
		tbContentEditOptions=arr['editOptions'];
		if (tbContentEditOptions['browse']) {
			if (tbContentEditOptions['browse']['hideMenu']) {
				mnMenu.style.display='none';
			} else {
				if (tbContentEditOptions['browse']['hideCurrent']) {
					mnCurrent.style.display='none';
				}
				if (tbContentEditOptions['browse']['hidePhotobook']) {
					mnPhotobook.style.display='none';
				} else if (!tbContentEditOptions['browse']['hideCurrent'] && (tbContentEditOptions['photobook']['location']=='<?php echo $this->path; ?>' || tbContentEditOptions['photobook']['location']=='')) {
					mnPhotobook.style.display='none';
				}
				if (tbContentEditOptions['browse']['hideHome']) {
					mnHome.style.display='none';
				}
				if (tbContentEditOptions['browse']['hideURL']) {
					mnURL.style.display='none';
				}
			}
		} else if (!tbContentEditOptions['browse']['hideCurrent'] && tbContentEditOptions['photobook']['location']=='<?php echo $this->path; ?>') {
			mnPhotobook.style.display='none';
		}
		if (tbContentEditOptions['browse']['top']) {
			browseTop=escape(tbContentEditOptions['browse']['top']);
		}
		if (tbContentEditOptions['styles']) {
			var imgstyle=document.forms[0].imgstyle;
			document.forms[0].imgstyle.disabled=false;
			for (var i=imgstyle.length-1; i>=0; i--) {
				imgstyle.options[i]=null;
			}
			for (var i in tbContentEditOptions['styles']) {
				imgstyle.options[imgstyle.length]=new Option(i, tbContentEditOptions['styles'][i]);
				var test=new String(tbContentEditOptions['styles'][i]);
				if (CurrentPath.substr(CurrentPath.length-test.length, test.length)==test) {
					imgstyle.options[imgstyle.length-1].selected=true;
					CurrentPath=CurrentPath.substr(0, CurrentPath.length-test.length);
				}
			}
		} else {
			document.forms[0].imgstyle.disabled=true;
		}
		if( !PreviewURL ) {
			if( CurrentPath == '<?php echo $this->path; ?>' ) {
				mnCurrent.className='menuButtonCurrent';
				CurrentButton=mnCurrent;
				View(CurrentPath, '<?php echo $this->call("system.get.name.phtml"); ?>', true);
			} else {
				View(CurrentPath, 'Selected Picture', true);
			}
		} else {
			KeepPath[3]=CurrentPath;
			BrowseURL();
		}
		showPreview();
	}

	function View(path,name,top) {
		var inlist=-1;
		var newname="";
		
		if (document.forms[0].BrowseNav) {
			blist=document.forms[0].BrowseNav.options;
			if (top) { //item is the new top
				for (i=blist.length-1; i>=0; i--) {
					blist[i]=null;
				}
				blist[blist.length]=new Option(name, path);
			} else {
				for (i=0; i<blist.length; i++) {
					if (blist[i].value==path) {
						blist.selected=true;
						inlist=i;
					}
				}
				if (inlist==-1) {
					for (i=0; i<blist.length; i++) {
						newname+="   ";
					}
					newname+=name;
					blist[blist.length]=new Option(newname,path);
					blist[blist.length-1].selected=true;
				} else {
					for (i=blist.length-1; i>inlist; i--) {
						blist[i]=null;
					}
					blist[blist.length-1].selected=true;
				}
			}
		}
		CurrentPath=path;
		mnBrowse.location="<?php
			echo $this->store->root; ?>"+path+"browse.nav."+
			ViewMode+".phtml?filter="+escape(CurrentFilter);
		showPreview();
	}

	function browseTo(path, button, name) {
		PreviewURL=false;
		document.forms[0].imgstyle.disabled=false;
		mnToolbar.style.display='block';
		CurrentPath=path;		
		ViewMode=mnBrowse.CurrentViewMode;
		if (!ViewMode) {
			ViewMode='icons';
		}
		View(CurrentPath, name, true);
		if (CurrentButton) {
			CurrentButton.className='menuButton';
		}
		CurrentButton=button;
		CurrentButton.className='menuButtonCurrent';
	}

	function BrowseURL() {
		PreviewURL=true;
		document.forms[0].imgstyle.disabled=true;
		KeepPath[KeepIndex]=CurrentPath;
		KeepIndex=3;
		CurrentPath=KeepPath[KeepIndex];
		ViewMode=mnBrowse.CurrentViewMode;
		if (!ViewMode) {
			ViewMode='icons';
		}
		mnBrowse.location='edit.object.html.image.url.phtml?url='+escape(CurrentPath)+'&mode='+ViewMode;
		mnToolbar.style.display='none';
		if (CurrentButton) {
			CurrentButton.className='menuButton';
		}
		CurrentButton=mnURL;
		CurrentButton.className='menuButtonCurrent';
	}

	function browseUp() {
		if (blist=document.forms[0].BrowseNav) {
			sIndex=blist.options.selectedIndex;
			if (sIndex>0) {
				View(blist.options[blist.options.selectedIndex-1].value);
			}
		}
	}

	function ViewMode(mode) {
		if (mode=='details') {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details-pressed.gif';			
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons.gif';			
		} else if (mode=='icons') {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details.gif';			
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons-pressed.gif';			
		} else {
			document.images["details"].src='<?php echo $AR->dir->images; ?>browse/details.gif';
			document.images["list"].src='<?php echo $AR->dir->images; ?>browse/list-pressed.gif';			
			document.images["icons"].src='<?php echo $AR->dir->images; ?>browse/icons.gif';			
		}
		CurrentViewMode=mode;
		View(CurrentPath);
	}

	function New() {
		if (blist=document.forms[0].BrowseNav) {
			startpath='<?php echo $this->store->root; ?>'+blist.options[blist.options.selectedIndex].value;
		} else {
			startpath='<?php echo $this->store->root.$this->path; ?>';
		}
		if (document.all) {
			args=new Array();
			showModalDialog( startpath+"object.new.select.phtml",args,"font-family:Verdana; font-size:12; dialogWidth:38em; dialogHeight:26em; status:no; resizable: yes;");
			ObjectAdded();
		} else {
			newwindow=window.open( startpath+'object.new.select.phtml', 'newwindow',
				'directories=no,height=300,width=500,location=no,menubar=no,status=no,toolbar=no,resizable=yes');
			newwindow.focus();
		}
	}

	function ObjectAdded() {
		if (blist=document.forms[0].BrowseNav) {
			View(blist.options[blist.options.selectedIndex].value);
		} else {
			View('<?php echo $this->store->root.$this->path; ?>');
		}
	}

	function showPage(page) { 
        b_page=page;
        b_offset=b_limit*page;
		mnBrowse.location.search='?filter=<?php echo RawUrlEncode($filter); ?>&offset='+escape(parent.b_offset)+'&limit='+escape(parent.b_limit);
        return false;
	}

	function filter(type) {
		CurrentFilter=type;
		View(CurrentPath);
	}

	function b_setTotal(total) {
		b_total=total;
       	pages_select=document.forms[0].page;
		if (b_total>b_limit) {
	  		var pages=(b_total/b_limit);
	       	for (i=0; i<pages; i++) {
				pages_select.options[i]=new Option(i+1, i+1);
            }
            pages_select.options[b_page].selected=true;
			pages_select.style.display='inline';
		} else {
			pages_select.style.display='none';
		}
    }
	
	function b_hide() { }

	function b_show() { }

	function showPreview() {
		var style=document.forms[0].imgstyle.options[document.forms[0].imgstyle.selectedIndex].value;
		var border=document.forms[0].border.value;
		var hspace=document.forms[0].hspace.value;
		var vspace=document.forms[0].vspace.value;
		var align=document.forms[0].align.value;
		var alt=document.forms[0].alt.value;
		if (PreviewURL) {
			var url=CurrentPath;
			var path=false;
		} else {
			var url=false;
			var path=CurrentPath;
		}
		mnPreview.location="<?php echo $this->store->root.$this->path; ?>show.preview.html?style="+escape(style)+
				"&border="+escape(border)+"&hspace="+escape(hspace)+"&vspace="+escape(vspace)+
				"&align="+escape(align)+"&alt="+escape(alt)+"&url="+escape(url)+"&path="+escape(path);
	}

//-->
</script>
</HEAD>
<BODY SCROLL=NO onLoad="init();">
<form method="post" name="PictureForm" height="100%" style="border: 0px; margin: 0px; padding: 0px;">
<table width="100%" border="0" cellpadding="0" cellspacing="0" height="100%" link="white" vlink="white" alink="white">
<tr>
	<td valign="top" width="100%" height="100%">

<div class="tab-pane" id="tabPane1">

<script type="text/javascript">
	tp1 = new WebFXTabPane( document.getElementById( "tabPane1" ), false );
</script>

	<div class="tab-page" id="tabPage1">
		<h2 class="tab"><?php echo $ARnls["browse"]; ?></h2>
	
		<script type="text/javascript">tp1.addTabPage( document.getElementById( "tabPage1" ) );</script>

	<table cellspacing="0" cellpadding="0" height="100%" width="100%">
	<tr>
	  <td valign="top" rowspan="2">
		<div class="menu" id="mnMenu">
			<?php
				if( $this->nlsdata->name ) {
					$currentname = $this->nlsdata->name;
				} else {
					$currentname = $ARnls["thisobject"];
				}
			?>
	   	 	<a class="menuButton" id="mnCurrent" href="#" onClick="browseTo('<?php echo $this->path; ?>', this, '<?php echo $currentname; ?>');"><img src="<?php echo $AR->dir->images; ?>wizard/current.gif" border="0"><br><nobr><?php echo $currentname; ?></nobr></a>
	   	 	<a class="menuButton" id="mnPhotobook" href="#" onClick="browseTo(tbContentEditOptions['photobook']['location'], this, 'Photobook');"><img src="<?php echo $AR->dir->images; ?>wizard/photobook.gif" border="0"><br><?php echo $ARnls["photobook"]; ?></a>
		    <a class="menuButton" id="mnHome" href="#" onClick="browseTo('<?php echo $AR->user->path; ?>', this, '<?php echo $AR->user->data->name; ?>');"><img src="<?php echo $AR->dir->images; ?>wizard/home.gif" border="0"><br><?php echo $ARnls["home"]; ?></a>
	   	 	<a class="menuButton" id="mnURL" href="#" onClick="BrowseURL();"><img src="<?php echo $AR->dir->images; ?>wizard/url.gif" border="0"><br><?php echo $ARnls["url"]; ?></a>
		</div>
	  </td><td valign="top" width="100%" id="mnToolbar">

		<table height="100%" width="100%">
		<tr>
		  <td height="30" style="height: 30px">

			<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tr>
				<td align="left" valign="middle">
					<nobr>&nbsp;&nbsp;<?php echo $ARnls["lookin"]; ?>&nbsp;:</nobr>
				</td><td align="left" valign="top">
					<select name="BrowseNav" style="width: 150px; padding: 2px; margin: 2px;" onChange="View(this.options[this.options.selectedIndex].value);" class="minimal">
					</select>
							</nobr>
				</td>
				<td align="left" valign="top">
					<nobr>
						<a href="#" onClick="browseUp(); return false;"><img name="up" src="<?php echo $AR->dir->images; ?>browse/up.gif" width="23" height="22" alt="<?php echo $ARnls["up"]; ?>" border="0" hspace="2" vspace="2"></a>
						<?php
								if (!$this->CheckSilent("add")) {
						?>
							<img name="new" src="<?php echo $AR->dir->images; ?>browse/new-shaded.gif" alt="" width="23" height="22" border="0" hspace="4" vspace="2">
						<?php 
								} else {
						?>
							<a href="#" onClick="New(); return false;"><img name="new" src="<?php echo $AR->dir->images; ?>browse/new.gif" alt="<?php echo $ARnls["new"]; ?>" width="23" height="22" border="0" hspace="4" vspace="2"></a> 
						<?php
							}
						?>
					</td><td align="right" valign="top" width="100%">
						<select name="page" onChange="return showPage(this.options.selectedIndex);" style="margin: 2px; padding: 4px; display: none; width: auto;">
						</select>
					</nobr>
				</td>
			</tr>
			</table>

		  </td>
		</tr>
		</table>

	  </td>
	</tr><tr>
	  <td height="100%">
	    <iframe id="mnBrowse" name="mnBrowse" style="height: 100%; width: 100%;">
	    </iframe>
	  </td>
	</tr>
	</table>

	</div>

	<div class="tab-page" id="tabPage2">
		<h2 class="tab"><?php echo $ARnls["e_image_options"]; ?></h2>
		
		<script type="text/javascript">tp1.addTabPage( document.getElementById( "tabPage2" ) );</script>
		
<table height="100%" width="100%">
<tr>
	<td align="left" colspan="2">
      <?php echo $ARnls["e_alternate_text"]; ?>: 
      <input id="alt" type="text" name="alt" value="<?php echo $alt; ?>" size="20" class="alternate" style="width: 225px;" onChange="showPreview();">
	  Stijl: 
        <select name="imgstyle" onChange="showPreview();" style="width: 75px;">
		<option value="view.html"><?php echo $ARnls["default"]; ?></option>
		</select>
    </td>
</tr><tr height="100%">
	<td valign="top">
		<table class="fieldset" align="left" height="100%" width="100%">
			<tr>
				<td><?php echo $ARnls["e_alignment"]; ?>:</td>
			</tr><tr>
				<td><select name="align" class="layout" onChange="showPreview();">
					<?php
						$list["none"]=$ARnls["e_align_not_set"];
						$list["left"]=$ARnls["e_align_left"];
						$list["right"]=$ARnls["e_align_right"];
						$list["textTop"]=$ARnls["e_align_texttop"];
						$list["absMiddle"]=$ARnls["e_align_absmiddle"];
						$list["baseline"]=$ARnls["e_align_baseline"];
						$list["absBottom"]=$ARnls["e_align_absbottom"];
						$list["bottom"]=$ARnls["e_align_bottom"];
						$list["middle"]=$ARnls["e_align_middle"];
						$list["top"]=$ARnls["e_align_top"];				 
						while (list($key, $value)=each($list)) {
							echo "<option value=\"$key\"";
							if ($key==$align) { echo " selected"; }
							echo ">$value</option>";
						}
					?>
				</select></td>
			</tr><tr>
				<td><?php echo $ARnls["e_border_thickness"]; ?>:</td>
			</tr><tr>
				<td><INPUT ID=border TYPE=TEXT SIZE=3 NAME=border ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $border; ?>" class="layout" onChange="showPreview();"></td>
			</tr><tr>
				<td height="100%">
					<fieldset>
					<legend><?php echo $ARnls["e_spacing"]; ?></legend>
					<table>
					<tr>
						<td><?php echo $ARnls["e_horizontal"]; ?>:</td>
					</tr><tr>
						<td><INPUT ID=hspace TYPE=TEXT SIZE=3 NAME=hspace ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $hspace; ?>" onChange="showPreview();"></td>
					</tr><tr>
						<td><?php echo $ARnls["e_vertical"]; ?>:</td>
					</tr><tr>
						<td><INPUT ID=vspace TYPE=TEXT SIZE=3 NAME=vspace ONKEYPRESS="event.returnValue=IsDigit();" value="<?php echo $vspace; ?>" onChange="showPreview();"></td>
					</tr>
					</table>
					</fieldset>
				</td>
			</tr>
		</table>
	</td><td width="100%">
		<iframe name="mnPreview" style="width: 100%; height: 100%" src="show.preview.html"></iframe>
	</td>
</tr>
</table>
		
	</div>

</div>


<script type="text/javascript">
//<![CDATA[

setupAllTabs();

//]]>
</script>

	</td><td valign="top" width="200px">

	<table>
	<tr>
	<td><input type="button" name="ok" value="<?php echo $ARnls["ok"]; ?>" class="button" onClick="doSubmit(this.form);"></td>
	</tr><tr>
	<td><input type="button" name="cancel" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();" class="button"></td>
	</tr>
	</table>

	</td>
</tr>
</table>
</form>

</body>
</html>
<?php
	}
?>