<?php
	/******************************************************************
	 edit.object.layout.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: layout
	 Global variables: none

	 This template displays a list of object templates defined at the
	 current object. It displays a list of clickable flags denoting the
	 different languages for which the template is defined, linked to
	 the template edit form for that template in that language.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["customdata"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>dialog.css">
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
<script>

	customlist=new Array();
	current_node=0;

	function init() {
		dest=document.customform.fieldname.options;
		<?php
			if (is_array($this->data->customconfig)) {
				while (list($name, $custom)=each($this->data->customconfig)) {
					echo "		dest[dest.length]=new Option('".AddSlashes($name)."','".AddSlashes($name)."');\n";
					echo "		customlist[customlist.length]=new custom_node(\n";
					echo "			'".AddSlashes($custom["type"])."','".AddSlashes($custom["inherit"])."',\n";
					echo "			'".AddSlashes($name)."','".AddSlashes($custom["size"])."',\n";
					echo "			'".AddSlashes($custom["grant"])."','".AddSlashes($custom["nls"])."',\n";
					echo "			'".AddSlashes($custom["check"])."');\n";
				}
			}
		?>
		if (dest.length>0) {
			document.customform.fieldname.selectedIndex=dest.length-1;
			document.customform.fieldname.focus();
			show();
		}
	}

	function remove() {
		dest=document.customform.fieldname.options;
		id=dest.selectedIndex;
		dest.options[id]=null;
		ii=0;
		newlist=new Array();
		for (i=0; i<customlist.length; i++) {
			if (i!=id) {
				newlist[ii]=customlist[i];
				ii++;
			}				
		}
		customlist=newlist;
		if (!dest.options[id]) {
			id-=1;
		}
		if (id>=0) {
			dest.options[id].selected=true;
			show();
		} else {
			form=document.customform;
			for (i=0; i<form.cdtype.options.length; i++) {
				if (form.cdtype.options[i].value=='pobject') {
					form.cdtype.options[i].selected=true;
					i=form.cdtype.options.length;
				}
			}
			form.cdname.value='';
			form.cdsize.value='255';
			form.cdgrant.value='edit';
			form.cdcheck.value='.*';
			form.cdinherit.checked=true;
			form.cdnls.checked=true;
		}
	}
	
	function add() {
		dest=document.customform.fieldname.options;
		if ((dest.length==0) || (dest[dest.length-1].value!='new')) {
			dest[dest.length]=new Option('<?php echo $ARnls["new"]; ?>...','new');
			customlist[customlist.length]=new custom_node(document.customform.cdtype.options[document.customform.cdtype.selectedIndex].value, true, '', 255, 'edit', true, '.*');
		}
		document.customform.fieldname.selectedIndex=dest.length-1;
		document.customform.fieldname.focus();
		show();
	}

	function save() {
		savestring='';
		for (i=0; i<customlist.length; i++) {
			data=customlist[i];
			savestring+='&customdata['+i+'][name]='+escape(data['name']);
			savestring+='&customdata['+i+'][type]='+escape(data['type']);
			savestring+='&customdata['+i+'][inherit]='+escape(data['inherit']);
			savestring+='&customdata['+i+'][size]='+escape(data['size']);
			savestring+='&customdata['+i+'][nls]='+escape(data['nls']);
			savestring+='&customdata['+i+'][grant]='+escape(data['grant']);
			savestring+='&customdata['+i+'][check]='+escape(data['check']);
		}
		document.customform.customdata.value=savestring;
		return true;
	}

	function show() {
		form=document.customform;
		if (form.fieldname.options.length>0) {
			id=form.fieldname.selectedIndex;
			fielddata=customlist[id];
			for (i=0; i<form.cdtype.options.length; i++) {
				if (form.cdtype.options[i].value==fielddata.type) {
					form.cdtype.options[i].selected=true;
					i=form.cdtype.options.length;
				}
			}
			form.cdname.value=fielddata.name;
			form.cdsize.value=fielddata.size;
			form.cdgrant.value=fielddata.grant;
			form.cdcheck.value=fielddata.check;
			form.cdinherit.checked=fielddata.inherit;
			form.cdnls.checked=fielddata.nls;
		}
	}

	function custom_node(type, inherit, name, size, grant, nls, check) {
		this.name=name;
		this.type=type;
		this.inherit=inherit;
		this.size=size;
		this.grant=grant;
		this.nls=nls;
		this.check=check;
	}

	function updateCustom(element) {
		fields=document.customform.fieldname;
		id=fields.selectedIndex;
		skip=false;
		switch(element.name) {
			case "cdname" :
				value=new String(element.value);
				while (value.substr(0,1)==' ') {
					value=value.substr(1);
				}
				while (value.substr(value.length-1,1)==' ') {
					value=value.substr(0,value.length-1);
				}
				if (value=='') {
					alert('You must enter a name.');
					skip=true;
				}
				element.value=value;
				for (i=0; i<fields.options.length; i++) {
					if ((fields.options[i].value==value) && (i!=id)) {
						alert(value+' already inuse, select another.');
						skip=true;
						i=fields.options.length;
					}
				}
				if (!skip) {
					customlist[id].name=value;
					fields.options[id]=new Option(value, value);
					fields.options[id].selected=true;
				} else {
					element.select();
					element.focus();
				}
				break;
			case "cdtype" :
				customlist[id].type=element.options[element.selectedIndex].value;
				break;
			case "cdinherit" :
				customlist[id].inherit=element.checked;
				break;
			case "cdsize" :
				customlist[id].size=element.value;
				break;
			case "cdgrant" :
				customlist[id].grant=element.value;
				break;
			case "cdnls" :
				customlist[id].nls=element.checked;
				break;
			case "cdcheck" :
				customlist[id].check=element.value;
				break;
		}
	}
</script>
<style>
.nameselect {
	width: 125px;
}
.button {
	width: 75px;
}
.typeselect {
	width: 100px;
}
.text {
	width: 100px;
}
BODY, TD {
	font-size: 13px;
	font-family: helvetica, sans-serif;
}
</style>
</head>
<body bgcolor="white" onload="init();">
<form name="customform" action="edit.object.custom.save.phtml" onSubmit="save()">
<input type="hidden" name="customdata">
<table border="0" width="100%" align="center" cellspacing="4" vspace="10" hspace="10">
<tr>
	<td align="center" valign="top">
		<select name="fieldname" size="10" width="16" class="nameselect" onChange="show();">
		</select>
	</td><td valign="top" style="width: 250px;">
		<fieldset>
		<legend><?php echo $ARnls["customdata"]; ?></legend>
			<table border="0" width="100%">
			<tr>
				<td align="right"><?php echo $ARnls["type"]; ?></td>
				<td><select class="typeselect" name="cdtype" onChange="updateCustom(this);" ><?php $this->ls('/system/ariadne/types/','show.option.value.phtml'); ?></select></td>
				<td><input type="checkbox" name="cdinherit" value="1" onChange="updateCustom(this);" checked> <?php echo $ARnls["inherit"]; ?></td>
			</tr><tr>
				<td align="right"><?php echo $ARnls["name"]; ?></td>
				<td><input class="text" type="text" name="cdname" value="" size="16" onBlur="updateCustom(this);" ></td>
				<td><input type="checkbox" name="cdnls" value="1" onChange="updateCustom(this);" checked> nls</td>
			</tr><tr>
				<td align="right"><?php echo $ARnls["size"]; ?></td>
				<td><input type="text" name="cdsize" value="255" size="4" onBlur="updateCustom(this);" ></td>
			</tr><tr>
				<td align="right"><?php echo $ARnls["grant"]; ?></td>
				<td><input class="text" type="text" name="cdgrant" value="" size="16" onBlur="updateCustom(this);" ></td>
			</tr><tr>
				<td align="right"><?php echo $ARnls["check"]; ?></td>
				<td><input class="text" type="text" name="cdcheck" value=".*" size="16" onBlur="updateCustom(this);" ></td>
			</tr>
			</table>
		</fieldset>
    </td>
</tr><tr>
	<td colspan="2">
		<table width="100%">
		<tr>
			<td align="left">
				<input class="button" type="button" name="action" value="<?php echo $ARnls["delete"]; ?>" onClick="remove();">
				<input class="button" type="button" name="action" value="<?php echo $ARnls["add"]; ?>" onClick="add();">
			</td><td align="right">
				<input class="button" type="button" name="action" value="<?php echo $ARnls["cancel"]; ?>" onClick="window.close();">
				<input class="button" type="submit" name="action" value="<?php echo $ARnls["ok"]; ?>">
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</form>
</body>
<?php
	}
?>