<?php
	/******************************************************************
	 edit.object.layout.form.phtml                         Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $type, $function, $template, $mode
	 Grant needed: layout
	 Global variables: none

	 This template displays an object template defined at the current 
	 object in an editable textarea.

	 If the template is called without arguments, it will default to
	 an empty template with the class of the current object.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php printf($ARnls["edittemplate"],$this->path.$function); ?></title>
<?php
	include($this->store->get_config("code")."widgets/wizard/classic.css");
?>
<style>
  .full {
    width: 100%;
    height: 82%;
  }
  .templatefield {
    width: 100%;
    height: 99%;
  }
  .linenumbers {
    height:99%;
    width:50px;
    overflow:hidden;
  }
</style>
<script>
  function init() {
    <?php
	 if ($error) {
		 echo "alert('".AddCSlashes($error, ARESCAPE)."');\n";
	 }
	 if( !$mode || $mode == "edit" ) {
		 echo "document.forms[0].template.focus();";
	 }
    ?>
  }

function event_templatescroll(){
   scrollposition=document.all.template.scrollTop;
   document.all.linenumber.scrollTop=scrollposition;
}

function mode_change() {
	document.forms[0].action = "edit.object.layout.form.phtml";
	if( document.forms[0].mode[document.forms[0].mode.selectedIndex].value == 'highlight' ) {
		document.forms[0].action = "edit.object.layout.highlight.phtml";
	}
	document.forms[0].submit();
}

function tabKey(evt,item){
	evt = (evt) ? evt : ((event) ? event : null );
	if( evt ) {
		var charCode = (evt.charCode ? evt.charCode : ((evt.keyCode) ? evt.keyCode : evt.which));
		if( charCode==9 ) {
			item.focus();
			item.selection=document.selection.createRange();
			item.selection.text="\t";
			return false;
		}
	}
	return true;
}

</script>
</head>
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
<body onload="init();">
<?php
	if( $newtype ) { 
		$type = $newtype; 
	}
	if( $newfunction ) {
		$function = $newfunction;
	}
	if( $newlanguage ) {
		$language = $newlanguage;
	}
?>
<form action="edit.object.layout.save.phtml" method="post" style="height: 100%;">
<input type="hidden" name="type" value="<?php echo $type; ?>">
<input type="hidden" name="function" value="<?php echo $function; ?>">
<input type="hidden" name="language" value="<?php echo $language; ?>">
<table border="0" width="100%" cellspacing="0" height="5%">
	<tr>
		<td>
			<span class="required"><?php echo $ARnls["type"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["template"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["language"]; ?></span>
		</td><td>
			<span class="required"><?php echo $ARnls["mode"]; ?></span>
		</td><td>
		</td>
	</tr><tr>
		<td>
			<select name="newtype">
			<?php
				$this->ls("/system/ariadne/types/", "show.option.value.phtml","selected=$type");
			?>
			</select>
		</td><td>
			<input type="text" name="newfunction" value="<?php echo $function; ?>">
		</td><td>
			<select name="newlanguage">
			<option value="any"><?php echo $ARnls["any"]; ?></option>
			<?php
				while (list($key, $value)=each($AR->nls->list)) {
					if ($language==$key) {
						echo "<option value=\"$key\" selected>$value</option>\n";
					} else {
						echo "<option value=\"$key\">$value</option>\n";
					}
				}				
			?>
			</select>
		</td><td>
			<select name="mode" onchange="mode_change();">
				<option value="highlight" <?php if( $mode == "highlight" ) echo "selected"; ?>><?php echo $ARnls["highlight"]; ?></option>
				<option value="edit" <?php if( !$mode || $mode == "edit" ) echo "selected"; ?>><?php echo $ARnls["edit"]; ?></option>
			</select>
		</td><td>
			<?php 
				if ($data->config->templates[$type][$function][$language] || !$function) {
					$default=1;
				}
			?>
			<input type="checkbox" name="default" value="1" <?php 
				if ($default) { echo " checked"; } ?>>
			<span class="required"><nobr><?php echo $ARnls["default"]; ?></nobr></span>
		</td>
	</tr>
</table>
<?php
	if (!($file=$template)) {
		if ($data->config->pinp[$type][$function][$language]) {
			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				$file=$templates->read($this->id, $template);
			}
		}
	}
	
	
	if( $mode == "highlight" ) {

		$hfile = $file;
		
?>
<table border="0" width="100%" cellspacing="0" class="full">
<input type="hidden" name="template" value="<?php echo str_replace('"', "&quot;", $file); ?>">
<tr height="100%"><td>
<div style="width: 100%; height: 100%; overflow: auto; border: 2px inset buttonhighlight;">
<code style="word-break: keep-all; white-space: nowrap;"><ol><li><?php
	

	$hfile = str_replace("<pinp>", "<?php", $hfile);
	$hfile = str_replace("</pinp>", "?>", $hfile);
	
	$hfile = highlight_string($hfile, true );
	
	$hfile = str_replace("&lt;?php", "&lt;pinp&gt;", $hfile);
	$hfile = str_replace("?&gt;", "&lt;/pinp&gt;", $hfile);
	
	$hfile = str_replace("&lt;?</font><font color=\"#0000BB\">php", "&lt;</font><font color=\"#0000BB\">pinp&gt;", $hfile);
	
	$hfile = str_replace("<br />", "</code></li><li><code style=\"word-break: keep-all; white-space: nowrap;\">", $hfile);
	echo $hfile;
?></li></ol></code>
</div>
</td></tr>
</table>
<?php	
	} else {
?>
<table border="0" width="100%" cellspacing="0" class="full"> 
<tr><td valign="top">

<textarea name="linenumber" id="linenumber"  wrap="off" readonly class="linenumbers" tabindex="-1">
<?php
	$file=ereg_replace("&","&amp;",$file);
	$file=ereg_replace("<","&lt;", ereg_replace(">","&gt;",$file));

	$linetotal = 1;
	$linetotal = substr_count( $file, "\n");

	  for( $i=1;$i<($linetotal+500);$i++) {
	     echo("$i\n");
	  }
?>
</textarea>
</td><td width="100%">
<div style="height: 100%;">
<textarea onkeydown="return tabKey(event,this);" cols="78" rows="20" name="template" id="template" wrap="off" class="templatefield" onscroll="event_templatescroll();"><?php
        echo $file;
?></textarea>
</div>
</td></tr></table>
<?php
	}
?>
<table border="0" width="100%" height="10%" cellspacing="0">
<tr>
	<td colspan="2" valign="top">
		<input type="submit" name="next_cancel" value="<?php echo $ARnls["cancel"]; ?>">
		<input type="submit" name="next_delete" value="<?php echo $ARnls["delete"]; ?>" 
		 onClick="return confirm('<?php echo $ARnls["q:removethistemplate"]; ?>');">
	</td><td colspan="2" align="right" valign="top">
		<input type="submit" name="next_apply" value="<?php echo $ARnls["apply"]; ?>">	
		<input type="submit" name="next_save" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
</form>
</body>
<?php 
	} 
?>