<?php
	$ARCurrent->nodes[$this->path]=$this->id;
    $data=$this->data;
    if ($nogrants) {
      unset($data->grants);
      unset($data->usergrants);
    }
	$ARCurrent->objects[$this->id]["data"]=$data;
    unset($data);
	$ARCurrent->objects[$this->id]["type"]=$this->type;
	$ARCurrent->objects[$this->id]["vtype"]=$this->vtype;
	$ARCurrent->objects[$this->id]["lastchanged"]=$this->lastchanged;
	$ARCurrent->objects[$this->id]["properties"]=$this->load_properties();
?>