<?php

if( $this->CheckLogin("config") ) {

	require_once($this->store->get_config("code")."modules/mod_export_wddx.php");

	$fp = $this->getvar('wddxfp','none');
	if(!$fp){
		$fp = fopen('php://stdout','w');
		$options = $this->getvar('wddxoptions','none');
		unset($options['verbose']);
		$this->putvar('wddxoptions',$options);
		$this->putvar('wddxfp',$fp);
		ldHeader("Content-Type: text/xml");
	}
	export_wddx::header($fp);
	$query="";
	$this->find(".", $query, "export.wddx.object.phtml", "", 0);
	export_wddx::footer($fp);
}
?>