<?php
	if ($this->CheckConfig("layout") && $this->CheckConfig()) {

		eregi('^(local[.])?([a-z_0-9-]+)[.](.*)[.](.*)', $template, $regs);
		$default	= ! $regs[1];
		$dtype		= $regs[2];
		$type		= str_replace('-', '.', $dtype);
		$function	= $regs[3];
		$language	= $regs[4];


		$this->call("system.delete.layout.phtml", Array(
												"template" => $template,
												"default" => $default,
												"type"		=> $type,
												"function"	=> $function,
												"language"	=> $language ));

	}
?>