<?php
  $ARCurrent->nolangcheck=true;
  if ($this->CheckLogin("layout") && $this->CheckConfig()) {

		preg_match('/^(local[.])?([a-z_0-9-]+)[.](.*)[.](.*)/i', $source_template, $regs);
		$default=(int)! $regs[1];
		$dtype=$regs[2];
		$type = str_replace('-', '.', $dtype);
		$function=$regs[3];
		$language=$regs[4];
		unset($regs);

		preg_match('/^(local[.])?([a-z_0-9-]+)[.](.*)[.](.*)/i', $target_template, $regs);
		$tdefault	= (int)! $regs[1];
		$tdtype		= (isset($regs[2])) ? $regs[2] : $dtype;
		$ttype		= str_replace('-', '.', $tdtype);
		$tfunction	= (isset($regs[3])) ? $regs[3] : $target_template;
		$tlanguage	= (isset($regs[4])) ? $regs[4] : $language;


		if ("$source.$default.$type.$function.$language"!=
				"$target.$tdefault.$ttype.$tfunction.$tlanguage") {

			if ($data->config->pinp[$type][$function][$language]) {

				$template=$type.".".$function.".".$language.".pinp";
				$templates=$this->store->get_filestore("templates");
				if ($templates->exists($this->id, $template)) {
					$file=$templates->read($this->id, $template);
					/* now we have to save our template */
					debug("templates.rename to: $tdefault, $ttype, $tfunction, $tlanguage");
					$this->get($target, "system.save.layout.phtml", array(
														"template"	=> $file,
														"default"	=> $tdefault,
														"type"		=> $ttype,
														"function"	=> $tfunction,
														"language"	=> $tlanguage ));

					/* if everything went ok, we are going to delete the source template */
					if (!$this->error) {
						$this->get($source, "system.delete.layout.phtml", 
											array(
												"type"		=> $type,
												"function"	=> $function,
												"language"	=> $language 
											));
					}

				} else {
					$this->error=$ARnls["err:ftpnotemplatebadperm"];
				}
			} else {
				$this->error=$ARnls["err:ftpnotemplate"];
			}
		} else {
			$this->error=$ARnls["err:ftpnorenameself"];
		}
	$ARCurrent->ftp_error = $this->error;
  }
?>
