<?php
	if (($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) {

		$fileinfo=$this->getdata("file");

		// now make the new values available for system.save.data.phtml
		$defaultNLS = $ARConfig->nls->default;
		$arCallArgs[$defaultNLS]["file"]=$fileinfo["name"];
		$arCallArgs[$defaultNLS]["file_temp"]=basename($fileinfo["tmp_name"]);
		$arCallArgs[$defaultNLS]["file_size"]=$fileinfo["size"];
		$arCallArgs[$defaultNLS]["file_type"]=$fileinfo["type"];
		$arCallArgs[$defaultNLS]["mimetype"]=$fileinfo["type"];
		$this->call("ftp.files.save.data.phtml", $arCallArgs);

		if ($this->error) {
			$ARCurrent->ftp_error=$this->error;
		}
	}
?>
