<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.1
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.

  ******************************************************************/
  $ARCurrent->nolangcheck=true;
  $arResult = false;
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
		preg_match('/^(local[.])?([a-z_0-9-]+)[.](.*)[.](.*)/i', $arRequestedTemplate, $regs);
		$dtype=$regs[2];
		$type = str_replace('-', '.', $dtype);
		$function=$regs[3];
		$language=$regs[4];
		if ($data->config->pinp[$type][$function][$language]) {
			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				if (!$this->data->config->templates[$type][$function]) {
					$entry["filename"]="local.$dtype.$function.$language";
				} else {
					$entry["filename"]="$dtype.$function.$language";
				}
				$entry["date"]=$this->lastchanged;
				$entry["type"]="template";
				$entry["size"]=$templates->size($this->id, $template);
				$entry["grants"]["read"]=true;
				$arResult=$entry;
			}
		}
  }
?>
