<?php
  $ARCurrent->nolangcheck=true;
  if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		eregi('^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)', $source_template, $regs);
		$default=! $regs[1];
		$type=$regs[2];
		$function=$regs[3];
		$language=$regs[4];
		unset($regs);
		if ($data->pinp[$type][$function][$language]) {

			$template=$type.".".$function.".".$language.".pinp";
			$templates=$this->store->get_filestore("templates");
			if ($templates->exists($this->id, $template)) {
				$file=$templates->read($this->id, $template);
					$this->get($source, "system.delete.layout.phtml", 
										Array(
											"type"		=> $type,
											"function"	=> $function,
											"language"	=> $language 
										));

				/* now we have to save our template */

				eregi('^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)', $target_template, $regs);
				$tdefault	= ! $regs[1];
				$ttype		= (isset($regs[2])) ? $regs[2] : $type;
				$tfunction	= (isset($regs[3])) ? $regs[3] : $target_template;
				$tlanguage	= (isset($regs[4])) ? $regs[4] : $language;

				debug("templates.rename to: $tdefault, $ttype, $tfunction, $tlanguage");				
				$this->get($target, "system.save.layout.phtml", Array(
														"template"	=> $file,
														"default"	=> $tdefault,
														"type"		=> $ttype,
														"function"	=> $tfunction,
														"language"	=> $tlanguage ));
			}
		}

	$ARCurrent->ftp_error = $this->error;
  }
?>