<?php
	if ($this->CheckConfig("layout")) {

		ob_start();
			@readfile($file["tmp_name"]);
			$template = ob_get_contents();
		ob_end_clean();
		ftp_Debug("1");

		eregi('^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)', $file["name"], $regs);
		$default = ! $regs[1];
		$type = $regs[2];
		$function = $regs[3];
		$language = $regs[4];


		ftp_Debug("2 call (system.save.layout.phtml) template=$template, default=$default, type=$type, function=$function, language=$language");
		$this->call("system.save.layout.phtml", Array(
												"template" => $template,
												"default" => $default,
												"type"		=> $type,
												"function"	=> $function,
												"language"	=> $language ));
		ftp_Debug("3");
	}
?>