<?php
	if ($this->CheckLogin("add") && $this->CheckConfig()) {

		$arNewType=$ARConfig->cache[$this->path]->FTP['mkdir'];
		debug("creating dir of type($arNewType)", "pinp");
//		$arNewType="pdir";

		$arNewPath=$this->make_path($arNewFilename);
		$arNewData=new baseObject;

		$arNewObj=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewdata);
		$arNewObj->arIsNewObject=true;
		$result=$arNewObj->call("ftp.save.data.phtml", $arCallArgs);
	}
?>
