<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$arResult=$this->call("ftp.objects.list.phtml");

		if ($this->CheckSilent("layout")) {
			$entry["grants"]["write"]=true;
		}

		$fstore=$this->store->get_filestore("templates");

		if (($data->config->pinp) && is_array($data->config->pinp)) {
			while (list($type, $values)=each($data->config->pinp)) {
				while (list($function, $templatelist)=each($values)) {
							ksort($templatelist);
							reset($templatelist);
							while (list($language, $template)=each($templatelist)) {
									$dtype = str_replace('.', '-', $type);
									if (!$this->data->config->templates[$type][$function]) {
										$entry["filename"]="local.$dtype.$function.$language";
									} else {
										$entry["filename"]="$dtype.$function.$language";
									}

									$time = $fstore->mtime($this->id, $entry["filename"].".pinp");

									$entry["date"]=$time;
									$entry["type"]="template";
									$entry["size"]=$fstore->size($this->id, "$type.$function.$language.pinp");
									$entry["grants"]["read"]=true;
									$arResult[]=$entry;
							}
				}
			}
		}
	}
?>
