<?php
	if ($this->CheckLogin("add") && $this->CheckConfig()) {

		/*	first check which object type we have to use for this
			kind of file											*/

		if (!$arNewType) {
			$arNewType="pfile";
		}

		$fileinfo=$this->getdata("file");
		$arNewFilename=$fileinfo["name"];
		$arNewPath=$this->make_path($arNewFilename);
		$arNewData=new object;

		$arNewObj=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewdata);
		$arNewObj->arIsNewObject=true;
		$result=$arNewObj->call("ftp.files.save.phtml", $arCallArgs);
	}
?>