<?php
	if ($this->CheckConfig("layout")) {

		ob_start();
			@readfile($file["tmp_name"]);
			$template = ob_get_contents();
		ob_end_clean();

		eregi('^(local[.])?([a-z_0-9]+)[.](.*)[.](.*)', $file["name"], $regs);
		$default	= ! $regs[1];
		$type		= ($regs[2]) ? $regs[2] : "pobject";
		$function	= ($regs[3]) ? $regs[3] : $file["name"];
		$language	= ($regs[4]) ? $regs[4] : "any";


		//debug("call (system.save.layout.phtml) template=$template, default=$default, type=$type, function=$function, language=$language");
		$this->call("system.save.layout.phtml", Array(
												"template" => $template,
												"default" => $default,
												"type"		=> $type,
												"function"	=> $function,
												"language"	=> $language ));
		if ($this->error) {
			$ARCurrent->ftp_error=$this->error;
		}

	}
?>