<?php
  debug("GetLock: $id");
  if ($data->locked) {
    if ($id) {
      if (($data->locked["id"]==$id) && ($data->locked["duration"]>time())) {
        debug("lock $id found"); 
        $arResult=$data->locked;
        $ARCurrent->locks[$this->path]=$data->locked;
      } else {
        debug("invalid or different lock");
      }
    } else {
      if ($data->locked["duration"]>time()) {
        debug("lock ".$data->locked["id"]." found");
        $arResult=$data->locked;
        $ARCurrent->locks[$this->path]=$data->locked;
      }
    }
  }
?>