<?php
	/******************************************************************
	 help.about.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays some information about Ariadne and Muze.
	 
	 no result

	******************************************************************/
?>
<html>
<head>
<title><?php echo $ARnls["aboutariadne"]; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
<script src="<?php echo $AR->dir->www; ?>widgets/window/savesize.js"></script>
</head>
<body>
<table border="0" cellpadding="5" cellspacing="5" height="100%">
<tr>
	<td valign="top" bgcolor="white" height="100%">
		<a href="http://www.muze.nl/" target="_new"><img src="<?php echo $AR->dir->images; ?>muze_small.gif" alt="Muze" border="0"></a>
		<p><nobr>
		Muze<br>
		Auke&nbsp;Vleerstraat&nbsp;1<br>
		7521&nbsp;PE&nbsp;Enschede<br>
		<?php echo $ARnls["netherlands"]; ?>
		<p>
		e-mail:&nbsp;<a href="mailto:info@muze.nl">info@muze.nl</a><br>
		tel.:&nbsp;+3153-4894441</nobr>
	</td><td valign="top">
		<b>Ariadne
			<p>
			version 2.0RC1<br>
			November 8, 2001<br>
			Copyright &copy; 1998-2001 Muze<br>
			Ariadne comes with ABSOLUTELY NO WARRANTY.<br>
			Ariadne is released under the <a href="help.about.license.phtml" target="_new">Gnu General Public License, version 2</a>. 
		</b>
	</td>
</tr>
</table>
</body>
</html>