<?php
  /******************************************************************
   import.phtml                                      Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("add")) {
?>
<body bgcolor="white">
<?php
  $this->parents($this->path, "show.link.phtml","target=import.phtml");
?>
<!-- hidden form variables needed by new.phtml/save.phtml -->

<table border="0" cellspacing="0" width="100%"> 
<tr bgcolor="#404074">
  <td >
	<font face="helvetica, sans-serif" color="white"><b>
	<?php echo $ARnls["importobject"]; ?></b></font>
  </td><td align="right">
	<font face="helvetica, sans-serif" color="white"><b>
	<form align="right" name="impfile" action="<?php echo $AR->root.$this->path."import.phtml"; ?>" ENCTYPE="multipart/form-data" method="post" >
	<font face="helvetica, sans-serif">File&nbsp;:
	<input type="hidden" name="MAX_FILE_SIZE" value="10000000">
	<input type="file" name="file">
	</font>
  </td>
</tr>
</table>

<?php

if (!$file)
global $file,$file_name,$file_type;

if ($file) {
?>
<?php
	$ax_file=$file;
	$import_path=$this->path;
	include($this->store->code."includes/import.phtml");
	if ($error) {
?>
	<script language="javascript">
	alert('<?php echo $error; ?>');
	history.back();
	</script>
<?php
	}
}
?>


<p>
<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
  <td>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
  </td>
  <td align="right">
    <input type="submit" name="next" value="<?php echo $ARnls["importobject"]; ?>">  
  </td>
</tr>
</table>
</form>
<font face="helvetica, sans-serif" size="2">
<?php
  $this->ls("","show.phtml","target=import.phtml");
?>
</font>
</body>
<?php
  }
?>