<?php
	/******************************************************************
	 js.window.close.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays javascript code which close a window. It is
	 used in conjunction with scripts that must first do a redirect
	 before closing a window.
	 
	 no result

	******************************************************************/
?>
<script>
<!--
  top.window.close();
// -->
</script>