<?php
	/******************************************************************
	 js.window.objectadded.phtml                           Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays javascript code which calls the function 
	 objectadded(type, name, path) in the opener of this window and
	 then closes the window. 

	 It is used in conjunction with scripts that must first do a 
	 redirect before closing a window.
	 
	 no result

	******************************************************************/
?>
<script>
<!--
	if (window.opener.objectadded) {
		window.opener.objectadded('<?php echo $this->type; ?>','<?php echo AddCSlashes($nlsdata->name, ARESCAPE); ?>','<?php echo $this->path; ?>');
	}
	<?php
		if (!$arIsNewObject) {
	?>
				top.window.close();
	<?php
		} else {
	?>
				top.window.location.href='<?php echo $this->store->get_config("root").$this->parent; ?>object.new.select.phtml';
	<?php
		}
	?>
// -->
</script>