<body bgcolor="white">
<h1><?php printf($ARnls["err:cannotlockobject"],$this->path); ?></h1>
<table border="0" bgcolor="#404074" cellpadding="0" cellspacing="0">
<tr>
  <td colspan="3">
    <img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="4" height="16">
    <font face="arial, helvetica, sans-serif" size="2" color="white"><b>
      <?php echo $ARnls["locks"]; ?>
    </b></font>
  </td>
</tr>
<tr>
  <td><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
  <td bgcolor="white">
    <table border="0" cellspacing="2" cellpadding="2" width="100%">
    <tr>
      <th bgcolor="#404074" align="center" width="400">
        <font face="arial, helvetica, sans-serif" size="2" color="white"><?php echo $ARnls["path"]; ?></font>
      </th><th bgcolor="#404074" align="center">
        <font face="arial, helvetica, sans-serif" size="2" color="white"><?php echo $ARnls["login"]; ?></font>
      </th><th bgcolor="#404074" align="center">
        <font face="arial, helvetica, sans-serif" size="2" color="white"><?php echo $ARnls["expires"]; ?></font>
      </th>
    </tr>
<?php
	if ($locklist=$this->store->mod_lock->locklist) {
		while ((list($key, $lock)=each($locklist))) {
			echo "<tr><td bgcolor=\"#EEEEEE\"><a href=\"".$this->store->root.$lock["path"].
				"classic.edit.phtml?returnpage=".RawUrlEncode($this->store->root.$this->path).
				"classic.edit.phtml\">".$lock["path"]."</a></td>";
			echo "<td bgcolor=\"#EEEEEE\">".$lock["identity"]."</td>";
			echo "<td bgcolor=\"#EEEEEE\">".strftime("%d-%m %H:%M:%S",$lock["release"])."</td></tr>\n";
		}
	}
?>
    </table>
  </td>
  <td><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
</tr><tr>
  <td colspan="3"><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
</tr>
</table>  
</body>
<?php
  exit;
?>