<?php
	/******************************************************************
	 login.phtml                                           Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $ARLogin, $ARPassword, $arReturnPath, $arReturnTemplate
	 Grant needed: none
	 Global variables: none

	 This template sets the login cookie and adds the username and
	 password to the session. If no session exists, or the session has
	 a different username, a new session is started.

	 Finally the template redirects the browser to $arReturnPage.

	 $ARLogin must be a valid user id
	 $ARPassword must be the password for that user
	 $arReturnPath is the path of the object to which
	   the browser must be redirected. This is the internal ariadne
	   path.
	 $arReturnTemplate is the name of the template to display in that
	   object.
	 
	 no result

	******************************************************************/
	if ($this->CheckConfig()) {
		if (!$arPopup) {
			ldRedirect($this->make_url($arReturnPath, '', true, false).$arReturnTemplate);
			?>
				<a href="<?php echo $this->make_url($arReturnPath, '', true, false).$arReturnTemplate; ?>">Continue</a>
			<?php
		} else {
			?>
			<script>
				if (window.opener && window.opener.location) {
					window.opener.location.href='<?php echo $this->make_url($arReturnPath, '', true, false).$arReturnTemplate; ?>';
				}
				window.close();
			</script>
			<?php
		}
	}
?>
