<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<?php
	if ($this->CheckConfig()) {
?>
<table width="100%">
<tr>
	<td valign="top"><img src="<?php echo $AR->dir->images; ?>tree/wait.gif" align="left" hspace="2">Loading...</td>
	<td align="right"><a href="javascript:top.hidetree();"><img align="right" src="<?php echo $AR->dir->images; ?>tree/x.gif" vspace="1" border="0"></a></td>
</tr>
</table>
<?php 
		if ($link && $this->exists($link)) {
			?>
			<script>
				top.view.location.href='<?php echo $this->make_url($link).$template; ?>';
			</script>
			<?php
		} else {
			?>
			<script>
				alert('<?php printf(AddSlashes($ARnls["err:wrongpath"]),$link); ?>');
				history.back();
			</script>
			<?php
		}
	}
?>
</body>
</html>
