<?php
	if ($this->CheckConfig()) {
		if ($arLanguage) {
			$append="?arLanguage=$arLanguage";
		}
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<div class="border">
  <span class="hoverbutton" style="float: right"><a href="#" onClick="top.hidetree(); return false;"><img src="<?php echo $AR->dir->images; ?>tree/x.gif" border="0" height="18" width="18" vspace="2"></a></span>
  <img src="<?php echo $AR->dir->images; ?>tree/wait.gif" hspace="2" width="15" height="15" style="float: left"> Loading...  
</div>
<?php 
		if ($link && $this->exists($link)) {
			?>
			<script>
				top.view.location='<?php echo $this->make_url($link).$template.$append; ?>';
			</script>
			<?php
		} else {
			?>
			<script>
				alert('<?php printf(AddSlashes($ARnls["err:wrongpath"]),$link); ?>');
				history.back();
			</script>
			<?php
		}
	}
?>
</body>
</html>
