<?php
	/******************************************************************
	 object.new.select.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: add
	 Global variables: none

	 No result.

	******************************************************************/
	if ($this->CheckLogin("add", ARANYTYPE) && $this->CheckConfig()) {
		if (!$arReturnTemplate) {
			$arReturnTemplate="object.new.phtml";
		}
?>
<html>
<head>
<title><?php echo $ARnls["addnewobject"]; ?></title>
<?php
	include($this->store->get_config("code")."widgets/wizard/classic.css");
?>
<style>
	.list {
		BACKGROUND-COLOR: white;
		WIDTH: 100%;
		HEIGHT: 100%;
	}
	.greyed {
		filter: gray();
	}
	<?php
		$browser=$this->call("browsercheck.phtml");
		if ($browser["id"]!="ns" || $browser["version"]!=4) {
		?>
			.listcontainer {
				BORDER-STYLE: inset;
				BORDER-WIDTH: thin;
				WIDTH: 100%;
				HEIGHT: 100%;
				OVERFLOW: auto;
			}
		<?php
		}
	?>
	.greyed {
		COLOR: #CCCCCC;
	}
    tbody A {
      text-decoration: none;
      display: block;
      text-align: center;
      padding: 2px;
      margin: 4px;
      font: menu;
      color: black;
      border: 1px solid white;
    }
    tbody A:hover {
      border: 1px solid #4A6799;
      background-color: #D0DCF7;
    }
	table thead td {
		border: 2px outset buttonhighlight;
		background-color: buttonface;
		text-align: center;
		height: 20px;
	}
	table thead td a, table thead td a:hover {
		text-decoration: none;
		color: black;
		display: block;
		font: menu;
		padding-top: 2px;
	}
</style>
<script>
	function View(path) {
		window.location=path;
		return false;
	}
</script>
</head>
<body bgcolor="white">
<div class='listcontainer'>
<table class="list" width="100%" border="0" cellspacing="0" cellpadding="4"><tr>
<?php
    $server_name=eregi_replace("^[htps:/]*/","",$AR->host);
	global $HTTP_SERVER_VARS;	

	if ($HTTP_SERVER_VARS["HTTP_HOST"]==$server_name) {
		$currentpath=$this->store->root.$this->path;
  	} else {
		$currentpath=$this->make_url();
	}
	if ($AR->user->data->login=="admin") {
		echo "<thead>";
		if( $showall ) {
			echo "<tr><td colspan=\"4\"><a href=\"".$currentpath."object.new.select.types.phtml?showall=0\">".$ARnls["show"].": ".$ARnls["typetree"]."</a></td></tr>";
		} else {
			echo "<tr><td colspan=\"4\"><a href=\"".$currentpath."object.new.select.types.phtml?showall=1\">".$ARnls["show"].": ".$ARnls["all"]."</a></td></tr>";
		}
		echo "</thead>";
	}
	echo "<tbody>";
	if( !$showall ) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->typetree) {
			$result=$this->ls($configcache->typetree."/".$this->type."/",
				"system.get.phtml");
		} else {
//			$result=$this->ls("/system/ariadne/typetree/normal/".$this->type."/",
//				"system.get.phtml");
			$typetree=$this->call('typetree.ini');
		}
	} else {
		$result=$this->ls("/system/ariadne/types/","system.get.phtml");
	}
	$cols=4;
	if ($result && is_array($result)) {
		$col=1;
		while (list($key, $object)=each($result)) {
			$type=$object->data->value;
			$name=$object->nlsdata->name;
			if (!$this->CheckSilent("add",$type)) {
				$class="class='greyed'";				
			} else {
				$class="";
			}
			if ($col>$cols) {
				$col=1;
				echo "</tr><tr valign='top'>";
			}
			?>
				<td valign="top" align="center" width="<?php echo (100/$cols); ?>%">
					<a <?php echo $class; ?> href="#" onClick="return View('<?php echo $currentpath.$arReturnTemplate; ?>?arNewType=<?php echo RawUrlEncode($type)."&".ldGetServerVar("QUERY_STRING"); ?>');">
					<img width="40" height="40" 
						 src="<?php echo $AR->dir->images."icons/".$type; ?>_open.gif" 
						 alt="<?php echo $type; ?>" border="0"><br>
					<?php
						echo "$name</a>";
					?></a>
				</td>
			<?php
			$col++;
		}
		while ($col<=$cols) {
			echo "<td>&nbsp;</td>\n";
			$col++;
		}
	} else if ($typetree) {
		$list=$typetree[$this->type];
		$col=1;
		while (list($type, $name)=each($list)) {
			if (!$this->CheckSilent("add",$type)) {
				$class="class='greyed'";				
			} else {
				$class="";
			}
			if ($col>$cols) {
				$col=1;
				echo "</tr><tr valign='top'>";
			}
			if ($ARCurrent->arTypeIcons[$type]) {
				$icon=$ARCurrent->arTypeIcons[$type];
			} else {
				$icon=$AR->dir->images."icons/".$type.'_open.gif';
			}
			?>
				<td valign="top" align="center" width="<?php echo (100/$cols); ?>%">
					<a <?php echo $class; ?> href="#" onClick="return View('<?php echo $currentpath.$arReturnTemplate; ?>?arNewType=<?php echo RawUrlEncode($type)."&".ldGetServerVar("QUERY_STRING"); ?>');">
					<img width="40" height="40" src="<?php echo $icon; ?>" alt="<?php echo $type; ?>" border="0"><br>
					<?php
						echo "$name</a>";
					?></a>
				</td>
			<?php
			$col++;
		}
		while ($col<=$cols) {
			echo "<td>&nbsp;</td>\n";
			$col++;
		}		
	} else {
		error($ARnls["err:wronggrants"]);
		// FROP error("Something is wrong with your grants, please contact the system administrator.");
	}
?>
</tr>
</tbody>
</TABLE>
</div>
</body>
<?php
	}
?>