<?php
	/******************************************************************
	
	******************************************************************/

	$folder=$this->call("system.get.folder.phtml");
	$newlocation=$this->call("system.rename.phtml", $arCallArgs);
	if (!$this->error) {
		// FIXME: add new path to tree
		?>
			<script>
				if (top.window && top.window.opener && top.window.opener.top.tree) {
					target=top.window.opener.top.tree;
				} else if (window.opener && window.opener.top.tree) {
					target=window.opener.top.tree;
				}
				target.DelLinks('<?php echo $this->path; ?>');
				target.AddLinks('<?php echo $this->store->make_path($newlocation, '..'); ?>', 
					'<?php echo $folder["icon"]; ?>', '<?php echo $folder["name"]; ?>', 
					'<?php echo $newlocation; ?>', '<?php echo $folder["pre"]; ?>');
				window.opener.top.View('<?php echo $newlocation; ?>');
				window.close();
			</script>
		<?php
	} else {
		echo "<font color='red'>$this->error</font>";
	}
?>