<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		include($this->store->code."nls/menu.".$nls);
?>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm.without_grants.focus();
	}
</script>
<table border="0" width="100%" cellspacing="0" cellpadding="2" height="100%">
<tr>
	<td colspan="2" align="center" valign="top">
		<table border="0" width="60%">
		<tr>
			<td>
				<fieldset>
				<legend><?php echo $ARnls["options"]; ?></legend>
					<input type="checkbox" name="without_grants" value="1" checked><?php echo $ARnls["withoutgrants"]; ?><br>
					<input type="checkbox" name="full_path" value="1"><?php echo $ARnls["fullpath"]; ?><br>
				</fieldset>
			</td>
		</tr>
		<tr>
			<td>
				<fieldset>
				<legend><?php echo $ARnls["advanced"]; ?></legend>
					<input type="checkbox" name="without_data" value="1"><?php echo $ARnls["withoutdata"]; ?><br>
					<input type="checkbox" name="without_files" value="1"><?php echo $ARnls["withoutfiles"]; ?><br>
					<input type="checkbox" name="without_templates" value="1"><?php echo $ARnls["withouttemplates"]; ?><br>
				</fieldset>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<?php
	}
?>