<?php
	/******************************************************************
	 object.new.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	$arNewType=$this->getdata("arNewType","none");
	if (!$arNewType) {
		error($ARnls["err:nonewtype"]);
		// FROP error("arNewType not defined.");
		$this->store->close();
		exit();
	}
	if ($this->CheckLogin("add", $arNewType) && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");
		$arNewFilename=$this->getdata("arNewFilename","none");
		$arNewData=new object;
		$arNewPath=$this->make_path($arNewFilename);
		$wgWizCallObject=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewData);
		$wgWizCallObject->arIsNewObject=true;
		$wgWizFlow=$wgWizCallObject->call("object.new.flow.phtml", $arCallArgs);
		if ($wgWizFlow[0]["error"]) {
			$wgWizAlert=$wgWizFlow[0]["error"];
		}
		$result=$this->get("/system/ariadne/types/$arNewType/","system.get.name.phtml");
		$wgWizTitle=$ARnls["new"]." ".$result[0];		
		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$arNewType.'_open.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizCallArgs=$arCallArgs.$wgWizFlow[0]["arCallArgs"];
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>