<?php
	$ARCurrent->nolangcheck=true;
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
		include($this->store->get_config('code').'nls/'.$this->reqnls);
?>
<html>
<head>
<title><?php echo $ARnls["delete"]; ?></title>
<?php
	include($this->store->get_config("code")."widgets/wizard/classic.css");
?>
<script>
	function init() {
		document.confirmform.cancel.focus();
	}
</script>
</head>
<body onLoad="init()">
<table border="0" width="100%" cellspacing="0" cellpadding="2">
<?php
	$server_name=eregi_replace("^[htps:/]*/","",$AR->host);
	global $HTTP_SERVER_VARS;
	if ($HTTP_SERVER_VARS["HTTP_HOST"]==$server_name) {
		$currentpath=$this->store->get_config("root").$this->path;
	} else {
		$currentpath=$this->make_url();
	}
?>
<form action="<?php echo $currentpath; ?>recurse.phtml" name="confirmform">
<input type="hidden" name="action" value="delete">
<tr>
	<td align="center" colspan="2">
		<?php echo $ARnls["q:removeobject"]."<br>( $this->path )"; ?><p>
	</td>
</tr><tr>
	<td align="right">
		<input type="submit" name="submit" style="width: 100px" value="<?php echo $ARnls["yes"]; ?>">
	</td><td align="left">
		<input type="submit" name="cancel" style="width: 100px" value="<?php echo $ARnls["no"]; ?>" onClick="window.close();">
	</td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>