<?php
	/******************************************************************
	 object.new.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	$arNewType=$this->getdata("arNewType","none");
	if (!$arNewType) {
		error($ARnls["err:nonewtype"]);
		//  error("arNewType not defined.");
		$this->store->close();
		exit();
	}
	if ($this->CheckLogin("add", $arNewType) && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");
		$arNewFilename=$this->getdata("arNewFilename","none");
		$arNewData=new object;
		$arNewPath=$this->make_path($arNewFilename);
		$wgWizCallObject=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewData);
		$wgWizCallObject->arIsNewObject=true;
		$wgWizFlow=$wgWizCallObject->call("object.new.flow.phtml", $arCallArgs);
		if ($wgWizFlow[0]["error"]) {
			$wgWizAlert=$wgWizFlow[0]["error"];
		}
		if ($wgWizFlow[0]["nextstep"]) {
			$wgWizNextStep=$wgWizFlow[0]["nextstep"];
		}
		if (!$ARCurrent->arTypeIconsSmall[$arNewType]) {
			// FIXME: for performance the check above is necessary, but
			// it does make it possible to get the wrong icon...
			// get typetree to get the correct icon
			$this->call('typetree.ini');
		}
		$icon=$ARCurrent->arTypeIcons[$arNewType]['default'];
		if (!$icon) {
			$dotPos=strpos($arNewType, '.');
			if (false!==$dotPos) {
				$realtype=substr($arNewType, 0, $dotPos);
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
			} else { 
				$realtype=$arNewType;
			}
			if (!$icon) {
				$icon=$AR->dir->images."icons/".$realtype.".gif";
			}
			$name=$ARCurrent->arTypeNames[$arNewType];
		} else {
			$name=$ARCurrent->arTypeNames[$arNewType];
		}
		$arResult=$icon;


//		$result=$this->get("/system/ariadne/types/$arNewType/","system.get.name.phtml");
//		$wgWizTitle=$ARnls["new"]." ".$result[0];		
//		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$arNewType.'_open.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTitle=$ARnls["new"]." ".$name;		
		$wgWizHeader=$wgWizTitle.'<img src="'.$icon.'" alt="" hspace="4" align="absmiddle">';
		$wgWizCallArgs=$arCallArgs.$wgWizFlow[0]["arCallArgs"];
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>
