<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
		include($this->store->code."nls/menu.".$nls);
?>
<script>
	window.onload=init;
    function init() {
        document.wgWizForm.source.focus();
    }
</script>
<table border="0" width="100%" cellspacing="0" cellpadding="2">
<tr>
	<td align="center" colspan="2">
		<?php 
			echo $ARnls["file"].":&nbsp;";
		?>
		<input type="file" name="source" class="autoSized">
	</td>
</tr><tr>
	<td colspan="2">&nbsp;</td>
</tr><tr>
	<td colspan="2" align="center" valign="top">
		<table border="0" width="60%">
		<tr>
			<td>
				<fieldset>
				<legend><?php echo $ARnls["options"]; ?></legend>
					<input type="checkbox" class="autoSized" name="without_grants" value="1" checked><?php echo $ARnls["withoutgrants"]; ?><br>
					<input type="checkbox" class="autoSized" name="force" value="1"><?php echo $ARnls["force"]; ?>
				</fieldset>
			</td>
		</tr>
		<tr>
			<td>
				<fieldset>
				<legend><?php echo $ARnls["advanced"]; ?></legend>
					<input type="checkbox" class="autoSized" name="without_data" value="1"><?php echo $ARnls["withoutdata"]; ?><br>
					<input type="checkbox" class="autoSized" name="without_files" value="1"><?php echo $ARnls["withoutfiles"]; ?><br>
					<input type="checkbox" class="autoSized" name="without_templates" value="1"><?php echo $ARnls["withouttemplates"]; ?><br>
				</fieldset>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<?php
	}
?>