<?php
	/******************************************************************
	 object.new.select.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: add
	 Global variables: none

	 No result.

	******************************************************************/
	if ($this->CheckLogin("add", ARANYTYPE) && $this->CheckConfig()) {
		if (!$arReturnTemplate) {
			$arReturnTemplate="object.new.phtml";
		}
?>
<html>
<head>
<title><?php echo $ARnls["addnewobject"]; ?></title>
<?php
	include($this->store->get_config("code")."widgets/wizard/classic.css");
?>
<style>
	.list {
		BACKGROUND-COLOR: white;
		WIDTH: 100%;
		HEIGHT: 100%;
	}
	.greyed {
		filter: gray();
	}
	<?php
		$browser=$this->call("browsercheck.phtml");
		if ($browser["id"]!="ns" || $browser["version"]!=4) {
		?>
			.listcontainer {
				BORDER-STYLE: inset;
				BORDER-WIDTH: thin;
				WIDTH: 100%;
				HEIGHT: 100%;
				OVERFLOW: auto;
			}
		<?php
		}
	?>
	.greyed {
		COLOR: #CCCCCC;
	}
    tbody A {
      text-decoration: none;
      display: block;
      text-align: center;
      padding: 2px;
      margin: 4px;
      font: menu;
      color: black;
      border: 1px solid white;
    }
    tbody A:hover {
      border: 1px solid #4A6799;
      background-color: #D0DCF7;
    }
	table thead td {
		border: 2px outset buttonhighlight;
		background-color: buttonface;
		text-align: center;
		height: 20px;
	}
	table thead td a, table thead td a:hover {
		text-decoration: none;
		color: black;
		display: block;
		font: menu;
		padding-top: 2px;
	}
</style>
<script>
	function View(path) {
		window.location=path;
		return false;
	}
</script>
</head>
<body bgcolor="white">
<div class='listcontainer'>
<table class="list" width="100%" border="0" cellspacing="0" cellpadding="4"><tr>
<?php
    $server_name=eregi_replace("^[htps:/]*/","",$AR->host);

	if ($_SERVER["HTTP_HOST"]==$server_name) {
		$currentpath=$this->store->get_config("root").$this->path;
  	} else {
		$currentpath=$this->make_url();
	}
	if ($AR->user->data->login=="admin") {
		echo "<thead>";
		if( $showall ) {
			echo "<tr><td colspan=\"4\"><a href=\"".$currentpath."object.new.select.types.phtml?showall=0\">".$ARnls["show"].": ".$ARnls["typetree"]."</a></td></tr>";
		} else {
			echo "<tr><td colspan=\"4\"><a href=\"".$currentpath."object.new.select.types.phtml?showall=1\">".$ARnls["show"].": ".$ARnls["all"]."</a></td></tr>";
		}
		echo "</thead>";
	}
	echo "<tbody>";

	$result = array();
	if (!$showall) {
		$configcache = $ARConfig->cache[$this->path];
		if (0 && $configcache->typetree) {
			$configtypes = $this->ls($configcache->typetree . "/" . $this->type . "/", "system.get.phtml");
			foreach($configtypes as $object) {
				$type = $object->data->value;
				$name = $object->nlsdata->name;

				$result[$type] = $name;
			}
		} else {
			$typetree = $this->call('typetree.ini');
			$thistypetree = $typetree[$this->type];

			while (list($type, $name) = each($thistypetree)) {
				$result[$type] = $name;
			}
		}
	} else {
		$systemtypes = $this->ls("/system/ariadne/types/", "system.get.phtml");
		foreach ($systemtypes as $object) {
			$type=$object->data->value;
			$name=$object->nlsdata->name;

			$result[$type] = $name;
		}

		$typetree = $this->call('typetree.ini');
		foreach ($typetree as $value) {
			while (list($type, $name) = each($value)) {
				$result[$type] = $name;
			}
		}
	}

	$cols=4;
	if($result && is_array($result) && count($result)) {
		$col=1;
		while (list($type, $name) = each($result)) {
			if (!$this->CheckSilent("add",$type)) {
				$class="class='greyed'";
			} else {
				$class="";
			}
			if ($col>$cols) {
				$col=1;
				echo "</tr><tr valign='top'>";
			}
			$dotPos=strpos($type, '.');
			if (false!==$dotPos) {
				$realtype=substr($type, 0, $dotPos);
			} else {
				$realtype=$type;
			}
			$icon=$ARCurrent->arTypeIcons[$type]['default'];
			if (!$icon) {
				$dotPos=strpos($type, '.');
				if (false!==$dotPos) {
					$realtype=substr($type, 0, $dotPos);
				} else {
					$realtype=$type;
				}
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
				if (!$icon) {
					$icon=$AR->dir->images."icons/".$realtype.'_open.gif';
				}
			}
			?>
				<td valign="top" align="center" width="<?php echo (100/$cols); ?>%">
					<a <?php echo $class; ?> href="#" onClick="return View('<?php echo $currentpath.$arReturnTemplate; ?>?arNewType=<?php echo RawUrlEncode($type)."&".ldGetServerVar("QUERY_STRING"); ?>');">
					<img width="40" height="40" src="<?php echo $icon; ?>" alt="<?php echo $type; ?>" border="0"><br>
					<?php
						echo "$name</a>";
					?></a>
				</td>
			<?php
			$col++;
		}
		while ($col<=$cols) {
			echo "<td>&nbsp;</td>\n";
			$col++;
		}
	} else {
		error($ARnls["err:wronggrants"]);
	}
?>
</tr>
</tbody>
</TABLE>
</div>
</body>
<?php
	}
?>