<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["logoff"]; ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
<script>
	function init() {
		document.confirmform.cancel.focus();
	}
</script>
</head>
<body onLoad="init()">
<table border="0" width="100%" cellspacing="0" cellpadding="2">
<form action="<?php echo $this->make_url($AR->user->path); ?>logoff.phtml" name="confirmform">
<input type="hidden" name="action" value="delete">
<tr>
	<td align="center" colspan="2">
		<?php echo $ARnls["q:logoff"]; ?><p>
	</td>
</tr><tr>
	<td align="right">
		<input type="submit" name="cancel" style="width: 100px" value="<?php echo $ARnls["no"]; ?>" onClick="window.close();">
	</td><td align="left">
		<input type="submit" name="submit" style="width: 100px" value="<?php echo $ARnls["yes"]; ?>" onCLick="window.opener.top.document.location.href='<?php echo $this->make_url($AR->user->path); ?>logoff.phtml'; window.close();">
	</td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>