<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		include($this->store->get_config("code")."nls/menu.".$nls);
		$exporttype = $this->getvar('exporttype','none');

		switch($exporttype){
			case 'wddx':
				$this->call('object.export.wddx.phtml');
				break;
			case 'ax':
				$this->call('object.export.ax.phtml');
				break;
			default:
				$this->error = $ARnls["selectexporttype"];
		}
		
	}
?>