<?php
	/******************************************************************
	 object.link.save.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.linkto.phtml
	 Grant needed: none
	 Global variables: none

	 This template is a wrapper around the system.linkto.phtml 
	 template.

	 No result
	
	******************************************************************/

	if ($error=$this->call("system.linkto.phtml", $arCallArgs)) {
		$this->error=$error;
	}
	if (!$this->error) {
		?>
		<script>
//			window.close();
		</script>
		<?php
	} else {
		$this->call("show.error.phtml");
	}
?>