<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $ARnls["m_import"]; ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
<script>
	function update() {
		if (window.opener) {
			window.opener.location.href=window.opener.location.href;
		}
	}
</script>
</head>
<body onLoad="update();">
<table border="0" width="100%" cellspacing="0" cellpadding="2">
<form name="importform">
<tr>
	<td align="center" colspan="2">
		<textarea cols="50" rows="13" wrap="off"><?php
			$file = ldRegisterFile("source", $this->error);
			if ($file && !$this->error) { 
				require($this->store->code."/configs/axstore.phtml");
				include($this->store->code."/stores/axstore.phtml");

				$ARCurrent->options["verbose"]=true;
				if ($without_grants=$this->getdata("without_grants","none")) {
					$ARCurrent->options["without_grants"]=true;
				}
				if ($without_data=$this->getdata("without_data","none")) {
					$ARCurrent->options["without_data"]=true;
				}
				if ($without_templates=$this->getdata("without_templates","none")) {
					$ARCurrent->options["without_templates"]=true;
				}
				if ($without_files=$this->getdata("without_files","none")) {
					$ARCurrent->options["without_files"]=true;
				}
				if ($force=$this->getdata("force","none")) {
					$ARCurrent->options["force"]=true;		
				}
				$source = $this->store->files."temp/".$file["source_temp"];
				$ax_config["writeable"]=false;
				$ax_config["database"]=$source;
				set_time_limit(0);

				$store=new axstore("", $ax_config);
				if (!$store->error) {

					$ARCurrent->importStore=&$this->store;
					// srcpath and destpath may be empty
					$callArgs=Array("srcpath" => $srcpath,
									"destpath" => $this->path);

					$store->call("system.export.phtml", $callArgs,
						$store->get("/"));
					$error=$store->error;

					$store->close();

				} else {
					$error="import error: ".$store->error;
				}
				unlink($source);
			} else {
				$error="import error: '$source' could not find uploaded file. (does the filesize exceed the maximum upload size?)";
			}

			if ($error) {
				echo $error."\n";
			}
		?></textarea>
	</td>
</tr><tr>
	<td align="right">
		<input type="submit" name="submit" style="width: 100px" value="<?php echo $ARnls["ok"]; ?>" onClick="window.close();">
	</td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>
