<?php
	/******************************************************************
	 object.new.select.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: add
	 Global variables: none

	 No result.

	******************************************************************/
	if ($this->CheckLogin("add") && $this->CheckConfig()) {
		if (!$arReturnTemplate) {
			$arReturnTemplate="object.new.phtml";
		}
?>
<html>
<title><?php echo $ARnls["selecttype"]; ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
<style>
	.list {
		BACKGROUND-COLOR: white;
		WIDTH: 100%;
		HEIGHT: 100%;
	}
	<?php
		$browser=$this->call("browsercheck.phtml");
		if ($browser["id"]!="ns" || $browser["version"]!=4) {
		?>
			.listcontainer {
				BORDER-STYLE: inset;
				BORDER-WIDTH: thin;
				WIDTH: 100%;
				HEIGHT: 100%;
				OVERFLOW: auto;
			}
		<?php
		}
	?>
	.greyed {
		COLOR: #CCCCCC;
	}
</style>
<body bgcolor="white">
<div class="listcontainer">
<table class="list" width="100%" border="0" cellspacing="0" cellpadding="4"><tr>
<?php
	if ($AR->user->data->login=="admin") {
		$result=$this->ls("/system/ariadne/types/","system.get.phtml");
	} else {
		if ($ARConfig->typetree) {
			$result=$this->ls($ARConfig->typetree."/".$this->type."/",
				"system.get.phtml");
		} else {
			$result=$this->ls("/system/ariadne/typetree/normal/".$this->type."/",
				"system.get.phtml");
		}
	}
	$cols=4;
	if ($result && is_array($result)) {
		$col=1;
		while (list($key, $object)=each($result)) {
			$type=$object->data->value;
			$name=$object->nlsdata->name;
			if (!$this->CheckSilent("add",$type)) {
				$class="class='greyed'";				
			} else {
				$class="";
			}
			if ($col>$cols) {
				$col=1;
				echo "</tr><tr valign='top'>";
			}
			?>
				<td valign="top" align="center" width="<?php echo (100/$cols); ?>%">
					<a <?php echo $class; ?> href="<?php echo $arReturnTemplate; ?>?arNewType=<?php echo RawUrlEncode($type); ?>">
					<img width="40" height="40" 
						 src="<?php echo $AR->dir->images."icons/".$type; ?>_open.gif" 
						 alt="<?php echo $type; ?>" border="0"><br>
					<?php
						echo "$name</a>";
					?></a>
				</td>
			<?php
			$col++;
		}
		while ($col<=$cols) {
			echo "<td>&nbsp;</td>\n";
			$col++;
		}
	} else {
		error("Something is wrong with your grants, please contact the system administrator.");
	}
?>
</tr>
</TABLE>
</div>
</body>
<?php
	}
?>