<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {

		require($this->store->get_config("code")."/configs/axstore.phtml");
		include($this->store->get_config("code")."/stores/axstore.phtml");

		$ARCurrent->options["verbose"]=true;
		if ($without_grants=$this->getdata("without_grants","none")) {
			$ARCurrent->options["without_grants"]=true;
		}
		if ($without_data=$this->getdata("without_data","none")) {
			$ARCurrent->options["without_data"]=true;
		}
		if ($without_templates=$this->getdata("without_templates","none")) {
			$ARCurrent->options["without_templates"]=true;
		}
		if ($without_files=$this->getdata("without_files","none")) {
			$ARCurrent->options["without_files"]=true;
		}

        set_time_limit(0);

		$ax_config["database"]=tempnam($this->store->get_config("files")."temp/","ax");
		@unlink($ax_config["database"]);
		$srcpath=$this->path;
		$ax_config["writeable"]=true;
		$ARCurrent->session->put("tempname",$ax_config["database"]);
		if ($full_path) {
			$destpath="";
		} else {
			if ($this->parent=="..") {
				$destpath="/";
			} else {
				$destpath="/".substr($this->path, strlen($this->parent));
			}
		}
?>
<script>
	error=false;
	window.onload=startdownload;
	
	function startdownload() {
		if (!error) {
			location.href='object.export.ax';
		}
	}
	
</script>

<pre style="background-color: white; border: 2px inset buttonhighlight; font-size: 12px; margin: 4px; padding: 2px;"><?php
			echo "Exporting $srcpath to $destpath\n";
			$importStore=new axstore("", $ax_config);
			if (!$importStore->error) {
				set_time_limit(0);
				$ARCurrent->importStore=&$importStore;
				$callArgs=Array("srcpath" => $srcpath,
								"destpath" => $destpath);

				$error = $this->call("system.export.phtml", $callArgs);
				$importStore->close();

			} else {
				$error="ax error: ".$importStore->error;
			}

			if ($error) {
				echo $error."\n";
			}
		?>
</pre><?php
		if ($error) {
			// prevent js download code from running 
			echo "<script> error=true; </script>";
		}
	}
?>