<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {

		require($this->store->code."/configs/axstore.phtml");
		include($this->store->code."/stores/axstore.phtml");

		$ARCurrent->options["verbose"]=true;
		if ($without_grants=$this->getdata("without_grants","none")) {
			$ARCurrent->options["without_grants"]=true;
		}
		if ($without_data=$this->getdata("without_data","none")) {
			$ARCurrent->options["without_data"]=true;
		}
		if ($without_templates=$this->getdata("without_templates","none")) {
			$ARCurrent->options["without_templates"]=true;
		}
		if ($without_files=$this->getdata("without_files","none")) {
			$ARCurrent->options["without_files"]=true;
		}

        set_time_limit(0);

		$ax_config["database"]=tempnam($this->store->files."temp/","ax");
		@unlink($ax_config["database"]);
		$srcpath=$this->path;
		$ax_config["writeable"]=true;
		$ARCurrent->session->put("tempname",$ax_config["database"]);
		if ($full_path) {
			$destpath="";
		} else {
			if ($this->parent=="..") {
				$destpath="/";
			} else {
				$destpath="/".substr($this->path, strlen($this->parent));
			}
		}
?>
<html>
<head>
<title><?php echo $ARnls["m_export"]; ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
<script>
	error=false;

	function startdownload() {
		if (!error) {
			location.href='object.export.ax';
		}
	}
	
</script>
</head>
<body onLoad="startdownload();">
<table border="0" width="100%" cellspacing="0" cellpadding="2">
<form name="importform">
<tr>
	<td align="center" colspan="2">
		<textarea cols="50" rows="13" wrap="off" style="width: 100%"><?php
			echo "Exporting $srcpath to $destpath\n";
			$importStore=new axstore("", $ax_config);
			if (!$importStore->error) {
				set_time_limit(0);
				$ARCurrent->importStore=&$importStore;
				$callArgs=Array("srcpath" => $srcpath,
								"destpath" => $destpath);
				$error=current($this->store->call("system.export.phtml", $callArgs,
					$this->store->get('/')));

				$importStore->close();

			} else {
				$error="ax error: ".$importStore->error;
			}

			if ($error) {
				echo $error."\n";
			}
		?></textarea>
		<?php
			if ($error) {
				// prevent js download code from running 
				echo "<script> error=true; </script>";
			}
		?>
	</td>
</tr><tr>
	<td align="right">
		<input type="submit" name="submit" style="width: 100px" value="<?php echo $ARnls["ok"]; ?>" onClick="window.close();">
	</td>
</tr>
</form>
</table>
</body>
</html>
<?php
	}
?>