<?php
	/******************************************************************
	 object.new.select.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: add
	 Global variables: none

	 No result.

	******************************************************************/
	if ($this->CheckLogin("add", ARANYTYPE) && $this->CheckConfig()) {
		global $QUERY_STRING;
		if (!$arReturnTemplate) {
			$arReturnTemplate="object.new.phtml";
		}
?>
<html>
<head>
<title><?php echo $ARnls["addnewobject"]; ?></title>
<?php
	include($this->store->code."widgets/wizard/classic.css");
?>
</head>
<body bgcolor="white">
<iframe style="padding: 0px; border: 0px; margin: 0px; width: 100%; height: 100%;" src="object.new.select.types.phtml?arReturnTemplate=<?php echo RawUrlEncode($arReturnTemplate); ?>">
</iframe>
</body>
<?php
	}
?>