<?php
	/******************************************************************
	 edit.object.cache.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template manages the flow of the cache configuration wizard.
	 
	 no result

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		include($this->store->get_config("code")."widgets/wizard/code.php");
		include($this->store->get_config("code")."nls/menu.".$nls);

		$start="object.export.form.phtml";
		$finish="object.export.do.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["save"]=$finish;
		$wgWizFlow[0]["cancel"]='js.window.close.phtml';
		$wgWizFlow[0]["template"]='object.export.form.phtml';
                
		$wgWizTitle=$ARnls["m_export"]." ".$nlsdata->name;		
		$wgWizSaveButton=$ARnls["m_export"];
        $wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'wizard/sections/config.gif" alt="" hspace="4" align="absmiddle">';
		$wgWizTabsTemplate=false;
		$wgWizAction=$this->getdata('wgWizAction');
		if ($wgWizAction=='save') {
			$wgWizCancelButton=$ARnls['ok'];
			$wgWizSaveButton=false;
		}
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>