<?php
	if ($this->CheckLogin("config") && $this->CheckConfig()) {
?>
<html>
<head>
<style>
	.width100 { width: 100; }
	.width200 { width: 200; }
	.width300 { width: 300; }
	H1		{ FONT: 12pt sans-serif; FONT-WEIGHT: bold; }
	TD				{ FONT: 10pt sans-serif; }
	BODY			{ FONT: 10pt sans-serif;
							BORDER: 0;
	<?php
		$browser=$this->call("browsercheck.phtml");
		if ($browser["id"]=="ns" && $browser["version"]<=4) {
	?>
							BACKGROUND-COLOR: #BBBBBB;
	<?php
		} else {
	?>
							BACKGROUND-COLOR: buttonface;
	<?php
		}
	?>
	}
</style>
<script>
	<?php
		if ($browser["id"]!="ns" || $browser["version"]!=4) {
		?>
			function setownernode() {
				top.setownernode();
			}
		<?php
		}
	?>
	function reloadpage(args) {
		if (document.layers) {
			window.document.layers.info.src=window.document.layers.info.src+args;
		} else {
			document.location.href=document.location.href+args;
		}
	}
</script>
</head>
<body bgcolor="#BBBBBB" onLoad="nextnode();" scroll="no">
<?php 
	$owner = $this->make_path($owner);
	echo $ARnls["settingowner"]. " ($owner)<br>".$this->path; 
	$this->call('system.save.owner.phtml', Array('owner' => $owner));
		?>
			<script>
				function nextnode() {
					<?php
						if ($this->error) {
							echo "\n// $this->error\n";
							?>
							if (!confirm('<?php echo AddCSlashes(sprintf($this->error,$newpath), ARESCAPE); ?>')) {
								if (top.window) {
									top.window.close();
								} else {
									window.close();
								}
							} 
							<?php
						}
					?>
					window.setTimeout("setownernode();",100);
				}
			</script>
</body>
</html>
<?php
	}
?>