<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
?>
<html>
<head>
<style>
	.width100 { width: 100px; }
	.width200 { width: 200px; }
	.width300 { width: 300px; }
	H1		{ 
		FONT: 12pt sans-serif; 
		FONT-WEIGHT: bold;
	}
	TD				{
		FONT: 10pt sans-serif;
	}
	BODY			{
		FONT: 10pt sans-serif;
		BORDER: 0;
	<?php
		$browser=$this->call("browsercheck.phtml");
		if ($browser["id"]=="ns" && $browser["version"]<=4) {
			?>
				BACKGROUND-COLOR: #BBBBBB;
			<?php
		} else {
			?>
				BACKGROUND-COLOR: buttonface;
			<?php
		}
	?>
	}
</style>
</head>
<body bgcolor="#BBBBBB" onLoad="nextnode();" scroll="no">
<?php 
	echo $ARnls["deleting"]." ($current/$total)<br>".$this->path; 
?>
<script>
	<?php
		if ($browser["id"]!="ns" || $browser["version"]!=4) {
			?>
				function deletenode() {
					window.parent.deletenode();
				}

			<?php
		}
	?>
	function nextnode() {
		<?php
			$this->call("system.delete.phtml");
			$rootpath=$this->getvar('rootpath');
			if ($rootpath && $rootpath==$this->path) {
				$this->unlock();
			}
			if ($this->error) {
				$rootpath=$this->getvar('rootpath');
				if ($rootpath) {
					if ($this->store->mod_lock) {
						$this->store->mod_lock->unlock($AR->user->data->login, $rootpath);
					}
				}
		?>
		if (!confirm('<?php echo AddCSlashes(sprintf($this->error,$this->path), ARESCAPE); ?>')) {
			if (top.window) {
				top.window.close();
			} else {
				window.close(); 
			}
		} 
		<?php
			}
		?>
		window.setTimeout("deletenode();",100);
	}
</script>
</body>
</html>
<?php
	}
?>