<?php
  debug($this->type."/ReleaseLock.phtml: $id","class");
  $arResult=0;
  if ($this->CheckSilent("edit") || $this->CheckSilent("delete")) {
    if ($data->locked) {
      debug("lock found","all");
      if ($data->locked["id"]==$id) {
        debug("and released","all");
        $arResult=$data->locked;
        unset($data->locked);
        $properties["locked"]=1;
        $this->save($this->path, $this->type, $data, $properties);
      }
    } else { // object wasn't locked anyway
      debug("no lock found: released ok","all");
      $arResult=1;
    }
  }
  debug($this->type."/ReleaseLock.phtml: end","all");
?>