<?php
  if ($this->CheckLogin("layout")) {
    if (!ereg("\.\.",$function) && eregi("^[a-z0-9\._-]+$",$function)) {
      if ($data->pinp[$type][$function][$language]) {
        while (list($oldtype, $functions)=each($data->pinp)) {
          while(list($oldfunction, $oldtemplatelist)=each($functions)) {
            while(list($oldlanguage, $value)=each($oldtemplatelist)) {
              if (($oldfunction!=$function) ||
                  ($oldtype!=$type) ||
                  ($oldlanguage!=$language)) {
                $pinp[$oldtype][$oldfunction][$oldlanguage]=$value;
              }
            }
          }
        }
        $data->pinp=$pinp;
        if ($data->templates[$type][$function][$language]) {
          while (list($oldtype, $functions)=each($data->templates)) {
            while(list($oldfunction, $oldtemplatelist)=each($functions)) {
              while(list($oldlanguage, $value)=each($oldtemplatelist)) {
                if (($oldfunction!=$function) ||
                    ($oldtype!=$type) ||
                    ($oldlanguage!=$language)) {
                  $templates[$oldtype][$oldfunction][$oldlanguage]=$value;
                }
              }
            }
          }
          $data->templates=$templates;
        }
        $this->save($this->path, $this->type, $data);
        unlink($this->store->files."templates".$this->path.$type."/".$function.".".$language);
        unlink($this->store->files."templates".$this->path.$type."/".$function.".".$language.".pinp");
      }
      Header("Location: ".$this->store->root.$this->path."templates.phtml");
    } else {
      echo "Tsk, tsk.";
    }
  } 
?>