<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		if (!$modifier) {
			$modifier=ARTHISTYPE;
		}
		if (!$grant || $this->CheckSilent($grant, $modifier)) {
			if (!$arLanguage) {
				$arLanguage = $nls;
			}
			?><option value="<?php echo $this->path; ?>"<?php 
			if ($selected==$this->path) { 
				echo " selected";
			} 
			?>><?php echo $this->showdata('name', $arLanguage); ?></option><?php
		}
	}
?>
