<?php
  if ($this->CheckSilent("read") && $this->CheckConfig()) {
	if (is_array($this->data->nls->list)) {
		reset($this->data->nls->list);
		foreach ($this->data->nls->list as $nlskey => $nlsvalue) {
			if (is_object($this->data->$nlskey)) {
				reset($this->data->$nlskey);
				foreach ($this->data->$nlskey as $key => $value) {
					$result[$nlskey][$key] = (string)$value;
				}
			}
		}
	}

	$result["type"] = $this->type;
	$result["value"] = (string)$this->data->value;

	$arResult = $result;
  }
?>
