<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {

		$username = $_POST['username'];
		$password = $_POST['password'];

		if (! (isset($username) && isset($password)) ) {
			?>
				<form method="post">
					SVN user: <input type="text" name="username">
					SVN pass: <input type="password" name="password">
					<input type="submit" value="checkout">
				</form>
			<?php
		} else {
			$arCallArgs['username'] = $username;
			$arCallArgs['password'] = $password;
			set_time_limit(0);
			$this->find($this->path, '', "svn.system.update.recursive.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>