<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->parents($path,"svn.system.getrepo.phtml");
		$repository = $this->getvar("repository");

		if (isset($repository)) {
			$repository = rtrim($repository, "/");
			$repoPath = $this->getvar("repoPath");
			$repository = $repository . "/" . substr($this->path, strlen($repoPath));

			$fstore	= $this->store->get_filestore_svn("templates");
			$svnstack = &PEAR_ErrorStack::singleton('VersionControl_SVN');
			$svn	= $fstore->connect($this->id, $repository, $username, $password);

			$status = $fstore->svn_diff($svn);

			echo(htmlspecialchars($status));
		}
	}
?>