<?php 
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> 
	<html>
	<head>
		<title>SVN info: <?php echo $this->nlsdata->name; ?></title>
		<style type="text/css">
			.svninfokey {
				width: 150px;
				height: 20px;
				display: block;
				float: left;
			}
			.svninfovalue {
				float: left;
			}
			#svninfo br {
				clear: both;
			}	
		</style>
	</head>
	<body>
		<div id="svninfo">
<?php
	set_time_limit(0);
	//$this->call($this->path, "svn.system.info.phtml", $arCallArgs);
	$this->call("svn.system.info.phtml", $arCallArgs);
?>
		</div>
	</body>
	</html>
<?php
	}
?>
