<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$svn_repo = $_POST['svn_repo'];
		if (isset($svn_repo)) {
			$arCallArgs['svn_repo'] = $svn_repo;
			echo "Testing repository and fetching certificate\n";
			$this->call('svn.system.config.phtml', $arCallArgs);
			echo "SVN settings saved\n";
		}

		$this->parents('',"svn.system.getrepo.phtml", '', '/');
		$repository = $this->getvar("repository");

		if (isset($this->data->svn)) {
			$disabled = "";
		} else {
			$disabled = " disabled";
		}

		if (isset($repository)) {
			$repository = rtrim($repository, "/");
			$repoPath = $this->getvar("repoPath");
			$repository = $repository . "/" . substr($this->path, strlen($repoPath));
		}

		?>
		<form method="post">
			Using repository: <?php echo $repository;?><br>
			Configured repository: <input type="text" name="svn_repo" size=50 value="<?php echo $this->data->svn;?>">
			SVN user: <input type="text" name="username">
			SVN pass: <input type="password" name="password">
			<input type="submit" value="save">
		</form>
</pre>
</div>

<?php
	}

?>

</pre>
