<?php
	echo "SSCUR: " . $this->path . "<br>";

	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		if (isset($repository)) {
			$repository = rtrim($repository, "/") . "/";
			$fstore	= $this->store->get_filestore_svn("templates");
			$svn	= $fstore->connect($this->id, $username, $password);

			if ($svn['info']['Revision']) {
				echo $this->path . " is already under version control - update instead.<br>";
			}

			echo "<br>";
			echo "Checkunder for " . $this->path . "<br>";

			if ($repoPath) {
				$repo_subpath = substr($this->path, strlen($repoPath));
			} else {
				// This is also the first loop!
				$fstore->svn_accept_cert($svn, $repository);
				$repo_subpath = '';
			}

			$repository = rtrim($repository, "/") . "/" . $repo_subpath;
			echo "Using repo: $repository<br>";

			// Checkunder the templates.
			$result = $fstore->svn_checkunder($svn, $repository);
			print_r($result);

			// Run checkunder on the existing subdirs.
			$arCallArgs['repoPath'] = $this->path;
			$this->ls($this->path, "svn.system.checkunder.recursive.phtml", $arCallArgs);

			// Create the dirs and checkout them if needed.
			$dirlist = $fstore->svn_list($svn);
			if ($dirlist) {
				$arCallArgs['dirlist'] = $dirlist;
				$arCallArgs['svn'] = $svn;
				$arCallArgs['fstore'] = $fstore;
				$arCallArgs['repository'] = $repository;
				$this->call("svn.system.checkout.dirs.phtml", $arCallArgs);
			}
			flush();
		}
	}
?>