<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
if ($this->CheckLogin("layout") && $this->CheckConfig()) {

	$repository = $_POST['repository'];
	$username = $_POST['username'];
	$password = $_POST['password'];
	$message  = $_POST['message'];

	if (! (isset($repository) && isset($username) && isset($password)) ) {
		?>
			<form method="post">
			SVN repository: <input type="text" name="repository">
			SVN user: <input type="text" name="username">
			SVN pass: <input type="password" name="password">
			Message: <input type="text" name="message">
			<input type="submit" value="import">
			</form>
			<?php
	} else {
		set_time_limit(0);
		$this->find($this->path, 'order by path', "svn.system.import.phtml", $arCallArgs);
	}
}
?>
</pre>
</div>