<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		$fstore	= $this->store->get_filestore_svn("templates");
		$svn	= $fstore->connect($this->id, $username, $password);

		$fileinfo = array();

		$pinp_filename = $type . "." . $function . "." . $language . ".pinp";
		if ($this->data->config->templates[$type][$function]) {
			$default = 1;
		} else {
			$default = 0;
		}

		$fileinfo[$pinp_filename] = array();
		$fileinfo[$pinp_filename]['ar:function'] = $function;
		$fileinfo[$pinp_filename]['ar:type'] = $type;
		$fileinfo[$pinp_filename]['ar:language'] = $language;
		$fileinfo[$pinp_filename]['ar:default'] = $default;										
		$fstore->svn_add($svn, $pinp_filename);
		$result = $fstore->svn_commit($svn, $message, $fileinfo);
		print_r($result);

		if ($result === false) {
			echo "Commit failed.<br>";
			if (count($errs = $fstore->svnstack->getErrors())) {
				foreach ($errs as $err) {
					echo $err['message']."<br>\n";
				}
			}
		}
		flush();
	}
?>