<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {

		$username = $_POST['username'];
		$password = $_POST['password'];
		$repository = $_POST['repository'];
		$message  = $_POST['message'];

		if (! (isset($repository) && isset($username) && isset($password)) ) {
			?>
				<form method="post">
					SVN repo: <input type="text" name="repository">
					SVN user: <input type="text" name="username">
					SVN pass: <input type="password" name="password">
					Message: <input type="text" name="message">
					<input type="submit" value="import">
				</form>
			<?php
		} else {
			$this->call("svn.system.import.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>
		<form method="post" action="edit.object.layout.phtml">
			<input type="submit" value="back">
		</form>