<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$repository = $this->data->svn;

		if (isset($repository)) {
			$arCallArgs['repository'] = $repository;
			$this->call("svn.system.revert.phtml", $arCallArgs);
		} else {
			echo "No SVN repository information set.";
		}
	}
?>
</pre>
</div>
<form method="post" action="edit.object.layout.phtml">
	<input type="submit" value="back">
</form>
