<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		if (! (isset($username) && isset($password)) ) {
			?>
				<form method="post">
					SVN user: <input type="text" name="username">
					SVN pass: <input type="password" name="password">
					SVN revision: <input type="text" name="revision">
					<input type="submit" value="update">
				</form>
			<?php
		} else {
			$this->call("svn.system.file.update.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>
<form method="post" action="edit.object.layout.form.phtml">
	<input type="submit" value="back">
	<input type="hidden" name="mode" value="edit">
	<input type="hidden" name="type" value="<?php echo $type;?>">
	<input type="hidden" name="language" value="<?php echo $language;?>">
	<input type="hidden" name="function" value="<?php echo $function;?>">
</form>