<?php 
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
?>
	<html>
	<head>
		<title>SVN info: <?php echo $this->nlsdata->name; ?></title>
		<style>
			#svninfo {
				width: 100%;
				height: 100%;
				overflow: auto;
			}
			.svninfokey {
				width: 150px;
			}
			.svninfovalue {
			}
		</style>
	</head>
	<body>
		<div id="svninfo">
<?php
	set_time_limit(0);
	//$this->call($this->path, "svn.system.info.phtml", $arCallArgs);
	$this->call("svn.system.info.phtml", $arCallArgs);
?>
		</div>
	</body>
	</html>
<?php
	}
?>
