<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {

		$username = $_POST['username'];
		$password = $_POST['password'];

		if (! (isset($username) && isset($password)) ) {
			?>
				<form method="post">
					<input type="text" name="username">
					<input type="password" name="password">
					<input type="submit" value="checkout recursive">
				</form>
			<?php
		} else {
			echo "Doing recursive checkout...";
			set_time_limit(0);
			$this->call("svn.system.checkout.recursive.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>