<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		$fstore	= $this->store->get_filestore_svn("templates");
		$svnstack = &PEAR_ErrorStack::singleton('VersionControl_SVN');
		$svn	= $fstore->connect($this->id, $username, $password);

		$filename = $type . "." . $function . "." . $language . ".pinp";

		$result = $fstore->svn_update($svn, $filename, $revision);

		print_r($result);

		if ($result) {
			$templates = array();
			foreach ($result as $item) {
				if ($item['status'] != "C") {
					$templates[] = $item['name'];
				}
			}

			$this->call(
				"svn.system.compile.templates.phtml",
				array(
					'templates' 	=> $templates,
					'fstore'	=> $fstore,
					'svn'		=> $svn
				)
			);
		}
		if ($result === false) {
			echo "Update failed.<br>";
			if (count($errs = $svnstack->getErrors())) {
				foreach ($errs as $err) {
					echo $err['message']."<br>\n";
				}
			}
		}
	}
?>
