<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		if (! (isset($username) && isset($password)) ) {
			?>
				<form method="post">
					SVN user: <input type="text" name="username">
					SVN pass: <input type="password" name="password">
					<input type="submit" value="update recursive">
				</form>
			<?php
		} else {
			set_time_limit(0);
			$this->call("svn.system.update.recursive.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>