<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		if (isset($repository)) {
			$repository = rtrim($repository, "/") . "/";
			$fstore = $this->store->get_filestore_svn("templates");
			$svn	= $fstore->connect($this->id, $username, $password);

			if ($svn['info']['Revision']) {
				echo $this->path . " is already under version control.<br>";
				return;
			}

			$fstore->svn_accept_cert($svn, $repository);
			$result = $fstore->svn_checkunder($svn, $repository, $revision);
			print_r($result);

			if ($result) {
				echo "[system.checkunder]<br>";

				$templates = array();
				foreach($result as $item) {
					$templates[] = $item['name'];
				}

				$this->call(
					"svn.system.compile.templates.phtml", 
					array(
						'templates' 	=> $templates,
						'fstore' 	=> $fstore,
						'svn'		=> $svn
					)
				);
			}
		}
	}
?>