<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		if (! (isset($repository) && isset($username) && isset($password)) ) {
			?>
				<form method="post">
					SVN repo: <input type="text" name="repository">
					SVN user: <input type="text" name="username">
					SVN pass: <input type="password" name="password">
					<input type="submit" value="checkout">
				</form>
			<?php
		} else {
			$this->call("svn.system.checkout.phtml", $arCallArgs);
		}
	}
?>
</pre>
</div>
<form method="post" action="edit.object.layout.phtml">
	<input type="submit" value="back">
</form>