<div style="width: 100%; height: 90%; overflow: auto">
<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$svn_repo = $_POST['svn_repo'];
		if (isset($svn_repo)) {
			$arCallArgs['svn_repo'] = $svn_repo;
			echo "Testing repository and fetching certificate\n";
			$this->call('svn.system.config.phtml', $arCallArgs);
			echo "SVN settings saved\n";
		}

		$repository = $this->data->svn;
		?>
		<form method="post">
			Repository: <input type="text" name="svn_repo" size=50 value="<?php echo $repository;?>">
			SVN user: <input type="text" name="username">
			SVN pass: <input type="password" name="password">
			<input type="submit" value="save">
		</form>
</pre>
</div>

		<form method="post" action="edit.object.layout.phtml">
			<input type="submit" value="back">
		</form>
<?php
	}

?>

</pre>
