<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		$fstore	= $this->store->get_filestore_svn("templates");
		$svnstack = &PEAR_ErrorStack::singleton('VersionControl_SVN');
		$svn	= $fstore->connect($this->id, $username, $password);

		$status = $fstore->svn_status($svn);

		if ($status) {
			$templates = array();
			foreach($status as $filename => $svn_status) {
				if ($svn_status == '?') {
					unset($status[$filename]);
				} else {
					$fstore->svn_revert($svn, $filename);
					$templates[] = $fstore->get_path($svn, $filename);
				}
			}

			$this->call(
				"svn.system.compile.templates.phtml",
				array(
					'templates' 	=> $templates,
					'fstore'	=> $fstore,
					'svn'		=> $svn
				)
			);
		}
	}
?>