<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$repository = $this->data->svn;

		$username = $_POST['username'];
		$password = $_POST['password'];

		if (! (isset($username) && isset($password)) ) {
			?>
				<form method="post">
					<input type="text" name="username">
					<input type="password" name="password">
					<input type="submit" value="checkout">
				</form>
			<?php
		} else {
			$arCallArgs['repository'] = $repository;
			$this->call("svn.system.checkout.phtml", $arCallArgs);
		}
	}
?>
</pre>
<form method="post" action="edit.object.layout.phtml">
	<input type="submit" value="back">
</form>
