<pre>
<?php
        if ($this->CheckLogin("layout") && $this->CheckConfig()) {

		$repository = $this->data->svn;

		if (isset($repository)) {
			$username 	= $_POST['username'];
			$password 	= $_POST['password'];
			$message 	= $_POST['message'];

			if (! (isset($username) && isset($password)) ) {
				?>
					<form method="post">
						SVN user: <input type="text" name="username">
						SVN pass: <input type="password" name="password">
						Commit message: <input type="text" name="message">
						<input type="submit" value="commit">
					</form>
				<?php
			} else {
				$arCallArgs['repository'] = $repository;
				$arCallArgs['username'] = $username;
				$arCallArgs['password'] = $password;
				$arCallArgs['message'] = $message;
				$this->call("svn.system.commit.phtml", $arCallArgs);
			}
		} else {
			echo "No repository set";
		}
	}
?>
</pre>
 		<form method="post" action="edit.object.layout.phtml">
			<input type="submit" value="back">
		</form>
