<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		$this->resetloopcheck();

		$fstore	= $this->store->get_filestore_svn("templates");
		$svn	= $fstore->connect($this->id, $username, $password);

		$filename = $type . "." . $function . "." . $language . ".pinp";

		$fstore->svn_revert($svn, $filename);

		$templates = array();
		$templates[] = $fstore->get_path($svn, $filename);

		$this->call(
			"svn.system.compile.templates.phtml",
			array(
				'templates' 	=> $templates,
				'fstore'	=> $fstore,
				'svn'		=> $svn
			)
		);
	}
?>