<?php
	if ($this->CheckLogin("edit")) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		if (!is_numeric($this->getdata("priority", "none"))) {
			$this->error = $ARnls['err:prioritynotnumber'];
		} else {
			$this->data=current($this->get(".","system.get.data.phtml"));
			$this->priority=(int)$this->getdata("priority","none");
			$this->save();
			$this->ClearCache();
		}
	}
?>
