<?php
  /******************************************************************
   system.get.value.phtml						   Muze Ariadne v2.1
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: none
   Global variables: none

   Returns the value of this object.

  ******************************************************************/
  $arResult=$data->value;
?>
