<?php
	/******************************************************************
	 system.new.phtml                                      Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/
	$arNewType=$this->getdata("arNewType","none");
	if (!$arNewType) {
		$this->error=$ARnls["err:nonewtype"];
		// FROP $this->error="No arNewType defined";
	} else if ($this->CheckLogin("add", $arNewType) && $this->CheckConfig()) {
		include_once($this->store->code."widgets/wizard/code.php");
		$arNewFilename=$this->getdata("arNewFilename","none");
		$arNewData=new object;
		$arNewPath=$this->make_path($arNewFilename);
		$arNewCallObject=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewData);
		$arNewCallObject->arIsNewObject=true;

		if ($arNewType == 'pshortcut') {
			$arNewCallObject->call("system.save.shortcut.phtml", $arCallArgs);
		} else {
			$arNewCallObject->call("system.save.data.phtml", $arCallArgs);
		}
		if (!$arNewCallObject->error) {
			$arResult=$arNewCallObject->path;
		} else {
			$this->error=$arNewCallObject->error;
			$arResult=false;
		}
	}
?>