<?php
  debug($this->type."/system.lock.unset.phtml: $id","class");
  $arResult=0;
  if ($this->CheckSilent("edit") || $this->CheckSilent("delete")) {
    if ($data->locked) {
      if ($data->locked["id"]==$id) {
        $arResult=$data->locked;
        unset($data->locked);
        $properties["locked"]=1;
        $this->save($this->path, $this->type, $data, $properties);
      }
    } else { // object wasn't locked anyway
      $arResult=1;
    }
  }
?>