<?php   
  if ($this->CheckSilent("delete")) {
    if (($result=$this->lock(0,"T")) && ($result["identity"])) {
      $this->error=$ARnls["err:cannotlockobject"];
    } else {
      if (!$this->ls(".","Get.phtml")) {
        // remove grants for this object in all user objects.
        if ($data->grants && is_array($data->grants)) {
          while (list($login, $grants)=each($data->grants)) {    
            $criteria["login"]["value"]["="]="'".$login."'";
            $this->find("/system/users/", $criteria, "updategrant.phtml", 
                        "action=delete&path=".RawUrlEncode($this->path)
                   );
          }
        }
        if ($data->pinp) {
          while (list($type, $values)=each($data->pinp)) {
            while (list($function, $templatelist)=each($values)) {
              while (list($language, $template)=each($templatelist)) {
                $file=$this->store->files."templates".$template;
                // FIXME: check for illegal values of $template
				if (file_exists($file)) {
                  unlink($file);
                }
                $file.=".pinp";
                if (file_exists($file)) {
                  unlink($file);
                }
              }
            }
          }
        }        
        $this->ClearCache();
        $this->delete($this->path);
      }
      $this->unlock();
    }
  } else {
    $this->error=$ARnls["nopermission"];
  }
?>