<?php
	/******************************************************************
	 system.get.folder.phtml							 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Interface/Widget: management/browse
	 Global variables: $AR->user

	 This template is responsible for returning the right name and icon 
	 for displaying an object in a tree or browselist.

	 It uses the global variable $AR->user, which references the user 
	 object (puser.phtml) of the currently logged on user, to check if 
	 this user has read access to this object. If not, the name will be 
	 greyed out.

	 result format:

	 $result["name"] is a html string containing the name of the object, 
		 possibly in grey.
	 $result["icon"] is the name of the icon to be displayed. The
		 calling function should decide what to do with it.
	 $result["path"] is the path to the object, as known by the object
		 (meaning, from the root of the current store).

	******************************************************************/
	require_once($this->store->get_config("code")."modules/mod_unicode.php");
	$name=unicode::utf8convert(trim($nlsdata->name));
	if ($AR->user && !$this->CheckSilent("read")) {
		$arResult["pre"]="<font color='#CCCCCC'>$flag";
		$arResult["name"]=$name."</font>";
	} else {
		$grants=$this->GetValidGrants();
		$arResult["pre"]=$flag;
		$arResult["name"]=$name;
	}
	$arResult["icon"]=$this->call('system.get.icon.small.phtml');
	$arResult["path"]=$this->path;
?>
