<?php
  /******************************************************************
	system.export.update.phtml				Muze Ariadne v2.1
	------------------------------------------------------------------
	Arguments: $this->import (object to import)
	Grant needed: edit
	Global variables: none

	Called when an object has to be updated from an export file.

	Returns true on success , false on an error.
  ******************************************************************/
  if ($this->CheckLogin("edit")) {
	if ($ARCurrent->options["without_grants"]??null) {
		$keep_grants	= $this->data->config->grants;
		$keep_usergrants = $this->data->config->usergrants;
	}
	$keep_templates = $this->data->config->templates??null;
	$keep_pinp		= $this->data->config->pinp??null;

	if ($ARCurrent->AXAction == "import") {
		unset($newObject->data->config->grants);
		unset($newObject->data->config->usergrants);
	}
	if (is_array($ARCurrent->options["nls"]??null)) {
		reset($ARCurrent->options["nls"]);
		while (list($nls) = each($ARCurrent->options["nls"])) {
			if ($newObject->data->nls->list[$nls]) {
				$this->data->nls->list[$nls] = $newObject->data->nls->list[$nls];
				$this->data->$nls = $newObject->data->$nls;
			}
		}
	} else {
		$this->data=$newObject->data;
	}
	$this->data->config->usergrants=$keep_usergrants??null;
	$this->data->config->grants=$keep_grants??null;
	$this->data->config->templates=$keep_templates??null;
	$this->data->config->pinp=$keep_pinp??null;
	$this->priority=$newObject->priority;

	$this->call( 'system.import.translations.phtml' );

	$this->save( $this->properties ?? null);

  } else {
	$arResult=false;
	$this->error=$ARnls["nopermimportnew"];
  }
?>
