<?php
	if ((($this->arIsNewObject &&
			($this->path == "/" ||
				($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
				$parentobj->CheckLogin("add", $this->type))) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		include_once($this->store->get_config("code")."modules/mod_unicode.php");

		if (!function_exists("convData2UTF8")) {
			function convData2UTF8($data, $charset) {
				if (is_array($data)) {
					reset($data);
					while (list($key, $val)=each($data)) {
						$data[$key] = convData2UTF8($val, $charset);
					}
				} else
				if (is_object($data)) {
					while (list($key, $val)=each($data)) {
						echo "converting ($key::$val)\n";
						$data->$key = convData2UTF8($val, $charset);
						echo "to (".$data->$key.")\n";
					}
				} else {
					$data = unicode::convertToUTF8($charset, $data);
				}
				return $data;
			}
		}

		if (is_array($convert_charsets ?? null)) {
			reset($convert_charsets);
			while (list($nls, $charset)=each($convert_charsets)) {
				echo "converting charset ($nls, $charset)\n";
				$this->data->$nls = convData2UTF8($this->data->$nls, $charset);
			}
		}

		/* these grants will be set at the end of the import process */
		if ($ARCurrent->AXAction == "import") {
			unset($this->data->config->grants);
			unset($this->data->config->usergrants);
		}

		if(!$this->store->is_supported("fulltext")){
			unset($this->properties['fulltext']);
		}

		$this->call('system.import.translations.phtml');

		$this->store->save(
				$this->path,
				$this->type,
				$this->data,
				$this->properties,
				$this->vtype,
				$this->priority,
				$this->axflags ?? null);

		$this->error = $this->store->error;
	}
?>
