<?php
  /******************************************************************
   system.get.phtml								 Muze Ariadne v2.110
   ------------------------------------------------------------------
   Called by: multiple
   Arguments: none
   Grant needed: none
   Interface/Widget: all
   Global variables: none

   Returns the complete PHP object. This should only be used for 
   complex operations where the normal method of only returning the 
   data needed is insufficient.
   
   NOTE: This template should be included in every template directory
   since it is often used with a large find or ls query. Failing to
   so will result in a large performance penalty.

  ******************************************************************/
  if (($context=$this->getContext(ARCALLINGCONTEXT)) 
  		&& $context["scope"]=="pinp") {

  	if ($this->CheckSilent('read')) {
  		$arResult = clone($this);
    }

  } else {

  	$arResult = clone($this);

  }
?>
