<?php
	if ($this->CheckLogin("layout") && $this->CheckConfig()) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=current($this->get(".","system.get.data.phtml"));

		unset($this->data->config->customconfig);
		$customfields = $this->getdata("customfields","none");
		if (is_string($customfields)) {
			parse_str($customfields);
		}
		if (is_array($customfields)) {
			while (list($key, $value)=each($customfields)) {
				$this->data->config->customconfig[$value["name"]]["type"]=$value["type"];
				$this->data->config->customconfig[$value["name"]]["inherit"]=$value["inherit"];
				$this->data->config->customconfig[$value["name"]]["size"]=$value["size"];
				$this->data->config->customconfig[$value["name"]]["nls"]=$value["nls"];
				$this->data->config->customconfig[$value["name"]]["grant"]=$value["grant"];
				$this->data->config->customconfig[$value["name"]]["check"]=$value["check"];
				$this->data->config->customconfig[$value["name"]]["property"]=$value["property"];
				$this->data->config->customconfig[$value["name"]]["containsHTML"]=$value["containsHTML"];
			}
		}
		if (!$this->error) {
			$this->save();
		}
	}
?>
