<?php
	/******************************************************************
	 system.get.type.phtml							 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 Returns the type of the current object. This is used by PShortCut
	 to determine the vtype to set. The vtype of PShortCut is set to
	 the type of the object to which PShortCut points.
 
	 result:
	 $result is a string containing a valid (ariadne) type.

	******************************************************************/
	$arResult=$this->type;
?>
