<?php
  /******************************************************************
	system.import.update.phtml				Muze Ariadne v2.0b
	------------------------------------------------------------------
	Arguments: $this->import (object to import)
	Grant needed: edit
	Global variables: none

	Called when an object has to be updated from an export file.

	Returns true on success , false on an error.
  ******************************************************************/

	echo "system.import.update.phtml (".$this->path.")\n";

  if ($this->CheckLogin("edit")) {

	// get object grants.

	$origgrants=$this->data->grants;
	$origusergrants=$this->data->usergrants;
	$this->data->grants=$this->import->data->grants;
	$this->data->usergrants=$this->import->data->usergrants;
	$this->call("system.import.get.grants.phtml");


	// set original grants back as these are going to be merged as def.
	$this->data->grants=$origgrants;
	$this->data->usergrants=$origusergrants;

	$this->save($this->properties, $this->vtype);

	if ($this->error) {
		$arResult=false;
	} else {
		$arResult=true;
	}

  } else {
	$arResult=false;
	$this->error="No permission to import a new object";
  }
?>