<?php
	debug("pobject/system.copyto.phtml: start","class");

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		if ($target && ($target!=".")) {
			debug("pobject/system.copyto.phtml: target:".$target.":","all");
			// first check to see if the target is valid
			$parent=$this->store->make_path($target, "..");
			if ($this->exists($parent)) {
				$pobject = current($this->get($parent, "system.get.phtml"));
				if ($pobject->CheckSilent("add", $this->type)) {
					$oldgrants = $this->data->grants;
					unset($this->data->grants);
					$target=$this->make_path($target);
					if (!$this->exists($target)) {
						// first make sure that the object is clean (data can only be set via 
						// the defined interface: $arCallArgs)
						$this->data=current($this->get(".","system.get.data.phtml"));

						// now save the object to get its new id.
						if (!$this->data->$defaultnls) {
							$this->data->nls->default=$ARConfig->nls->default;
						}
						$properties=$this->load_properties();
						$ARCurrent->newpath=$this->store->save($target, $this->type, $this->data, $properties, $this->vtype, $this->priority);
						if ($ARCurrent->newid=$this->exists($ARCurrent->newpath)) {

							// now save templates for the new object
							if ($this->data->pinp) {
								$templates=$this->store->get_filestore("templates");
								while (list($type, $values)=each($data->pinp)) {
									while (list($function, $templatelist)=each($values)) {
										while (list($language, $id)=each($templatelist)) {
											$template=$type.".".$function.".".$language;
											$templates->copy($this->id, $template.".pinp", $ARCurrent->newid, $template.".pinp");
											$templates->copy($this->id, $template, $ARCurrent->newid, $template);
											$this->data->pinp[$type][$function][$language]=$ARCurrent->newid;
		
											if ($this->data->templates[$type][$function][$language]) {
												$this->data->templates[$type][$function][$language]=$ARCurrent->newid;
											}
										}
									}
								}
							}

							$this->store->save($ARCurrent->newpath, $this->type, $this->data);

							$this->find($ARCurrent->newpath, "", "system.update.user.grants.phtml", array("config"=>$pobject->CheckSilent("config")));

						} // else: first save failed.

					} else {
						$arResult=sprintf($ARnls["err:alreadyexists"],$target);
					}
				} else {
					$arResult = $ARnls["accessdenied"];
				}
			} else {
				$arResult=sprintf($ARnls["err:wrongpath"],$parent);
			}
		} else {
			$arResult=sprintf($ARnls["err:wrongpath"],$target);
		}
	} else {
		$arResult=$ARnls["accessdenied"];
	}
	if ($arResult) {
		debug("pobject/system.copyto.phtml: arResult: $arResult;","class");
	} else {
		debug("pobject/system.copyto.phtml: end","class");
	}
?>