<?php
  debug($this->type."/system.get.lock.phtml: $id","class");
  if ($data->locked) {
    if ($id) {
      if (($data->locked["id"]==$id) && ($data->locked["duration"]>time())) {
        $arResult=$data->locked;
        $ARCurrent->locks[$this->path]=$data->locked;
      }
    } else {
      if ($data->locked["duration"]>time()) {
        $arResult=$data->locked;
        $ARCurrent->locks[$this->path]=$data->locked;
      }
    }
  }
?>