<?php	 
	/*
		This template is called in a single find to copy multiple objects in one go.
		It is not meant to be used on large selections of objects, since you
		could run into memory or time limit problems.

		arguments:
			$source: 	source of the tree to copy
			$target:	target root of the copied tree.

		This template should be called on the source objects, with the parents
		called before any children are called.
	*/
	if (!$source || !$this->exists($source)) {
		$this->error=sprintf($ARnls["err:wrongpath"],$source);
	} else {
		if ($target) {
			$relativeparent=substr($this->parent, strlen($source));
			$absoluteparent=$source.$relativeparent;
			if (!$this->exists($absoluteparent)) {
				$this->error=sprintf($ARnls["err:wrongpath"],$absoluteparent);
			} else {
				$relativepath=substr($this->path, strlen($source));
				$absolutepath=$source.$relativepath;
				$this->error=$this->call("system.copyto.phtml", array (
					"target" 	=> $target.$relativepath, 
					"search"	=> $source,
					"replace"	=> $target,
					"defaultnls"=> $ARConfig->nls->default));
			}
		}
	}

	if ($this->error) {
		$arResult=$this->error;
	}
?>
