<?php
  /******************************************************************
   system.get.name.phtml				   		   Muze Ariadne v2.1
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: none
   Global variables: none

   Returns the name of this object.

  ******************************************************************/
  $arResult=$nlsdata->name;
?>
