<?php
	if ($this->CheckConfig()) {
		$this->pushContext(array("scope" => "php"));
			$query = "login.value = '".AddSlashes($chpwdLogin)."' and implements = 'puser'";
			$user  = current($this->find("/system/users/", $query, "system.get.phtml", "", 0, 1));
			if (!$user) {
				$this->error = sprintf($ARnls["err:notfindusergroup"], $chpwdLogin);
			} else {
				$user->call("system.change.password.phtml", $arCallArgs);
				if ($user->error) {
					$this->error = $user->error;
				}
			}
		$this->popContext();
	}
?>
