<?php
  /******************************************************************
   system.get.value.phtml						   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: none
   Global variables: none

   Returns the path of this object.

  ******************************************************************/
  $arResult=$this->path;
?>