<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
		if (!$this->lock("T")) {
			$this->error=$ARnls["err:cannotlockobject"];
		} else {
			$target=$this->getdata("target");
			$target=$this->store->make_path($this->parent, $this->getdata("target","none"));

			$eventData = new baseObject();
			$eventData->arTarget = $target;
			$eventData = ar_events::fire( 'onbeforemove', $eventData );
			if ( !$eventData || ar_error::isError( $eventData ) ) {
				$arResult = $eventData;
			} else {
				$target = $eventData->arTarget;
			
				if ($this->exists($target)) {
					if (substr(strtolower($target), 0, strlen(strtolower($this->path)))==strtolower($this->path)) {
						if (strtolower($target) == strtolower($this->path)) {
							$parent = $this->parent;
						} else {
							$this->error=$ARnls["err:nomovebelow"];
						}
					} else {
						$parent=$target;
						$target.=substr($this->path, strlen($this->parent));
					}
				} else {
					$parent=$this->store->make_path($target, '..');
					if (!$this->exists($parent)) {
						$this->error=sprintf($ARnls["err:noparentcreatefirst"],$parent);
					} else if (substr($parent, 0, strlen($this->path))==$this->path) {
						$this->error=$ARnls["err:nomovebelow"];
					}
				}
				if (!preg_match("|^[a-z0-9_\{\}\.\:/-]+$|i",$target)) { 
					$this->error=sprintf($ARnls["err:fileillegalchars"],$target);
				}

				$this->unlock();

				if (!$this->error) {
					if (current($this->get($parent, "system.check.grant.phtml", array("grant"=>"add", "modifier"=>$this->type)))) {

						$this->find($this->path, "", "system.update.user.grants.phtml", array("action"=>"delete"));
						
						$target = $this->store->move($this->path, $eventData->arTarget);

						if ( $target ) {
							$this->path=$target;
							$this->parent=$parent;
							$arResult=$target;
							$this->find($this->path, "", "system.update.user.grants.phtml", array("config"=>$this->CheckSilent("config")));
							
							ar_events::fire( 'onmove', $eventData );
							
						} else {
							$this->error=$this->store->error;
						}
					} else {
						$this->error=$ARnls["accessdenied"];
					}
				}
			}
		}
	}
?>
