<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {
		if (!$this->lock("T")) {
			$this->error=$ARnls["err:cannotlockobject"];
		} else {
			$target=$this->getdata("target");
			$target=$this->store->make_path($this->parent, $this->getdata("target","none"));
			if ($this->exists($target)) {
				if (substr(strtolower($target), 0, strlen(strtolower($this->path)))==strtolower($this->path)) {
					if (strtolower($target) == strtolower($this->path)) {
						$parent = $this->parent;
					} else {
						$this->error=$ARnls["err:nomovebelow"];
						// FROP $this->error="You cannot move an object below itself.";
					}
				} else {
					$parent=$target;
					$target.=substr($this->path, strlen($this->parent));
				}
			} else {
				$parent=$this->store->make_path($target, '..');
				if (!$this->exists($parent)) {
					$this->error=sprintf($ARnls["err:noparentcreatefirst"],$parent);
					// FROP $this->error="$parent doesn't exists, create it first.";
				} else if (substr($parent, 0, strlen($this->path))==$this->path) {
					$this->error=$ARnls["err:nomovebelow"];
					// FROP $this->error="You cannot move an object below itself.";
				}
			}
			if (!eregi("^[a-z0-9_\{\}\.\:/-]+$",$target)) { 
				$this->error=sprintf($ARnls["err:fileillegalchars"],$target);
				// FROP $this->error="Illegal characters in filename: $target";
			}

			$this->unlock();

			if (!$this->error) {
				// FIXME: check add permission in $target
				$target = $this->store->move($this->path, $target);			
				if ($target) {
					$this->path=$target;
					$this->parent=$parent;
					$arResult=$target;
				} else {
					$this->error=$this->store->error;
				}
			}
		}
	}
?>