<?php
	if ($this->CheckLogin("config")) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=@current($this->get(".","system.get.data.phtml"));

		unset($this->data->nlsconfig);
		if (!$inherit) {
			if (!$default) {
				$default=$AR->nls->default;
			}
			if (!$available) {
				$available[]=$default;
			}
			$this->data->nlsconfig=new object;
			$this->data->nlsconfig->default=$default;
			reset($available);
			while (list($key, $lang)=each($available)) {
				$this->data->nlsconfig->list[$lang]=$AR->nls->list[$lang];
			}
		}
		$this->save();
	}
?>