<?php
/******************************************************************
  system.get.priority.phtml                             Muze Ariadne
  ------------------------------------------------------------------
  Arguments: none
  Grant needed: none
  Global variables: none

  Returns the priority of this object.

 ******************************************************************/
$arResult=$this->priority;
?>
