<?php   
	if ($this->CheckSilent("delete")) {
		if (!$this->lock("T")) {
			$this->error = ar::error( $ARnls["err:cannotlockobject"], 1105);
		} else {
			if (!$this->ls(".","system.get.phtml")) {
				$userConfig = $this->loadUserConfig();
				$authconfig = $userConfig['authentication'];

				// copy $this so we'll be able to remove grants and templates _after_ the object has been deleted.
				$clone = $this;

				// remove object itself
				if ($this->delete() && !$this->error) {
					$arResult = true;
					// remove grants for this object in all user objects.
					if ($clone->data->config->grants && is_array($clone->data->config->grants)) {
						foreach ($clone->data->config->grants as $type => $grantdata) {
							foreach ($grantdata as $login => $grants) {
								$query = "object.implements = '$type' and login.value = '$login'";
								if ($clone->store->AR_implements($type, 'pgroup')) {
									foreach ($authconfig['groupdirs'] as $groupdirpath) {
										$clone->find($groupdirpath, $query, "system.update.grants.phtml", array(
											"action" => "delete",
											"path" => $clone->path
										));
									}
								} else {
									foreach ($authconfig['userdirs'] as $userdirpath) {
										$clone->find($userdirpath, $query, "system.update.grants.phtml", array(
											"action" => "delete",
											"path" => $clone->path
										));
									}
								}
							}
						}
					}
					// clear cache

					global $cache_config;
					$cachestore=new cache($cache_config);
					$cachestore->onObjectSaved($clone->id);

					$clone->resetConfig();
				}
			} else {
				$this->error = ar::error( $ARnls["err:containsobj"], 1118);
			}
			$this->unlock();
		}
	} else {
		$this->error = ar::error( $ARnls["nopermission"], 1117);
	}
?>