<?php
	$context    = $this->getContext(ARCALLINGCONTEXT);
	if (($context["addProfileSettings"] || $this->CheckSilent("edit")) && $this->CheckConfig()) {
		$user = current($this->get($owner, "system.get.phtml"));
		if (!$user || !$user->implements('puser') || $user->implements('pgroup')) {
			$this->error = sprintf($ARnls["err:notfindusergroup"], $owner);
		} else {
			$this->data = current($this->get($this->path, "system.get.data.phtml"));
			$this->data->config->owner = $user->data->login;
			$this->data->config->owner_name = $user->data->name;
			$properties = Array();
			$properties['owner'][0]['value'] = $user->data->login;
			$this->save($properties);
		}
	}
?>
