<?php
	if (!$ARConfig->cache[$this->parent] && $this->parent!="..") {
		$this->get($this->parent, "system.get.config.phtml");
	}

	$this->call('system.get.config.data.phtml', $arCallArgs);
	/* load pinp configuration data via config.ini */
	$allnls = $ARCurrent->allnls;
	$ARCurrent->allnls = true;
	
	$ARConfig->pinpcache[$this->path] = $ARConfig->pinpcache[$this->parent];
	// backwards compatibility when calling templates from config.ini
	if (!isset($ARCurrent->arConfig)) {
		$ARCurrent->arConfig = $ARConfig->pinpcache[$this->path];
	}

	$arCallArgs['arConfig'] = $ARConfig->pinpcache[$this->path];

	/* calling config.ini directly for each system.get.config.phtml call */
	$loginSilent = $ARCurrent->arLoginSilent;
	$ARCurrent->arLoginSilent = true;
	if (!$this->CheckConfig('config.ini', $arCallArgs)) {
		$arConfig = $ARCurrent->arResult;
		if (!isset($arConfig)) {
			$arConfig = $ARCurrent->arConfig;
		}
		unset($ARCurrent->arResult);
		if (is_array($arConfig['library'])) {
			if (!$ARConfig->libraries[$this->path]) {
				$ARConfig->libraries[$this->path] = array();
			}
			foreach ($arConfig['library'] as $libName => $libPath) {
				$this->loadLibrary($libName, $libPath);
			}
			unset($arConfig['library']);
		}
		$ARConfig->pinpcache[$this->path] = (array) $arConfig;
	}
	
	$arConfig = &$ARConfig->pinpcache[$this->path];
	if (!is_array($arConfig['authentication']['userdirs'])) {
		$arConfig['authentication']['userdirs'] = array('/system/users/');
	} else {
		if (reset($arConfig['authentication']['userdirs']) != '/system/users/') {
			array_unshift($arConfig['authentication']['userdirs'], '/system/users/');
		}
	}
	if (!is_array($arConfig['authentication']['groupdirs'])) {
		$arConfig['authentication']['groupdirs'] = array('/system/groups/');
	} else {
		if (reset($arConfig['authentication']['groupdirs']) != '/system/groups/') {
			array_unshift($arConfig['authentication']['groupdirs'], '/system/groups/');
		}
	}

	$ARCurrent->arLoginSilent = $loginSilent;

	// remove pinpcache reference
	unset($ARCurrent->arConfig);
	$ARCurrent->allnls = $allnls;

?>
