<?php
  /*******************************************************************
	system.import.phtml								Muze Ariadne v2.0b
	------------------------------------------------------------------
	Arguments: none
	Grant needed: add
	Global variables: none

	Called when an object has to be imported from an export file.

	Returns true on success , false on an error.
		($this->error will be set with an error-message)
  *******************************************************************/
  if ($this->CheckLogin("add")) {
	display("system.import.new.phtml (".$this->path.")\n");

	// get object grants.
	$this->call("system.import.get.grants.phtml");
	unset($this->data->grants);			// do not save grants
	unset($this->data->usergrants);

	$this->save($this->properties, $this->vtype);

	if ($this->error) {
		$arResult=false;
	} else {
		$arResult=true;
	}

  } else {
	$arResult=false;
  }
?>