<?php
	/******************************************************************
	 system.save.cache.phtml                               Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $cache, $keepfor, $refresh
	 Grant needed: "config"
	 Global variables: none

	 This template saves the cache configuration. 
 
	 $cache is an integer between -1 and 999. If $cache==1 then $cache
	   will become $keepfor. The value of $cache is saved in 
	   $data->config->cacheconfig.
	 $keepfor is an integer between 1 and 999.
	 $refresh is the string "now" or is not set. If $refresh is set, 
	   the cache will be cleared for all objects and templates from 
	   the current object in the tree and onwards.

	 No return value.
	
	******************************************************************/

	if ($this->CheckSilent("edit") && $this->CheckConfig()) {
		$donotcache=-1;
		$inherited=0;
		$onrequest=1;
		$onchange=-2;	

		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=current($this->get(".","system.get.data.phtml"));

		$cache=$this->getdata("cacheconfig","none");
		$refresh=$this->getdata("refresh","none");
		$keepfor=$this->getdata("keepfor","none");
		if ($cache==$onrequest) {
			$cache=$keepfor;
		}
		$this->data->config->cacheconfig=$cache;
		$this->save();
		if ($refresh || $donotcache == $cache ) {
			$this->ClearCache($this->path, true, true);
		}
	} else {
		$this->error=$ARnls["accessdenied"];
	} 
?>