<?php
	debug($this->type."/system.lock.unset.phtml: $id","class");
	$arResult=0;
	if ($this->CheckSilent("edit") || $this->CheckSilent("delete")) {
		if ($this->data->locked) {
			if ($this->data->locked["id"]==$id) {
				// first make sure that the object is clean (data can only be set via 
				// the defined interface: $arCallArgs)
				$this->data=@current($this->get(".","system.get.data.phtml"));

				$arResult=$this->data->locked;
				unset($this->data->locked);
				$properties["locked"]=1;
				$this->save($properties);
			}
		} else { // object wasn't locked anyway
			$arResult=1;
		}
	}
?>