<?php
  /******************************************************************
   GetValue.phtml				   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by: multiple
   Arguments: none
   Grant needed: none
   Interface/Widget: all
   Global variables: none

   Returns the value of this object.

  ******************************************************************/
  $arResult=$nlsdata->name;
?>