<?php
  /******************************************************************
	system.export.update.phtml				Muze Ariadne v2.1
	------------------------------------------------------------------
	Arguments: $this->import (object to import)
	Grant needed: edit
	Global variables: none

	Called when an object has to be updated from an export file.

	Returns true on success , false on an error.
  ******************************************************************/
  if ($this->CheckLogin("edit")) {
	$keep_templates = $this->data->templates;
	$keep_pinp		= $this->data->pinp;

	$this->data=$newObject->data;
	$this->data->templates=$keep_templates;
	$this->data->pinp=$keep_pinp;
	$this->priority=$newObject->priority;
	$this->save();

  } else {
	$arResult=false;
	$this->error=$ARnls["nopermimportnew"];
	// FROP $this->error="No permission to import a new object";
  }
?>