<?php
	if (!isset($this->arIsNewObject)) {
		$this->arIsNewObject = null;
	}
	if (!isset($this->error)) {
		$this->error = null;
	}

	if (($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) {

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) {
			$arLanguage = $ARConfig->nls->default;
		}

		if ($this->error) {
			return array();
		}

		// for backwards compatibility we will first try to
		// register the file without nls
		$info = ldRegisterFile("file", $this->error);
		if ($this->error) {
			return array();
		}

		if (count($info)) {
			$_POST = array_merge($_POST, $info);
			if (!$_POST['mimetype'] && $info['file_type']) {
				$_POST['mimetype'] = $info['file_type'];
			}
		} else {
			// no file without nls found, try the nls specific one
			foreach ($AR->nls->list as $language => $language_name) {
				$info = ldRegisterFile($language."[file]", $this->error);
				if (!$this->error && count($info)) {
					if (!is_array($_POST[$language])) {
						$_POST[$language] = array();
					}
					$_POST[$language] = array_merge($_POST[$language], $info);
					if (!$_POST[$language]['mimetype'] && $info['file_type']) {
						$_POST[$language]['mimetype'] = $info['file_type'];
					}
					break; // only accept one file
				}
			}
		}

		$arResult = $info;
	}
?>
