<?php
	/******************************************************************
	 system.save.layout.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $type, $function, $language, $template
	 Grant needed: layout
	 Global variables: none

	 This template saves a new or changes object template.

	 $type is the type of the object to which the template is 
	   to be assigned 
	 $function is the name assigned to this template. The name may 
	   consist of the characters [a-zA-Z], [0-9], '.', '-' and '_'.
	   The name must not contain '..' and must not end with '.phtml'.
	 $language is the language associated with the template. It can be
	   any of the keys defined in $AR->nls->list[] or 'any'.
	 $template contains the PINP template to compile and save

	 no result

	******************************************************************/
	if ($this->CheckSilent("layout") && $this->CheckConfig()) {
		// check arguments, remove ".."
		$type=str_replace("..",".",$type);
		$function=str_replace("..",".",$function);
		$language=str_replace("..",".",$language);

		include_once($this->store->get_config("code")."modules/mod_pinp.phtml");
		if (!$function) {
			$this->error=$ARnls["err:notemplatename"];
		} else if (preg_match("/\.phtml$/",$function)) {
			$this->error=$ARnls["err:endswith.phtml"];
		} else if (!preg_match("/^[a-z0-9\._-]*$/i",$function)) {
			$this->error=$ARnls["err:illegalchars"];
		} else {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));

			$templates=$this->store->get_filestore("templates");
			$pinp=new pinp($AR->PINP_Functions, "local->", "\$AR_this->_");
			$compiled=$pinp->compile(strtr($template,"\r",""));
			if ($pinp->error) {
				$this->error = $pinp->error;
			} else {
				$this->data->config->pinp[$type][$function][$language]=$this->id;

				if ($private) {
					$this->data->config->privatetemplates[$type][$function] = 1;
				} else if (isset($private)) {
					if (isset($this->data->config->privatetemplates[$type][$function])) {
						unset($this->data->config->privatetemplates[$type][$function]);
						if (count($this->data->config->privatetemplates[$type])==0) {
							unset($this->data->config->privatetemplates[$type]);
						}
					}
				}


				$file=$type.".".$function.".".$language;

				// cleanup old file format
				$templates->remove($this->id, $file);

				$templates->write($template, $this->id, $file.".pinp");
				if (isset($mtime) && $mtime) {
					$templates->touch($this->id, $file.".pinp", $mtime);
				}
				$templateCode = $templates->templateCodeFunction($compiled);

				// generating optimized template code
				$optimized = sprintf($AR->PINPtemplate, $compiled);

				$templates->write($optimized, $this->id, $file.".inc");
				if (isset($mtime) && $mtime) {
					$templates->touch($this->id, $file.".inc", $mtime);
				}

				if ($default) { // add pinp template from default templates list
					$this->data->config->templates[$type][$function][$language]=$this->id;
				} else { // remove pinp template from default templates list
					if (isset($this->data->config->templates[$type][$function][$language])) {
						unset($this->data->config->templates[$type][$function][$language]);
						if (count($this->data->config->templates[$type][$function])==0) {
							unset($this->data->config->templates[$type][$function]);
							if (count($this->data->config->templates[$type])==0) {
								unset($this->data->config->templates[$type]);
							}
						}
					}
				}

				// Remove this template from 'deleted templates'.
				if ($AR->SVN->enabled) {
					if (isset($this->data->config->deleted_templates[$type][$function][$language])) {
						unset($this->data->config->deleted_templates[$type][$function][$language]);
						if (count($this->data->config->deleted_templates[$type][$function])==0) {
							unset($this->data->config->deleted_templates[$type][$function]);
							if (count($this->data->config->deleted_templates[$type])==0) {
								unset($this->data->config->deleted_templates[$type]);
							}
						}
					}
				}

				$this->save();
				$this->ClearCache($this->path, true, false);

				global $cache_config;
				$cachestore=new cache($cache_config);
				$cachestore->onTemplateSaved($this->id, $type, $file);
			}
		}
	}
?>
