<?php
  global $nocache;
  $nocache=true;
  if (!$this->error) {
    if (!$this->data || !is_object($this->data)) {
      $this->error="Fatal error: data corrupt, cannot save";
    } else {
      if ($this->newobject) { // save a new object
        if ($this->CheckSilent("add")) {
          // check for ".." in path
          $path=$this->store->make_path($this->path, "");        
          if ($path==$this->path) {
            $filename=substr($this->path, strlen($this->parent));
            if (eregi("^[a-z0-9_\/\{\}\.\:-]+$",$filename)) { // no "/" allowed, these will void the 'add' grant check.
              $parent=$this->make_path("..");
              if ($this->exists($parent)) {
                if (!$this->exists($this->path)) {
                  $this->path=$this->save($this->path, $this->type, $this->data, $this->properties, $this->vtype);
                  $this->get($this->parent, "system.cache.clear.phtml");
                } else {
                  $this->error="$this->path already exists.";
                }
              } else {
                $this->error="illegal path: parent $parent not found";
              }         
            } else {
              $this->error="$this->path is not a valid path, use only a-z, A-Z, 0-9 and _ / or -.";          
            }
          } else {
            $this->error="$this->path is not a valid path, do not use '..' in paths.";
          }
        }
      } else { // edit an existing object
        if ($this->CheckSilent("edit")) {
          if (!($result=$this->lock(0,"O")) || ($result["locks"][$this->path]["identity"]==$AR->user->data->login)) {
            $this->save($this->path, $this->type, $this->data, $this->properties, $this->vtype);
            $this->call("system.cache.clear.phtml");
  	    $this->unlock();
  	  } else {
  	    $this->error="Object already locked.";
          }
        }
      }
    }
  }
?>