<?php
  /******************************************************************
   system.get.size.phtml				   		   Muze Ariadne 
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Global variables: none

   Returns the size of this object.

  ******************************************************************/
	$ARCurrent->nolangcheck=true;
	$arResult=$this->size;

	if (isset($this->data->filesize)) {
		$arResult += $this->data->filesize;
	}

	if (is_array($this->data->nls->list)) {
		foreach ($this->data->nls->list as $key => $language) {
			if (isset($this->data->$key->filesize)) {
				$arResult += $this->data->$key->filesize;
			}
		}
	}
?>