<?php
	debug("pobject/system.update.user.grants.phtml: $this->path","class");
	
	$action=$this->getdata("action");
	if (!$action) $action="add";
	
	if ($action=="delete" || $this->getdata("config")) { // the grants need to be updated
		debug("grants need to be updated");
		$args=array("action"=>$action, "path"=>$this->path);
		$types=array("puser", "pgroup");
		$criteria=array();
		$userConfig = $this->loadUserConfig();
		$authconfig = $userConfig['authentication'];

		$realgrants = $AR->user->grants[ $this->path ] ?? null;
		$AR->user->grants[$this->path]['config']=6;
		$AR->user->grants[$this->path]['read']=6;

		foreach ($types as $type) {
			if ( $typegrants = ( $this->data->config->grants[$type] ?? null ) ) {
				foreach ($typegrants as $id=>$grants) {
					$user_ob = null;
					$criteria["login"]["value"]["="]=$id;
					if ( $type == 'puser' ) {
						foreach ($authconfig['userdirs'] as $userdirpath) {
							$user_ob = current($this->find($userdirpath, $criteria, "system.get.phtml"));
							if ($user_ob) {
								break;
							}
						}
					} else {
						foreach ($authconfig['groupdirs'] as $groupdirpath) {
							$user_ob = current($this->find($groupdirpath, $criteria, "system.get.phtml"));
							if ($user_ob) {
								break;
							}
						}
					}
					if ($user_ob) {
						$path=$user_ob->path;

						foreach ($grants as $grant=>$granttype) {
							$args["grant"]=$grant;
							if ( is_array( $value ?? null ) ) {
								foreach ($granttype as $modifier=>$value) {
									$args["modifier"]=$modifier;
									$args["granttype"]=$value;
									$this->get($path, "system.save.grants.user.phtml", $args);
								}
							} else {
								$args["modifier"]="";
								$args["granttype"]=$granttype;
								$this->get($path, "system.save.grants.user.phtml", $args);
							}
						}
					}
				}
			}
		}
		if ( $realgrants !== null ) {
			$AR->user->grants[$this->path]=$realgrants;
		}

	} else { // the grants need to be removed (no config grant on the target)
		debug("grants need to be removed (no config grant on the target)");
		unset($this->data->config->grants);
		$this->save();
	}
?>
