<?php
 if ($this->CheckConfig("read") && !$ARCurrent->options["without_files"]) {
	if (($this->newObject->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->newObject->type)) ||
			(!$this->newObject->arIsNewObject && $this->CheckLogin("edit"))) {
		 $orig_filestore=$this->store->get_filestore("files");
		 $orig_files=$orig_filestore->ls($this->id);
		 if (is_array($orig_files)) {
			$new_filestore=$this->newObject->store->get_filestore("files");

			if ($ARCurrent->options["force"]) {
				$new_filestore->purge($this->newObject->id);

			}


			while (list(,$file)=each($orig_files)) {
				display("\n");
				if ($new_filestore->exists($this->newObject->id, $file) &&
					( $new_filestore->mtime($this->newObject->id, $file) >=
						$orig_filestore->mtime($this->id, $file))) {
							display("	file($file) no update");
				} else {
					$srcStream = $orig_filestore->get_stream($this->id, $file);
					if (is_resource($srcStream) ){
						$result = $new_filestore->copy_stream_to_store($srcStream, $this->newObject->id, $file);

						fclose($srcStream);
						display("	file($file) created");
					} else {
						display("	file($file) ERROR: Could not open file");
					}
				}
			}
		 }
	}
 }
?>