<?php
	if (!$setDummyObject) {
		$this->properties=$this->load_properties();

		/* 
			versions below and equal to 1.2 do not have their config
			saved in the data->config object
		*/
		if ($ARCurrent->AXAction == "import" 
				&& ($ARCurrent->AXHeader["version"] <= 1.2)) {
			if (!$data->config) {
				$data->config = new object;
			}
			if ($data->templates) {
				$data->config->templates = $data->templates;
				unset($data->templates);
			}
			if ($data->pinp) {
				$data->config->pinp = $data->pinp;
				unset($data->pinp);
			}
			if ($data->grants) {
				$data->config->grants = $data->grants;
				unset($data->grants);
			}
			if ($data->usergrants) {
				$data->config->usergrants = $data->usergrants;
				unset($data->usergrants);
			}
			if ($data->cacheconfig) {
				$data->config->cacheconfig = $data->cacheconfig;
				unset($data->cacheconfig);
			}
			if ($data->typetree) {
				$data->config->typetree = $data->typetree;
				unset($data->typetree);
			}
			if ($data->nlsconfig) {
				$data->config->nlsconfig = $data->nlsconfig;
				unset($data->nlsconfig);
			}
			if ($data->customconfig) {
				$data->config->customconfig = $data->customconfig;
				unset($data->customconfig);
			}
		}
		if ($ARCurrent->options["without_grants"]) {
			unset($this->data->config->grants);
			unset($this->data->grants);
		} else {
			$this->call("system.export.get.grants.phtml");
		}
	} else {
		$this->axflags=AX_DUMMY;
		unset($this->data->config->grants);
		unset($this->data->grants);
	}


	$arResult=$this;
?>