<?php	 
	/*
		called by the parent of the target. e.g. 
		copy /a/b/ to /c/
			calls /c/system.copy.phtml?source=/a/b/
			results in /c/b/
		copy /a/b/ to /c
			calls /system.copy.phtml?source=/a/b/&target=/c/
			results in /c/
			if /c/ exists, fail
				calling template should first remove it
		FIXME: implement above description :)
	*/
	if (!$source || !$this->exists($source)) {
		$this->error=sprintf($ARnls["err:wrongpath"],$source);
	} else {
		if (!$target) {
			$target=end(explode("/",$source));
			if (!$target) {
				$target="{5:id}"; // can only happen if $source=="/" ?
			}
		}
		$this->error=current($this->get($source, "system.copyto.phtml", array (
					"target" 	=> $this->path.$target."/", 
					"search"	=> $search,
					"replace"	=> $replace,
					"defaultnls"=> $ARConfig->nls->default)));
	}

	if ($this->error) {
		$arResult=$this->error;
	}
?>
