<?php
  if ($this->CheckLogin("layout")) {
?>
<body bgcolor="white">
<br>
<h3><?php printf($ARnls["layouttemp"], $data->name); ?></h3>
<table border="0" width="100%" cellspacing="4" vspace="10" hspace="10">
<tr>
  <td bgcolor="#404074" colspan="2">&nbsp;
    <font face="helvetica,sans-serif" color="white"><b><?php echo $ARnls["templates"]; ?></b></font>
  </td>  
</tr><tr>
  <td colspan="2">
    <form action="EditTemplate.phtml">
    <table border="0" width="100%" cellspacing="0" bgcolor="#EEEEEE">
    <tr>
      <td>
        <font face="helvetica,sans-serif"><?php echo $ARnls["type"]; ?></font>       
      </td><td>
        <font face="helvetica,sans-serif"><?php echo $ARnls["language"]; ?></font>       
      </td><td>
        <font face="helvetica,sans-serif"><?php echo $ARnls["template"]; ?></font>       
      </td><td>&nbsp;
      </td>
    </tr><tr>
      <?php
        if (($data->pinp) && is_array($data->pinp)) {
          while (list($type, $values)=each($data->pinp)) {
            while (list($function, $templatelist)=each($values)) {
              while (list($language, $template)=each($templatelist)) {
              ?>
                <td><?php echo $type; ?>&nbsp;</td>
                <td><?php echo $language; ?>&nbsp;</td>
                <td><a href="EditTemplate.phtml?type=<?php 
                       echo $type; ?>&function=<?php 
                       echo RawUrlEncode($function); ?>&language=<?php
                       echo $language; ?>"><?php echo $function; ?></a></td>
  	      <td><a href="RemoveTemplate.phtml?type=<?php 
                       echo $type; ?>&function=<?php 
                       echo RawUrlEncode($function); ?>&language=<?php
                       echo $language; ?>" onClick="return confirm('<?php printf($ARnls["q:removetemplate"],$function, $type); ?>');"><?php echo $ARnls["delete"]; ?></a></td>
              </tr><tr>
              <?php
              }
            }
          }
        }
      ?>
      <td>&nbsp;
      </td><td>&nbsp;
      </td><td>&nbsp;
      </td><td>
        <input type="hidden" name="type" value="<?php echo $this->type; ?>">
        <input type="submit" name="action" value="<?php echo $ARnls["new"]; ?>">
      </td>
    </tr>
    </table>    
    </form>
  </td>
</tr>
</table>
</body>
<?php } ?>
