<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<div class="border">
  <span class="hoverbutton" style="float: right"><a href="#" onClick="top.hidetree(); return false;"><img src="<?php echo $AR->dir->images; ?>tree/x.gif" border="0" height="7" width="8" vspace="2"></a></span>
  <div style="padding: 4px;">
  <img src="<?php echo $AR->dir->images; ?>tree/wait.gif" style="float: left" hspace="2" height="15" width="15"> <?php echo $ARnls["loading"]; ?>
</div>
  <?php
		flush();
		if ($folder=$this->call("system.get.folder.phtml")) {
			?>
				<script language="javascript">
					window.parent.init("<?php echo AddCSlashes($folder["icon"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["name"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["path"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["pre"], ARESCAPE); ?>",
							"<?php echo AddCSlashes($folder["shortcut"], ARESCAPE); ?>");
					node=window.parent.root;
					node.status="Open";
					<?php
						// also show links below a profile user object if a profile is set
						if($profile=$this->getdata("profile","none")){
							$pquery=" OR ( object.parent = '".addslashes($profile)."' and object.path != '".addslashes($profile."static/")."' ) ";
						}
						$criteria="(object.parent = '".addslashes($this->path)."'".$pquery.") and (object.implements =  'pdir' OR object.type = 'pshortcut')";
						if ($folders=$this->find("/",$criteria,"system.get.folder.phtml",$args)) {
							while (list($key, $folder)=each($folders)) {
								?>
									node.add("<?php echo AddCSlashes($folder["icon"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["name"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["path"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["pre"], ARESCAPE); ?>",
											 "<?php echo AddCSlashes($folder["shortcut"], ARESCAPE); ?>");
								<?php
									time();
									flush();
							}
						}
					?>
					window.parent.Draw();
				</script>
			<?php
		} else {
			echo "Error initializing tree, contact system administrator.";
		}
?>
</body>
</html>
<?php	 
	} 
?>