<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>control.css">
</head>
<body>
<div class="border">
  <span class="hoverbutton" style="float: right"><a href="#" onClick="top.hidetree(); return false;"><img src="<?php echo $AR->dir->images; ?>tree/x.gif" border="0" height="18" width="18" vspace="2"></a></span>
  <img src="<?php echo $AR->dir->images; ?>tree/wait.gif" style="float: left" hspace="2" height="15" width="15"> Loading...
  <?php
		flush();
		if ($folder=$this->call("system.get.folder.phtml")) {
			?>
				<script language="javascript">
					window.parent.init("<?php echo AddSlashes($folder["icon"]); ?>",
							"<?php echo AddSlashes($folder["name"]); ?>",
							"<?php echo AddSlashes($folder["path"]); ?>",
							"<?php echo AddSlashes($folder["pre"]); ?>");
					node=window.parent.root;
					node.status="Open";
					<?php
						$criteria["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
						$criteria["object"]["implements"]["="]="'pdir'";
						if ($folders=$this->find("",$criteria,"system.get.folder.phtml",$args)) {
							while (list($key, $folder)=each($folders)) {
								?>
									node.add("<?php echo AddSlashes($folder["icon"]); ?>",
											 "<?php echo AddSlashes($folder["name"]); ?>",
											 "<?php echo AddSlashes($folder["path"]); ?>",
											 "<?php echo AddSlashes($folder["pre"]); ?>");
								<?php
									time();
									flush();
							}
						}
					?>
					window.parent.Draw();
				</script>
			<?php
		} else {
			echo "Error initializing tree, contact system administrator.";
		}
?>
</body>
</html>
<?php	 
	} 
?>