<?php
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<style>
TD {
	FONT: 13px sans-serif;
}
BODY 	{
	FONT: 13px sans-serif;
	BORDER: 0;
    CURSOR: wait;
  <?php
    global $HTTP_USER_AGENT;
    if (eregi(".*msie ([0-9]+).*",$HTTP_USER_AGENT, $regs) &&
       $regs[1] && (intval($regs[1])>=4)) { //ie4+
  ?>
	BACKGROUND-COLOR: buttonface;
  <?php
    } else {
  ?>
	BACKGROUND-COLOR: #BBBBBB;
  <?php
    }
  ?>
}
</style>
</head>
<body>
<fieldset>
<table width="100%">
<tr>
  <td valign="middle"><img src="<?php echo $AR->images; ?>tree/wait.gif" align="left" hspace="2">Loading...</td>
  <td align="right"><img align="right" src="<?php echo $AR->images; ?>tree/x.png" vspace="1"></td>
</tr>
</table>
</fieldset>
<?php
  flush();
  $folders=$this->get(".","GetFolder.phtml");
  if ($folders) {
    $folder=$folders[0];
?>
<script>
  window.parent.init("<?php echo AddSlashes($folder["icon"]); ?>",
              "<?php echo AddSlashes($folder["name"]); ?>",
              "<?php echo AddSlashes($folder["path"]); ?>",
              "<?php echo AddSlashes($folder["pre"]); ?>");
  node=window.parent.root;
  node.status="Open";
<?php
    $criteria["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
    $criteria["object"]["implements"]["="]="'pdir'";
    $folders=$this->find("",$criteria,"GetFolder.phtml",$args);
    // en nu node.add doen voor elke folder.
    if ($folders) {
      while (list($key, $folder)=each($folders)) {
        ?>
        node.add("<?php echo AddSlashes($folder["icon"]); ?>",
                 "<?php echo AddSlashes($folder["name"]); ?>",
                 "<?php echo AddSlashes($folder["path"]); ?>",
                 "<?php echo AddSlashes($folder["pre"]); ?>");
        <?php
      }
    }
?>
  window.parent.Draw();
</script>
<?php
  } else {
    echo "Error initializing tree, contact system administrator.";
  }
?>
</body>
</html>
<?php   
  } 
?>