<?php
	$ARCurrent->nolangcheck=true;
	// FIXME: add error checking and html cleanup stuff
	if ($this->CheckLogin('edit') && $this->CheckConfig($arCallFunction, $arCallArgs)) {
		if (is_array($changes)) {
//			echo "<pre>"; print_r($changes); echo "</pre>";
			while (list($path, $fields)=each($changes)) {
				$this->get($path, 'system.save.current.phtml', $fields);
			}
		}
	}
?>
<script>
  <?php
  	if ($arReturnPage) {
  ?>
  	window.opener.location.href='<?php echo $arReturnPage; ?>';
  <?php
    }
  ?>
  window.close();
</script>
