<?php
  /******************************************************************
   index.html					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Arguments: none
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This displays a suitable overview of the object.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php echo $data->$nls->name; ?></title>
<script>
  tree=1;
  function View(path) {
    document.location.href='<?php echo $this->store->root; ?>'+path+'view.phtml';
  }
  function LoadingDone() {
  }
</script>
</head>
<body scroll="no" bgcolor="white" onLoad="top.LoadingDone();">
<?php
  include($this->store->code."widgets/menu/menu.phtml");
  $this->call("manage.html");
?>
</font>
</body>
</html>
<?php
  }
?>