<?php
	require_once($this->store->get_config("code")."modules/mod_webdav.php");

	if (!$this->CheckLogin('add', 'pdir')) {
		$arResult = "401 Access Denied";
	} else {
		$this->CheckConfig();

		$collection_name = Ariadne_WebDAV_Server::path_unescape($collection);

		$newData = Array();
		foreach ($ARConfig->nls->list as $key => $val) {
			debug("collection nls: $key:$val");
			$newData[$key]["name"] = $collection_name;
		}

		$newData['arNewFilename'] = $collection;
		$newData['arNewType'] = 'pdir';
		debug("creating collection $this->path($collection)");
		$this->call('system.new.phtml', $newData);

		debug("collection error?: $this->error");
		$arResult = "201 Created";
	}
?>
