<?php
	if ($this->CheckLogin('read') && $this->CheckConfig()) {
		$arResult['type'] = 'data';
		if ($this->AR_implements('pfile')) {
			$arResult['contents'] = $this->GetFile();
		} else {
			$arResult['contents'] = $nlsdata->page;
		}
		$arResult['props']['size'] = strlen($contents);
		$arResult['props']['mtime'] = $this->data->mtime;
		$arResult['props']['ctime'] = $this->data->ctime;
		$arResult['props']['mimetype'] = 'application/data';
	}
?>
