<?php
	if ($this->CheckLogin("add") && $this->CheckConfig()) {

		$fileinfo=$this->getdata("file");

		/*	first check which object type we have to use for this
			kind of file											*/

		unset($arNewType);
		$mimetypes = $ARConfig->cache[$this->path]->mimetypes;
		@reset($mimetypes);
		while (!$arNewType && (list($regexp, $arType)=@each($mimetypes))) {
			// Find a suitable delimiter
			$delimiters = array("/", "|", "%", "#");
			$delimiter = array_pop($delimiters);
			while ($delimiter && (strpos($regexp, $delimiter) !== false)) {
				$delimiter = array_pop($delimiters);
			}

			if (preg_match($delimiter . $regexp . $delimiter . "i", $fileinfo["type"], $regs)) {
				$arNewType = $arType;
			}
		}

		if (!$arNewType) {
			// default to pfile
			$arNewType = "pfile";
		}

		debug("saving new file of type $arNewType");
		$arNewFilename=$fileinfo["name"];
		$arNewPath=$this->make_path($arNewFilename);
		$arNewData=new baseObject;

		$arNewObj=$this->store->newobject($arNewPath, $this->path, $arNewType, $arNewdata);
		$arNewObj->arIsNewObject=true;
		$result=$arNewObj->call("webdav.files.save.phtml", $arCallArgs);
	}
?>
