<?php
	require_once($this->store->get_config("code")."modules/mod_webdav.php");

	$this->call('system.rename.phtml', Array('target' => $dest));
	if ($this->error) {
		// FIXME: find a better error description check
		$arResult = "409 Conflict";
	} else {
		$filename = basename($this->path);

		$filename = Ariadne_WebDAV_Server::path_unescape($filename);

		$properties = Array( "name" => Array() );
		foreach($this->data->nls->list as $nls => $value) {
			$this->setValue("name", $filename, $nls);
			$properties["name"][]=Array(
				"value" => $filename,
				"nls"   => nls
			);
		}
		$this->save($properties);
		$arResult = "201 Created";
	}
?>