<?php 
	/******************************************************************
	 winxp.browse.nav.phtml                           Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $crit, $filter, $viewtype
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<html>
<head>
<title><?php echo $nlsdata->name; ?></title>
<style>
	* { 
		font: 11px tahoma,Helvetica,sans-serif ;
	}
	.object {
		background: transparent;
<?php
	if ($viewtype!='details') {
?>
		width: 150px;
		overflow: hidden;
<?php
	} else {
?>
		width: 100%;
		overflow: hidden;
<?php
	}
?>
		<?php
			if (($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	.dataname { 
		font: 14px; font-weight:bold;}
	.selectedItem {
		background: #316AC5;
		color: #ffffff;
		overflow: hidden;
	}
	.unselectedItem {
		background: transparent;
		color: #000000;
		overflow: hidden;
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 11px Tahoma,Helvetica,sans-serif;
	}
	A {
		text-decoration: none;
		color: black;
	}
	<?php if ($viewtype == "details") {?>
	.heading {
		font-weight:normal;
		<?php
			$browser=$this->call("browsercheck.phtml");
			if ($browser["id"]=="ns" && $browser["version"]==4)
				echo "background: #BBBBBB;";
			else
				echo "background: buttonface;";
		?>
		border: 2px outset;
		
	}
	<?php } ?>
</style>
<script language="JavaScript">
	var selectedItem;
 	var BR_NS = (document.layers) ? true : false;
		var BR_IE = (document.all) ? true : false;
	
	function selectItem(itm){
		if (itm != selectedItem){
			if (selectedItem)
				selectedItem.className= 'unselectedItem';
			itm.className = 'selectedItem';
			selectedItem = itm;
			parent.selectItem(itm, '1');
		}
	}
	
	function bodyClick(e){
		cm_hideMenus();
		if(BR_IE) e = event;
		var source=BR_IE?e.srcElement:e.target;
		if (source.tagName == "HTML" || source.tagName == "BODY"){
			if (selectedItem) {
				selectedItem.className= 'unselectedItem';
				selectedItem = null;
				var itm=new Object();
				itm.path='<?php echo $this->path; ?>';
				parent.selectItem(itm, '0');
			}
		}
	}
	
	function initBody() {
		createContextMenus();
		document.onclick = bodyClick;
	}
	
	function objectadded() {
		top.View('<?php echo $this->path; ?>');
		return "close";
	}
	
</script>
<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/menu/functions.js"
		type='text/javascript'>
</script>	
<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/contextmenu/cm.js"
		type='text/javascript'>
</script>
<script>
	function test() {
		alert('test');
	}
</script>
<script language="JavaScript1.2" 
		src="winxp.browse.contextmenu.js"
		type='text/javascript'>
</script>	
<link href="<?php echo $AR->dir->www; ?>widgets/contextmenu/cm.css" rel="StyleSheet" type="text/css">
</head>

<body bgcolor="white" onLoad="initBody();" contextmenu="bodyContextMenu" hiddenItems="normalCMexplore;">

<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr height="20">
	<td width="50%" valign="top">

<!--dataname and datasummary for this object-->

<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr height="20">
	<td><span class="dataname"><?php echo $nlsdata->name; ?></span></td>
</tr>
<tr height="2">
	<td><img src="<?php echo $AR->dir->images; ?>winxp/bluedot.gif" width="100%" height="2"></td>
</tr>
<tr>
	<td>&nbsp;</td>
</tr>
<tr>
	<td><?php
		if (strlen($nlsdata->summary)>128) {
			$shortsummary=substr($nlsdata->summary,0, 128)."...";
		} else {
			$shortsummary=$nlsdata->summary;
		} 
		echo $shortsummary; ?>
	</td>
</tr>
<tr>
	<td>&nbsp;</td>
</tr>
</table>

	</td>
	<td align="right" valign="top"><img src="<?php echo $AR->dir->images; ?>winxp/system.gif"><img src="<?php echo $AR->dir->images; ?>winxp/ariadnexplogo.gif"</td>
</tr>
<tr>
	<td colspan="2"><img src="<?php echo $AR->dir->images; ?>winxp/bluedot.gif" width="100%" height="1"></td>
</tr>
</table>
<BR>
<?php if ($viewtype == "details") {?>

<table width="100%" cellspacing="0" cellpadding="0" border="0">
<col style="width: 45%; overflow: hidden;">
<tr>
	<td align="left"><div class="heading">&nbsp;<?php echo $ARnls["name"]; ?></div></td>
	<td align="right"><div class="heading"><?php echo $ARnls["size"]; ?>&nbsp;</div></td>
	<td align="right"><div class="heading"><?php echo $ARnls["user"]; ?>&nbsp;</div></td>
	<td align="left"><div class="heading">&nbsp;<?php echo $ARnls["time"]; ?></div></td>
	<td><div class="heading">&nbsp;Lan</div></td>
</tr>
<?php } ?>
<?php
	$arCallArgs['template']="winxp.browse.nav.".$viewtype.".show.phtml";
	$this->call("browse.list.phtml", $arCallArgs);
	if ($viewtype == "details")
		echo "</table>";
?>

</body>
</html>
<?php
	}
?>