<?php
	/******************************************************************
	 view.phtml                                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: read
	 Global variables: none

	 This template displays the management view of the object, with
	 pulldown menu's etc.

	 no result.

 ******************************************************************/

	if ($this->CheckLogin("read") && $this->CheckConfig()) {
  		include_once($this->store->get_config("code")."nls/winxp.".$this->reqnls);
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title><?php echo $data->$nls->name; ?></title>

<link href="<?php echo $AR->dir->styles; ?>default.css" rel="StyleSheet" type="text/css">

<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/menu/functions.js"
        type='text/javascript'>
</script>	

<script language="javascript">
	tree=1;
	function View(path) {
		document.location.href='<?php echo $this->store->get_config("root"); ?>'+path+'view.phtml';
	}
	function LoadingDone() {
		parent.LoadingDone();
	}
	function objectadded() {
		document.location.href=document.location.href;
	}

	function arEdit(object, arguments) {
		arshow('edit_object_data','<?php echo $this->store->get_config("root"); ?>'+object+'edit.object.data.phtml', arguments);
	}
</script>
</head>
<body scroll="no" bgcolor="white" onLoad="parent.LoadingDone();">
<div id="kill-scrollbars" style="position: relative;">
<?php

	include($this->store->get_config("code")."widgets/toolbar/xptoolbar.phtml");
	$this->call("winxp.manage.html", $arCallArgs);
?>
</div>
<script>
	document.body.style.zoom='1.0'; // forces IE to redraw the screen, workaround for bug that hides most of the page content untill you resize the page
</script>
</body>
</html>
<?php
	}
?>