<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

	if (!$arLanguage) {
		$arLanguage=$nls;
	}
	if ($data->$arLanguage) {
		$nlsdata=$data->$arLanguage;
	}

	$permcheck = array();
	$permcheck[] = "edit";
	$permcheck[] = "config";
	$permcheck[] = "delete";
	$permcheck[] = "layout";
	
	$disabledItems="";
	if(!$this->implements("pshortcut") || !$this->CheckSilent("edit"))
		$disabledItems.= "normalCMshortcut;";
	if(!$this->CheckSilent("edit"))
		$disabledItems.= "normalCMedit;";
	if(!$this->CheckSilent("delete"))
		$disabledItems.= "normalCMdelete;normalCMrename;";
	if(!$this->CheckSilent("read"))
		$disabledItems.= "normalCMexplore;normalCMviewweb;normalCMcopy;normalCMlink;";

	$server_name=eregi_replace("^[htps:/]*/","",$AR->host);
	if ($HTTP_SERVER_VARS["HTTP_HOST"]!=$server_name) {
		$fullObjectpath = $this->store->root.$this->path;
	} else {
		$fullObjectpath = $this->make_url();
	}
	if (strpos($this->type, '.')!==false) {
		$icon=$this->call('system.get.icon.small.phtml');	
	} else {
		$icon=$AR->dir->images."icons/".$this->type.".gif";
	}

	if ($AR->SVN->enabled) {
		$filestore = $this->store->get_filestore_svn("templates");
		$svnstack = &PEAR_ErrorStack::singleton('VersionControl_SVN');
		$svn = $filestore->connect($this->id);

		$svn_info = $svn['info'];
		ob_start();
		$svn_status = $filestore->svn_status($svn);
		ob_end_clean();

		if ($svn_status) {
			foreach ($svn_status as $key => $value) {
				if (substr($key, -5) == ".pinp") {
				} else {
					unset($svn_status[$key]);
				}
			} 
			if (sizeof($svn_status)) {
				$svnicon = $AR->dir->images.'svn/ModifiedIcon.png';
			} else {
				$svnicon = $AR->dir->images.'svn/InSubVersionIcon.png';
			}
		} else if ($svn_info) {
			$svnicon = $AR->dir->images.'svn/InSubVersionIcon.png';
		}
	}

?>
<div class='object'><nobr>
<a contextmenu="normalContextMenu" disableditems="<?php echo $disabledItems; ?>" title="<?php echo $nlsdata->name; ?>"
href="#" class="unselectedItem" onClick="selectItem(this); return false;" onDblClick="top.View(this.getAttribute('path'))" path="<?php echo $this->path; ?>" fullPath="<?php echo $fullObjectpath; ?>">
<img width="20" height="20" src="<?php echo $icon; ?>"	alt="<?php echo $this->path; ?>" border="0">

<?php
	if ($svnicon) {
?>
		<img width="16" height="16" src="<?php echo $svnicon; ?>"  alt="<?php 
			foreach ($svn_status as $key => $value) {
				echo "$value  $key\n";
			}?>" border="0">  
<?php
	}
?>
&nbsp;<?php	 
		if (!$details && strlen($nlsdata->name)>32) {
			$name=substr($nlsdata->name,0, 32)."...";
		} else {
			$name=$nlsdata->name;
		}
		if (!$this->CheckSilent("read")) {
			echo "<font color=\"#CCCCCC\">$name</font>";
		} else {
			echo "$name";
		}
	?>&nbsp;</a></nobr></div>
