<?php 
	/******************************************************************
	 winxp.browse.nav.list.phtml                       	   Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter, $crit
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
if ($this->CheckLogin("read") && $this->CheckConfig()) {

	$arCallArgs["viewtype"] = "list";
	
	$this->call("winxp.browse.nav.phtml", $arCallArgs);
}
?>
