<?php 
	/******************************************************************
	 winxp.browse.nav.phtml                           Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $crit, $filter, $viewtype
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<html>
<head>
<title><?php echo $nlsdata->name; ?></title>
<style>
	.object {
		background: transparent;
		width: 150px;
		overflow: hidden;
		<?php
			if (($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	.selectedItem {
		background: #316AC5;
		color: #ffffff;
		overflow: hidden;
	}
	.unselectedItem {
		background: transparent;
		color: #000000;
		overflow: hidden;
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
	}
	A {
		text-decoration: none;
		color: black;
	}
	<?php if ($viewtype == "details") {?>
	.heading {
		font: 10pt Arial,Helvetica,sans-serif;
		<?php
			$browser=$this->call("browsercheck.phtml");
			if ($browser["id"]=="ns" && $browser["version"]==4)
				echo "background: #BBBBBB;";
			else
				echo "background: buttonface;";
		?>
		border: 2px outset;
		text-align: center;
	}
	<?php } ?>
</style>
<script language="JavaScript">
	var selectedItem;
 	var BR_NS = (document.layers) ? true : false;
  	var BR_IE = (document.all) ? true : false;
	
	function selectItem(itm){
		if (itm != selectedItem){
			if (selectedItem)
				selectedItem.className= 'unselectedItem';
			itm.className = 'selectedItem';
			selectedItem = itm;
			parent.selectItem(itm, '1');
		}
	}
	
	function bodyClick(e){
		cm_hideMenus();
		if(BR_IE) e = event;
		var source=BR_IE?e.srcElement:e.target;
		if (source.tagName == "HTML" || source.tagName == "BODY"){
			if (selectedItem) {
				selectedItem.className= 'unselectedItem';
				selectedItem = null;
				var itm=new Object();
				itm.path='<?php echo $this->path; ?>';
				parent.selectItem(itm, '0');
			}
		}
	}
	
	function initBody() {
		createContextMenus();
		document.onclick = bodyClick;
	}
	
	function objectadded() {
		top.View('<?php echo $this->path; ?>');
		return "close";
	}
	
</script>
<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/menu/functions.js"
        type='text/javascript'>
</script>	
<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/contextmenu/cm.js"
        type='text/javascript'>
</script>
<script>
	function test() {
		alert('test');
	}
</script>
<script language="JavaScript1.2" 
		src="winxp.browse.contextmenu.js"
        type='text/javascript'>
</script>	
<link href="<?php echo $AR->dir->www; ?>widgets/contextmenu/cm.css" rel="StyleSheet" type="text/css">
</head>
<body bgcolor="white" onLoad="initBody();" contextmenu="bodyContextMenu" hiddenItems="normalCMexplore;">
<?php if ($viewtype == "details") {?>
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
  <td><div class="heading"><?php echo $ARnls["name"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["size"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["user"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["time"]; ?></div></td>
  <td><div class="heading">&nbsp;</div></td>
</tr>
<?php } ?>
<?php
	if ($filter) {
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	if ($letter && ($letter=substr(eregi_replace("[^a-z]","",$letter),0,1))) {
		$crit["name"]["value"]["LIKE"]="'$letter%'";
	}
	
	$limit=100;
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	
	$this->find(".",$crit, "winxp.browse.nav.".$viewtype.".show.phtml", "", $limit, $offset);	

	if ($viewtype == "details")
		echo "</table>";
?>

</body>
</html>
<?php
	}
?>