<?php 
	/******************************************************************
	 browse.nav.list.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<style>
	.object {
		width: 150px;
		overflow: hidden;
		<?php
			if (($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
	}
	A {
		text-decoration: none;
		color: black;
	}
</style>
<body bgcolor="white">
<img src="<?php echo $this->make_url(); ?>" alt="<?php echo $nlsdata->name; ?>" vspace="2" hspace="2">
<?php
	$this->call('browse.list.phtml',Array('template' => 'browse.nav.list.show.phtml'));
?>
</body>
<?php
	}
?>