<?php
	/******************************************************************
	 browse.nav.list.show.phtml                            Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: none
	 Global variables: none

	 This template displays the icon and name of an object. If the 
	 user doesn't have read access to the object, the name is displayed
	 in grey.
	 
	 no result

	******************************************************************/

	if ($this->CheckConfig()) {
?>
<SPAN class=item>
	<A TITLE="<?php echo $nlsdata->name; ?>" HREF="javascript:top.View('<?php echo $this->path; ?>');"><IMG 
		SRC="<?php echo $this->make_url(); ?>view.thumb.html" border=0 HSPACE=0 VSPACE=0 WIDTH="40" HEIGHT="40" ALT="<?php echo $nlsdata->name; ?>"><br>
	<?php 
		if (!$this->CheckSilent("read")) {
			echo "<font color=\"#CCCCCC\">$nlsdata->name</font>";
		} else {
			echo "$nlsdata->name";
		}
	?></A>
</SPAN>
<?php
	}
?>