<?php
  if ($this->CheckLogin("read") && $this->CheckConfig($arCallFunction, $arCallArgs)) {
?>
<html>
<head>
<title><?php echo $nlsdata->name; ?></title>
<style>
BODY,TD {
    FONT: 10pt sans-serif;
}
A {
    COLOR: #404074;
    FONT: 10pt sans-serif;
    text-decoration: none;
}
A:hover {
    COLOR: #404074;
    FONT: 10pt sans-serif;
    FONT-WEIGHT: bold;
    text-decoration: none;

}
</style>
<script>
    windowproperties='directories=no,location=no,menubar=no,status=no,toolbar=no,resizable=yes,height=300,width=500'
    function editobject() {
      newwindow=window.open('edit.object.data.phtml',
                             'newwindow', windowproperties);
      newwindow.focus();	
      return false;
    }

    function objectadded() {
      document.location.href=document.location.href;
    }
</script>
</head>
<body bgcolor="white">
<table border="0" cellpadding="0" cellspacing="0" height="100%">
<tr><td><img src="dot.gif" width="100" height="1"></td></tr>
<tr valign="top">
<td>

<form method=GET name="search" action="view.html">
<table border="0">
<tr>
	<td align="left">
	<img width="40" height="40" src="<?php echo $this->store->root.$this->path; ?>view.thumb.html">
	<br><b><?php echo $nlsdata->name; ?></b>
	</td>
</tr>
<tr>
	<td align="left">
	<p>
	<nobr>
	<?php echo "Mimetype : ".$this->data->mimetype; ?><br>
	<?php echo $ARnls["owner"].": ".$this->data->author; ?><br>
	<?php 
		echo $ARnls["size"].": "; 
		if ($data->filesize>=1024) {
			echo round($data->filesize/1024)." KB";
		} else {
			echo $data->filesize." B";
		}
	?><br>
	<?php echo $ARnls["date"].": ";	?>
    <nobr><?php
        $start=mktime(0,0,0,date("m",time()),date("d",time()), date("Y",time()));
        if ( ($this->lastchanged > $start  ) &&
             ($this->lastchanged < ($start+(3600*24)) )) {
            echo date("H:i",$this->lastchanged);
        } else {
            echo date("d-m-Y",$this->lastchanged);
        }
    ?></nobr>
	<p>
	<?php echo $nlsdata->summary; ?>
	</td>
</tr>
<tr>
    <td align="center" bgcolor="#EEEEEE" style="width: 100px">
        <input type="button" style="width: 80px;" value="<?php echo $ARnls["edit"]; ?>" name="edit" onClick="editobject();">
<?php
    $wgRecurseConfirm=$ARnls["q:removephoto"];
    $wgRecurseAction="delete";
    $wgRecurseTitle=$ARnls["delete"];
    $wgRecurseStyle="width: 80px;";
    include($this->store->code."widgets/recurse/form.js");
    include($this->store->code."widgets/recurse/form.html");
?>
    </td>
</tr>
</table>
</form>

</td>

<td align="left" width="1" units="pixels" bgcolor="#000000"><img width="1" height="1" src="<?php echo $AR->dir->images; ?>dot.gif" border="0" vspace="0" hspace="0"><p></td>

<td align="left" width="100%">

	<?php
		if ($this->data->mimetype=="image/jpeg" 
			|| $this->data->mimetype=="image/gif" 
			|| $this->data->mimetype=="image/pjpeg" 
			|| $this->data->mimetype=="image/png" ) {
	?>
    <iframe hspace="5" vspace="5" width="100%" height="50%" src="show.html.phtml"> 
    </iframe>
	<?php
		}
	?>
	<table border="0" width="100%">
	<tr valign="top">
	<?php
		if (!$ncols) $ncols=4;
		$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";

		if (!$srch_keywords && !$src_imgtype) {
			$this->ls(".","info.html","ncols=$ncols");
		} else {
			if ($srch_imgtype) {
				$crit["mimetype"]["subtype"]["="]="'".AddSlashes($srch_imgtype)."'";
			}
			if ($srch_keywords) {
				$crit["text"]["value"]["LIKE"]="'%".AddSlashes($srch_keywords)."%'";
			}
			$this->find(".",$crit,"info.html","ncols=$ncols");
		}
		for ($i=1; $i<=$ncols; $i++) {
			echo "<td>&nbsp;</td>";
		}
	?>
	</tr>
	</table>
</td>

</tr>
</table>
</body>
<?php
 }
?>