<?php 
	/******************************************************************
	 browse.nav.icons.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the icons list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
	?>
<html>
<head>
<link type="text/css" rel="stylesheet" href="<?php echo $AR->dir->www; ?>styles/browse.icons.css">
<script>
	function init() {
		if (top.document.forms[0] && top.document.forms[0].imgstyle) {
			var style=top.document.forms[0].imgstyle;
			image.src=image.src+style.options[style.selectedIndex].value;
		}
	}
</script>
<body bgcolor="white" onLoad="init();">
<img id="image" src="<?php echo $this->make_url(); ?>" alt="<?php echo $nlsdata->name; ?>" vspace="4" hspace="4">
<?php
	$query="object.parent='".AddSlashes($this->path)."'";
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	if ($filter) {
		$query.=" and object.implements='".AddSlashes($filter)."'";
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$query.=" and name.value ~= '%".AddSlashes($name)."%'";
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$query.=" and name.value ~= '".AddSlashes($letter)."%'";
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	$query.=" and ( name.nls='".$nls."' or name.nls='' or name.nls='none' ) order by name.value";
	if (!$limit) {
		$limit=100;
	}
	$total=$this->store->count($this->store->find("", $query, 0));
	$this->find(".",$query, "browse.nav.icons.show.phtml", "", $limit, $offset);
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));
?>
</body>
<?php
	}
?>