<?php 
	/******************************************************************
	 browse.nav.details.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none

	 This templates displays the detailed list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<style>
	BODY, TD {
		font: 10pt Arial,Helvetica,sans-serif;
		line-height: 15pt;
	}
	BODY {
		margin: 0px;
		padding: 0px;
	}
	TD {
		margin: 1px;
	}
	A {
		text-decoration: none;
		color: black;
	}
	.heading {
		font: 10pt Arial,Helvetica,sans-serif;
		background: buttonface;
		border: 1px solid buttonhighlight;
		border-bottom-color: buttonshadow;
		border-right-color: buttonshadow;
		text-align: center;
	}

</style>
<body bgcolor="white">
<img id="image" src="<?php echo $this->make_url(); ?>view.thumb.html" alt="<?php echo $nlsdata->name; ?>" vspace="4" hspace="4">
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
  <td><div class="heading"><?php echo $ARnls["name"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["size"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["user"]; ?></div></td>
  <td><div class="heading"><?php echo $ARnls["time"]; ?></div></td>
  <td><div class="heading">&nbsp;</div></td>
</tr>
<?php
	$this->call('browse.list.phtml',Array('template' => 'browse.nav.list.details.phtml'));
?>
</table>
</body>
<?php
	}
?>