<?php
	/******************************************************************
	 classic.save.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: see system.save.data.phtml, $arReturnPage
	 Grant needed: add or edit
	 Global variables: none

	 This is a wrapper around system.save.data.phtml for the classic
	 interface.	 

	 no result.
 
	******************************************************************/

	$this->call("system.save.data.phtml",$arCallArgs);
	if (!$this->error) {
		if (!$arReturnPage) {
			$arReturnPage=$this->store->root.$this->parent; 
		}
		ldRedirect($arReturnPage);
	} else {
		$this->call("show.error.phtml");
	}
?>