<?php
	/******************************************************************
	 classic.form.phtml															Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Called by 'classic.edit.phtml' and 'classic.new.phtml'
	 Arguments: arNewType, arNewFilename
	 Grant needed: read
	 Interface/Widget: all
	 Global variables: none

	 This template displays the input form for this object. If $newtype
	 is set, the form is called to create a new object. This means that
	 $data points to the data of the object creating it!
	 $newtype, $newfilename and $newparent are saved in hidden input
	 fields for further processing by whatever template is called when
	 the form is processed.
	 The html form tag in a form template should always leave the action
	 property out.

	 This template must be available in every pobject derivative's
	 template directory.

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php 
	$title=$ARnls["edit"]." ".@current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<?php
		if ($this->call("lock.init.phtml")) {
?>
</head>
<body bgcolor="white" onUnLoad="releaseLock()">
<form ENCTYPE="multipart/form-data" method="post">
<input type="hidden" name="MAX_FILE_SIZE" value="10000000">
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">
<table border="0" cellspacing="0">
<tr>
	<td colspan="2" bgcolor="#404074">
		<?php
			$wgNLSpretext="<font face=\"helvetica, sans-serif\" color=\"white\"><b>".
				$ARnls["editphoto"].":</b></font><br>";
			include($this->store->code."widgets/nls/form.phtml"); 
		?>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="text" name="<?php echo $selectednls; ?>[name]" size="16" maxlength="50" value="<?php $this->showdata("name",$selectednls); ?>">
		&nbsp;<font face="helvetica, sans-serif"><b>Mimetype&nbsp;:</b></font>
		<input type="text" name="mimetype" size="16" maxlength="50" value="<?php $this->showdata("mimetype","none"); ?>">
	</td>
</tr><tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif"><?php echo $ARnls["summary"]; ?>&nbsp;:</font>
	</td><td>
		<textarea cols=50 rows=3 wrap=soft name="<?php echo $selectednls; ?>[summary]"><?php 
			echo ereg_replace('&','&amp;',$this->getdata("summary",$selectednls)); 
		?></textarea>
	</td>
</tr><tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif"><?php echo $ARnls["keywords"]; ?>&nbsp;:</font>
	</td><td>
		<textarea cols=50 rows=3 wrap=soft name="<?php echo $selectednls; ?>[keywords]"><?php 
			echo $this->getdata("keywords",$selectednls); 
		?></textarea>
	</td>
</tr><tr>
	<td align="right" valign="top">
		<font face="helvetica, sans-serif"><?php echo $ARnls["file"]; ?>&nbsp;:</font>
	</td><td>
		<input type="file" name="file">
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><?php echo $ARnls["page"]; ?>&nbsp;:</font>
	</td>
	<td width="100%">
	<?php 
		if (!$newtype) {
			$wgHTMLEditName="page";
			$wgHTMLEditLanguage=$selectednls;
			$wgHTMLEditPath=$this->parent;
			$wgHTMLEditFile=substr($this->path, strlen($this->parent), -1);
			$wgHTMLEditContent=$this->getdata("page",$selectednls);
			include($this->store->code."widgets/htmledit/js.html"); 
			include($this->store->code."widgets/htmledit/form.html"); 
		} else {
			echo "available after object is created";
		}
	?>
	</td>
</tr>

<tr><td><br></td></tr>

<tr bgcolor="#404074">
	<td align="left" colspan="2">
	<font face="arial,helvetica" color="white"><?php echo $ARnls["createthumb"]; ?></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><?php echo $ARnls["width"]; ?>&nbsp;:</b></font>
	</td>
	<td>
		<input type="text" name="newthumbwidth" size="3" maxlength="3" value="<?php 
				$this->showdata("thumbwidth","none"); 
		?>">

		&nbsp;<font face="helvetica, sans-serif"><?php echo $ARnls["height"]; ?>&nbsp;:</b></font>
		<input type="text" name="newthumbheight" size="3" maxlength="3" value="<?php 
				$this->showdata("thumbheight","none"); 
		?>">

		&nbsp;<font face="helvetica, sans-serif"><?php echo $ARnls["color"]; ?>&nbsp;:</b></font>
		<input type="text" name="newthumbcolor" size="6" maxlength="6" value="<?php 
				$this->showdata("thumbcolor","none"); 
		?>">
	</td>
</tr><tr bgcolor="#404074">
	<td align="left" colspan="2">
	<font face="arial,helvetica" color="white"><?php echo $ARnls["oruploadthumb"]; ?></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><?php echo $ARnls["file"]; ?>&nbsp;:</b></font>
	</td>
	<td align="left">
		<input type="file" name="thumbfile">
	</td>
</tr>
</table>
<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removephoto"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->code."widgets/recurse/form.js");
				include($this->store->code."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
<?php
	$this->call("lock.form.phtml");
?>
</form>
</body>
</html>
<?php
		}
	}
?>