	<table border="0">
	<tr>
		<td>
			<span class="required"><?php echo $ARnls["file"]; ?></span>
		</td>
	</tr><tr>
		<td valign="top">
			<input type="file" name="file" onMouseDown="preview(true);">
		</td>
	</tr><tr>
		<td align="center">
			<div ID="busy"  STYLE="position: absolute; left: 100px; top: 100px; width: 200px; height: 50px; background: buttonface; border:2px outset; padding: 10px; margin-top: 20px; text-align: left; visibility:hidden;">
				<img src="<?PHP echo $AR->dir->images; ?>tree/wait.gif" align="left">Uploading...
			</div>
			<div style="width: 250px; height: 160px; padding: 0px; overflow: auto;">
				<img name="thumb" src="<?PHP  echo $AR->dir->images; ?>dot.gif" style="margin: 0px; border: 0px;" height="150">
			</div>
			<script>
				var oldValue=document.wgWizForm.file.value;
				function preview(first) {
					if (first) {
						oldValue=document.wgWizForm.file.value;
					}
					var newValue=document.wgWizForm.file.value;
					if (newValue==oldValue) {
						setTimeout(preview, 500, false);
					} else {
						document.images["thumb"].src = 'file://'+newValue;
						oldValue=newValue;
					}
				}
				function busy() {
					if (document.all) {
						var busy=document.all['busy'];
					} else if (document.getElementById) {
						var busy=document.getElementById('busy');
					}
					if (busy) {				
						busy.style.visibility='visible';
					}
				}
			</script>
		</td>
	</tr>
	</table>
	<script>
		function forminit() { 
			document.wgWizForm.file.focus();
		}
		window.onload=forminit;
		document.wgWizForm.onsubmit=busy;
	</script>
