<?php
  if ($newtype) {
    $newdata=new object;
    $newdata->author=$AR->user->name;
    $newdata->authorpath=$AR->user->path;
    $newdata->created=time();
  } else { 
    $newdata=$data;
  }
  $newdata->mimetype=$mimetype;

  if (!isset(${$ARConfig->nls->default}) && !isset($newdata->{$ARConfig->nls->default})) { // default language for this path
    $error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
  } else {
    if (!$newdata->nls) {
      $newdata->nls=new object;
    }
    $newdata->nls->default=$ARConfig->nls->default;
    reset($AR->nls->list);
    while (list($key, $value)=each($AR->nls->list)) {
      if (isset(${$key})) {
        $nlsformdata=$$key;
        if (!isset($newdata->$key)) {
          $newnlsdata=new object;
        } else {
          $newnlsdata=$newdata->$key;
        }
        if (!$nlsformdata["name"]) {
          $error=sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]);
        }
        $newnlsdata->name=$nlsformdata["name"];
        $properties["name"][]["value"]="'".AddSlashes($nlsformdata["name"])."'";
		$properties["text"][]["value"]="'".AddSlashes($nlsformdata["name"])."'";
        $newnlsdata->summary=$nlsformdata["summary"];
        $properties["text"][]["value"]="'".AddSlashes($nlsformdata["summary"])."'";
		$newnlsdata->keywords=$nlsformdata["keywords"];
		$properties["text"][]["value"]="'".AddSlashes($nlsformdata["keywords"])."'";
        $newdata->$key=$newnlsdata;
        $newdata->nls->list[$key]=$value;
      }
    }

    
    include ($this->store->code."includes/save.phtml");
    if (!$error) {
      unset($properties);

      if (!$error) {
      global $HTTP_POST_FILES;
        if ($HTTP_POST_FILES['file'] && is_uploaded_file($HTTP_POST_FILES['file']['tmp_name'])) {
          if ($newtype) {
            $this->MkDir("files".$newfilename);
          }
          $path=$this->store->files."files".$newfilename.'/view=';
          $newdata->size=$HTTP_POST_FILES['file']['size'];
          if (!$newdata->mimetype) {
            $newdata->mimetype=$HTTP_POST_FILES['file']['type'];
          }
          if (!$error) {
            if (!move_uploaded_file($HTTP_POST_FILES['file']['tmp_name'],$path)) {
              $error="Couldn't move file to $path";
            }
          }
        }
      }
    }
  }

  if (!$error) {
    $temp=explode("/",$newdata->mimetype);
    $newdata->mime["type"]=$temp[0];
    $newdata->mime["subtype"]=$temp[1];

    $imgfile=$this->store->files."files".$newfilename."view=";
    $newdata->thumbwidth=$thumbwidth=$newthumbwidth;
    $newdata->thumbheight=$thumbheight=$newthumbheight;
    $newdata->thumbcolor=$thumbcolor=$newthumbcolor;
    $thumbfile=$this->store->files."files".$newfilename."view.thumb=";	

    include($this->store->code."includes/create.thumb.phtml");
  }

  // realy
  if ($newtype) {
   $this->path=$newfilename;
   unset($newtype);
  }
    $properties["mimetype"][0]["type"]="'".AddSlashes($newdata->mime["type"])."'";
    $properties["mimetype"][0]["subtype"]="'".AddSlashes($newdata->mime["subtype"])."'";
    include($this->store->code."includes/save.object.phtml");
?>