<?php
	if (($this->arIsNewObject && $this->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit")) &&
			$this->CheckConfig()) {

		$f_store=$this->store->get_filestore("files");

		$imgfile=tempnam($this->store->files."temp/", "img");
		if (file_exists($imgfile)) {
			@unlink($imgfile);
		}
		$f_store->copy_from_store($imgfile, $this->id, "file");

		$thumbfile=tempnam($this->store->file."temp/", "thumb");
		if (file_exists($thumbfile)) {
			@unlink($thumbfile);
		}


		$thumbheight=$this->getdata("thumbheight", "none");
		$thumbwidth=$this->getdata("thumbwidth", "none");
		$thumbcolor=$this->getdata("thumbcolor", "none");

		if (!file_exists($imgfile) ) {
			$error="err:imgnotfound";
		} else {
			$imgdata = GetImageSize($imgfile, $info);
			switch ($imgdata[2]) {
			case 1:
				system("gif2png $imgfile",$retvar);
				if ($retvar) {
					debug("err:gif2png","class");
				} else {
					if (function_exists("imagecreatefrompng")) {
						if (! ($im = imagecreatefrompng($imgfile.".png"))) {
							debug("err:imgtypenotsupported","class");
						} else {
							@unlink($imgfile.".png");
						}
					}
				}
				break;
			case 2:
				if (function_exists("imagecreatefromjpeg")) {
					if (! ($im = imagecreatefromjpeg($imgfile))) {
						$error="err:imgtypenotsupported";
					}
				}
				break;
			case 3:
				if (function_exists("imagecreatefrompng")) {
					if (! ($im = imagecreatefrompng($imgfile))) {
						$error="err:imgtypenotsupported";
					}
				}
				break;

			default:
				debug("err:imgtypenotsupported","class");
				break;

			}

			if (!$error && $im) {
				$w=ImageSX($im);
				$h=ImageSY($im);
				$nw=$thumbwidth;
				$nh=$thumbheight;
				if ( ($w>=$nw && $h>=$nh) || ($nw>=$w && $nh>=$h) ) {
					$stretchw=$nw/$w;
					$stretchh=$nh/$h;
					$stretch=($stretchh < $stretchw) ? $stretchh : $stretchw; 
				} else if ($w>$nw && $h<$nh) {
					$stretch=$nw/$w;
				} else if ($w<$nw && $h>$nh) {
					$stretch=$nh/$h;
				}

				$sw=$w*$stretch; $sh=$h*$stretch;
				
				$ni=ImageCreate($nw,$nh);

				// convert hexcolor to RGB
				// valid chars are '0'-'9' && 'A'-'F'
				if ($thumbcolor) {
					$thumbcolor=substr(eregi_replace("[^0-9A-F]","0",$thumbcolor),0,6);
					eval("\$col=(0x$thumbcolor);");
					$red=$col >> 16;
					$green=($col & 0x00FF00) >> 8;
					$blue=($col & 0x0000FF);
				}
				$ic=ImageColorAllocate($ni,$red,$blue,$green);
				ImageFill($ni,0,0,$ic);
				ImageCopyResized($ni,$im,(($nw/2)-($sw/2)),(($nh/2)-($sh/2)),0,0,$w*$stretch,$h*$stretch,$w,$h); 
				if ($thumbfile) {
					if (!ImagePNG($ni,$thumbfile)) {
						$this->error="err:cannotsavethumbnail";
					} else {
						$f_store->copy_to_store($thumbfile, $this->id, "file.thumb");
						@unlink($thumbfile);
					}
				}
		  	}

			@unlink($imgfile);
		}
	}
?>