<?php 
	/******************************************************************
	 browse.nav.list.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none


	 This templates displays the short list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$browser=$this->call("browsercheck.phtml");
?>
<style>
	.object {
		width: 150px;
		overflow: hidden;
		<?php
			if (($browser["version"]!=4)) {
		?>
				float: left;
		<?php
			}
		?>
	}
	BODY {
		margin: 0px;
		padding: 2px;
		font: 10pt Arial,Helvetica,sans-serif;
	}
	A {
		text-decoration: none;
		color: black;
	}
</style>
<body bgcolor="white">
<?php
	$query="object.parent='".AddSlashes($this->path)."'";
	$crit["object"]["parent"]["="]="'".AddSlashes($this->path)."'";
	if ($filter) {
		$query.=" and object.implements='".AddSlashes($filter)."'";
		$crit["object"]["implements"]["="]="'".AddSlashes($filter)."'";
	}
	if ($name) {
		$query.=" and name.value ~= '%".AddSlashes($name)."%'";
		$crit["name"]["value"]["like"]="'%".AddSlashes($name)."%'";
	} else if ($letter) {
		$query.=" and name.value ~= '".AddSlashes($letter)."%'";
		$crit["name"]["value"]["like"]="'".AddSlashes($letter)."%'";
	}
	if ($date) {
		$date=ereg_replace("[^0-9]*","",$date);
		$crit["article"]["start"]["<="]=$date+86400;
		$crit["article"]["end"][">="]=$date;
		$query.=" and timeframe.start <= ".($date+86400)." and timeframe.end >= ".$date;
	}
	$query.=" and ( name.nls='".$nls."' or name.nls='' ) order by name.value";
	if (!$limit) {
		$limit=100;
	}
	$total=$this->store->count($this->store->find("", $query, 0));
	$this->find(".",$query, "browse.nav.list.show.phtml", "", $limit, $offset);
	$this->call("browse.update.toolbar.phtml", Array("total" => $total, "offset" => $offset, "limit" => $limit));

?>
</body>
<?php
	}
?>