<?php 
	/******************************************************************
	 browse.nav.details.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $filter
	 Grant needed: read
	 Global variables: none

	 This templates displays the detailed list of files in the browse
	 files view. 
	 
	 $filter must be a valid argument for the object.implements search
	 criteria.
	 
	 no result

	******************************************************************/
if ($this->CheckLogin("read") && $this->CheckConfig()) {

	if ($date) {
		$date=ereg_replace("[^0-9]*","",$date);
		$crit["article"]["start"]["<="]=$date+86400;
		$crit["article"]["end"][">="]=$date;
	}

	$arCallArgs["crit"] = $crit;
	$arCallArgs["viewtype"] = "details";
	
	$this->call("winxp.browse.nav.phtml", $arCallArgs);
}
?>
