<?php
  /******************************************************************
   classic.form.phtml                              Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'classic.edit.phtml' and 'classic.new.phtml'
   Arguments: arNewType, arNewFilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<?php

	if($this->call("lock.init.phtml")) {
		$this->parents($this->path, "show.link.phtml","target=classic.edit.phtml");
?>
<title><?php 
	$title=$ARnls["edit"]." ".@current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">

<body bgcolor="white">
<form method="post">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<table border="0" cellspacing="0" width="100%"> 
<tr>
  <td bgcolor="#404074">
    <?php
      $wgNLSpretext="<font face=\"helvetica, sans-serif\" size=\"+1\" color=\"white\"><b>".
        $ARnls["editphotobook"].":</b></font><br>";
      include($this->store->code."widgets/nls/form.phtml");
    ?>
  </td>
</tr>
</table>
<table border="0">
<tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?> :</b></font>
  </td><td>
    <input type="text" name="<?php echo $selectednls."[name]"; ?>" maxlength="50" 
      value="<?php $this->showdata("name",$selectednls); ?>">
  </td><td align="right">
    <?php 
	if (!$arNewType) {
		$wgBrowsePath=$this->getdata("picture","none");
	} else {
		$wgBrowsePath=$this->parent;
	}
	$wgBrowseName="picture";
	include($this->store->code."widgets/browse/js.html");
	include($this->store->code."widgets/browse/form.html");
    ?>
  </td>
</tr><tr>
  <td align="right" valign="top">
    <font face="helvetica, sans-serif"><?php echo $ARnls["summary"]; ?>&nbsp;:</font>
  </td>
  <td colspan="2">
    <textarea name="<?php echo $selectednls."[summary]"; ?>" cols="50" rows="4" wrap="soft"><?php 
        echo ereg_replace("&","&amp;",$this->getdata("summary",$selectednls)); 
    ?></textarea>
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><?php echo $ARnls["page"]; ?>&nbsp;:</font>
  </td>
  <td colspan="2">
  <?php 
    if (!$arNewType) {
      $wgHTMLEditName="page";
      $wgHTMLEditLanguage=$selectednls;
      $wgHTMLEditContent=$this->getdata("page",$selectednls);
      include($this->store->code."widgets/htmledit/js.html"); 
      include($this->store->code."widgets/htmledit/form.html"); 
    } else {
      echo "available when object is created";
    }
  ?>
  </td>
</tr>
</table>
<p>
<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
  <td>
    <?php if ($arNewType) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
<?php
    $wgRecurseConfirm=$ARnls["q:removephotobook"];
    $wgRecurseAction="delete";
    $wgRecurseTitle=$ARnls["delete"];
    include($this->store->code."widgets/recurse/form.js");
    include($this->store->code."widgets/recurse/form.html");
?>
    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>

<?php
	$this->call("lock.form.phtml");
?>
</form>
</body>
<?php
	}
  }
?>