<?php
  // template not found, try ancestor
  // FIXME: gijs: moet dit niet pdir zijn? hij mag dan pphoto implementen,
  //        het lijkt erop dat die foto dan wel ergens anders vandaan komt.
  $arCallTemplate=$this->store->code."templates/pdir/".$arCallFunction;
  if (file_exists($arCallTemplate)) {
    include($arCallTemplate);
  } else {
    include($this->store->code."templates/pdir/default.phtml");
  }
?>