<?php
  /******************************************************************
   edit.object.data.phtml			   Muze Ariadne v2.0b
   ------------------------------------------------------------------

   No result.

  ******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$customoffset=0;
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					$customoffset=1;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$summary="edit.object.data.form.phtml";
		$conversion="edit.object.data.thumb.phtml";
		$language="edit.object.language.phtml";
		$save="edit.object.data.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["data"];
		$wgWizFlow[$i]["template"]=$summary;
		$wgWizFlow[$i]["save"]=$i+2+$saveoffset+$customoffset;
		$wgWizFlow[$i]["next"]=$i+1;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["thumbnail"];
		$wgWizFlow[$i]["template"]=$conversion;
		$wgWizFlow[$i]["prev"]=$i-1;
		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			if ($hascustomdata) {
				$wgWizFlow[$i]["next"]=$i-3;
			} else {
				$wgWizFlow[$i]["next"]=$i-2;
			}
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			$wgWizFlow[$i]["save"]=$i+1;
		}
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$save;
		$wgWizFlow[$i]["back"]=$i-1;
		
		global $HTTP_POST_VARS;

		$arLanguage=$this->getdata("arLanguage","none");
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($languageselect && $wgWizFlow[0]["current"]==3) { // =edit.object.language.phtml
			if ($arControl=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}
		$HTTP_POST_VARS["arLanguage"]=$arLanguage;
		$name=current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml"));
		$wgWizTitle=$ARnls["edit"]." ".$name;		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>