<?php
  /******************************************************************
   edit.object.data.phtml			   Muze Ariadne v2.1
   ------------------------------------------------------------------

   No result.

  ******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		include($this->store->get_config("code")."widgets/wizard/code.php");

		$wgWizFlow=Array(
			Array(
				"current"	=> $this->getdata("wgWizCurrent","none"),
				"cancel"	=> "edit.object.cancel.phtml",
				"save"		=> "edit.object.data.save.phtml"
				),
			Array(
				"title"		=> $ARnls["data"],
				"image"		=> $AR->dir->images."wizard/data.png",
				"template"	=> "edit.object.data.form.phtml"
				),
			Array(
				"title"		=> $ARnls["thumbnail"],
				"image"		=> $AR->dir->images."wizard/data.png",
				"template"	=> "edit.object.data.thumb.phtml",
				"nolang"	=> true
				)
		);

		if ($hascustomdata) {
			$wgWizFlow[]=Array(
				"title"		=> $ARnls["customdata"],
				"image"		=> $AR->dir->images."wizard/customdata.png",
				"template"	=> "edit.object.data.custom.phtml");
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = "edit.object.lock.phtml";
		}

		$wgWizFlow = $this->call("user.wizard.edit.html", Array("wgWizFlow" => $wgWizFlow));

		if (!$ARCurrent->arTypeIconsSmall[$this->type]) {
			// FIXME: for performance the check above is necessary, but
			// it does make it possible to get the wrong icon...
			// get typetree to get the correct icon
			$this->call('typetree.ini');
		}
		$icon=$ARCurrent->arTypeIcons[$this->type]['default'];
		if (!$icon) {
			$dotPos=strpos($this->type, '.');
			if (false!==$dotPos) {
				$realtype=substr($this->type, 0, $dotPos);
				$icon=$ARCurrent->arTypeIcons[$realtype]['default'];
			} else { 
				$realtype=$this->type;
			}
			if (!$icon) {
				$icon=$AR->dir->images."icons/".$realtype.".gif";
			}
			$name=$ARCurrent->arTypeNames[$this->type];
		} else {
			$name=$ARCurrent->arTypeNames[$this->type];
		}
		$arResult=$icon;

		$wgWizTitle=$ARnls["edit"]." ".$name;
		$wgWizHeader=$wgWizTitle.'<img src="'.$icon.'" alt="" hspace="4" align="absmiddle">';
		include($this->store->get_config("code")."widgets/wizard/new.html");
	}
?>