<?php
  /******************************************************************
   edit.object.data.phtml			   Muze Ariadne v2.1
   ------------------------------------------------------------------

   No result.

  ******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
		}
		include($this->store->code."widgets/wizard/code.php");

		$wgWizFlow=Array(
			Array(
				"current"	=> $this->getdata("wgWizCurrent","none"),
				"cancel"	=> "edit.object.cancel.phtml",
				"save"		=> "edit.object.data.save.phtml"),
			Array(
				"title"		=> $ARnls["data"],
				"image"		=> $AR->dir->images."wizard/data.png",
				"template"	=> "edit.object.data.form.phtml"),
			Array(
				"title"		=> $ARnls["thumbnail"],
				"image"		=> $AR->dir->images."wizard/data.png",
				"template"	=> "edit.object.data.thumb.phtml")
		);

		if ($hascustomdata) {
			$wgWizFlow[]=Array(
				"title"		=> $ARnls["customdata"],
				"image"		=> $AR->dir->images."wizard/customdata.png",
				"template"	=> "edit.object.data.custom.phtml");
		}
		
		if ($languages) { // more than one language available			
			$wgWizFlow[]=Array(
				"title"		=> $ARnls["language"],
				"image"		=> $AR->dir->images."wizard/languages.png",
				"template"	=> "edit.object.language.phtml");
		}
		
		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = "edit.object.lock.phtml";
		}

		$name=current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml"));
		$wgWizTitle=$ARnls["edit"]." ".$name;		
		include($this->store->code."widgets/wizard/new.html");
	}
?>