<?php
  /******************************************************************

  ******************************************************************/
  if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
  <td>
    <fieldset id="filters">
    <legend><?php echo $ARnls["thumbnail"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          <?php echo $ARnls["thumbwidth"]; ?>
        </td><td>
          <?php echo $ARnls["thumbheight"]; ?>   
        </td>
      </tr><tr>
        <td>
          <input type="text" size="4" maxlength="3" name="thumbwidth" value="<?php 
            $this->showdata("thumbwidth","none"); 
          ?>">
        </td><td>
          <input type="text" size="4" maxlength="3" name="thumbheight" value="<?php 
            $this->showdata("thumbheight","none"); 
          ?>">
        </td>
      </tr><tr>
        <td colspan="2">
          <?php echo $ARnls["thumbcolor"]; ?>
        </td>
      </tr><tr>
        <td colspan="2">
          # <input type="text" size="15" name="thumbcolor" value="<?php
            $this->showdata("thumbcolor","none");
          ?>">
        </td>
      </tr>
      </table>
    </fieldset>
  </td>
</tr>
</table>
<script>
  window.onload=init;
  function init() {
    document.wgWizForm["thumbwidth"].focus();
  }
</script>
<?php
  }
?>