<?php
  /******************************************************************
   object.new.phtml				   Muze Ariadne v2.0b
   ------------------------------------------------------------------

   No result.

  ******************************************************************/
	global $HTTP_POST_VARS, $HTTP_POST_FILES;

	$filename="object.new.filename.phtml";
	$summary="edit.object.data.form.phtml";
	$conversion="edit.object.data.thumb.phtml";
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";


 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");

	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["template"]=$filename;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 

	if (count($ARConfig->nls->list)>1) {
		$languageselect=true;
	} else {
		$languageselect=false;
	}

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["template"]=$summary;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 
    if (!$languageselect) {
		$arFlow[$i]["save"]=$i+2;
	} else {
 		$arFlow[$i]["save"]=$i+3;
	}

	$i++;
	$arFlow[$i]["title"]=$ARnls["thumbnail"];
	$arFlow[$i]["template"]=$conversion;
	$arFlow[$i]["prev"]=$i-1;

	if (!$languageselect) {
		$arFlow[$i]["save"]=$i+1;
	} else {
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2; 
		$i++;
		$arFlow[$i]["title"]=$ARnls["language"];
		$arFlow[$i]["template"]=$language;
		$arFlow[$i]["next"]=$i-2;
		$arFlow[$i]["prev"]=$i-2;
		$arFlow[$i]["save"]=$i+1;
	}

	$i++;
	$arFlow[$i]["title"]=$ARnls["save"];
	$arFlow[$i]["template"]=$finish;
	$arFlow[$i]["back"]=$i-1;
	$arFlow[$i]["save"]=$i;



	if ($arFlow[0]["current"]==4) { // =edit.object.language.phtml
		$arControl=$this->getdata("wgWizControl","none");
		if ($arControl==$ARnls["prev"]) { // if previous selected, ignore the language select list.
			$arLanguage=$this->getdata("arPrevLanguage","none");
			$ARCurrent->arLanguage=$arLanguage;
		}
	}
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	$arResult=$arFlow;
?>