<?php
  /******************************************************************
   object.new.phtml				   Muze Ariadne v2.0b
   ------------------------------------------------------------------

   No result.

  ******************************************************************/
	global $HTTP_POST_VARS, $HTTP_POST_FILES;

	$configcache=$ARConfig->cache[$this->parent];
	$customoffset=0;
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$customdata=true;
				$customoffset=1;
				break;
			}
		}
	}
	if (count($ARConfig->nls->list)>1) { // more than one language available
		$languages=true;
		$saveoffset=1;
	} else {
		$saveoffset=0;
	}
	
	$custom="edit.object.data.custom.phtml";

	$filename="object.new.filename.phtml";
	$summary="edit.object.data.form.phtml";
	$conversion="edit.object.data.thumb.phtml";
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");

	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["template"]=$filename;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["template"]=$summary;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 
	$arFlow[$i]["save"]=$i+2+$saveoffset+$customoffset;

	$i++;
	$arFlow[$i]["title"]=$ARnls["thumbnail"];
	$arFlow[$i]["template"]=$conversion;
	$arFlow[$i]["prev"]=$i-1;

	if ($customdata) {
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2+$saveoffset;
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["template"]=$custom;
		$arFlow[$i]["prev"]=$i-1;
	}
	if ($languages) { // more than one language available
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2;
		$i++;
		$arFlow[$i]["title"]=$ARnls["language"];
		$arFlow[$i]["template"]=$language;
		if ($customdata) {
			$arFlow[$i]["next"]=$i-3;
		} else {
			$arFlow[$i]["next"]=$i-2;
		}
		$arFlow[$i]["prev"]=$i-1;
		$arFlow[$i]["save"]=$i+1;
	} else {
		$arFlow[$i]["save"]=$i+1;
	}

	$i++;
	$arFlow[$i]["title"]=$ARnls["save"];
	$arFlow[$i]["template"]=$finish;
	$arFlow[$i]["back"]=$i-1;
	$arFlow[$i]["save"]=$i;



	if ($arFlow[0]["current"]==4) { // =edit.object.language.phtml
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($arControl=="prev") { // if previous selected, ignore the language select list.
			$arLanguage=$this->getdata("arPrevLanguage","none");
			$ARCurrent->arLanguage=$arLanguage;
		}
	}
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	$arResult=$arFlow;
?>