<?php
  /******************************************************************
   object.new.phtml				   Muze Ariadne v2.1
   ------------------------------------------------------------------

   No result.

  ******************************************************************/
	global $HTTP_POST_VARS;

	$configcache=$ARConfig->cache[$this->parent];
	$customoffset=0;
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				$customoffset=1;
				break;
			}
		}
	}
//	if (count($ARConfig->nls->list)>1) { // more than one language available
//		$languages=true;
//	}
	
	$custom="edit.object.data.custom.phtml";

	$filename="object.new.filename.phtml";
	$summary="edit.object.data.form.phtml";
	$conversion="edit.object.data.thumb.phtml";
	$language="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$finish;

	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$filename;

	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$summary;

	$i++;
	$arFlow[$i]["title"]=$ARnls["thumbnail"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$conversion;

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}

	if ($languages) { // more than one language available
		$i++;
		$arFlow[$i]["title"]=$ARnls["language"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/languages.png";
		$arFlow[$i]["template"]=$language;
	}

	$arLanguage=$this->getdata("arLanguage","none");
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}

	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		

	$arResult=$arFlow;
?>