<?php
	/******************************************************************
	 system.get.config.phtml							 Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Arguments: see pdir::system.get.config.phtml
	 Grant needed: none
	 Global variables: none

	 This template calls its superclass template first, and then adds
	 the url defined in psite to the configcache->root.

	 This allows make_url() to generate correct user specified url's.

	 No result.	

	******************************************************************/

	debug($this->type."/system.get.config.phtml ".$this->path,"class");
	$this->call("pdir::system.get.config.phtml",$arCallArgs);
	$configcache=$ARConfig->cache[$this->path];
	if ($data->thumbwidth || $data->thumbheight) {
		$configcache->thumb["width"]=$data->thumbwidth;
		$configcache->thumb["height"]=$data->thumbheight;
	} else {
		debugon();
		debug("no thumb width or height at ".$this->path);
		debugoff();
	}
	if ($data->thumbcolor) {
		$configcache->thumb["color"]=$data->thumbcolor;
	}
	$ARConfig->cache[$this->path]=$configcache;
?>