<?php
	/******************************************************************
	 system.save.data.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
 
	******************************************************************/

	require_once($this->store->get_config('code')."modules/mod_page.php");

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
			$this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$scaffold = ar::getvar('scaffold');
			if ($scaffold && ar::exists($scaffold)) {
				$this->data = current(ar::get($scaffold)->call('system.get.data.phtml'));
			}
			if (!isset($this->data) || ar_error::isError($this->data)) {
				$this->data = new baseObject;
			}
		}

		$this->error = null;

		// unset the properties array, so no properties can be passed to this template.
		$properties = array();

		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error = ar::error( sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]), 1101);
		} else {
			if ($ContentEditOptionsPath) {
				$arEditorSettings=$ARCurrent->editorSettings[$ContentEditOptionsPath];
				if (!$arEditorSettings) {
					$arEditorSettings=current($this->get($ContentEditOptionsPath, "editor.ini"));
					$ARCurrent->editorSettings[$ContentEditOptionsPath]=$arEditorSettings;
				}
			} else {
				$arEditorSettings=$ARCurrent->editorSettings[$this->path];
				if (!$arEditorSettings) {
					$arEditorSettings=$this->call("editor.ini");
					$ARCurrent->editorSettings[$this->path]=$arEditorSettings;
					if (sizeof($ARCurrent->editorSettings) > 10) {
						array_shift($ARCurrent->editorSettings);
					}
				}
			}
			if (!$this->data->nls) {
				$this->data->nls=new baseObject;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			$this->data->scaffold = $this->getdata('scaffold','none');
			reset($AR->nls->list);
			$count=0;
			while (list($key, $value)=each($AR->nls->list)) {

				if ($name=$this->getdata("name",$key)) { // $name is the variable that must be set for a language to be available.
					if (!$this->data->$key) {
						debug("$key not yet set","all");
						$newnlsdata=new baseObject;
					} else {
						debug("$key was set","all");
						$newnlsdata=$this->data->$key;
					}
					debug("name found: $name","all");
					$newnlsdata->name=$name;
					$properties["name"][$count]["value"]=$newnlsdata->name;
					$properties["name"][$count]["nls"]=$key;
					$properties["text"][$count]["value"]=$newnlsdata->name;
					$properties["text"][$count]["nls"]=$key;
					$count++;
					$newnlsdata->summary=page::compile($this->getdata("summary",$key), $key);
					if ($arEditorSettings) {
						if ($arEditorSettings["htmlcleaner"]["enabled"]) {
							include_once($this->store->get_config("code")."modules/mod_htmlcleaner.php");
							$config = $arEditorSettings["htmlcleaner"];
							$newnlsdata->summary = htmlcleaner::cleanup($newnlsdata->summary, $config);
						}
						if ($arEditorSettings["htmltidy"]["enabled"]) {
							include_once($this->store->get_config("code")."modules/mod_tidy.php");
							$config=$arEditorSettings["htmltidy"];
							$config["temp"]=$this->store->get_config("files")."temp/";
							$config["path"]=$AR->Tidy->path;
							$tidy=new ARtidy($config);
							$result=$tidy->clean($newnlsdata->summary);
							$newnlsdata->summary=$result["html"];
						}
						if ($arEditorSettings["allow_tags_summary"]) {
							$newnlsdata->summary=strip_tags($newnlsdata->summary, $arEditorSettings["allow_tags_summary"]);
						}
					}
					$properties["text"][$count]["value"]=$newnlsdata->summary;
					$properties["text"][$count]["nls"]=$key;
					$count++;
					if ($this->store->is_supported("fulltext")) {
						$properties["fulltext"][$count]["value"]=$this->store->format_for_fti(
								$newnlsdata->name." ".
								$this->html_to_text($newnlsdata->summary)
								);
						$properties["fulltext"][$count]["nls"]=$key;
					}
					$this->data->{$key}=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				} else { // clear language values for $key->name if set, keep the rest, just in case.
					if ($this->data->$key) {
						unset($this->data->$key->name);
						unset($this->data->nls->list[$key]);
					}
				}
			}
		}
		$picture=$this->getdata("picture","none");
		if (!$picture || !$this->exists($picture)) {
			$picture='/system/photo/nothumb/';
		} else {
			$object=$this->get($picture,"system.get.phtml");
			if ($object && $object[0]) {
				$object=$object[0];
				if (!$object->AR_implements('pphoto')) {
					$picture='/system/photo/nothumb/';
				}
			}	
		}
		$this->data->picture=$picture;
		$this->data->thumbwidth=$this->getdata("thumbwidth","none");
		$this->data->thumbheight=$this->getdata("thumbheight","none");
		$this->data->thumbcolor=$this->getdata("thumbcolor","none");
		$arIsNewObject = $this->arIsNewObject;
		$arResult = $this->save($properties);
		if ( !$this->error ) {
			if ( $arIsNewObject && $this->data->scaffold ) {
				$this->call('system.copy.scaffold.php',array('scaffold' => $this->data->scaffold));
			}
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				if ($page=$this->getdata("page",$key)) {
					$this->call("system.save.page.phtml",array("ContentLanguage" => $key, "page" => $page));
				}
			}
		}
		global $cache_config;
		$cachestore=new cache($cache_config);
		$cachestore->onObjectSaved($this->id);
	}
?>