<?php
  /******************************************************************
   delete.phtml					   Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by: edit.phtml
   Arguments: none
   Grant needed: delete
   Interface/Widget: all
   Global variables: none

   This template deletes the current object.

  ******************************************************************/

  include($this->store->code."includes/delete.dir.phtml");
?>