<?php
	/******************************************************************
	 edit.object.data.save.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------

	 no result.
 
	******************************************************************/
	$arIsNewObject=$this->arIsNewObject;
	$this->call("system.save.data.phtml",$arCallArgs);
	if ($this->error) {
		?>
			<font color="red" face="arial,helvetica,sans-serif" size=+1><?php echo $this->error; ?></font><p>
		<?php
	} else {
		$folder=$this->call("system.get.folder.phtml");
		?>
			<script> 
				<?php 
					if ($arIsNewObject) { 
						echo "	window.opener.top.tree.AddLinks('{$this->parent}','{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
					} else {
						echo "	window.opener.top.tree.UpdateLinks('{$folder["icon"]}','".AddCSlashes($folder["name"], ARESCAPE)."','{$folder["path"]}','".AddCSlashes($folder["pre"], ARESCAPE)."');\n";
					}
				?>
				if (window.opener.objectadded) {
					window.opener.objectadded('<?php echo $this->type; ?>','<?php echo AddCSlashes($nlsdata->name, ARESCAPE); ?>','<?php echo $this->path; ?>'); 
				}
				<?php
					if (!$arIsNewObject) {
				?>
							window.close();
				<?php
					} else {
				?>
							window.location.href='object.new.select.phtml';
				<?php
					}
				?>
			</script>
		<?php
	}
?>