<?php
	if (($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) {

		reset($ARConfig->nls->list);
		while (list($key, $val)=each($ARConfig->nls->list)) {
			$arCallArgs[$key]["name"]=$this->getdata("arNewFilename");
		}

		$this->call("system.save.data.phtml", $arCallArgs);
		if ($this->error) {
			$ARCurrent->ftp_error=$this->error;
		}
	}
?>
