<?php
	if ($this->CheckLogin("delete") && $this->CheckConfig()) {

		echo $ARnls["deleting"]." ($current/$total)<br>".$this->path; 
		$this->call("system.delete.phtml");
		$rootpath=$this->getvar('rootpath');
		if ($rootpath && $rootpath==$this->path) {
			$this->unlock();
		}
		if ($this->error) {
			$rootpath=$this->getvar('rootpath');
			if ($rootpath) {
				if ($this->store->mod_lock) {
					$this->store->mod_lock->unlock($AR->user->data->login, $rootpath);
				}
			}
			// FIXME: pass error to parent window for the confirm.
		}
	}
?>