<?php 
  /* this widget displays a language select bar with flags 
     representing each available language, and the currently selected
     language. */

  global $HTTP_POST_VARS, $HTTP_GET_VARS;

  $this->nlson=true; // set nls mode on for getdata

  // first find the selected language (if any)
  $config=$ARConfig->cache[$this->path];
  reset($config->nls->list);
  while (list($arnls, $arlanguage)=each($config->nls->list)) {
    if ($HTTP_POST_VARS[$arlanguage."_x"] ||
        $HTTP_GET_VARS[$arlanguage."_x"]) {
      $selectednls=$arnls;
      break;
    }
  }
  if (!$selectednls) {
    if ($setnls) { // hidden option when other submit buttons are pressed
      $selectednls=$setnls;
    } else {
      $selectednls=$config->nls->default;
    }
  }
  $this->nls=$selectednls;
  $nls=$selectednls;
  $selectedlanguage=$config->nls->list[$selectednls];
  // enter this information in the form
  echo "<input type=\"hidden\" name=\"setnls\" value=\"$selectednls\">\n";
  // now 'remember' all language specific information and display the flags
  reset($config->nls->list);
  while (list($arnls, $arlanguage)=each($config->nls->list)) {
    // now list all non-selected-language variables
    if (isset($$arnls)) {
      // assume no data is actually filled in -> faded flag (unless this is the currently selected language!)
      if ($arnls!=$selectednls) {
        $image=$AR->dir->images.'nls/faded/'.$arnls.'.gif';
      } else {
        $image=$AR->dir->images.'nls/'.$arnls.'.gif';
      }
      while (list($key, $value)=each($$arnls)) {
        if ($arnls!=$selectednls) {
          echo "<input type=\"hidden\" name=\"".$arnls."[$key]\" value=\"".ereg_replace('"','&quot;',$value)."\">\n";
          // data entered, so our assumption proved wrong. -> full flag
          $image=$AR->dir->images.'nls/'.$arnls.'.gif';
        }
      }
    } else {
      if ($arnls!=$selectednls && ($this->newtype || !isset($this->data->$arnls)) ) {
        $image=$AR->dir->images.'nls/faded/'.$arnls.'.gif';
      } else {
        $image=$AR->dir->images.'nls/'.$arnls.'.gif';
      }
    }
    if ($arnls==$selectednls) {
      echo "<a href=\"#\" onClick=\"return false;\"><img alt=\"<<".htmlentities($arlanguage).">>\" align=\"right\" border=\"2\" src=\"$image\"></a>\n";
    } else {
      echo "<input type=\"image\" name=\"".htmlentities($arlanguage)."\" align=\"right\" border=\"0\" src=\"$image\">\n";
    }
  }
?>
<img src="<?php echo $AR->dir->images; ?>dot.gif" align="right" width="1" height="28" alt="">
<?php echo $wgNLSpretext; ?><font face="helvetica, sans-serif" color="white"><b><?php echo $ARnls["language"]; ?> :</b>
<?php echo $selectedlanguage; ?></font><?php echo $wgNLSposttext; ?>
