<html>
<body bgcolor="white">
<h3><?php printf($ARnls["languagenotavailable"],$AR->nls->list[$this->reqnls]); ?></h3>
<table border="0" bgcolor="#404074" cellpadding="0" cellspacing="0">
<tr>
  <td colspan="3">
    <img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="4" height="16">
    <font face="arial, helvetica, sans-serif" size="2" color="white"><b>
      <?php echo $ARnls["selectlanguage"]; ?>
    </b></font>
  </td>
</tr>
<tr>
  <td><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
  <td bgcolor="white">
    <table border="0" cellspacing="2" cellpadding="2" width="100%">
    <tr>
<?php 
  if (!$ARConfig->nls) {
    $ARConfig->nls=$AR->nls;
  }
  reset($ARConfig->nls->list);
  while (list($arnls, $arlanguage)=each($ARConfig->nls->list)) {
    // now list all non-selected-language variables
    $arlanguage=htmlentities($arlanguage);
    $image=$AR->dir->images.'nls/'.$arnls.'.gif';
    if (isset($this->data->$arnls)) {
      ldSetNls($arnls);
      echo "<td align=\"center\"><font face=\"arial, helvetica, sans-serif\"><a href=\"".$this->store->root.$this->path."\"><img alt=\"$arlanguage\" src=\"$image\"><br>$arlanguage</a></font></td>\n";
    }
  }
?>
    </tr>
    </table>
  </td>
  <td><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
</tr><tr>
  <td colspan="3"><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"></td>
</tr>
</table>  
</body>
</html>