<?php

  include_once($this->store->get_config("code")."nls/menu.".$this->reqnls);

	$disabled_open = "<font color='#959595'>";
	$disabled_close = "</font>";
$permcheck = array();
$permcheck[] = "edit";
$permcheck[] = "config";
$permcheck[] = "delete";
$permcheck[] = "layout";

foreach ($permcheck as $curgrant){
		if($this->CheckSilent($curgrant)) {
			${$curgrant} = array();
			${$curgrant}[0]=1; ${$curgrant}[1]=''; ${$curgrant}[2]='';
		} else {
			${$curgrant} = array();
			${$curgrant}[0]=false; ${$curgrant}[1]=$disabled_open;  ${$curgrant}[2]=$disabled_close;
		}
}
if ($this->CheckSilent("add",ARANYTYPE)) {
	$add[0]=1; $add[1]=''; $add[2]='';
} else {
	$add[0]=false; $add[1]=$disabled_open; $add[2]=$disabled_close;
}
if($this->implements("pshortcut") && $this->CheckSilent("edit")) {
	$shortcut[0]=true;$shortcut[1]='';$shortcut[2]='';
}else {
	$shortcut[0]=false;$shortcut[1]=$disabled_open;$shortcut[2]=$disabled_close;
}

?>
<script>

HM_Array1 = [
[150,                          // menu width
2, // left_position
27,
],
["<?php echo $add[1].$ARnls["m_new"].$add[2]; ?>","javascript:arshow('edit_object_data','object.new.select.phtml')",1,0,0],
["<?php echo $delete[1].$ARnls["m_rename"].$delete[2]; ?>","javascript:arshow('object_fs','object.rename.phtml')",1,0,0],
["<?php echo $ARnls["m_copy"]; ?>","javascript:arshow('object_fs','object.copy.phtml')",1,0,0],
["<?php echo $ARnls["m_link"]; ?>","javascript:arshow('object_fs','object.link.phtml')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
["<?php echo $add[1].$ARnls["m_import"].$add[2]; ?>","javascript:arshow('edit_object_data','object.import.phtml')",1,0,0],
["<?php echo $ARnls["m_export"]; ?>","javascript:arshow('edit_object_data','object.export.phtml')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
["<?php echo $delete[1].$ARnls["m_delete"].$delete[2]; ?>","javascript:arshow('object_fs','object.delete.phtml')",1,0,0],
["<?php echo $ARnls["m_logoff"]; ?>","javascript:arshow('object_fs','object.logoff.phtml')",1,0,0]
]

HM_Array2 = [
[150,
60,
27,
],
["<?php echo $ARnls["m_object"]; ?>","",1,0,1],
["<?php echo $ARnls["m_layout"]; ?>","",1,0,2],
["<?php echo $ARnls["m_config"]; ?>","",1,0,3],
["<?php echo $ARnls["m_priority"]; ?>","javascript:arshow('edit_priority','edit.priority.phtml')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
["<?php echo $ARnls["m_find"]; ?>","javascript:arshow('edit_find','edit.find.phtml')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
["<?php echo $ARnls["m_preferences"]; ?>","javascript:arshow('edit_preferences','<?php echo $this->store->root.$AR->user->path; ; ?>edit.preferences.phtml')",1,0,0]
]

HM_Array3 = [
[150,
108,
27,
],
["<?php echo $ARnls["m_web"]; ?>","javascript:arshow('_new','<?php 
	$arLanguage=$this->getdata("arLanguage","none");
	if ($arLanguage!=$this->reqnls) {
		$oldnls=$this->reqnls;
		$this->setnls($arLanguage);
	}
	echo $this->make_url();
	if ($oldnls) {
		$this->setnls($oldnls);
	} 
?>')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
["<?php echo $ARnls["m_page"]; ?>","javascript:setView('page')",1,0,0],
["<?php echo $ARnls["m_small"]; ?>","javascript:setView('list')",1,0,0],
["<?php echo $ARnls["m_large"]; ?>","javascript:setView('icons')",1,0,0],
["<?php echo $ARnls["m_details"]; ?>","javascript:setView('details')",1,0,0],
['<hr>','<img src="<?php echo $AR->dir->images; ?>hr.gif" width="100%" height="2" alt="" style="padding: 4px 2px 4px -20px;">',0,0,0],
['<div id="explorerbar_icon" class="selectedOption">a</div><?php echo $ARnls["m_explorerbar"]; ?>',"javascript:artoggleexplorerbar()",1,0,0]
]


HM_Array4 = [
[150,                          // menu width
163, // left_position
27,
],

["<?php echo $ARnls["m_index"]; ?>","javascript:arshow('help','<?php echo $this->make_url('/system/ariadne/help/reference/'); ?>')",1,0,0],
["<?php echo $ARnls["m_tutorials"]; ?>","javascript:arshow('help','<?php echo $this->make_url('/system/ariadne/help/tutorials/'); ?>')",1,0,0],
["<?php echo $ARnls["m_about"]; ?>","javascript:arshow('help_about','help.about.phtml')",1,0,0]
]

HM_Array2_1 = [
[150],
["<?php echo $edit[1].$ARnls["m_data"].$edit[2]; ?>","javascript:arshow('edit_object_data','edit.object.data.phtml')",1,0,0],
["<?php echo $shortcut[1].$ARnls["m_shortcut"].$shortcut[2]; ?>","<?php echo $shortcut[0]?"javascript:arshow('edit_object_data','edit.object.shortcut.phtml')":''; ?>",1,0,0],
["<?php echo $edit[1].$ARnls["m_cache"].$edit[2]; ?>","javascript:arshow('edit_object_cache','edit.object.cache.phtml')",1,0,0]
]

HM_Array2_2 = [
[150],
["<?php echo $layout[1].$ARnls["m_templates"].$layout[2]; ?>","javascript:arshow('edit_object_layout','edit.object.layout.phtml')",1,0,0],
["<?php echo $layout[1].$ARnls["m_custom"].$layout[2]; ?>","javascript:arshow('edit_object_custom','edit.object.custom.phtml')",1,0,0],
["<?php echo $layout[1].$ARnls["m_language"].$layout[2]; ?>","javascript:arshow('edit_object_nls','edit.object.nls.phtml')",1,0,0]
]

HM_Array2_3 = [
[150],
["<?php echo $config[1].$ARnls["m_grants"].$config[2]; ?>","javascript:arshow('edit_object_grants','edit.object.grants.phtml')",1,0,0],
["<?php echo $config[1].$ARnls["m_types"].$config[2]; ?>","javascript:arshow('edit_object_types','edit.object.types.phtml')",1,0,0],
["<?php echo $config[1].$ARnls["m_owner"].$config[2]; ?>","javascript:arshow('edit_object_owner','edit.config.owner.phtml')",1,0,0]

]
</script>