<?php
	include($this->store->get_config("code")."widgets/menu/menuarray.phtml");

	$bgcolor="buttonface";
	$browser=$this->call("pobject::browsercheck.phtml");
	if ($browser["id"]=="ns" && $browser["version"]=="4") {
		$browser_string = "NS4";
		$bgcolor="#bfbfbf";
	} else if ($browser["id"]="msie" && $browser["version"]=="4") {
		$browser_string = "IE4";
	} else {
		$browser_string = "DOM";
	}
?>
<LINK REL=stylesheet HREF="<?php echo $AR->dir->www; ?>styles/menu.css" TYPE="text/css">
<script>
  if (document.all) {
	document.body.style.border='1px inset buttonhighlight';
  }
</script>
<script language="JavaScript1.2"
        src="<?php echo $AR->dir->www; ?>widgets/menu/config.php?arDirWWW=<?php echo rawurlencode($AR->dir->www); ?>"
        type='text/javascript'>
</script>
<script language="JavaScript1.2" 
		src="<?php echo $AR->dir->www; ?>widgets/menu/HM_Script<?php echo $browser_string; ?>.js" 
		type="text/javascript">
</script>

<form>
<div id="hideoverflow" style="position: relative; width: 100%; margin: 0px; overflow: hidden;">
<table id="menu" width="100%" style="border: 1px solid buttonhighlight; border-bottom: 2px groove buttonhighlight; border-right: 1px solid buttonshadow; background-color: <?php echo $bgcolor; ?>;padding:0px;" cellspacing="0" cellpadding="0">
	<tr><td valign="top"><table width="220" border="0" cellpadding="0" cellspacing="0">
		<tr align="center" class="menu_header" valign="bottom">
			<td><div style="width: 0px; height: 26px;"></div></td>
			<td width="60">
				<a HREF="javascript:;"
					onMouseOver="popUp('HM_Menu1',event)"
					onMouseOut="popDown('HM_Menu1')"><?php echo $ARnls["m_object"]; ?>&nbsp;&nbsp;&nbsp;</a>
				</td>
			<td width="50">
				<a HREF="javascript:arshow('edit_object_data','edit.object.data.phtml')"
					onMouseOver="popUp('HM_Menu2',event)"
					onMouseOut="popDown('HM_Menu2')"><?php echo $ARnls["m_edit"]; ?>&nbsp;&nbsp;&nbsp;</a>
			</td>
			<td width="60">
				<a HREF="javascript:arshow('_new','<?php echo $this->make_url(); ?>view.html')"
					onMouseOver="popUp('HM_Menu3',event)"
					onMouseOut="popDown('HM_Menu3')"><?php echo $ARnls["m_view"]; ?>&nbsp;&nbsp;&nbsp;</a>
			</td>
			<td width="60">
				<a HREF="javascript:;"
					onMouseOver="popUp('HM_Menu4',event)"
					onMouseOut="popDown('HM_Menu4')"><?php echo $ARnls["m_help"]; ?>&nbsp;&nbsp;&nbsp;</a>
			</td>
		</tr>
		</table></td>
	<td align="right" width="100%">
		<?php echo $ARnls["path"];?>:&nbsp;</td><td align="right"><input type="text" name="path" size="50" value="<?php echo $this->path; ?>">
	</td>
</tr> <!-- Needed to fill out the menubar -->
</table>
</div>
</form>
