<?php
	/******************************************************************
	 system.get.phtml                              Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none 
	 Grant needed: none
	 Global variables: none

	 This template returns it's data;

	******************************************************************/
	$arResult = $this->data->filename;
?>
