<?php
	/******************************************************************
	 remove.phtml                                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: delete
	 Global variables: none

	 This template 

	******************************************************************/
	if ($this->CheckLogin("delete")) {
		$entry=$this->getdata("entry", "none");
		if (!$confirm=$this->getdata("confirm","none")) {
			if (!$this->data->repeat || ($this->data->repeat=="none")) {
				$confirm=$ARnls["current"];
			} else {
				$question=$ARnls["q:deleteall"];
				$buttons[]=$ARnls["all"];
				$buttons[]=$ARnls["current"];
				$arCallArgs=array_merge($arCallArgs, compact("question", "buttons"));
				$this->call("classic.confirm.phtml", $arCallArgs);
			}
		}
		if ($confirm) {
			$this->call("system.remove.phtml",compact("entry","confirm"));
			if (!$arReturnPage) {
				$arReturnPage=$this->store->root.$this->parent;
			}
			ldRedirect($arReturnPage);
		}
	}
?>