<?php
	/******************************************************************
	 remove.phtml                                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: delete
	 Global variables: none

	 This template 

	******************************************************************/
	if ($this->CheckLogin("delete")) {
		if (!$confirm) {
			if (!$this->data->repeat || ($this->data->repeat=="none")) {
				$confirm=$ARnls["current"];
			} else {
				$arCallArgs.="&question=".RawUrlEncode($ARnls["q:deleteall"]);
				$arCallArgs.="&buttons[]=".RawUrlEncode($ARnls["all"]);
				$arCallArgs.="&buttons[]=".RawUrlEncode($ARnls["current"]);
				$this->call("classic.confirm.phtml", $arCallArgs);
			}
		}
		if ($confirm) {
			$this->call("system.remove.phtml","entry=$entry&confirm=".RawUrlEncode($confirm));
			if (!$arReturnPage) {
				$arReturnPage=$this->store->root.$this->parent;
			}
			ldRedirect($arReturnPage);
		}
	}
?>