<?php
	/******************************************************************
	 classic.edit.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arSubmit
	 Grant needed: edit
	 Global variables: none

	 This template controls the flow between the form and save or delete
	 templates. 
	 First the form template will be shown. This will set 
	 $submit to either 'Save' or 'Delete'. Then the corresponding 
	 template will be called (In the case of delete via a get, save.phtml 
	 will simply be included.)

	 $submit='Save' or 'Delete' or don't care

	 No result.

	 FIXME: move checks on locks to individual templates.

	******************************************************************/

	if ($this->CheckConfig($arCallFunction, $arCallArgs) && $this->CheckLogin("edit")) {
		switch($arSubmit) {
			case $ARnls["save"] :	// save data
				// every object _must_ have a save.phtml, so:
				$this->call("classic.save.phtml",$arCallArgs);
				break;
			case $ARnls["delete"] : // delete this object
				$this->call("classic.remove.phtml",$arCallArgs);
				break;
			case $ARnls["cancel"] :	// stop editing -> release locks 
				include($this->store->code."includes/cancel.phtml");
				$this->unlock();
				break;
			default : 	// edit	
				// every object _must_ also have a form.phtml:
				if ($this->lock()) {
					// object locked, show us by who
					$this->call("show.locks.phtml");
				} else {
					$this->call("classic.form.phtml",$arCallArgs);
				}
		}
	}
?>