<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		$url=$_SERVER['PHP_SELF']."?".$arCallArgs;
?>
<html>
<body bgcolor="white">
<p>&nbsp;</p>
<p>&nbsp;</p>
<form>
<?php

  function arKeepVars($array, $prefix="") {
	if ($prefix) {
		$postfix="]";
		$prefix.="[";
	}
    @reset($array);
    while (list($key, $value)=@each($array)) {
      if (is_array($value)) {
        arKeepVars($value, $prefix.$key.$postfix);
      } else { // value not in array
        echo "<input type=\"hidden\" name=\"".$prefix.$key.$postfix."\" value=\"".preg_replace('/"/','&quot;',$value)."\">\n";
      }
    }
  }

  arKeepVars($arCallArgs);
?>
	<table border="0" cellspacing="0" width="400" cellpadding="0" bgcolor="#404074" align="center">
	<tr>
		<td colspan="3">&nbsp;&nbsp;<font face="helvetica, sans-serif" color="white"><b>Confirm</b></font></td>
	</tr><tr>
		<td><img src="<?php echo $AR->dir->images; ?>dot.gif" width="1" height="1" alt=""></td>
		<td bgcolor="white">
			<table vspace="1" hspace="1" border="0" cellspacing="0" cellpadding="5" width="100%">
			<tr><td colspan="2">
				<font face="helvetica,sans-serif"><?php echo $question; ?></font></td>
			</tr><tr>
				<td>
					<input type="button" name="cancel" value="Cancel" onClick="history.back();">
				</td><td align="right">
					<?php 
						while (list($key, $button)=each($buttons)) { 
							?>
								<input type="submit" name="confirm" value="<?php echo $button; ?>" style="width: 75px;">&nbsp;&nbsp;
							<?php 
						} 
					?>
				</td>
			</tr>
			</table>
		</td>
		<td><img src="<?php echo $AR->dir->images; ?>dot.gif" width="1" height="1" alt=""></td>
	</tr><tr>
		<td colspan="3"><img src="<?php echo $AR->dir->images; ?>dot.gif" width="1" height="1" alt=""></td>
	</tr>
	</table>
</form>	
</body>
</html>
<?php
	}
?>