<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
//		if (count($ARConfig->nls->list)>1) { // more than one language available
//			$languages=true;
//		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$step1="edit.object.data.item.phtml";
		$step2="edit.object.data.date.phtml";
		$step3="edit.object.data.repeat.phtml";

		$language="edit.object.language.phtml";

		$finish="edit.object.data.save.phtml";
		$lock="edit.object.lock.phtml";
		$cancel="edit.object.cancel.phtml";

		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$wgWizFlow[0]["cancel"] = $cancel;
		$wgWizFlow[0]["save"] = $save;
	 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["item"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
		$wgWizFlow[$i]["template"]=$step1;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["date"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/schedule.png";
		$wgWizFlow[$i]["template"]=$step2;

		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["repeat"];
		$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/scenario.png";
		$wgWizFlow[$i]["template"]=$step3;

		if ($hascustomdata) {
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
			$wgWizFlow[$i]["template"]=$custom;
		}

		if ($languages) { // more than one language available
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["image"]=$AR->dir->images."wizard/languages.png";
			$wgWizFlow[$i]["template"]=$language;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = $lock;
		}

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$this->type.'_open.gif" alt="" hspace="4" align="absmiddle">';
		include($this->store->code."widgets/wizard/new.html");
	}
?>