<?php
	/******************************************************************
	 edit.object.data.item.phtml Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Arguments: newtype, newparent, newfilename
	 Grant needed: read
	 Global variables: none

	 This template displays the data entry step for creating or editing
	 an object. The template is meant to be used as part of a wizard.

	 no result.

	******************************************************************/
	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="data">
		<legend><?php echo $ARnls["repeat"]."/".$ARnls["week"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center">
			<tr>
				<td>
					<?php echo $ARnls["every"]; ?>
				</td><td>
					<input size="3" maxlength="3" type="text" name="repeatn" value="<?php if ($this->getdata("repeatn", "none")) { $this->showdata("repeatn", "none"); } else { echo "1"; } ?>">
					&nbsp;<?php echo $ARnls["weeks"]; ?>
				</td>
			</tr><tr valign="top">
				<td colspan="2">
					<nobr><?php echo $ARnls["repeaton"]; ?></nobr>
				</td>
			</tr><tr>
				<td colspan="2">
					<table border="0" cellpadding="0" cellspacing="0">
					<tr>
					<?php
					$woptions=array(
							$ARnls["sun"],
							$ARnls["mon"],
							$ARnls["tue"],
							$ARnls["wed"],
							$ARnls["thu"],
							$ARnls["fri"],
							$ARnls["sat"]);

					$repeat_on=$this->getdata("repeat_on", "none");
					reset($woptions);
					while (list($key,$option)=each($woptions)) {

						if ($key==4) {
							echo "</tr><tr>\n";
						}
						echo "<td>";						
							echo "<input type=\"checkbox\" name=\"repeat_on[$key]\" value=\"1\"";
							if ($repeat_on[$key]) {
								echo " checked";
							}
							echo ">&nbsp;$option ";
						echo "</td>\n";
					}
					?>
					</tr>
					</table>
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["endson"]; ?>
				</td><td><?php
							if ($this->getdata("repeatend", "none")) {
								$wgDate=$this->getdata("repeatend", "none");
							} else {
								$wgDate=$this->getdata("date", "none") + $this->getdata("starthour","none")*3600 + $this->getdata("startminute", "none") * 60;
							}
							$wgDateName="repeatend";
							include($this->store->code."widgets/date/js.html");
							include($this->store->code."widgets/date/form.html");
						?>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		document.wgWizForm["repeatn"].focus();
	}
</script>
<?php
	}
?>