<?php
	/******************************************************************
	 edit.object.data.save.phtml				 Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: see system.save.data.phtml
	 Grant needed: read
	 Global variables: none

	 This template is a wrapper around system.save.data.phtml. It is
	 meant to be used as the last step in a wizard.

	 If system.save.data.phtml doesn't return an error, it will call
	 the javascript function 'objectadded(type, name, path)' in its
	 opener document and then close the current window.
	 
	 no result

	******************************************************************/
	if ((($this->arIsNewObject && $this->CheckLogin("add")) ||
		(!$this->arIsNewObject && $this->CheckLogin("edit"))) &&
		$this->CheckConfig()) {
		//	$repeatn: int
		//	week:  $repeat_on[$option]=0/1 
		//	       $option {0-7)
		//	month: $repeat_by=$option {"Day","Date"}
		//	       $repeatend: date int
		$roptions=array(	$ARnls["none"]	=> "none",
							$ARnls["day"]	=> "day",
							$ARnls["week"]	=> "week",
							$ARnls["month"]	=> "month",
							$ARnls["year"]	=> "year");
		if (!($confirm=$this->getdata("confirm","none"))) {
			if ($date=$this->getdata("date","none")) {
				$date_arr=getdate($date);
			}
			if ($entry=$this->getdata("entry","none")) {
				$entry_arr=getdate($entry);
			}
			$repeat=$this->getdata("repeat","none");			
			$repeatend=$this->getdata("repeatend","none");
			$repeatn=$this->getdata("repeatn","none");
			$repeat_on=$this->getdata("repeat_on","none");
			$repeat_by=$this->getdata("repeat_by","none");

			if (($this->arIsNewObject) ||
					(!$this->data->repeat) ||
					($this->data->repeat=="none")) { // default all for new items, and none repeating items
				$confirm=$ARnls["all"];
			} else if (($repeatnls) && ( 
					($this->data->repeatend<($repeatend+24*60*60-1)) ||
					($this->data->repeatn!=$repeatn) ||
					($this->data->repeat!=$repeat) ||
					((serialize($this->data->repeat_on)!=serialize($repeat_on)) && ($repeat=="week")) ||
					((serialize($this->data->repeat_by)!=serialize($repeat_by)) && ($repeat=="month")) ) ) {
				// when changing the repeat values, default to all
				$confirm=$ARnls["all"];
			} else if ($date && $entry &&
					 ( ($entry_arr["year"]!=$date_arr["year"]) ||
					 ($entry_arr["mon"]!=$date_arr["mon"]) ||
					 ($entry_arr["mday"]!=$date_arr["mday"]) ) ) { // when the date is changed, default to current
				$confirm=$ARnls["current"];
			} else {
				$arCallArgs["question"]=$ARnls["q:applychanges"];
				$buttons[]=$ARnls["all"];
				$buttons[]=$ARnls["current"];
				$arCallArgs["buttons"]=$buttons;
				$this->call("edit.object.data.save.confirm.phtml",$arCallArgs);
			}
		} 
		if ($confirm) {		
			$arCallArgs["repeat"]=$repeat;
			$arCallArgs["confirm"]=$confirm;
			$dosave = true;
		}
	} else {
		$dosave = true;
	}
	if ($dosave) {
		$arCallArgs["repeat"]=$repeat;
		$arCallArgs["confirm"]=$confirm;
		$this->call("system.save.data.phtml",$arCallArgs);
		if ($this->error) {
			?>
				<font color="red" face="arial,helvetica,sans-serif" size=+1><?php echo $this->error; ?></font><p>
			<?php
			$arResult["save"]=false;
		} else {
			?>
				<script> 
					if (top.window.opener) {
						if (top.window.opener.objectadded) {
							top.window.opener.objectadded('<?php echo $this->type; ?>','<?php echo AddCSlashes($this->nlsdata->name, ARESCAPE); ?>','<?php echo $this->path; ?>'); 
						}
						<?php
							if (!$arIsNewObject || $this->getdata("arCloseWindow", "none")) {
						?>
									top.window.close();
						<?php
							} else {
						?>
									top.window.location.href='object.new.select.phtml';
						<?php
							}
						?>
					} else if (top.window.dialogArguments) {
						arr=new Array();
						arr['type']='<?php echo $this->type; ?>';
						arr['name']='<?php echo AddCSlashes($this->nlsdata->name, ARESCAPE); ?>';
						arr['path']='<?php echo $this->path; ?>';
						top.window.returnValue=arr;
						top.window.close();
					} 
				</script>
			<?php
		}
	}
?>