<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
		if (count($ARConfig->nls->list)>1) { // more than one language available
			$languages=true;
			$saveoffset=1;
		} else {
			$saveoffset=0;
		}
		$custom="edit.object.data.custom.phtml";

		include($this->store->code."widgets/wizard/code.php");

		$step1="edit.object.data.item.phtml";
		$step2="edit.object.data.date.phtml";
		$step3="edit.object.data.repeat.phtml";

		$language="edit.object.language.phtml";

		$finish="edit.object.data.save.phtml";
	 
		$wgWizFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["item"];
		$wgWizFlow[$i]["template"]=$step1;
		$wgWizFlow[$i]["next"]=$i+1; 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["date"];
		$wgWizFlow[$i]["template"]=$step2;
		$wgWizFlow[$i]["prev"]=$i-1;
		$wgWizFlow[$i]["next"]=$i+1; 
		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["repeat"];
		$wgWizFlow[$i]["template"]=$step3;
		$wgWizFlow[$i]["prev"]=$i-1;
		$wgWizFlow[$i]["next"]=$i+1; 

		if ($hascustomdata) {
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2+$saveoffset;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["customdata"];
			$wgWizFlow[$i]["template"]=$custom;
			$wgWizFlow[$i]["prev"]=$i-1;
		}
		if ($languages) { // more than one language available
			$wgWizFlow[$i]["next"]=$i+1;
			$wgWizFlow[$i]["save"]=$i+2;
			$i++;
			$wgWizFlow[$i]["title"]=$ARnls["language"];
			$wgWizFlow[$i]["template"]=$language;
			$wgWizFlow[$i]["next"]=1;
			$wgWizFlow[$i]["prev"]=$i-1;
			$wgWizFlow[$i]["save"]=$i+1;
		} else {
			unset($wgWizFlow[$i]["next"]);
			$wgWizFlow[$i]["save"]=$i+1;
		}


		$i++;
		$wgWizFlow[$i]["title"]=$ARnls["save"];
		$wgWizFlow[$i]["template"]=$finish;
		$wgWizFlow[$i]["back"]=$i-1;
		for ($ii=1; $ii<$i; $ii++) {
			$wgWizFlow[$ii]["save"]=$i;
		}
		
		$arLanguage=$this->getdata("arLanguage","none");
		if ($wgWizFlow[0]["current"]==5) { // =edit.object.language.phtml
			$arControl=$this->getdata("wgWizControl","none");
			if (wgWizGetAction($arControl)=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$result=$this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml");
		$wgWizTitle=$ARnls["edit"]." ".$result[0];		
		include($this->store->code."widgets/wizard/classic.html");
	}
?>