<?php
	/******************************************************************
	 edit.object.data.item.phtml Muze Ariadne v2.1
	 ------------------------------------------------------------------
	 Arguments: newtype, newparent, newfilename
	 Grant needed: read
	 Global variables: none

	 This template displays the data entry step for creating or editing
	 an object. The template is meant to be used as part of a wizard.

	 no result.

	******************************************************************/
	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<script>
  var currentRepeat=false;

  function updateRepeat(value) {
	if (!value) {
		repeat=document.wgWizForm.repeat;
		value=repeat.options[repeat.selectedIndex].value;
	}
    if (window.all) {
      var fieldset=window.all[value];
    } else {
      var fieldset=document.getElementById(value);
    }
    if (currentRepeat) {
      currentRepeat.style.display='none';
	}
    fieldset.style.display='block';
	currentRepeat=fieldset;
  }

  function updateRepeatN(value) {
	document.wgWizForm.repeatn.value=value;
	document.wgWizForm.day_repeatn.value=value;
	document.wgWizForm.week_repeatn.value=value;
	document.wgWizForm.month_repeatn.value=value;
	document.wgWizForm.year_repeatn.value=value;
  }

  // alternative SetDate for the date widget
  function SetDate(name, date, formatted) {
    document.wgWizForm.repeatend.value=date;
    document.wgWizForm['day_repeatend'].value=date;
    document.wgWizForm['day_repeatendformatted'].value=formatted;
    document.wgWizForm['week_repeatend'].value=date;
    document.wgWizForm['week_repeatendformatted'].value=formatted;
    document.wgWizForm['month_repeatend'].value=date;
    document.wgWizForm['month_repeatendformatted'].value=formatted;
    document.wgWizForm['year_repeatend'].value=date;
    document.wgWizForm['year_repeatendformatted'].value=formatted;
  }

</script>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
 				$arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
		<fieldset id="data">
		<legend><?php echo $ARnls["repeat"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<select name="repeat" onChange="updateRepeat();">
					<?php
						$roptions = array(
								"none" 	=> $ARnls["none"],
								"day"  	=> $ARnls["day"],
								"week" 	=> $ARnls["week"],
								"month"	=> $ARnls["month"],
								"year"	=> $ARnls["year"]);

						$repeat=$this->getdata("repeat", "none");
						while (list($key, $val)=each($roptions)) {
							echo "<option value=\"$key\"";
							if ((!$repeat && $key=="none") || ($repeat==$key)) { echo " selected"; }
							echo ">$val</option>";
						}
					?>
					</select>
				</td>
			</tr>
			</table>
		</fieldset>

		<?php
			$repeatn=$this->getdata("repeatn","none");
			if (!$repeatn) {
				$repeatn=1;
			}
			$repeatend=$this->getdata("repeatend","none");
			if (!$repeatend) {
				$repeatend=$this->getdata("date", "none") + $this->getdata("starthour","none")*3600 + $this->getdata("startminute", "none") * 60;
			}
			$repeat_on=$this->getdata("repeat_on", "none");
			$repeat_by=$this->getdata("repeat_by", "none");
			if (!$repeat_by) {
				$repeat_by="day";
			}
			$woptions=array(
				$ARnls["sun"],
				$ARnls["mon"],
				$ARnls["tue"],
				$ARnls["wed"],
				$ARnls["thu"],
				$ARnls["fri"],
				$ARnls["sat"]);

		?>
		<input type="hidden" name="repeatn" value="<?php echo $repeatn; ?>">
		<input type="hidden" name="repeatend" value="<?php echo $repeatend; ?>">
		<input type="hidden" name="repeat_on" value="<?php echo $repeat_on; ?>">

		<fieldset id="day" style="display: none;">
		<legend><?php echo $ARnls["repeat"].": ".$ARnls["day"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<?php echo $ARnls["every"]; ?>
				</td><td>
					<input size="3" maxlength="3" type="text" name="day_repeatn" value="<?php echo $repeatn; ?>" onChange="updateRepeatN(this.value);">
					&nbsp;<?php echo $ARnls["days"]; ?>
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["endson"]; ?>
				</td><td>
					<?php
						$wgDate=$repeatend;
						$wgDateName="day_repeatend";
						include($this->store->code."widgets/date/js.selectdate.html");
						include($this->store->code."widgets/date/form.html");
					?>
				</td>
			</tr>
			</table>
		</fieldset>

		<fieldset id="week" style="display: none;">
		<legend><?php echo $ARnls["repeat"].": ".$ARnls["week"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<?php echo $ARnls["every"]; ?>
				</td><td colspan="3">
					<input size="3" maxlength="3" type="text" name="week_repeatn" value="<?php echo $repeatn; ?>" onChange="updateRepeatN(this.value);">
					&nbsp;<?php echo $ARnls["weeks"]; ?>
				</td>
			</tr><tr>
				<td>
					<nobr><?php echo $ARnls["repeaton"]; ?></nobr>
				</td>
				<?php
					reset($woptions);
					while (list($key,$option)=each($woptions)) {

						if (($key==3) || ($key==6)) {
							echo "</tr><tr><td></td>\n";
						}
						echo "<td><input type=\"checkbox\" name=\"repeat_on[$key]\" value=\"1\"";
						if ($repeat_on[$key]) {
							echo " checked";
						}
						echo ">&nbsp;$option</td>";
					}
					?>
			</tr><tr>
				<td>
					<?php echo $ARnls["endson"]; ?>
				</td><td colspan="3">
					<?php
						$wgDate=$repeatend;
						$wgDateName="week_repeatend";
						include($this->store->code."widgets/date/form.html");
					?>
				</td>
			</tr>
			</table>
		</fieldset>

		<fieldset id="month" style="display: none;">
		<legend><?php echo $ARnls["repeat"].": ".$ARnls["month"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<?php echo $ARnls["every"]; ?>
				</td><td>
					<input size="3" maxlength="3" type="text" name="month_repeatn" value="<?php echo $repeatn; ?>" onChange="updateRepeatN(this.value);">
					&nbsp;<?php echo $ARnls["months"]; ?>
				</td>
			</tr><tr>
				<td>
					<nobr><?php echo $ARnls["repeatby"]; ?></nobr>
				</td>
				<td>
					<input type="radio" name="repeat_by" value="<?php echo $ARnls["day"]; ?>" 
							<?php if ($repeat_by=="day")  echo "checked"; ?>>
							<?php echo $ARnls["day"]; ?>
					<input type="radio" name="repeat_by" value="<?php echo $ARnls["date"]; ?>" 
							<?php if ($repeat_by=="date")  echo "checked"; ?>>
							<?php echo $ARnls["date"]; ?>
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["endson"]; ?>
				</td><td>
					<?php
						$wgDate=$repeatend;
						$wgDateName="month_repeatend";
						include($this->store->code."widgets/date/form.html");
					?>
				</td>
			</tr>
			</table>
		</fieldset>

		<fieldset id="year" style="display: none;">
		<legend><?php echo $ARnls["repeat"].": ".$ARnls["year"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="90%">
			<tr>
				<td>
					<?php echo $ARnls["every"]; ?>
				</td><td>
					<input size="3" maxlength="3" type="text" name="year_repeatn" value="<?php echo $repeatn; ?>" onChange="updateRepeatN(this.value);">
					&nbsp;<?php echo $ARnls["years"]; ?>
				</td>
			</tr><tr>
				<td>
					<?php echo $ARnls["endson"]; ?>
				</td><td>
					<?php
						$wgDate=$repeatend;
						$wgDateName="year_repeatend";
						include($this->store->code."widgets/date/form.html");
					?>
				</td>
			</tr>
			</table>
		</fieldset>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		<?php
			if ($repeat) {
				echo "		updateRepeat('".$repeat."');\n";
			}
		?>
		document.wgWizForm.repeat.focus();
	}
</script>
<?php
	}
?>