<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}
	if (count($ARConfig->nls->list)>1) { // more than one language available
		$languages=true;
		$saveoffset=1;
	} else {
		$saveoffset=0;
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.filename.phtml";
	$step1="edit.object.data.item.phtml";
	$step2="edit.object.data.date.phtml";
	$step3="edit.object.data.repeat.phtml";
	$step5="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["next"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["item"];
	$arFlow[$i]["template"]=$step1;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["date"];
	$arFlow[$i]["template"]=$step2;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 
	$i++;
	$arFlow[$i]["title"]=$ARnls["repeat"];
	$arFlow[$i]["template"]=$step3;
	$arFlow[$i]["prev"]=$i-1;
	$arFlow[$i]["next"]=$i+1; 

	$repeat=$this->getdata("repeat", "none");
	if ($repeat==="day") {
		$step4="edit.object.data.repeat.day.phtml";
	} else
	if ($repeat==="week") {
		$step4="edit.object.data.repeat.week.phtml";
	} else
	if ($repeat==="month") {
		$step4="edit.object.data.repeat.month.phtml";
	} else
	if ($repeat==="year") {
		$step4="edit.object.data.repeat.year.phtml";
	} else {
		$arFlow[0]["current"]++; // skip step4
	}
	if ($step4) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["repeat"]."&nbsp;".$ARnls["data"];
		$arFlow[$i]["template"]=$step4;
		$arFlow[$i]["prev"]=$i-1;
		$arFlow[$i]["next"]=$i+1; 
	}

	if ($hascustomdata) {
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2+$saveoffset;
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["template"]=$custom;
		$arFlow[$i]["prev"]=$i-1;
	}
	if ($languages) { // more than one language available
		$arFlow[$i]["next"]=$i+1;
		$arFlow[$i]["save"]=$i+2;
		$i++;
		$arFlow[$i]["title"]=$ARnls["language"];
		$arFlow[$i]["template"]=$step5;
		$arFlow[$i]["next"]=2;
		$arFlow[$i]["prev"]=$i-1;
		$arFlow[$i]["save"]=$i+1;
	} else {
		$arFlow[$i]["save"]=$i+1;
	}

	$i++;
	$arFlow[$i]["title"]=$ARnls["save"];
	$arFlow[$i]["template"]=$finish;
	$arFlow[$i]["back"]=$i-1;
	
	$arLanguage=$this->getdata("arLanguage","none");
	if ($arFlow[0]["current"]==5) { // =edit.object.language.phtml
		$arControl=$this->getdata("wgWizControl","none");
		if ($arControl==$ARnls["prev"]) { // if previous selected, ignore the language select list.
			$arLanguage=$this->getdata("arPrevLanguage","none");
			$ARCurrent->arLanguage=$arLanguage;
		}
	}
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}
	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	$arResult=$arFlow;
?>