<?php
	/******************************************************************
	 remove.phtml                                          Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: none
	 Grant needed: delete
	 Global variables: none

	 This template 

	******************************************************************/
	if ($this->CheckLogin("delete")) {
		if (!$confirm) {
			if (!$this->data->repeat || ($this->data->repeat=="none")) {
				$confirm=$ARnls["current"];
			} else {
				$question=$ARnls["q:deleteall"];
				$buttons[]=$ARnls["all"];
				$buttons[]=$ARnls["current"];
				$this->call("confirm.phtml");
			}
		}
		if ($confirm) {
			$this->call("system.remove.phtml","entry=$entry&confirm=".RawUrlEncode($confirm));
			if (!$arReturnPage) {
				$arReturnPage=$this->store->root.$this->parent;
			}
			Header("Location: $arReturnPage");
		}
	}
?>