<?php
	if ($this->CheckLogin("edit"))) && $this->CheckConfig()) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
	    $this->data=@current($this->get(".","system.get.data.phtml"));

		if ($confirm==$ARnls["all"]) {
			$this->ls(".","system.remove.phtml","entry=$entry&confirm=".RawUrlEncode($confirm));
		}
		if ($confirm==$ARnls["all"]) {
			$this->data->timeframes=$this->NewEndtime($entry);
		} else {
			$this->data->timeframes=$this->DelTimeframe($entry);
		}
		if (@count($this->data->timeframes)) { // entries left
			$this->save();
		} else { // all entries gone, remove object
			$this->call("system.delete.phtml");
		}
	}
?>