<?php
	/******************************************************************
	 edit.object.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	if ($this->CheckLogin("edit",$this->type) && $this->CheckConfig()) {
		$configcache=$ARConfig->cache[$this->path];
		if ($configcache->custom) {
			while (list($key, $definition)=each($configcache->custom)) {
				if (($definition["type"]==$this->type) ||
					($definition["inherit"] && ($this->implements($definition["type"])))) {
					$hascustomdata=true;
					break;
				}
			}
		}
//		if (count($ARConfig->nls->list)>1) { // more than one language available
//			$languages=true;
//		}

		include($this->store->code."widgets/wizard/code.php");

		$wgWizFlow[] = Array {
			"current"	=> $this->getdata("wgWizCurrent","none"),
			"cancel"	=> "edit.object.cancel.phtml",
			"save"		=> "edit.object.data.save.phtml"
		};


		$wgWizFlow[] = Array {
			"title"		=> $ARnls["data"],
			"template"	=> "edit.object.data.form.phtml",
			"image"		=> $AR->dir->images."wizard/data.png"
		};
		
		$wgWizFlow[] = Array {
			"title"		=> "Connection", //FIXME use NLS
			"template"	=> "edit.object.data.conninfo.phtml",
			"image"     => $AR->dir->images."wizard/data.png"
		};

		$wgWizFlow[] = Array {
			"title"		=> "General filter", //FIXME use NLS
			"template"	=> "edit.object.data.generalfilter.phtml",
			"image"     => $AR->dir->images."wizard/data.png"
		}
	
		$wgWizFlow[] = Array {
			"title"		=> "Search translation", //FIXME use NLS
			"template"	=> "edit.object.data.searchtranslation.phtml",
			"image"     => $AR->dir->images."wizard/data.png"
		}

		$wgWizFlow[] = Array {
			"title"		=> "Other paramaters", //FIXME use NLS
			"template"	=> "edit.object.data.otherparams.phtml",
			"image"     => $AR->dir->images."wizard/data.png"
		}

		$wgWizFlow[] = Array {
			"title"		=> "User mapping", //FIXME use NLS
			"template"	=> "edit.object.data.usermapping.phtml",
			"image"     => $AR->dir->images."wizard/data.png"
		}

		if ($hascustomdata) {
			$wgWizFlow[]=Array(
				"title"		=> $ARnls["customdata"],
				"image"		=> $AR->dir->images."wizard/customdata.png",
				"template"	=> "edit.object.data.custom.phtml");
		}
		
		if ($languages) { // more than one language available			
			$wgWizFlow[]=Array(
				"title"		=> $ARnls["language"],
				"image"		=> $AR->dir->images."wizard/languages.png",
				"template"	=> "edit.object.language.phtml");
		}
		
		$arLanguage=$this->getdata("arLanguage","none");
		$arControl=wgWizGetAction($this->getdata("wgWizControl","none"));
		if ($wgWizFlow[0]["current"]=="language") { // =edit.object.language.phtml
			if ($arControl=="prev") { // if previous selected, ignore the language select list.
				$arLanguage=$this->getdata("arPrevLanguage","none");
				$ARCurrent->arLanguage=$arLanguage;
			}
		}
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		$arLanguage=$this->getdata("arLanguage","none");
		if (!$arLanguage) { // language select hasn't been done yet, so start with default language
			$arLanguage=$ARConfig->nls->default;
			$ARCurrent->arLanguage=$arLanguage;
		}

		if (!$this->lock('O')) {
			$i = $wgWizFlow[0]["current"]+1;
			$wgWizFlow[$i]["template"] = "edit.object.lock.phtml";
		}

		$name=current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml"));
		$wgWizTitle=$ARnls["edit"]." ".$name;		
		$wgWizHeader=$wgWizTitle.'<img src="'.$AR->dir->images.'icons/'.$this->type.'_open.gif" alt="" hspace="4" align="absmiddle">';
		include($this->store->code."widgets/wizard/new.html");

	}
?>