<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckSilent("read")) {
?>
<script language="javascript">

function addreplacement(myform) {
  var ariadneexpr=myform.expr_ariadne.value;
  var ldapexpr=myform.expr_ldap.value;

  if (ariadneexpr=='' || ldapexpr=='') {
    return;
  }

  // We use two pipe characters ('||') for seperating the two strings, so
  // make sure that this sequence doesn't occur in the first string
  // (it doesn't matter if it occurs in the second string, because we
  // do the split on the first occurence only later)
  // Doing escaping stuff manually is stupid, but I'm not aware of
  // quoting functions portable between javascript and php
  ariadneexpr_=ariadneexpr.replace(/\|/g, "\\|");

  mylist=myform.searchtranslations;
  mylist.options[mylist.length]=
    new Option(ariadneexpr+' -> '+ldapexpr, ariadneexpr_+'||'+ldapexpr);

  myform.expr_ariadne.value='';
  myform.expr_ldap.value='';

  mylist.selectedIndex=mylist.length-1;
}

function delreplacement(myform) {
  if (myform.searchtranslations.selectedIndex==-1) {
    return;
  }

  var old=myform.searchtranslations.options[myform.searchtranslations.selectedIndex].value;
  myform.searchtranslations.options[myform.searchtranslations.selectedIndex]=null;

  arr=old.split("||", 2);
  ariadneexpr=arr[0];
  ldapexpr=arr[1];

  // Unescape
  ariadneexpr=ariadneexpr.replace(/\\\|/g, "|");

  myform.expr_ariadne.value=ariadneexpr;
  myform.expr_ldap.value=ldapexpr;
}

/* Select all items in the replacement list, so they get transmitted
   with the form */
function selectsearchtranslations() {
  var c;

  myform=document.wgWizForm;

  for (c=0;c<myform.searchtranslations.length;c++) {
    myform.searchtranslations.options[c].selected=true;
  }

  if (myform.searchtranslations.length==0) {
    // Transmit at least one element for the list, if it's empty;
    // otherwise no POST variable with that name will be transmitted,
    // and the empty list will be overridden by the hidden
    // arStoreVars fields from the wizard...
    myform.searchtranslations.options[0]=new Option('', '', true, true);
  }

  return true;
}

document.wgWizForm.wgWizSubmitHandler=selectsearchtranslations;

</script>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>

		<fieldset id="searchtranslation">
		<legend><?php echo "Search translation"; //FIXME ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="100%">
			<tr>
				<td><?php echo "Ariadne search expression:"; //FIXME ?>
				<br>
					<input type="text" name="expr_ariadne" style="width:250;">
				</td>
			</tr>
			<tr>
				<td><?php echo "Replace with LDAP filter expression:"; //FIXME ?>
				<br>
					<input type="text" name="expr_ldap" style="width:250;">
				</td>
			</tr>
			<tr>
				<td><table align="center" border="0" cellpadding="5" cellspacing="0"><tr>
				<td nowrap><input type="button" name="move_down" value="&darr; Add &darr;" onClick="addreplacement(this.form);">
				&nbsp;
				<input type="button" name="move_up" value="&uarr; Remove &uarr;" onClick="delreplacement(this.form);"></td>
				</tr></table>
				</td>
			</tr>
			<tr>
				<td><select multiple id="searchtranslations" name="ldap_searchtranslations[]" size="4" style="width:250;">
<?php
					$transl=$this->getdata("ldap_searchtranslations", "none");
					if (is_array($transl) && $transl[0]!="") {
						foreach ($transl as $tr) {
							$tr = htmlspecialchars( $tr, ENT_QUOTES, 'UTF-8');
							list($ariadneexpr, $ldapexpr)=explode("||", $tr, 2);
							$ariadneexpr=str_replace("\\|", "|", $ariadneexpr);
							print "<option value=\"$tr\">$ariadneexpr -&gt; $ldapexpr</option>\n";
						}
					}
?>
				</select>
				</td>
			</tr>
			</table>
		</fieldset>

	</td>
</tr>
</table>
<?php
	}
?>
