<?php
	/******************************************************************

	******************************************************************/
	if ($this->CheckSilent("read")) {
?>
<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>

		<input type="hidden" name="ldap_useiso8859" value="<?php $this->showdata("ldap_useiso8859","none"); ?>">
		<fieldset id="charset">
		<legend><?php echo "Charset"; //FIXME ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="100%">
			<tr>
				<td><input type="checkbox" name="useiso8859"<?php if ($this->getdata("ldap_useiso8859","none")) print "checked" ?> onClick="this.form.ldap_useiso8859.value=(this.checked ? '1' : '0');">
				<?php echo "Use ISO-8859 instead of UTF-8"; //FIXME ?>
				<br>
				</td>
			</tr>
			</table>
		</fieldset>
		<br>
		<fieldset id="nameattribute">
		<legend><?php echo "Name attribute"; //FIXME ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="100%">
			<tr>
				<td><?php echo "LDAP attribute to use as name"; //FIXME ?>
				<br>
				<input type="text" name="ldap_nameattribute" maxlength="50" value="<?php $this->showdata("ldap_nameattribute","none"); ?>">
				</td>
			</tr>
			</table>
		</fieldset>
		<br>
		<fieldset id="defaultsorting">
		<legend><?php echo "Default sorting"; //FIXME ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
			<table border="0" align="center" width="100%">
			<tr>
				<td><?php echo "Default sorting attribute"; //FIXME ?>
				<br>
				<input type="text" name="ldap_defsortattr" maxlength="50" value="<?php $this->showdata("ldap_defsortattr","none"); ?>">
				</td>
			</tr>
			</table>
		</fieldset>

	</td>
</tr>
</table>
<?php
	}
?>
