<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.filename.phtml";
	$step1="edit.object.data.form.phtml";

	$step2="edit.object.data.conninfo.phtml";
	$step3="edit.object.data.generalfilter.phtml";
	$step4="edit.object.data.searchtranslation.phtml";
	$step5="edit.object.data.otherparams.phtml";
	$step6="edit.object.data.usermapping.phtml";

	$step7="edit.object.language.phtml";
	$finish="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$finish;

	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step1;

	$i++;
	$arFlow[$i]["title"]="Connection"; //FIXME
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step2;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]="General filter"; //FIXME
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step3;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]="Search translation"; //FIXME
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step4;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]="Other parameters"; //FIXME
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step5;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]="User mapping"; //FIXME
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step6;
	$arFlow[$i]["nolang"]=true;
	
	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}

	$arLanguage=$this->getdata("arLanguage","none");
	if (!$arLanguage) { // language select hasn't been done yet, so start with default language
		$arLanguage=$ARConfig->nls->default;
		$ARCurrent->arLanguage=$arLanguage;
	}

	$arNewFilename=$this->getdata("arNewFilename","none");
	if (!$arNewFilename) {
		$arNewFilename="{5:id}";
		$ARCurrent->arNewFilename=$arNewFilename;
	}		
	$arResult = $this->call("user.wizard.new.html", Array("wgWizFlow" => $arFlow));
?>
