<?php

// This assumes that the Ariadne administrator has created a mapping
// from the "login.value" property to the LDAP attribute which he
// wishes to use as the login name for the pldapconnection object

global $AR, $ARCurrent;

// If there is no user mapping, there is nothing we can do...
if ($this->data->mappeduser) {

	if ($ARCurrent && $ARCurrent->session) {
		$ldapdata=$ARCurrent->session->get("userldapdata");
	}

	// Fetch the user's LDAP data, if not already cached in the
	// session data
	if (!is_array($ldapdata)) {
		$criteria=Array();
		$criteria["login"]["value"]["="]="'".AddSlashes($ARLogin)."'";
		$this->get_ldap_data($criteria, $limit, $offset);
		$ldapdata=$this->ldapdata[0];
		$ARCurrent->session->put("userldapdata", $ldapdata);
		$ARCurrent->session->save();
	}

	//print_r($ldapdata);

	// Different LDAP implementations have different attributes
	// for group memberships; we try to support them all...
	$groupattrs=array("groupmembership", "memberof");
	$AR->externalgroupmemberships=array();
	// Store the LDAP group memberships as they will be used later to
	// virtually add the user to Ariadne groups with the same name
	foreach ($groupattrs as $groupattr) {
		if (is_array($ldapdata[$groupattr])) {
			for ($c=0;$c<$ldapdata[$groupattr]["count"];$c++) {
				list($group)=ldap_explode_dn($ldapdata[$groupattr][$c], 1);
				array_push($AR->externalgroupmemberships, strtolower($group));
			}
		}
	}

	// Test the supplied password by trying a ldap_bind() with it
	if ($ldapdata["dn"]) {
		$ds=@ldap_connect($this->data->ldap_server);
		if ($ds) {
			$r=@ldap_bind($ds, $ldapdata["dn"], $ARPassword);
			ldap_close($ds);

			if ($r) {
				// LDAP password is correct, so get the mapped
				// user and modify some of the Ariadne data
				// with the corresponding LDAP data
				$arResult=current($this->store->call("system.get.phtml", "",
				                             $this->store->get($this->data->mappeduser)));
				// If you change the mapping of LDAP attributes to Ariadne data
				// below, also change it in system.get.externaluser.phtml
				$arResult->data->name=$ldapdata["displayname"][0];
				$arResult->data->email=$ldapdata["mail"][0];
			}
		}
	}
}

?>
