<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	require_once($this->store->get_config('code')."modules/mod_page.php");

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		if (!$this->arIsNewObject) {
		    $this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new baseObject;
		}

		$this->error = null;

		// unset the properties array, so no properties can be passed to this template.
		$properties = array();

		if (!$this->getdata("name",$ARConfig->nls->default)) { // default language for this path
			$this->error = ar::error( sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]), 1101);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new baseObject;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			$count=0;
			while (list($key, $value)=each($AR->nls->list)) {
				if ($this->getdata($key, "none")) {
					if (!$this->data->$key) {
						$newnlsdata=new baseObject;
					} else {
						$newnlsdata=$this->data->$key;
					}
					if (!$this->getdata("name", $key)) {
						$this->error = ar::error(sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]),1114);
					}
					$newnlsdata->name=$this->getdata("name", $key);
					$properties["name"][$count]["value"]=$this->getdata("name", $key);
					$properties["name"][$count]["nls"]=$key;
					$properties["text"][$count]["value"]=$this->getdata("name", $key);
					$properties["text"][$count]["nls"]=$key;
					$count++;
					$newnlsdata->summary=page::compile($this->getdata("summary",$key), $key);
					$properties["text"][$count]["value"]=$this->getdata("summary", $key);
					$properties["text"][$count]["nls"]=$key;
					$count++;
					$newnlsdata->effect=$this->getdata("effect", $key);
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				}
			}
		}

		$this->data->ldap_server = $this->getdata("ldap_server", "none");
		$this->data->ldap_username = $this->getdata("ldap_username", "none");
		$this->data->ldap_password = $this->getdata("ldap_password", "none");
		$this->data->ldap_basedn = $this->getdata("ldap_basedn", "none");
		$this->data->ldap_generalfilter = $this->getdata("ldap_generalfilter", "none");
		$this->data->ldap_userfilter = $this->getdata("ldap_userfilter", "none");
		$this->data->ldap_groupfilter = $this->getdata("ldap_groupfilter", "none");
		$this->data->ldap_searchtranslations = $this->getdata("ldap_searchtranslations", "none");
		$this->data->ldap_useiso8859 = $this->getdata("ldap_useiso8859", "none");
		$this->data->ldap_nameattribute = $this->getdata("ldap_nameattribute", "none");
		$this->data->ldap_defsortattr = $this->getdata("ldap_defsortattr", "none");
		$this->data->mappeduser = $this->getdata("mappeduser", "none");

		$arResult = $this->save($properties);
		$this->ClearCache();
	}
?>
