<?php

// This assumes that the Ariadne administrator has created a mapping
// from the "login.value" property to the LDAP attribute which he
// wishes to use as the login name for the pldapconnection object

global $AR, $ARCurrent;

// If there is no user mapping, there is nothing we can do...
if ($this->data->mappeduser) {

	if ($ARCurrent && $ARCurrent->session) {
		$ldapdata=$ARCurrent->session->get("userldapdata");
	}

	// Fetch the user's LDAP data, if not already cached in the
	// session data
	if (!is_array($ldapdata)) {
		$criteria=array();
		$criteria["login"]["value"]["="]=$ARLogin;
		$this->get_ldap_data($criteria, $limit, $offset);
		$ldapdata=$this->ldapdata[0];
		$ARCurrent->session->put("userldapdata", $ldapdata);
		$ARCurrent->session->save();
	}

	//print_r($ldapdata);

	// Test the supplied password by trying a ldap_bind() with it
	if ($ldapdata["dn"]) {
		$ds=@ldap_connect($this->data->ldap_server);
		if ($ds) {
			$r=@ldap_bind($ds, $ldapdata["dn"], $ARPassword);
			ldap_close($ds);

			if ($r) {
				// LDAP password is correct, so get the mapped
				// user and modify some of the Ariadne data
				// with the corresponding LDAP data
				$arResult=current($this->store->call("system.get.phtml", "",
				                             $this->store->get($this->data->mappeduser)));
				// If you change the mapping of LDAP attributes to Ariadne data
				// below, also change it in system.get.externaluser.phtml
				$arResult->externalgroupmemberships=$this->get_nested_groupmemberships($ldapdata);
				$arResult->data->name=$ldapdata["displayname"][0];
				$arResult->data->email=$ldapdata["mail"][0];
			}
		}
	}
}

?>
