<?php
  /**************************************************************************/
  /* Ariadne Global Configuration File                                      */
  /* =================================                                      */
  /* This file contains system wide variables and configuration information */
  /* Some lines should not be changed, these are marked with the text:      */
  /*   // do not change                                                     */
  /**************************************************************************/
        if (!class_exists('baseObject',false)) {
                class baseObject { }           // do not change
        }

	$AR = new baseObject;             // do not change
	$AR->dir = new baseObject;        // do not change
	$AR->IM = new baseObject;         // do not change
	$AR->DB = new baseObject;         // do not change
	$AR->SVN = new baseObject;        // do not change
	$AR->Tidy = new baseObject;       // do not change
	$AR->Grep = new baseObject;       // do not change
	$AR->Webkit2png = new baseObject; // do not change
	$AR->loader = new baseObject;     // do not change
	$AR->superClass = array();        // do not change

	$AR->ESI = false;
	$AR->arNoHeaders = false;
	$AR->session = new baseObject;

	$ARCurrent = new baseObject;
	$ARCurrent->arNoHeaders = false;

$AR->OS = 'UNIX';

  /**************************************************************************/
  /* Error Reporting                                                        */
  /* =============                                                          */
  /* Ariadne generates warnings when E_NOTICE is not disabled               */
  /**************************************************************************/

  error_reporting( E_ALL & ~(E_NOTICE | E_DEPRECATED | E_STRICT) );
$AR->dir->www = '';
$AR->dir->install = '/opt/ariadne';
$AR->DB->dbms = 'mysql';
$AR->DB->host = 'mysql';
$AR->DB->database = 'ariadne';
$AR->DB->user = 'ariadne';
$AR->DB->password = 'secret';

  /**************************************************************************/
  /* sgSalt:                                                                */
  /* Set this key to a random string if you want to use the sg* functions   */
  /**************************************************************************/

  $AR->sgSalt = 'wjkqliervj';
  /**************************************************************************/
  /* sessionCryptoKey                                                       */
  /* contains a base64 encoded key for mcrypti                              */
  /* $key = base64_encode(mcrypt_create_iv(                                 */
  /*             mcrypt_get_key_size(MCRYPT_RIJNDAEL_256,MCRYPT_MODE_CBC))  */
  /*           );                                                           */
  /**************************************************************************/
  $AR->sessionCryptoKey = '3C0jOtwzBY1+8WBwvj19+zxwmKUOpT63BC/AOPBK1q0=';

  /**************************************************************************/
  /* Allowed HTTP methods for loader.web                                    */
  /* =============                                                          */
  /* Which HTTP methods are allowed and handled by loader.web in Ariadne?   */
  /* If no methods are configured Ariadne will allow any method             */
  /**************************************************************************/

  $AR->loader->web['AllowedMethods'] = array(
    "GET", "POST", "PUT", "DELETE", "HEAD"
  );

  /**************************************************************************/
  /* ImageMagick information                                                */
  /* For the photobook Ariadne needs to know where to find the ImageMagick  */
  /* utilities. The default setting works for a debian potato linux install */
  /* Don't forget to install ImageMagick. Older versions of ImageMagick     */
  /* refer to 'composite' as 'combine'.                                     */
  /**************************************************************************/

  $AR->IM->convert          = '/usr/bin/convert';
  $AR->IM->mogrify          = '/usr/bin/mogrify';
  $AR->IM->composite        = '/usr/bin/composite';
//$AR->IM->composite        = '/usr/bin/combine';
  $AR->IM->identify         = '/usr/bin/identify';

  /**************************************************************************/
  /* ImageMagick Processing limits                                          */
  /* uncomment the limits below to prevent large images from bringing down  */
  /* your server. Images larger than the hard limit won't be manipulated by */
  /* imagemagick at all. Images larger than the soft limit are scaled down  */
  /* when uploaded to fit into the soft limit, keeping aspect ratio's. The  */
  /* original unscaled version is also available through:                   */
  /*   ShowFile('file.original')                                            */
  /**************************************************************************/
  // $AR->IM->softLimit         = 1000000;  // 1 megapixel
  // $AR->IM->hardLimit         = 10000000; // 10 megapixel
  // $AR->IM->hardLimitBytes    = 2000000;  // 2 MB

  /**************************************************************************/
  /* ImageMagick Queueing options.                                          */
  /* Uncomment the following lines to adjust the default ImageMagick        */
  /* queueing options. The default is limited to 2 IM processes at a time   */
  /* per server. The default semKey is calculated with the ftok call        */
  /* This wil generated a unique semKey.                                    */
  /* timeout defaults to 60 seconds.                                        */
  /*                                                                        */
  /* Warning:                                                               */
  /* the semaphore limit is set on creating the semahore. If multiple       */
  /* ariadne installs have different limits, the first to create the        */
  /* semaphore wil set the limit.                                           */
  /*                                                                        */
  /* If you wish to use the ImageMagick Queuer you should prepend the IM    */
  /* commands in the following manner:                                      */
  /* $AR->IM->convert = '/path/to/ariadne/bin/im-queue.php /usr/bin/convert'*/
  /**************************************************************************/
  // $AR->IMQueue = array();
  // $AR->IMQueue["semKey"] = ftok('/',1);
  // $AR->IMQueue["max"] = 2;
  // $AR->IMQueue["timeout"] = 60;


  /**************************************************************************/
  /* SVN Configuration                                                      */
  /* To enable SVN support for templates set $AR->SVN->enabled to 'true'    */
  /* and point $AR->SVN->path to your svn binary on disk.                   */
  /* Use the SVN feature from within the Ariadne browser or, for per        */
  /* template options, from within the template browser.                    */
  /**************************************************************************/
  $AR->SVN->enabled      = true;
  $AR->SVN->path         = '/usr/bin/svn';


  /**************************************************************************/
  /* HTMLTidy information                                                   */
  /**************************************************************************/

  $AR->Tidy->path       = '/usr/bin/tidy';
  $AR->Tidy->options    = '--tidy-mark no --show-warnings yes -utf8 --force-output yes';

  /**************************************************************************/
  /* Webkit information                                                     */
  /**************************************************************************/

  $AR->Webkit2png->path     = '/usr/local/bin/webkit2png';
  $AR->Webkit2png->options  = '--log=/dev/null';
  $AR->Webkit2png->xvfbPath = 'xvfb-run';
  $AR->Webkit2png->xvfbOptions = '--server-args="-screen 0 1024x768x24+32"';


  /**************************************************************************/
  /* Grep information                                                       */
  /**************************************************************************/

  $AR->Grep->path           = '/bin/grep';
  $AR->Grep->options		= '-n -i -H';

