<?php
  /*************************************************************************/
  /* Ariadne Authentication Configuration                                  */
  /* ====================================                                  */
  /* This file contains configuration information for the Ariadne-         */
  /* Authentication module.                                                */
  /*************************************************************************/


  /*************************************************************************/
  /* Set authentication method                                             */
  /*************************************************************************/

  $auth_config["method"] = "default";


  /**************************************************************************/
  /* Generated password expiry. 
  /*************************************************************************/

  $auth_config["genpassexpiry"] = 3600 * 24; // expire generated passwords after 24 hours
?>