<?php
  /*************************************************************************/
  /* Ariadne Export Store Configuration                                    */
  /* ==================================                                    */
  /* This file contains configuration information for the Ariadne Export   */
  /* Store. There should be no need to change anything here.               */
  /* By default the store uses the settings from the main configuration    */
  /* file: ariadne.phtml                                                   */ 
  /*************************************************************************/

  /*************************************************************************/
  /* DBMS for this store                                                   */
  /*************************************************************************/

  $ax_config['dbms']                  = 'ax';

  /*************************************************************************/
  /* Ariadne Code Library (lib)                                            */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $ax_config['code']                  = $AR->dir->install.'\lib\\';
  } else {
    $ax_config['code']                  = $AR->dir->install.'/lib/';
  }

  /*************************************************************************/
  /* Ariadne Export temp directory                                         */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $ax_config['temp']                  = $AR->dir->install.'\files\temp\\';
  } else {
    $ax_config['temp']                  = $AR->dir->install.'/files/temp/';
  }

  /*************************************************************************/
  /* Tar configuration                                                     */
  /*************************************************************************/

  if ( $AR->OS=='WIN32' ) {
    $ax_config["tar"]["mode"] = "pear";
  } else {
    $ax_config["tar"]["mode"] = "system";
  }

  if ($ax_config["tar"]["mode"] == "system") {
    if ($AR->OS=='WIN32') {
      $tar_path=str_replace('\\', '/', $AR->dir->install);
      if (preg_match('/^([a-z]):/i', $tar_path, $regs)) {
        $tar_path="//".$regs[1].substr($tar_path,2);
      }
      $tar_path=preg_replace('/([^\])[ ]/', '\1\ ', $tar_path);
  
      $compress_cmd                     = '--use-compress-program='.($tar_path).'/bin/gzip.exe';
      $tar_cmd                          = $AR->dir->install.'\bin\tar.exe '.$compress_cmd;
      $ax_config["tar"]["error_handler"]   = '';
    } else {
      $tar_cmd                          = 'tar ';
      $ax_config["tar"]["error_handler"]   = ' 2> %s ';
    }

    $ax_config["tar"]["tar"]               = $tar_cmd." -z -f %archive% -c -C %destdir% %contents% %errorhandler%";
    $ax_config["tar"]["untar"]             = $tar_cmd." --no-same-owner -x -C %destdir% %contents% -f %archive% %errorhandler%";

    // set this to true if you are really sure that tar throws errors which
    // do not occur.

    $ax_config["tar"]["nofail"]            = false;
  }
?>
