<?php
  /*************************************************************************/
  /* Ariadne Export Store Configuration                                    */
  /* ==================================                                    */
  /* This file contains configuration information for the Ariadne Export   */
  /* Store. There should be no need to change anything here.               */
  /* By default the store uses the settings from the main configuration    */
  /* file: ariadne.phtml                                                   */ 
  /*************************************************************************/

  /*************************************************************************/
  /* DBMS for this store                                                   */
  /*************************************************************************/

  $ax_config['dbms']                  = 'ax';

  /*************************************************************************/
  /* Ariadne Code Library (lib)                                            */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $ax_config['code']                  = $AR->dir->install.'\lib\\';
  } else {
    $ax_config['code']                  = $AR->dir->install.'/lib/';
  }

  /*************************************************************************/
  /* Ariadne Export temp directory                                         */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $ax_config['temp']                  = $AR->dir->install.'\files\temp\\';
  } else {
    $ax_config['temp']                  = $AR->dir->install.'/files/temp/';
  }

?>
