<?php
  if (!$session_config) {
    $session_config = array();
  }

  /*************************************************************************/
  /* Ariadne Session Store Configuration                                   */
  /* ==================================                                    */
  /* This file contains configuration information for the Ariadne Session  */
  /* Store. E.g. which database on which host to connect to, the location  */
  /* of the code library (as the session store is just another Ariadne     */
  /* Object Store), etc.                                                   */
  /* By default the session store uses the settings from the main          */
  /* configuration file: ariadne.phtml                                     */ 
  /*************************************************************************/

  $session_config['prefix']      = 'session_';

  /*************************************************************************/
  /* Database Information:                                                 */
  /* Fill in the Hostname, and database name of the database server, and   */
  /* the username and password with which to connect to it.                */
  /* Prefix is an optional prefix to add to each table name ariadne uses   */
  /* for this store. This allows you to have a full Ariadne installation   */
  /* which uses just one database.                                         */
  /*************************************************************************/

  $session_config['dbms']        = $AR->DB->dbms;
  $session_config['host']        = $AR->DB->host;
  $session_config['database']    = $AR->DB->database;
  $session_config['user']        = $AR->DB->user;
  $session_config['password']    = $AR->DB->password;


  /*************************************************************************/
  /* Path Information:                                                     */
  /* Fill in the location of the Ariadne code library and the files        */
  /* file repository (used for temporary files, caching, templates, etc.)  */
  /*************************************************************************/

  /*************************************************************************/
  /* Ariadne Code Library (lib)                                            */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $session_config['code']        = $AR->dir->install.'\lib\\';
  } else {
    $session_config['code']        = $AR->dir->install.'/lib/';
  }

  /*************************************************************************/
  /* Ariadne Files Repository (files)                                      */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $session_config['files']       = $AR->dir->install.'\sessions\\';
  } else {
    $session_config['files']       = $AR->dir->install.'/sessions/';
  }

  /*************************************************************************/
  /* Ariadne Session Timeout                                               */
  /*************************************************************************/

  $session_config['timeout']     = 3600;

?>