<?php
  /*************************************************************************/
  /* Ariadne Object Store Configuration                                    */
  /* ==================================                                    */
  /* This file contains configuration information for the Ariadne Object   */
  /* Store. E.g. which database on which host to connect to, the location  */
  /* of the code library, etc.                                             */
  /* By default the store uses the settings from the main configuration    */
  /* file: ariadne.phtml                                                   */ 
  /*************************************************************************/

  $store_config['prefix']        = 'store_';

  /*************************************************************************/
  /* Database Information:                                                 */
  /* Fill in the Hostname, and database name of the database server, and   */
  /* the username and password with which to connect to it.                */
  /* Prefix is an optional prefix to add to each table name ariadne uses   */
  /* for this store. This allows you to have a full Ariadne installation   */
  /* which uses just one database.                                         */
  /*************************************************************************/

  $store_config['dbms']          = $AR->DB->dbms;
  $store_config['host']          = $AR->DB->host;
  $store_config['database']      = $AR->DB->database;
  $store_config['user']          = $AR->DB->user;
  $store_config['password']      = $AR->DB->password;
  $store_config['crypto']        = $AR->DB->crypto;

  /*************************************************************************/
  /* Fulltext search: If your databaseserver does not support fulltext     */
  /* search                                                                */
  /* (mysql < 3.23.23) you can disable it by setting this value to false   */
  /*************************************************************************/

  $store_config['fulltext']      = true;


  /*************************************************************************/
  /* Fulltext boolean search. Set to true if supported by your DB          */
  /* (it's standard set to false because boolean mode searches on fulltext */
  /* indexes are very slow; this is probably because mysql will run a      */
  /* search on the complete index, even if it is able to use a subset)     */
  /*************************************************************************/

  $store_config['fulltext_boolean'] = false;


  /*************************************************************************/
  /* Path Information:                                                     */
  /* Fill in the location of the Ariadne code library and the files        */
  /* file repository (used for temporary files, caching, templates, etc.)  */
  /*************************************************************************/

  /*************************************************************************/
  /* Ariadne Code Library (lib)                                            */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $store_config['code']          = $AR->dir->install.'\lib\\';
  } else {
    $store_config['code']          = $AR->dir->install.'/lib/';
  }

  /*************************************************************************/
  /* Ariadne Files Repository (files)                                      */
  /*************************************************************************/

  if( $AR->OS=='WIN32' ) {
    $store_config['files']         = $AR->dir->install.'\files\\';
  } else {
    $store_config['files']         = $AR->dir->install.'/files/';
  }

  /*************************************************************************/
  /* Lock Duration                                                         */
  /*************************************************************************/

  $store_config['lock_duration'] = -1;

?>
