<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/

	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=current($this->get(".","system.get.data.phtml"));
		} else {
			$scaffold = ar::getvar('scaffold');
			if ($scaffold && ar::exists($scaffold)) {
				$this->data = current(ar::get($scaffold)->call('system.get.data.phtml'));
			}
			if (!isset($this->data) || ar_error::isError($this->data)) {
				$this->data = new baseObject;
			}
		}

		$this->error = null;

		$userConfig = $this->loadUserConfig();
		$authconfig = $userConfig['authentication'];

		// unset the properties array, so no properties can be passed to this template.
		$properties = array();

		$properties["value"][]["value"]=$value;
		$this->data->name=$this->getdata("name","none");
		$properties["name"][]["value"]=$this->data->name;
		$properties["text"][]["value"]=$this->data->name;
		if ($this->arIsNewObject) {
			if ($login=$this->getdata("arNewFilename","none")) {
				if (strlen($login)>128) {
					$this->error = ar::error( $ARnls["err:logintoolong"], 1206);
				} else {
					$criteria["login"]["value"]["="]=$login;
				
					$loginexists = false;
					foreach ($authconfig['userdirs'] as $userdirpath) {
						$result=$this->find($userdirpath,$criteria,"system.get.phtml");
						if ($result) {
							$loginexists = true;
							break;
						}
					}

					if ($loginexists) {
						$this->error = ar::error( sprintf($ARnls["err:loginexists"],$login), 1207);
					} else {
						if (preg_match('/\{.*\}/',$login)) {
							$this->error = ar::error( $ARnls["err:donotuseid"], 1204);
						} else {
							$this->data->login=$login;
							$properties["login"][0]["value"]=$login;
						}
					}
				}
			} else {
				$this->error = ar::error( $ARnls["err:mustenterlogin"], 1205);
			}
		}
		if ($language=$this->getdata("language","none")) {
			$this->data->language=$language;
		}
		if ($interface=$this->getdata("interface","none")) {
			$this->data->interface=$interface;
		}
		if ($editor=$this->getdata("editor","none")) {
			$this->data->editor=$editor;
		}

		$this->data->email = $this->getdata("email","none");
		$this->data->telephone = $this->getdata("telephone","none");

		$this->data->groups = array();
		$groups = $this->getdata("groups", "none");
		if (is_array($groups)) {
			reset($groups);
			while (list($key, $val)=each($groups)) {
				if (substr($val, 0, 1) == "/") {
					$this->data->groups[$val] = $val;
				} else {
					$this->data->groups[$key] = $val;
				}
			}
		}
		$this->data->scaffold = $this->getdata('scaffold','none');

		if (!$this->error) {
			$arIsNewObject = $this->arIsNewObject;
			$arResult = $this->save($properties);
			if ( !$this->error && $arIsNewObject && $this->data->scaffold ) {
				$this->call('system.copy.scaffold.php', array('scaffold' => $this->data->scaffold) );
			}
		}
		global $cache_config;
		$cachestore=new cache($cache_config);
		$cachestore->onObjectSaved($this->id);
	}
?>