<?php
	/******************************************************************
	 classic.form.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: arNewType, newparent, arNewFilename
	 Grant needed: read
	 Global variables: none

	 This template displays the input form for this object.

	 no result.

	******************************************************************/
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<title><?php 
	$title=$ARnls["edit"]." ".current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
<?php
		if ($this->call("lock.init.phtml")) {
?>
</head>
<body bgcolor="white" onUnLoad="releaseLock()">
<form onSubmit="if (document.wgWizForm.wgWizSubmitHandler) { document.wgWizForm.wgWizSubmitHandler(); }">
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">
<table border="0" width="100%" cellspacing="0">
<tr>
	<td bgcolor="#404074" colspan="2">
		<font face="helvetica, sans-serif" color="white"><b><?php echo $ARnls["groupdata"]; ?> 
		<?php if (!$arNewType) { echo $data->login; } else { echo $arNewFilename; } ?></b></font>
	</td>
</tr><tr>
	<td align="right">
		<font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?> :</b></font>
	</td>
	<td>
		<input type="text" name="name" maxlength="50" value="<?php $this->showdata("name","none"); ?>">
	</td>
</tr><tr>
	<?php if (!$arNewType) { ?>
	<td bgcolor="#404074" colspan="2">
		<font face="helvetica, sans-serif" color="white"><b><?php echo $ARnls["membersofgroup"]; ?></b></font>
	</td>
</tr><tr>
	<td colspan="2">
		<?php
			$criteria["object"]["parent"]["="]="'$this->path'";
			$criteria["object"]["implements"]["="]="'puser'";
			$result=$this->find("",$criteria,"system.get.phtml");
			if ($result && is_array($result)) {
				while (list($key, $user)=each($result)) {
					echo "<img src=\"".$AR->dir->images."icons/puser.gif\">";
					echo "<a href=\"classic.set.user.phtml?action=delete&path=".
						RawUrlEncode($user->path)."\">".$user->data->name."</a> ( ".$user->data->login." )<br>\n";
				}
			}
		?>
		<table width="110%"><tr bgcolor="#EEEEEE">
			<td align="center">
				<?php
					$wgBrowsePath="/system/users/";
					$wgBrowseName="path";
					include($this->store->get_config("code")."widgets/browse/js.html");
					include($this->store->get_config("code")."widgets/browse/form.html");
				?>
				<input type="hidden" name="action" value="add">
				<input type="submit" name="arSubmit" value="<?php echo $ARnls["add"]; ?>">
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<p>
<script>
	<!-- set wgWizForm to the current form -->
	document.wgWizForm = document.forms[0];
</script>
<table width="100%" cellspacing="0" border="0">
<?php
	$configcache=$ARConfig->cache[$this->path];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->AR_implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}

	if ($hascustomdata) {
?><tr>
	<td colspan="2" bgcolor="#404074">
		<font face="helvetica, sans-serif" color="white">
		<?php 
			echo $ARnls["customdata"];
		?></font>
	</td>
</tr><tr>
	<td colspan="2">
		<?php
				$this->call("edit.object.data.custom.phtml", Array("arLanguage" => $selectednls));
		?>
	</td>
</tr>
<?php
	}
?>
<tr>
	<?php } // end if (!$arNewType) ?>
	<td>
		<?php if ($arNewType) { ?>
			<input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
		<?php } else { ?>
			<input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
			<?php
				$wgRecurseConfirm=$ARnls["q:removegroup"];
				$wgRecurseAction="delete";
				$wgRecurseTitle=$ARnls["delete"];
				include($this->store->get_config("code")."widgets/recurse/form.js");
				include($this->store->get_config("code")."widgets/recurse/form.html");
			?>
		<?php } ?>
	</td>
	<td align="right">
		<input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">	
	</td>
</tr>
</table>
<?php
	$this->call("lock.form.phtml");
?>
</form>
</body>
<?php
		}
	}
?>
