<?php
	/******************************************************************
	 classic.edit.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arSubmit
	 Grant needed: edit
	 Global variables: none

	 This template controls the flow between the form and save or delete
	 templates. 
	 First the classic.form.phtml template will be shown. This will set 
	 $arSubmit to either 'Save' or 'Delete'. Then the corresponding 
	 template will be called.

	 No result.

	******************************************************************/
	$ARCurrent->allnls=1;

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		if ($arSubmit==$ARnls["save"]) { // save data
			$this->call("classic.save.phtml",$arCallArgs);
		} else if ($arSubmit==$ARnls["cancel"]) {
			include($this->store->code."includes/cancel.phtml");
			$this->unlock();
		} else if ($next==$ARnls["add"]) { // add new user to this group
			if ($this->locked()) {
				// object locked, show us by who
				$this->call("show.locks.phtml");
			} else {
				$this->call("system.set.user.phtml",$arCallArgs);
			}
		} else {// edit it
			if ($this->lock()) {
				// object locked, show us by who
				$this->call("show.locks.phtml");
			} else {
				$this->call("classic.form.phtml",$arCallArgs);	
			}
		}
	}
?>