<?php
	/******************************************************************
	 classic.edit.phtml                                    Muze Ariadne
	 ------------------------------------------------------------------
	 Arguments: $arSubmit
	 Grant needed: edit
	 Global variables: none

	 This template controls the flow between the form and save or delete
	 templates. 
	 First the classic.form.phtml template will be shown. This will set 
	 $arSubmit to either 'Save' or 'Delete'. Then the corresponding 
	 template will be called.

	 No result.

	******************************************************************/
	$ARCurrent->allnls=1;

	if ($this->CheckLogin("edit") && $this->CheckConfig()) {
		if (!$arReturnPage) {
			$arReturnPage=$this->store->root.$this->parent;
		}
		if ($arSubmit==$ARnls["save"]) { // save data
			$this->call("classic.save.phtml",$arCallArgs);
		} else if ($arSubmit==$ARnls["cancel"]) {
			ldRedirect($arReturnPage);
		} else if ($arSubmit==$ARnls["add"]) { // add new user to this group
			$this->call("classic.set.user.phtml",$arCallArgs);
		} else {// edit it
			$this->call("classic.form.phtml",$arCallArgs);	
		}
	}
?>