<?php
  /******************************************************************
  ******************************************************************/
  if ($this->CheckSilent("read")) {
    if ($this->arIsNewObject) {
      $login=$this->getdata("arNewFilename","none");
    } else {
      $login=$this->data->login;
    }
?>
<table border="0" width="90%">
<tr>
  <td>
    <fieldset id="data">
    <legend><?php echo $ARnls["login"]." : ".$login; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
      <table border="0" align="center">
      <tr>
        <td>
          <span class="required"><?php echo $ARnls["name"]; ?></span>
        </td>
      </tr><tr>
        <td colspan="2">
          <input type="text" name="name" maxlength="50" 
            value="<?php $this->showdata("name", "none"); ?>">
        </td>
      </tr>
      </table>
    </fieldset>
  </td>
</tr>
</table>
<script>
  window.onload=init;
  function init() {
    document.wgWizForm["name"].focus();
  }
</script>
<?php
    $arResult["save"]["name"]["ereg"]=".+";
    $arResult["save"]["name"]["error"]=sprintf($ARnls["err:nonameentered"],$selectedlanguage);
    $arResult["next"]=$arResult["save"];
  }
?>