<?php
	/******************************************************************
	 object.new.flow.phtml                                 Muze Ariadne
	 ------------------------------------------------------------------

	 No result.

	******************************************************************/

	$configcache=$ARConfig->cache[$this->parent];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}
	$custom="edit.object.data.custom.phtml";

	$start="object.new.filename.phtml";
	$step1="edit.object.data.form.phtml";
	$save="edit.object.data.save.phtml";
	$cancel="object.new.cancel.phtml";
 
	$arFlow[0]["current"]=$this->getdata("wgWizCurrent","none");
	$arFlow[0]["cancel"]=$cancel;
	$arFlow[0]["save"]=$save;
 
	$i++;
	$arFlow[$i]["title"]=$ARnls["filename"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/info.png";
	$arFlow[$i]["template"]=$start;
	$arFlow[$i]["nolang"]=true;
	
	$i++;
	$arFlow[$i]["title"]=$ARnls["data"];
	$arFlow[$i]["image"]=$AR->dir->images."wizard/data.png";
	$arFlow[$i]["template"]=$step1;

	if ($hascustomdata) {
		$i++;
		$arFlow[$i]["title"]=$ARnls["customdata"];
		$arFlow[$i]["image"]=$AR->dir->images."wizard/customdata.png";
		$arFlow[$i]["template"]=$custom;
	}

	$wgWizCurrent=$this->getdata("wgWizCurrent","none");
	$wgWizControl=$this->getdata("wgWizControl","none");
	if ($wgWizCurrent==1) {
		$arNewFilename=$this->getdata("arNewFilename","none");
		if (!$arNewFilename) {
			$arFlow[0]["error"]=$ARnls["err:mustenterlogin"];
			$ARCurrent->wgWizNextStep=1;
		} else {
			$criteria["login"]["value"]["="]="'".AddSlashes($arNewFilename)."'";
			$criteria["object"]["implements"]["="]="'pgroup'";
			$result=$this->find("/system/groups/", $criteria, "system.get.phtml");
			if ($result) {
				$arFlow[0]["error"]=sprintf($ARnls["err:loginexists"],$newfilename);
				$ARCurrent->wgWizNextStep=1;
			}
		}	
	}
	$arResult=$arFlow;
?>