<?php
	$context    = $this->getContext(ARCALLINGCONTEXT);
	if ((($context["addProfileSettings"]??null) || $this->CheckSilent("edit")) && $this->CheckConfig()) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=current($this->get("","system.get.data.phtml"));

		if (($user=current($this->get($path, "system.get.phtml")))
			&& $user->AR_implements("puser")) {
			$user->call("system.set.group.phtml", array(
							"action"	=> $action,
							"path"		=> $this->path,
							"id"		=> $this->data->login));

			if ($action=="add") {
				$this->sgBegin('add(pshortcut)');
					$this->call('system.new.phtml', array(
							$ARConfig->nls->default  => array(
								'name' => $user->data->name
							),
							'arNewType'     => 'pshortcut',
							'arNewFilename' => basename($path),
							'keepurl'       => true,
							'path'			=> $path
					));
					//$this->store->link($path, $this->path.$user->data->login."/");
				$this->sgEnd();
			} else {
				$login = $user->data->login;
				if ($login && $login!=".") {
					$linkedObj = current($this->get($this->path.$login, 'system.get.phtml'));
					if ($linkedObj && $linkedObj->AR_implements('pshortcut')) {
						$this->sgBegin('>delete(pshortcut)');
							$linkedObj->call('system.delete.phtml');
						$this->sgEnd();
					} else {
						$this->store->delete($this->path.$login."/");
					}
				}
			}
		}
	}
?>
