<?php
	/******************************************************************
	 system.save.data.phtml                                Muze Ariadne
	 ------------------------------------------------------------------
 
	******************************************************************/
	if ((($this->arIsNewObject && $this->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {
		if (!$this->arIsNewObject) {
			// first make sure that the object is clean (data can only be set via 
			// the defined interface: $arCallArgs)
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		} else {
			$this->data=new object;
		}


		$this->data->name=$this->getdata("name","none");
		$properties["name"][]["value"]="'".AddSlashes($this->data->name)."'";
		$properties["text"][]["value"]="'".AddSlashes($this->data->name)."'";
		if ($this->arIsNewObject) {
			$login=$this->getdata("arNewFilename","none");
			if ($login) {
				$criteria["login"]["value"]["="]="'".AddSlashes($login)."'";
				$criteria["object"]["implements"]["="]="'pgroup'";
				$result=$this->find("/system/groups/",$criteria,"system.get.phtml");
				if ($result) {
					$this->error=sprintf($ARnls["err:loginexists"],$login);
				} else {
					if (ereg('\{.*\}',$login)) {
						$this->error=$ARnls["err:donotuseid"];
					} else {
						$this->data->login=$login;
						$properties["login"][0]["value"]="'".AddSlashes($this->data->login)."'";
					}
				}
			} else {
				$this->error=$ARnls["err:mustenterlogin"];
			}
		}
		$this->save($properties);
		$this->ClearCache();
	}
?>