<?php
	if ((($this->arIsNewObject &&
			($parentobj=current($this->get($this->parent, "system.get.phtml"))) &&
			$parentobj->CheckLogin("add", $this->type)) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		$criteria["login"]["value"]["="]=$this->data->login;
		$result = $this->find("/system/groups/", $criteria, "system.get.phtml");
		if (is_array($result) && current($result)) {
			$this->error = "group '".$this->data->login."' already exists";
		} else {
			$this->store->save(
				$this->path,
				$this->type,
				$this->data,
				$this->properties,
				$this->vtype,
				$this->priority);
				$this->error = $this->store->error;
		}
	}
?>
