<?php
	display("importing grants for group ".$this->data->login."\n");
	$paths=$ARCurrent->grants_list["pgroup"][$this->data->login];
	while (list($path, $grants)=each($paths)) {
		$newpath=$importDestPath.substr($path, strlen($importRootPath));
		display("	$newpath\n");

		$result=@current($this->get($newpath, "system.import.grants.phtml", 
												Array(
													"importDestPath" => $importDestPath,
													"importRootPath" => $importRootPath,
													"grants" => &$grants,
													"type" 	=> "pgroup" ,
													"id"	=> $this->data->login
												)));
		if ($result) {
			@reset($grants);
			while (list($grant,)=each($grants)) {
				$this->data->usergrants[$newpath][$grant]=1;
			}
		}
	}
	$this->save();
?>