<?php
	$context    = $this->getContext(ARCALLINGCONTEXT);
	if (($context["addProfileSettings"] || $this->CheckSilent("edit")) && $this->CheckConfig()) {
		// first make sure that the object is clean (data can only be set via 
		// the defined interface: $arCallArgs)
		$this->data=current($this->get("","system.get.data.phtml"));

		if (($user=current($this->get($path, "system.get.phtml")))
			&& $this->store->AR_implements($user->type, "puser")) {
			$user->call("system.set.group.phtml", Array(
							"action"	=> $action,
							"path"		=> $this->path,
							"id"		=> $this->data->login));
			if ($action=="add") {
				$this->store->link($path, $this->path.$user->data->login."/");
			} else {
				if (($login=$user->data->login) && $login!=".") {
					$this->store->delete($this->path.$login."/");
				}
			}
		}
		//calculate and save new member properties
		$members=$this->ls(".","system.get.login.phtml");
		while (list($key, $member)=@each($members)) {
			$properties["members"][]["login"]="'".AddSlashes($member)."'";
		} 
		if (!$properties["members"]) {
			// make sure the members property is cleared
			$properties["members"]=1;
		}
		$this->save($properties);
	}
?>