<?php
  /******************************************************************
   classic.form.phtml                                      Muze Ariadne v2.1
   ------------------------------------------------------------------
   Called by 'classic.edit.phtml' and 'classic.new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<html>
<head>
<?php
	// lock this object first, if it succeeds, it will expose some js functions
	if ($this->call("lock.init.phtml")) {
?>
<title><?php 
	$title=$ARnls["edit"]." ".current($this->get("/system/ariadne/types/".$this->type."/","system.get.name.phtml")); 
	echo $title;
?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $AR->dir->styles; ?>form.css">
</head>
<body bgcolor="white" onUnload="releaseLock()">
<?php
  $this->parents($this->path, "show.link.phtml","target=classic.edit.phtml");
?>
<form method="post"  onSubmit="if (document.wgWizForm.wgWizSubmitHandler) { document.wgWizForm.wgWizSubmitHandler(); }">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="arNewType" value="<?php echo $arNewType; ?>">
<input type="hidden" name="arNewFilename" value="<?php echo $arNewFilename; ?>">
<input type="hidden" name="arReturnPage" value="<?php echo $arReturnPage; ?>">

<table border="0" cellspacing="0" width="100%"> 
<tr>
  <td bgcolor="#404074">
    <?php
      $wgNLSpretext="<font face=\"helvetica, sans-serif\" size=\"+1\" color=\"white\"><b>".
        $ARnls["editscenario"].":</b></font><br>";
      include($this->store->code."widgets/nls/form.phtml");
    ?>
  </td>
</tr>
</table>
<table border="0">
<tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <input type="text" name="<?php echo $selectednls; ?>[name]" maxlength="50" value="<?php $this->showdata("name",$selectednls); ?>">
  </td>
</tr><tr>
  <td align="right">
    <font face="helvetica, sans-serif"><?php echo $ARnls["priority"]; ?>&nbsp;:</font>
  </td>
  <td>
    <input type="text" name="priority" size="5" value="<?php $this->showdata("priority","none"); ?>">
  </td>
</tr><tr>
  <td align="right" valign="top">
    <font face="helvetica, sans-serif"><?php echo $ARnls["summary"]; ?>&nbsp;:</font>
  </td>
  <td>
    <textarea name="<?php echo $selectednls."[summary]"; ?>" cols="50" rows="4" wrap="soft"><?php
        echo ereg_replace("&","&amp;",$this->getdata("summary",$selectednls));
    ?></textarea>
  </td>
</tr><tr>
  <td align="right" valign="top">
    <font face="helvetica, sans-serif"><?php echo $ARnls["effect"]; ?>&nbsp;:</font>
  </td>
  <td>
    <textarea name="<?php echo $selectednls."[effect]"; ?>" cols="50" rows="4" wrap="soft"><?php
        echo ereg_replace("&","&amp;",$this->getdata("effect",$selectednls));
    ?></textarea>
  </td>
</tr>
</table>
<table border="0" cellspacing="0" width="100%"> 
<tr>
  <td bgcolor="#404074">
    <font face="helvetica, sans-serif" color="white" size="+1"><b><?php echo $ARnls["display"]; ?></b>  
  </td>
</tr>
</table>
<table border="0" width="300">
<td></td><td align="left">
<b><font face="helvetica,sans-serif"><?php echo $ARnls["start"]; ?></font></b>
</td><td align="left">
<b><font face="helvetica,sans-serif"><?php echo $ARnls["end"]; ?></font></b>
</td></tr>
<?php
	$displays=$this->ls("/system/newspaper/displays/","system.get.value.phtml");
	while (is_array($displays) && list($key,$val)=each($displays)) {
?>
<tr><td align="left">
<font face="helvetica,sans-serif"><?php echo $val; ?></font>
</td><td align="left">
<input type="text" size="4" name="display[<?php echo $val; ?>][start]" value="<?php echo $data->display[$val]["start"]; ?>">
</td><td align="left">
<input type="text" size="4" name="display[<?php echo $val; ?>][end]" value="<?php echo $data->display[$val]["end"]; ?>">
</td>
</tr>
<?php
	}
?>
</table>
<br><br>

<p>

<script>
	<!-- set wgWizForm to the current form -->
	document.wgWizForm = document.forms[0];
</script>
<table width="100%" cellspacing="0" border="0">
<?php
	$configcache=$ARConfig->cache[$this->path];
	if ($configcache->custom) {
		reset($configcache->custom);
		while (list($key, $definition)=each($configcache->custom)) {
			if (($definition["type"]==$this->type) ||
				($definition["inherit"] && ($this->implements($definition["type"])))) {
				$hascustomdata=true;
				break;
			}
		}
	}

	if ($hascustomdata) {
?><tr>
	<td colspan="2" bgcolor="#404074">
		<font face="helvetica, sans-serif" color="white">
		<?php 
			echo $ARnls["customdata"];
		?></font>
	</td>
</tr><tr>
	<td colspan="2">
		<?php
				$this->call("edit.object.data.custom.phtml", Array("arLanguage" => $selectednls));
		?>
	</td>
</tr>
<?php
	}
?><tr bgcolor="#404074">
  <td>
    <?php if ($arNewType) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="arSubmit" value="<?php echo $ARnls["cancel"]; ?>">
<?php
    $wgRecurseConfirm=$ARnls["q:removescenario"];
    $wgRecurseAction="delete";
    $wgRecurseTitle=$ARnls["delete"];
    include($this->store->code."widgets/recurse/form.js");
    include($this->store->code."widgets/recurse/form.html");
?>
    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="arSubmit" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>
</form>
<?php
		$this->call("lock.form.phtml");
	} // end lock-if-statement
?>
</body>
<?php
  }
?>