<?php
	/******************************************************************
	 edit.object.data.displays.phtml Muze Ariadne v2.0b
	 ------------------------------------------------------------------
	 Arguments: newtype, newparent, newfilename
	 Grant needed: read
	 Global variables: none

	 This template displays the data entry step for creating or editing
	 an object. The template is meant to be used as part of a wizard.

	 no result.

	******************************************************************/
	if ($this->CheckSilent("read") && $this->CheckConfig()) {
?>
<script language="javascript">
<!--
	function show_display_values() {
		sbox = document.wgWizForm["display-select"];
		if ( sbox.selectedIndex != -1 ) {
			display = sbox.options[ sbox.selectedIndex ].value;
			if (display) {
				if (! (document.wgWizForm["display-start"].value = document.wgWizForm[ "display[" + display + "][start]" ].value)) {
					// default to zero
					document.wgWizForm["display-start"].value = 0;
				}
				if (! (document.wgWizForm["display-end"].value = document.wgWizForm[ "display[" + display + "][end]" ].value)) {
					// default to zero
					document.wgWizForm["display-end"].value = 0;
				}
			}
		}
	}

	function commit_display_values() {
		sbox = document.wgWizForm["display-select"];

		if ( sbox.selectedIndex != -1 ) {
			display = sbox.options[ sbox.selectedIndex ].value;
			if (display) {
				document.wgWizForm[ "display[" + display + "][start]" ].value = document.wgWizForm["display-start"].value;
				document.wgWizForm[ "display[" + display + "][end]" ].value = document.wgWizForm["display-end"].value;
			}
		}
	}

//-->
</script>

<table border="0" width="90%">
<tr>
	<td>
		<?php 
			$arLanguage=$this->getdata("arLanguage","none");
			if (!$arLanguage) {
			 $arLanguage=$ARConfig->nls->default;
			}
			$selectednls=$arLanguage;
			$selectedlanguage=$ARConfig->nls->list[$arLanguage];
			$flag="<img src=\"".$AR->dir->images."nls/small/$selectednls.gif\" alt=\"$selectedlanguage\">";
		?>
			<table border="0" align="center" width="80%">
			<tr>
				<td align="center">
				<fieldset id="data">
				<legend><?php echo $ARnls["priority"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
					<table>
					<tr>
						<td>
							<input type="text" name="priority" maxlength="4" size="6"
								value="<?php $this->showdata("priority", "none"); ?>">
						</td>
					</tr>
					</table>
				</td>
				</fieldset>
			</tr><tr>
				<td align="center">
				<br>

				<fieldset id="data">
				<legend><?php echo $ARnls["display"]; ?></legend><img src="<?php echo $AR->dir->images; ?>dot.gif" alt="" width="1" height="1"><br>
				<table>
					<tr>
						<td>
							<?php echo $ARnls["id"]; ?>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<select name="display-select" onChange=" show_display_values() " style = "width : 150px">
							<?php
								$displays=$this->ls("/system/newspaper/displays/","system.get.value.phtml");
								while (is_array($displays) && (list($key, $val)=each($displays))) {
									echo "<option value=\"$val\">$val</option>";
								}
							?>
							</select>
							<?php
								// now setup the hidden form values
								if (is_array($displays)) {
									$ddata=$this->getdata("display", "none");
									reset($displays);
									while (list($key, $val)=each($displays)) {
										?>
											<input type="hidden" name="display[<?php echo $val; ?>][start]" value="<?php echo $ddata[$val]["start"]; ?>">
											<input type="hidden" name="display[<?php echo $val; ?>][end]" value="<?php echo $ddata[$val]["end"]; ?>">
										<?php
									}
								}
							?>
						</td>
					</tr><tr>
						<td>
							<?php echo $ARnls["start"]; ?>
						</td><td align="right">
							<?php echo $ARnls["end"]; ?>
						</td>
					</tr><tr>
						<td>
							<input type="text" onChange="commit_display_values()" size="4" name="display-start" value="">
						</td><td align="right">
							<input type="text" onChange="commit_display_values()" size="4" name="display-end" value="">
						</td>
					</tr>
				</table>
				</fieldset>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<script>
	window.onload=init;
	function init() {
		show_display_values();
	}
</script>
<?php
	}
?>