<?php
  /******************************************************************
   form.phtml                                      Muze Ariadne v2.0b
   ------------------------------------------------------------------
   Called by 'edit.phtml' and 'new.phtml'
   Arguments: newtype, newfilename
   Grant needed: read
   Interface/Widget: all
   Global variables: none

   This template displays the input form for this object. If $newtype
   is set, the form is called to create a new object. This means that
   $data points to the data of the object creating it!
   $newtype, $newfilename and $newparent are saved in hidden input
   fields for further processing by whatever template is called when
   the form is processed.
   The html form tag in a form template should always leave the action
   property out.

   This template must be available in every pobject derivative's
   template directory.

   no result.

  ******************************************************************/
  if ($this->CheckLogin("read") && $this->CheckConfig()) {
?>
<body bgcolor="white">
<?php
  $this->parents($this->path, "ShowLink.phtml","target=edit.phtml");
?>
<form method="post">
<!-- hidden form variables needed by new.phtml/save.phtml -->
<input type="hidden" name="newtype" value="<?php echo $newtype; ?>">
<input type="hidden" name="newparent" value="<?php echo $this->path; ?>">
<input type="hidden" name="newfilename" value="<?php echo $newfilename; ?>">
<input type="hidden" name="returnpage" value="<?php echo $returnpage; ?>">
<?php
include($this->store->code."widgets/formlock/js.html");
?>

<table border="0" cellspacing="0" width="100%"> 
<tr>
  <td bgcolor="#404074">
    <?php
      $wgNLSpretext="<font face=\"helvetica, sans-serif\" size=\"+1\" color=\"white\"><b>".
        $ARnls["editscenario"].":</b></font><br>";
      include($this->store->code."widgets/nls/form.phtml");
    ?>
  </td>
</tr>
</table>
<table border="0">
<tr>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["name"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <input type="text" name="<?php echo $nls; ?>[name]" maxlength="50" value="<?php $this->showdata("name",$nls); ?>">
  </td>
  <td align="right">
    <font face="helvetica, sans-serif"><b><?php echo $ARnls["priority"]; ?>&nbsp;:</b></font>
  </td>
  <td>
    <input type="text" name="priority" size="5" value="<?php if (!$newtype) echo $data->priority; else echo 0; ?>">
  </td>

</tr>
</table>

<br>
<table>

<table border="0">
<tr><td align="left">
<b><?php echo $ARnls["display"]; ?></b>
</td><td align="left">
<b><?php echo $ARnls["start"]; ?></b>
</td><td align="left">
<b><?php echo $ARnls["end"]; ?></b>
</td></tr>
<?php
	$displays=$this->ls("/system/newspaper/displays/","GetValue.phtml");
	while (is_array($displays) && list($key,$val)=each($displays)) {
?>
<tr><td align="left">
<b><?php echo $val; ?></b>
</td><td align="left">
<input type="text" size="4" name="<?php echo $val; ?>_start" value="<?php echo $data->display[$val]["start"]; ?>">
</td><td align="left">
<input type="text" size="4" name="<?php echo $val; ?>_end" value="<?php echo $data->display[$val]["end"]; ?>">
</td>
</tr>
<?php
	}
?>
</table>
<br><br>

<p>
<table width="100%" cellspacing="0" border="0">
<tr bgcolor="#404074">
  <td>
    <?php if ($newtype) { ?>
      <input type="button" name="Back" value="<?php echo $ARnls["back"]; ?>" onClick="history.back()">
    <?php } else { ?>
      <input type="submit" name="next" value="<?php echo $ARnls["cancel"]; ?>">
<?php
    $wgRecurseConfirm=$ARnls["q:removescenario"];
	$wgRecurseAction="delete";
	$wgRecurseTitle=$ARnls["delete"];
    include($this->store->code."widgets/recurse/form.js");
	include($this->store->code."widgets/recurse/form.html");
?>
    <?php } ?>
  </td>
  <td align="right">
    <input type="submit" name="next" value="<?php echo $ARnls["save"]; ?>">  
  </td>
</tr>
</table>
</form>
<font face="helvetica, sans-serif" size="2">
<?php
  $this->ls("","Show.phtml","target=edit.phtml");
?>
</font>
</body>
<?php
  }
?>