<?php
	if ((($this->arIsNewObject && $this->CheckLogin("add")) ||
			(!$this->arIsNewObject && $this->CheckLogin("edit"))) && 
			$this->CheckConfig()) {

		if (!$this->arIsNewObject) {
		    $this->data=@current($this->get(".","system.get.data.phtml"));
		}


		if (!isset(${$ARConfig->nls->default}) && !isset($this->data->{$ARConfig->nls->default})) { // default language for this path
			$error=sprintf($ARnls["err:nodatafordefaultlanguage"],$AR->nls->list[$ARConfig->nls->default]);
		} else {
			if (!$this->data->nls) {
				$this->data->nls=new object;
			}
			$this->data->nls->default=$ARConfig->nls->default;
			reset($AR->nls->list);
			while (list($key, $value)=each($AR->nls->list)) {
				if (isset(${$key})) {
					if (!$this->data->$key) {
						$newnlsdata=new object;
					} else {
						$newnlsdata=$this->data->$key;
					}
					if (!$this->getdata("name", $key)) {
						$error=sprintf($ARnls["err:nonameentered"],$AR->nls->list[$key]);
					}
					$newnlsdata->name=$this->getdata("name", $key);
					$properties["name"][]["value"]="'".AddSlashes($this->getdata("name", $key))."'";
					$newnlsdata->summary=$this->getdata("summary", $key);
					$properties["text"][]["value"]="'".AddSlashes($this->getdata("summary", $key))."'";
					$newnlsdata->effect=$this->getdata("effect", $key);
					$this->data->$key=$newnlsdata;
					$this->data->nls->list[$key]=$value;
				}
			}
		}

		$this->data->priority = $this->getdata("priority", "none");

		$this->data->display = $this->getdata("display", "none");

		$this->save($properties);
	}
?>